# Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import logging
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
import talib as ta
from torch import optim
from torch.utils.data import DataLoader, Dataset, TensorDataset, random_split
from tqdm import tqdm
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.optim import AdamW
from utils import scale, inverse_scale, inverse_scale_pair, inspect
from utils.paths import CHECKPOINTS_DIR
from pypfopt import risk_models, expected_returns, plotting, EfficientFrontier

# Own Libs
from config import *
from entities import *
from strategies import *
from datasets import *
from engine import Engine
from models import DiffusionTransformer, Diffusion

# Setup

In [2]:
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('matplotlib').setLevel(logging.WARNING)

In [3]:
cfg = TrainConfig(epochs=10000, window_size=64)
window_size = cfg.window_size
device = cfg.device
batch_size = cfg.batch_size
epochs = cfg.epochs
sim_steps = cfg.steps_to_sim
num_sims = cfg.num_sims

# Optimizer
weight_decay = cfg.optimizer.weight_decay
lr = cfg.optimizer.lr

time_range = {
    'start_date': '2021-01-01',
    'end_date': '2024-12-31'
}

ddpm = {
    'timesteps': int(1000),
    'beta_start': 0.0001,
    'beta_end': 0.02
}

ddpm_transformer = {
    'window_size': window_size,
    'd_model': 64,
    'nhead': 4,
    'num_layers': 32,
    'dim_feedforward': 512,
    'dropout': 0.1
}

# Data [N, W, A, F]
**[N, T, A, F]** means: 
* **N**: Num of Window or Num of Batch
* **W**: Window
* **A**: Assets
* **F**: Features or Channels

In [4]:
def time_range_info(df):
    info = (df.index.min(), df.index.max())
    print(f"Data range: {info[0]} to {info[1]}")
    
    duration = df.index.max() - df.index.min()
    print(f"Total duration: {duration}")

def time_range_mask(df, start_date, end_date):
    mask = (df.index >= start_date) & (df.index <= end_date)
    return mask

In [5]:
symbols = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO']
freq = "1d"

# Basket
basket = Basket(symbols=symbols)
basket.load_all_assets(freq=freq)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

DEBUG:entities.basket:Initialized Asset Basket: ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO'] with 0 assets which loaded.
INFO:entities.basket:Starting batch load for 14 symbols...
DEBUG:entities.basket:Attempting to load AAPL...
DEBUG:entities.asset:Initialized Asset: AAPL with 2724 rows.
INFO:entities.basket:Successfully loaded AAPL (2724 rows).
DEBUG:entities.basket:Attempting to load TSLA...
DEBUG:entities.asset:Initialized Asset: TSLA with 2760 rows.
INFO:entities.basket:Successfully loaded TSLA (2760 rows).
DEBUG:entities.basket:Attempting to load MSFT...
DEBUG:entities.asset:Initialized Asset: MSFT with 2724 rows.
INFO:entities.basket:Successfully loaded MSFT (2724 rows).
DEBUG:entities.basket:Attempting to load NVDA...
DEBUG:entities.asset:Initialized Asset: NVDA with 2724 rows.
INFO:entities.basket:Successfully loaded NVDA (2724 rows).
DEBUG:entities.basket:Attempting to load GOOGL...
DEBUG:entities.asset:Initialized Asset: GOOGL with 2760 rows.
INFO:entities.basket:Successfully loaded GOOGL (2760 rows).
DEBUG:entities.basket:Attempting to load AMZN...
DEBUG:entities.asset:Initialized Asset: AMZN with 2760 rows.
INFO:entities.basket:Successfully loaded AMZN (2760 rows).
DEBUG:entities.basket:Attempting to load GOOG...
DEBUG:entities.asset:Initialized Asset: GOOG with 1464 rows.
INFO:entities.basket:Successfully loaded GOOG (1464 rows).
DEBUG:entities.basket:Attempting to load META...
DEBUG:entities.asset:Initialized Asset: META with 2760 rows.
INFO:entities.basket:Successfully loaded META (2760 rows).
DEBUG:entities.basket:Attempting to load AVGO...
DEBUG:entities.asset:Initialized Asset: AVGO with 2724 rows.
INFO:entities.basket:Successfully loaded AVGO (2724 rows).
DEBUG:entities.basket:Attempting to load ORCL...
DEBUG:entities.asset:Initialized Asset: ORCL with 2724 rows.
INFO:entities.basket:Successfully loaded ORCL (2724 rows).
DEBUG:entities.basket:Attempting to load CRM...
DEBUG:entities.asset:Initialized Asset: CRM with 2724 rows.
INFO:entities.basket:Successfully loaded CRM (2724 rows).
DEBUG:entities.basket:Attempting to load ADBE...
DEBUG:entities.asset:Initialized Asset: ADBE with 2724 rows.
INFO:entities.basket:Successfully loaded ADBE (2724 rows).
DEBUG:entities.basket:Attempting to load AMD...
DEBUG:entities.asset:Initialized Asset: AMD with 2724 rows.
INFO:entities.basket:Successfully loaded AMD (2724 rows).
DEBUG:entities.basket:Attempting to load CSCO...
DEBUG:entities.asset:Initialized Asset: CSCO with 2724 rows.
INFO:entities.basket:Successfully loaded CSCO (2724 rows).
INFO:entities.basket:Batch load complete. Success: 14/14. Total assets in basket: 14

Basket data shape: (2760, 70)

                 AAPL                                                \
                Close       High        Low       Open       Volume
Date
2015-01-02  24.261047  24.729270  23.821672  24.718174  212818400.0
2015-01-05  23.577574  24.110150  23.391173  24.030263  257142000.0
2015-01-06  23.579794  23.839424  23.218085  23.641928  263188400.0
2015-01-07  23.910433  24.010290  23.677430  23.788384  160423600.0
2015-01-08  24.829119  24.886815  24.121236  24.238848  237458000.0

                 TSLA                                             ...   AMD  \
                Close       High        Low       Open    Volume  ... Close
Date                                                              ...
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  ...  2.67
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  ...  2.66
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  ...  2.63
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  ...  2.58
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  ...  2.61

                                               CSCO                        \
            High   Low  Open      Volume      Close       High        Low
Date
2015-01-02  2.67  2.67  2.67         0.0  19.815605  20.181631  19.650534
2015-01-05  2.70  2.64  2.67   8878200.0  19.420874  19.700776  19.377812
2015-01-06  2.66  2.55  2.65  13912500.0  19.413698  19.865848  19.406522
2015-01-07  2.65  2.54  2.63  12377600.0  19.593126  19.664896  19.363463
2015-01-08  2.65  2.56  2.59  11136600.0  19.743843  20.160107  19.715135


                 Open      Volume
Date
2015-01-02  19.995029  22926500.0
2015-01-05  19.607475  29460600.0
2015-01-06  19.478291  47297600.0
2015-01-07  19.478295  27570800.0
2015-01-08  19.765374  40907000.0

[5 rows x 70 columns]

## Time Range Custom

In [6]:
time_range_info(basket.data)

for symbol, asset in basket.assets.items():
    mask = time_range_mask(asset.data, time_range['start_date'], time_range['end_date'])
    asset.data = asset.data[mask]

time_range_info(basket.data)

Data range: 2015-01-02 00:00:00 to 2025-12-22 00:00:00
Total duration: 4007 days 00:00:00
Data range: 2021-01-04 00:00:00 to 2024-12-31 00:00:00
Total duration: 1457 days 00:00:00

## Features/Channels ($F$)
1. Find Joint Distribution $F_{\text{date\ A}} \cap F_{\text{date\ B}}$ with intersection
2. Select $F$ to norm as Return values

In [7]:
targets = ["Close"]
features = basket.get_unique_features()
print(f"Features:\t{features}\nTargets:\t{targets}")

Features:	['Close', 'High', 'Low', 'Open', 'Volume']
Targets:	['Close']

In [8]:
print(f"Basket data shape before Joint: {basket.data.shape}")

joint_strategy = IntersectionStrategy()
basket.align(joint_strategy)

print(f"Basket data shape after Joint: {basket.data.shape}")

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 1005 rows
DEBUG:entities.basket:Aligned data shape: (1005, 70)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 1005)

Basket data shape before Joint: (1005, 70)
Basket data shape after Joint: (1005, 70)

In [9]:
basket.to_returns(features=targets, log=True, keep=False)
targets = basket.get_keyword_features("Returns")
features = basket.get_unique_features()

print(f"Features:\t{features}\nTargets:\t{targets}")
basket.data.head(5)

DEBUG:entities.asset:AAPL converted to Returns (log=True)
DEBUG:entities.asset:TSLA converted to Returns (log=True)
DEBUG:entities.asset:MSFT converted to Returns (log=True)
DEBUG:entities.asset:NVDA converted to Returns (log=True)
DEBUG:entities.asset:GOOGL converted to Returns (log=True)
DEBUG:entities.asset:AMZN converted to Returns (log=True)
DEBUG:entities.asset:GOOG converted to Returns (log=True)
DEBUG:entities.asset:META converted to Returns (log=True)
DEBUG:entities.asset:AVGO converted to Returns (log=True)
DEBUG:entities.asset:ORCL converted to Returns (log=True)
DEBUG:entities.asset:CRM converted to Returns (log=True)
DEBUG:entities.asset:ADBE converted to Returns (log=True)
DEBUG:entities.asset:AMD converted to Returns (log=True)
DEBUG:entities.asset:CSCO converted to Returns (log=True)

Features:	['Close_Log_Returns', 'High', 'Low', 'Open', 'Volume']
Targets:	{'Close_Log_Returns'}

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                  TSLA                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  246.946671  239.733337  241.220001   96735600          0.007291
2021-01-06  258.000000  249.699997  252.830002  134100000          0.027995
2021-01-07  272.329987  258.399994  259.209991  154496700          0.076448
2021-01-08  294.829987  279.463318  285.333344  225166500          0.075481
2021-01-11  284.809998  267.873322  283.133331  177904800         -0.081442

            ...        AMD                                                    \
            ...       High        Low       Open    Volume Close_Log_Returns
Date        ...
2021-01-05  ...  93.209999  91.410004  92.099998  34208000          0.005079
2021-01-06  ...  92.279999  89.459999  91.620003  51911700         -0.026654
2021-01-07  ...  95.510002  91.199997  91.330002  42897200          0.052090
2021-01-08  ...  96.400002  93.269997  95.980003  39816400         -0.006114
2021-01-11  ...  99.230003  93.760002  94.029999  48600200          0.027839

                 CSCO
                 High        Low       Open    Volume Close_Log_Returns
Date
2021-01-05  38.335017  37.734811  37.995770  17763700          0.000455
2021-01-06  39.030909  38.178440  38.387210  21823100          0.009505
2021-01-07  39.239677  38.422000  38.448099  18218800          0.012534
2021-01-08  39.500638  38.491593  38.691662  20936300          0.002222
2021-01-11  39.970367  39.161391  39.274475  25058200          0.006636

[5 rows x 70 columns]

## Add Indicators as Features ($F$)

In [10]:
# Indicator
time_prd = 20
fast_prd, slow_prd, signal_prd = 12, 26, 9

for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        s = df[target]
        
        df[f"SMA_{time_prd} {target}"] = ta.SMA(s, timeperiod=time_prd)
        df[f"EMA_{time_prd} {target}"] = ta.EMA(s, timeperiod=time_prd)
        df[f"RSI_{time_prd} {target}"] = ta.RSI(s, timeperiod=time_prd)
        
        macd, signal, hist = ta.MACD(s, fastperiod=fast_prd, slowperiod=slow_prd, signalperiod=signal_prd)
        df[f"MACD {target}"] = macd
        df[f"MACD_Sig {target}"] = signal
        df[f"MACD_Hist {target}"] = hist

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (1004, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-01-05                      NaN                    NaN
2021-01-06                      NaN                    NaN
2021-01-07                      NaN                    NaN
2021-01-08                      NaN                    NaN
2021-01-11                      NaN                    NaN

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-01-05                        NaN  ...  37.734811  37.995770  17763700
2021-01-06                        NaN  ...  38.178440  38.387210  21823100
2021-01-07                        NaN  ...  38.422000  38.448099  18218800
2021-01-08                        NaN  ...  38.491593  38.691662  20936300
2021-01-11                        NaN  ...  39.161391  39.274475  25058200

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-01-05          0.000455                      NaN
2021-01-06          0.009505                      NaN
2021-01-07          0.012534                      NaN
2021-01-08          0.002222                      NaN
2021-01-11          0.006636                      NaN

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-01-05                    NaN                        NaN
2021-01-06                    NaN                        NaN
2021-01-07                    NaN                        NaN
2021-01-08                    NaN                        NaN
2021-01-11                    NaN                        NaN


           MACD_Hist Close_Log_Returns
Date
2021-01-05                         NaN
2021-01-06                         NaN
2021-01-07                         NaN
2021-01-08                         NaN
2021-01-11                         NaN

[5 rows x 154 columns]

## Additional! Shift data for future simulation (forward)

In [11]:
for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        df[f"SMA_{time_prd} {target}"] = df[f"SMA_{time_prd} {target}"].shift(1)
        df[f"EMA_{time_prd} {target}"] = df[f"EMA_{time_prd} {target}"].shift(1)
        df[f"RSI_{time_prd} {target}"] = df[f"RSI_{time_prd} {target}"].shift(1)
        df[f"MACD {target}"] = df[f"MACD {target}"].shift(1)
        df[f"MACD_Sig {target}"] = df[f"MACD_Sig {target}"].shift(1)
        df[f"MACD_Hist {target}"] = df[f"MACD_Hist {target}"].shift(1)

    asset.data = df.dropna() 
    
print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (970, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-02-24  122.527972  119.278390  121.922948  111039900         -0.004060
2021-02-25  123.406232  117.629191  121.669217  148199500         -0.035402
2021-02-26  121.835107  118.273246  119.629680  164560400          0.002229
2021-03-01  124.840766  119.824887  120.761704  116307900          0.052452
2021-03-02  125.611668  121.991258  125.309156  102260900         -0.021115

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                -0.006281                -0.004764
2021-02-25                -0.006568                -0.004697
2021-02-26                -0.007952                -0.007621
2021-03-01                -0.006060                -0.006683
2021-03-02                -0.001531                -0.001051

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                49.443327              -0.005006
2021-02-25                49.042061              -0.004288
2021-02-26                44.959599              -0.006177
2021-03-01                50.199121              -0.004584
2021-03-02                56.073523               0.000722

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-02-24                  -0.005451  ...  39.178786  39.352760  17823600
2021-02-25                  -0.005218  ...  39.352752  39.657204  21916700
2021-02-26                  -0.005410  ...  38.935217  39.648511  22144900
2021-03-01                  -0.005245  ...  39.335356  39.335356  17394100
2021-03-02                  -0.004051  ...  39.509325  39.952959  14833000

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24          0.005041                 0.000530
2021-02-25         -0.004822                 0.000527
2021-02-26         -0.014382                -0.000197
2021-03-01          0.023131                -0.000521
2021-03-02         -0.008749                 0.001481

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.001497                50.527952
2021-02-25                -0.000874                51.224838
2021-02-26                -0.001250                49.039717
2021-03-01                -0.002501                46.994221
2021-03-02                -0.000060                54.783902

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.001681                  -0.000759
2021-02-25              -0.000967                  -0.000801
2021-02-26              -0.001184                  -0.000877
2021-03-01              -0.002102                  -0.001122
2021-03-02               0.000194                  -0.000859


           MACD_Hist Close_Log_Returns
Date
2021-02-24                   -0.000923
2021-02-25                   -0.000167
2021-02-26                   -0.000307
2021-03-01                   -0.000980
2021-03-02                    0.001053

[5 rows x 154 columns]

In [12]:
basket.align(joint_strategy)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 970 rows
DEBUG:entities.basket:Aligned data shape: (970, 154)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 970)

Basket data shape: (970, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-02-24  122.527972  119.278390  121.922948  111039900         -0.004060
2021-02-25  123.406232  117.629191  121.669217  148199500         -0.035402
2021-02-26  121.835107  118.273246  119.629680  164560400          0.002229
2021-03-01  124.840766  119.824887  120.761704  116307900          0.052452
2021-03-02  125.611668  121.991258  125.309156  102260900         -0.021115

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                -0.006281                -0.004764
2021-02-25                -0.006568                -0.004697
2021-02-26                -0.007952                -0.007621
2021-03-01                -0.006060                -0.006683
2021-03-02                -0.001531                -0.001051

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                49.443327              -0.005006
2021-02-25                49.042061              -0.004288
2021-02-26                44.959599              -0.006177
2021-03-01                50.199121              -0.004584
2021-03-02                56.073523               0.000722

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-02-24                  -0.005451  ...  39.178786  39.352760  17823600
2021-02-25                  -0.005218  ...  39.352752  39.657204  21916700
2021-02-26                  -0.005410  ...  38.935217  39.648511  22144900
2021-03-01                  -0.005245  ...  39.335356  39.335356  17394100
2021-03-02                  -0.004051  ...  39.509325  39.952959  14833000

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24          0.005041                 0.000530
2021-02-25         -0.004822                 0.000527
2021-02-26         -0.014382                -0.000197
2021-03-01          0.023131                -0.000521
2021-03-02         -0.008749                 0.001481

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.001497                50.527952
2021-02-25                -0.000874                51.224838
2021-02-26                -0.001250                49.039717
2021-03-01                -0.002501                46.994221
2021-03-02                -0.000060                54.783902

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.001681                  -0.000759
2021-02-25              -0.000967                  -0.000801
2021-02-26              -0.001184                  -0.000877
2021-03-01              -0.002102                  -0.001122
2021-03-02               0.000194                  -0.000859


           MACD_Hist Close_Log_Returns
Date
2021-02-24                   -0.000923
2021-02-25                   -0.000167
2021-02-26                   -0.000307
2021-03-01                   -0.000980
2021-03-02                    0.001053

[5 rows x 154 columns]

## Filter only Target Features ($F_{target} $)

In [13]:
targets = basket.get_keyword_features("Returns")
print(f"Targets: {targets}")


for symbol, asset in basket.assets.items():
    mask = asset.data.columns.isin(targets)
    asset.data = asset.data.loc[:, mask]

print(f"Basket shape: {basket.data.shape}")
basket.data.head(5)

Targets: {'EMA_20 Close_Log_Returns', 'MACD_Sig Close_Log_Returns', 'RSI_20 Close_Log_Returns', 'MACD_Hist Close_Log_Returns', 'MACD Close_Log_Returns', 'SMA_20 Close_Log_Returns', 'Close_Log_Returns'}
Basket shape: (970, 98)

                        AAPL                           \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24         -0.004060                -0.006281
2021-02-25         -0.035402                -0.006568
2021-02-26          0.002229                -0.007952
2021-03-01          0.052452                -0.006060
2021-03-02         -0.021115                -0.001531

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.004764                49.443327
2021-02-25                -0.004697                49.042061
2021-02-26                -0.007621                44.959599
2021-03-01                -0.006683                50.199121
2021-03-02                -0.001051                56.073523

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.005006                  -0.005451
2021-02-25              -0.004288                  -0.005218
2021-02-26              -0.006177                  -0.005410
2021-03-01              -0.004584                  -0.005245
2021-03-02               0.000722                  -0.004051

                                                    TSLA  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-24                    0.000445          0.059954
2021-02-25                    0.000930         -0.084024
2021-02-26                   -0.000767         -0.009899
2021-03-01                    0.000661          0.061615
2021-03-02                    0.004773         -0.045549

                                                              ...  \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns  ...
Date                                                          ...
2021-02-24                -0.011570                -0.012856  ...
2021-02-25                -0.008703                -0.005921  ...
2021-02-26                -0.011820                -0.013360  ...
2021-03-01                -0.010625                -0.013030  ...
2021-03-02                -0.004971                -0.005921  ...

                              AMD                             \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.004678                  -0.002595
2021-02-25              -0.001476                  -0.002371
2021-02-26              -0.005253                  -0.002947
2021-03-01              -0.001896                  -0.002737
2021-03-02               0.000513                  -0.002087

                                                    CSCO  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-24                   -0.002084          0.005041
2021-02-25                    0.000895         -0.004822
2021-02-26                   -0.002306         -0.014382
2021-03-01                    0.000841          0.023131
2021-03-02                    0.002600         -0.008749

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                 0.000530                -0.001497
2021-02-25                 0.000527                -0.000874
2021-02-26                -0.000197                -0.001250
2021-03-01                -0.000521                -0.002501
2021-03-02                 0.001481                -0.000060

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                50.527952              -0.001681
2021-02-25                51.224838              -0.000967
2021-02-26                49.039717              -0.001184
2021-03-01                46.994221              -0.002102
2021-03-02                54.783902               0.000194


           MACD_Sig Close_Log_Returns MACD_Hist Close_Log_Returns
Date
2021-02-24                  -0.000759                   -0.000923
2021-02-25                  -0.000801                   -0.000167
2021-02-26                  -0.000877                   -0.000307
2021-03-01                  -0.001122                   -0.000980
2021-03-02                  -0.000859                    0.001053

[5 rows x 98 columns]

# Dataset & Dataloader

In [14]:
n_obs = len(basket.data)
n_assets = basket.data.columns.levels[0].size
n_features = basket.data.columns.levels[1].size

print(n_obs, n_assets, n_features)

basket_np = basket.data.values.reshape(n_obs, n_assets, n_features)
basket_np.shape

970 14 7

(970, 14, 7)

## Ratio Dataset

In [15]:
ratios = [0.8, 0.1, 0.1]
total_count = len(basket_np)
train_count = int(total_count * ratios[0])
val_count = int(total_count * ratios[1])
test_count = total_count - train_count - val_count

print(f"Ratios DS\nTrain:\t{train_count}\nVal:\t{val_count}\nTest:\t{test_count}\nTotal:\t{total_count}")

Ratios DS
Train:	776
Val:	97
Test:	97
Total:	970

In [16]:
all_dates = basket.data.index.get_level_values(0).unique().to_numpy()
print(f"Dates shape: {all_dates.shape}")

Dates shape: (970,)

In [17]:
end_val = train_count + val_count

# Ratios
train_part = basket_np[:train_count]
val_part = basket_np[train_count:end_val]
test_part = basket_np[end_val:]

train_dates = all_dates[:train_count]
val_dates   = all_dates[train_count:end_val]
test_dates  = all_dates[end_val:]

print(f"Train: {train_part.shape}\nVal: {val_part.shape}\nTest:{test_part.shape}")
print(f"Train Dates: {train_dates.shape}\nVal Dates: {val_dates.shape}\nTest Dates:{test_dates.shape}")

Train: (776, 14, 7)
Val: (97, 14, 7)
Test:(97, 14, 7)
Train Dates: (776,)
Val Dates: (97,)
Test Dates:(97,)

## Scale Dataset

In [18]:
# scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = StandardScaler()

# Require 2D Numpy Array
T, A, F = train_part.shape
scaler.fit(train_part.reshape(-1, F))

scaled_train_part = scale(train_part, scaler)
scaled_val_part = scale(val_part, scaler)
scaled_test_part = scale(test_part, scaler)

inspect(scaled_train_part, "Scaled Train Part")
inspect(scaled_val_part, "Scaled Val Part")
inspect(scaled_test_part, "Scaled Test Part")
print(f"Train:\t{scaled_train_part.shape}\nVal:\t{scaled_val_part.shape}\nTest:\t{scaled_test_part.shape}")

--- Inspecting: Scaled Train Part ---
------------------------------------
Shape: (776, 14, 7)
Min:   -12.4922
Max:   8.8458
Mean:  0.0000
Std:   1.0000
------------------------------------
--- Inspecting: Scaled Val Part ---
------------------------------------
Shape: (97, 14, 7)
Min:   -8.9719
Max:   6.1577
Mean:  -0.0437
Std:   0.9942
------------------------------------
--- Inspecting: Scaled Test Part ---
------------------------------------
Shape: (97, 14, 7)
Min:   -6.1881
Max:   8.8664
Mean:  0.1223
Std:   0.9497
------------------------------------
Train:	(776, 14, 7)
Val:	(97, 14, 7)
Test:	(97, 14, 7)

## Dataloader

In [19]:
train_ds = MarketDataset(data=scaled_train_part, dates=train_dates, window_size=window_size)
val_ds = MarketDataset(data=scaled_val_part, dates=val_dates, window_size=window_size)
test_ds = MarketDataset(data=scaled_test_part, dates=test_dates, window_size=window_size)

print(f"Num of Windows\nTrain DS: {len(train_ds)}, Val Ds: {len(val_ds)}, Test DS: {len(test_ds)}\n")
print(f"A sample shape from Train DS\n\tx: {train_ds[0]['x'].shape},\n\tx_cond: {train_ds[0]['x_cond'].shape}")

Num of Windows
Train DS: 713, Val Ds: 34, Test DS: 34

A sample shape from Train DS
	x: (64, 14, 1),
	x_cond: (64, 14, 6)

In [20]:
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False)

batch = next(iter(train_loader))
print(len(train_loader))
print(batch["x"].shape)
print(batch["x_cond"].shape)

90
torch.Size([8, 64, 14, 1])
torch.Size([8, 64, 14, 6])

# Model, Engine
Use *Condition DDPM*

In [21]:
# n_window mean batch size
n_window, window, n_assets, n_features = batch["x"].shape
n_window, window, n_assets, n_conds = batch["x_cond"].shape
ddpm_transformer['n_cond'] = n_conds

print(n_assets, n_features, n_conds)

input_channels = n_assets * n_features
cond_channels = n_assets * n_conds
print(input_channels, cond_channels)

14 1 6
14 84

In [22]:
model = DiffusionTransformer(
    n_features=input_channels,
    n_cond=cond_channels,        
    window_size=window_size,             
    d_model=ddpm_transformer['d_model'],                
    nhead=ddpm_transformer['nhead'],
    num_layers=ddpm_transformer['num_layers'],
    dim_feedforward=ddpm_transformer['dim_feedforward'],
    dropout=ddpm_transformer['dropout']
).to(device)

In [23]:
diffusion = Diffusion(model, timesteps=ddpm['timesteps'], beta_start=ddpm['beta_start'], beta_end=ddpm['beta_end']).to(device)

In [24]:
optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

In [25]:
engine = Engine(
    train_dataloader=train_loader,
    val_dataloader=val_loader,
    model=diffusion,
    scaler=scaler,
    optimizer=optimizer,
    device=device,
    file_name=f"ddpm_transformer_d{ddpm_transformer['d_model']}_l{ddpm_transformer['num_layers']}",
)

In [ ]:
engine.fit(epochs)

INFO:engine.trainer:Engine started Training for 10000 epochs on cuda...
Epoch 1/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.966]
Epoch 1/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.05it/s]

End of Epoch 1 | Train Loss: 1.020934 | Val Loss: 1.019503
New Best Model Saved (Val Loss: 1.019503)

Epoch 2/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=1.02]
Epoch 2/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.50it/s]

End of Epoch 2 | Train Loss: 1.008717 | Val Loss: 0.996560
New Best Model Saved (Val Loss: 0.996560)

Epoch 3/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.987]
Epoch 3/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.27it/s]

End of Epoch 3 | Train Loss: 1.006538 | Val Loss: 0.999474

Epoch 4/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=1.08]
Epoch 4/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 4 | Train Loss: 1.008889 | Val Loss: 1.004092

Epoch 5/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=1.01]
Epoch 5/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 5 | Train Loss: 1.004001 | Val Loss: 1.011299

Epoch 6/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=1.04]
Epoch 6/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 6 | Train Loss: 1.003208 | Val Loss: 0.993633
New Best Model Saved (Val Loss: 0.993633)

Epoch 7/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=1]
Epoch 7/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.52it/s]

End of Epoch 7 | Train Loss: 1.002191 | Val Loss: 0.995441

Epoch 8/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.963]
Epoch 8/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.38it/s]

End of Epoch 8 | Train Loss: 1.002857 | Val Loss: 0.992147
New Best Model Saved (Val Loss: 0.992147)

Epoch 9/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=1.01]
Epoch 9/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.34it/s]

End of Epoch 9 | Train Loss: 1.004825 | Val Loss: 0.999564

Epoch 10/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=1.01]
Epoch 10/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.58it/s]

End of Epoch 10 | Train Loss: 1.002689 | Val Loss: 0.985139
New Best Model Saved (Val Loss: 0.985139)

Epoch 11/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.992]
Epoch 11/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.91it/s]

End of Epoch 11 | Train Loss: 1.005632 | Val Loss: 1.004193

Epoch 12/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=1.06]
Epoch 12/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 12 | Train Loss: 1.005943 | Val Loss: 1.009483

Epoch 13/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.985]
Epoch 13/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 13 | Train Loss: 1.000516 | Val Loss: 0.996906

Epoch 14/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.983]
Epoch 14/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.46it/s]

End of Epoch 14 | Train Loss: 0.999519 | Val Loss: 0.999499

Epoch 15/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=1.09]
Epoch 15/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 15 | Train Loss: 1.001935 | Val Loss: 1.004003

Epoch 16/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.994]
Epoch 16/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 16 | Train Loss: 1.001955 | Val Loss: 0.992514

Epoch 17/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.962]
Epoch 17/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 17 | Train Loss: 1.001701 | Val Loss: 1.019145

Epoch 18/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=1.02]
Epoch 18/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 18 | Train Loss: 1.003425 | Val Loss: 1.004044

Epoch 19/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.933]
Epoch 19/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 19 | Train Loss: 1.000124 | Val Loss: 1.014423

Epoch 20/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=1.02]
Epoch 20/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 20 | Train Loss: 1.002733 | Val Loss: 0.998057

Epoch 21/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=1.03]
Epoch 21/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.07it/s]

End of Epoch 21 | Train Loss: 1.006176 | Val Loss: 0.999947

Epoch 22/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=1]
Epoch 22/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.30it/s]

End of Epoch 22 | Train Loss: 1.004285 | Val Loss: 1.000658

Epoch 23/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=1.08]
Epoch 23/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.78it/s]

End of Epoch 23 | Train Loss: 1.004684 | Val Loss: 0.992978

Epoch 24/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.992]
Epoch 24/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 24 | Train Loss: 0.999558 | Val Loss: 1.005076

Epoch 25/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.974]
Epoch 25/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.57it/s]

End of Epoch 25 | Train Loss: 1.003821 | Val Loss: 1.005883

Epoch 26/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.953]
Epoch 26/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 26 | Train Loss: 1.001575 | Val Loss: 0.985270

Epoch 27/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=1.05]
Epoch 27/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.31it/s]

End of Epoch 27 | Train Loss: 1.000572 | Val Loss: 1.002663

Epoch 28/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.953]
Epoch 28/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.29it/s]

End of Epoch 28 | Train Loss: 1.002898 | Val Loss: 0.994017

Epoch 29/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.48it/s, loss=1.01]
Epoch 29/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.56it/s]

End of Epoch 29 | Train Loss: 1.001819 | Val Loss: 0.995365

Epoch 30/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=1.03]
Epoch 30/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.16it/s]

End of Epoch 30 | Train Loss: 1.001890 | Val Loss: 1.008263

Epoch 31/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=1.04]
Epoch 31/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 31 | Train Loss: 1.002404 | Val Loss: 0.995458

Epoch 32/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.988]
Epoch 32/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 32 | Train Loss: 0.998023 | Val Loss: 0.995923

Epoch 33/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=1]
Epoch 33/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.95it/s]

End of Epoch 33 | Train Loss: 1.001702 | Val Loss: 0.984684
New Best Model Saved (Val Loss: 0.984684)

Epoch 34/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.974]
Epoch 34/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.91it/s]

End of Epoch 34 | Train Loss: 0.999147 | Val Loss: 1.002058

Epoch 35/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.978]
Epoch 35/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.92it/s]

End of Epoch 35 | Train Loss: 1.001107 | Val Loss: 1.000458

Epoch 36/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=1.02]
Epoch 36/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 36 | Train Loss: 0.997205 | Val Loss: 1.001436

Epoch 37/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=1.02]
Epoch 37/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.34it/s]

End of Epoch 37 | Train Loss: 0.998942 | Val Loss: 1.014476

Epoch 38/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.966]
Epoch 38/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 38 | Train Loss: 0.986137 | Val Loss: 0.975110
New Best Model Saved (Val Loss: 0.975110)

Epoch 39/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.932]
Epoch 39/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.99it/s]

End of Epoch 39 | Train Loss: 0.959205 | Val Loss: 0.962255
New Best Model Saved (Val Loss: 0.962255)

Epoch 40/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=1]
Epoch 40/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 40 | Train Loss: 0.952493 | Val Loss: 0.933391
New Best Model Saved (Val Loss: 0.933391)

Epoch 41/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.978]
Epoch 41/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.84it/s]

End of Epoch 41 | Train Loss: 0.944695 | Val Loss: 0.950548

Epoch 42/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.882]
Epoch 42/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.58it/s]

End of Epoch 42 | Train Loss: 0.945411 | Val Loss: 0.954978

Epoch 43/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.853]
Epoch 43/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 43 | Train Loss: 0.928709 | Val Loss: 0.904691
New Best Model Saved (Val Loss: 0.904691)

Epoch 44/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.863]
Epoch 44/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.77it/s]

End of Epoch 44 | Train Loss: 0.899093 | Val Loss: 0.894099
New Best Model Saved (Val Loss: 0.894099)

Epoch 45/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.98]
Epoch 45/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 45 | Train Loss: 0.894415 | Val Loss: 0.880415
New Best Model Saved (Val Loss: 0.880415)

Epoch 46/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.951]
Epoch 46/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 46 | Train Loss: 0.891338 | Val Loss: 0.880320
New Best Model Saved (Val Loss: 0.880320)

Epoch 47/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.85]
Epoch 47/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.19it/s]

End of Epoch 47 | Train Loss: 0.886768 | Val Loss: 0.899591

Epoch 48/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.57it/s, loss=0.827]
Epoch 48/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 48 | Train Loss: 0.887674 | Val Loss: 0.871454
New Best Model Saved (Val Loss: 0.871454)

Epoch 49/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.828]
Epoch 49/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.42it/s]

End of Epoch 49 | Train Loss: 0.878531 | Val Loss: 0.900485

Epoch 50/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.846]
Epoch 50/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 50 | Train Loss: 0.855662 | Val Loss: 0.854200
New Best Model Saved (Val Loss: 0.854200)

Epoch 51/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.876]
Epoch 51/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 51 | Train Loss: 0.856066 | Val Loss: 0.866721

Epoch 52/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.771]
Epoch 52/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 52 | Train Loss: 0.851399 | Val Loss: 0.850816
New Best Model Saved (Val Loss: 0.850816)

Epoch 53/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.764]
Epoch 53/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.64it/s]

End of Epoch 53 | Train Loss: 0.834474 | Val Loss: 0.828295
New Best Model Saved (Val Loss: 0.828295)

Epoch 54/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.83]
Epoch 54/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 54 | Train Loss: 0.834739 | Val Loss: 0.816238
New Best Model Saved (Val Loss: 0.816238)

Epoch 55/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.775]
Epoch 55/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.69it/s]

End of Epoch 55 | Train Loss: 0.815098 | Val Loss: 0.800938
New Best Model Saved (Val Loss: 0.800938)

Epoch 56/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.865]
Epoch 56/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.98it/s]

End of Epoch 56 | Train Loss: 0.802027 | Val Loss: 0.767052
New Best Model Saved (Val Loss: 0.767052)

Epoch 57/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.734]
Epoch 57/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.79it/s]

End of Epoch 57 | Train Loss: 0.796799 | Val Loss: 0.779776

Epoch 58/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.746]
Epoch 58/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 58 | Train Loss: 0.784294 | Val Loss: 0.751393
New Best Model Saved (Val Loss: 0.751393)

Epoch 59/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.742]
Epoch 59/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.94it/s]

End of Epoch 59 | Train Loss: 0.773915 | Val Loss: 0.799539

Epoch 60/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.771]
Epoch 60/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.11it/s]

End of Epoch 60 | Train Loss: 0.774508 | Val Loss: 0.768177

Epoch 61/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.749]
Epoch 61/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.78it/s]

End of Epoch 61 | Train Loss: 0.767005 | Val Loss: 0.757555

Epoch 62/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.731]
Epoch 62/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 62 | Train Loss: 0.754470 | Val Loss: 0.733711
New Best Model Saved (Val Loss: 0.733711)

Epoch 63/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.694]
Epoch 63/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.23it/s]

End of Epoch 63 | Train Loss: 0.740451 | Val Loss: 0.761728

Epoch 64/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.721]
Epoch 64/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.75it/s]

End of Epoch 64 | Train Loss: 0.727526 | Val Loss: 0.743563

Epoch 65/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.663]
Epoch 65/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.75it/s]

End of Epoch 65 | Train Loss: 0.720623 | Val Loss: 0.726066
New Best Model Saved (Val Loss: 0.726066)

Epoch 66/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.654]
Epoch 66/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 93.15it/s]

End of Epoch 66 | Train Loss: 0.715377 | Val Loss: 0.733699

Epoch 67/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.662]
Epoch 67/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.79it/s]

End of Epoch 67 | Train Loss: 0.717360 | Val Loss: 0.714673
New Best Model Saved (Val Loss: 0.714673)

Epoch 68/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.548]
Epoch 68/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 68 | Train Loss: 0.701874 | Val Loss: 0.757499

Epoch 69/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.58]
Epoch 69/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.71it/s]

End of Epoch 69 | Train Loss: 0.660497 | Val Loss: 0.618865
New Best Model Saved (Val Loss: 0.618865)

Epoch 70/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.533]
Epoch 70/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 70 | Train Loss: 0.631813 | Val Loss: 0.595614
New Best Model Saved (Val Loss: 0.595614)

Epoch 71/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.513]
Epoch 71/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.54it/s]

End of Epoch 71 | Train Loss: 0.627244 | Val Loss: 0.605111

Epoch 72/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.54]
Epoch 72/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 72 | Train Loss: 0.613311 | Val Loss: 0.588334
New Best Model Saved (Val Loss: 0.588334)

Epoch 73/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.498]
Epoch 73/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 73 | Train Loss: 0.595075 | Val Loss: 0.633004

Epoch 74/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.545]
Epoch 74/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.86it/s]

End of Epoch 74 | Train Loss: 0.563842 | Val Loss: 0.621308

Epoch 75/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.553]
Epoch 75/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.15it/s]

End of Epoch 75 | Train Loss: 0.566292 | Val Loss: 0.591115

Epoch 76/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.517]
Epoch 76/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 76 | Train Loss: 0.552982 | Val Loss: 0.537431
New Best Model Saved (Val Loss: 0.537431)

Epoch 77/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.423]
Epoch 77/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.14it/s]

End of Epoch 77 | Train Loss: 0.531574 | Val Loss: 0.509745
New Best Model Saved (Val Loss: 0.509745)

Epoch 78/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.437]
Epoch 78/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 78 | Train Loss: 0.511457 | Val Loss: 0.521246

Epoch 79/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.447]
Epoch 79/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.39it/s]

End of Epoch 79 | Train Loss: 0.505531 | Val Loss: 0.549982

Epoch 80/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.689]
Epoch 80/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 80 | Train Loss: 0.493896 | Val Loss: 0.475319
New Best Model Saved (Val Loss: 0.475319)

Epoch 81/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.429]
Epoch 81/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.84it/s]

End of Epoch 81 | Train Loss: 0.488964 | Val Loss: 0.490233

Epoch 82/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.479]
Epoch 82/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.44it/s]

End of Epoch 82 | Train Loss: 0.466709 | Val Loss: 0.446953
New Best Model Saved (Val Loss: 0.446953)

Epoch 83/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.465]
Epoch 83/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.80it/s]

End of Epoch 83 | Train Loss: 0.459001 | Val Loss: 0.491657

Epoch 84/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=1.01]
Epoch 84/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.88it/s]

End of Epoch 84 | Train Loss: 0.424467 | Val Loss: 0.524738

Epoch 85/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.329]
Epoch 85/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 85 | Train Loss: 0.419578 | Val Loss: 0.377095
New Best Model Saved (Val Loss: 0.377095)

Epoch 86/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.43it/s, loss=0.3]
Epoch 86/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.36it/s]

End of Epoch 86 | Train Loss: 0.410742 | Val Loss: 0.449545

Epoch 87/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.299]
Epoch 87/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.17it/s]

End of Epoch 87 | Train Loss: 0.421050 | Val Loss: 0.431010

Epoch 88/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.336]
Epoch 88/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.75it/s]

End of Epoch 88 | Train Loss: 0.411205 | Val Loss: 0.363905
New Best Model Saved (Val Loss: 0.363905)

Epoch 89/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.393]
Epoch 89/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.73it/s]

End of Epoch 89 | Train Loss: 0.393241 | Val Loss: 0.362166
New Best Model Saved (Val Loss: 0.362166)

Epoch 90/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.237]
Epoch 90/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.72it/s]

End of Epoch 90 | Train Loss: 0.373380 | Val Loss: 0.387489

Epoch 91/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.575]
Epoch 91/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 91 | Train Loss: 0.337665 | Val Loss: 0.334363
New Best Model Saved (Val Loss: 0.334363)

Epoch 92/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.195]
Epoch 92/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 92 | Train Loss: 0.341072 | Val Loss: 0.406947

Epoch 93/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.218]
Epoch 93/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 93 | Train Loss: 0.338586 | Val Loss: 0.388738

Epoch 94/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.205]
Epoch 94/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 94 | Train Loss: 0.326521 | Val Loss: 0.398954

Epoch 95/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.204]
Epoch 95/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.22it/s]

End of Epoch 95 | Train Loss: 0.328734 | Val Loss: 0.364749

Epoch 96/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.206]
Epoch 96/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.27it/s]

End of Epoch 96 | Train Loss: 0.322528 | Val Loss: 0.321253
New Best Model Saved (Val Loss: 0.321253)

Epoch 97/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.894]
Epoch 97/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.39it/s]

End of Epoch 97 | Train Loss: 0.310317 | Val Loss: 0.300870
New Best Model Saved (Val Loss: 0.300870)

Epoch 98/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.124]
Epoch 98/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 98 | Train Loss: 0.305894 | Val Loss: 0.274233
New Best Model Saved (Val Loss: 0.274233)

Epoch 99/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.307]
Epoch 99/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.28it/s]

End of Epoch 99 | Train Loss: 0.276486 | Val Loss: 0.252889
New Best Model Saved (Val Loss: 0.252889)

Epoch 100/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.759]
Epoch 100/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 100 | Train Loss: 0.290431 | Val Loss: 0.350766

Epoch 101/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.877]
Epoch 101/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 101 | Train Loss: 0.269326 | Val Loss: 0.331316

Epoch 102/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.158]
Epoch 102/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 102 | Train Loss: 0.273944 | Val Loss: 0.264353

Epoch 103/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.117]
Epoch 103/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 103 | Train Loss: 0.268541 | Val Loss: 0.167168
New Best Model Saved (Val Loss: 0.167168)

Epoch 104/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.113]
Epoch 104/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.35it/s]

End of Epoch 104 | Train Loss: 0.269847 | Val Loss: 0.292357

Epoch 105/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.471]
Epoch 105/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.01it/s]

End of Epoch 105 | Train Loss: 0.266389 | Val Loss: 0.269132

Epoch 106/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.14]
Epoch 106/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.84it/s]

End of Epoch 106 | Train Loss: 0.274156 | Val Loss: 0.316061

Epoch 107/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0944]
Epoch 107/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 107 | Train Loss: 0.249012 | Val Loss: 0.281641

Epoch 108/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.082]
Epoch 108/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.82it/s]

End of Epoch 108 | Train Loss: 0.241128 | Val Loss: 0.315199

Epoch 109/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=1.05]
Epoch 109/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.30it/s]

End of Epoch 109 | Train Loss: 0.262155 | Val Loss: 0.221215

Epoch 110/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.161]
Epoch 110/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.25it/s]

End of Epoch 110 | Train Loss: 0.237305 | Val Loss: 0.208644

Epoch 111/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0813]
Epoch 111/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.63it/s]

End of Epoch 111 | Train Loss: 0.227324 | Val Loss: 0.229833

Epoch 112/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.627]
Epoch 112/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 112 | Train Loss: 0.237183 | Val Loss: 0.325737

Epoch 113/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0586]
Epoch 113/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 113 | Train Loss: 0.206699 | Val Loss: 0.186469

Epoch 114/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.912]
Epoch 114/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 114 | Train Loss: 0.230389 | Val Loss: 0.287967

Epoch 115/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.255]
Epoch 115/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.19it/s]

End of Epoch 115 | Train Loss: 0.219255 | Val Loss: 0.170094

Epoch 116/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0525]
Epoch 116/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 116 | Train Loss: 0.239562 | Val Loss: 0.277862

Epoch 117/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0554]
Epoch 117/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.71it/s]

End of Epoch 117 | Train Loss: 0.205996 | Val Loss: 0.245567

Epoch 118/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0586]
Epoch 118/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 118 | Train Loss: 0.215339 | Val Loss: 0.281333

Epoch 119/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0585]
Epoch 119/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.78it/s]

End of Epoch 119 | Train Loss: 0.218448 | Val Loss: 0.195766

Epoch 120/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0697]
Epoch 120/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.46it/s]

End of Epoch 120 | Train Loss: 0.221964 | Val Loss: 0.262770

Epoch 121/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0542]
Epoch 121/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 121 | Train Loss: 0.210183 | Val Loss: 0.240630

Epoch 122/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0731]
Epoch 122/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.48it/s]

End of Epoch 122 | Train Loss: 0.231863 | Val Loss: 0.194641

Epoch 123/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0649]
Epoch 123/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.31it/s]

End of Epoch 123 | Train Loss: 0.224768 | Val Loss: 0.234595

Epoch 124/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.46it/s, loss=0.132]
Epoch 124/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.83it/s]

End of Epoch 124 | Train Loss: 0.221363 | Val Loss: 0.256754

Epoch 125/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0618]
Epoch 125/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.82it/s]

End of Epoch 125 | Train Loss: 0.207546 | Val Loss: 0.202271

Epoch 126/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.047]
Epoch 126/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.38it/s]

End of Epoch 126 | Train Loss: 0.234295 | Val Loss: 0.157899
New Best Model Saved (Val Loss: 0.157899)

Epoch 127/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.104]
Epoch 127/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.79it/s]

End of Epoch 127 | Train Loss: 0.203963 | Val Loss: 0.233021

Epoch 128/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0619]
Epoch 128/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 128 | Train Loss: 0.231893 | Val Loss: 0.239562

Epoch 129/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0521]
Epoch 129/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.36it/s]

End of Epoch 129 | Train Loss: 0.198207 | Val Loss: 0.223529

Epoch 130/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0464]
Epoch 130/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 130 | Train Loss: 0.186725 | Val Loss: 0.128867
New Best Model Saved (Val Loss: 0.128867)

Epoch 131/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0473]
Epoch 131/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 131 | Train Loss: 0.206241 | Val Loss: 0.305437

Epoch 132/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0552]
Epoch 132/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 132 | Train Loss: 0.194803 | Val Loss: 0.147532

Epoch 133/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.16]
Epoch 133/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 133 | Train Loss: 0.215569 | Val Loss: 0.363910

Epoch 134/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.985]
Epoch 134/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.93it/s]

End of Epoch 134 | Train Loss: 0.240206 | Val Loss: 0.246454

Epoch 135/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.179]
Epoch 135/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.13it/s]

End of Epoch 135 | Train Loss: 0.218281 | Val Loss: 0.253751

Epoch 136/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0472]
Epoch 136/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.22it/s]

End of Epoch 136 | Train Loss: 0.186338 | Val Loss: 0.365419

Epoch 137/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0558]
Epoch 137/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 137 | Train Loss: 0.214150 | Val Loss: 0.262608

Epoch 138/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0429]
Epoch 138/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.85it/s]

End of Epoch 138 | Train Loss: 0.223794 | Val Loss: 0.158028

Epoch 139/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0549]
Epoch 139/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.22it/s]

End of Epoch 139 | Train Loss: 0.204812 | Val Loss: 0.196899

Epoch 140/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.459]
Epoch 140/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.69it/s]

End of Epoch 140 | Train Loss: 0.207737 | Val Loss: 0.303104

Epoch 141/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0454]
Epoch 141/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.50it/s]

End of Epoch 141 | Train Loss: 0.200759 | Val Loss: 0.232762

Epoch 142/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0448]
Epoch 142/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 142 | Train Loss: 0.191595 | Val Loss: 0.284741

Epoch 143/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.46it/s, loss=0.172]
Epoch 143/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.87it/s]

End of Epoch 143 | Train Loss: 0.206214 | Val Loss: 0.172155

Epoch 144/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0574]
Epoch 144/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 144 | Train Loss: 0.194896 | Val Loss: 0.284961

Epoch 145/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.3]
Epoch 145/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.27it/s]

End of Epoch 145 | Train Loss: 0.211393 | Val Loss: 0.224775

Epoch 146/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.129]
Epoch 146/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 146 | Train Loss: 0.208161 | Val Loss: 0.145810

Epoch 147/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.829]
Epoch 147/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 147 | Train Loss: 0.210197 | Val Loss: 0.167103

Epoch 148/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0346]
Epoch 148/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 148 | Train Loss: 0.199702 | Val Loss: 0.156408

Epoch 149/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0382]
Epoch 149/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 149 | Train Loss: 0.204231 | Val Loss: 0.204351

Epoch 150/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.134]
Epoch 150/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 150 | Train Loss: 0.191878 | Val Loss: 0.216939

Epoch 151/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0709]
Epoch 151/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 151 | Train Loss: 0.192783 | Val Loss: 0.268400

Epoch 152/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.283]
Epoch 152/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.02it/s]

End of Epoch 152 | Train Loss: 0.192191 | Val Loss: 0.189816

Epoch 153/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.426]
Epoch 153/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 153 | Train Loss: 0.202257 | Val Loss: 0.242712

Epoch 154/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.606]
Epoch 154/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 154 | Train Loss: 0.215245 | Val Loss: 0.241765

Epoch 155/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0383]
Epoch 155/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.45it/s]

End of Epoch 155 | Train Loss: 0.179583 | Val Loss: 0.329450

Epoch 156/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.047]
Epoch 156/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.53it/s]

End of Epoch 156 | Train Loss: 0.195973 | Val Loss: 0.121741
New Best Model Saved (Val Loss: 0.121741)

Epoch 157/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.168]
Epoch 157/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 157 | Train Loss: 0.200514 | Val Loss: 0.225651

Epoch 158/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0446]
Epoch 158/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.26it/s]

End of Epoch 158 | Train Loss: 0.194617 | Val Loss: 0.222364

Epoch 159/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.847]
Epoch 159/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 159 | Train Loss: 0.217096 | Val Loss: 0.207456

Epoch 160/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0349]
Epoch 160/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 160 | Train Loss: 0.194101 | Val Loss: 0.213658

Epoch 161/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0346]
Epoch 161/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.41it/s]

End of Epoch 161 | Train Loss: 0.187471 | Val Loss: 0.087660
New Best Model Saved (Val Loss: 0.087660)

Epoch 162/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.53it/s, loss=0.0312]
Epoch 162/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 162 | Train Loss: 0.187258 | Val Loss: 0.220012

Epoch 163/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0343]
Epoch 163/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.90it/s]

End of Epoch 163 | Train Loss: 0.204144 | Val Loss: 0.293909

Epoch 164/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0375]
Epoch 164/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 164 | Train Loss: 0.207755 | Val Loss: 0.177928

Epoch 165/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.45it/s, loss=0.261]
Epoch 165/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.78it/s]

End of Epoch 165 | Train Loss: 0.187861 | Val Loss: 0.105833

Epoch 166/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0394]
Epoch 166/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 166 | Train Loss: 0.182361 | Val Loss: 0.346866

Epoch 167/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0355]
Epoch 167/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.81it/s]

End of Epoch 167 | Train Loss: 0.189549 | Val Loss: 0.180809

Epoch 168/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.252]
Epoch 168/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.42it/s]

End of Epoch 168 | Train Loss: 0.180543 | Val Loss: 0.167349

Epoch 169/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0391]
Epoch 169/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.06it/s]

End of Epoch 169 | Train Loss: 0.182262 | Val Loss: 0.164752

Epoch 170/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.354]
Epoch 170/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 170 | Train Loss: 0.186704 | Val Loss: 0.363746

Epoch 171/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0335]
Epoch 171/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.21it/s]

End of Epoch 171 | Train Loss: 0.184046 | Val Loss: 0.280016

Epoch 172/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0386]
Epoch 172/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.20it/s]

End of Epoch 172 | Train Loss: 0.183596 | Val Loss: 0.418022

Epoch 173/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.173]
Epoch 173/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 173 | Train Loss: 0.188331 | Val Loss: 0.339900

Epoch 174/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.0602]
Epoch 174/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 174 | Train Loss: 0.182974 | Val Loss: 0.274431

Epoch 175/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.751]
Epoch 175/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 175 | Train Loss: 0.199947 | Val Loss: 0.362404

Epoch 176/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.533]
Epoch 176/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 176 | Train Loss: 0.179476 | Val Loss: 0.223449

Epoch 177/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.951]
Epoch 177/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.90it/s]

End of Epoch 177 | Train Loss: 0.199094 | Val Loss: 0.183153

Epoch 178/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.435]
Epoch 178/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 178 | Train Loss: 0.190323 | Val Loss: 0.145047

Epoch 179/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0352]
Epoch 179/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 179 | Train Loss: 0.178062 | Val Loss: 0.247833

Epoch 180/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0953]
Epoch 180/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.50it/s]

End of Epoch 180 | Train Loss: 0.187741 | Val Loss: 0.357730

Epoch 181/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0321]
Epoch 181/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 181 | Train Loss: 0.177305 | Val Loss: 0.232087

Epoch 182/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.0337]
Epoch 182/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.33it/s]

End of Epoch 182 | Train Loss: 0.169961 | Val Loss: 0.197683

Epoch 183/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.353]
Epoch 183/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.91it/s]

End of Epoch 183 | Train Loss: 0.176417 | Val Loss: 0.224470

Epoch 184/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0311]
Epoch 184/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 184 | Train Loss: 0.169046 | Val Loss: 0.181363

Epoch 185/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0327]
Epoch 185/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 185 | Train Loss: 0.165635 | Val Loss: 0.281196

Epoch 186/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0821]
Epoch 186/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 186 | Train Loss: 0.183007 | Val Loss: 0.188806

Epoch 187/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0303]
Epoch 187/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 187 | Train Loss: 0.172579 | Val Loss: 0.193592

Epoch 188/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.256]
Epoch 188/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.12it/s]

End of Epoch 188 | Train Loss: 0.179786 | Val Loss: 0.234534

Epoch 189/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0503]
Epoch 189/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.24it/s]

End of Epoch 189 | Train Loss: 0.190338 | Val Loss: 0.204471

Epoch 190/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0323]
Epoch 190/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 190 | Train Loss: 0.183208 | Val Loss: 0.137412

Epoch 191/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.11]
Epoch 191/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.66it/s]

End of Epoch 191 | Train Loss: 0.175314 | Val Loss: 0.272477

Epoch 192/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0302]
Epoch 192/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 192 | Train Loss: 0.161906 | Val Loss: 0.291565

Epoch 193/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.914]
Epoch 193/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.95it/s]

End of Epoch 193 | Train Loss: 0.188087 | Val Loss: 0.128941

Epoch 194/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0349]
Epoch 194/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 194 | Train Loss: 0.180178 | Val Loss: 0.185326

Epoch 195/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0408]
Epoch 195/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.40it/s]

End of Epoch 195 | Train Loss: 0.162327 | Val Loss: 0.230507

Epoch 196/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.16]
Epoch 196/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.55it/s]

End of Epoch 196 | Train Loss: 0.181095 | Val Loss: 0.325803

Epoch 197/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0346]
Epoch 197/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 197 | Train Loss: 0.181567 | Val Loss: 0.233857

Epoch 198/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0729]
Epoch 198/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 198 | Train Loss: 0.176582 | Val Loss: 0.243446

Epoch 199/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.96]
Epoch 199/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.67it/s]

End of Epoch 199 | Train Loss: 0.183909 | Val Loss: 0.205372

Epoch 200/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0795]
Epoch 200/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 200 | Train Loss: 0.180572 | Val Loss: 0.316390

Epoch 201/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.49it/s, loss=0.0526]
Epoch 201/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.33it/s]

End of Epoch 201 | Train Loss: 0.160351 | Val Loss: 0.321667

Epoch 202/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.268]
Epoch 202/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.59it/s]

End of Epoch 202 | Train Loss: 0.168869 | Val Loss: 0.218077

Epoch 203/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.132]
Epoch 203/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.32it/s]

End of Epoch 203 | Train Loss: 0.173113 | Val Loss: 0.118706

Epoch 204/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.489]
Epoch 204/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 204 | Train Loss: 0.162333 | Val Loss: 0.292934

Epoch 205/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.217]
Epoch 205/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 205 | Train Loss: 0.169214 | Val Loss: 0.251131

Epoch 206/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.029]
Epoch 206/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.97it/s]

End of Epoch 206 | Train Loss: 0.170169 | Val Loss: 0.192967

Epoch 207/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.931]
Epoch 207/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 207 | Train Loss: 0.177485 | Val Loss: 0.267265

Epoch 208/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0266]
Epoch 208/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.63it/s]

End of Epoch 208 | Train Loss: 0.158795 | Val Loss: 0.228555

Epoch 209/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0275]
Epoch 209/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 209 | Train Loss: 0.170389 | Val Loss: 0.185031

Epoch 210/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.254]
Epoch 210/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.96it/s]

End of Epoch 210 | Train Loss: 0.156659 | Val Loss: 0.160774

Epoch 211/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.128]
Epoch 211/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 211 | Train Loss: 0.154223 | Val Loss: 0.251082

Epoch 212/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0285]
Epoch 212/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.11it/s]

End of Epoch 212 | Train Loss: 0.157778 | Val Loss: 0.167383

Epoch 213/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0316]
Epoch 213/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 213 | Train Loss: 0.157986 | Val Loss: 0.266081

Epoch 214/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0299]
Epoch 214/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.41it/s]

End of Epoch 214 | Train Loss: 0.161449 | Val Loss: 0.221742

Epoch 215/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.336]
Epoch 215/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.09it/s]

End of Epoch 215 | Train Loss: 0.171983 | Val Loss: 0.242599

Epoch 216/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.257]
Epoch 216/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.30it/s]

End of Epoch 216 | Train Loss: 0.166067 | Val Loss: 0.440131

Epoch 217/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0218]
Epoch 217/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 217 | Train Loss: 0.160743 | Val Loss: 0.241492

Epoch 218/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0288]
Epoch 218/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 218 | Train Loss: 0.155865 | Val Loss: 0.340981

Epoch 219/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0294]
Epoch 219/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.66it/s]

End of Epoch 219 | Train Loss: 0.165704 | Val Loss: 0.258589

Epoch 220/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.0208]
Epoch 220/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.67it/s]

End of Epoch 220 | Train Loss: 0.155997 | Val Loss: 0.423833

Epoch 221/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0242]
Epoch 221/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.10it/s]

End of Epoch 221 | Train Loss: 0.150527 | Val Loss: 0.293232

Epoch 222/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.616]
Epoch 222/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.46it/s]

End of Epoch 222 | Train Loss: 0.160542 | Val Loss: 0.272630

Epoch 223/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.664]
Epoch 223/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.29it/s]

End of Epoch 223 | Train Loss: 0.164404 | Val Loss: 0.300151

Epoch 224/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0273]
Epoch 224/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 224 | Train Loss: 0.180795 | Val Loss: 0.223840

Epoch 225/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0249]
Epoch 225/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.76it/s]

End of Epoch 225 | Train Loss: 0.137399 | Val Loss: 0.279831

Epoch 226/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.121]
Epoch 226/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.92it/s]

End of Epoch 226 | Train Loss: 0.147279 | Val Loss: 0.177232

Epoch 227/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0349]
Epoch 227/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 227 | Train Loss: 0.159728 | Val Loss: 0.238485

Epoch 228/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.458]
Epoch 228/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.92it/s]

End of Epoch 228 | Train Loss: 0.154572 | Val Loss: 0.236217

Epoch 229/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0234]
Epoch 229/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 229 | Train Loss: 0.149759 | Val Loss: 0.196449

Epoch 230/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.455]
Epoch 230/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 230 | Train Loss: 0.157377 | Val Loss: 0.236080

Epoch 231/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.134]
Epoch 231/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.01it/s]

End of Epoch 231 | Train Loss: 0.141822 | Val Loss: 0.234974

Epoch 232/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0268]
Epoch 232/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.11it/s]

End of Epoch 232 | Train Loss: 0.138412 | Val Loss: 0.211430

Epoch 233/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0269]
Epoch 233/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.97it/s]

End of Epoch 233 | Train Loss: 0.148760 | Val Loss: 0.215595

Epoch 234/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0804]
Epoch 234/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.55it/s]

End of Epoch 234 | Train Loss: 0.171728 | Val Loss: 0.219613

Epoch 235/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0248]
Epoch 235/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 235 | Train Loss: 0.152988 | Val Loss: 0.243507

Epoch 236/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.178]
Epoch 236/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.38it/s]

End of Epoch 236 | Train Loss: 0.154841 | Val Loss: 0.343447

Epoch 237/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0321]
Epoch 237/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 237 | Train Loss: 0.144714 | Val Loss: 0.141624

Epoch 238/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0248]
Epoch 238/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.95it/s]

End of Epoch 238 | Train Loss: 0.152037 | Val Loss: 0.184582

Epoch 239/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.0232]
Epoch 239/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 239 | Train Loss: 0.154029 | Val Loss: 0.155754

Epoch 240/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0254]
Epoch 240/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.19it/s]

End of Epoch 240 | Train Loss: 0.149025 | Val Loss: 0.202300

Epoch 241/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.118]
Epoch 241/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.14it/s]

End of Epoch 241 | Train Loss: 0.148417 | Val Loss: 0.287077

Epoch 242/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0306]
Epoch 242/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.97it/s]

End of Epoch 242 | Train Loss: 0.145997 | Val Loss: 0.326939

Epoch 243/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0976]
Epoch 243/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.92it/s]

End of Epoch 243 | Train Loss: 0.146504 | Val Loss: 0.136635

Epoch 244/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0238]
Epoch 244/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 244 | Train Loss: 0.167791 | Val Loss: 0.229852

Epoch 245/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.906]
Epoch 245/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.96it/s]

End of Epoch 245 | Train Loss: 0.153354 | Val Loss: 0.259900

Epoch 246/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.256]
Epoch 246/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.03it/s]

End of Epoch 246 | Train Loss: 0.148998 | Val Loss: 0.400089

Epoch 247/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0275]
Epoch 247/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.04it/s]

End of Epoch 247 | Train Loss: 0.155003 | Val Loss: 0.235756

Epoch 248/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0235]
Epoch 248/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 248 | Train Loss: 0.160901 | Val Loss: 0.205032

Epoch 249/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.313]
Epoch 249/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 249 | Train Loss: 0.152915 | Val Loss: 0.389480

Epoch 250/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0288]
Epoch 250/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 250 | Train Loss: 0.142489 | Val Loss: 0.194867

Epoch 251/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0216]
Epoch 251/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.19it/s]

End of Epoch 251 | Train Loss: 0.148593 | Val Loss: 0.230548

Epoch 252/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0563]
Epoch 252/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 252 | Train Loss: 0.148263 | Val Loss: 0.180855

Epoch 253/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.496]
Epoch 253/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.15it/s]

End of Epoch 253 | Train Loss: 0.147747 | Val Loss: 0.231977

Epoch 254/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0316]
Epoch 254/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.54it/s]

End of Epoch 254 | Train Loss: 0.145165 | Val Loss: 0.249822

Epoch 255/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0374]
Epoch 255/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 255 | Train Loss: 0.152898 | Val Loss: 0.350513

Epoch 256/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0211]
Epoch 256/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 256 | Train Loss: 0.141708 | Val Loss: 0.173901

Epoch 257/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0178]
Epoch 257/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.47it/s]

End of Epoch 257 | Train Loss: 0.134718 | Val Loss: 0.346294

Epoch 258/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0272]
Epoch 258/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.58it/s]

End of Epoch 258 | Train Loss: 0.151154 | Val Loss: 0.288162

Epoch 259/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.403]
Epoch 259/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.98it/s]

End of Epoch 259 | Train Loss: 0.162966 | Val Loss: 0.353323

Epoch 260/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0641]
Epoch 260/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.69it/s]

End of Epoch 260 | Train Loss: 0.141815 | Val Loss: 0.185131

Epoch 261/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.11]
Epoch 261/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.48it/s]

End of Epoch 261 | Train Loss: 0.140608 | Val Loss: 0.288792

Epoch 262/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.528]
Epoch 262/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 262 | Train Loss: 0.166874 | Val Loss: 0.236182

Epoch 263/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.127]
Epoch 263/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.84it/s]

End of Epoch 263 | Train Loss: 0.152090 | Val Loss: 0.262744

Epoch 264/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.13]
Epoch 264/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.00it/s]

End of Epoch 264 | Train Loss: 0.130486 | Val Loss: 0.455948

Epoch 265/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0233]
Epoch 265/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 265 | Train Loss: 0.140997 | Val Loss: 0.225976

Epoch 266/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0935]
Epoch 266/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 266 | Train Loss: 0.143717 | Val Loss: 0.318986

Epoch 267/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.235]
Epoch 267/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.90it/s]

End of Epoch 267 | Train Loss: 0.145537 | Val Loss: 0.296328

Epoch 268/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.40it/s, loss=0.21]
Epoch 268/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.22it/s]

End of Epoch 268 | Train Loss: 0.147875 | Val Loss: 0.182677

Epoch 269/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.138]
Epoch 269/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.11it/s]

End of Epoch 269 | Train Loss: 0.133667 | Val Loss: 0.360471

Epoch 270/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0218]
Epoch 270/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 270 | Train Loss: 0.131360 | Val Loss: 0.301651

Epoch 271/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0208]
Epoch 271/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 271 | Train Loss: 0.138095 | Val Loss: 0.338385

Epoch 272/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.242]
Epoch 272/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.37it/s]

End of Epoch 272 | Train Loss: 0.148396 | Val Loss: 0.298321

Epoch 273/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0595]
Epoch 273/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.11it/s]

End of Epoch 273 | Train Loss: 0.146029 | Val Loss: 0.192352

Epoch 274/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.36it/s, loss=0.149]
Epoch 274/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 274 | Train Loss: 0.132693 | Val Loss: 0.220613

Epoch 275/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0567]
Epoch 275/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 275 | Train Loss: 0.124571 | Val Loss: 0.247169

Epoch 276/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.534]
Epoch 276/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 276 | Train Loss: 0.146100 | Val Loss: 0.167690

Epoch 277/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0488]
Epoch 277/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.14it/s]

End of Epoch 277 | Train Loss: 0.130685 | Val Loss: 0.302835

Epoch 278/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0469]
Epoch 278/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 278 | Train Loss: 0.150224 | Val Loss: 0.447948

Epoch 279/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.138]
Epoch 279/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.73it/s]

End of Epoch 279 | Train Loss: 0.134761 | Val Loss: 0.443117

Epoch 280/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.116]
Epoch 280/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.88it/s]

End of Epoch 280 | Train Loss: 0.139946 | Val Loss: 0.293189

Epoch 281/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0172]
Epoch 281/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 281 | Train Loss: 0.131801 | Val Loss: 0.256652

Epoch 282/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.12]
Epoch 282/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.30it/s]

End of Epoch 282 | Train Loss: 0.144168 | Val Loss: 0.325762

Epoch 283/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0703]
Epoch 283/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.77it/s]

End of Epoch 283 | Train Loss: 0.116822 | Val Loss: 0.193961

Epoch 284/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0228]
Epoch 284/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 284 | Train Loss: 0.145174 | Val Loss: 0.194558

Epoch 285/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.137]
Epoch 285/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.74it/s]

End of Epoch 285 | Train Loss: 0.139842 | Val Loss: 0.311319

Epoch 286/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.259]
Epoch 286/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 286 | Train Loss: 0.126629 | Val Loss: 0.188279

Epoch 287/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.659]
Epoch 287/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.21it/s]

End of Epoch 287 | Train Loss: 0.142211 | Val Loss: 0.183650

Epoch 288/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.114]
Epoch 288/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 288 | Train Loss: 0.130306 | Val Loss: 0.317200

Epoch 289/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0473]
Epoch 289/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 289 | Train Loss: 0.120963 | Val Loss: 0.244827

Epoch 290/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0344]
Epoch 290/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 290 | Train Loss: 0.115814 | Val Loss: 0.467617

Epoch 291/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.152]
Epoch 291/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 291 | Train Loss: 0.124707 | Val Loss: 0.234506

Epoch 292/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.144]
Epoch 292/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.89it/s]

End of Epoch 292 | Train Loss: 0.142933 | Val Loss: 0.348358

Epoch 293/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0573]
Epoch 293/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 293 | Train Loss: 0.128044 | Val Loss: 0.441174

Epoch 294/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0165]
Epoch 294/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.12it/s]

End of Epoch 294 | Train Loss: 0.121638 | Val Loss: 0.216996

Epoch 295/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0417]
Epoch 295/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.68it/s]

End of Epoch 295 | Train Loss: 0.118822 | Val Loss: 0.165412

Epoch 296/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.105]
Epoch 296/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.89it/s]

End of Epoch 296 | Train Loss: 0.133889 | Val Loss: 0.256500

Epoch 297/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0313]
Epoch 297/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 297 | Train Loss: 0.117036 | Val Loss: 0.322216

Epoch 298/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0218]
Epoch 298/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 298 | Train Loss: 0.129653 | Val Loss: 0.301089

Epoch 299/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.166]
Epoch 299/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 299 | Train Loss: 0.127161 | Val Loss: 0.396425

Epoch 300/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0803]
Epoch 300/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.83it/s]

End of Epoch 300 | Train Loss: 0.117611 | Val Loss: 0.287498

Epoch 301/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0866]
Epoch 301/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 301 | Train Loss: 0.117310 | Val Loss: 0.461456

Epoch 302/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.136]
Epoch 302/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.91it/s]

End of Epoch 302 | Train Loss: 0.122357 | Val Loss: 0.203052

Epoch 303/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0238]
Epoch 303/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.89it/s]

End of Epoch 303 | Train Loss: 0.116446 | Val Loss: 0.408211

Epoch 304/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.993]
Epoch 304/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.00it/s]

End of Epoch 304 | Train Loss: 0.131212 | Val Loss: 0.241452

Epoch 305/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0364]
Epoch 305/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 305 | Train Loss: 0.124764 | Val Loss: 0.345087

Epoch 306/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0201]
Epoch 306/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.17it/s]

End of Epoch 306 | Train Loss: 0.121060 | Val Loss: 0.326420

Epoch 307/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.104]
Epoch 307/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.84it/s]

End of Epoch 307 | Train Loss: 0.114508 | Val Loss: 0.493581

Epoch 308/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0547]
Epoch 308/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.10it/s]

End of Epoch 308 | Train Loss: 0.126888 | Val Loss: 0.263633

Epoch 309/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0203]
Epoch 309/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.45it/s]

End of Epoch 309 | Train Loss: 0.128638 | Val Loss: 0.311001

Epoch 310/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.027]
Epoch 310/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.70it/s]

End of Epoch 310 | Train Loss: 0.120109 | Val Loss: 0.162138

Epoch 311/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0227]
Epoch 311/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.28it/s]

End of Epoch 311 | Train Loss: 0.116255 | Val Loss: 0.216708

Epoch 312/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.19]
Epoch 312/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.14it/s]

End of Epoch 312 | Train Loss: 0.132298 | Val Loss: 0.345878

Epoch 313/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.02]
Epoch 313/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.65it/s]

End of Epoch 313 | Train Loss: 0.131295 | Val Loss: 0.248387

Epoch 314/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0182]
Epoch 314/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.72it/s]

End of Epoch 314 | Train Loss: 0.116857 | Val Loss: 0.227505

Epoch 315/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0149]
Epoch 315/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 315 | Train Loss: 0.108883 | Val Loss: 0.440140

Epoch 316/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0885]
Epoch 316/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 316 | Train Loss: 0.117779 | Val Loss: 0.307335

Epoch 317/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.0288]
Epoch 317/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 317 | Train Loss: 0.111992 | Val Loss: 0.236006

Epoch 318/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.154]
Epoch 318/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.24it/s]

End of Epoch 318 | Train Loss: 0.114007 | Val Loss: 0.261046

Epoch 319/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0579]
Epoch 319/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.26it/s]

End of Epoch 319 | Train Loss: 0.126567 | Val Loss: 0.317370

Epoch 320/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0182]
Epoch 320/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 320 | Train Loss: 0.114028 | Val Loss: 0.184976

Epoch 321/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.965]
Epoch 321/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 321 | Train Loss: 0.130933 | Val Loss: 0.284294

Epoch 322/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0216]
Epoch 322/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.32it/s]

End of Epoch 322 | Train Loss: 0.107161 | Val Loss: 0.429703

Epoch 323/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.15]
Epoch 323/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.27it/s]

End of Epoch 323 | Train Loss: 0.121454 | Val Loss: 0.324587

Epoch 324/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0404]
Epoch 324/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.19it/s]

End of Epoch 324 | Train Loss: 0.120908 | Val Loss: 0.329339

Epoch 325/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.172]
Epoch 325/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.99it/s]

End of Epoch 325 | Train Loss: 0.099708 | Val Loss: 0.246489

Epoch 326/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.267]
Epoch 326/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.69it/s]

End of Epoch 326 | Train Loss: 0.110745 | Val Loss: 0.221272

Epoch 327/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0192]
Epoch 327/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 327 | Train Loss: 0.120782 | Val Loss: 0.311308

Epoch 328/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0188]
Epoch 328/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.71it/s]

End of Epoch 328 | Train Loss: 0.106469 | Val Loss: 0.194862

Epoch 329/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.0212]
Epoch 329/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 329 | Train Loss: 0.112310 | Val Loss: 0.473813

Epoch 330/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0996]
Epoch 330/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.10it/s]

End of Epoch 330 | Train Loss: 0.119276 | Val Loss: 0.320123

Epoch 331/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0201]
Epoch 331/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.89it/s]

End of Epoch 331 | Train Loss: 0.108826 | Val Loss: 0.374158

Epoch 332/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.016]
Epoch 332/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.76it/s]

End of Epoch 332 | Train Loss: 0.106818 | Val Loss: 0.155442

Epoch 333/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0169]
Epoch 333/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.82it/s]

End of Epoch 333 | Train Loss: 0.105477 | Val Loss: 0.218040

Epoch 334/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.285]
Epoch 334/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 334 | Train Loss: 0.116251 | Val Loss: 0.211740

Epoch 335/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.135]
Epoch 335/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.52it/s]

End of Epoch 335 | Train Loss: 0.108791 | Val Loss: 0.322273

Epoch 336/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.366]
Epoch 336/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 336 | Train Loss: 0.105823 | Val Loss: 0.247890

Epoch 337/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.335]
Epoch 337/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.04it/s]

End of Epoch 337 | Train Loss: 0.115178 | Val Loss: 0.362749

Epoch 338/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0159]
Epoch 338/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.24it/s]

End of Epoch 338 | Train Loss: 0.104482 | Val Loss: 0.452626

Epoch 339/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=1.01]
Epoch 339/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 339 | Train Loss: 0.116060 | Val Loss: 0.344383

Epoch 340/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0189]
Epoch 340/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 340 | Train Loss: 0.125776 | Val Loss: 0.409927

Epoch 341/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.432]
Epoch 341/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 341 | Train Loss: 0.116410 | Val Loss: 0.165829

Epoch 342/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0174]
Epoch 342/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.45it/s]

End of Epoch 342 | Train Loss: 0.112241 | Val Loss: 0.372126

Epoch 343/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0187]
Epoch 343/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.02it/s]

End of Epoch 343 | Train Loss: 0.101328 | Val Loss: 0.190031

Epoch 344/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0722]
Epoch 344/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.92it/s]

End of Epoch 344 | Train Loss: 0.116748 | Val Loss: 0.341272

Epoch 345/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.027]
Epoch 345/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 345 | Train Loss: 0.106520 | Val Loss: 0.300675

Epoch 346/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.186]
Epoch 346/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.07it/s]

End of Epoch 346 | Train Loss: 0.108320 | Val Loss: 0.165451

Epoch 347/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0308]
Epoch 347/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.15it/s]

End of Epoch 347 | Train Loss: 0.103797 | Val Loss: 0.301342

Epoch 348/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.225]
Epoch 348/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.24it/s]

End of Epoch 348 | Train Loss: 0.117279 | Val Loss: 0.378752

Epoch 349/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0136]
Epoch 349/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.98it/s]

End of Epoch 349 | Train Loss: 0.116274 | Val Loss: 0.227063

Epoch 350/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.338]
Epoch 350/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 350 | Train Loss: 0.119574 | Val Loss: 0.162757

Epoch 351/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0185]
Epoch 351/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 351 | Train Loss: 0.118718 | Val Loss: 0.282704

Epoch 352/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.154]
Epoch 352/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 352 | Train Loss: 0.106598 | Val Loss: 0.242891

Epoch 353/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0165]
Epoch 353/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.36it/s]

End of Epoch 353 | Train Loss: 0.106639 | Val Loss: 0.234267

Epoch 354/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.169]
Epoch 354/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 354 | Train Loss: 0.102065 | Val Loss: 0.476728

Epoch 355/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.0497]
Epoch 355/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.22it/s]

End of Epoch 355 | Train Loss: 0.109413 | Val Loss: 0.308347

Epoch 356/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0321]
Epoch 356/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.67it/s]

End of Epoch 356 | Train Loss: 0.108739 | Val Loss: 0.242341

Epoch 357/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0162]
Epoch 357/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.54it/s]

End of Epoch 357 | Train Loss: 0.108876 | Val Loss: 0.301910

Epoch 358/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0196]
Epoch 358/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 358 | Train Loss: 0.101380 | Val Loss: 0.307274

Epoch 359/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0174]
Epoch 359/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.61it/s]

End of Epoch 359 | Train Loss: 0.098049 | Val Loss: 0.457282

Epoch 360/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.611]
Epoch 360/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 360 | Train Loss: 0.114021 | Val Loss: 0.215538

Epoch 361/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0755]
Epoch 361/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 361 | Train Loss: 0.103525 | Val Loss: 0.276651

Epoch 362/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0152]
Epoch 362/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 362 | Train Loss: 0.098487 | Val Loss: 0.374467

Epoch 363/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0798]
Epoch 363/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.23it/s]

End of Epoch 363 | Train Loss: 0.117928 | Val Loss: 0.276954

Epoch 364/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0887]
Epoch 364/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.08it/s]

End of Epoch 364 | Train Loss: 0.120465 | Val Loss: 0.504548

Epoch 365/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.11]
Epoch 365/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 365 | Train Loss: 0.090606 | Val Loss: 0.489436

Epoch 366/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0152]
Epoch 366/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.05it/s]

End of Epoch 366 | Train Loss: 0.101753 | Val Loss: 0.360793

Epoch 367/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0165]
Epoch 367/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.20it/s]

End of Epoch 367 | Train Loss: 0.109303 | Val Loss: 0.348210

Epoch 368/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0374]
Epoch 368/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.95it/s]

End of Epoch 368 | Train Loss: 0.101749 | Val Loss: 0.437264

Epoch 369/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.015]
Epoch 369/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.19it/s]

End of Epoch 369 | Train Loss: 0.103504 | Val Loss: 0.270194

Epoch 370/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0766]
Epoch 370/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 370 | Train Loss: 0.110247 | Val Loss: 0.214872

Epoch 371/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0331]
Epoch 371/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 371 | Train Loss: 0.104103 | Val Loss: 0.190652

Epoch 372/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.23]
Epoch 372/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 372 | Train Loss: 0.102626 | Val Loss: 0.280223

Epoch 373/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.62]
Epoch 373/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 373 | Train Loss: 0.112584 | Val Loss: 0.247430

Epoch 374/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0138]
Epoch 374/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.39it/s]

End of Epoch 374 | Train Loss: 0.104528 | Val Loss: 0.167479

Epoch 375/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0919]
Epoch 375/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.17it/s]

End of Epoch 375 | Train Loss: 0.097089 | Val Loss: 0.272454

Epoch 376/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.0145]
Epoch 376/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.99it/s]

End of Epoch 376 | Train Loss: 0.100684 | Val Loss: 0.325770

Epoch 377/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0676]
Epoch 377/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 377 | Train Loss: 0.105762 | Val Loss: 0.284751

Epoch 378/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.122]
Epoch 378/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 378 | Train Loss: 0.091395 | Val Loss: 0.357913

Epoch 379/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.36it/s, loss=0.0141]
Epoch 379/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.53it/s]

End of Epoch 379 | Train Loss: 0.101793 | Val Loss: 0.311627

Epoch 380/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.61]
Epoch 380/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.90it/s]

End of Epoch 380 | Train Loss: 0.093448 | Val Loss: 0.249625

Epoch 381/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0353]
Epoch 381/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 381 | Train Loss: 0.098708 | Val Loss: 0.338086

Epoch 382/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0341]
Epoch 382/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 382 | Train Loss: 0.091762 | Val Loss: 0.459927

Epoch 383/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0152]
Epoch 383/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 383 | Train Loss: 0.098127 | Val Loss: 0.401932

Epoch 384/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0395]
Epoch 384/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 384 | Train Loss: 0.087632 | Val Loss: 0.434093

Epoch 385/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0162]
Epoch 385/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.68it/s]

End of Epoch 385 | Train Loss: 0.096012 | Val Loss: 0.350820

Epoch 386/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0175]
Epoch 386/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.04it/s]

End of Epoch 386 | Train Loss: 0.097617 | Val Loss: 0.264584

Epoch 387/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0249]
Epoch 387/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.71it/s]

End of Epoch 387 | Train Loss: 0.093672 | Val Loss: 0.280112

Epoch 388/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0247]
Epoch 388/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.28it/s]

End of Epoch 388 | Train Loss: 0.082283 | Val Loss: 0.458584

Epoch 389/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.39it/s, loss=0.243]
Epoch 389/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 389 | Train Loss: 0.092476 | Val Loss: 0.233066

Epoch 390/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.574]
Epoch 390/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 390 | Train Loss: 0.098305 | Val Loss: 0.438397

Epoch 391/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0196]
Epoch 391/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 391 | Train Loss: 0.095201 | Val Loss: 0.483508

Epoch 392/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.114]
Epoch 392/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 392 | Train Loss: 0.089609 | Val Loss: 0.404706

Epoch 393/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0194]
Epoch 393/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 393 | Train Loss: 0.090447 | Val Loss: 0.160230

Epoch 394/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0573]
Epoch 394/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 394 | Train Loss: 0.094131 | Val Loss: 0.379845

Epoch 395/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0156]
Epoch 395/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.97it/s]

End of Epoch 395 | Train Loss: 0.088074 | Val Loss: 0.317794

Epoch 396/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0688]
Epoch 396/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.19it/s]

End of Epoch 396 | Train Loss: 0.082129 | Val Loss: 0.363184

Epoch 397/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0214]
Epoch 397/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 397 | Train Loss: 0.099825 | Val Loss: 0.406249

Epoch 398/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0155]
Epoch 398/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.85it/s]

End of Epoch 398 | Train Loss: 0.094207 | Val Loss: 0.546505

Epoch 399/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.279]
Epoch 399/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 399 | Train Loss: 0.085074 | Val Loss: 0.359787

Epoch 400/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0183]
Epoch 400/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.10it/s]

End of Epoch 400 | Train Loss: 0.086596 | Val Loss: 0.314096

Epoch 401/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0164]
Epoch 401/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.13it/s]

End of Epoch 401 | Train Loss: 0.092515 | Val Loss: 0.468118

Epoch 402/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0168]
Epoch 402/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.42it/s]

End of Epoch 402 | Train Loss: 0.091331 | Val Loss: 0.356073

Epoch 403/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0227]
Epoch 403/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 403 | Train Loss: 0.084183 | Val Loss: 0.320563

Epoch 404/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.026]
Epoch 404/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 404 | Train Loss: 0.078809 | Val Loss: 0.364633

Epoch 405/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.014]
Epoch 405/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.68it/s]

End of Epoch 405 | Train Loss: 0.081399 | Val Loss: 0.494935

Epoch 406/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.403]
Epoch 406/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 406 | Train Loss: 0.101697 | Val Loss: 0.313702

Epoch 407/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0329]
Epoch 407/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.54it/s]

End of Epoch 407 | Train Loss: 0.095070 | Val Loss: 0.161978

Epoch 408/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.086]
Epoch 408/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 408 | Train Loss: 0.091413 | Val Loss: 0.301599

Epoch 409/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0387]
Epoch 409/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 409 | Train Loss: 0.078620 | Val Loss: 0.473821

Epoch 410/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.017]
Epoch 410/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.20it/s]

End of Epoch 410 | Train Loss: 0.092233 | Val Loss: 0.335999

Epoch 411/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.149]
Epoch 411/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 411 | Train Loss: 0.093524 | Val Loss: 0.464728

Epoch 412/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0162]
Epoch 412/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.75it/s]

End of Epoch 412 | Train Loss: 0.081622 | Val Loss: 0.207369

Epoch 413/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0141]
Epoch 413/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 413 | Train Loss: 0.087596 | Val Loss: 0.382499

Epoch 414/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0179]
Epoch 414/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.94it/s]

End of Epoch 414 | Train Loss: 0.080987 | Val Loss: 0.305158

Epoch 415/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0176]
Epoch 415/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.25it/s]

End of Epoch 415 | Train Loss: 0.077119 | Val Loss: 0.369230

Epoch 416/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0124]
Epoch 416/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 416 | Train Loss: 0.078575 | Val Loss: 0.280328

Epoch 417/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0155]
Epoch 417/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 417 | Train Loss: 0.100715 | Val Loss: 0.169873

Epoch 418/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0323]
Epoch 418/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 418 | Train Loss: 0.076922 | Val Loss: 0.223305

Epoch 419/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.335]
Epoch 419/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.39it/s]

End of Epoch 419 | Train Loss: 0.086798 | Val Loss: 0.318337

Epoch 420/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.519]
Epoch 420/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.67it/s]

End of Epoch 420 | Train Loss: 0.096825 | Val Loss: 0.467194

Epoch 421/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0233]
Epoch 421/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.64it/s]

End of Epoch 421 | Train Loss: 0.084858 | Val Loss: 0.135646

Epoch 422/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.373]
Epoch 422/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.97it/s]

End of Epoch 422 | Train Loss: 0.091271 | Val Loss: 0.355648

Epoch 423/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0493]
Epoch 423/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 423 | Train Loss: 0.086901 | Val Loss: 0.246435

Epoch 424/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0629]
Epoch 424/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.49it/s]

End of Epoch 424 | Train Loss: 0.084899 | Val Loss: 0.296415

Epoch 425/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0772]
Epoch 425/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 425 | Train Loss: 0.078321 | Val Loss: 0.114947

Epoch 426/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0297]
Epoch 426/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.27it/s]

End of Epoch 426 | Train Loss: 0.085365 | Val Loss: 0.189125

Epoch 427/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.12]
Epoch 427/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.29it/s]

End of Epoch 427 | Train Loss: 0.079244 | Val Loss: 0.261534

Epoch 428/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.115]
Epoch 428/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.79it/s]

End of Epoch 428 | Train Loss: 0.089553 | Val Loss: 0.509974

Epoch 429/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0188]
Epoch 429/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.22it/s]

End of Epoch 429 | Train Loss: 0.085252 | Val Loss: 0.371487

Epoch 430/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0726]
Epoch 430/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.84it/s]

End of Epoch 430 | Train Loss: 0.082338 | Val Loss: 0.503558

Epoch 431/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0155]
Epoch 431/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 431 | Train Loss: 0.089428 | Val Loss: 0.296985

Epoch 432/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.53it/s, loss=0.109]
Epoch 432/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.26it/s]

End of Epoch 432 | Train Loss: 0.084353 | Val Loss: 0.529059

Epoch 433/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.599]
Epoch 433/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 433 | Train Loss: 0.096583 | Val Loss: 0.226698

Epoch 434/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0151]
Epoch 434/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.00it/s]

End of Epoch 434 | Train Loss: 0.090321 | Val Loss: 0.185419

Epoch 435/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0602]
Epoch 435/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.92it/s]

End of Epoch 435 | Train Loss: 0.098468 | Val Loss: 0.331189

Epoch 436/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0206]
Epoch 436/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 436 | Train Loss: 0.078089 | Val Loss: 0.269433

Epoch 437/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.231]
Epoch 437/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.48it/s]

End of Epoch 437 | Train Loss: 0.083258 | Val Loss: 0.425883

Epoch 438/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0433]
Epoch 438/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 438 | Train Loss: 0.082946 | Val Loss: 0.560032

Epoch 439/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.0157]
Epoch 439/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.48it/s]

End of Epoch 439 | Train Loss: 0.075930 | Val Loss: 0.162832

Epoch 440/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0545]
Epoch 440/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 440 | Train Loss: 0.074401 | Val Loss: 0.444300

Epoch 441/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0171]
Epoch 441/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 441 | Train Loss: 0.084282 | Val Loss: 0.154391

Epoch 442/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0511]
Epoch 442/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 442 | Train Loss: 0.082855 | Val Loss: 0.377777

Epoch 443/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0132]
Epoch 443/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.18it/s]

End of Epoch 443 | Train Loss: 0.075571 | Val Loss: 0.311630

Epoch 444/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0434]
Epoch 444/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 444 | Train Loss: 0.084458 | Val Loss: 0.330037

Epoch 445/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0137]
Epoch 445/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.70it/s]

End of Epoch 445 | Train Loss: 0.070142 | Val Loss: 0.208333

Epoch 446/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0738]
Epoch 446/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.74it/s]

End of Epoch 446 | Train Loss: 0.077852 | Val Loss: 0.294025

Epoch 447/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0221]
Epoch 447/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 447 | Train Loss: 0.081149 | Val Loss: 0.453726

Epoch 448/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0139]
Epoch 448/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 448 | Train Loss: 0.071748 | Val Loss: 0.429978

Epoch 449/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.151]
Epoch 449/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 449 | Train Loss: 0.080026 | Val Loss: 0.436715

Epoch 450/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0824]
Epoch 450/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.73it/s]

End of Epoch 450 | Train Loss: 0.087682 | Val Loss: 0.272343

Epoch 451/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0332]
Epoch 451/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 451 | Train Loss: 0.081280 | Val Loss: 0.666762

Epoch 452/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0112]
Epoch 452/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.69it/s]

End of Epoch 452 | Train Loss: 0.063475 | Val Loss: 0.249126

Epoch 453/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.265]
Epoch 453/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 453 | Train Loss: 0.084539 | Val Loss: 0.415226

Epoch 454/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0136]
Epoch 454/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.57it/s]

End of Epoch 454 | Train Loss: 0.082163 | Val Loss: 0.466010

Epoch 455/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0137]
Epoch 455/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 455 | Train Loss: 0.076606 | Val Loss: 0.206005

Epoch 456/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0161]
Epoch 456/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 456 | Train Loss: 0.075586 | Val Loss: 0.446957

Epoch 457/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0168]
Epoch 457/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 457 | Train Loss: 0.079432 | Val Loss: 0.262082

Epoch 458/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0415]
Epoch 458/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.33it/s]

End of Epoch 458 | Train Loss: 0.076169 | Val Loss: 0.349846

Epoch 459/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0158]
Epoch 459/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 459 | Train Loss: 0.083098 | Val Loss: 0.487600

Epoch 460/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0791]
Epoch 460/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.85it/s]

End of Epoch 460 | Train Loss: 0.079552 | Val Loss: 0.231605

Epoch 461/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0267]
Epoch 461/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.36it/s]

End of Epoch 461 | Train Loss: 0.085130 | Val Loss: 0.498611

Epoch 462/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0273]
Epoch 462/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 462 | Train Loss: 0.078913 | Val Loss: 0.274953

Epoch 463/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.138]
Epoch 463/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.45it/s]

End of Epoch 463 | Train Loss: 0.079894 | Val Loss: 0.166691

Epoch 464/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0313]
Epoch 464/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.55it/s]

End of Epoch 464 | Train Loss: 0.081337 | Val Loss: 0.400884

Epoch 465/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.749]
Epoch 465/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.41it/s]

End of Epoch 465 | Train Loss: 0.079966 | Val Loss: 0.195654

Epoch 466/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.032]
Epoch 466/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.74it/s]

End of Epoch 466 | Train Loss: 0.077190 | Val Loss: 0.293076

Epoch 467/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0652]
Epoch 467/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 467 | Train Loss: 0.077888 | Val Loss: 0.404816

Epoch 468/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.196]
Epoch 468/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.38it/s]

End of Epoch 468 | Train Loss: 0.079653 | Val Loss: 0.421839

Epoch 469/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0218]
Epoch 469/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.80it/s]

End of Epoch 469 | Train Loss: 0.074286 | Val Loss: 0.259182

Epoch 470/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0146]
Epoch 470/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 470 | Train Loss: 0.073123 | Val Loss: 0.211727

Epoch 471/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.48it/s, loss=0.325]
Epoch 471/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.94it/s]

End of Epoch 471 | Train Loss: 0.083346 | Val Loss: 0.389308

Epoch 472/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0105]
Epoch 472/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 472 | Train Loss: 0.083901 | Val Loss: 0.267916

Epoch 473/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0126]
Epoch 473/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 473 | Train Loss: 0.078670 | Val Loss: 0.240055

Epoch 474/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0134]
Epoch 474/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.01it/s]

End of Epoch 474 | Train Loss: 0.069399 | Val Loss: 0.392206

Epoch 475/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0123]
Epoch 475/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.06it/s]

End of Epoch 475 | Train Loss: 0.074029 | Val Loss: 0.304697

Epoch 476/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0133]
Epoch 476/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 92.50it/s]

End of Epoch 476 | Train Loss: 0.067104 | Val Loss: 0.301099

Epoch 477/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0165]
Epoch 477/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.62it/s]

End of Epoch 477 | Train Loss: 0.073882 | Val Loss: 0.362454

Epoch 478/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0123]
Epoch 478/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.11it/s]

End of Epoch 478 | Train Loss: 0.079794 | Val Loss: 0.491151

Epoch 479/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0462]
Epoch 479/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 479 | Train Loss: 0.069376 | Val Loss: 0.415660

Epoch 480/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0271]
Epoch 480/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.66it/s]

End of Epoch 480 | Train Loss: 0.079421 | Val Loss: 0.316254

Epoch 481/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0296]
Epoch 481/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 481 | Train Loss: 0.078913 | Val Loss: 0.269908

Epoch 482/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0273]
Epoch 482/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 482 | Train Loss: 0.067248 | Val Loss: 0.238145

Epoch 483/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00978]
Epoch 483/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 483 | Train Loss: 0.071301 | Val Loss: 0.298074

Epoch 484/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.219]
Epoch 484/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 484 | Train Loss: 0.076801 | Val Loss: 0.443933

Epoch 485/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0184]
Epoch 485/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.43it/s]

End of Epoch 485 | Train Loss: 0.074506 | Val Loss: 0.309484

Epoch 486/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0134]
Epoch 486/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 486 | Train Loss: 0.079001 | Val Loss: 0.348015

Epoch 487/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0837]
Epoch 487/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 487 | Train Loss: 0.081949 | Val Loss: 0.264321

Epoch 488/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.192]
Epoch 488/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.31it/s]

End of Epoch 488 | Train Loss: 0.069568 | Val Loss: 0.456156

Epoch 489/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.236]
Epoch 489/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.03it/s]

End of Epoch 489 | Train Loss: 0.070561 | Val Loss: 0.551318

Epoch 490/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00877]
Epoch 490/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.06it/s]

End of Epoch 490 | Train Loss: 0.066438 | Val Loss: 0.189175

Epoch 491/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0114]
Epoch 491/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 491 | Train Loss: 0.069727 | Val Loss: 0.223570

Epoch 492/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0601]
Epoch 492/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.73it/s]

End of Epoch 492 | Train Loss: 0.068906 | Val Loss: 0.461212

Epoch 493/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0134]
Epoch 493/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.62it/s]

End of Epoch 493 | Train Loss: 0.071855 | Val Loss: 0.193429

Epoch 494/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0666]
Epoch 494/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.12it/s]

End of Epoch 494 | Train Loss: 0.079503 | Val Loss: 0.238106

Epoch 495/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0117]
Epoch 495/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.80it/s]

End of Epoch 495 | Train Loss: 0.072883 | Val Loss: 0.155546

Epoch 496/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0723]
Epoch 496/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.59it/s]

End of Epoch 496 | Train Loss: 0.064551 | Val Loss: 0.348135

Epoch 497/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.128]
Epoch 497/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.85it/s]

End of Epoch 497 | Train Loss: 0.072292 | Val Loss: 0.282993

Epoch 498/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0795]
Epoch 498/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.34it/s]

End of Epoch 498 | Train Loss: 0.070158 | Val Loss: 0.285947

Epoch 499/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.42it/s, loss=0.0719]
Epoch 499/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 499 | Train Loss: 0.075054 | Val Loss: 0.577988

Epoch 500/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.0129]
Epoch 500/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.71it/s]

End of Epoch 500 | Train Loss: 0.061027 | Val Loss: 0.426543

Epoch 501/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0306]
Epoch 501/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 501 | Train Loss: 0.075207 | Val Loss: 0.276173

Epoch 502/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0159]
Epoch 502/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 502 | Train Loss: 0.072500 | Val Loss: 0.557644

Epoch 503/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0599]
Epoch 503/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 503 | Train Loss: 0.079312 | Val Loss: 0.315612

Epoch 504/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.216]
Epoch 504/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.45it/s]

End of Epoch 504 | Train Loss: 0.072646 | Val Loss: 0.194734

Epoch 505/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.48it/s, loss=0.0131]
Epoch 505/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.70it/s]

End of Epoch 505 | Train Loss: 0.066234 | Val Loss: 0.441337

Epoch 506/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.157]
Epoch 506/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 506 | Train Loss: 0.071653 | Val Loss: 0.219497

Epoch 507/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.426]
Epoch 507/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 507 | Train Loss: 0.075879 | Val Loss: 0.338599

Epoch 508/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.278]
Epoch 508/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.16it/s]

End of Epoch 508 | Train Loss: 0.072228 | Val Loss: 0.338019

Epoch 509/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0512]
Epoch 509/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.05it/s]

End of Epoch 509 | Train Loss: 0.074804 | Val Loss: 0.289314

Epoch 510/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0652]
Epoch 510/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 510 | Train Loss: 0.070862 | Val Loss: 0.492165

Epoch 511/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00991]
Epoch 511/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.19it/s]

End of Epoch 511 | Train Loss: 0.071792 | Val Loss: 0.443226

Epoch 512/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0249]
Epoch 512/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 512 | Train Loss: 0.071477 | Val Loss: 0.270235

Epoch 513/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0267]
Epoch 513/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 513 | Train Loss: 0.072222 | Val Loss: 0.268990

Epoch 514/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0651]
Epoch 514/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 514 | Train Loss: 0.071472 | Val Loss: 0.281779

Epoch 515/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0508]
Epoch 515/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.83it/s]

End of Epoch 515 | Train Loss: 0.065312 | Val Loss: 0.241087

Epoch 516/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.026]
Epoch 516/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 516 | Train Loss: 0.072820 | Val Loss: 0.398188

Epoch 517/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0127]
Epoch 517/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 517 | Train Loss: 0.077519 | Val Loss: 0.295658

Epoch 518/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00977]
Epoch 518/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.90it/s]

End of Epoch 518 | Train Loss: 0.077000 | Val Loss: 0.205881

Epoch 519/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00988]
Epoch 519/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 519 | Train Loss: 0.073006 | Val Loss: 0.227552

Epoch 520/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0123]
Epoch 520/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 520 | Train Loss: 0.070068 | Val Loss: 0.418581

Epoch 521/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0346]
Epoch 521/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.34it/s]

End of Epoch 521 | Train Loss: 0.067431 | Val Loss: 0.424766

Epoch 522/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0149]
Epoch 522/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.81it/s]

End of Epoch 522 | Train Loss: 0.062307 | Val Loss: 0.373744

Epoch 523/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0125]
Epoch 523/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.17it/s]

End of Epoch 523 | Train Loss: 0.074028 | Val Loss: 0.350432

Epoch 524/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.466]
Epoch 524/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.65it/s]

End of Epoch 524 | Train Loss: 0.081256 | Val Loss: 0.328122

Epoch 525/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0118]
Epoch 525/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 525 | Train Loss: 0.072262 | Val Loss: 0.222162

Epoch 526/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0204]
Epoch 526/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 526 | Train Loss: 0.063579 | Val Loss: 0.314399

Epoch 527/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0882]
Epoch 527/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 527 | Train Loss: 0.069217 | Val Loss: 0.257865

Epoch 528/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.209]
Epoch 528/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 528 | Train Loss: 0.085473 | Val Loss: 0.352620

Epoch 529/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.0322]
Epoch 529/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.20it/s]

End of Epoch 529 | Train Loss: 0.070446 | Val Loss: 0.337425

Epoch 530/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0116]
Epoch 530/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 530 | Train Loss: 0.067551 | Val Loss: 0.481248

Epoch 531/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0393]
Epoch 531/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 531 | Train Loss: 0.069083 | Val Loss: 0.508697

Epoch 532/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0341]
Epoch 532/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.23it/s]

End of Epoch 532 | Train Loss: 0.074683 | Val Loss: 0.287559

Epoch 533/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.012]
Epoch 533/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 533 | Train Loss: 0.068031 | Val Loss: 0.427336

Epoch 534/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.111]
Epoch 534/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.82it/s]

End of Epoch 534 | Train Loss: 0.060054 | Val Loss: 0.449186

Epoch 535/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0126]
Epoch 535/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.48it/s]

End of Epoch 535 | Train Loss: 0.075420 | Val Loss: 0.321744

Epoch 536/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.013]
Epoch 536/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.09it/s]

End of Epoch 536 | Train Loss: 0.059546 | Val Loss: 0.367702

Epoch 537/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0132]
Epoch 537/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.33it/s]

End of Epoch 537 | Train Loss: 0.066871 | Val Loss: 0.403872

Epoch 538/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0109]
Epoch 538/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.44it/s]

End of Epoch 538 | Train Loss: 0.070334 | Val Loss: 0.519121

Epoch 539/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0494]
Epoch 539/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.92it/s]

End of Epoch 539 | Train Loss: 0.066838 | Val Loss: 0.480529

Epoch 540/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0126]
Epoch 540/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.23it/s]

End of Epoch 540 | Train Loss: 0.072232 | Val Loss: 0.294508

Epoch 541/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0374]
Epoch 541/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.25it/s]

End of Epoch 541 | Train Loss: 0.069477 | Val Loss: 0.407460

Epoch 542/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0134]
Epoch 542/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 542 | Train Loss: 0.062343 | Val Loss: 0.384967

Epoch 543/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0137]
Epoch 543/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.04it/s]

End of Epoch 543 | Train Loss: 0.074322 | Val Loss: 0.373523

Epoch 544/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0174]
Epoch 544/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 544 | Train Loss: 0.076125 | Val Loss: 0.351608

Epoch 545/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0375]
Epoch 545/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 545 | Train Loss: 0.066510 | Val Loss: 0.232684

Epoch 546/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0106]
Epoch 546/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 546 | Train Loss: 0.072545 | Val Loss: 0.332533

Epoch 547/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0128]
Epoch 547/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.36it/s]

End of Epoch 547 | Train Loss: 0.067072 | Val Loss: 0.512527

Epoch 548/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0182]
Epoch 548/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 548 | Train Loss: 0.058480 | Val Loss: 0.554492

Epoch 549/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0125]
Epoch 549/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.22it/s]

End of Epoch 549 | Train Loss: 0.054554 | Val Loss: 0.329189

Epoch 550/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0155]
Epoch 550/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.37it/s]

End of Epoch 550 | Train Loss: 0.069475 | Val Loss: 0.368539

Epoch 551/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0755]
Epoch 551/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.49it/s]

End of Epoch 551 | Train Loss: 0.067990 | Val Loss: 0.448299

Epoch 552/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.0576]
Epoch 552/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.67it/s]

End of Epoch 552 | Train Loss: 0.065343 | Val Loss: 0.276924

Epoch 553/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0162]
Epoch 553/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 553 | Train Loss: 0.056779 | Val Loss: 0.339357

Epoch 554/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0102]
Epoch 554/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 554 | Train Loss: 0.067187 | Val Loss: 0.561125

Epoch 555/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0325]
Epoch 555/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 555 | Train Loss: 0.058495 | Val Loss: 0.231357

Epoch 556/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0634]
Epoch 556/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 556 | Train Loss: 0.063757 | Val Loss: 0.426935

Epoch 557/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0234]
Epoch 557/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.98it/s]

End of Epoch 557 | Train Loss: 0.069935 | Val Loss: 0.452646

Epoch 558/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0118]
Epoch 558/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.69it/s]

End of Epoch 558 | Train Loss: 0.074607 | Val Loss: 0.457559

Epoch 559/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0261]
Epoch 559/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.65it/s]

End of Epoch 559 | Train Loss: 0.056320 | Val Loss: 0.553880

Epoch 560/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0228]
Epoch 560/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.40it/s]

End of Epoch 560 | Train Loss: 0.066942 | Val Loss: 0.189929

Epoch 561/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0215]
Epoch 561/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.55it/s]

End of Epoch 561 | Train Loss: 0.074293 | Val Loss: 0.448836

Epoch 562/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.0379]
Epoch 562/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 562 | Train Loss: 0.064971 | Val Loss: 0.346658

Epoch 563/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.41it/s, loss=0.0125]
Epoch 563/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.71it/s]

End of Epoch 563 | Train Loss: 0.071298 | Val Loss: 0.218485

Epoch 564/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.49it/s, loss=0.0319]
Epoch 564/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 564 | Train Loss: 0.054820 | Val Loss: 0.280737

Epoch 565/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.0148]
Epoch 565/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.38it/s]

End of Epoch 565 | Train Loss: 0.067747 | Val Loss: 0.325582

Epoch 566/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0111]
Epoch 566/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 566 | Train Loss: 0.060389 | Val Loss: 0.319881

Epoch 567/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0874]
Epoch 567/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 567 | Train Loss: 0.073114 | Val Loss: 0.317239

Epoch 568/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0132]
Epoch 568/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.58it/s]

End of Epoch 568 | Train Loss: 0.061944 | Val Loss: 0.270255

Epoch 569/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0693]
Epoch 569/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 569 | Train Loss: 0.060813 | Val Loss: 0.275651

Epoch 570/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0115]
Epoch 570/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 570 | Train Loss: 0.055297 | Val Loss: 0.294964

Epoch 571/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.202]
Epoch 571/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 571 | Train Loss: 0.064542 | Val Loss: 0.426041

Epoch 572/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0404]
Epoch 572/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.88it/s]

End of Epoch 572 | Train Loss: 0.069264 | Val Loss: 0.381379

Epoch 573/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00896]
Epoch 573/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 573 | Train Loss: 0.066111 | Val Loss: 0.281980

Epoch 574/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.118]
Epoch 574/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.63it/s]

End of Epoch 574 | Train Loss: 0.055991 | Val Loss: 0.300072

Epoch 575/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.14]
Epoch 575/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.52it/s]

End of Epoch 575 | Train Loss: 0.068515 | Val Loss: 0.329956

Epoch 576/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.019]
Epoch 576/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.87it/s]

End of Epoch 576 | Train Loss: 0.062517 | Val Loss: 0.454770

Epoch 577/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.337]
Epoch 577/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 577 | Train Loss: 0.071806 | Val Loss: 0.287254

Epoch 578/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0108]
Epoch 578/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.33it/s]

End of Epoch 578 | Train Loss: 0.069685 | Val Loss: 0.410566

Epoch 579/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0392]
Epoch 579/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.61it/s]

End of Epoch 579 | Train Loss: 0.061719 | Val Loss: 0.351207

Epoch 580/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0409]
Epoch 580/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.49it/s]

End of Epoch 580 | Train Loss: 0.070977 | Val Loss: 0.404322

Epoch 581/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00974]
Epoch 581/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.63it/s]

End of Epoch 581 | Train Loss: 0.065591 | Val Loss: 0.208936

Epoch 582/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0111]
Epoch 582/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 582 | Train Loss: 0.060303 | Val Loss: 0.353565

Epoch 583/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.345]
Epoch 583/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.68it/s]

End of Epoch 583 | Train Loss: 0.067224 | Val Loss: 0.615223

Epoch 584/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0109]
Epoch 584/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.16it/s]

End of Epoch 584 | Train Loss: 0.064512 | Val Loss: 0.377468

Epoch 585/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0732]
Epoch 585/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.18it/s]

End of Epoch 585 | Train Loss: 0.063359 | Val Loss: 0.211734

Epoch 586/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.029]
Epoch 586/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.23it/s]

End of Epoch 586 | Train Loss: 0.061078 | Val Loss: 0.415568

Epoch 587/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.0257]
Epoch 587/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.16it/s]

End of Epoch 587 | Train Loss: 0.069641 | Val Loss: 0.508351

Epoch 588/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0268]
Epoch 588/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 588 | Train Loss: 0.065503 | Val Loss: 0.366107

Epoch 589/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0107]
Epoch 589/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.26it/s]

End of Epoch 589 | Train Loss: 0.053404 | Val Loss: 0.284045

Epoch 590/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0101]
Epoch 590/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 590 | Train Loss: 0.061178 | Val Loss: 0.498394

Epoch 591/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.461]
Epoch 591/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.82it/s]

End of Epoch 591 | Train Loss: 0.072596 | Val Loss: 0.448541

Epoch 592/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0106]
Epoch 592/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 592 | Train Loss: 0.072126 | Val Loss: 0.227432

Epoch 593/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.045]
Epoch 593/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 593 | Train Loss: 0.055216 | Val Loss: 0.491907

Epoch 594/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00992]
Epoch 594/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.30it/s]

End of Epoch 594 | Train Loss: 0.061512 | Val Loss: 0.332116

Epoch 595/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.846]
Epoch 595/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 595 | Train Loss: 0.071183 | Val Loss: 0.332876

Epoch 596/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0185]
Epoch 596/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 596 | Train Loss: 0.070194 | Val Loss: 0.470038

Epoch 597/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.1]
Epoch 597/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 597 | Train Loss: 0.065006 | Val Loss: 0.249174

Epoch 598/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0503]
Epoch 598/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.01it/s]

End of Epoch 598 | Train Loss: 0.059271 | Val Loss: 0.256442

Epoch 599/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0134]
Epoch 599/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.52it/s]

End of Epoch 599 | Train Loss: 0.052194 | Val Loss: 0.392771

Epoch 600/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0125]
Epoch 600/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 600 | Train Loss: 0.061589 | Val Loss: 0.313970

Epoch 601/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0672]
Epoch 601/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 601 | Train Loss: 0.061895 | Val Loss: 0.359922

Epoch 602/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00948]
Epoch 602/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.09it/s]

End of Epoch 602 | Train Loss: 0.047687 | Val Loss: 0.403036

Epoch 603/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.037]
Epoch 603/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 603 | Train Loss: 0.057948 | Val Loss: 0.208697

Epoch 604/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.514]
Epoch 604/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.34it/s]

End of Epoch 604 | Train Loss: 0.059977 | Val Loss: 0.350661

Epoch 605/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.42it/s, loss=0.033]
Epoch 605/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.83it/s]

End of Epoch 605 | Train Loss: 0.058364 | Val Loss: 0.317440

Epoch 606/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.0108]
Epoch 606/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.96it/s]

End of Epoch 606 | Train Loss: 0.071480 | Val Loss: 0.468885

Epoch 607/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0169]
Epoch 607/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.98it/s]

End of Epoch 607 | Train Loss: 0.054536 | Val Loss: 0.424600

Epoch 608/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0112]
Epoch 608/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 608 | Train Loss: 0.069026 | Val Loss: 0.407755

Epoch 609/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00878]
Epoch 609/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 609 | Train Loss: 0.057040 | Val Loss: 0.403049

Epoch 610/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.062]
Epoch 610/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 610 | Train Loss: 0.062162 | Val Loss: 0.272292

Epoch 611/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0232]
Epoch 611/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 611 | Train Loss: 0.064703 | Val Loss: 0.404285

Epoch 612/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0119]
Epoch 612/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 612 | Train Loss: 0.056587 | Val Loss: 0.440469

Epoch 613/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0287]
Epoch 613/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.95it/s]

End of Epoch 613 | Train Loss: 0.067243 | Val Loss: 0.314463

Epoch 614/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0159]
Epoch 614/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.60it/s]

End of Epoch 614 | Train Loss: 0.056550 | Val Loss: 0.622195

Epoch 615/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0111]
Epoch 615/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.38it/s]

End of Epoch 615 | Train Loss: 0.058978 | Val Loss: 0.398530

Epoch 616/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.41it/s, loss=0.0273]
Epoch 616/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.90it/s]

End of Epoch 616 | Train Loss: 0.054925 | Val Loss: 0.496122

Epoch 617/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0183]
Epoch 617/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.92it/s]

End of Epoch 617 | Train Loss: 0.064705 | Val Loss: 0.229494

Epoch 618/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0104]
Epoch 618/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 618 | Train Loss: 0.059610 | Val Loss: 0.212171

Epoch 619/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00847]
Epoch 619/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.04it/s]

End of Epoch 619 | Train Loss: 0.065936 | Val Loss: 0.424174

Epoch 620/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.016]
Epoch 620/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.78it/s]

End of Epoch 620 | Train Loss: 0.056286 | Val Loss: 0.349903

Epoch 621/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0329]
Epoch 621/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 621 | Train Loss: 0.049548 | Val Loss: 0.191528

Epoch 622/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.39it/s, loss=0.0238]
Epoch 622/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 622 | Train Loss: 0.064497 | Val Loss: 0.294094

Epoch 623/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.40it/s, loss=0.025]
Epoch 623/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.39it/s]

End of Epoch 623 | Train Loss: 0.047710 | Val Loss: 0.262034

Epoch 624/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0774]
Epoch 624/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 624 | Train Loss: 0.053259 | Val Loss: 0.263239

Epoch 625/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00954]
Epoch 625/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 625 | Train Loss: 0.057435 | Val Loss: 0.511560

Epoch 626/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0142]
Epoch 626/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.75it/s]

End of Epoch 626 | Train Loss: 0.054342 | Val Loss: 0.281047

Epoch 627/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0258]
Epoch 627/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 627 | Train Loss: 0.057082 | Val Loss: 0.252816

Epoch 628/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0162]
Epoch 628/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 628 | Train Loss: 0.061469 | Val Loss: 0.402612

Epoch 629/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.127]
Epoch 629/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 629 | Train Loss: 0.054694 | Val Loss: 0.268553

Epoch 630/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.311]
Epoch 630/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 630 | Train Loss: 0.060988 | Val Loss: 0.288294

Epoch 631/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00967]
Epoch 631/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.80it/s]

End of Epoch 631 | Train Loss: 0.058868 | Val Loss: 0.314811

Epoch 632/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0166]
Epoch 632/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 632 | Train Loss: 0.052055 | Val Loss: 0.246860

Epoch 633/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00976]
Epoch 633/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 633 | Train Loss: 0.066827 | Val Loss: 0.351432

Epoch 634/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.0341]
Epoch 634/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 634 | Train Loss: 0.061317 | Val Loss: 0.264058

Epoch 635/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0116]
Epoch 635/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 635 | Train Loss: 0.055732 | Val Loss: 0.224097

Epoch 636/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0488]
Epoch 636/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 636 | Train Loss: 0.060953 | Val Loss: 0.402981

Epoch 637/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.119]
Epoch 637/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.18it/s]

End of Epoch 637 | Train Loss: 0.057263 | Val Loss: 0.456348

Epoch 638/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0395]
Epoch 638/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.52it/s]

End of Epoch 638 | Train Loss: 0.047325 | Val Loss: 0.217809

Epoch 639/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0345]
Epoch 639/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 639 | Train Loss: 0.056602 | Val Loss: 0.448996

Epoch 640/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0104]
Epoch 640/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.83it/s]

End of Epoch 640 | Train Loss: 0.060949 | Val Loss: 0.354263

Epoch 641/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0866]
Epoch 641/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 641 | Train Loss: 0.052579 | Val Loss: 0.448187

Epoch 642/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.114]
Epoch 642/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.54it/s]

End of Epoch 642 | Train Loss: 0.052471 | Val Loss: 0.229520

Epoch 643/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0199]
Epoch 643/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 643 | Train Loss: 0.057579 | Val Loss: 0.686584

Epoch 644/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.397]
Epoch 644/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 644 | Train Loss: 0.063022 | Val Loss: 0.560435

Epoch 645/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.114]
Epoch 645/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.39it/s]

End of Epoch 645 | Train Loss: 0.064247 | Val Loss: 0.301685

Epoch 646/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00824]
Epoch 646/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.54it/s]

End of Epoch 646 | Train Loss: 0.052806 | Val Loss: 0.288137

Epoch 647/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.369]
Epoch 647/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 647 | Train Loss: 0.060434 | Val Loss: 0.494230

Epoch 648/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0136]
Epoch 648/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.81it/s]

End of Epoch 648 | Train Loss: 0.057263 | Val Loss: 0.348318

Epoch 649/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.44it/s, loss=0.0131]
Epoch 649/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 649 | Train Loss: 0.063551 | Val Loss: 0.226676

Epoch 650/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.99]
Epoch 650/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.93it/s]

End of Epoch 650 | Train Loss: 0.067419 | Val Loss: 0.382925

Epoch 651/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0107]
Epoch 651/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 651 | Train Loss: 0.054467 | Val Loss: 0.260617

Epoch 652/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.027]
Epoch 652/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 652 | Train Loss: 0.054014 | Val Loss: 0.505123

Epoch 653/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00946]
Epoch 653/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.75it/s]

End of Epoch 653 | Train Loss: 0.052345 | Val Loss: 0.153507

Epoch 654/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00842]
Epoch 654/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.14it/s]

End of Epoch 654 | Train Loss: 0.051875 | Val Loss: 0.394438

Epoch 655/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0235]
Epoch 655/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.17it/s]

End of Epoch 655 | Train Loss: 0.064627 | Val Loss: 0.323422

Epoch 656/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0151]
Epoch 656/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.00it/s]

End of Epoch 656 | Train Loss: 0.053120 | Val Loss: 0.305834

Epoch 657/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00966]
Epoch 657/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.19it/s]

End of Epoch 657 | Train Loss: 0.052317 | Val Loss: 0.421147

Epoch 658/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.174]
Epoch 658/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.71it/s]

End of Epoch 658 | Train Loss: 0.067753 | Val Loss: 0.350674

Epoch 659/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0253]
Epoch 659/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.70it/s]

End of Epoch 659 | Train Loss: 0.052272 | Val Loss: 0.264425

Epoch 660/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0101]
Epoch 660/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 660 | Train Loss: 0.047406 | Val Loss: 0.333836

Epoch 661/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0177]
Epoch 661/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.07it/s]

End of Epoch 661 | Train Loss: 0.055895 | Val Loss: 0.386504

Epoch 662/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00966]
Epoch 662/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.81it/s]

End of Epoch 662 | Train Loss: 0.054975 | Val Loss: 0.401142

Epoch 663/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0111]
Epoch 663/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 663 | Train Loss: 0.062625 | Val Loss: 0.392058

Epoch 664/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0119]
Epoch 664/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.82it/s]

End of Epoch 664 | Train Loss: 0.055000 | Val Loss: 0.558848

Epoch 665/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.0506]
Epoch 665/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.68it/s]

End of Epoch 665 | Train Loss: 0.054674 | Val Loss: 0.349210

Epoch 666/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.057]
Epoch 666/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.53it/s]

End of Epoch 666 | Train Loss: 0.063909 | Val Loss: 0.565046

Epoch 667/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.145]
Epoch 667/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 667 | Train Loss: 0.067381 | Val Loss: 0.226207

Epoch 668/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0355]
Epoch 668/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.21it/s]

End of Epoch 668 | Train Loss: 0.064629 | Val Loss: 0.576048

Epoch 669/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0313]
Epoch 669/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 669 | Train Loss: 0.054931 | Val Loss: 0.233857

Epoch 670/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.44it/s, loss=0.00843]
Epoch 670/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.51it/s]

End of Epoch 670 | Train Loss: 0.051303 | Val Loss: 0.247211

Epoch 671/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0186]
Epoch 671/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 671 | Train Loss: 0.046802 | Val Loss: 0.468359

Epoch 672/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0113]
Epoch 672/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.75it/s]

End of Epoch 672 | Train Loss: 0.054511 | Val Loss: 0.486627

Epoch 673/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0683]
Epoch 673/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.85it/s]

End of Epoch 673 | Train Loss: 0.060156 | Val Loss: 0.239917

Epoch 674/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0116]
Epoch 674/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 674 | Train Loss: 0.046312 | Val Loss: 0.445320

Epoch 675/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0105]
Epoch 675/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 675 | Train Loss: 0.056631 | Val Loss: 0.543619

Epoch 676/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0085]
Epoch 676/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 676 | Train Loss: 0.045698 | Val Loss: 0.274378

Epoch 677/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.049]
Epoch 677/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.10it/s]

End of Epoch 677 | Train Loss: 0.071331 | Val Loss: 0.490875

Epoch 678/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0121]
Epoch 678/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 678 | Train Loss: 0.055433 | Val Loss: 0.356024

Epoch 679/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0508]
Epoch 679/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 679 | Train Loss: 0.067462 | Val Loss: 0.352277

Epoch 680/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00875]
Epoch 680/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.52it/s]

End of Epoch 680 | Train Loss: 0.054117 | Val Loss: 0.449952

Epoch 681/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0402]
Epoch 681/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 681 | Train Loss: 0.057024 | Val Loss: 0.355575

Epoch 682/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00959]
Epoch 682/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 682 | Train Loss: 0.049363 | Val Loss: 0.388049

Epoch 683/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0227]
Epoch 683/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 683 | Train Loss: 0.048696 | Val Loss: 0.382005

Epoch 684/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0113]
Epoch 684/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.96it/s]

End of Epoch 684 | Train Loss: 0.046068 | Val Loss: 0.505325

Epoch 685/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0096]
Epoch 685/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 685 | Train Loss: 0.049695 | Val Loss: 0.335052

Epoch 686/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.00987]
Epoch 686/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 686 | Train Loss: 0.049882 | Val Loss: 0.261179

Epoch 687/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00964]
Epoch 687/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.35it/s]

End of Epoch 687 | Train Loss: 0.055814 | Val Loss: 0.227556

Epoch 688/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.47it/s, loss=0.00898]
Epoch 688/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.28it/s]

End of Epoch 688 | Train Loss: 0.052449 | Val Loss: 0.398958

Epoch 689/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00977]
Epoch 689/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 689 | Train Loss: 0.054130 | Val Loss: 0.311179

Epoch 690/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.00932]
Epoch 690/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.32it/s]

End of Epoch 690 | Train Loss: 0.055980 | Val Loss: 0.216223

Epoch 691/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.00978]
Epoch 691/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 691 | Train Loss: 0.055189 | Val Loss: 0.267004

Epoch 692/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00935]
Epoch 692/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 692 | Train Loss: 0.059500 | Val Loss: 0.409359

Epoch 693/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.47it/s, loss=0.0101]
Epoch 693/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 693 | Train Loss: 0.056134 | Val Loss: 0.278808

Epoch 694/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.36it/s, loss=0.0116]
Epoch 694/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.31it/s]

End of Epoch 694 | Train Loss: 0.054121 | Val Loss: 0.388527

Epoch 695/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00944]
Epoch 695/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 695 | Train Loss: 0.059536 | Val Loss: 0.382151

Epoch 696/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.152]
Epoch 696/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 696 | Train Loss: 0.057808 | Val Loss: 0.343908

Epoch 697/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00869]
Epoch 697/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.10it/s]

End of Epoch 697 | Train Loss: 0.059291 | Val Loss: 0.417692

Epoch 698/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.40it/s, loss=0.0101]
Epoch 698/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.62it/s]

End of Epoch 698 | Train Loss: 0.050295 | Val Loss: 0.403892

Epoch 699/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0087]
Epoch 699/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.87it/s]

End of Epoch 699 | Train Loss: 0.041082 | Val Loss: 0.317939

Epoch 700/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0142]
Epoch 700/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 700 | Train Loss: 0.060579 | Val Loss: 0.617858

Epoch 701/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0109]
Epoch 701/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 701 | Train Loss: 0.052062 | Val Loss: 0.486518

Epoch 702/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00876]
Epoch 702/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.63it/s]

End of Epoch 702 | Train Loss: 0.048498 | Val Loss: 0.451330

Epoch 703/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.33]
Epoch 703/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.13it/s]

End of Epoch 703 | Train Loss: 0.055185 | Val Loss: 0.318410

Epoch 704/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.0694]
Epoch 704/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 704 | Train Loss: 0.053519 | Val Loss: 0.493430

Epoch 705/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0103]
Epoch 705/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.68it/s]

End of Epoch 705 | Train Loss: 0.058237 | Val Loss: 0.308234

Epoch 706/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.129]
Epoch 706/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.95it/s]

End of Epoch 706 | Train Loss: 0.050272 | Val Loss: 0.208764

Epoch 707/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00928]
Epoch 707/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.01it/s]

End of Epoch 707 | Train Loss: 0.045350 | Val Loss: 0.431908

Epoch 708/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.389]
Epoch 708/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.25it/s]

End of Epoch 708 | Train Loss: 0.058130 | Val Loss: 0.374695

Epoch 709/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0127]
Epoch 709/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 709 | Train Loss: 0.062609 | Val Loss: 0.322100

Epoch 710/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00953]
Epoch 710/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.41it/s]

End of Epoch 710 | Train Loss: 0.045414 | Val Loss: 0.400948

Epoch 711/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0224]
Epoch 711/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 711 | Train Loss: 0.049299 | Val Loss: 0.180715

Epoch 712/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0097]
Epoch 712/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.83it/s]

End of Epoch 712 | Train Loss: 0.045176 | Val Loss: 0.267966

Epoch 713/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00889]
Epoch 713/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.78it/s]

End of Epoch 713 | Train Loss: 0.057532 | Val Loss: 0.423291

Epoch 714/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0162]
Epoch 714/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 714 | Train Loss: 0.052961 | Val Loss: 0.465995

Epoch 715/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0154]
Epoch 715/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.25it/s]

End of Epoch 715 | Train Loss: 0.045809 | Val Loss: 0.585803

Epoch 716/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0229]
Epoch 716/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.04it/s]

End of Epoch 716 | Train Loss: 0.051000 | Val Loss: 0.229075

Epoch 717/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00847]
Epoch 717/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.29it/s]

End of Epoch 717 | Train Loss: 0.046834 | Val Loss: 0.305170

Epoch 718/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.0199]
Epoch 718/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 718 | Train Loss: 0.056702 | Val Loss: 0.284262

Epoch 719/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0118]
Epoch 719/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.52it/s]

End of Epoch 719 | Train Loss: 0.046622 | Val Loss: 0.312105

Epoch 720/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.0323]
Epoch 720/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.87it/s]

End of Epoch 720 | Train Loss: 0.060662 | Val Loss: 0.638193

Epoch 721/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0096]
Epoch 721/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.91it/s]

End of Epoch 721 | Train Loss: 0.046607 | Val Loss: 0.337531

Epoch 722/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00945]
Epoch 722/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.33it/s]

End of Epoch 722 | Train Loss: 0.048220 | Val Loss: 0.456127

Epoch 723/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.0203]
Epoch 723/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.43it/s]

End of Epoch 723 | Train Loss: 0.057944 | Val Loss: 0.378472

Epoch 724/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0124]
Epoch 724/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 724 | Train Loss: 0.044712 | Val Loss: 0.259299

Epoch 725/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00937]
Epoch 725/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 725 | Train Loss: 0.050324 | Val Loss: 0.316016

Epoch 726/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00799]
Epoch 726/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.75it/s]

End of Epoch 726 | Train Loss: 0.048700 | Val Loss: 0.518586

Epoch 727/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.197]
Epoch 727/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 727 | Train Loss: 0.050165 | Val Loss: 0.434962

Epoch 728/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0133]
Epoch 728/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.67it/s]

End of Epoch 728 | Train Loss: 0.062740 | Val Loss: 0.314670

Epoch 729/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0198]
Epoch 729/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.40it/s]

End of Epoch 729 | Train Loss: 0.054639 | Val Loss: 0.275512

Epoch 730/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00827]
Epoch 730/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 730 | Train Loss: 0.049813 | Val Loss: 0.232456

Epoch 731/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0124]
Epoch 731/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 731 | Train Loss: 0.043416 | Val Loss: 0.404190

Epoch 732/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0085]
Epoch 732/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 732 | Train Loss: 0.058955 | Val Loss: 0.315842

Epoch 733/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.742]
Epoch 733/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.20it/s]

End of Epoch 733 | Train Loss: 0.054723 | Val Loss: 0.362717

Epoch 734/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0143]
Epoch 734/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 734 | Train Loss: 0.058040 | Val Loss: 0.248064

Epoch 735/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.00812]
Epoch 735/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 735 | Train Loss: 0.053941 | Val Loss: 0.534685

Epoch 736/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0159]
Epoch 736/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.56it/s]

End of Epoch 736 | Train Loss: 0.058204 | Val Loss: 0.629598

Epoch 737/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0128]
Epoch 737/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 737 | Train Loss: 0.060080 | Val Loss: 0.386174

Epoch 738/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0403]
Epoch 738/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 738 | Train Loss: 0.054323 | Val Loss: 0.583742

Epoch 739/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.042]
Epoch 739/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 739 | Train Loss: 0.055101 | Val Loss: 0.468690

Epoch 740/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.183]
Epoch 740/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.73it/s]

End of Epoch 740 | Train Loss: 0.052055 | Val Loss: 0.589347

Epoch 741/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0131]
Epoch 741/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.34it/s]

End of Epoch 741 | Train Loss: 0.048809 | Val Loss: 0.274028

Epoch 742/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00917]
Epoch 742/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.61it/s]

End of Epoch 742 | Train Loss: 0.048529 | Val Loss: 0.323220

Epoch 743/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0614]
Epoch 743/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.10it/s]

End of Epoch 743 | Train Loss: 0.048811 | Val Loss: 0.349159

Epoch 744/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0124]
Epoch 744/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 744 | Train Loss: 0.046472 | Val Loss: 0.537632

Epoch 745/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.43it/s, loss=0.0351]
Epoch 745/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.85it/s]

End of Epoch 745 | Train Loss: 0.046056 | Val Loss: 0.545799

Epoch 746/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0455]
Epoch 746/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 746 | Train Loss: 0.053019 | Val Loss: 0.395268

Epoch 747/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.40it/s, loss=0.0175]
Epoch 747/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.44it/s]

End of Epoch 747 | Train Loss: 0.048196 | Val Loss: 0.325239

Epoch 748/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.274]
Epoch 748/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.09it/s]

End of Epoch 748 | Train Loss: 0.053531 | Val Loss: 0.300883

Epoch 749/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00737]
Epoch 749/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.75it/s]

End of Epoch 749 | Train Loss: 0.058993 | Val Loss: 0.374442

Epoch 750/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.152]
Epoch 750/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 750 | Train Loss: 0.048939 | Val Loss: 0.302455

Epoch 751/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00716]
Epoch 751/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 751 | Train Loss: 0.055104 | Val Loss: 0.491293

Epoch 752/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0574]
Epoch 752/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 752 | Train Loss: 0.061687 | Val Loss: 0.636320

Epoch 753/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0294]
Epoch 753/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 753 | Train Loss: 0.052729 | Val Loss: 0.257501

Epoch 754/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0136]
Epoch 754/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.29it/s]

End of Epoch 754 | Train Loss: 0.051041 | Val Loss: 0.259789

Epoch 755/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0142]
Epoch 755/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 755 | Train Loss: 0.058147 | Val Loss: 0.767887

Epoch 756/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0128]
Epoch 756/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.10it/s]

End of Epoch 756 | Train Loss: 0.053734 | Val Loss: 0.248282

Epoch 757/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0144]
Epoch 757/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.33it/s]

End of Epoch 757 | Train Loss: 0.048685 | Val Loss: 0.195411

Epoch 758/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00904]
Epoch 758/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.78it/s]

End of Epoch 758 | Train Loss: 0.051405 | Val Loss: 0.220808

Epoch 759/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0293]
Epoch 759/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 759 | Train Loss: 0.047513 | Val Loss: 0.284494

Epoch 760/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0375]
Epoch 760/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.77it/s]

End of Epoch 760 | Train Loss: 0.046686 | Val Loss: 0.362741

Epoch 761/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00938]
Epoch 761/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 761 | Train Loss: 0.047945 | Val Loss: 0.255466

Epoch 781/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.022]
Epoch 781/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 781 | Train Loss: 0.051963 | Val Loss: 0.232881

Epoch 782/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.0139]
Epoch 782/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.26it/s]

End of Epoch 782 | Train Loss: 0.046217 | Val Loss: 0.489230

Epoch 783/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00745]
Epoch 783/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 783 | Train Loss: 0.055537 | Val Loss: 0.286285

Epoch 784/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.275]
Epoch 784/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.03it/s]

End of Epoch 784 | Train Loss: 0.047396 | Val Loss: 0.512643

Epoch 785/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.00753]
Epoch 785/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 785 | Train Loss: 0.051989 | Val Loss: 0.296149

Epoch 786/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00816]
Epoch 786/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.31it/s]

End of Epoch 786 | Train Loss: 0.047075 | Val Loss: 0.246735

Epoch 787/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.149]
Epoch 787/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.01it/s]

End of Epoch 787 | Train Loss: 0.054944 | Val Loss: 0.434107

Epoch 788/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0266]
Epoch 788/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 788 | Train Loss: 0.054359 | Val Loss: 0.472569

Epoch 789/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0708]
Epoch 789/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.09it/s]

End of Epoch 789 | Train Loss: 0.045709 | Val Loss: 0.462548

Epoch 790/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0279]
Epoch 790/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 790 | Train Loss: 0.050158 | Val Loss: 0.234221

Epoch 791/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00769]
Epoch 791/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.93it/s]

End of Epoch 791 | Train Loss: 0.053208 | Val Loss: 0.340837

Epoch 792/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.00886]
Epoch 792/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.66it/s]

End of Epoch 792 | Train Loss: 0.042934 | Val Loss: 0.629956

Epoch 793/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0144]
Epoch 793/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.28it/s]

End of Epoch 793 | Train Loss: 0.053506 | Val Loss: 0.317205

Epoch 794/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00845]
Epoch 794/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.19it/s]

End of Epoch 794 | Train Loss: 0.052949 | Val Loss: 0.186490

Epoch 795/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.0372]
Epoch 795/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.31it/s]

End of Epoch 795 | Train Loss: 0.051451 | Val Loss: 0.467143

Epoch 796/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.682]
Epoch 796/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 796 | Train Loss: 0.060408 | Val Loss: 0.389802

Epoch 797/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0192]
Epoch 797/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.77it/s]

End of Epoch 797 | Train Loss: 0.063268 | Val Loss: 0.551114

Epoch 798/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.43it/s, loss=0.00713]
Epoch 798/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 798 | Train Loss: 0.046785 | Val Loss: 0.172722

Epoch 799/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0091]
Epoch 799/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 799 | Train Loss: 0.044326 | Val Loss: 0.244104

Epoch 800/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.014]
Epoch 800/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.76it/s]

End of Epoch 800 | Train Loss: 0.052858 | Val Loss: 0.246475

Epoch 801/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00901]
Epoch 801/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.27it/s]

End of Epoch 801 | Train Loss: 0.048832 | Val Loss: 0.367459

Epoch 802/10000 [Train]:  62%|██████▏   | 56/90 [00:03<00:01, 18.30it/s, loss=0.0168]IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

Epoch 1035/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0223]
Epoch 1035/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.41it/s]

End of Epoch 1035 | Train Loss: 0.044354 | Val Loss: 0.520447

Epoch 1036/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0123]
Epoch 1036/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 1036 | Train Loss: 0.037774 | Val Loss: 0.211528

Epoch 1037/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.479]
Epoch 1037/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.22it/s]

End of Epoch 1037 | Train Loss: 0.050271 | Val Loss: 0.425538

Epoch 1038/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0678]
Epoch 1038/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.36it/s]

End of Epoch 1038 | Train Loss: 0.043760 | Val Loss: 0.358015

Epoch 1039/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00699]
Epoch 1039/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.52it/s]

End of Epoch 1039 | Train Loss: 0.037790 | Val Loss: 0.683819

Epoch 1040/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0647]
Epoch 1040/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 1040 | Train Loss: 0.042471 | Val Loss: 0.423018

Epoch 1041/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00602]
Epoch 1041/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.55it/s]

End of Epoch 1041 | Train Loss: 0.041782 | Val Loss: 0.395205

Epoch 1042/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0159]
Epoch 1042/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 1042 | Train Loss: 0.040126 | Val Loss: 0.572505

Epoch 1043/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0117]
Epoch 1043/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.26it/s]

End of Epoch 1043 | Train Loss: 0.042916 | Val Loss: 0.446821

Epoch 1044/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00698]
Epoch 1044/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1044 | Train Loss: 0.026981 | Val Loss: 0.378762

Epoch 1045/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0242]
Epoch 1045/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.35it/s]

End of Epoch 1045 | Train Loss: 0.046339 | Val Loss: 0.257678

Epoch 1046/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0169]
Epoch 1046/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 1046 | Train Loss: 0.036740 | Val Loss: 0.718494

Epoch 1047/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00771]
Epoch 1047/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.70it/s]

End of Epoch 1047 | Train Loss: 0.037784 | Val Loss: 0.563753

Epoch 1048/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00815]
Epoch 1048/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 1048 | Train Loss: 0.035750 | Val Loss: 0.290799

Epoch 1049/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00561]
Epoch 1049/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.80it/s]

End of Epoch 1049 | Train Loss: 0.044401 | Val Loss: 0.233300

Epoch 1050/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0078]
Epoch 1050/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.16it/s]

End of Epoch 1050 | Train Loss: 0.045346 | Val Loss: 0.433136

Epoch 1051/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00879]
Epoch 1051/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.88it/s]

End of Epoch 1051 | Train Loss: 0.048153 | Val Loss: 0.627638

Epoch 1052/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00592]
Epoch 1052/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 1052 | Train Loss: 0.033227 | Val Loss: 0.382597

Epoch 1053/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00726]
Epoch 1053/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.10it/s]

End of Epoch 1053 | Train Loss: 0.037670 | Val Loss: 0.387921

Epoch 1054/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.025]
Epoch 1054/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 1054 | Train Loss: 0.041878 | Val Loss: 0.505835

Epoch 1055/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0082]
Epoch 1055/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 1055 | Train Loss: 0.036840 | Val Loss: 0.313275

Epoch 1056/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00731]
Epoch 1056/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 1056 | Train Loss: 0.034215 | Val Loss: 0.526360

Epoch 1057/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0114]
Epoch 1057/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.54it/s]

End of Epoch 1057 | Train Loss: 0.039377 | Val Loss: 0.396179

Epoch 1058/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.006]
Epoch 1058/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.19it/s]

End of Epoch 1058 | Train Loss: 0.039427 | Val Loss: 0.260406

Epoch 1059/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.01]
Epoch 1059/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 1059 | Train Loss: 0.046845 | Val Loss: 0.537842

Epoch 1060/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00906]
Epoch 1060/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.39it/s]

End of Epoch 1060 | Train Loss: 0.044251 | Val Loss: 0.524334

Epoch 1061/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.213]
Epoch 1061/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.27it/s]

End of Epoch 1061 | Train Loss: 0.043382 | Val Loss: 0.872334

Epoch 1062/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0066]
Epoch 1062/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 1062 | Train Loss: 0.033839 | Val Loss: 0.400699

Epoch 1063/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0104]
Epoch 1063/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.19it/s]

End of Epoch 1063 | Train Loss: 0.049769 | Val Loss: 0.401751

Epoch 1064/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0208]
Epoch 1064/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.06it/s]

End of Epoch 1064 | Train Loss: 0.043688 | Val Loss: 0.277926

Epoch 1065/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0294]
Epoch 1065/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 1065 | Train Loss: 0.044351 | Val Loss: 0.330878

Epoch 1066/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.044]
Epoch 1066/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.18it/s]

End of Epoch 1066 | Train Loss: 0.045214 | Val Loss: 0.497971

Epoch 1067/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00764]
Epoch 1067/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 1067 | Train Loss: 0.036693 | Val Loss: 0.308498

Epoch 1068/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0086]
Epoch 1068/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 1068 | Train Loss: 0.036172 | Val Loss: 0.254678

Epoch 1069/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0389]
Epoch 1069/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.44it/s]

End of Epoch 1069 | Train Loss: 0.028202 | Val Loss: 0.710440

Epoch 1070/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00701]
Epoch 1070/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.01it/s]

End of Epoch 1070 | Train Loss: 0.036838 | Val Loss: 0.385830

Epoch 1071/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0262]
Epoch 1071/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.21it/s]

End of Epoch 1071 | Train Loss: 0.040721 | Val Loss: 0.221413

Epoch 1072/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0284]
Epoch 1072/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.50it/s]

End of Epoch 1072 | Train Loss: 0.044326 | Val Loss: 0.389872

Epoch 1073/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0138]
Epoch 1073/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 1073 | Train Loss: 0.031839 | Val Loss: 0.321222

Epoch 1074/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0202]
Epoch 1074/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.38it/s]

End of Epoch 1074 | Train Loss: 0.037771 | Val Loss: 0.362290

Epoch 1075/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00919]
Epoch 1075/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 1075 | Train Loss: 0.044264 | Val Loss: 0.421131

Epoch 1076/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0063]
Epoch 1076/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 1076 | Train Loss: 0.037363 | Val Loss: 0.373941

Epoch 1077/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0157]
Epoch 1077/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.90it/s]

End of Epoch 1077 | Train Loss: 0.042525 | Val Loss: 0.258948

Epoch 1078/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0222]
Epoch 1078/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.82it/s]

End of Epoch 1078 | Train Loss: 0.049530 | Val Loss: 0.609267

Epoch 1079/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0986]
Epoch 1079/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.90it/s]

End of Epoch 1079 | Train Loss: 0.034681 | Val Loss: 0.141930

Epoch 1080/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0136]
Epoch 1080/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 1080 | Train Loss: 0.038025 | Val Loss: 0.737344

Epoch 1081/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0922]
Epoch 1081/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 1081 | Train Loss: 0.041523 | Val Loss: 0.630851

Epoch 1082/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00511]
Epoch 1082/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.23it/s]

End of Epoch 1082 | Train Loss: 0.032790 | Val Loss: 0.215941

Epoch 1083/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00692]
Epoch 1083/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 1083 | Train Loss: 0.038641 | Val Loss: 0.392058

Epoch 1084/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00821]
Epoch 1084/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.49it/s]

End of Epoch 1084 | Train Loss: 0.047184 | Val Loss: 0.590052

Epoch 1085/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00588]
Epoch 1085/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 1085 | Train Loss: 0.041217 | Val Loss: 0.571202

Epoch 1086/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00564]
Epoch 1086/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 1086 | Train Loss: 0.050964 | Val Loss: 0.364185

Epoch 1087/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0205]
Epoch 1087/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 1087 | Train Loss: 0.036582 | Val Loss: 0.584422

Epoch 1088/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0202]
Epoch 1088/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.48it/s]

End of Epoch 1088 | Train Loss: 0.036329 | Val Loss: 0.540319

Epoch 1089/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.012]
Epoch 1089/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 1089 | Train Loss: 0.037600 | Val Loss: 0.132290

Epoch 1090/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.0181]
Epoch 1090/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1090 | Train Loss: 0.033361 | Val Loss: 0.386357

Epoch 1091/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00579]
Epoch 1091/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.18it/s]

End of Epoch 1091 | Train Loss: 0.042961 | Val Loss: 0.312708

Epoch 1092/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00708]
Epoch 1092/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.62it/s]

End of Epoch 1092 | Train Loss: 0.038836 | Val Loss: 0.319186

Epoch 1093/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0219]
Epoch 1093/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.56it/s]

End of Epoch 1093 | Train Loss: 0.028062 | Val Loss: 0.336046

Epoch 1094/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00594]
Epoch 1094/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 1094 | Train Loss: 0.037745 | Val Loss: 0.564035

Epoch 1095/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0065]
Epoch 1095/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.56it/s]

End of Epoch 1095 | Train Loss: 0.041815 | Val Loss: 0.223760

Epoch 1096/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00581]
Epoch 1096/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 1096 | Train Loss: 0.039749 | Val Loss: 0.594944

Epoch 1097/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0169]
Epoch 1097/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 1097 | Train Loss: 0.042480 | Val Loss: 0.511782

Epoch 1098/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0795]
Epoch 1098/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 1098 | Train Loss: 0.039101 | Val Loss: 0.327579

Epoch 1099/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0121]
Epoch 1099/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 1099 | Train Loss: 0.036324 | Val Loss: 0.345195

Epoch 1100/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0174]
Epoch 1100/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 1100 | Train Loss: 0.038691 | Val Loss: 0.197042

Epoch 1101/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0653]
Epoch 1101/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.29it/s]

End of Epoch 1101 | Train Loss: 0.039577 | Val Loss: 0.620972

Epoch 1102/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00965]
Epoch 1102/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.61it/s]

End of Epoch 1102 | Train Loss: 0.036482 | Val Loss: 0.424992

Epoch 1103/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00681]
Epoch 1103/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.27it/s]

End of Epoch 1103 | Train Loss: 0.040631 | Val Loss: 0.584200

Epoch 1104/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00516]
Epoch 1104/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.87it/s]

End of Epoch 1104 | Train Loss: 0.037350 | Val Loss: 0.395144

Epoch 1105/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00964]
Epoch 1105/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.19it/s]

End of Epoch 1105 | Train Loss: 0.042127 | Val Loss: 0.507976

Epoch 1106/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.225]
Epoch 1106/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.43it/s]

End of Epoch 1106 | Train Loss: 0.049602 | Val Loss: 0.490091

Epoch 1107/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00738]
Epoch 1107/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.25it/s]

End of Epoch 1107 | Train Loss: 0.046609 | Val Loss: 0.329742

Epoch 1108/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.832]
Epoch 1108/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.38it/s]

End of Epoch 1108 | Train Loss: 0.046050 | Val Loss: 0.419801

Epoch 1109/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.038]
Epoch 1109/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.72it/s]

End of Epoch 1109 | Train Loss: 0.047829 | Val Loss: 0.681067

Epoch 1110/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0063]
Epoch 1110/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 1110 | Train Loss: 0.034774 | Val Loss: 0.531360

Epoch 1111/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00864]
Epoch 1111/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.42it/s]

End of Epoch 1111 | Train Loss: 0.038164 | Val Loss: 0.383145

Epoch 1112/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.00622]
Epoch 1112/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 1112 | Train Loss: 0.039166 | Val Loss: 0.557654

Epoch 1113/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.00962]
Epoch 1113/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.96it/s]

End of Epoch 1113 | Train Loss: 0.040991 | Val Loss: 0.324468

Epoch 1114/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00611]
Epoch 1114/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 1114 | Train Loss: 0.042445 | Val Loss: 0.604795

Epoch 1115/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0136]
Epoch 1115/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.05it/s]

End of Epoch 1115 | Train Loss: 0.045559 | Val Loss: 0.254576

Epoch 1116/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0129]
Epoch 1116/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 1116 | Train Loss: 0.036429 | Val Loss: 0.674811

Epoch 1117/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0258]
Epoch 1117/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 1117 | Train Loss: 0.034175 | Val Loss: 0.520937

Epoch 1118/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00878]
Epoch 1118/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 1118 | Train Loss: 0.037613 | Val Loss: 0.313461

Epoch 1119/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00598]
Epoch 1119/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 1119 | Train Loss: 0.035107 | Val Loss: 0.618219

Epoch 1120/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0239]
Epoch 1120/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 1120 | Train Loss: 0.034390 | Val Loss: 0.457063

Epoch 1121/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00782]
Epoch 1121/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.20it/s]

End of Epoch 1121 | Train Loss: 0.039226 | Val Loss: 0.446484

Epoch 1122/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00518]
Epoch 1122/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.58it/s]

End of Epoch 1122 | Train Loss: 0.041954 | Val Loss: 0.833578

Epoch 1123/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0121]
Epoch 1123/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 1123 | Train Loss: 0.041946 | Val Loss: 0.841604

Epoch 1124/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.939]
Epoch 1124/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1124 | Train Loss: 0.052504 | Val Loss: 0.417271

Epoch 1125/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0197]
Epoch 1125/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.84it/s]

End of Epoch 1125 | Train Loss: 0.046969 | Val Loss: 0.202167

Epoch 1126/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0464]
Epoch 1126/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 1126 | Train Loss: 0.040913 | Val Loss: 0.286520

Epoch 1127/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00733]
Epoch 1127/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.13it/s]

End of Epoch 1127 | Train Loss: 0.043967 | Val Loss: 0.285088

Epoch 1128/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00675]
Epoch 1128/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.73it/s]

End of Epoch 1128 | Train Loss: 0.039995 | Val Loss: 0.419126

Epoch 1129/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00858]
Epoch 1129/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 1129 | Train Loss: 0.042714 | Val Loss: 0.388140

Epoch 1130/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0611]
Epoch 1130/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 1130 | Train Loss: 0.042540 | Val Loss: 0.409378

Epoch 1131/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0127]
Epoch 1131/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.60it/s]

End of Epoch 1131 | Train Loss: 0.040938 | Val Loss: 0.470018

Epoch 1132/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0156]
Epoch 1132/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 1132 | Train Loss: 0.047253 | Val Loss: 0.424722

Epoch 1133/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00693]
Epoch 1133/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.76it/s]

End of Epoch 1133 | Train Loss: 0.041290 | Val Loss: 0.366165

Epoch 1134/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0205]
Epoch 1134/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.76it/s]

End of Epoch 1134 | Train Loss: 0.035225 | Val Loss: 0.493884

Epoch 1135/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00731]
Epoch 1135/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.67it/s]

End of Epoch 1135 | Train Loss: 0.037236 | Val Loss: 0.399017

Epoch 1136/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0332]
Epoch 1136/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 1136 | Train Loss: 0.036497 | Val Loss: 0.368977

Epoch 1137/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00568]
Epoch 1137/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 1137 | Train Loss: 0.034030 | Val Loss: 0.236020

Epoch 1138/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00952]
Epoch 1138/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.39it/s]

End of Epoch 1138 | Train Loss: 0.037559 | Val Loss: 0.454855

Epoch 1139/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0057]
Epoch 1139/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.24it/s]

End of Epoch 1139 | Train Loss: 0.034362 | Val Loss: 0.423269

Epoch 1140/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00604]
Epoch 1140/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.31it/s]

End of Epoch 1140 | Train Loss: 0.039292 | Val Loss: 0.178868

Epoch 1141/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0445]
Epoch 1141/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1141 | Train Loss: 0.034539 | Val Loss: 0.446206

Epoch 1142/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0157]
Epoch 1142/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 1142 | Train Loss: 0.038116 | Val Loss: 0.188883

Epoch 1143/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0065]
Epoch 1143/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.42it/s]

End of Epoch 1143 | Train Loss: 0.043181 | Val Loss: 0.347838

Epoch 1144/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0075]
Epoch 1144/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1144 | Train Loss: 0.038545 | Val Loss: 0.359934

Epoch 1145/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0182]
Epoch 1145/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.80it/s]

End of Epoch 1145 | Train Loss: 0.032040 | Val Loss: 0.467665

Epoch 1146/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0062]
Epoch 1146/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.34it/s]

End of Epoch 1146 | Train Loss: 0.036477 | Val Loss: 0.495475

Epoch 1147/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0294]
Epoch 1147/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.92it/s]

End of Epoch 1147 | Train Loss: 0.038059 | Val Loss: 0.367981

Epoch 1148/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0142]
Epoch 1148/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.99it/s]

End of Epoch 1148 | Train Loss: 0.039253 | Val Loss: 0.425936

Epoch 1149/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.48it/s, loss=0.00618]
Epoch 1149/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 1149 | Train Loss: 0.031432 | Val Loss: 0.567167

Epoch 1150/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.42it/s, loss=0.044]
Epoch 1150/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.21it/s]

End of Epoch 1150 | Train Loss: 0.034226 | Val Loss: 0.357155

Epoch 1151/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00735]
Epoch 1151/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.50it/s]

End of Epoch 1151 | Train Loss: 0.032984 | Val Loss: 0.385409

Epoch 1152/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.458]
Epoch 1152/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 1152 | Train Loss: 0.039298 | Val Loss: 0.364567

Epoch 1153/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00639]
Epoch 1153/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 1153 | Train Loss: 0.042780 | Val Loss: 0.517343

Epoch 1154/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00682]
Epoch 1154/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 1154 | Train Loss: 0.031668 | Val Loss: 0.430820

Epoch 1155/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00613]
Epoch 1155/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 1155 | Train Loss: 0.033789 | Val Loss: 0.280974

Epoch 1156/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0054]
Epoch 1156/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.94it/s]

End of Epoch 1156 | Train Loss: 0.034411 | Val Loss: 0.503576

Epoch 1157/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00542]
Epoch 1157/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.07it/s]

End of Epoch 1157 | Train Loss: 0.039746 | Val Loss: 0.293999

Epoch 1158/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00649]
Epoch 1158/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 1158 | Train Loss: 0.043855 | Val Loss: 0.203922

Epoch 1159/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00553]
Epoch 1159/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.16it/s]

End of Epoch 1159 | Train Loss: 0.039940 | Val Loss: 0.461384

Epoch 1160/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00562]
Epoch 1160/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 1160 | Train Loss: 0.044191 | Val Loss: 0.406305

Epoch 1161/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00597]
Epoch 1161/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.29it/s]

End of Epoch 1161 | Train Loss: 0.042732 | Val Loss: 0.265774

Epoch 1162/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00474]
Epoch 1162/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 1162 | Train Loss: 0.038266 | Val Loss: 0.461814

Epoch 1163/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0161]
Epoch 1163/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.08it/s]

End of Epoch 1163 | Train Loss: 0.035309 | Val Loss: 0.549706

Epoch 1164/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0411]
Epoch 1164/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.15it/s]

End of Epoch 1164 | Train Loss: 0.034354 | Val Loss: 0.642037

Epoch 1165/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00874]
Epoch 1165/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.72it/s]

End of Epoch 1165 | Train Loss: 0.039249 | Val Loss: 0.571119

Epoch 1166/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0182]
Epoch 1166/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 1166 | Train Loss: 0.034614 | Val Loss: 0.562014

Epoch 1167/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0259]
Epoch 1167/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 1167 | Train Loss: 0.033445 | Val Loss: 0.495477

Epoch 1168/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0049]
Epoch 1168/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.36it/s]

End of Epoch 1168 | Train Loss: 0.042371 | Val Loss: 0.382393

Epoch 1169/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00896]
Epoch 1169/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.52it/s]

End of Epoch 1169 | Train Loss: 0.039701 | Val Loss: 0.352898

Epoch 1170/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00915]
Epoch 1170/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.26it/s]

End of Epoch 1170 | Train Loss: 0.034973 | Val Loss: 0.507253

Epoch 1171/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.443]
Epoch 1171/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 1171 | Train Loss: 0.040932 | Val Loss: 0.510707

Epoch 1172/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00699]
Epoch 1172/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.20it/s]

End of Epoch 1172 | Train Loss: 0.035857 | Val Loss: 0.381751

Epoch 1173/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00873]
Epoch 1173/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 1173 | Train Loss: 0.036169 | Val Loss: 0.632300

Epoch 1174/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0325]
Epoch 1174/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 1174 | Train Loss: 0.039883 | Val Loss: 0.271137

Epoch 1175/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00536]
Epoch 1175/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 1175 | Train Loss: 0.027249 | Val Loss: 0.244537

Epoch 1176/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00607]
Epoch 1176/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.76it/s]

End of Epoch 1176 | Train Loss: 0.030873 | Val Loss: 0.380968

Epoch 1177/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00456]
Epoch 1177/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 1177 | Train Loss: 0.036614 | Val Loss: 0.440587

Epoch 1178/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00557]
Epoch 1178/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.43it/s]

End of Epoch 1178 | Train Loss: 0.035440 | Val Loss: 0.277397

Epoch 1179/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0519]
Epoch 1179/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.78it/s]

End of Epoch 1179 | Train Loss: 0.041146 | Val Loss: 0.417581

Epoch 1180/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00659]
Epoch 1180/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.41it/s]

End of Epoch 1180 | Train Loss: 0.045388 | Val Loss: 0.317111

Epoch 1181/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0102]
Epoch 1181/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.40it/s]

End of Epoch 1181 | Train Loss: 0.035660 | Val Loss: 0.320910

Epoch 1182/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0153]
Epoch 1182/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.96it/s]

End of Epoch 1182 | Train Loss: 0.034035 | Val Loss: 0.448583

Epoch 1183/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00802]
Epoch 1183/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1183 | Train Loss: 0.029661 | Val Loss: 0.505583

Epoch 1184/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00739]
Epoch 1184/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 1184 | Train Loss: 0.032945 | Val Loss: 0.287091

Epoch 1185/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.168]
Epoch 1185/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.50it/s]

End of Epoch 1185 | Train Loss: 0.044139 | Val Loss: 0.319395

Epoch 1186/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.911]
Epoch 1186/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 1186 | Train Loss: 0.048913 | Val Loss: 0.570032

Epoch 1187/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0159]
Epoch 1187/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 1187 | Train Loss: 0.042937 | Val Loss: 0.480002

Epoch 1188/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00629]
Epoch 1188/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.81it/s]

End of Epoch 1188 | Train Loss: 0.038095 | Val Loss: 0.305706

Epoch 1189/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0072]
Epoch 1189/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 1189 | Train Loss: 0.039448 | Val Loss: 0.245368

Epoch 1190/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0127]
Epoch 1190/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.66it/s]

End of Epoch 1190 | Train Loss: 0.033101 | Val Loss: 0.336889

Epoch 1191/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0062]
Epoch 1191/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 1191 | Train Loss: 0.031372 | Val Loss: 0.335777

Epoch 1192/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0264]
Epoch 1192/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 1192 | Train Loss: 0.040590 | Val Loss: 0.219278

Epoch 1193/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0116]
Epoch 1193/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 1193 | Train Loss: 0.032584 | Val Loss: 0.407473

Epoch 1194/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0378]
Epoch 1194/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 1194 | Train Loss: 0.040661 | Val Loss: 0.503884

Epoch 1195/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0184]
Epoch 1195/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.63it/s]

End of Epoch 1195 | Train Loss: 0.029038 | Val Loss: 0.215254

Epoch 1196/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0131]
Epoch 1196/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.45it/s]

End of Epoch 1196 | Train Loss: 0.036892 | Val Loss: 0.222775

Epoch 1197/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.182]
Epoch 1197/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.65it/s]

End of Epoch 1197 | Train Loss: 0.034112 | Val Loss: 0.624975

Epoch 1198/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00602]
Epoch 1198/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 1198 | Train Loss: 0.046723 | Val Loss: 0.568850

Epoch 1199/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00476]
Epoch 1199/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 1199 | Train Loss: 0.032242 | Val Loss: 0.613421

Epoch 1200/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00732]
Epoch 1200/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 1200 | Train Loss: 0.039262 | Val Loss: 0.452009

Epoch 1201/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0291]
Epoch 1201/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.90it/s]

End of Epoch 1201 | Train Loss: 0.037050 | Val Loss: 0.304278

Epoch 1202/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0119]
Epoch 1202/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.40it/s]

End of Epoch 1202 | Train Loss: 0.040398 | Val Loss: 0.468534

Epoch 1203/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.017]
Epoch 1203/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.57it/s]

End of Epoch 1203 | Train Loss: 0.034157 | Val Loss: 0.370211

Epoch 1204/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.897]
Epoch 1204/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.08it/s]

End of Epoch 1204 | Train Loss: 0.040089 | Val Loss: 0.300222

Epoch 1205/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00637]
Epoch 1205/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 1205 | Train Loss: 0.042664 | Val Loss: 0.408457

Epoch 1206/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00618]
Epoch 1206/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.34it/s]

End of Epoch 1206 | Train Loss: 0.039164 | Val Loss: 0.454199

Epoch 1207/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0159]
Epoch 1207/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.68it/s]

End of Epoch 1207 | Train Loss: 0.034412 | Val Loss: 0.582865

Epoch 1208/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00564]
Epoch 1208/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 1208 | Train Loss: 0.032097 | Val Loss: 0.224294

Epoch 1209/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00539]
Epoch 1209/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.11it/s]

End of Epoch 1209 | Train Loss: 0.032121 | Val Loss: 0.408307

Epoch 1210/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00893]
Epoch 1210/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 1210 | Train Loss: 0.040727 | Val Loss: 0.310656

Epoch 1211/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.2]
Epoch 1211/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 1211 | Train Loss: 0.040459 | Val Loss: 0.351668

Epoch 1212/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00744]
Epoch 1212/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.89it/s]

End of Epoch 1212 | Train Loss: 0.049138 | Val Loss: 0.386009

Epoch 1213/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.0134]
Epoch 1213/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 1213 | Train Loss: 0.040533 | Val Loss: 0.726964

Epoch 1214/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0587]
Epoch 1214/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 1214 | Train Loss: 0.037899 | Val Loss: 0.286153

Epoch 1215/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00986]
Epoch 1215/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 1215 | Train Loss: 0.042361 | Val Loss: 0.321075

Epoch 1216/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0378]
Epoch 1216/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.23it/s]

End of Epoch 1216 | Train Loss: 0.040700 | Val Loss: 0.523114

Epoch 1217/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00752]
Epoch 1217/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 1217 | Train Loss: 0.033911 | Val Loss: 0.357181

Epoch 1218/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00636]
Epoch 1218/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 1218 | Train Loss: 0.032068 | Val Loss: 0.373335

Epoch 1219/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00623]
Epoch 1219/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.89it/s]

End of Epoch 1219 | Train Loss: 0.040674 | Val Loss: 0.344473

Epoch 1220/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00871]
Epoch 1220/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.34it/s]

End of Epoch 1220 | Train Loss: 0.033139 | Val Loss: 0.624618

Epoch 1221/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.39it/s, loss=0.00474]
Epoch 1221/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.14it/s]

End of Epoch 1221 | Train Loss: 0.032551 | Val Loss: 0.596096

Epoch 1222/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0224]
Epoch 1222/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 1222 | Train Loss: 0.030437 | Val Loss: 0.514901

Epoch 1223/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00961]
Epoch 1223/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 1223 | Train Loss: 0.042292 | Val Loss: 0.308077

Epoch 1224/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00582]
Epoch 1224/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 1224 | Train Loss: 0.030680 | Val Loss: 0.335599

Epoch 1225/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00553]
Epoch 1225/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 1225 | Train Loss: 0.030282 | Val Loss: 0.467559

Epoch 1226/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00487]
Epoch 1226/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 1226 | Train Loss: 0.041714 | Val Loss: 0.367297

Epoch 1227/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0585]
Epoch 1227/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.71it/s]

End of Epoch 1227 | Train Loss: 0.036744 | Val Loss: 0.368821

Epoch 1228/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0359]
Epoch 1228/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1228 | Train Loss: 0.041185 | Val Loss: 0.487834

Epoch 1229/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.0326]
Epoch 1229/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.04it/s]

End of Epoch 1229 | Train Loss: 0.040466 | Val Loss: 0.564311

Epoch 1230/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.136]
Epoch 1230/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 1230 | Train Loss: 0.037104 | Val Loss: 0.214363

Epoch 1231/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0105]
Epoch 1231/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 1231 | Train Loss: 0.035976 | Val Loss: 0.508550

Epoch 1232/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00667]
Epoch 1232/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.66it/s]

End of Epoch 1232 | Train Loss: 0.033862 | Val Loss: 0.451958

Epoch 1233/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.142]
Epoch 1233/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 1233 | Train Loss: 0.031538 | Val Loss: 0.584729

Epoch 1234/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00683]
Epoch 1234/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 1234 | Train Loss: 0.032577 | Val Loss: 0.343919

Epoch 1235/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00767]
Epoch 1235/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 1235 | Train Loss: 0.040388 | Val Loss: 0.514706

Epoch 1236/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0082]
Epoch 1236/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.01it/s]

End of Epoch 1236 | Train Loss: 0.032010 | Val Loss: 0.395573

Epoch 1237/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0116]
Epoch 1237/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.82it/s]

End of Epoch 1237 | Train Loss: 0.040665 | Val Loss: 0.225179

Epoch 1238/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0205]
Epoch 1238/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 1238 | Train Loss: 0.039955 | Val Loss: 0.273544

Epoch 1239/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00922]
Epoch 1239/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.97it/s]

End of Epoch 1239 | Train Loss: 0.038744 | Val Loss: 0.386661

Epoch 1240/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0193]
Epoch 1240/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.03it/s]

End of Epoch 1240 | Train Loss: 0.031451 | Val Loss: 0.333509

Epoch 1241/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00596]
Epoch 1241/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.44it/s]

End of Epoch 1241 | Train Loss: 0.035079 | Val Loss: 0.439748

Epoch 1242/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0075]
Epoch 1242/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.23it/s]

End of Epoch 1242 | Train Loss: 0.042502 | Val Loss: 0.365272

Epoch 1243/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00866]
Epoch 1243/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 1243 | Train Loss: 0.037764 | Val Loss: 0.562142

Epoch 1244/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00814]
Epoch 1244/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 1244 | Train Loss: 0.035301 | Val Loss: 0.394510

Epoch 1245/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0085]
Epoch 1245/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 1245 | Train Loss: 0.030245 | Val Loss: 0.387732

Epoch 1246/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00521]
Epoch 1246/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.19it/s]

End of Epoch 1246 | Train Loss: 0.039611 | Val Loss: 0.494476

Epoch 1247/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0132]
Epoch 1247/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 1247 | Train Loss: 0.033399 | Val Loss: 0.121664

Epoch 1248/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0127]
Epoch 1248/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 1248 | Train Loss: 0.034015 | Val Loss: 0.449896

Epoch 1249/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00551]
Epoch 1249/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 1249 | Train Loss: 0.030635 | Val Loss: 0.283639

Epoch 1250/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0393]
Epoch 1250/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 1250 | Train Loss: 0.029355 | Val Loss: 0.375220

Epoch 1251/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00767]
Epoch 1251/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.35it/s]

End of Epoch 1251 | Train Loss: 0.036599 | Val Loss: 0.560478

Epoch 1252/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00529]
Epoch 1252/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.30it/s]

End of Epoch 1252 | Train Loss: 0.039913 | Val Loss: 0.374628

Epoch 1253/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0111]
Epoch 1253/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 1253 | Train Loss: 0.045621 | Val Loss: 0.630818

Epoch 1254/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.017]
Epoch 1254/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.78it/s]

End of Epoch 1254 | Train Loss: 0.042781 | Val Loss: 0.473172

Epoch 1255/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.16]
Epoch 1255/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.27it/s]

End of Epoch 1255 | Train Loss: 0.035150 | Val Loss: 0.338331

Epoch 1256/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0677]
Epoch 1256/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.69it/s]

End of Epoch 1256 | Train Loss: 0.040295 | Val Loss: 0.441518

Epoch 1257/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0539]
Epoch 1257/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.29it/s]

End of Epoch 1257 | Train Loss: 0.032125 | Val Loss: 0.329312

Epoch 1258/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00684]
Epoch 1258/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 1258 | Train Loss: 0.034114 | Val Loss: 0.160604

Epoch 1259/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0073]
Epoch 1259/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 1259 | Train Loss: 0.030918 | Val Loss: 0.296490

Epoch 1260/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.015]
Epoch 1260/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 1260 | Train Loss: 0.034442 | Val Loss: 0.538218

Epoch 1261/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.109]
Epoch 1261/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 1261 | Train Loss: 0.040988 | Val Loss: 0.846902

Epoch 1262/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00783]
Epoch 1262/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 1262 | Train Loss: 0.042552 | Val Loss: 0.218544

Epoch 1263/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00948]
Epoch 1263/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.71it/s]

End of Epoch 1263 | Train Loss: 0.036465 | Val Loss: 0.399402

Epoch 1264/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0137]
Epoch 1264/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 1264 | Train Loss: 0.033063 | Val Loss: 0.498305

Epoch 1265/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00554]
Epoch 1265/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 1265 | Train Loss: 0.028169 | Val Loss: 0.490645

Epoch 1266/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00553]
Epoch 1266/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.46it/s]

End of Epoch 1266 | Train Loss: 0.029316 | Val Loss: 0.374386

Epoch 1267/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0391]
Epoch 1267/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.15it/s]

End of Epoch 1267 | Train Loss: 0.040006 | Val Loss: 0.366081

Epoch 1268/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0151]
Epoch 1268/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.47it/s]

End of Epoch 1268 | Train Loss: 0.028698 | Val Loss: 0.440006

Epoch 1269/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00928]
Epoch 1269/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.49it/s]

End of Epoch 1269 | Train Loss: 0.024780 | Val Loss: 0.361775

Epoch 1270/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0106]
Epoch 1270/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.68it/s]

End of Epoch 1270 | Train Loss: 0.032584 | Val Loss: 0.226871

Epoch 1271/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0083]
Epoch 1271/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.59it/s]

End of Epoch 1271 | Train Loss: 0.032674 | Val Loss: 0.732648

Epoch 1272/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0126]
Epoch 1272/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 1272 | Train Loss: 0.030702 | Val Loss: 0.475796

Epoch 1273/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0125]
Epoch 1273/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 1273 | Train Loss: 0.033225 | Val Loss: 0.484050

Epoch 1274/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00595]
Epoch 1274/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 1274 | Train Loss: 0.042074 | Val Loss: 0.568781

Epoch 1275/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00527]
Epoch 1275/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.73it/s]

End of Epoch 1275 | Train Loss: 0.031092 | Val Loss: 0.504800

Epoch 1276/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00584]
Epoch 1276/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1276 | Train Loss: 0.029067 | Val Loss: 0.307705

Epoch 1277/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0081]
Epoch 1277/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.16it/s]

End of Epoch 1277 | Train Loss: 0.041885 | Val Loss: 0.368377

Epoch 1278/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00578]
Epoch 1278/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.19it/s]

End of Epoch 1278 | Train Loss: 0.032217 | Val Loss: 0.317333

Epoch 1279/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00962]
Epoch 1279/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.25it/s]

End of Epoch 1279 | Train Loss: 0.032681 | Val Loss: 0.211281

Epoch 1280/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00608]
Epoch 1280/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 1280 | Train Loss: 0.037235 | Val Loss: 0.427416

Epoch 1281/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00566]
Epoch 1281/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 1281 | Train Loss: 0.037300 | Val Loss: 0.346666

Epoch 1282/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00687]
Epoch 1282/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.15it/s]

End of Epoch 1282 | Train Loss: 0.037664 | Val Loss: 0.504373

Epoch 1283/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00501]
Epoch 1283/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 1283 | Train Loss: 0.030704 | Val Loss: 0.581526

Epoch 1284/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00759]
Epoch 1284/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.53it/s]

End of Epoch 1284 | Train Loss: 0.033274 | Val Loss: 0.418946

Epoch 1285/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00617]
Epoch 1285/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 1285 | Train Loss: 0.038209 | Val Loss: 0.413680

Epoch 1286/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0056]
Epoch 1286/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.68it/s]

End of Epoch 1286 | Train Loss: 0.040396 | Val Loss: 0.300310

Epoch 1287/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00559]
Epoch 1287/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 1287 | Train Loss: 0.037396 | Val Loss: 0.296054

Epoch 1288/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.67it/s, loss=0.0745]
Epoch 1288/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.97it/s]

End of Epoch 1288 | Train Loss: 0.032739 | Val Loss: 0.318222

Epoch 1289/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.114]
Epoch 1289/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.23it/s]

End of Epoch 1289 | Train Loss: 0.031154 | Val Loss: 0.464614

Epoch 1290/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00741]
Epoch 1290/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 1290 | Train Loss: 0.034329 | Val Loss: 0.422379

Epoch 1291/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00613]
Epoch 1291/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.91it/s]

End of Epoch 1291 | Train Loss: 0.034966 | Val Loss: 0.147044

Epoch 1292/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0497]
Epoch 1292/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 1292 | Train Loss: 0.029592 | Val Loss: 0.339710

Epoch 1293/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00544]
Epoch 1293/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.41it/s]

End of Epoch 1293 | Train Loss: 0.035415 | Val Loss: 0.637964

Epoch 1294/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00554]
Epoch 1294/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 1294 | Train Loss: 0.035236 | Val Loss: 0.337367

Epoch 1295/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0154]
Epoch 1295/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 1295 | Train Loss: 0.031959 | Val Loss: 0.539432

Epoch 1296/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.15]
Epoch 1296/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.96it/s]

End of Epoch 1296 | Train Loss: 0.033298 | Val Loss: 0.362656

Epoch 1297/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0143]
Epoch 1297/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.64it/s]

End of Epoch 1297 | Train Loss: 0.033906 | Val Loss: 0.441426

Epoch 1298/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.436]
Epoch 1298/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.34it/s]

End of Epoch 1298 | Train Loss: 0.036101 | Val Loss: 0.303743

Epoch 1299/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00572]
Epoch 1299/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.11it/s]

End of Epoch 1299 | Train Loss: 0.036409 | Val Loss: 0.409594

Epoch 1300/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0365]
Epoch 1300/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.16it/s]

End of Epoch 1300 | Train Loss: 0.040160 | Val Loss: 0.502276

Epoch 1301/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00511]
Epoch 1301/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.26it/s]

End of Epoch 1301 | Train Loss: 0.039971 | Val Loss: 0.379008

Epoch 1302/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0169]
Epoch 1302/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 1302 | Train Loss: 0.037642 | Val Loss: 0.512742

Epoch 1303/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0211]
Epoch 1303/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 1303 | Train Loss: 0.035088 | Val Loss: 0.368850

Epoch 1304/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00853]
Epoch 1304/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.58it/s]

End of Epoch 1304 | Train Loss: 0.030463 | Val Loss: 0.475081

Epoch 1305/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0375]
Epoch 1305/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 1305 | Train Loss: 0.041722 | Val Loss: 0.328009

Epoch 1306/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00732]
Epoch 1306/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 1306 | Train Loss: 0.043816 | Val Loss: 0.693446

Epoch 1307/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00531]
Epoch 1307/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 1307 | Train Loss: 0.032658 | Val Loss: 0.485754

Epoch 1308/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00558]
Epoch 1308/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.31it/s]

End of Epoch 1308 | Train Loss: 0.034028 | Val Loss: 0.210344

Epoch 1309/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0116]
Epoch 1309/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 1309 | Train Loss: 0.039436 | Val Loss: 0.327379

Epoch 1310/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0349]
Epoch 1310/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.04it/s]

End of Epoch 1310 | Train Loss: 0.034725 | Val Loss: 0.589861

Epoch 1311/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00542]
Epoch 1311/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.68it/s]

End of Epoch 1311 | Train Loss: 0.030749 | Val Loss: 0.345318

Epoch 1312/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00918]
Epoch 1312/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.82it/s]

End of Epoch 1312 | Train Loss: 0.032967 | Val Loss: 0.376976

Epoch 1313/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00561]
Epoch 1313/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.62it/s]

End of Epoch 1313 | Train Loss: 0.039046 | Val Loss: 0.641886

Epoch 1314/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0544]
Epoch 1314/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.20it/s]

End of Epoch 1314 | Train Loss: 0.039998 | Val Loss: 0.256676

Epoch 1315/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0166]
Epoch 1315/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.91it/s]

End of Epoch 1315 | Train Loss: 0.035660 | Val Loss: 0.521541

Epoch 1316/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00612]
Epoch 1316/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.15it/s]

End of Epoch 1316 | Train Loss: 0.029483 | Val Loss: 0.385211

Epoch 1317/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00568]
Epoch 1317/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 1317 | Train Loss: 0.035991 | Val Loss: 0.294245

Epoch 1318/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0114]
Epoch 1318/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1318 | Train Loss: 0.034634 | Val Loss: 0.284080

Epoch 1319/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00906]
Epoch 1319/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.13it/s]

End of Epoch 1319 | Train Loss: 0.035389 | Val Loss: 0.350887

Epoch 1320/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0437]
Epoch 1320/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1320 | Train Loss: 0.035841 | Val Loss: 0.604214

Epoch 1321/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.024]
Epoch 1321/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 1321 | Train Loss: 0.035689 | Val Loss: 0.318082

Epoch 1322/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0044]
Epoch 1322/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 1322 | Train Loss: 0.035406 | Val Loss: 0.527324

Epoch 1323/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00568]
Epoch 1323/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 1323 | Train Loss: 0.032169 | Val Loss: 0.553761

Epoch 1324/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0169]
Epoch 1324/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.18it/s]

End of Epoch 1324 | Train Loss: 0.027374 | Val Loss: 0.627068

Epoch 1325/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00593]
Epoch 1325/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.66it/s]

End of Epoch 1325 | Train Loss: 0.039805 | Val Loss: 0.433235

Epoch 1326/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00565]
Epoch 1326/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 1326 | Train Loss: 0.036439 | Val Loss: 0.410675

Epoch 1327/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00588]
Epoch 1327/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.41it/s]

End of Epoch 1327 | Train Loss: 0.043640 | Val Loss: 0.441105

Epoch 1328/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00661]
Epoch 1328/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.78it/s]

End of Epoch 1328 | Train Loss: 0.032948 | Val Loss: 0.382701

Epoch 1329/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00471]
Epoch 1329/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.20it/s]

End of Epoch 1329 | Train Loss: 0.034489 | Val Loss: 0.560191

Epoch 1330/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0057]
Epoch 1330/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 1330 | Train Loss: 0.038534 | Val Loss: 0.697443

Epoch 1331/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.0105]
Epoch 1331/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.93it/s]

End of Epoch 1331 | Train Loss: 0.036032 | Val Loss: 0.389409

Epoch 1332/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00755]
Epoch 1332/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 1332 | Train Loss: 0.030319 | Val Loss: 0.333680

Epoch 1333/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00569]
Epoch 1333/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.22it/s]

End of Epoch 1333 | Train Loss: 0.038750 | Val Loss: 0.516497

Epoch 1334/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.00485]
Epoch 1334/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.82it/s]

End of Epoch 1334 | Train Loss: 0.035317 | Val Loss: 0.295955

Epoch 1335/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00603]
Epoch 1335/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.24it/s]

End of Epoch 1335 | Train Loss: 0.034454 | Val Loss: 0.651226

Epoch 1336/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0108]
Epoch 1336/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.25it/s]

End of Epoch 1336 | Train Loss: 0.039038 | Val Loss: 0.216884

Epoch 1337/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00557]
Epoch 1337/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.28it/s]

End of Epoch 1337 | Train Loss: 0.035531 | Val Loss: 0.390383

Epoch 1338/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00587]
Epoch 1338/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 1338 | Train Loss: 0.032293 | Val Loss: 0.364107

Epoch 1339/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0318]
Epoch 1339/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.45it/s]

End of Epoch 1339 | Train Loss: 0.031724 | Val Loss: 0.487665

Epoch 1340/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.00522]
Epoch 1340/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.38it/s]

End of Epoch 1340 | Train Loss: 0.028796 | Val Loss: 0.401486

Epoch 1341/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00992]
Epoch 1341/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.15it/s]

End of Epoch 1341 | Train Loss: 0.037636 | Val Loss: 0.341002

Epoch 1342/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00457]
Epoch 1342/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.61it/s]

End of Epoch 1342 | Train Loss: 0.031397 | Val Loss: 0.400646

Epoch 1343/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00569]
Epoch 1343/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 1343 | Train Loss: 0.028506 | Val Loss: 0.590486

Epoch 1344/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00762]
Epoch 1344/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 1344 | Train Loss: 0.033814 | Val Loss: 0.458322

Epoch 1345/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00582]
Epoch 1345/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 1345 | Train Loss: 0.031087 | Val Loss: 0.285647

Epoch 1346/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0206]
Epoch 1346/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 1346 | Train Loss: 0.032199 | Val Loss: 0.718669

Epoch 1347/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0138]
Epoch 1347/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.78it/s]

End of Epoch 1347 | Train Loss: 0.031083 | Val Loss: 0.481696

Epoch 1348/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00741]
Epoch 1348/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.34it/s]

End of Epoch 1348 | Train Loss: 0.033808 | Val Loss: 0.499622

Epoch 1349/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00509]
Epoch 1349/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.37it/s]

End of Epoch 1349 | Train Loss: 0.036792 | Val Loss: 0.215351

Epoch 1350/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00456]
Epoch 1350/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 1350 | Train Loss: 0.028383 | Val Loss: 0.222914

Epoch 1351/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00541]
Epoch 1351/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.95it/s]

End of Epoch 1351 | Train Loss: 0.033739 | Val Loss: 0.644494

Epoch 1352/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00444]
Epoch 1352/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 1352 | Train Loss: 0.030882 | Val Loss: 0.302081

Epoch 1353/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0101]
Epoch 1353/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.69it/s]

End of Epoch 1353 | Train Loss: 0.027726 | Val Loss: 0.238218

Epoch 1354/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0051]
Epoch 1354/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.37it/s]

End of Epoch 1354 | Train Loss: 0.029667 | Val Loss: 0.455341

Epoch 1355/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0199]
Epoch 1355/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.81it/s]

End of Epoch 1355 | Train Loss: 0.035621 | Val Loss: 0.357386

Epoch 1356/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0165]
Epoch 1356/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.52it/s]

End of Epoch 1356 | Train Loss: 0.032347 | Val Loss: 0.536995

Epoch 1357/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0064]
Epoch 1357/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.52it/s]

End of Epoch 1357 | Train Loss: 0.038389 | Val Loss: 0.577328

Epoch 1358/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0232]
Epoch 1358/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.95it/s]

End of Epoch 1358 | Train Loss: 0.029720 | Val Loss: 0.439062

Epoch 1359/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0135]
Epoch 1359/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 1359 | Train Loss: 0.026143 | Val Loss: 0.548581

Epoch 1360/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00713]
Epoch 1360/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.82it/s]

End of Epoch 1360 | Train Loss: 0.032407 | Val Loss: 0.508361

Epoch 1361/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00829]
Epoch 1361/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.77it/s]

End of Epoch 1361 | Train Loss: 0.036129 | Val Loss: 0.564859

Epoch 1362/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00938]
Epoch 1362/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.61it/s]

End of Epoch 1362 | Train Loss: 0.034961 | Val Loss: 0.233331

Epoch 1363/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00579]
Epoch 1363/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.61it/s]

End of Epoch 1363 | Train Loss: 0.026288 | Val Loss: 0.387648

Epoch 1364/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00573]
Epoch 1364/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.90it/s]

End of Epoch 1364 | Train Loss: 0.035400 | Val Loss: 0.342425

Epoch 1365/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00496]
Epoch 1365/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.00it/s]

End of Epoch 1365 | Train Loss: 0.036616 | Val Loss: 0.522357

Epoch 1366/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.49it/s, loss=0.283]
Epoch 1366/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.56it/s]

End of Epoch 1366 | Train Loss: 0.032650 | Val Loss: 0.402568

Epoch 1367/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00419]
Epoch 1367/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.73it/s]

End of Epoch 1367 | Train Loss: 0.034671 | Val Loss: 0.510368

Epoch 1368/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0404]
Epoch 1368/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.95it/s]

End of Epoch 1368 | Train Loss: 0.033699 | Val Loss: 0.241908

Epoch 1369/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0115]
Epoch 1369/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.37it/s]

End of Epoch 1369 | Train Loss: 0.038656 | Val Loss: 0.260037

Epoch 1370/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0077]
Epoch 1370/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.68it/s]

End of Epoch 1370 | Train Loss: 0.031650 | Val Loss: 0.372859

Epoch 1371/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0259]
Epoch 1371/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 1371 | Train Loss: 0.036650 | Val Loss: 0.161252

Epoch 1372/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00541]
Epoch 1372/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.98it/s]

End of Epoch 1372 | Train Loss: 0.035437 | Val Loss: 0.429967

Epoch 1373/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00629]
Epoch 1373/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 1373 | Train Loss: 0.031115 | Val Loss: 0.243708

Epoch 1374/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0513]
Epoch 1374/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.00it/s]

End of Epoch 1374 | Train Loss: 0.031055 | Val Loss: 0.395864

Epoch 1375/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0128]
Epoch 1375/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.95it/s]

End of Epoch 1375 | Train Loss: 0.032441 | Val Loss: 0.644810

Epoch 1376/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0395]
Epoch 1376/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.75it/s]

End of Epoch 1376 | Train Loss: 0.034503 | Val Loss: 0.829339

Epoch 1377/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00557]
Epoch 1377/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 1377 | Train Loss: 0.035296 | Val Loss: 0.327683

Epoch 1378/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.00522]
Epoch 1378/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.64it/s]

End of Epoch 1378 | Train Loss: 0.034873 | Val Loss: 0.385749

Epoch 1379/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00669]
Epoch 1379/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.63it/s]

End of Epoch 1379 | Train Loss: 0.036512 | Val Loss: 0.505462

Epoch 1380/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00604]
Epoch 1380/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.24it/s]

End of Epoch 1380 | Train Loss: 0.036109 | Val Loss: 0.544823

Epoch 1381/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00451]
Epoch 1381/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.56it/s]

End of Epoch 1381 | Train Loss: 0.029764 | Val Loss: 0.264120

Epoch 1382/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.12]
Epoch 1382/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 1382 | Train Loss: 0.034992 | Val Loss: 0.412020

Epoch 1383/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00885]
Epoch 1383/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 1383 | Train Loss: 0.029301 | Val Loss: 0.366666

Epoch 1384/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00516]
Epoch 1384/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1384 | Train Loss: 0.030295 | Val Loss: 0.628168

Epoch 1385/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0172]
Epoch 1385/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.28it/s]

End of Epoch 1385 | Train Loss: 0.031097 | Val Loss: 0.417144

Epoch 1386/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00642]
Epoch 1386/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.28it/s]

End of Epoch 1386 | Train Loss: 0.032092 | Val Loss: 0.312092

Epoch 1387/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00843]
Epoch 1387/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.59it/s]

End of Epoch 1387 | Train Loss: 0.028994 | Val Loss: 0.672170

Epoch 1388/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00811]
Epoch 1388/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 1388 | Train Loss: 0.036010 | Val Loss: 0.285508

Epoch 1389/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00863]
Epoch 1389/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 1389 | Train Loss: 0.034751 | Val Loss: 0.355972

Epoch 1390/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00731]
Epoch 1390/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 1390 | Train Loss: 0.034100 | Val Loss: 0.668171

Epoch 1391/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00547]
Epoch 1391/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 1391 | Train Loss: 0.028793 | Val Loss: 0.844661

Epoch 1392/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00543]
Epoch 1392/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 1392 | Train Loss: 0.029827 | Val Loss: 0.427653

Epoch 1393/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.146]
Epoch 1393/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.57it/s]

End of Epoch 1393 | Train Loss: 0.035444 | Val Loss: 0.369898

Epoch 1394/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.0129]
Epoch 1394/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 1394 | Train Loss: 0.035871 | Val Loss: 0.302780

Epoch 1395/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00428]
Epoch 1395/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 1395 | Train Loss: 0.036025 | Val Loss: 0.577999

Epoch 1396/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0524]
Epoch 1396/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 1396 | Train Loss: 0.036200 | Val Loss: 0.268091

Epoch 1397/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.123]
Epoch 1397/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.47it/s]

End of Epoch 1397 | Train Loss: 0.035343 | Val Loss: 0.456618

Epoch 1398/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0123]
Epoch 1398/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 1398 | Train Loss: 0.032888 | Val Loss: 0.472104

Epoch 1399/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00623]
Epoch 1399/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 1399 | Train Loss: 0.030004 | Val Loss: 0.335802

Epoch 1400/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0117]
Epoch 1400/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.27it/s]

End of Epoch 1400 | Train Loss: 0.035007 | Val Loss: 0.499436

Epoch 1401/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00564]
Epoch 1401/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.74it/s]

End of Epoch 1401 | Train Loss: 0.034192 | Val Loss: 0.463144

Epoch 1402/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.01]
Epoch 1402/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.40it/s]

End of Epoch 1402 | Train Loss: 0.034968 | Val Loss: 0.245088

Epoch 1403/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00614]
Epoch 1403/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.30it/s]

End of Epoch 1403 | Train Loss: 0.037460 | Val Loss: 0.391295

Epoch 1404/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00825]
Epoch 1404/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 1404 | Train Loss: 0.037816 | Val Loss: 0.496949

Epoch 1405/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00396]
Epoch 1405/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.00it/s]

End of Epoch 1405 | Train Loss: 0.025999 | Val Loss: 0.424290

Epoch 1406/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.0186]
Epoch 1406/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 1406 | Train Loss: 0.037916 | Val Loss: 0.362688

Epoch 1407/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00565]
Epoch 1407/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 1407 | Train Loss: 0.033117 | Val Loss: 0.532103

Epoch 1408/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0103]
Epoch 1408/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.75it/s]

End of Epoch 1408 | Train Loss: 0.036552 | Val Loss: 0.372366

Epoch 1409/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.9]
Epoch 1409/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.45it/s]

End of Epoch 1409 | Train Loss: 0.041750 | Val Loss: 0.480768

Epoch 1410/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00984]
Epoch 1410/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.41it/s]

End of Epoch 1410 | Train Loss: 0.036884 | Val Loss: 0.641928

Epoch 1411/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0045]
Epoch 1411/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.44it/s]

End of Epoch 1411 | Train Loss: 0.030770 | Val Loss: 0.476172

Epoch 1412/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0056]
Epoch 1412/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 1412 | Train Loss: 0.026673 | Val Loss: 0.334720

Epoch 1413/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00589]
Epoch 1413/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.72it/s]

End of Epoch 1413 | Train Loss: 0.028952 | Val Loss: 0.463707

Epoch 1414/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00415]
Epoch 1414/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 1414 | Train Loss: 0.025709 | Val Loss: 0.785398

Epoch 1415/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00543]
Epoch 1415/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.93it/s]

End of Epoch 1415 | Train Loss: 0.031504 | Val Loss: 0.305078

Epoch 1416/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.009]
Epoch 1416/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 1416 | Train Loss: 0.042723 | Val Loss: 0.278634

Epoch 1417/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0129]
Epoch 1417/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 1417 | Train Loss: 0.039746 | Val Loss: 0.347486

Epoch 1418/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0226]
Epoch 1418/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.95it/s]

End of Epoch 1418 | Train Loss: 0.032232 | Val Loss: 0.408760

Epoch 1419/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00591]
Epoch 1419/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.18it/s]

End of Epoch 1419 | Train Loss: 0.032029 | Val Loss: 0.455545

Epoch 1420/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00798]
Epoch 1420/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.59it/s]

End of Epoch 1420 | Train Loss: 0.029586 | Val Loss: 0.389141

Epoch 1421/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0469]
Epoch 1421/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.74it/s]

End of Epoch 1421 | Train Loss: 0.031269 | Val Loss: 0.435775

Epoch 1422/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00855]
Epoch 1422/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.80it/s]

End of Epoch 1422 | Train Loss: 0.029172 | Val Loss: 0.463301

Epoch 1423/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00548]
Epoch 1423/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.10it/s]

End of Epoch 1423 | Train Loss: 0.032506 | Val Loss: 0.603148

Epoch 1424/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00399]
Epoch 1424/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.57it/s]

End of Epoch 1424 | Train Loss: 0.037926 | Val Loss: 0.389927

Epoch 1425/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.55it/s, loss=0.0046]
Epoch 1425/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 1425 | Train Loss: 0.037978 | Val Loss: 0.574173

Epoch 1426/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.229]
Epoch 1426/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1426 | Train Loss: 0.032213 | Val Loss: 0.700967

Epoch 1427/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.288]
Epoch 1427/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 1427 | Train Loss: 0.038892 | Val Loss: 0.589862

Epoch 1428/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0329]
Epoch 1428/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 1428 | Train Loss: 0.031627 | Val Loss: 0.508538

Epoch 1429/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00674]
Epoch 1429/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.60it/s]

End of Epoch 1429 | Train Loss: 0.036024 | Val Loss: 0.285488

Epoch 1430/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00511]
Epoch 1430/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 1430 | Train Loss: 0.028714 | Val Loss: 0.361559

Epoch 1431/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0162]
Epoch 1431/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.72it/s]

End of Epoch 1431 | Train Loss: 0.025355 | Val Loss: 0.345226

Epoch 1432/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.815]
Epoch 1432/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.25it/s]

End of Epoch 1432 | Train Loss: 0.043854 | Val Loss: 0.178627

Epoch 1433/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00435]
Epoch 1433/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.52it/s]

End of Epoch 1433 | Train Loss: 0.041445 | Val Loss: 0.373891

Epoch 1434/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0472]
Epoch 1434/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.30it/s]

End of Epoch 1434 | Train Loss: 0.035236 | Val Loss: 0.283729

Epoch 1435/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00776]
Epoch 1435/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.12it/s]

End of Epoch 1435 | Train Loss: 0.031679 | Val Loss: 0.481358

Epoch 1436/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0385]
Epoch 1436/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.30it/s]

End of Epoch 1436 | Train Loss: 0.028088 | Val Loss: 0.358142

Epoch 1437/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00655]
Epoch 1437/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.22it/s]

End of Epoch 1437 | Train Loss: 0.035447 | Val Loss: 0.560519

Epoch 1438/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00596]
Epoch 1438/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 1438 | Train Loss: 0.027276 | Val Loss: 0.260229

Epoch 1439/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0119]
Epoch 1439/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 1439 | Train Loss: 0.034944 | Val Loss: 0.444198

Epoch 1440/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.108]
Epoch 1440/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 1440 | Train Loss: 0.037100 | Val Loss: 0.347733

Epoch 1441/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00865]
Epoch 1441/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 1441 | Train Loss: 0.031036 | Val Loss: 0.604912

Epoch 1442/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00796]
Epoch 1442/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 1442 | Train Loss: 0.021113 | Val Loss: 0.422275

Epoch 1443/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.034]
Epoch 1443/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 1443 | Train Loss: 0.032892 | Val Loss: 0.658522

Epoch 1444/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.40it/s, loss=0.0135]
Epoch 1444/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 1444 | Train Loss: 0.036249 | Val Loss: 0.470248

Epoch 1445/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00404]
Epoch 1445/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.08it/s]

End of Epoch 1445 | Train Loss: 0.037432 | Val Loss: 0.377257

Epoch 1446/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.36it/s, loss=0.00482]
Epoch 1446/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 1446 | Train Loss: 0.029343 | Val Loss: 0.457886

Epoch 1447/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00553]
Epoch 1447/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 1447 | Train Loss: 0.031426 | Val Loss: 0.433046

Epoch 1448/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.729]
Epoch 1448/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.13it/s]

End of Epoch 1448 | Train Loss: 0.041894 | Val Loss: 0.245979

Epoch 1449/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00453]
Epoch 1449/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.07it/s]

End of Epoch 1449 | Train Loss: 0.041054 | Val Loss: 0.704004

Epoch 1450/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.43it/s, loss=0.0358]
Epoch 1450/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 1450 | Train Loss: 0.033248 | Val Loss: 0.640761

Epoch 1451/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00756]
Epoch 1451/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.44it/s]

End of Epoch 1451 | Train Loss: 0.031154 | Val Loss: 0.586753

Epoch 1452/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00472]
Epoch 1452/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.17it/s]

End of Epoch 1452 | Train Loss: 0.029662 | Val Loss: 0.456424

Epoch 1453/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00562]
Epoch 1453/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.32it/s]

End of Epoch 1453 | Train Loss: 0.031919 | Val Loss: 0.526368

Epoch 1454/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.005]
Epoch 1454/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.31it/s]

End of Epoch 1454 | Train Loss: 0.033138 | Val Loss: 0.341122

Epoch 1455/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00502]
Epoch 1455/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.78it/s]

End of Epoch 1455 | Train Loss: 0.029287 | Val Loss: 0.396924

Epoch 1456/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0183]
Epoch 1456/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 1456 | Train Loss: 0.037039 | Val Loss: 0.225375

Epoch 1457/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.045]
Epoch 1457/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.60it/s]

End of Epoch 1457 | Train Loss: 0.037787 | Val Loss: 0.442539

Epoch 1458/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00561]
Epoch 1458/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.18it/s]

End of Epoch 1458 | Train Loss: 0.030965 | Val Loss: 0.656168

Epoch 1459/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0301]
Epoch 1459/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.32it/s]

End of Epoch 1459 | Train Loss: 0.034289 | Val Loss: 0.187788

Epoch 1460/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00554]
Epoch 1460/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.43it/s]

End of Epoch 1460 | Train Loss: 0.035767 | Val Loss: 0.373605

Epoch 1461/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.509]
Epoch 1461/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.62it/s]

End of Epoch 1461 | Train Loss: 0.039620 | Val Loss: 0.562642

Epoch 1462/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00572]
Epoch 1462/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 1462 | Train Loss: 0.038222 | Val Loss: 0.312225

Epoch 1463/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0157]
Epoch 1463/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.22it/s]

End of Epoch 1463 | Train Loss: 0.036235 | Val Loss: 0.281786

Epoch 1464/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0265]
Epoch 1464/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 1464 | Train Loss: 0.038222 | Val Loss: 0.325349

Epoch 1465/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00456]
Epoch 1465/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.69it/s]

End of Epoch 1465 | Train Loss: 0.027293 | Val Loss: 0.392550

Epoch 1466/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00645]
Epoch 1466/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 1466 | Train Loss: 0.027163 | Val Loss: 0.204206

Epoch 1467/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.168]
Epoch 1467/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 1467 | Train Loss: 0.034883 | Val Loss: 0.493727

Epoch 1468/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00455]
Epoch 1468/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.59it/s]

End of Epoch 1468 | Train Loss: 0.037729 | Val Loss: 0.430463

Epoch 1469/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0121]
Epoch 1469/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 1469 | Train Loss: 0.028125 | Val Loss: 0.585165

Epoch 1470/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0116]
Epoch 1470/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 1470 | Train Loss: 0.025714 | Val Loss: 0.477063

Epoch 1471/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00602]
Epoch 1471/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.10it/s]

End of Epoch 1471 | Train Loss: 0.032310 | Val Loss: 0.651300

Epoch 1472/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0273]
Epoch 1472/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 1472 | Train Loss: 0.031220 | Val Loss: 0.310768

Epoch 1473/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.028]
Epoch 1473/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 1473 | Train Loss: 0.039207 | Val Loss: 0.281198

Epoch 1474/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00647]
Epoch 1474/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 1474 | Train Loss: 0.032681 | Val Loss: 0.605934

Epoch 1475/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0047]
Epoch 1475/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 1475 | Train Loss: 0.029791 | Val Loss: 0.584303

Epoch 1476/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00492]
Epoch 1476/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.92it/s]

End of Epoch 1476 | Train Loss: 0.034967 | Val Loss: 0.535203

Epoch 1477/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0128]
Epoch 1477/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 1477 | Train Loss: 0.027472 | Val Loss: 0.419818

Epoch 1478/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0426]
Epoch 1478/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.59it/s]

End of Epoch 1478 | Train Loss: 0.033168 | Val Loss: 0.411636

Epoch 1479/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0163]
Epoch 1479/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.67it/s]

End of Epoch 1479 | Train Loss: 0.039834 | Val Loss: 0.284188

Epoch 1480/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00723]
Epoch 1480/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.78it/s]

End of Epoch 1480 | Train Loss: 0.032562 | Val Loss: 0.541913

Epoch 1481/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00471]
Epoch 1481/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.93it/s]

End of Epoch 1481 | Train Loss: 0.031233 | Val Loss: 0.258527

Epoch 1482/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00543]
Epoch 1482/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.34it/s]

End of Epoch 1482 | Train Loss: 0.031518 | Val Loss: 0.363651

Epoch 1483/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00688]
Epoch 1483/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 1483 | Train Loss: 0.032077 | Val Loss: 0.300156

Epoch 1484/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00599]
Epoch 1484/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.85it/s]

End of Epoch 1484 | Train Loss: 0.035922 | Val Loss: 0.467299

Epoch 1485/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0133]
Epoch 1485/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 1485 | Train Loss: 0.030622 | Val Loss: 0.370373

Epoch 1486/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00498]
Epoch 1486/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.94it/s]

End of Epoch 1486 | Train Loss: 0.034907 | Val Loss: 0.567470

Epoch 1487/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0447]
Epoch 1487/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.00it/s]

End of Epoch 1487 | Train Loss: 0.034357 | Val Loss: 0.266143

Epoch 1488/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.233]
Epoch 1488/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.00it/s]

End of Epoch 1488 | Train Loss: 0.037971 | Val Loss: 0.243067

Epoch 1489/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00775]
Epoch 1489/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 1489 | Train Loss: 0.040682 | Val Loss: 0.614567

Epoch 1490/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00768]
Epoch 1490/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.14it/s]

End of Epoch 1490 | Train Loss: 0.037546 | Val Loss: 0.312035

Epoch 1491/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00642]
Epoch 1491/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 1491 | Train Loss: 0.029276 | Val Loss: 0.438320

Epoch 1492/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00413]
Epoch 1492/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.48it/s]

End of Epoch 1492 | Train Loss: 0.029317 | Val Loss: 0.462944

Epoch 1493/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0223]
Epoch 1493/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.81it/s]

End of Epoch 1493 | Train Loss: 0.036051 | Val Loss: 0.334751

Epoch 1494/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0195]
Epoch 1494/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.28it/s]

End of Epoch 1494 | Train Loss: 0.026407 | Val Loss: 0.473592

Epoch 1495/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00792]
Epoch 1495/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.75it/s]

End of Epoch 1495 | Train Loss: 0.034220 | Val Loss: 0.393500

Epoch 1496/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.014]
Epoch 1496/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 1496 | Train Loss: 0.028112 | Val Loss: 0.445238

Epoch 1497/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00444]
Epoch 1497/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 1497 | Train Loss: 0.032032 | Val Loss: 0.673437

Epoch 1498/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0138]
Epoch 1498/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 1498 | Train Loss: 0.035493 | Val Loss: 0.252740

Epoch 1499/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0161]
Epoch 1499/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 1499 | Train Loss: 0.030957 | Val Loss: 0.598093

Epoch 1500/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0264]
Epoch 1500/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 1500 | Train Loss: 0.030881 | Val Loss: 0.398706

Epoch 1501/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0153]
Epoch 1501/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 1501 | Train Loss: 0.032003 | Val Loss: 0.386172

Epoch 1502/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0068]
Epoch 1502/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 1502 | Train Loss: 0.036826 | Val Loss: 0.386742

Epoch 1503/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00697]
Epoch 1503/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 1503 | Train Loss: 0.026141 | Val Loss: 0.651629

Epoch 1504/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.014]
Epoch 1504/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.09it/s]

End of Epoch 1504 | Train Loss: 0.039131 | Val Loss: 0.294345

Epoch 1505/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.501]
Epoch 1505/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 1505 | Train Loss: 0.039200 | Val Loss: 0.532812

Epoch 1506/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0155]
Epoch 1506/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.64it/s]

End of Epoch 1506 | Train Loss: 0.036802 | Val Loss: 0.471191

Epoch 1507/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00591]
Epoch 1507/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 1507 | Train Loss: 0.030342 | Val Loss: 0.588148

Epoch 1508/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00464]
Epoch 1508/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.85it/s]

End of Epoch 1508 | Train Loss: 0.038723 | Val Loss: 0.537928

Epoch 1509/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.244]
Epoch 1509/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.31it/s]

End of Epoch 1509 | Train Loss: 0.036184 | Val Loss: 0.528993

Epoch 1510/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0047]
Epoch 1510/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.71it/s]

End of Epoch 1510 | Train Loss: 0.041625 | Val Loss: 0.463948

Epoch 1511/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00519]
Epoch 1511/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.13it/s]

End of Epoch 1511 | Train Loss: 0.034208 | Val Loss: 0.176078

Epoch 1512/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0209]
Epoch 1512/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 1512 | Train Loss: 0.025636 | Val Loss: 0.592999

Epoch 1513/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00521]
Epoch 1513/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.59it/s]

End of Epoch 1513 | Train Loss: 0.030253 | Val Loss: 0.213713

Epoch 1514/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00787]
Epoch 1514/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 1514 | Train Loss: 0.033818 | Val Loss: 0.435913

Epoch 1515/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.177]
Epoch 1515/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 1515 | Train Loss: 0.040755 | Val Loss: 0.724723

Epoch 1516/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00808]
Epoch 1516/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 1516 | Train Loss: 0.030727 | Val Loss: 0.534110

Epoch 1517/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0125]
Epoch 1517/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.02it/s]

End of Epoch 1517 | Train Loss: 0.025673 | Val Loss: 0.620201

Epoch 1518/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00754]
Epoch 1518/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.27it/s]

End of Epoch 1518 | Train Loss: 0.033460 | Val Loss: 0.331001

Epoch 1519/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.00599]
Epoch 1519/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 1519 | Train Loss: 0.035191 | Val Loss: 0.283540

Epoch 1520/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0118]
Epoch 1520/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.44it/s]

End of Epoch 1520 | Train Loss: 0.029444 | Val Loss: 0.205811

Epoch 1521/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0076]
Epoch 1521/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 1521 | Train Loss: 0.024824 | Val Loss: 0.536484

Epoch 1522/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0297]
Epoch 1522/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 1522 | Train Loss: 0.027424 | Val Loss: 0.280863

Epoch 1523/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0172]
Epoch 1523/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.57it/s]

End of Epoch 1523 | Train Loss: 0.031700 | Val Loss: 0.306355

Epoch 1524/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0155]
Epoch 1524/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.40it/s]

End of Epoch 1524 | Train Loss: 0.035751 | Val Loss: 0.435097

Epoch 1525/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.248]
Epoch 1525/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 1525 | Train Loss: 0.027734 | Val Loss: 0.469609

Epoch 1526/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0098]
Epoch 1526/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.61it/s]

End of Epoch 1526 | Train Loss: 0.036475 | Val Loss: 0.470071

Epoch 1527/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00559]
Epoch 1527/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.61it/s]

End of Epoch 1527 | Train Loss: 0.032795 | Val Loss: 0.537031

Epoch 1528/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00699]
Epoch 1528/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 1528 | Train Loss: 0.030720 | Val Loss: 0.315605

Epoch 1529/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00553]
Epoch 1529/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 1529 | Train Loss: 0.034018 | Val Loss: 0.667835

Epoch 1530/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.00453]
Epoch 1530/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 1530 | Train Loss: 0.028866 | Val Loss: 0.265645

Epoch 1531/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.579]
Epoch 1531/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 1531 | Train Loss: 0.034578 | Val Loss: 0.411243

Epoch 1532/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.1]
Epoch 1532/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 1532 | Train Loss: 0.038941 | Val Loss: 0.551807

Epoch 1533/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.288]
Epoch 1533/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.40it/s]

End of Epoch 1533 | Train Loss: 0.034164 | Val Loss: 0.338124

Epoch 1534/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00448]
Epoch 1534/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.56it/s]

End of Epoch 1534 | Train Loss: 0.034233 | Val Loss: 0.759042

Epoch 1535/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00639]
Epoch 1535/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1535 | Train Loss: 0.030740 | Val Loss: 0.212610

Epoch 1536/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00464]
Epoch 1536/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.44it/s]

End of Epoch 1536 | Train Loss: 0.032283 | Val Loss: 0.440839

Epoch 1537/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.015]
Epoch 1537/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.29it/s]

End of Epoch 1537 | Train Loss: 0.036089 | Val Loss: 0.313801

Epoch 1538/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00469]
Epoch 1538/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.22it/s]

End of Epoch 1538 | Train Loss: 0.029719 | Val Loss: 0.282884

Epoch 1539/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0112]
Epoch 1539/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.95it/s]

End of Epoch 1539 | Train Loss: 0.028486 | Val Loss: 0.302250

Epoch 1540/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00679]
Epoch 1540/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 1540 | Train Loss: 0.027793 | Val Loss: 0.426212

Epoch 1541/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00418]
Epoch 1541/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 1541 | Train Loss: 0.029913 | Val Loss: 0.434744

Epoch 1542/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00884]
Epoch 1542/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.29it/s]

End of Epoch 1542 | Train Loss: 0.026368 | Val Loss: 0.560451

Epoch 1543/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.0166]
Epoch 1543/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 1543 | Train Loss: 0.035829 | Val Loss: 0.464486

Epoch 1544/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00433]
Epoch 1544/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 1544 | Train Loss: 0.030907 | Val Loss: 0.530493

Epoch 1545/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0046]
Epoch 1545/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.68it/s]

End of Epoch 1545 | Train Loss: 0.031993 | Val Loss: 0.156073

Epoch 1546/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0427]
Epoch 1546/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.45it/s]

End of Epoch 1546 | Train Loss: 0.029609 | Val Loss: 0.620721

Epoch 1547/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00458]
Epoch 1547/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.32it/s]

End of Epoch 1547 | Train Loss: 0.024270 | Val Loss: 0.358273

Epoch 1548/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00627]
Epoch 1548/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.12it/s]

End of Epoch 1548 | Train Loss: 0.027652 | Val Loss: 0.439317

Epoch 1549/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00503]
Epoch 1549/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 1549 | Train Loss: 0.031531 | Val Loss: 0.340311

Epoch 1550/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0221]
Epoch 1550/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.77it/s]

End of Epoch 1550 | Train Loss: 0.033018 | Val Loss: 0.718045

Epoch 1551/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00733]
Epoch 1551/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.08it/s]

End of Epoch 1551 | Train Loss: 0.031701 | Val Loss: 0.379137

Epoch 1552/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.281]
Epoch 1552/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 1552 | Train Loss: 0.034883 | Val Loss: 0.401528

Epoch 1553/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00952]
Epoch 1553/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 1553 | Train Loss: 0.033262 | Val Loss: 0.503568

Epoch 1554/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00492]
Epoch 1554/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 1554 | Train Loss: 0.030242 | Val Loss: 0.457543

Epoch 1555/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00579]
Epoch 1555/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 1555 | Train Loss: 0.031879 | Val Loss: 0.304591

Epoch 1556/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0052]
Epoch 1556/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.81it/s]

End of Epoch 1556 | Train Loss: 0.025337 | Val Loss: 0.680137

Epoch 1557/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00451]
Epoch 1557/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.30it/s]

End of Epoch 1557 | Train Loss: 0.038894 | Val Loss: 0.407210

Epoch 1558/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0052]
Epoch 1558/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.98it/s]

End of Epoch 1558 | Train Loss: 0.037689 | Val Loss: 0.351906

Epoch 1559/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00758]
Epoch 1559/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.67it/s]

End of Epoch 1559 | Train Loss: 0.027559 | Val Loss: 0.271567

Epoch 1560/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00839]
Epoch 1560/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 1560 | Train Loss: 0.031520 | Val Loss: 0.328060

Epoch 1561/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00549]
Epoch 1561/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.06it/s]

End of Epoch 1561 | Train Loss: 0.040015 | Val Loss: 0.425072

Epoch 1562/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.47it/s, loss=0.0555]
Epoch 1562/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.57it/s]

End of Epoch 1562 | Train Loss: 0.031395 | Val Loss: 0.557390

Epoch 1563/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.505]
Epoch 1563/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.53it/s]

End of Epoch 1563 | Train Loss: 0.037435 | Val Loss: 0.277698

Epoch 1564/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00622]
Epoch 1564/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 1564 | Train Loss: 0.035889 | Val Loss: 0.767551

Epoch 1565/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00566]
Epoch 1565/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.16it/s]

End of Epoch 1565 | Train Loss: 0.029084 | Val Loss: 0.352257

Epoch 1566/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0137]
Epoch 1566/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.23it/s]

End of Epoch 1566 | Train Loss: 0.034711 | Val Loss: 0.660479

Epoch 1567/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0301]
Epoch 1567/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 1567 | Train Loss: 0.031873 | Val Loss: 0.385838

Epoch 1568/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00681]
Epoch 1568/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.62it/s]

End of Epoch 1568 | Train Loss: 0.025580 | Val Loss: 0.487755

Epoch 1569/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00443]
Epoch 1569/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 1569 | Train Loss: 0.025161 | Val Loss: 0.602827

Epoch 1570/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00455]
Epoch 1570/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1570 | Train Loss: 0.033669 | Val Loss: 0.334797

Epoch 1571/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00545]
Epoch 1571/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.94it/s]

End of Epoch 1571 | Train Loss: 0.032183 | Val Loss: 0.664491

Epoch 1572/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0121]
Epoch 1572/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.68it/s]

End of Epoch 1572 | Train Loss: 0.032042 | Val Loss: 0.395648

Epoch 1573/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00814]
Epoch 1573/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.53it/s]

End of Epoch 1573 | Train Loss: 0.030586 | Val Loss: 0.325415

Epoch 1574/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00466]
Epoch 1574/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 1574 | Train Loss: 0.025433 | Val Loss: 0.447571

Epoch 1575/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00395]
Epoch 1575/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 1575 | Train Loss: 0.028587 | Val Loss: 0.591728

Epoch 1576/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00451]
Epoch 1576/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 1576 | Train Loss: 0.024136 | Val Loss: 0.288518

Epoch 1577/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00645]
Epoch 1577/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.25it/s]

End of Epoch 1577 | Train Loss: 0.031882 | Val Loss: 0.490971

Epoch 1578/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00411]
Epoch 1578/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 1578 | Train Loss: 0.028856 | Val Loss: 0.410829

Epoch 1579/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00865]
Epoch 1579/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 1579 | Train Loss: 0.037211 | Val Loss: 0.309749

Epoch 1580/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00561]
Epoch 1580/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 1580 | Train Loss: 0.026569 | Val Loss: 0.321928

Epoch 1581/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00523]
Epoch 1581/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 1581 | Train Loss: 0.027763 | Val Loss: 0.388403

Epoch 1582/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00474]
Epoch 1582/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 1582 | Train Loss: 0.028126 | Val Loss: 0.553877

Epoch 1583/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0755]
Epoch 1583/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.20it/s]

End of Epoch 1583 | Train Loss: 0.031445 | Val Loss: 0.701598

Epoch 1584/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00596]
Epoch 1584/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.82it/s]

End of Epoch 1584 | Train Loss: 0.031686 | Val Loss: 0.250460

Epoch 1585/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00607]
Epoch 1585/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 1585 | Train Loss: 0.031886 | Val Loss: 0.764814

Epoch 1586/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00488]
Epoch 1586/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.54it/s]

End of Epoch 1586 | Train Loss: 0.030006 | Val Loss: 0.659361

Epoch 1587/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00479]
Epoch 1587/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.81it/s]

End of Epoch 1587 | Train Loss: 0.032868 | Val Loss: 0.543578

Epoch 1588/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00525]
Epoch 1588/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.35it/s]

End of Epoch 1588 | Train Loss: 0.025388 | Val Loss: 1.027295

Epoch 1589/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0104]
Epoch 1589/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.76it/s]

End of Epoch 1589 | Train Loss: 0.032470 | Val Loss: 0.755213

Epoch 1590/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00929]
Epoch 1590/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.77it/s]

End of Epoch 1590 | Train Loss: 0.026819 | Val Loss: 0.358145

Epoch 1591/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00619]
Epoch 1591/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 1591 | Train Loss: 0.029520 | Val Loss: 0.235474

Epoch 1592/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0121]
Epoch 1592/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 1592 | Train Loss: 0.031902 | Val Loss: 0.280958

Epoch 1593/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0928]
Epoch 1593/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.29it/s]

End of Epoch 1593 | Train Loss: 0.033515 | Val Loss: 0.269962

Epoch 1594/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.046]
Epoch 1594/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.35it/s]

End of Epoch 1594 | Train Loss: 0.034392 | Val Loss: 0.777416

Epoch 1595/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00603]
Epoch 1595/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 1595 | Train Loss: 0.033171 | Val Loss: 0.431372

Epoch 1596/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00683]
Epoch 1596/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.14it/s]

End of Epoch 1596 | Train Loss: 0.023005 | Val Loss: 0.349971

Epoch 1597/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00464]
Epoch 1597/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 1597 | Train Loss: 0.030670 | Val Loss: 0.418229

Epoch 1598/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0045]
Epoch 1598/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.20it/s]

End of Epoch 1598 | Train Loss: 0.030906 | Val Loss: 0.508321

Epoch 1599/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0097]
Epoch 1599/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.29it/s]

End of Epoch 1599 | Train Loss: 0.029868 | Val Loss: 0.279117

Epoch 1600/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.251]
Epoch 1600/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.03it/s]

End of Epoch 1600 | Train Loss: 0.034018 | Val Loss: 0.229264

Epoch 1601/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00943]
Epoch 1601/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.59it/s]

End of Epoch 1601 | Train Loss: 0.026190 | Val Loss: 0.367269

Epoch 1602/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00517]
Epoch 1602/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 1602 | Train Loss: 0.030235 | Val Loss: 0.338715

Epoch 1603/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00506]
Epoch 1603/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.29it/s]

End of Epoch 1603 | Train Loss: 0.036440 | Val Loss: 0.415430

Epoch 1604/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00476]
Epoch 1604/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.26it/s]

End of Epoch 1604 | Train Loss: 0.029880 | Val Loss: 0.382772

Epoch 1605/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00528]
Epoch 1605/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 1605 | Train Loss: 0.026006 | Val Loss: 0.313184

Epoch 1606/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00455]
Epoch 1606/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1606 | Train Loss: 0.034028 | Val Loss: 0.721076

Epoch 1607/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00781]
Epoch 1607/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.91it/s]

End of Epoch 1607 | Train Loss: 0.029412 | Val Loss: 0.397091

Epoch 1608/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00688]
Epoch 1608/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 1608 | Train Loss: 0.027386 | Val Loss: 0.449006

Epoch 1609/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00956]
Epoch 1609/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.59it/s]

End of Epoch 1609 | Train Loss: 0.024076 | Val Loss: 0.423206

Epoch 1610/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00464]
Epoch 1610/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.68it/s]

End of Epoch 1610 | Train Loss: 0.026331 | Val Loss: 0.594694

Epoch 1611/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00459]
Epoch 1611/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.53it/s]

End of Epoch 1611 | Train Loss: 0.035106 | Val Loss: 0.430520

Epoch 1612/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00532]
Epoch 1612/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.54it/s]

End of Epoch 1612 | Train Loss: 0.030090 | Val Loss: 0.205507

Epoch 1613/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00871]
Epoch 1613/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.23it/s]

End of Epoch 1613 | Train Loss: 0.029994 | Val Loss: 0.381021

Epoch 1614/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00494]
Epoch 1614/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 1614 | Train Loss: 0.030730 | Val Loss: 0.315692

Epoch 1615/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00517]
Epoch 1615/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 1615 | Train Loss: 0.038127 | Val Loss: 0.357275

Epoch 1616/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0042]
Epoch 1616/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 1616 | Train Loss: 0.033206 | Val Loss: 0.464472

Epoch 1617/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00583]
Epoch 1617/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.03it/s]

End of Epoch 1617 | Train Loss: 0.026951 | Val Loss: 0.277796

Epoch 1618/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00518]
Epoch 1618/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 1618 | Train Loss: 0.026080 | Val Loss: 0.453230

Epoch 1619/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0339]
Epoch 1619/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.84it/s]

End of Epoch 1619 | Train Loss: 0.030098 | Val Loss: 0.642120

Epoch 1620/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00401]
Epoch 1620/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 1620 | Train Loss: 0.026030 | Val Loss: 0.498995

Epoch 1621/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00944]
Epoch 1621/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.31it/s]

End of Epoch 1621 | Train Loss: 0.033278 | Val Loss: 0.395171

Epoch 1622/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00567]
Epoch 1622/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 1622 | Train Loss: 0.034979 | Val Loss: 0.471319

Epoch 1623/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.022]
Epoch 1623/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 1623 | Train Loss: 0.029946 | Val Loss: 0.315351

Epoch 1624/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0054]
Epoch 1624/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1624 | Train Loss: 0.036694 | Val Loss: 0.540565

Epoch 1625/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0104]
Epoch 1625/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.29it/s]

End of Epoch 1625 | Train Loss: 0.036748 | Val Loss: 0.409433

Epoch 1626/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.0277]
Epoch 1626/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 1626 | Train Loss: 0.033368 | Val Loss: 0.388639

Epoch 1627/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0217]
Epoch 1627/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 1627 | Train Loss: 0.027126 | Val Loss: 0.485246

Epoch 1628/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.011]
Epoch 1628/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.15it/s]

End of Epoch 1628 | Train Loss: 0.032613 | Val Loss: 0.572292

Epoch 1629/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00605]
Epoch 1629/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 1629 | Train Loss: 0.035706 | Val Loss: 0.638373

Epoch 1630/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0145]
Epoch 1630/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.57it/s]

End of Epoch 1630 | Train Loss: 0.030316 | Val Loss: 0.269983

Epoch 1631/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0146]
Epoch 1631/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 1631 | Train Loss: 0.029547 | Val Loss: 0.273569

Epoch 1632/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.184]
Epoch 1632/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.25it/s]

End of Epoch 1632 | Train Loss: 0.027831 | Val Loss: 0.524467

Epoch 1633/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0046]
Epoch 1633/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 1633 | Train Loss: 0.025340 | Val Loss: 0.787650

Epoch 1634/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00551]
Epoch 1634/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.10it/s]

End of Epoch 1634 | Train Loss: 0.030086 | Val Loss: 0.545307

Epoch 1635/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0115]
Epoch 1635/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 1635 | Train Loss: 0.029955 | Val Loss: 0.647073

Epoch 1636/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0119]
Epoch 1636/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.56it/s]

End of Epoch 1636 | Train Loss: 0.031516 | Val Loss: 0.309209

Epoch 1637/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00576]
Epoch 1637/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.06it/s]

End of Epoch 1637 | Train Loss: 0.025308 | Val Loss: 0.425782

Epoch 1638/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0043]
Epoch 1638/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 1638 | Train Loss: 0.021392 | Val Loss: 0.227831

Epoch 1639/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00605]
Epoch 1639/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 1639 | Train Loss: 0.027857 | Val Loss: 0.287334

Epoch 1640/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0665]
Epoch 1640/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.14it/s]

End of Epoch 1640 | Train Loss: 0.028558 | Val Loss: 0.343056

Epoch 1641/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00395]
Epoch 1641/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.87it/s]

End of Epoch 1641 | Train Loss: 0.029540 | Val Loss: 0.343116

Epoch 1642/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0107]
Epoch 1642/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.53it/s]

End of Epoch 1642 | Train Loss: 0.025359 | Val Loss: 0.622485

Epoch 1643/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00491]
Epoch 1643/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 1643 | Train Loss: 0.035337 | Val Loss: 0.511535

Epoch 1644/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00419]
Epoch 1644/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 1644 | Train Loss: 0.037378 | Val Loss: 0.327990

Epoch 1645/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00549]
Epoch 1645/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.18it/s]

End of Epoch 1645 | Train Loss: 0.028794 | Val Loss: 0.604128

Epoch 1646/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00522]
Epoch 1646/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.61it/s]

End of Epoch 1646 | Train Loss: 0.035572 | Val Loss: 0.455990

Epoch 1647/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0131]
Epoch 1647/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 1647 | Train Loss: 0.024544 | Val Loss: 0.419033

Epoch 1648/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.0723]
Epoch 1648/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.01it/s]

End of Epoch 1648 | Train Loss: 0.028265 | Val Loss: 0.713809

Epoch 1649/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0267]
Epoch 1649/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 1649 | Train Loss: 0.037150 | Val Loss: 0.283940

Epoch 1650/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.005]
Epoch 1650/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.52it/s]

End of Epoch 1650 | Train Loss: 0.031721 | Val Loss: 0.368392

Epoch 1651/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0435]
Epoch 1651/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.84it/s]

End of Epoch 1651 | Train Loss: 0.024775 | Val Loss: 0.458560

Epoch 1652/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00929]
Epoch 1652/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.05it/s]

End of Epoch 1652 | Train Loss: 0.027891 | Val Loss: 0.440251

Epoch 1653/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00668]
Epoch 1653/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 1653 | Train Loss: 0.029114 | Val Loss: 0.568474

Epoch 1654/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0193]
Epoch 1654/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.93it/s]

End of Epoch 1654 | Train Loss: 0.031711 | Val Loss: 0.454004

Epoch 1655/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00584]
Epoch 1655/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.43it/s]

End of Epoch 1655 | Train Loss: 0.029800 | Val Loss: 0.349918

Epoch 1656/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0105]
Epoch 1656/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.70it/s]

End of Epoch 1656 | Train Loss: 0.030912 | Val Loss: 0.639553

Epoch 1657/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0117]
Epoch 1657/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.29it/s]

End of Epoch 1657 | Train Loss: 0.028913 | Val Loss: 0.286820

Epoch 1658/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00938]
Epoch 1658/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 1658 | Train Loss: 0.029557 | Val Loss: 0.530841

Epoch 1659/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00369]
Epoch 1659/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.61it/s]

End of Epoch 1659 | Train Loss: 0.030484 | Val Loss: 0.613312

Epoch 1660/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00476]
Epoch 1660/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.82it/s]

End of Epoch 1660 | Train Loss: 0.030830 | Val Loss: 0.867106

Epoch 1661/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.67it/s, loss=0.0933]
Epoch 1661/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.45it/s]

End of Epoch 1661 | Train Loss: 0.038202 | Val Loss: 0.537420

Epoch 1662/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0255]
Epoch 1662/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 1662 | Train Loss: 0.032701 | Val Loss: 0.185865

Epoch 1663/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00382]
Epoch 1663/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.10it/s]

End of Epoch 1663 | Train Loss: 0.029712 | Val Loss: 0.657184

Epoch 1664/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.477]
Epoch 1664/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 1664 | Train Loss: 0.037856 | Val Loss: 0.294543

Epoch 1665/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00451]
Epoch 1665/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.89it/s]

End of Epoch 1665 | Train Loss: 0.036698 | Val Loss: 0.434293

Epoch 1666/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0296]
Epoch 1666/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 1666 | Train Loss: 0.031601 | Val Loss: 0.247868

Epoch 1667/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0041]
Epoch 1667/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.30it/s]

End of Epoch 1667 | Train Loss: 0.029844 | Val Loss: 0.462954

Epoch 1668/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0156]
Epoch 1668/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 1668 | Train Loss: 0.031812 | Val Loss: 0.251455

Epoch 1669/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0046]
Epoch 1669/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 1669 | Train Loss: 0.033331 | Val Loss: 0.451925

Epoch 1670/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00437]
Epoch 1670/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 1670 | Train Loss: 0.035803 | Val Loss: 0.404696

Epoch 1671/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00903]
Epoch 1671/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.95it/s]

End of Epoch 1671 | Train Loss: 0.022282 | Val Loss: 0.575691

Epoch 1672/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00527]
Epoch 1672/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.00it/s]

End of Epoch 1672 | Train Loss: 0.025421 | Val Loss: 0.350806

Epoch 1673/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0103]
Epoch 1673/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.61it/s]

End of Epoch 1673 | Train Loss: 0.038275 | Val Loss: 0.524486

Epoch 1674/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0702]
Epoch 1674/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.24it/s]

End of Epoch 1674 | Train Loss: 0.033337 | Val Loss: 0.520804

Epoch 1675/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00475]
Epoch 1675/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.26it/s]

End of Epoch 1675 | Train Loss: 0.029779 | Val Loss: 0.313190

Epoch 1676/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00712]
Epoch 1676/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1676 | Train Loss: 0.032724 | Val Loss: 0.227368

Epoch 1677/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0048]
Epoch 1677/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.30it/s]

End of Epoch 1677 | Train Loss: 0.036107 | Val Loss: 0.470207

Epoch 1678/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0178]
Epoch 1678/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.22it/s]

End of Epoch 1678 | Train Loss: 0.025049 | Val Loss: 0.343986

Epoch 1679/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0041]
Epoch 1679/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.61it/s]

End of Epoch 1679 | Train Loss: 0.026709 | Val Loss: 0.184910

Epoch 1680/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.49it/s, loss=0.00338]
Epoch 1680/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 1680 | Train Loss: 0.026184 | Val Loss: 0.394337

Epoch 1681/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00397]
Epoch 1681/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.06it/s]

End of Epoch 1681 | Train Loss: 0.031116 | Val Loss: 0.700012

Epoch 1682/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00407]
Epoch 1682/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.30it/s]

End of Epoch 1682 | Train Loss: 0.038818 | Val Loss: 0.435868

Epoch 1683/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0759]
Epoch 1683/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.47it/s]

End of Epoch 1683 | Train Loss: 0.030452 | Val Loss: 0.429483

Epoch 1684/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.0037]
Epoch 1684/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.89it/s]

End of Epoch 1684 | Train Loss: 0.031056 | Val Loss: 0.262143

Epoch 1685/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00453]
Epoch 1685/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.78it/s]

End of Epoch 1685 | Train Loss: 0.030123 | Val Loss: 0.334770

Epoch 1686/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0143]
Epoch 1686/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.69it/s]

End of Epoch 1686 | Train Loss: 0.030885 | Val Loss: 0.459722

Epoch 1687/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00385]
Epoch 1687/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.70it/s]

End of Epoch 1687 | Train Loss: 0.028433 | Val Loss: 0.567001

Epoch 1688/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00537]
Epoch 1688/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.33it/s]

End of Epoch 1688 | Train Loss: 0.026769 | Val Loss: 0.437504

Epoch 1689/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00385]
Epoch 1689/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.02it/s]

End of Epoch 1689 | Train Loss: 0.020629 | Val Loss: 0.321185

Epoch 1690/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00364]
Epoch 1690/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.89it/s]

End of Epoch 1690 | Train Loss: 0.025474 | Val Loss: 0.451137

Epoch 1691/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00597]
Epoch 1691/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.62it/s]

End of Epoch 1691 | Train Loss: 0.027393 | Val Loss: 0.472704

Epoch 1692/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0046]
Epoch 1692/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.15it/s]

End of Epoch 1692 | Train Loss: 0.025548 | Val Loss: 0.458407

Epoch 1693/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0579]
Epoch 1693/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.85it/s]

End of Epoch 1693 | Train Loss: 0.026370 | Val Loss: 0.210163

Epoch 1694/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00417]
Epoch 1694/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.61it/s]

End of Epoch 1694 | Train Loss: 0.025723 | Val Loss: 0.702547

Epoch 1695/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00353]
Epoch 1695/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.80it/s]

End of Epoch 1695 | Train Loss: 0.035262 | Val Loss: 0.336981

Epoch 1696/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00412]
Epoch 1696/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.53it/s]

End of Epoch 1696 | Train Loss: 0.024752 | Val Loss: 0.397371

Epoch 1697/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00573]
Epoch 1697/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 1697 | Train Loss: 0.028788 | Val Loss: 0.253596

Epoch 1698/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0209]
Epoch 1698/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.85it/s]

End of Epoch 1698 | Train Loss: 0.026977 | Val Loss: 0.572620

Epoch 1699/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0043]
Epoch 1699/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 1699 | Train Loss: 0.025734 | Val Loss: 0.524503

Epoch 1700/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.00581]
Epoch 1700/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 1700 | Train Loss: 0.031675 | Val Loss: 0.343173

Epoch 1701/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0126]
Epoch 1701/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.83it/s]

End of Epoch 1701 | Train Loss: 0.035951 | Val Loss: 0.347338

Epoch 1702/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0053]
Epoch 1702/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 1702 | Train Loss: 0.027607 | Val Loss: 0.272742

Epoch 1703/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00583]
Epoch 1703/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.70it/s]

End of Epoch 1703 | Train Loss: 0.035908 | Val Loss: 0.272710

Epoch 1704/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.102]
Epoch 1704/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.83it/s]

End of Epoch 1704 | Train Loss: 0.029994 | Val Loss: 0.294196

Epoch 1705/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0547]
Epoch 1705/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 1705 | Train Loss: 0.032706 | Val Loss: 0.483071

Epoch 1706/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0249]
Epoch 1706/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.80it/s]

End of Epoch 1706 | Train Loss: 0.035092 | Val Loss: 0.347752

Epoch 1707/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0968]
Epoch 1707/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.23it/s]

End of Epoch 1707 | Train Loss: 0.034279 | Val Loss: 0.479887

Epoch 1708/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00541]
Epoch 1708/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 1708 | Train Loss: 0.031603 | Val Loss: 0.270690

Epoch 1709/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0109]
Epoch 1709/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 1709 | Train Loss: 0.032598 | Val Loss: 0.703115

Epoch 1710/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0076]
Epoch 1710/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.86it/s]

End of Epoch 1710 | Train Loss: 0.032231 | Val Loss: 0.290877

Epoch 1711/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00339]
Epoch 1711/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.64it/s]

End of Epoch 1711 | Train Loss: 0.025543 | Val Loss: 0.461551

Epoch 1712/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0119]
Epoch 1712/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1712 | Train Loss: 0.034202 | Val Loss: 0.248885

Epoch 1713/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00399]
Epoch 1713/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.71it/s]

End of Epoch 1713 | Train Loss: 0.025517 | Val Loss: 0.636739

Epoch 1714/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0078]
Epoch 1714/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.05it/s]

End of Epoch 1714 | Train Loss: 0.024840 | Val Loss: 0.378312

Epoch 1715/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0156]
Epoch 1715/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.27it/s]

End of Epoch 1715 | Train Loss: 0.029274 | Val Loss: 0.461494

Epoch 1716/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0042]
Epoch 1716/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.15it/s]

End of Epoch 1716 | Train Loss: 0.023822 | Val Loss: 0.279879

Epoch 1717/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0134]
Epoch 1717/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 1717 | Train Loss: 0.035242 | Val Loss: 0.574352

Epoch 1718/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.051]
Epoch 1718/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 1718 | Train Loss: 0.028052 | Val Loss: 0.273476

Epoch 1719/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.927]
Epoch 1719/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.61it/s]

End of Epoch 1719 | Train Loss: 0.030829 | Val Loss: 0.291373

Epoch 1720/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.00411]
Epoch 1720/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 1720 | Train Loss: 0.026745 | Val Loss: 0.332172

Epoch 1721/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0724]
Epoch 1721/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.41it/s]

End of Epoch 1721 | Train Loss: 0.031274 | Val Loss: 0.537758

Epoch 1722/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0137]
Epoch 1722/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.59it/s]

End of Epoch 1722 | Train Loss: 0.029555 | Val Loss: 0.339203

Epoch 1723/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00382]
Epoch 1723/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 1723 | Train Loss: 0.028894 | Val Loss: 0.486822

Epoch 1724/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00648]
Epoch 1724/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.25it/s]

End of Epoch 1724 | Train Loss: 0.033813 | Val Loss: 0.377301

Epoch 1725/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00399]
Epoch 1725/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.67it/s]

End of Epoch 1725 | Train Loss: 0.032428 | Val Loss: 0.460306

Epoch 1726/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00716]
Epoch 1726/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.27it/s]

End of Epoch 1726 | Train Loss: 0.026837 | Val Loss: 0.338557

Epoch 1727/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00944]
Epoch 1727/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.06it/s]

End of Epoch 1727 | Train Loss: 0.035816 | Val Loss: 0.630199

Epoch 1728/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00382]
Epoch 1728/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 1728 | Train Loss: 0.028438 | Val Loss: 0.299191

Epoch 1729/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00431]
Epoch 1729/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.90it/s]

End of Epoch 1729 | Train Loss: 0.026780 | Val Loss: 0.393009

Epoch 1730/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0338]
Epoch 1730/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.48it/s]

End of Epoch 1730 | Train Loss: 0.026289 | Val Loss: 0.380119

Epoch 1731/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0433]
Epoch 1731/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.36it/s]

End of Epoch 1731 | Train Loss: 0.027473 | Val Loss: 0.340116

Epoch 1732/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00395]
Epoch 1732/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.39it/s]

End of Epoch 1732 | Train Loss: 0.029085 | Val Loss: 0.574818

Epoch 1733/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00383]
Epoch 1733/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.85it/s]

End of Epoch 1733 | Train Loss: 0.027265 | Val Loss: 0.226770

Epoch 1734/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00377]
Epoch 1734/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.89it/s]

End of Epoch 1734 | Train Loss: 0.022638 | Val Loss: 0.334220

Epoch 1735/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00423]
Epoch 1735/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.26it/s]

End of Epoch 1735 | Train Loss: 0.026452 | Val Loss: 0.483743

Epoch 1736/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00455]
Epoch 1736/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.46it/s]

End of Epoch 1736 | Train Loss: 0.025783 | Val Loss: 0.787937

Epoch 1737/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00774]
Epoch 1737/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.61it/s]

End of Epoch 1737 | Train Loss: 0.033090 | Val Loss: 0.619330

Epoch 1738/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00356]
Epoch 1738/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 1738 | Train Loss: 0.032873 | Val Loss: 0.282775

Epoch 1739/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00813]
Epoch 1739/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 1739 | Train Loss: 0.027326 | Val Loss: 0.140991

Epoch 1740/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0035]
Epoch 1740/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 1740 | Train Loss: 0.028830 | Val Loss: 0.461977

Epoch 1741/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00457]
Epoch 1741/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 1741 | Train Loss: 0.029110 | Val Loss: 0.339423

Epoch 1742/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00438]
Epoch 1742/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.57it/s]

End of Epoch 1742 | Train Loss: 0.034104 | Val Loss: 0.382452

Epoch 1743/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00566]
Epoch 1743/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 1743 | Train Loss: 0.027132 | Val Loss: 0.419177

Epoch 1744/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00684]
Epoch 1744/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 1744 | Train Loss: 0.030612 | Val Loss: 0.195995

Epoch 1745/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00595]
Epoch 1745/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.59it/s]

End of Epoch 1745 | Train Loss: 0.028502 | Val Loss: 0.660668

Epoch 1746/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0043]
Epoch 1746/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.83it/s]

End of Epoch 1746 | Train Loss: 0.027314 | Val Loss: 0.439431

Epoch 1747/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00516]
Epoch 1747/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 1747 | Train Loss: 0.028905 | Val Loss: 0.183302

Epoch 1748/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00456]
Epoch 1748/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.17it/s]

End of Epoch 1748 | Train Loss: 0.028106 | Val Loss: 0.866531

Epoch 1749/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0194]
Epoch 1749/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.11it/s]

End of Epoch 1749 | Train Loss: 0.027059 | Val Loss: 0.395599

Epoch 1750/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00571]
Epoch 1750/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.29it/s]

End of Epoch 1750 | Train Loss: 0.037249 | Val Loss: 0.488793

Epoch 1751/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00418]
Epoch 1751/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.27it/s]

End of Epoch 1751 | Train Loss: 0.028411 | Val Loss: 0.332823

Epoch 1752/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00386]
Epoch 1752/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.89it/s]

End of Epoch 1752 | Train Loss: 0.029874 | Val Loss: 0.413728

Epoch 1753/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0116]
Epoch 1753/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.25it/s]

End of Epoch 1753 | Train Loss: 0.026175 | Val Loss: 0.274809

Epoch 1754/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00487]
Epoch 1754/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.91it/s]

End of Epoch 1754 | Train Loss: 0.029674 | Val Loss: 0.583381

Epoch 1755/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00394]
Epoch 1755/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.05it/s]

End of Epoch 1755 | Train Loss: 0.021665 | Val Loss: 0.368382

Epoch 1756/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0041]
Epoch 1756/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.19it/s]

End of Epoch 1756 | Train Loss: 0.028519 | Val Loss: 0.466162

Epoch 1757/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00604]
Epoch 1757/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 1757 | Train Loss: 0.025209 | Val Loss: 0.139721

Epoch 1758/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0231]
Epoch 1758/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 1758 | Train Loss: 0.031053 | Val Loss: 0.429795

Epoch 1759/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.647]
Epoch 1759/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.39it/s]

End of Epoch 1759 | Train Loss: 0.035218 | Val Loss: 0.183837

Epoch 1760/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00383]
Epoch 1760/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.41it/s]

End of Epoch 1760 | Train Loss: 0.034715 | Val Loss: 0.390743

Epoch 1761/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0137]
Epoch 1761/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 1761 | Train Loss: 0.030226 | Val Loss: 0.605099

Epoch 1762/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00941]
Epoch 1762/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 1762 | Train Loss: 0.020487 | Val Loss: 0.283395

Epoch 1763/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00682]
Epoch 1763/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 1763 | Train Loss: 0.029803 | Val Loss: 0.486067

Epoch 1764/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00357]
Epoch 1764/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 1764 | Train Loss: 0.026345 | Val Loss: 0.486479

Epoch 1765/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00941]
Epoch 1765/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 1765 | Train Loss: 0.029162 | Val Loss: 0.481435

Epoch 1766/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00431]
Epoch 1766/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.20it/s]

End of Epoch 1766 | Train Loss: 0.021706 | Val Loss: 0.589454

Epoch 1767/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00524]
Epoch 1767/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 1767 | Train Loss: 0.024763 | Val Loss: 0.377138

Epoch 1768/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.011]
Epoch 1768/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.37it/s]

End of Epoch 1768 | Train Loss: 0.028338 | Val Loss: 0.587208

Epoch 1769/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0214]
Epoch 1769/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.55it/s]

End of Epoch 1769 | Train Loss: 0.029540 | Val Loss: 0.204761

Epoch 1770/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00513]
Epoch 1770/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.53it/s]

End of Epoch 1770 | Train Loss: 0.033428 | Val Loss: 0.570853

Epoch 1771/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.473]
Epoch 1771/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 1771 | Train Loss: 0.028301 | Val Loss: 0.427808

Epoch 1772/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0109]
Epoch 1772/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.97it/s]

End of Epoch 1772 | Train Loss: 0.029786 | Val Loss: 0.242919

Epoch 1773/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00602]
Epoch 1773/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.64it/s]

End of Epoch 1773 | Train Loss: 0.032684 | Val Loss: 0.535903

Epoch 1774/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0477]
Epoch 1774/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 1774 | Train Loss: 0.031879 | Val Loss: 0.222716

Epoch 1775/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00442]
Epoch 1775/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.85it/s]

End of Epoch 1775 | Train Loss: 0.023663 | Val Loss: 0.341789

Epoch 1776/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0362]
Epoch 1776/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.07it/s]

End of Epoch 1776 | Train Loss: 0.025003 | Val Loss: 0.703277

Epoch 1777/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00434]
Epoch 1777/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 1777 | Train Loss: 0.026538 | Val Loss: 0.630773

Epoch 1778/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0053]
Epoch 1778/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 1778 | Train Loss: 0.026649 | Val Loss: 0.759949

Epoch 1779/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.47it/s, loss=0.016]
Epoch 1779/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.70it/s]

End of Epoch 1779 | Train Loss: 0.023302 | Val Loss: 0.288006

Epoch 1780/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00408]
Epoch 1780/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.97it/s]

End of Epoch 1780 | Train Loss: 0.031945 | Val Loss: 0.398817

Epoch 1781/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00546]
Epoch 1781/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 1781 | Train Loss: 0.023716 | Val Loss: 0.586742

Epoch 1782/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00398]
Epoch 1782/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 1782 | Train Loss: 0.027797 | Val Loss: 0.333200

Epoch 1783/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00384]
Epoch 1783/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.57it/s]

End of Epoch 1783 | Train Loss: 0.028821 | Val Loss: 0.563478

Epoch 1784/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00772]
Epoch 1784/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 1784 | Train Loss: 0.026959 | Val Loss: 0.294902

Epoch 1785/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0152]
Epoch 1785/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.54it/s]

End of Epoch 1785 | Train Loss: 0.025597 | Val Loss: 0.176106

Epoch 1786/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00456]
Epoch 1786/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 1786 | Train Loss: 0.030792 | Val Loss: 0.377378

Epoch 1787/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00522]
Epoch 1787/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.25it/s]

End of Epoch 1787 | Train Loss: 0.028306 | Val Loss: 0.352294

Epoch 1788/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00687]
Epoch 1788/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.18it/s]

End of Epoch 1788 | Train Loss: 0.033799 | Val Loss: 0.451317

Epoch 1789/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00744]
Epoch 1789/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 1789 | Train Loss: 0.026957 | Val Loss: 0.536739

Epoch 1790/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0063]
Epoch 1790/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.05it/s]

End of Epoch 1790 | Train Loss: 0.025394 | Val Loss: 0.574418

Epoch 1791/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0187]
Epoch 1791/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 1791 | Train Loss: 0.028154 | Val Loss: 0.594009

Epoch 1792/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00357]
Epoch 1792/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.65it/s]

End of Epoch 1792 | Train Loss: 0.023433 | Val Loss: 0.327156

Epoch 1793/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00452]
Epoch 1793/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 1793 | Train Loss: 0.033679 | Val Loss: 0.349029

Epoch 1794/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0112]
Epoch 1794/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.10it/s]

End of Epoch 1794 | Train Loss: 0.024991 | Val Loss: 0.346696

Epoch 1795/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00535]
Epoch 1795/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 1795 | Train Loss: 0.022767 | Val Loss: 0.338818

Epoch 1796/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0215]
Epoch 1796/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 1796 | Train Loss: 0.021961 | Val Loss: 0.915389

Epoch 1797/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0254]
Epoch 1797/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 1797 | Train Loss: 0.030316 | Val Loss: 0.520102

Epoch 1798/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0119]
Epoch 1798/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 1798 | Train Loss: 0.034781 | Val Loss: 0.354325

Epoch 1799/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.0549]
Epoch 1799/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.42it/s]

End of Epoch 1799 | Train Loss: 0.029216 | Val Loss: 0.396660

Epoch 1800/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0228]
Epoch 1800/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.56it/s]

End of Epoch 1800 | Train Loss: 0.027541 | Val Loss: 0.229638

Epoch 1801/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00907]
Epoch 1801/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.38it/s]

End of Epoch 1801 | Train Loss: 0.031842 | Val Loss: 0.583431

Epoch 1802/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00444]
Epoch 1802/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 1802 | Train Loss: 0.035988 | Val Loss: 0.552280

Epoch 1803/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00992]
Epoch 1803/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 1803 | Train Loss: 0.026456 | Val Loss: 0.485372

Epoch 1804/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0119]
Epoch 1804/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.60it/s]

End of Epoch 1804 | Train Loss: 0.024735 | Val Loss: 0.859319

Epoch 1805/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0106]
Epoch 1805/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 1805 | Train Loss: 0.030941 | Val Loss: 0.336628

Epoch 1806/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00569]
Epoch 1806/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.88it/s]

End of Epoch 1806 | Train Loss: 0.037678 | Val Loss: 0.471631

Epoch 1807/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0298]
Epoch 1807/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.52it/s]

End of Epoch 1807 | Train Loss: 0.031376 | Val Loss: 0.394172

Epoch 1808/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00757]
Epoch 1808/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.79it/s]

End of Epoch 1808 | Train Loss: 0.025120 | Val Loss: 0.479768

Epoch 1809/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00482]
Epoch 1809/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.85it/s]

End of Epoch 1809 | Train Loss: 0.030189 | Val Loss: 0.257336

Epoch 1810/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0131]
Epoch 1810/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 1810 | Train Loss: 0.032289 | Val Loss: 0.453126

Epoch 1811/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00429]
Epoch 1811/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 1811 | Train Loss: 0.031382 | Val Loss: 0.404119

Epoch 1812/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00581]
Epoch 1812/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1812 | Train Loss: 0.039932 | Val Loss: 0.536468

Epoch 1813/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0217]
Epoch 1813/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.62it/s]

End of Epoch 1813 | Train Loss: 0.026083 | Val Loss: 0.312150

Epoch 1814/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.00448]
Epoch 1814/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.02it/s]

End of Epoch 1814 | Train Loss: 0.028194 | Val Loss: 0.424014

Epoch 1815/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00363]
Epoch 1815/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.92it/s]

End of Epoch 1815 | Train Loss: 0.024713 | Val Loss: 0.575764

Epoch 1816/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0193]
Epoch 1816/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 1816 | Train Loss: 0.029218 | Val Loss: 0.596866

Epoch 1817/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0835]
Epoch 1817/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.19it/s]

End of Epoch 1817 | Train Loss: 0.026600 | Val Loss: 0.234781

Epoch 1818/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.00473]
Epoch 1818/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.35it/s]

End of Epoch 1818 | Train Loss: 0.028109 | Val Loss: 0.381664

Epoch 1819/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0323]
Epoch 1819/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.38it/s]

End of Epoch 1819 | Train Loss: 0.031863 | Val Loss: 0.503738

Epoch 1820/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00411]
Epoch 1820/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.27it/s]

End of Epoch 1820 | Train Loss: 0.026871 | Val Loss: 0.468670

Epoch 1821/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0032]
Epoch 1821/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 1821 | Train Loss: 0.022514 | Val Loss: 0.387448

Epoch 1822/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00433]
Epoch 1822/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 1822 | Train Loss: 0.029805 | Val Loss: 0.591699

Epoch 1823/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0235]
Epoch 1823/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.11it/s]

End of Epoch 1823 | Train Loss: 0.031070 | Val Loss: 0.290885

Epoch 1824/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0184]
Epoch 1824/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.17it/s]

End of Epoch 1824 | Train Loss: 0.025241 | Val Loss: 0.517880

Epoch 1825/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00481]
Epoch 1825/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.87it/s]

End of Epoch 1825 | Train Loss: 0.026828 | Val Loss: 0.699463

Epoch 1826/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00442]
Epoch 1826/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.47it/s]

End of Epoch 1826 | Train Loss: 0.021916 | Val Loss: 0.669786

Epoch 1827/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0173]
Epoch 1827/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 1827 | Train Loss: 0.031187 | Val Loss: 0.702306

Epoch 1828/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00401]
Epoch 1828/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 1828 | Train Loss: 0.024175 | Val Loss: 0.451397

Epoch 1829/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00388]
Epoch 1829/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 1829 | Train Loss: 0.027818 | Val Loss: 0.202826

Epoch 1830/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.0104]
Epoch 1830/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.98it/s]

End of Epoch 1830 | Train Loss: 0.030072 | Val Loss: 0.448133

Epoch 1831/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0116]
Epoch 1831/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.12it/s]

End of Epoch 1831 | Train Loss: 0.028247 | Val Loss: 0.588104

Epoch 1832/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00597]
Epoch 1832/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.41it/s]

End of Epoch 1832 | Train Loss: 0.028212 | Val Loss: 0.844812

Epoch 1833/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0319]
Epoch 1833/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.03it/s]

End of Epoch 1833 | Train Loss: 0.023581 | Val Loss: 0.340987

Epoch 1834/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.011]
Epoch 1834/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.38it/s]

End of Epoch 1834 | Train Loss: 0.034737 | Val Loss: 0.903401

Epoch 1835/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00409]
Epoch 1835/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 1835 | Train Loss: 0.024471 | Val Loss: 0.451993

Epoch 1836/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00381]
Epoch 1836/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.17it/s]

End of Epoch 1836 | Train Loss: 0.025772 | Val Loss: 0.790329

Epoch 1837/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00404]
Epoch 1837/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 1837 | Train Loss: 0.023042 | Val Loss: 1.043344

Epoch 1838/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.0824]
Epoch 1838/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.31it/s]

End of Epoch 1838 | Train Loss: 0.028776 | Val Loss: 0.480539

Epoch 1839/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0238]
Epoch 1839/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 1839 | Train Loss: 0.036776 | Val Loss: 0.386529

Epoch 1840/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0163]
Epoch 1840/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.85it/s]

End of Epoch 1840 | Train Loss: 0.027134 | Val Loss: 0.772415

Epoch 1841/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0247]
Epoch 1841/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.95it/s]

End of Epoch 1841 | Train Loss: 0.024701 | Val Loss: 0.492135

Epoch 1842/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.014]
Epoch 1842/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.77it/s]

End of Epoch 1842 | Train Loss: 0.022978 | Val Loss: 0.485532

Epoch 1843/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00825]
Epoch 1843/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 1843 | Train Loss: 0.031172 | Val Loss: 0.383138

Epoch 1844/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00515]
Epoch 1844/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.21it/s]

End of Epoch 1844 | Train Loss: 0.028621 | Val Loss: 0.748494

Epoch 1845/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0501]
Epoch 1845/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.50it/s]

End of Epoch 1845 | Train Loss: 0.034110 | Val Loss: 0.590349

Epoch 1846/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00588]
Epoch 1846/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.71it/s]

End of Epoch 1846 | Train Loss: 0.027633 | Val Loss: 0.253800

Epoch 1847/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00551]
Epoch 1847/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 1847 | Train Loss: 0.029468 | Val Loss: 0.405799

Epoch 1848/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00461]
Epoch 1848/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 1848 | Train Loss: 0.030308 | Val Loss: 0.317430

Epoch 1849/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0036]
Epoch 1849/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 1849 | Train Loss: 0.029447 | Val Loss: 0.485380

Epoch 1850/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.045]
Epoch 1850/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 1850 | Train Loss: 0.026360 | Val Loss: 0.545440

Epoch 1851/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00896]
Epoch 1851/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 1851 | Train Loss: 0.032289 | Val Loss: 0.360330

Epoch 1852/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0168]
Epoch 1852/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.51it/s]

End of Epoch 1852 | Train Loss: 0.023417 | Val Loss: 0.427534

Epoch 1853/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00509]
Epoch 1853/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.74it/s]

End of Epoch 1853 | Train Loss: 0.029487 | Val Loss: 0.485620

Epoch 1854/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00427]
Epoch 1854/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.77it/s]

End of Epoch 1854 | Train Loss: 0.025278 | Val Loss: 0.429271

Epoch 1855/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00364]
Epoch 1855/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 1855 | Train Loss: 0.027987 | Val Loss: 0.416995

Epoch 1856/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00452]
Epoch 1856/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 1856 | Train Loss: 0.022266 | Val Loss: 0.342559

Epoch 1857/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00324]
Epoch 1857/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.89it/s]

End of Epoch 1857 | Train Loss: 0.028066 | Val Loss: 0.477051

Epoch 1858/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00442]
Epoch 1858/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 1858 | Train Loss: 0.024584 | Val Loss: 0.286731

Epoch 1859/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00418]
Epoch 1859/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.84it/s]

End of Epoch 1859 | Train Loss: 0.029653 | Val Loss: 0.308131

Epoch 1860/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0145]
Epoch 1860/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 1860 | Train Loss: 0.028151 | Val Loss: 0.475770

Epoch 1861/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00477]
Epoch 1861/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.57it/s]

End of Epoch 1861 | Train Loss: 0.029842 | Val Loss: 0.307731

Epoch 1862/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00702]
Epoch 1862/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 1862 | Train Loss: 0.033911 | Val Loss: 0.613117

Epoch 1863/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00415]
Epoch 1863/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.38it/s]

End of Epoch 1863 | Train Loss: 0.025020 | Val Loss: 0.508645

Epoch 1864/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0142]
Epoch 1864/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 1864 | Train Loss: 0.029593 | Val Loss: 0.718238

Epoch 1865/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0157]
Epoch 1865/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 1865 | Train Loss: 0.030202 | Val Loss: 0.354103

Epoch 1866/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00558]
Epoch 1866/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 1866 | Train Loss: 0.027635 | Val Loss: 0.304088

Epoch 1867/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0042]
Epoch 1867/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 1867 | Train Loss: 0.021076 | Val Loss: 0.437676

Epoch 1868/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00398]
Epoch 1868/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 1868 | Train Loss: 0.026266 | Val Loss: 0.474324

Epoch 1869/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00411]
Epoch 1869/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.44it/s]

End of Epoch 1869 | Train Loss: 0.024697 | Val Loss: 0.672816

Epoch 1870/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00721]
Epoch 1870/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 1870 | Train Loss: 0.030323 | Val Loss: 0.183386

Epoch 1871/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00398]
Epoch 1871/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.69it/s]

End of Epoch 1871 | Train Loss: 0.029363 | Val Loss: 0.395436

Epoch 1872/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0192]
Epoch 1872/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.67it/s]

End of Epoch 1872 | Train Loss: 0.037967 | Val Loss: 0.629431

Epoch 1873/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.371]
Epoch 1873/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.90it/s]

End of Epoch 1873 | Train Loss: 0.032899 | Val Loss: 0.288386

Epoch 1874/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0126]
Epoch 1874/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 1874 | Train Loss: 0.031931 | Val Loss: 0.491569

Epoch 1875/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00572]
Epoch 1875/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 1875 | Train Loss: 0.030299 | Val Loss: 0.269040

Epoch 1876/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0222]
Epoch 1876/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.43it/s]

End of Epoch 1876 | Train Loss: 0.026741 | Val Loss: 0.342663

Epoch 1877/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.56it/s, loss=0.00359]
Epoch 1877/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 1877 | Train Loss: 0.024182 | Val Loss: 0.607727

Epoch 1878/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00532]
Epoch 1878/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 1878 | Train Loss: 0.030558 | Val Loss: 0.380458

Epoch 1879/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00476]
Epoch 1879/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 1879 | Train Loss: 0.022327 | Val Loss: 0.755884

Epoch 1880/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00474]
Epoch 1880/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 1880 | Train Loss: 0.034071 | Val Loss: 0.218153

Epoch 1881/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00585]
Epoch 1881/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.09it/s]

End of Epoch 1881 | Train Loss: 0.028208 | Val Loss: 0.472912

Epoch 1882/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00435]
Epoch 1882/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.69it/s]

End of Epoch 1882 | Train Loss: 0.026045 | Val Loss: 0.517682

Epoch 1883/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0175]
Epoch 1883/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 1883 | Train Loss: 0.026792 | Val Loss: 0.519383

Epoch 1884/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00901]
Epoch 1884/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.25it/s]

End of Epoch 1884 | Train Loss: 0.027676 | Val Loss: 0.450891

Epoch 1885/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00588]
Epoch 1885/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 1885 | Train Loss: 0.030625 | Val Loss: 0.345296

Epoch 1886/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00353]
Epoch 1886/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.93it/s]

End of Epoch 1886 | Train Loss: 0.028815 | Val Loss: 0.675836

Epoch 1887/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0099]
Epoch 1887/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.57it/s]

End of Epoch 1887 | Train Loss: 0.025288 | Val Loss: 0.362374

Epoch 1888/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0096]
Epoch 1888/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.11it/s]

End of Epoch 1888 | Train Loss: 0.023033 | Val Loss: 0.520316

Epoch 1889/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00388]
Epoch 1889/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.22it/s]

End of Epoch 1889 | Train Loss: 0.026752 | Val Loss: 0.531587

Epoch 1890/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00522]
Epoch 1890/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.32it/s]

End of Epoch 1890 | Train Loss: 0.029709 | Val Loss: 0.396617

Epoch 1891/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00394]
Epoch 1891/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 1891 | Train Loss: 0.021160 | Val Loss: 0.404207

Epoch 1892/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0102]
Epoch 1892/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 1892 | Train Loss: 0.028309 | Val Loss: 0.419073

Epoch 1893/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00521]
Epoch 1893/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 1893 | Train Loss: 0.028119 | Val Loss: 0.739528

Epoch 1894/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00563]
Epoch 1894/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.20it/s]

End of Epoch 1894 | Train Loss: 0.025995 | Val Loss: 0.379231

Epoch 1895/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00914]
Epoch 1895/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.97it/s]

End of Epoch 1895 | Train Loss: 0.022740 | Val Loss: 0.507162

Epoch 1896/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0136]
Epoch 1896/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.05it/s]

End of Epoch 1896 | Train Loss: 0.026306 | Val Loss: 0.317734

Epoch 1897/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.148]
Epoch 1897/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.17it/s]

End of Epoch 1897 | Train Loss: 0.025166 | Val Loss: 0.187982

Epoch 1898/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00779]
Epoch 1898/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 1898 | Train Loss: 0.028748 | Val Loss: 0.374920

Epoch 1899/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00687]
Epoch 1899/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.12it/s]

End of Epoch 1899 | Train Loss: 0.029325 | Val Loss: 0.330567

Epoch 1900/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0134]
Epoch 1900/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.19it/s]

End of Epoch 1900 | Train Loss: 0.025497 | Val Loss: 0.382467

Epoch 1901/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00555]
Epoch 1901/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1901 | Train Loss: 0.028242 | Val Loss: 0.192005

Epoch 1902/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00383]
Epoch 1902/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.95it/s]

End of Epoch 1902 | Train Loss: 0.029870 | Val Loss: 0.657672

Epoch 1903/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0349]
Epoch 1903/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 1903 | Train Loss: 0.027873 | Val Loss: 0.940828

Epoch 1904/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.00446]
Epoch 1904/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.01it/s]

End of Epoch 1904 | Train Loss: 0.025279 | Val Loss: 0.304910

Epoch 1905/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00407]
Epoch 1905/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.28it/s]

End of Epoch 1905 | Train Loss: 0.031278 | Val Loss: 0.384442

Epoch 1906/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00346]
Epoch 1906/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 1906 | Train Loss: 0.023246 | Val Loss: 0.302644

Epoch 1907/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00451]
Epoch 1907/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.62it/s]

End of Epoch 1907 | Train Loss: 0.026305 | Val Loss: 0.558691

Epoch 1908/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00598]
Epoch 1908/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 1908 | Train Loss: 0.038829 | Val Loss: 0.855295

Epoch 1909/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0052]
Epoch 1909/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.72it/s]

End of Epoch 1909 | Train Loss: 0.021651 | Val Loss: 0.472093

Epoch 1910/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0164]
Epoch 1910/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.77it/s]

End of Epoch 1910 | Train Loss: 0.023030 | Val Loss: 0.308148

Epoch 1911/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0041]
Epoch 1911/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 1911 | Train Loss: 0.022921 | Val Loss: 0.390427

Epoch 1912/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00928]
Epoch 1912/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.86it/s]

End of Epoch 1912 | Train Loss: 0.029742 | Val Loss: 0.378469

Epoch 1913/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00329]
Epoch 1913/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.33it/s]

End of Epoch 1913 | Train Loss: 0.030550 | Val Loss: 0.380107

Epoch 1914/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.144]
Epoch 1914/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.96it/s]

End of Epoch 1914 | Train Loss: 0.029729 | Val Loss: 0.306263

Epoch 1915/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00477]
Epoch 1915/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.69it/s]

End of Epoch 1915 | Train Loss: 0.033146 | Val Loss: 0.232686

Epoch 1916/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0034]
Epoch 1916/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 1916 | Train Loss: 0.030081 | Val Loss: 0.403632

Epoch 1917/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00903]
Epoch 1917/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 1917 | Train Loss: 0.026334 | Val Loss: 0.460455

Epoch 1918/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00411]
Epoch 1918/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 1918 | Train Loss: 0.026855 | Val Loss: 0.755089

Epoch 1919/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00348]
Epoch 1919/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 1919 | Train Loss: 0.023851 | Val Loss: 0.596386

Epoch 1920/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00566]
Epoch 1920/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 1920 | Train Loss: 0.028562 | Val Loss: 0.432796

Epoch 1921/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0289]
Epoch 1921/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 1921 | Train Loss: 0.037577 | Val Loss: 0.620985

Epoch 1922/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0115]
Epoch 1922/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 1922 | Train Loss: 0.025889 | Val Loss: 0.223623

Epoch 1923/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00419]
Epoch 1923/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 1923 | Train Loss: 0.031398 | Val Loss: 0.697297

Epoch 1924/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.00346]
Epoch 1924/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.03it/s]

End of Epoch 1924 | Train Loss: 0.022852 | Val Loss: 0.416061

Epoch 1925/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00414]
Epoch 1925/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.78it/s]

End of Epoch 1925 | Train Loss: 0.025019 | Val Loss: 0.547901

Epoch 1926/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00376]
Epoch 1926/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 1926 | Train Loss: 0.024308 | Val Loss: 0.452720

Epoch 1927/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00525]
Epoch 1927/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.80it/s]

End of Epoch 1927 | Train Loss: 0.027746 | Val Loss: 0.461047

Epoch 1928/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0204]
Epoch 1928/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.19it/s]

End of Epoch 1928 | Train Loss: 0.026353 | Val Loss: 0.603002

Epoch 1929/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.021]
Epoch 1929/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.12it/s]

End of Epoch 1929 | Train Loss: 0.027764 | Val Loss: 0.587063

Epoch 1930/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00312]
Epoch 1930/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.20it/s]

End of Epoch 1930 | Train Loss: 0.023302 | Val Loss: 0.247350

Epoch 1931/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00426]
Epoch 1931/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.98it/s]

End of Epoch 1931 | Train Loss: 0.021955 | Val Loss: 0.178484

Epoch 1932/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.35it/s, loss=0.00746]
Epoch 1932/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.51it/s]

End of Epoch 1932 | Train Loss: 0.025955 | Val Loss: 0.460072

Epoch 1933/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00411]
Epoch 1933/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.95it/s]

End of Epoch 1933 | Train Loss: 0.020188 | Val Loss: 0.420720

Epoch 1934/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0043]
Epoch 1934/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 1934 | Train Loss: 0.026559 | Val Loss: 0.585670

Epoch 1935/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0033]
Epoch 1935/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.32it/s]

End of Epoch 1935 | Train Loss: 0.022499 | Val Loss: 0.449719

Epoch 1936/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00328]
Epoch 1936/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 1936 | Train Loss: 0.021239 | Val Loss: 0.406115

Epoch 1937/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00333]
Epoch 1937/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.55it/s]

End of Epoch 1937 | Train Loss: 0.021992 | Val Loss: 0.535724

Epoch 1938/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00765]
Epoch 1938/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 1938 | Train Loss: 0.031655 | Val Loss: 0.470110

Epoch 1939/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00543]
Epoch 1939/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.00it/s]

End of Epoch 1939 | Train Loss: 0.027169 | Val Loss: 0.470484

Epoch 1940/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00514]
Epoch 1940/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.75it/s]

End of Epoch 1940 | Train Loss: 0.028508 | Val Loss: 0.513764

Epoch 1941/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00361]
Epoch 1941/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.49it/s]

End of Epoch 1941 | Train Loss: 0.032099 | Val Loss: 0.645167

Epoch 1942/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00366]
Epoch 1942/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.44it/s]

End of Epoch 1942 | Train Loss: 0.025948 | Val Loss: 0.465801

Epoch 1943/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00815]
Epoch 1943/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 1943 | Train Loss: 0.020793 | Val Loss: 0.743755

Epoch 1944/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00339]
Epoch 1944/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.61it/s]

End of Epoch 1944 | Train Loss: 0.029461 | Val Loss: 0.351282

Epoch 1945/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0125]
Epoch 1945/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 1945 | Train Loss: 0.020866 | Val Loss: 0.616282

Epoch 1946/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00617]
Epoch 1946/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.52it/s]

End of Epoch 1946 | Train Loss: 0.027675 | Val Loss: 0.194951

Epoch 1947/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00385]
Epoch 1947/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 1947 | Train Loss: 0.024560 | Val Loss: 0.334601

Epoch 1948/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0319]
Epoch 1948/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.58it/s]

End of Epoch 1948 | Train Loss: 0.025812 | Val Loss: 0.301909

Epoch 1949/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00435]
Epoch 1949/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 1949 | Train Loss: 0.030879 | Val Loss: 0.269020

Epoch 1950/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00585]
Epoch 1950/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 1950 | Train Loss: 0.024351 | Val Loss: 0.486527

Epoch 1951/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00363]
Epoch 1951/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 1951 | Train Loss: 0.026813 | Val Loss: 0.353601

Epoch 1952/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00477]
Epoch 1952/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.81it/s]

End of Epoch 1952 | Train Loss: 0.028037 | Val Loss: 0.642643

Epoch 1953/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00406]
Epoch 1953/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 1953 | Train Loss: 0.020604 | Val Loss: 0.490534

Epoch 1954/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0256]
Epoch 1954/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.99it/s]

End of Epoch 1954 | Train Loss: 0.027233 | Val Loss: 0.691746

Epoch 1955/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0171]
Epoch 1955/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.31it/s]

End of Epoch 1955 | Train Loss: 0.029097 | Val Loss: 0.685596

Epoch 1956/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.0101]
Epoch 1956/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.71it/s]

End of Epoch 1956 | Train Loss: 0.031147 | Val Loss: 0.442623

Epoch 1957/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0088]
Epoch 1957/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 1957 | Train Loss: 0.035343 | Val Loss: 0.723040

Epoch 1958/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00426]
Epoch 1958/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.66it/s]

End of Epoch 1958 | Train Loss: 0.025296 | Val Loss: 0.544267

Epoch 1959/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00478]
Epoch 1959/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.78it/s]

End of Epoch 1959 | Train Loss: 0.028753 | Val Loss: 0.413254

Epoch 1960/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0195]
Epoch 1960/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 1960 | Train Loss: 0.027628 | Val Loss: 0.492665

Epoch 1961/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00395]
Epoch 1961/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 1961 | Train Loss: 0.025639 | Val Loss: 0.363469

Epoch 1962/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00679]
Epoch 1962/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 1962 | Train Loss: 0.024976 | Val Loss: 0.509325

Epoch 1963/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00411]
Epoch 1963/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.25it/s]

End of Epoch 1963 | Train Loss: 0.029423 | Val Loss: 0.402119

Epoch 1964/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00533]
Epoch 1964/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.16it/s]

End of Epoch 1964 | Train Loss: 0.025758 | Val Loss: 0.289177

Epoch 1965/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00396]
Epoch 1965/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 1965 | Train Loss: 0.022204 | Val Loss: 0.771939

Epoch 1966/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.0384]
Epoch 1966/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.92it/s]

End of Epoch 1966 | Train Loss: 0.035005 | Val Loss: 0.862681

Epoch 1967/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0043]
Epoch 1967/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 1967 | Train Loss: 0.025025 | Val Loss: 0.581566

Epoch 1968/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00555]
Epoch 1968/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 1968 | Train Loss: 0.025815 | Val Loss: 0.506743

Epoch 1969/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0035]
Epoch 1969/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.83it/s]

End of Epoch 1969 | Train Loss: 0.026215 | Val Loss: 0.490135

Epoch 1970/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00397]
Epoch 1970/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.58it/s]

End of Epoch 1970 | Train Loss: 0.025457 | Val Loss: 0.391715

Epoch 1971/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00475]
Epoch 1971/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 1971 | Train Loss: 0.032424 | Val Loss: 0.367977

Epoch 1972/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00341]
Epoch 1972/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.02it/s]

End of Epoch 1972 | Train Loss: 0.022141 | Val Loss: 0.296981

Epoch 1973/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00404]
Epoch 1973/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.19it/s]

End of Epoch 1973 | Train Loss: 0.025924 | Val Loss: 0.286179

Epoch 1974/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0164]
Epoch 1974/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.33it/s]

End of Epoch 1974 | Train Loss: 0.029893 | Val Loss: 0.699711

Epoch 1975/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.011]
Epoch 1975/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.57it/s]

End of Epoch 1975 | Train Loss: 0.025581 | Val Loss: 0.286310

Epoch 1976/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00413]
Epoch 1976/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.20it/s]

End of Epoch 1976 | Train Loss: 0.028721 | Val Loss: 0.449675

Epoch 1977/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.0111]
Epoch 1977/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.52it/s]

End of Epoch 1977 | Train Loss: 0.029148 | Val Loss: 0.215663

Epoch 1978/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00444]
Epoch 1978/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.30it/s]

End of Epoch 1978 | Train Loss: 0.034262 | Val Loss: 0.292016

Epoch 1979/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00283]
Epoch 1979/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 1979 | Train Loss: 0.022115 | Val Loss: 0.595388

Epoch 1980/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00365]
Epoch 1980/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.57it/s]

End of Epoch 1980 | Train Loss: 0.022793 | Val Loss: 0.349358

Epoch 1981/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00669]
Epoch 1981/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 1981 | Train Loss: 0.022465 | Val Loss: 0.240423

Epoch 1982/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0487]
Epoch 1982/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 1982 | Train Loss: 0.028141 | Val Loss: 0.369190

Epoch 1983/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0042]
Epoch 1983/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.06it/s]

End of Epoch 1983 | Train Loss: 0.028010 | Val Loss: 0.624945

Epoch 1984/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0176]
Epoch 1984/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.89it/s]

End of Epoch 1984 | Train Loss: 0.032442 | Val Loss: 0.339367

Epoch 1985/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00501]
Epoch 1985/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.22it/s]

End of Epoch 1985 | Train Loss: 0.021160 | Val Loss: 0.344376

Epoch 1986/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.0627]
Epoch 1986/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 1986 | Train Loss: 0.031514 | Val Loss: 0.492655

Epoch 1987/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00573]
Epoch 1987/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.63it/s]

End of Epoch 1987 | Train Loss: 0.024565 | Val Loss: 0.356255

Epoch 1988/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00418]
Epoch 1988/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.23it/s]

End of Epoch 1988 | Train Loss: 0.025815 | Val Loss: 0.593047

Epoch 1989/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00409]
Epoch 1989/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.72it/s]

End of Epoch 1989 | Train Loss: 0.024032 | Val Loss: 0.646957

Epoch 1990/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00451]
Epoch 1990/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.15it/s]

End of Epoch 1990 | Train Loss: 0.028093 | Val Loss: 0.441997

Epoch 1991/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00906]
Epoch 1991/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 1991 | Train Loss: 0.024841 | Val Loss: 0.397521

Epoch 1992/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00456]
Epoch 1992/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.98it/s]

End of Epoch 1992 | Train Loss: 0.028114 | Val Loss: 0.302361

Epoch 1993/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00467]
Epoch 1993/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.05it/s]

End of Epoch 1993 | Train Loss: 0.024130 | Val Loss: 0.662254

Epoch 1994/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00362]
Epoch 1994/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 1994 | Train Loss: 0.027508 | Val Loss: 0.579217

Epoch 1995/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0122]
Epoch 1995/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.82it/s]

End of Epoch 1995 | Train Loss: 0.029814 | Val Loss: 0.752056

Epoch 1996/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0125]
Epoch 1996/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.62it/s]

End of Epoch 1996 | Train Loss: 0.027796 | Val Loss: 0.418464

Epoch 1997/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.38it/s, loss=0.00358]
Epoch 1997/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.17it/s]

End of Epoch 1997 | Train Loss: 0.028460 | Val Loss: 0.313236

Epoch 1998/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00312]
Epoch 1998/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.54it/s]

End of Epoch 1998 | Train Loss: 0.015212 | Val Loss: 0.676620

Epoch 1999/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00448]
Epoch 1999/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 1999 | Train Loss: 0.023032 | Val Loss: 0.555663

Epoch 2000/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0665]
Epoch 2000/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.15it/s]

End of Epoch 2000 | Train Loss: 0.025141 | Val Loss: 0.556659

Epoch 2001/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00571]
Epoch 2001/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.55it/s]

End of Epoch 2001 | Train Loss: 0.034914 | Val Loss: 0.398763

Epoch 2002/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0888]
Epoch 2002/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 2002 | Train Loss: 0.026338 | Val Loss: 0.594672

Epoch 2003/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00375]
Epoch 2003/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2003 | Train Loss: 0.021190 | Val Loss: 0.447235

Epoch 2004/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00853]
Epoch 2004/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 2004 | Train Loss: 0.020567 | Val Loss: 0.558551

Epoch 2005/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00369]
Epoch 2005/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 2005 | Train Loss: 0.025395 | Val Loss: 0.512023

Epoch 2006/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00356]
Epoch 2006/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.60it/s]

End of Epoch 2006 | Train Loss: 0.025265 | Val Loss: 0.284238

Epoch 2007/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.73]
Epoch 2007/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.68it/s]

End of Epoch 2007 | Train Loss: 0.038651 | Val Loss: 0.548937

Epoch 2008/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00499]
Epoch 2008/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 2008 | Train Loss: 0.042063 | Val Loss: 0.485589

Epoch 2009/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0155]
Epoch 2009/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 2009 | Train Loss: 0.033111 | Val Loss: 0.401921

Epoch 2010/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00306]
Epoch 2010/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.30it/s]

End of Epoch 2010 | Train Loss: 0.027837 | Val Loss: 0.413426

Epoch 2011/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00323]
Epoch 2011/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 2011 | Train Loss: 0.022079 | Val Loss: 0.384080

Epoch 2012/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00837]
Epoch 2012/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 2012 | Train Loss: 0.025776 | Val Loss: 0.643308

Epoch 2013/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0207]
Epoch 2013/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.09it/s]

End of Epoch 2013 | Train Loss: 0.030524 | Val Loss: 0.496235

Epoch 2014/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00723]
Epoch 2014/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.15it/s]

End of Epoch 2014 | Train Loss: 0.025215 | Val Loss: 0.463149

Epoch 2015/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.00507]
Epoch 2015/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.73it/s]

End of Epoch 2015 | Train Loss: 0.028005 | Val Loss: 0.981505

Epoch 2016/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00759]
Epoch 2016/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 2016 | Train Loss: 0.025685 | Val Loss: 0.771201

Epoch 2017/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0457]
Epoch 2017/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.29it/s]

End of Epoch 2017 | Train Loss: 0.027765 | Val Loss: 0.454609

Epoch 2018/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.501]
Epoch 2018/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 2018 | Train Loss: 0.034526 | Val Loss: 0.421629

Epoch 2019/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0443]
Epoch 2019/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 2019 | Train Loss: 0.028704 | Val Loss: 0.339341

Epoch 2020/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00607]
Epoch 2020/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 2020 | Train Loss: 0.024423 | Val Loss: 0.452703

Epoch 2021/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.209]
Epoch 2021/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.04it/s]

End of Epoch 2021 | Train Loss: 0.034409 | Val Loss: 0.397437

Epoch 2022/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00382]
Epoch 2022/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.25it/s]

End of Epoch 2022 | Train Loss: 0.032675 | Val Loss: 1.014773

Epoch 2023/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00616]
Epoch 2023/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.42it/s]

End of Epoch 2023 | Train Loss: 0.022745 | Val Loss: 0.256516

Epoch 2024/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0246]
Epoch 2024/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.49it/s]

End of Epoch 2024 | Train Loss: 0.023535 | Val Loss: 0.485112

Epoch 2025/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00758]
Epoch 2025/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.87it/s]

End of Epoch 2025 | Train Loss: 0.027903 | Val Loss: 0.516033

Epoch 2026/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.056]
Epoch 2026/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.48it/s]

End of Epoch 2026 | Train Loss: 0.024544 | Val Loss: 0.491528

Epoch 2027/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00409]
Epoch 2027/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.04it/s]

End of Epoch 2027 | Train Loss: 0.032376 | Val Loss: 0.426536

Epoch 2028/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00629]
Epoch 2028/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.21it/s]

End of Epoch 2028 | Train Loss: 0.028422 | Val Loss: 0.510446

Epoch 2029/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00391]
Epoch 2029/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.04it/s]

End of Epoch 2029 | Train Loss: 0.021989 | Val Loss: 0.326765

Epoch 2030/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00808]
Epoch 2030/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 2030 | Train Loss: 0.023651 | Val Loss: 0.630390

Epoch 2031/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00395]
Epoch 2031/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.77it/s]

End of Epoch 2031 | Train Loss: 0.022414 | Val Loss: 0.644888

Epoch 2032/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00355]
Epoch 2032/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.64it/s]

End of Epoch 2032 | Train Loss: 0.025228 | Val Loss: 0.552714

Epoch 2033/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0195]
Epoch 2033/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 2033 | Train Loss: 0.023083 | Val Loss: 0.542337

Epoch 2034/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00977]
Epoch 2034/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 2034 | Train Loss: 0.033566 | Val Loss: 0.319002

Epoch 2035/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00322]
Epoch 2035/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 2035 | Train Loss: 0.027588 | Val Loss: 0.637097

Epoch 2036/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00403]
Epoch 2036/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 2036 | Train Loss: 0.022644 | Val Loss: 0.316136

Epoch 2037/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0109]
Epoch 2037/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 2037 | Train Loss: 0.027906 | Val Loss: 0.384902

Epoch 2038/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00872]
Epoch 2038/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.56it/s]

End of Epoch 2038 | Train Loss: 0.027712 | Val Loss: 0.619149

Epoch 2039/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0438]
Epoch 2039/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 2039 | Train Loss: 0.025262 | Val Loss: 0.689392

Epoch 2040/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00418]
Epoch 2040/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.74it/s]

End of Epoch 2040 | Train Loss: 0.029888 | Val Loss: 0.439724

Epoch 2041/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0123]
Epoch 2041/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.33it/s]

End of Epoch 2041 | Train Loss: 0.025380 | Val Loss: 0.700766

Epoch 2042/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00369]
Epoch 2042/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.02it/s]

End of Epoch 2042 | Train Loss: 0.020090 | Val Loss: 0.516079

Epoch 2043/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00972]
Epoch 2043/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 2043 | Train Loss: 0.029241 | Val Loss: 0.776125

Epoch 2044/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00403]
Epoch 2044/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.81it/s]

End of Epoch 2044 | Train Loss: 0.031003 | Val Loss: 0.238571

Epoch 2045/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00536]
Epoch 2045/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.85it/s]

End of Epoch 2045 | Train Loss: 0.021711 | Val Loss: 0.751340

Epoch 2046/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00451]
Epoch 2046/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.82it/s]

End of Epoch 2046 | Train Loss: 0.017368 | Val Loss: 0.633578

Epoch 2047/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00389]
Epoch 2047/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 2047 | Train Loss: 0.026164 | Val Loss: 0.318756

Epoch 2048/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00326]
Epoch 2048/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.20it/s]

End of Epoch 2048 | Train Loss: 0.018657 | Val Loss: 0.341417

Epoch 2049/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00557]
Epoch 2049/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 2049 | Train Loss: 0.033090 | Val Loss: 0.469247

Epoch 2050/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00312]
Epoch 2050/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.84it/s]

End of Epoch 2050 | Train Loss: 0.027439 | Val Loss: 0.295223

Epoch 2051/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00313]
Epoch 2051/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 2051 | Train Loss: 0.020618 | Val Loss: 0.307400

Epoch 2052/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00347]
Epoch 2052/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 2052 | Train Loss: 0.027665 | Val Loss: 0.432812

Epoch 2053/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00382]
Epoch 2053/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 2053 | Train Loss: 0.024088 | Val Loss: 0.298746

Epoch 2054/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.77]
Epoch 2054/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 2054 | Train Loss: 0.035791 | Val Loss: 0.380370

Epoch 2055/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.0355]
Epoch 2055/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 2055 | Train Loss: 0.032546 | Val Loss: 0.431354

Epoch 2056/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0491]
Epoch 2056/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.50it/s]

End of Epoch 2056 | Train Loss: 0.027932 | Val Loss: 0.255996

Epoch 2057/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.0148]
Epoch 2057/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.03it/s]

End of Epoch 2057 | Train Loss: 0.032345 | Val Loss: 0.557011

Epoch 2058/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0044]
Epoch 2058/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 2058 | Train Loss: 0.022868 | Val Loss: 0.684498

Epoch 2059/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00757]
Epoch 2059/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 2059 | Train Loss: 0.027711 | Val Loss: 0.508872

Epoch 2060/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00371]
Epoch 2060/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 2060 | Train Loss: 0.020687 | Val Loss: 0.372373

Epoch 2061/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00593]
Epoch 2061/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 2061 | Train Loss: 0.029025 | Val Loss: 0.253898

Epoch 2062/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0125]
Epoch 2062/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 2062 | Train Loss: 0.025241 | Val Loss: 0.808499

Epoch 2063/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00531]
Epoch 2063/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.60it/s]

End of Epoch 2063 | Train Loss: 0.025758 | Val Loss: 0.372771

Epoch 2064/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00354]
Epoch 2064/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.59it/s]

End of Epoch 2064 | Train Loss: 0.024465 | Val Loss: 0.196606

Epoch 2065/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.884]
Epoch 2065/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 2065 | Train Loss: 0.038868 | Val Loss: 0.217462

Epoch 2066/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00662]
Epoch 2066/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.64it/s]

End of Epoch 2066 | Train Loss: 0.038106 | Val Loss: 0.249493

Epoch 2067/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00628]
Epoch 2067/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.91it/s]

End of Epoch 2067 | Train Loss: 0.027374 | Val Loss: 0.627305

Epoch 2068/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00311]
Epoch 2068/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 2068 | Train Loss: 0.029087 | Val Loss: 0.387826

Epoch 2069/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.309]
Epoch 2069/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.63it/s]

End of Epoch 2069 | Train Loss: 0.024739 | Val Loss: 0.331704

Epoch 2070/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00367]
Epoch 2070/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.13it/s]

End of Epoch 2070 | Train Loss: 0.032656 | Val Loss: 0.526876

Epoch 2071/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00607]
Epoch 2071/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.90it/s]

End of Epoch 2071 | Train Loss: 0.028197 | Val Loss: 0.677986

Epoch 2072/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00637]
Epoch 2072/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.52it/s]

End of Epoch 2072 | Train Loss: 0.021728 | Val Loss: 0.368042

Epoch 2073/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00538]
Epoch 2073/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 2073 | Train Loss: 0.027924 | Val Loss: 0.355315

Epoch 2074/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.37it/s, loss=0.00383]
Epoch 2074/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.54it/s]

End of Epoch 2074 | Train Loss: 0.024726 | Val Loss: 0.358534

Epoch 2075/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0491]
Epoch 2075/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.73it/s]

End of Epoch 2075 | Train Loss: 0.023879 | Val Loss: 0.338954

Epoch 2076/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00338]
Epoch 2076/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.07it/s]

End of Epoch 2076 | Train Loss: 0.020989 | Val Loss: 0.473279

Epoch 2077/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00383]
Epoch 2077/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 2077 | Train Loss: 0.019395 | Val Loss: 0.515057

Epoch 2078/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00313]
Epoch 2078/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.13it/s]

End of Epoch 2078 | Train Loss: 0.028687 | Val Loss: 0.488839

Epoch 2079/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00524]
Epoch 2079/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.27it/s]

End of Epoch 2079 | Train Loss: 0.029444 | Val Loss: 0.363095

Epoch 2080/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00293]
Epoch 2080/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.16it/s]

End of Epoch 2080 | Train Loss: 0.022363 | Val Loss: 0.374748

Epoch 2081/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00404]
Epoch 2081/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.50it/s]

End of Epoch 2081 | Train Loss: 0.023367 | Val Loss: 0.541565

Epoch 2082/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.013]
Epoch 2082/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.01it/s]

End of Epoch 2082 | Train Loss: 0.028361 | Val Loss: 0.328767

Epoch 2083/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.011]
Epoch 2083/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.55it/s]

End of Epoch 2083 | Train Loss: 0.026127 | Val Loss: 0.564454

Epoch 2084/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00438]
Epoch 2084/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 2084 | Train Loss: 0.032311 | Val Loss: 0.340583

Epoch 2085/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.218]
Epoch 2085/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 2085 | Train Loss: 0.027973 | Val Loss: 0.485716

Epoch 2086/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0184]
Epoch 2086/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.75it/s]

End of Epoch 2086 | Train Loss: 0.027882 | Val Loss: 0.154575

Epoch 2087/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00419]
Epoch 2087/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.53it/s]

End of Epoch 2087 | Train Loss: 0.031993 | Val Loss: 0.291132

Epoch 2088/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00616]
Epoch 2088/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.14it/s]

End of Epoch 2088 | Train Loss: 0.028523 | Val Loss: 0.591366

Epoch 2089/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0033]
Epoch 2089/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 2089 | Train Loss: 0.024364 | Val Loss: 0.602508

Epoch 2090/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.137]
Epoch 2090/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 2090 | Train Loss: 0.020700 | Val Loss: 0.514159

Epoch 2091/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0227]
Epoch 2091/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.74it/s]

End of Epoch 2091 | Train Loss: 0.023353 | Val Loss: 0.696051

Epoch 2092/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00572]
Epoch 2092/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 2092 | Train Loss: 0.026334 | Val Loss: 0.384267

Epoch 2093/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00351]
Epoch 2093/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 2093 | Train Loss: 0.023824 | Val Loss: 0.379616

Epoch 2094/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.47it/s, loss=0.0071]
Epoch 2094/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.88it/s]

End of Epoch 2094 | Train Loss: 0.026507 | Val Loss: 0.448098

Epoch 2095/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0401]
Epoch 2095/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 2095 | Train Loss: 0.024925 | Val Loss: 0.527517

Epoch 2096/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0148]
Epoch 2096/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.63it/s]

End of Epoch 2096 | Train Loss: 0.024327 | Val Loss: 0.378329

Epoch 2097/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0039]
Epoch 2097/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 2097 | Train Loss: 0.023257 | Val Loss: 0.489422

Epoch 2098/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00645]
Epoch 2098/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.44it/s]

End of Epoch 2098 | Train Loss: 0.026762 | Val Loss: 0.743279

Epoch 2099/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00444]
Epoch 2099/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 2099 | Train Loss: 0.029555 | Val Loss: 0.400579

Epoch 2100/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00939]
Epoch 2100/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.49it/s]

End of Epoch 2100 | Train Loss: 0.022604 | Val Loss: 0.703898

Epoch 2101/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00371]
Epoch 2101/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.96it/s]

End of Epoch 2101 | Train Loss: 0.020066 | Val Loss: 0.471353

Epoch 2102/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0182]
Epoch 2102/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 2102 | Train Loss: 0.021368 | Val Loss: 0.196214

Epoch 2103/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0039]
Epoch 2103/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.36it/s]

End of Epoch 2103 | Train Loss: 0.026458 | Val Loss: 0.348551

Epoch 2104/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00507]
Epoch 2104/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.40it/s]

End of Epoch 2104 | Train Loss: 0.027009 | Val Loss: 0.293704

Epoch 2105/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.014]
Epoch 2105/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 2105 | Train Loss: 0.025982 | Val Loss: 0.527137

Epoch 2106/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00434]
Epoch 2106/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 2106 | Train Loss: 0.026672 | Val Loss: 0.320676

Epoch 2107/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0635]
Epoch 2107/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 2107 | Train Loss: 0.030204 | Val Loss: 0.164056

Epoch 2108/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00664]
Epoch 2108/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 2108 | Train Loss: 0.024952 | Val Loss: 0.689921

Epoch 2109/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0028]
Epoch 2109/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.41it/s]

End of Epoch 2109 | Train Loss: 0.022865 | Val Loss: 0.676267

Epoch 2110/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00681]
Epoch 2110/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.07it/s]

End of Epoch 2110 | Train Loss: 0.028591 | Val Loss: 0.376591

Epoch 2111/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00344]
Epoch 2111/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 2111 | Train Loss: 0.022128 | Val Loss: 0.645971

Epoch 2112/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.33it/s, loss=0.0062]
Epoch 2112/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.54it/s]

End of Epoch 2112 | Train Loss: 0.026192 | Val Loss: 0.378807

Epoch 2113/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00396]
Epoch 2113/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.27it/s]

End of Epoch 2113 | Train Loss: 0.023266 | Val Loss: 0.389211

Epoch 2114/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.53it/s, loss=0.00378]
Epoch 2114/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.22it/s]

End of Epoch 2114 | Train Loss: 0.024510 | Val Loss: 0.654616

Epoch 2115/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00542]
Epoch 2115/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.61it/s]

End of Epoch 2115 | Train Loss: 0.024286 | Val Loss: 0.344036

Epoch 2116/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00502]
Epoch 2116/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 2116 | Train Loss: 0.031090 | Val Loss: 0.333223

Epoch 2117/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00636]
Epoch 2117/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.15it/s]

End of Epoch 2117 | Train Loss: 0.028404 | Val Loss: 0.305866

Epoch 2118/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0203]
Epoch 2118/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.83it/s]

End of Epoch 2118 | Train Loss: 0.024298 | Val Loss: 0.287982

Epoch 2119/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00528]
Epoch 2119/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.76it/s]

End of Epoch 2119 | Train Loss: 0.028609 | Val Loss: 0.389873

Epoch 2120/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00316]
Epoch 2120/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 2120 | Train Loss: 0.023668 | Val Loss: 0.148233

Epoch 2121/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0094]
Epoch 2121/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 2121 | Train Loss: 0.021675 | Val Loss: 0.514098

Epoch 2122/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0206]
Epoch 2122/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.17it/s]

End of Epoch 2122 | Train Loss: 0.023841 | Val Loss: 0.617891

Epoch 2123/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0281]
Epoch 2123/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 2123 | Train Loss: 0.021795 | Val Loss: 0.780156

Epoch 2124/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00405]
Epoch 2124/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.22it/s]

End of Epoch 2124 | Train Loss: 0.021648 | Val Loss: 0.612868

Epoch 2125/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00446]
Epoch 2125/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.06it/s]

End of Epoch 2125 | Train Loss: 0.029518 | Val Loss: 0.255741

Epoch 2126/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00432]
Epoch 2126/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 2126 | Train Loss: 0.030976 | Val Loss: 0.499952

Epoch 2127/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00755]
Epoch 2127/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.96it/s]

End of Epoch 2127 | Train Loss: 0.024020 | Val Loss: 0.634004

Epoch 2128/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0125]
Epoch 2128/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.14it/s]

End of Epoch 2128 | Train Loss: 0.026477 | Val Loss: 0.538318

Epoch 2129/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0125]
Epoch 2129/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 2129 | Train Loss: 0.027900 | Val Loss: 0.463600

Epoch 2130/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.034]
Epoch 2130/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.16it/s]

End of Epoch 2130 | Train Loss: 0.027943 | Val Loss: 0.473909

Epoch 2131/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00565]
Epoch 2131/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.73it/s]

End of Epoch 2131 | Train Loss: 0.024535 | Val Loss: 0.680131

Epoch 2132/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.306]
Epoch 2132/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.38it/s]

End of Epoch 2132 | Train Loss: 0.031074 | Val Loss: 0.315319

Epoch 2133/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0117]
Epoch 2133/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.51it/s]

End of Epoch 2133 | Train Loss: 0.030879 | Val Loss: 0.523326

Epoch 2134/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0715]
Epoch 2134/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.20it/s]

End of Epoch 2134 | Train Loss: 0.021576 | Val Loss: 0.420358

Epoch 2135/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00366]
Epoch 2135/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.74it/s]

End of Epoch 2135 | Train Loss: 0.030056 | Val Loss: 0.210234

Epoch 2136/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00418]
Epoch 2136/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 2136 | Train Loss: 0.028724 | Val Loss: 0.259357

Epoch 2137/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00306]
Epoch 2137/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 2137 | Train Loss: 0.016103 | Val Loss: 0.330363

Epoch 2138/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00434]
Epoch 2138/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 2138 | Train Loss: 0.025098 | Val Loss: 0.222402

Epoch 2139/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00522]
Epoch 2139/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 2139 | Train Loss: 0.032217 | Val Loss: 0.558527

Epoch 2140/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0394]
Epoch 2140/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 2140 | Train Loss: 0.026721 | Val Loss: 0.531870

Epoch 2141/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00331]
Epoch 2141/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.89it/s]

End of Epoch 2141 | Train Loss: 0.020270 | Val Loss: 0.442601

Epoch 2142/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00331]
Epoch 2142/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.63it/s]

End of Epoch 2142 | Train Loss: 0.018690 | Val Loss: 0.426093

Epoch 2143/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.262]
Epoch 2143/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.88it/s]

End of Epoch 2143 | Train Loss: 0.042465 | Val Loss: 0.422351

Epoch 2144/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0916]
Epoch 2144/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.27it/s]

End of Epoch 2144 | Train Loss: 0.029422 | Val Loss: 0.228230

Epoch 2145/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00456]
Epoch 2145/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 2145 | Train Loss: 0.027727 | Val Loss: 0.448019

Epoch 2146/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00827]
Epoch 2146/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 2146 | Train Loss: 0.029335 | Val Loss: 0.551670

Epoch 2147/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0069]
Epoch 2147/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.41it/s]

End of Epoch 2147 | Train Loss: 0.026936 | Val Loss: 0.568012

Epoch 2148/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0181]
Epoch 2148/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 2148 | Train Loss: 0.021520 | Val Loss: 0.766927

Epoch 2149/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00394]
Epoch 2149/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.82it/s]

End of Epoch 2149 | Train Loss: 0.025977 | Val Loss: 0.284067

Epoch 2150/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00326]
Epoch 2150/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 2150 | Train Loss: 0.024646 | Val Loss: 0.475360

Epoch 2151/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00347]
Epoch 2151/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 2151 | Train Loss: 0.026117 | Val Loss: 0.404540

Epoch 2152/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0234]
Epoch 2152/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 2152 | Train Loss: 0.025881 | Val Loss: 0.435309

Epoch 2153/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00341]
Epoch 2153/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.91it/s]

End of Epoch 2153 | Train Loss: 0.022988 | Val Loss: 0.457865

Epoch 2154/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00392]
Epoch 2154/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.08it/s]

End of Epoch 2154 | Train Loss: 0.024583 | Val Loss: 0.482543

Epoch 2155/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00724]
Epoch 2155/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 2155 | Train Loss: 0.029801 | Val Loss: 0.303236

Epoch 2156/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00443]
Epoch 2156/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 2156 | Train Loss: 0.026897 | Val Loss: 0.324652

Epoch 2157/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00309]
Epoch 2157/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.71it/s]

End of Epoch 2157 | Train Loss: 0.022425 | Val Loss: 0.335462

Epoch 2158/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00692]
Epoch 2158/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.34it/s]

End of Epoch 2158 | Train Loss: 0.031699 | Val Loss: 0.284782

Epoch 2159/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00475]
Epoch 2159/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.52it/s]

End of Epoch 2159 | Train Loss: 0.029493 | Val Loss: 0.520888

Epoch 2160/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00421]
Epoch 2160/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 2160 | Train Loss: 0.029078 | Val Loss: 0.404890

Epoch 2161/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00424]
Epoch 2161/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.16it/s]

End of Epoch 2161 | Train Loss: 0.024938 | Val Loss: 0.633220

Epoch 2162/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0126]
Epoch 2162/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 2162 | Train Loss: 0.026375 | Val Loss: 0.319162

Epoch 2163/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0052]
Epoch 2163/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 2163 | Train Loss: 0.029756 | Val Loss: 0.766202

Epoch 2164/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00312]
Epoch 2164/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 2164 | Train Loss: 0.029142 | Val Loss: 0.597115

Epoch 2165/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00436]
Epoch 2165/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 2165 | Train Loss: 0.025643 | Val Loss: 0.399580

Epoch 2166/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.288]
Epoch 2166/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 2166 | Train Loss: 0.030035 | Val Loss: 0.314320

Epoch 2167/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00414]
Epoch 2167/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.33it/s]

End of Epoch 2167 | Train Loss: 0.031992 | Val Loss: 0.448086

Epoch 2168/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00389]
Epoch 2168/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.02it/s]

End of Epoch 2168 | Train Loss: 0.028920 | Val Loss: 0.534119

Epoch 2169/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00256]
Epoch 2169/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.19it/s]

End of Epoch 2169 | Train Loss: 0.031935 | Val Loss: 0.349366

Epoch 2170/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00426]
Epoch 2170/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.82it/s]

End of Epoch 2170 | Train Loss: 0.025471 | Val Loss: 0.314876

Epoch 2171/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00447]
Epoch 2171/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.10it/s]

End of Epoch 2171 | Train Loss: 0.026994 | Val Loss: 0.348657

Epoch 2172/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0324]
Epoch 2172/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.86it/s]

End of Epoch 2172 | Train Loss: 0.024862 | Val Loss: 0.344257

Epoch 2173/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.0167]
Epoch 2173/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.00it/s]

End of Epoch 2173 | Train Loss: 0.026061 | Val Loss: 0.461314

Epoch 2174/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00336]
Epoch 2174/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 2174 | Train Loss: 0.023171 | Val Loss: 0.304883

Epoch 2175/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00473]
Epoch 2175/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.36it/s]

End of Epoch 2175 | Train Loss: 0.020658 | Val Loss: 0.395985

Epoch 2176/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00439]
Epoch 2176/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.15it/s]

End of Epoch 2176 | Train Loss: 0.025714 | Val Loss: 0.397864

Epoch 2177/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0297]
Epoch 2177/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 2177 | Train Loss: 0.026629 | Val Loss: 0.612242

Epoch 2178/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00322]
Epoch 2178/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.61it/s]

End of Epoch 2178 | Train Loss: 0.028734 | Val Loss: 0.223409

Epoch 2179/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00342]
Epoch 2179/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 2179 | Train Loss: 0.023172 | Val Loss: 0.800796

Epoch 2180/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0029]
Epoch 2180/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 2180 | Train Loss: 0.024986 | Val Loss: 0.273633

Epoch 2181/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00367]
Epoch 2181/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.55it/s]

End of Epoch 2181 | Train Loss: 0.030299 | Val Loss: 0.499418

Epoch 2182/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0107]
Epoch 2182/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.24it/s]

End of Epoch 2182 | Train Loss: 0.017572 | Val Loss: 0.546134

Epoch 2183/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00363]
Epoch 2183/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 2183 | Train Loss: 0.021327 | Val Loss: 0.827366

Epoch 2184/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0171]
Epoch 2184/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 2184 | Train Loss: 0.025680 | Val Loss: 0.337915

Epoch 2185/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00477]
Epoch 2185/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.45it/s]

End of Epoch 2185 | Train Loss: 0.025054 | Val Loss: 0.356754

Epoch 2186/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00408]
Epoch 2186/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.94it/s]

End of Epoch 2186 | Train Loss: 0.032427 | Val Loss: 0.478563

Epoch 2187/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.253]
Epoch 2187/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 2187 | Train Loss: 0.024949 | Val Loss: 0.375410

Epoch 2188/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.011]
Epoch 2188/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 2188 | Train Loss: 0.028237 | Val Loss: 0.722523

Epoch 2189/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00357]
Epoch 2189/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.11it/s]

End of Epoch 2189 | Train Loss: 0.035102 | Val Loss: 0.398400

Epoch 2190/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.195]
Epoch 2190/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.89it/s]

End of Epoch 2190 | Train Loss: 0.022484 | Val Loss: 0.338713

Epoch 2191/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00389]
Epoch 2191/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.00it/s]

End of Epoch 2191 | Train Loss: 0.030734 | Val Loss: 0.619890

Epoch 2192/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00732]
Epoch 2192/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.78it/s]

End of Epoch 2192 | Train Loss: 0.024523 | Val Loss: 0.338066

Epoch 2193/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.55it/s, loss=0.00788]
Epoch 2193/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.85it/s]

End of Epoch 2193 | Train Loss: 0.027589 | Val Loss: 0.369697

Epoch 2194/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00312]
Epoch 2194/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 2194 | Train Loss: 0.026349 | Val Loss: 0.338233

Epoch 2195/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0142]
Epoch 2195/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 2195 | Train Loss: 0.031461 | Val Loss: 0.397308

Epoch 2196/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00707]
Epoch 2196/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 2196 | Train Loss: 0.026802 | Val Loss: 0.227844

Epoch 2197/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00907]
Epoch 2197/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 2197 | Train Loss: 0.030236 | Val Loss: 0.291348

Epoch 2198/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00445]
Epoch 2198/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.43it/s]

End of Epoch 2198 | Train Loss: 0.023658 | Val Loss: 0.473895

Epoch 2199/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00357]
Epoch 2199/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 2199 | Train Loss: 0.023893 | Val Loss: 0.317488

Epoch 2200/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00609]
Epoch 2200/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 2200 | Train Loss: 0.026997 | Val Loss: 0.361631

Epoch 2201/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0043]
Epoch 2201/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.94it/s]

End of Epoch 2201 | Train Loss: 0.028732 | Val Loss: 0.373391

Epoch 2202/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00896]
Epoch 2202/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.59it/s]

End of Epoch 2202 | Train Loss: 0.019517 | Val Loss: 0.373959

Epoch 2203/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00416]
Epoch 2203/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.12it/s]

End of Epoch 2203 | Train Loss: 0.020847 | Val Loss: 0.510105

Epoch 2204/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00421]
Epoch 2204/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.17it/s]

End of Epoch 2204 | Train Loss: 0.028638 | Val Loss: 0.450510

Epoch 2205/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00669]
Epoch 2205/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.06it/s]

End of Epoch 2205 | Train Loss: 0.027134 | Val Loss: 0.259902

Epoch 2206/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0042]
Epoch 2206/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.40it/s]

End of Epoch 2206 | Train Loss: 0.024594 | Val Loss: 0.320718

Epoch 2207/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0033]
Epoch 2207/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.64it/s]

End of Epoch 2207 | Train Loss: 0.022991 | Val Loss: 0.735978

Epoch 2208/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00416]
Epoch 2208/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.42it/s]

End of Epoch 2208 | Train Loss: 0.022324 | Val Loss: 0.519415

Epoch 2209/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00335]
Epoch 2209/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.33it/s]

End of Epoch 2209 | Train Loss: 0.024455 | Val Loss: 0.403215

Epoch 2210/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00467]
Epoch 2210/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 2210 | Train Loss: 0.024169 | Val Loss: 0.578130

Epoch 2211/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00521]
Epoch 2211/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.28it/s]

End of Epoch 2211 | Train Loss: 0.026483 | Val Loss: 0.691195

Epoch 2212/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.55it/s, loss=0.00404]
Epoch 2212/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 2212 | Train Loss: 0.026864 | Val Loss: 0.563602

Epoch 2213/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00472]
Epoch 2213/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.80it/s]

End of Epoch 2213 | Train Loss: 0.022472 | Val Loss: 0.481685

Epoch 2214/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00961]
Epoch 2214/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.09it/s]

End of Epoch 2214 | Train Loss: 0.028309 | Val Loss: 0.346245

Epoch 2215/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00276]
Epoch 2215/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 2215 | Train Loss: 0.023938 | Val Loss: 0.321215

Epoch 2216/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0205]
Epoch 2216/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.01it/s]

End of Epoch 2216 | Train Loss: 0.024244 | Val Loss: 0.236039

Epoch 2217/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00364]
Epoch 2217/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.85it/s]

End of Epoch 2217 | Train Loss: 0.028495 | Val Loss: 0.463774

Epoch 2218/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00664]
Epoch 2218/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.52it/s]

End of Epoch 2218 | Train Loss: 0.019127 | Val Loss: 0.422160

Epoch 2219/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00558]
Epoch 2219/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 2219 | Train Loss: 0.029191 | Val Loss: 0.225900

Epoch 2220/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00344]
Epoch 2220/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.47it/s]

End of Epoch 2220 | Train Loss: 0.025411 | Val Loss: 0.762803

Epoch 2221/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.413]
Epoch 2221/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.59it/s]

End of Epoch 2221 | Train Loss: 0.029730 | Val Loss: 0.341275

Epoch 2222/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00406]
Epoch 2222/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 2222 | Train Loss: 0.032789 | Val Loss: 0.516086

Epoch 2223/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00358]
Epoch 2223/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.58it/s]

End of Epoch 2223 | Train Loss: 0.022998 | Val Loss: 0.342847

Epoch 2224/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00395]
Epoch 2224/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.52it/s]

End of Epoch 2224 | Train Loss: 0.028090 | Val Loss: 0.866001

Epoch 2225/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00531]
Epoch 2225/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.78it/s]

End of Epoch 2225 | Train Loss: 0.020655 | Val Loss: 0.497192

Epoch 2226/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.339]
Epoch 2226/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.38it/s]

End of Epoch 2226 | Train Loss: 0.038327 | Val Loss: 0.633869

Epoch 2227/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00538]
Epoch 2227/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.99it/s]

End of Epoch 2227 | Train Loss: 0.026324 | Val Loss: 0.160251

Epoch 2228/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00606]
Epoch 2228/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.61it/s]

End of Epoch 2228 | Train Loss: 0.025541 | Val Loss: 0.519259

Epoch 2229/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00422]
Epoch 2229/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 2229 | Train Loss: 0.028643 | Val Loss: 0.555693

Epoch 2230/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0224]
Epoch 2230/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.52it/s]

End of Epoch 2230 | Train Loss: 0.027673 | Val Loss: 0.416778

Epoch 2231/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00484]
Epoch 2231/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.32it/s]

End of Epoch 2231 | Train Loss: 0.024088 | Val Loss: 0.545015

Epoch 2232/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.55it/s, loss=0.0089]
Epoch 2232/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.71it/s]

End of Epoch 2232 | Train Loss: 0.029124 | Val Loss: 0.864578

Epoch 2233/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00853]
Epoch 2233/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.76it/s]

End of Epoch 2233 | Train Loss: 0.026741 | Val Loss: 0.453114

Epoch 2234/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0048]
Epoch 2234/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.89it/s]

End of Epoch 2234 | Train Loss: 0.024813 | Val Loss: 0.239876

Epoch 2235/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.38]
Epoch 2235/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.38it/s]

End of Epoch 2235 | Train Loss: 0.028386 | Val Loss: 0.487769

Epoch 2236/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00734]
Epoch 2236/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 2236 | Train Loss: 0.027505 | Val Loss: 0.436280

Epoch 2237/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.00428]
Epoch 2237/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.07it/s]

End of Epoch 2237 | Train Loss: 0.023476 | Val Loss: 0.410651

Epoch 2238/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00333]
Epoch 2238/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 2238 | Train Loss: 0.015807 | Val Loss: 0.806674

Epoch 2239/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00358]
Epoch 2239/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.31it/s]

End of Epoch 2239 | Train Loss: 0.024615 | Val Loss: 0.365663

Epoch 2240/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00545]
Epoch 2240/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.44it/s]

End of Epoch 2240 | Train Loss: 0.021052 | Val Loss: 0.379776

Epoch 2241/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00489]
Epoch 2241/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.99it/s]

End of Epoch 2241 | Train Loss: 0.022142 | Val Loss: 0.385960

Epoch 2242/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0144]
Epoch 2242/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 2242 | Train Loss: 0.023455 | Val Loss: 0.461660

Epoch 2243/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00377]
Epoch 2243/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 2243 | Train Loss: 0.026473 | Val Loss: 0.288047

Epoch 2244/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00441]
Epoch 2244/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 2244 | Train Loss: 0.024932 | Val Loss: 0.845316

Epoch 2245/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0112]
Epoch 2245/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 2245 | Train Loss: 0.024876 | Val Loss: 0.506472

Epoch 2246/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00401]
Epoch 2246/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 2246 | Train Loss: 0.023512 | Val Loss: 0.847681

Epoch 2247/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00624]
Epoch 2247/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.37it/s]

End of Epoch 2247 | Train Loss: 0.022417 | Val Loss: 0.320739

Epoch 2248/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00364]
Epoch 2248/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.97it/s]

End of Epoch 2248 | Train Loss: 0.018979 | Val Loss: 0.289222

Epoch 2249/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00391]
Epoch 2249/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.49it/s]

End of Epoch 2249 | Train Loss: 0.023896 | Val Loss: 0.251870

Epoch 2250/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0248]
Epoch 2250/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 2250 | Train Loss: 0.026589 | Val Loss: 0.540134

Epoch 2251/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00619]
Epoch 2251/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 2251 | Train Loss: 0.026508 | Val Loss: 0.357386

Epoch 2252/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.41it/s, loss=0.00329]
Epoch 2252/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.03it/s]

End of Epoch 2252 | Train Loss: 0.026012 | Val Loss: 0.461406

Epoch 2253/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0032]
Epoch 2253/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.02it/s]

End of Epoch 2253 | Train Loss: 0.028227 | Val Loss: 0.876941

Epoch 2254/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00597]
Epoch 2254/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.90it/s]

End of Epoch 2254 | Train Loss: 0.029044 | Val Loss: 0.395756

Epoch 2255/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00577]
Epoch 2255/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 2255 | Train Loss: 0.026960 | Val Loss: 0.396019

Epoch 2256/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.195]
Epoch 2256/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.58it/s]

End of Epoch 2256 | Train Loss: 0.031822 | Val Loss: 0.348715

Epoch 2257/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0087]
Epoch 2257/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.72it/s]

End of Epoch 2257 | Train Loss: 0.027879 | Val Loss: 0.452332

Epoch 2258/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00484]
Epoch 2258/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.00it/s]

End of Epoch 2258 | Train Loss: 0.028956 | Val Loss: 0.469003

Epoch 2259/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00313]
Epoch 2259/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.23it/s]

End of Epoch 2259 | Train Loss: 0.024788 | Val Loss: 0.171256

Epoch 2260/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.003]
Epoch 2260/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 2260 | Train Loss: 0.023914 | Val Loss: 0.652845

Epoch 2261/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00341]
Epoch 2261/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.21it/s]

End of Epoch 2261 | Train Loss: 0.021127 | Val Loss: 0.692984

Epoch 2262/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0136]
Epoch 2262/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 2262 | Train Loss: 0.022386 | Val Loss: 0.298601

Epoch 2263/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00375]
Epoch 2263/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.67it/s]

End of Epoch 2263 | Train Loss: 0.022216 | Val Loss: 0.869203

Epoch 2264/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.00725]
Epoch 2264/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.43it/s]

End of Epoch 2264 | Train Loss: 0.022416 | Val Loss: 0.157689

Epoch 2265/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0398]
Epoch 2265/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 2265 | Train Loss: 0.024732 | Val Loss: 0.250368

Epoch 2266/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.036]
Epoch 2266/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.64it/s]

End of Epoch 2266 | Train Loss: 0.021717 | Val Loss: 0.425147

Epoch 2267/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00861]
Epoch 2267/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 2267 | Train Loss: 0.028954 | Val Loss: 0.438559

Epoch 2268/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0206]
Epoch 2268/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.22it/s]

End of Epoch 2268 | Train Loss: 0.025359 | Val Loss: 0.442947

Epoch 2269/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00337]
Epoch 2269/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 2269 | Train Loss: 0.028885 | Val Loss: 0.462969

Epoch 2270/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00692]
Epoch 2270/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 2270 | Train Loss: 0.024123 | Val Loss: 0.278215

Epoch 2271/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.003]
Epoch 2271/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 2271 | Train Loss: 0.027015 | Val Loss: 0.528125

Epoch 2272/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00379]
Epoch 2272/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.97it/s]

End of Epoch 2272 | Train Loss: 0.030859 | Val Loss: 0.493424

Epoch 2273/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00238]
Epoch 2273/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 2273 | Train Loss: 0.021600 | Val Loss: 0.437619

Epoch 2274/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0364]
Epoch 2274/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.43it/s]

End of Epoch 2274 | Train Loss: 0.021675 | Val Loss: 0.646982

Epoch 2275/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00343]
Epoch 2275/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 2275 | Train Loss: 0.030497 | Val Loss: 0.348226

Epoch 2276/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00974]
Epoch 2276/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.40it/s]

End of Epoch 2276 | Train Loss: 0.021333 | Val Loss: 0.247836

Epoch 2277/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00385]
Epoch 2277/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.43it/s]

End of Epoch 2277 | Train Loss: 0.021811 | Val Loss: 0.464943

Epoch 2278/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00401]
Epoch 2278/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.77it/s]

End of Epoch 2278 | Train Loss: 0.028629 | Val Loss: 0.353865

Epoch 2279/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00291]
Epoch 2279/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.77it/s]

End of Epoch 2279 | Train Loss: 0.024494 | Val Loss: 0.456584

Epoch 2280/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0966]
Epoch 2280/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.00it/s]

End of Epoch 2280 | Train Loss: 0.028643 | Val Loss: 0.261180

Epoch 2281/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00379]
Epoch 2281/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 2281 | Train Loss: 0.024921 | Val Loss: 0.464874

Epoch 2282/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00352]
Epoch 2282/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 2282 | Train Loss: 0.024014 | Val Loss: 0.449274

Epoch 2283/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00927]
Epoch 2283/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 2283 | Train Loss: 0.021540 | Val Loss: 0.304403

Epoch 2284/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00307]
Epoch 2284/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 2284 | Train Loss: 0.024974 | Val Loss: 0.645066

Epoch 2285/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0217]
Epoch 2285/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 2285 | Train Loss: 0.017022 | Val Loss: 0.422936

Epoch 2286/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00425]
Epoch 2286/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 2286 | Train Loss: 0.021952 | Val Loss: 0.415547

Epoch 2287/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00396]
Epoch 2287/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.52it/s]

End of Epoch 2287 | Train Loss: 0.017875 | Val Loss: 0.620201

Epoch 2288/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00736]
Epoch 2288/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.47it/s]

End of Epoch 2288 | Train Loss: 0.023188 | Val Loss: 0.647810

Epoch 2289/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00451]
Epoch 2289/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.31it/s]

End of Epoch 2289 | Train Loss: 0.026445 | Val Loss: 0.605203

Epoch 2290/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00816]
Epoch 2290/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 2290 | Train Loss: 0.026903 | Val Loss: 0.361769

Epoch 2291/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00439]
Epoch 2291/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.23it/s]

End of Epoch 2291 | Train Loss: 0.023634 | Val Loss: 0.452639

Epoch 2292/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.43it/s, loss=0.00358]
Epoch 2292/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 2292 | Train Loss: 0.028658 | Val Loss: 0.427391

Epoch 2293/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00474]
Epoch 2293/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 2293 | Train Loss: 0.024552 | Val Loss: 0.395913

Epoch 2294/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00334]
Epoch 2294/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2294 | Train Loss: 0.027777 | Val Loss: 0.407652

Epoch 2295/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0036]
Epoch 2295/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.99it/s]

End of Epoch 2295 | Train Loss: 0.016673 | Val Loss: 0.669883

Epoch 2296/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00341]
Epoch 2296/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.59it/s]

End of Epoch 2296 | Train Loss: 0.025551 | Val Loss: 0.379946

Epoch 2297/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0599]
Epoch 2297/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.30it/s]

End of Epoch 2297 | Train Loss: 0.032480 | Val Loss: 0.418227

Epoch 2298/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00531]
Epoch 2298/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.76it/s]

End of Epoch 2298 | Train Loss: 0.026274 | Val Loss: 0.493115

Epoch 2299/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00399]
Epoch 2299/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.16it/s]

End of Epoch 2299 | Train Loss: 0.025306 | Val Loss: 0.760119

Epoch 2300/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00385]
Epoch 2300/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.30it/s]

End of Epoch 2300 | Train Loss: 0.028426 | Val Loss: 0.576434

Epoch 2301/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00445]
Epoch 2301/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 2301 | Train Loss: 0.025039 | Val Loss: 0.344662

Epoch 2302/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00525]
Epoch 2302/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.55it/s]

End of Epoch 2302 | Train Loss: 0.020891 | Val Loss: 0.540788

Epoch 2303/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00438]
Epoch 2303/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.85it/s]

End of Epoch 2303 | Train Loss: 0.024135 | Val Loss: 0.896596

Epoch 2304/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.007]
Epoch 2304/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.16it/s]

End of Epoch 2304 | Train Loss: 0.021148 | Val Loss: 0.313174

Epoch 2305/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00334]
Epoch 2305/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.05it/s]

End of Epoch 2305 | Train Loss: 0.034172 | Val Loss: 0.446868

Epoch 2306/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00357]
Epoch 2306/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 2306 | Train Loss: 0.022221 | Val Loss: 0.414221

Epoch 2307/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00324]
Epoch 2307/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 2307 | Train Loss: 0.019819 | Val Loss: 0.606131

Epoch 2308/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00301]
Epoch 2308/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.05it/s]

End of Epoch 2308 | Train Loss: 0.025202 | Val Loss: 0.638536

Epoch 2309/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0094]
Epoch 2309/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 2309 | Train Loss: 0.024502 | Val Loss: 0.620713

Epoch 2310/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00391]
Epoch 2310/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 2310 | Train Loss: 0.023785 | Val Loss: 0.424828

Epoch 2311/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0331]
Epoch 2311/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 2311 | Train Loss: 0.022612 | Val Loss: 0.334308

Epoch 2312/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00912]
Epoch 2312/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 2312 | Train Loss: 0.021397 | Val Loss: 0.572075

Epoch 2313/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00778]
Epoch 2313/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 2313 | Train Loss: 0.019616 | Val Loss: 0.699702

Epoch 2314/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00425]
Epoch 2314/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.56it/s]

End of Epoch 2314 | Train Loss: 0.025876 | Val Loss: 0.367727

Epoch 2315/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0045]
Epoch 2315/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 2315 | Train Loss: 0.023633 | Val Loss: 0.285250

Epoch 2316/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00621]
Epoch 2316/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.82it/s]

End of Epoch 2316 | Train Loss: 0.020883 | Val Loss: 0.644100

Epoch 2317/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00345]
Epoch 2317/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.14it/s]

End of Epoch 2317 | Train Loss: 0.020306 | Val Loss: 0.569095

Epoch 2318/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0096]
Epoch 2318/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 2318 | Train Loss: 0.019703 | Val Loss: 0.451888

Epoch 2319/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00811]
Epoch 2319/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.84it/s]

End of Epoch 2319 | Train Loss: 0.020943 | Val Loss: 0.591362

Epoch 2320/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00349]
Epoch 2320/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.69it/s]

End of Epoch 2320 | Train Loss: 0.023373 | Val Loss: 0.420421

Epoch 2321/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0111]
Epoch 2321/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.12it/s]

End of Epoch 2321 | Train Loss: 0.019957 | Val Loss: 0.486524

Epoch 2322/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00661]
Epoch 2322/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.90it/s]

End of Epoch 2322 | Train Loss: 0.031599 | Val Loss: 0.458551

Epoch 2323/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0049]
Epoch 2323/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.91it/s]

End of Epoch 2323 | Train Loss: 0.018176 | Val Loss: 0.319084

Epoch 2324/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00397]
Epoch 2324/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 2324 | Train Loss: 0.026050 | Val Loss: 0.450838

Epoch 2325/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.632]
Epoch 2325/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.96it/s]

End of Epoch 2325 | Train Loss: 0.033692 | Val Loss: 0.244141

Epoch 2326/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00465]
Epoch 2326/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 2326 | Train Loss: 0.034685 | Val Loss: 0.400424

Epoch 2327/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00482]
Epoch 2327/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 2327 | Train Loss: 0.028827 | Val Loss: 0.539763

Epoch 2328/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00392]
Epoch 2328/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.84it/s]

End of Epoch 2328 | Train Loss: 0.025006 | Val Loss: 0.404687

Epoch 2329/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00804]
Epoch 2329/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.87it/s]

End of Epoch 2329 | Train Loss: 0.030101 | Val Loss: 0.693373

Epoch 2330/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.232]
Epoch 2330/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.57it/s]

End of Epoch 2330 | Train Loss: 0.021933 | Val Loss: 0.696766

Epoch 2331/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00414]
Epoch 2331/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.69it/s]

End of Epoch 2331 | Train Loss: 0.035751 | Val Loss: 0.500061

Epoch 2332/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0105]
Epoch 2332/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 2332 | Train Loss: 0.031500 | Val Loss: 0.737588

Epoch 2333/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00294]
Epoch 2333/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 2333 | Train Loss: 0.017708 | Val Loss: 0.530088

Epoch 2334/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0636]
Epoch 2334/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.03it/s]

End of Epoch 2334 | Train Loss: 0.026720 | Val Loss: 0.328755

Epoch 2335/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00363]
Epoch 2335/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 2335 | Train Loss: 0.025980 | Val Loss: 0.746168

Epoch 2336/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00362]
Epoch 2336/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.08it/s]

End of Epoch 2336 | Train Loss: 0.019391 | Val Loss: 0.213609

Epoch 2337/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0182]
Epoch 2337/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.16it/s]

End of Epoch 2337 | Train Loss: 0.018732 | Val Loss: 0.154781

Epoch 2338/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00302]
Epoch 2338/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.15it/s]

End of Epoch 2338 | Train Loss: 0.022852 | Val Loss: 0.296469

Epoch 2339/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00529]
Epoch 2339/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 2339 | Train Loss: 0.026806 | Val Loss: 0.711419

Epoch 2340/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00685]
Epoch 2340/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.59it/s]

End of Epoch 2340 | Train Loss: 0.023713 | Val Loss: 0.414658

Epoch 2341/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0484]
Epoch 2341/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.06it/s]

End of Epoch 2341 | Train Loss: 0.029735 | Val Loss: 0.435753

Epoch 2342/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00815]
Epoch 2342/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.09it/s]

End of Epoch 2342 | Train Loss: 0.026367 | Val Loss: 0.807807

Epoch 2343/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00406]
Epoch 2343/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.97it/s]

End of Epoch 2343 | Train Loss: 0.028017 | Val Loss: 0.545993

Epoch 2344/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00379]
Epoch 2344/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.44it/s]

End of Epoch 2344 | Train Loss: 0.022970 | Val Loss: 0.385985

Epoch 2345/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00634]
Epoch 2345/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.59it/s]

End of Epoch 2345 | Train Loss: 0.025581 | Val Loss: 0.390832

Epoch 2346/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00393]
Epoch 2346/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 2346 | Train Loss: 0.021220 | Val Loss: 0.198241

Epoch 2347/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00525]
Epoch 2347/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 2347 | Train Loss: 0.027554 | Val Loss: 0.399636

Epoch 2348/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00845]
Epoch 2348/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.64it/s]

End of Epoch 2348 | Train Loss: 0.022171 | Val Loss: 0.342654

Epoch 2349/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00284]
Epoch 2349/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.42it/s]

End of Epoch 2349 | Train Loss: 0.018874 | Val Loss: 0.546753

Epoch 2350/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.0609]
Epoch 2350/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 2350 | Train Loss: 0.024386 | Val Loss: 0.742685

Epoch 2351/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.34it/s, loss=0.0306]
Epoch 2351/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.45it/s]

End of Epoch 2351 | Train Loss: 0.026881 | Val Loss: 0.521942

Epoch 2352/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.124]
Epoch 2352/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.66it/s]

End of Epoch 2352 | Train Loss: 0.023263 | Val Loss: 0.517623

Epoch 2353/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00572]
Epoch 2353/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.56it/s]

End of Epoch 2353 | Train Loss: 0.022132 | Val Loss: 0.314277

Epoch 2354/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00403]
Epoch 2354/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 2354 | Train Loss: 0.019700 | Val Loss: 0.357116

Epoch 2355/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0704]
Epoch 2355/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.80it/s]

End of Epoch 2355 | Train Loss: 0.016297 | Val Loss: 0.345663

Epoch 2356/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00307]
Epoch 2356/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 2356 | Train Loss: 0.022364 | Val Loss: 0.273045

Epoch 2357/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00478]
Epoch 2357/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.44it/s]

End of Epoch 2357 | Train Loss: 0.024380 | Val Loss: 0.951179

Epoch 2358/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0467]
Epoch 2358/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.29it/s]

End of Epoch 2358 | Train Loss: 0.026092 | Val Loss: 0.703699

Epoch 2359/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00444]
Epoch 2359/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.72it/s]

End of Epoch 2359 | Train Loss: 0.020478 | Val Loss: 0.606677

Epoch 2360/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00417]
Epoch 2360/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.75it/s]

End of Epoch 2360 | Train Loss: 0.019879 | Val Loss: 0.429047

Epoch 2361/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00333]
Epoch 2361/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.04it/s]

End of Epoch 2361 | Train Loss: 0.026709 | Val Loss: 0.426523

Epoch 2362/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00383]
Epoch 2362/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.61it/s]

End of Epoch 2362 | Train Loss: 0.025012 | Val Loss: 0.324268

Epoch 2363/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.027]
Epoch 2363/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.53it/s]

End of Epoch 2363 | Train Loss: 0.023684 | Val Loss: 0.516420

Epoch 2364/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00955]
Epoch 2364/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.59it/s]

End of Epoch 2364 | Train Loss: 0.025617 | Val Loss: 0.462086

Epoch 2365/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0216]
Epoch 2365/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.36it/s]

End of Epoch 2365 | Train Loss: 0.018923 | Val Loss: 0.426847

Epoch 2366/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.018]
Epoch 2366/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.38it/s]

End of Epoch 2366 | Train Loss: 0.024527 | Val Loss: 0.255784

Epoch 2367/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00356]
Epoch 2367/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 2367 | Train Loss: 0.020856 | Val Loss: 0.462052

Epoch 2368/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.105]
Epoch 2368/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.45it/s]

End of Epoch 2368 | Train Loss: 0.020349 | Val Loss: 0.457232

Epoch 2369/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.376]
Epoch 2369/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 2369 | Train Loss: 0.035723 | Val Loss: 0.362620

Epoch 2370/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00429]
Epoch 2370/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.07it/s]

End of Epoch 2370 | Train Loss: 0.026903 | Val Loss: 0.440701

Epoch 2371/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00504]
Epoch 2371/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 2371 | Train Loss: 0.024862 | Val Loss: 0.717401

Epoch 2372/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00353]
Epoch 2372/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2372 | Train Loss: 0.023157 | Val Loss: 0.236236

Epoch 2373/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0629]
Epoch 2373/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 2373 | Train Loss: 0.032639 | Val Loss: 0.430303

Epoch 2374/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0119]
Epoch 2374/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 2374 | Train Loss: 0.020203 | Val Loss: 0.370293

Epoch 2375/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0125]
Epoch 2375/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.60it/s]

End of Epoch 2375 | Train Loss: 0.024123 | Val Loss: 0.467998

Epoch 2376/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.228]
Epoch 2376/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.71it/s]

End of Epoch 2376 | Train Loss: 0.022620 | Val Loss: 0.321897

Epoch 2377/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00279]
Epoch 2377/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 2377 | Train Loss: 0.030308 | Val Loss: 0.356505

Epoch 2378/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00613]
Epoch 2378/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.11it/s]

End of Epoch 2378 | Train Loss: 0.023693 | Val Loss: 0.825710

Epoch 2379/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.148]
Epoch 2379/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.49it/s]

End of Epoch 2379 | Train Loss: 0.022176 | Val Loss: 0.429520

Epoch 2380/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.0105]
Epoch 2380/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.79it/s]

End of Epoch 2380 | Train Loss: 0.022714 | Val Loss: 0.444045

Epoch 2381/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00678]
Epoch 2381/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.28it/s]

End of Epoch 2381 | Train Loss: 0.033836 | Val Loss: 0.495538

Epoch 2382/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.436]
Epoch 2382/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.46it/s]

End of Epoch 2382 | Train Loss: 0.028214 | Val Loss: 0.207070

Epoch 2383/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00463]
Epoch 2383/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 2383 | Train Loss: 0.028621 | Val Loss: 0.464465

Epoch 2384/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.003]
Epoch 2384/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 80.18it/s]

End of Epoch 2384 | Train Loss: 0.019301 | Val Loss: 0.581743

Epoch 2385/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00363]
Epoch 2385/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.94it/s]

End of Epoch 2385 | Train Loss: 0.019107 | Val Loss: 0.485412

Epoch 2386/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0345]
Epoch 2386/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.82it/s]

End of Epoch 2386 | Train Loss: 0.026112 | Val Loss: 0.310993

Epoch 2387/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00451]
Epoch 2387/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.13it/s]

End of Epoch 2387 | Train Loss: 0.025931 | Val Loss: 0.439060

Epoch 2388/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00439]
Epoch 2388/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.56it/s]

End of Epoch 2388 | Train Loss: 0.022948 | Val Loss: 0.383897

Epoch 2389/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0113]
Epoch 2389/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 2389 | Train Loss: 0.023304 | Val Loss: 0.583987

Epoch 2390/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00317]
Epoch 2390/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 2390 | Train Loss: 0.018856 | Val Loss: 0.465386

Epoch 2391/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00397]
Epoch 2391/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.91it/s]

End of Epoch 2391 | Train Loss: 0.025153 | Val Loss: 0.263511

Epoch 2392/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00307]
Epoch 2392/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.71it/s]

End of Epoch 2392 | Train Loss: 0.025844 | Val Loss: 0.344388

Epoch 2393/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0032]
Epoch 2393/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.38it/s]

End of Epoch 2393 | Train Loss: 0.020783 | Val Loss: 0.477912

Epoch 2394/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00361]
Epoch 2394/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.85it/s]

End of Epoch 2394 | Train Loss: 0.023792 | Val Loss: 0.727167

Epoch 2395/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0764]
Epoch 2395/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 2395 | Train Loss: 0.022507 | Val Loss: 0.350671

Epoch 2396/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00525]
Epoch 2396/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 2396 | Train Loss: 0.025786 | Val Loss: 0.870304

Epoch 2397/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0129]
Epoch 2397/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 2397 | Train Loss: 0.022865 | Val Loss: 0.428381

Epoch 2398/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00361]
Epoch 2398/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.84it/s]

End of Epoch 2398 | Train Loss: 0.017166 | Val Loss: 0.397622

Epoch 2399/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0663]
Epoch 2399/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 2399 | Train Loss: 0.024211 | Val Loss: 0.323965

Epoch 2400/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0234]
Epoch 2400/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 2400 | Train Loss: 0.017178 | Val Loss: 0.358373

Epoch 2401/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0377]
Epoch 2401/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.57it/s]

End of Epoch 2401 | Train Loss: 0.018365 | Val Loss: 0.346171

Epoch 2402/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0103]
Epoch 2402/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 2402 | Train Loss: 0.033833 | Val Loss: 0.439089

Epoch 2403/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00281]
Epoch 2403/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.99it/s]

End of Epoch 2403 | Train Loss: 0.024675 | Val Loss: 0.447119

Epoch 2404/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0036]
Epoch 2404/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 2404 | Train Loss: 0.021099 | Val Loss: 0.399789

Epoch 2405/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00273]
Epoch 2405/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.99it/s]

End of Epoch 2405 | Train Loss: 0.023941 | Val Loss: 0.319827

Epoch 2406/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0239]
Epoch 2406/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.68it/s]

End of Epoch 2406 | Train Loss: 0.016771 | Val Loss: 0.633018

Epoch 2407/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0118]
Epoch 2407/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 2407 | Train Loss: 0.028542 | Val Loss: 0.688549

Epoch 2408/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00622]
Epoch 2408/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.31it/s]

End of Epoch 2408 | Train Loss: 0.021080 | Val Loss: 0.501664

Epoch 2409/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0433]
Epoch 2409/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.91it/s]

End of Epoch 2409 | Train Loss: 0.024954 | Val Loss: 0.246414

Epoch 2410/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.00537]
Epoch 2410/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 2410 | Train Loss: 0.023166 | Val Loss: 0.292465

Epoch 2411/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00429]
Epoch 2411/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.31it/s]

End of Epoch 2411 | Train Loss: 0.026838 | Val Loss: 0.413514

Epoch 2412/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00462]
Epoch 2412/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.00it/s]

End of Epoch 2412 | Train Loss: 0.025098 | Val Loss: 0.425179

Epoch 2413/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00305]
Epoch 2413/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.11it/s]

End of Epoch 2413 | Train Loss: 0.023073 | Val Loss: 0.545061

Epoch 2414/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00274]
Epoch 2414/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.97it/s]

End of Epoch 2414 | Train Loss: 0.026120 | Val Loss: 0.521917

Epoch 2415/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.22]
Epoch 2415/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.78it/s]

End of Epoch 2415 | Train Loss: 0.022879 | Val Loss: 0.492474

Epoch 2416/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00562]
Epoch 2416/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.10it/s]

End of Epoch 2416 | Train Loss: 0.028048 | Val Loss: 0.644480

Epoch 2417/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00469]
Epoch 2417/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 2417 | Train Loss: 0.028422 | Val Loss: 0.526547

Epoch 2418/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0263]
Epoch 2418/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.68it/s]

End of Epoch 2418 | Train Loss: 0.021316 | Val Loss: 0.421923

Epoch 2419/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.145]
Epoch 2419/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.92it/s]

End of Epoch 2419 | Train Loss: 0.025033 | Val Loss: 0.326191

Epoch 2420/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00367]
Epoch 2420/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 2420 | Train Loss: 0.025332 | Val Loss: 1.090968

Epoch 2421/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0142]
Epoch 2421/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 2421 | Train Loss: 0.023349 | Val Loss: 0.398118

Epoch 2422/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0117]
Epoch 2422/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.66it/s]

End of Epoch 2422 | Train Loss: 0.029208 | Val Loss: 0.578222

Epoch 2423/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00411]
Epoch 2423/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 2423 | Train Loss: 0.025393 | Val Loss: 0.608464

Epoch 2424/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00466]
Epoch 2424/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 2424 | Train Loss: 0.026077 | Val Loss: 0.439271

Epoch 2425/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.046]
Epoch 2425/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.37it/s]

End of Epoch 2425 | Train Loss: 0.022308 | Val Loss: 0.687874

Epoch 2426/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00406]
Epoch 2426/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.27it/s]

End of Epoch 2426 | Train Loss: 0.025042 | Val Loss: 0.475853

Epoch 2427/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00281]
Epoch 2427/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.83it/s]

End of Epoch 2427 | Train Loss: 0.022153 | Val Loss: 0.532027

Epoch 2428/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.175]
Epoch 2428/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.54it/s]

End of Epoch 2428 | Train Loss: 0.024512 | Val Loss: 0.490242

Epoch 2429/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00372]
Epoch 2429/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 2429 | Train Loss: 0.025754 | Val Loss: 0.614654

Epoch 2430/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0171]
Epoch 2430/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.29it/s]

End of Epoch 2430 | Train Loss: 0.033844 | Val Loss: 0.398031

Epoch 2431/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00355]
Epoch 2431/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 2431 | Train Loss: 0.027438 | Val Loss: 0.382596

Epoch 2432/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.53it/s, loss=0.0082]
Epoch 2432/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.96it/s]

End of Epoch 2432 | Train Loss: 0.021533 | Val Loss: 0.702356

Epoch 2433/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0165]
Epoch 2433/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 2433 | Train Loss: 0.016506 | Val Loss: 0.483005

Epoch 2434/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.004]
Epoch 2434/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 2434 | Train Loss: 0.027482 | Val Loss: 0.613178

Epoch 2435/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00309]
Epoch 2435/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 2435 | Train Loss: 0.026923 | Val Loss: 0.652750

Epoch 2436/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0081]
Epoch 2436/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.85it/s]

End of Epoch 2436 | Train Loss: 0.022199 | Val Loss: 0.478164

Epoch 2437/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.67it/s, loss=0.00364]
Epoch 2437/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.93it/s]

End of Epoch 2437 | Train Loss: 0.030561 | Val Loss: 0.120610

Epoch 2438/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00325]
Epoch 2438/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.39it/s]

End of Epoch 2438 | Train Loss: 0.020822 | Val Loss: 0.365764

Epoch 2439/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00341]
Epoch 2439/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 2439 | Train Loss: 0.026532 | Val Loss: 0.350125

Epoch 2440/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.00457]
Epoch 2440/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 2440 | Train Loss: 0.023396 | Val Loss: 0.517006

Epoch 2441/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00388]
Epoch 2441/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 2441 | Train Loss: 0.019376 | Val Loss: 0.756026

Epoch 2442/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00441]
Epoch 2442/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.45it/s]

End of Epoch 2442 | Train Loss: 0.022131 | Val Loss: 0.278333

Epoch 2443/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00362]
Epoch 2443/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 2443 | Train Loss: 0.022390 | Val Loss: 0.356000

Epoch 2444/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0229]
Epoch 2444/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 2444 | Train Loss: 0.021720 | Val Loss: 0.640280

Epoch 2445/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00836]
Epoch 2445/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.67it/s]

End of Epoch 2445 | Train Loss: 0.018041 | Val Loss: 0.509856

Epoch 2446/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0123]
Epoch 2446/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.27it/s]

End of Epoch 2446 | Train Loss: 0.031382 | Val Loss: 0.386161

Epoch 2447/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0125]
Epoch 2447/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.11it/s]

End of Epoch 2447 | Train Loss: 0.020381 | Val Loss: 0.430203

Epoch 2448/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00507]
Epoch 2448/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.13it/s]

End of Epoch 2448 | Train Loss: 0.019294 | Val Loss: 0.676383

Epoch 2449/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00972]
Epoch 2449/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.91it/s]

End of Epoch 2449 | Train Loss: 0.018707 | Val Loss: 0.755621

Epoch 2450/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00362]
Epoch 2450/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.88it/s]

End of Epoch 2450 | Train Loss: 0.022845 | Val Loss: 0.605888

Epoch 2451/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0584]
Epoch 2451/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.88it/s]

End of Epoch 2451 | Train Loss: 0.023980 | Val Loss: 0.332540

Epoch 2452/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00485]
Epoch 2452/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 2452 | Train Loss: 0.020448 | Val Loss: 0.620303

Epoch 2453/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00506]
Epoch 2453/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 2453 | Train Loss: 0.021321 | Val Loss: 0.376048

Epoch 2454/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0259]
Epoch 2454/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 2454 | Train Loss: 0.028959 | Val Loss: 0.493131

Epoch 2455/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0043]
Epoch 2455/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.93it/s]

End of Epoch 2455 | Train Loss: 0.021962 | Val Loss: 0.395904

Epoch 2456/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00348]
Epoch 2456/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 2456 | Train Loss: 0.026128 | Val Loss: 0.599810

Epoch 2457/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00312]
Epoch 2457/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.44it/s]

End of Epoch 2457 | Train Loss: 0.016732 | Val Loss: 0.462322

Epoch 2458/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00233]
Epoch 2458/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 2458 | Train Loss: 0.015578 | Val Loss: 0.731025

Epoch 2459/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.287]
Epoch 2459/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 2459 | Train Loss: 0.028270 | Val Loss: 0.277355

Epoch 2460/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00404]
Epoch 2460/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 2460 | Train Loss: 0.031442 | Val Loss: 0.357965

Epoch 2461/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00757]
Epoch 2461/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 2461 | Train Loss: 0.032901 | Val Loss: 0.559886

Epoch 2462/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00957]
Epoch 2462/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.92it/s]

End of Epoch 2462 | Train Loss: 0.024736 | Val Loss: 0.334445

Epoch 2463/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0047]
Epoch 2463/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.21it/s]

End of Epoch 2463 | Train Loss: 0.024882 | Val Loss: 0.634383

Epoch 2464/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00388]
Epoch 2464/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.32it/s]

End of Epoch 2464 | Train Loss: 0.025360 | Val Loss: 0.549092

Epoch 2465/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0196]
Epoch 2465/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 2465 | Train Loss: 0.027468 | Val Loss: 0.631123

Epoch 2466/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00419]
Epoch 2466/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.69it/s]

End of Epoch 2466 | Train Loss: 0.028216 | Val Loss: 0.474516

Epoch 2467/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00333]
Epoch 2467/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.90it/s]

End of Epoch 2467 | Train Loss: 0.024779 | Val Loss: 0.348800

Epoch 2468/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00295]
Epoch 2468/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.32it/s]

End of Epoch 2468 | Train Loss: 0.020093 | Val Loss: 0.585203

Epoch 2469/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00545]
Epoch 2469/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 2469 | Train Loss: 0.027895 | Val Loss: 0.401585

Epoch 2470/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0288]
Epoch 2470/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.31it/s]

End of Epoch 2470 | Train Loss: 0.023602 | Val Loss: 0.807695

Epoch 2471/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0203]
Epoch 2471/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.18it/s]

End of Epoch 2471 | Train Loss: 0.021987 | Val Loss: 0.381294

Epoch 2472/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00403]
Epoch 2472/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.70it/s]

End of Epoch 2472 | Train Loss: 0.018156 | Val Loss: 0.555571

Epoch 2473/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00374]
Epoch 2473/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 2473 | Train Loss: 0.028371 | Val Loss: 0.338551

Epoch 2474/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00369]
Epoch 2474/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.56it/s]

End of Epoch 2474 | Train Loss: 0.020592 | Val Loss: 0.445103

Epoch 2475/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.005]
Epoch 2475/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.14it/s]

End of Epoch 2475 | Train Loss: 0.018619 | Val Loss: 0.381595

Epoch 2476/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00494]
Epoch 2476/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 2476 | Train Loss: 0.024262 | Val Loss: 0.437201

Epoch 2477/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00287]
Epoch 2477/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 2477 | Train Loss: 0.022399 | Val Loss: 0.344666

Epoch 2478/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0033]
Epoch 2478/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 2478 | Train Loss: 0.019675 | Val Loss: 0.525642

Epoch 2479/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00439]
Epoch 2479/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.07it/s]

End of Epoch 2479 | Train Loss: 0.022684 | Val Loss: 0.415509

Epoch 2480/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0139]
Epoch 2480/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.45it/s]

End of Epoch 2480 | Train Loss: 0.020618 | Val Loss: 0.378134

Epoch 2481/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00415]
Epoch 2481/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 2481 | Train Loss: 0.022745 | Val Loss: 0.502931

Epoch 2482/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.102]
Epoch 2482/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.12it/s]

End of Epoch 2482 | Train Loss: 0.030790 | Val Loss: 0.563373

Epoch 2483/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0118]
Epoch 2483/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 2483 | Train Loss: 0.023691 | Val Loss: 0.503749

Epoch 2484/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00291]
Epoch 2484/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 2484 | Train Loss: 0.025936 | Val Loss: 0.359046

Epoch 2485/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00348]
Epoch 2485/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.67it/s]

End of Epoch 2485 | Train Loss: 0.023945 | Val Loss: 0.196233

Epoch 2486/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0046]
Epoch 2486/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 2486 | Train Loss: 0.026360 | Val Loss: 0.244104

Epoch 2487/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0175]
Epoch 2487/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.07it/s]

End of Epoch 2487 | Train Loss: 0.021723 | Val Loss: 0.399118

Epoch 2488/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00396]
Epoch 2488/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 2488 | Train Loss: 0.023682 | Val Loss: 0.474733

Epoch 2489/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00439]
Epoch 2489/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 2489 | Train Loss: 0.020007 | Val Loss: 0.502583

Epoch 2490/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.37it/s, loss=0.375]
Epoch 2490/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.26it/s]

End of Epoch 2490 | Train Loss: 0.025081 | Val Loss: 0.457623

Epoch 2491/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00414]
Epoch 2491/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 2491 | Train Loss: 0.024638 | Val Loss: 0.639804

Epoch 2492/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00755]
Epoch 2492/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.19it/s]

End of Epoch 2492 | Train Loss: 0.022407 | Val Loss: 0.611393

Epoch 2493/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00871]
Epoch 2493/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 2493 | Train Loss: 0.027205 | Val Loss: 0.280172

Epoch 2494/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.128]
Epoch 2494/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.58it/s]

End of Epoch 2494 | Train Loss: 0.026836 | Val Loss: 0.386961

Epoch 2495/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0072]
Epoch 2495/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 2495 | Train Loss: 0.022925 | Val Loss: 0.323514

Epoch 2496/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00675]
Epoch 2496/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.08it/s]

End of Epoch 2496 | Train Loss: 0.022304 | Val Loss: 0.407222

Epoch 2497/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00446]
Epoch 2497/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 2497 | Train Loss: 0.022577 | Val Loss: 0.259159

Epoch 2498/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00269]
Epoch 2498/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.70it/s]

End of Epoch 2498 | Train Loss: 0.026167 | Val Loss: 0.407977

Epoch 2499/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00325]
Epoch 2499/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.49it/s]

End of Epoch 2499 | Train Loss: 0.020938 | Val Loss: 0.945438

Epoch 2500/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.00807]
Epoch 2500/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 2500 | Train Loss: 0.022001 | Val Loss: 0.746890

Epoch 2501/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.00472]
Epoch 2501/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.16it/s]

End of Epoch 2501 | Train Loss: 0.019846 | Val Loss: 0.440121

Epoch 2502/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00375]
Epoch 2502/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 2502 | Train Loss: 0.021872 | Val Loss: 0.681696

Epoch 2503/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00836]
Epoch 2503/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 2503 | Train Loss: 0.017578 | Val Loss: 0.473363

Epoch 2504/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0699]
Epoch 2504/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 2504 | Train Loss: 0.022128 | Val Loss: 0.600070

Epoch 2505/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00267]
Epoch 2505/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.35it/s]

End of Epoch 2505 | Train Loss: 0.021196 | Val Loss: 0.646396

Epoch 2506/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00398]
Epoch 2506/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.59it/s]

End of Epoch 2506 | Train Loss: 0.020461 | Val Loss: 0.379597

Epoch 2507/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00273]
Epoch 2507/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 2507 | Train Loss: 0.019733 | Val Loss: 0.180382

Epoch 2508/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00741]
Epoch 2508/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.58it/s]

End of Epoch 2508 | Train Loss: 0.025146 | Val Loss: 0.547426

Epoch 2509/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0159]
Epoch 2509/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.02it/s]

End of Epoch 2509 | Train Loss: 0.023118 | Val Loss: 0.565819

Epoch 2510/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.56it/s, loss=0.928]
Epoch 2510/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.33it/s]

End of Epoch 2510 | Train Loss: 0.035047 | Val Loss: 0.350096

Epoch 2511/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00345]
Epoch 2511/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 2511 | Train Loss: 0.022502 | Val Loss: 0.233954

Epoch 2512/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.17]
Epoch 2512/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 2512 | Train Loss: 0.027306 | Val Loss: 0.295180

Epoch 2513/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0136]
Epoch 2513/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.83it/s]

End of Epoch 2513 | Train Loss: 0.027397 | Val Loss: 0.484084

Epoch 2514/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00433]
Epoch 2514/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.78it/s]

End of Epoch 2514 | Train Loss: 0.029393 | Val Loss: 0.149095

Epoch 2515/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0199]
Epoch 2515/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 2515 | Train Loss: 0.031220 | Val Loss: 0.642048

Epoch 2516/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0036]
Epoch 2516/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 2516 | Train Loss: 0.015435 | Val Loss: 0.637622

Epoch 2517/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00667]
Epoch 2517/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.80it/s]

End of Epoch 2517 | Train Loss: 0.023868 | Val Loss: 0.495886

Epoch 2518/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00699]
Epoch 2518/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.66it/s]

End of Epoch 2518 | Train Loss: 0.019991 | Val Loss: 0.422503

Epoch 2519/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00315]
Epoch 2519/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.88it/s]

End of Epoch 2519 | Train Loss: 0.025312 | Val Loss: 0.652132

Epoch 2520/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00624]
Epoch 2520/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.54it/s]

End of Epoch 2520 | Train Loss: 0.019462 | Val Loss: 0.339526

Epoch 2521/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00686]
Epoch 2521/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 2521 | Train Loss: 0.019813 | Val Loss: 0.309395

Epoch 2522/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0175]
Epoch 2522/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.68it/s]

End of Epoch 2522 | Train Loss: 0.020832 | Val Loss: 0.593470

Epoch 2523/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0108]
Epoch 2523/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 2523 | Train Loss: 0.027838 | Val Loss: 0.533499

Epoch 2524/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00339]
Epoch 2524/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.31it/s]

End of Epoch 2524 | Train Loss: 0.021765 | Val Loss: 0.550372

Epoch 2525/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00821]
Epoch 2525/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.93it/s]

End of Epoch 2525 | Train Loss: 0.021256 | Val Loss: 0.292838

Epoch 2526/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00267]
Epoch 2526/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 2526 | Train Loss: 0.022951 | Val Loss: 0.575849

Epoch 2527/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00393]
Epoch 2527/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 2527 | Train Loss: 0.022530 | Val Loss: 0.411219

Epoch 2528/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.114]
Epoch 2528/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.05it/s]

End of Epoch 2528 | Train Loss: 0.020495 | Val Loss: 0.716951

Epoch 2529/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00691]
Epoch 2529/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.22it/s]

End of Epoch 2529 | Train Loss: 0.027150 | Val Loss: 0.633848

Epoch 2530/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.366]
Epoch 2530/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.44it/s]

End of Epoch 2530 | Train Loss: 0.026967 | Val Loss: 0.511515

Epoch 2531/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.011]
Epoch 2531/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 2531 | Train Loss: 0.033365 | Val Loss: 0.279070

Epoch 2532/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00812]
Epoch 2532/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.97it/s]

End of Epoch 2532 | Train Loss: 0.020024 | Val Loss: 0.406786

Epoch 2533/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00588]
Epoch 2533/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 2533 | Train Loss: 0.023460 | Val Loss: 0.691177

Epoch 2534/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00424]
Epoch 2534/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.95it/s]

End of Epoch 2534 | Train Loss: 0.022854 | Val Loss: 0.425938

Epoch 2535/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00532]
Epoch 2535/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.26it/s]

End of Epoch 2535 | Train Loss: 0.023357 | Val Loss: 0.573986

Epoch 2536/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0168]
Epoch 2536/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.93it/s]

End of Epoch 2536 | Train Loss: 0.025584 | Val Loss: 0.321942

Epoch 2537/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.0111]
Epoch 2537/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.66it/s]

End of Epoch 2537 | Train Loss: 0.028886 | Val Loss: 0.300613

Epoch 2538/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.014]
Epoch 2538/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.19it/s]

End of Epoch 2538 | Train Loss: 0.022083 | Val Loss: 0.665677

Epoch 2539/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0425]
Epoch 2539/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 2539 | Train Loss: 0.020677 | Val Loss: 0.362438

Epoch 2540/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00361]
Epoch 2540/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 2540 | Train Loss: 0.021465 | Val Loss: 0.522661

Epoch 2541/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00308]
Epoch 2541/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.05it/s]

End of Epoch 2541 | Train Loss: 0.020857 | Val Loss: 0.499505

Epoch 2542/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0038]
Epoch 2542/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.00it/s]

End of Epoch 2542 | Train Loss: 0.019450 | Val Loss: 0.258212

Epoch 2543/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00317]
Epoch 2543/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.88it/s]

End of Epoch 2543 | Train Loss: 0.018276 | Val Loss: 0.671853

Epoch 2544/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00274]
Epoch 2544/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 2544 | Train Loss: 0.015149 | Val Loss: 0.664494

Epoch 2545/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.341]
Epoch 2545/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.28it/s]

End of Epoch 2545 | Train Loss: 0.021643 | Val Loss: 0.615409

Epoch 2546/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0049]
Epoch 2546/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2546 | Train Loss: 0.028510 | Val Loss: 0.612512

Epoch 2547/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00344]
Epoch 2547/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.50it/s]

End of Epoch 2547 | Train Loss: 0.021145 | Val Loss: 0.614220

Epoch 2548/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00705]
Epoch 2548/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.21it/s]

End of Epoch 2548 | Train Loss: 0.022188 | Val Loss: 0.245239

Epoch 2549/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.41it/s, loss=0.0119]
Epoch 2549/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.71it/s]

End of Epoch 2549 | Train Loss: 0.025050 | Val Loss: 0.312625

Epoch 2550/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00375]
Epoch 2550/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.35it/s]

End of Epoch 2550 | Train Loss: 0.022157 | Val Loss: 0.364293

Epoch 2551/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00523]
Epoch 2551/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 2551 | Train Loss: 0.025576 | Val Loss: 0.720181

Epoch 2552/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0363]
Epoch 2552/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.55it/s]

End of Epoch 2552 | Train Loss: 0.028882 | Val Loss: 0.418222

Epoch 2553/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00569]
Epoch 2553/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.61it/s]

End of Epoch 2553 | Train Loss: 0.025582 | Val Loss: 0.378124

Epoch 2554/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0145]
Epoch 2554/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.86it/s]

End of Epoch 2554 | Train Loss: 0.021948 | Val Loss: 0.349187

Epoch 2555/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00423]
Epoch 2555/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.66it/s]

End of Epoch 2555 | Train Loss: 0.023139 | Val Loss: 0.327573

Epoch 2556/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00395]
Epoch 2556/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 2556 | Train Loss: 0.022674 | Val Loss: 0.784851

Epoch 2557/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00452]
Epoch 2557/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 2557 | Train Loss: 0.018757 | Val Loss: 0.422392

Epoch 2558/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00429]
Epoch 2558/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.48it/s]

End of Epoch 2558 | Train Loss: 0.021218 | Val Loss: 0.596166

Epoch 2559/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0144]
Epoch 2559/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 2559 | Train Loss: 0.020105 | Val Loss: 0.242291

Epoch 2560/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.674]
Epoch 2560/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 2560 | Train Loss: 0.036257 | Val Loss: 0.520375

Epoch 2561/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00433]
Epoch 2561/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.02it/s]

End of Epoch 2561 | Train Loss: 0.031964 | Val Loss: 0.567415

Epoch 2562/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00479]
Epoch 2562/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.17it/s]

End of Epoch 2562 | Train Loss: 0.023876 | Val Loss: 0.372131

Epoch 2563/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00391]
Epoch 2563/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.29it/s]

End of Epoch 2563 | Train Loss: 0.019261 | Val Loss: 0.481633

Epoch 2564/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0026]
Epoch 2564/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 2564 | Train Loss: 0.020378 | Val Loss: 0.338098

Epoch 2565/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0229]
Epoch 2565/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 2565 | Train Loss: 0.020223 | Val Loss: 0.530161

Epoch 2566/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00316]
Epoch 2566/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 2566 | Train Loss: 0.018847 | Val Loss: 0.241492

Epoch 2567/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00251]
Epoch 2567/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.41it/s]

End of Epoch 2567 | Train Loss: 0.016898 | Val Loss: 0.452022

Epoch 2568/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00503]
Epoch 2568/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 2568 | Train Loss: 0.025716 | Val Loss: 0.213062

Epoch 2569/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.00742]
Epoch 2569/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 2569 | Train Loss: 0.017235 | Val Loss: 0.457715

Epoch 2570/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00533]
Epoch 2570/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.80it/s]

End of Epoch 2570 | Train Loss: 0.020816 | Val Loss: 0.304714

Epoch 2571/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.018]
Epoch 2571/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.89it/s]

End of Epoch 2571 | Train Loss: 0.024224 | Val Loss: 0.545387

Epoch 2572/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00374]
Epoch 2572/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.48it/s]

End of Epoch 2572 | Train Loss: 0.020829 | Val Loss: 0.475448

Epoch 2573/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00274]
Epoch 2573/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 2573 | Train Loss: 0.015650 | Val Loss: 0.397660

Epoch 2574/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00263]
Epoch 2574/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.61it/s]

End of Epoch 2574 | Train Loss: 0.015430 | Val Loss: 0.376342

Epoch 2575/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00289]
Epoch 2575/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.18it/s]

End of Epoch 2575 | Train Loss: 0.026146 | Val Loss: 0.554954

Epoch 2576/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00661]
Epoch 2576/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.59it/s]

End of Epoch 2576 | Train Loss: 0.022996 | Val Loss: 0.175209

Epoch 2577/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00581]
Epoch 2577/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.54it/s]

End of Epoch 2577 | Train Loss: 0.021214 | Val Loss: 0.407837

Epoch 2578/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0762]
Epoch 2578/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 2578 | Train Loss: 0.021465 | Val Loss: 0.236988

Epoch 2579/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00553]
Epoch 2579/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.80it/s]

End of Epoch 2579 | Train Loss: 0.022555 | Val Loss: 0.416478

Epoch 2580/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00714]
Epoch 2580/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 2580 | Train Loss: 0.020043 | Val Loss: 0.317809

Epoch 2581/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.486]
Epoch 2581/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.99it/s]

End of Epoch 2581 | Train Loss: 0.030286 | Val Loss: 0.699062

Epoch 2582/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00389]
Epoch 2582/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.37it/s]

End of Epoch 2582 | Train Loss: 0.027760 | Val Loss: 0.339977

Epoch 2583/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00643]
Epoch 2583/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.61it/s]

End of Epoch 2583 | Train Loss: 0.025827 | Val Loss: 0.550410

Epoch 2584/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00277]
Epoch 2584/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 2584 | Train Loss: 0.019970 | Val Loss: 0.713961

Epoch 2585/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00341]
Epoch 2585/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 2585 | Train Loss: 0.015748 | Val Loss: 0.442790

Epoch 2586/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00275]
Epoch 2586/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.04it/s]

End of Epoch 2586 | Train Loss: 0.023420 | Val Loss: 0.340719

Epoch 2587/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0041]
Epoch 2587/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.42it/s]

End of Epoch 2587 | Train Loss: 0.023825 | Val Loss: 0.639947

Epoch 2588/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0041]
Epoch 2588/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 2588 | Train Loss: 0.018263 | Val Loss: 0.444217

Epoch 2589/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.00653]
Epoch 2589/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.83it/s]

End of Epoch 2589 | Train Loss: 0.022002 | Val Loss: 0.530802

Epoch 2590/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00446]
Epoch 2590/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.98it/s]

End of Epoch 2590 | Train Loss: 0.019277 | Val Loss: 0.453142

Epoch 2591/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00954]
Epoch 2591/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 2591 | Train Loss: 0.020015 | Val Loss: 0.315084

Epoch 2592/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00385]
Epoch 2592/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 2592 | Train Loss: 0.025788 | Val Loss: 0.286030

Epoch 2593/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00387]
Epoch 2593/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 2593 | Train Loss: 0.031425 | Val Loss: 0.341832

Epoch 2594/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00564]
Epoch 2594/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.21it/s]

End of Epoch 2594 | Train Loss: 0.028497 | Val Loss: 0.635988

Epoch 2595/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00731]
Epoch 2595/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.50it/s]

End of Epoch 2595 | Train Loss: 0.023134 | Val Loss: 0.563424

Epoch 2596/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00346]
Epoch 2596/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.83it/s]

End of Epoch 2596 | Train Loss: 0.020760 | Val Loss: 0.393189

Epoch 2597/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00339]
Epoch 2597/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 2597 | Train Loss: 0.021390 | Val Loss: 0.266504

Epoch 2598/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00276]
Epoch 2598/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 2598 | Train Loss: 0.022083 | Val Loss: 0.476867

Epoch 2599/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00299]
Epoch 2599/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.94it/s]

End of Epoch 2599 | Train Loss: 0.020136 | Val Loss: 0.775549

Epoch 2600/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00434]
Epoch 2600/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.28it/s]

End of Epoch 2600 | Train Loss: 0.027523 | Val Loss: 0.341794

Epoch 2601/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00339]
Epoch 2601/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 2601 | Train Loss: 0.023078 | Val Loss: 0.321954

Epoch 2602/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00312]
Epoch 2602/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 2602 | Train Loss: 0.019117 | Val Loss: 0.169130

Epoch 2603/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00292]
Epoch 2603/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 2603 | Train Loss: 0.019541 | Val Loss: 0.390756

Epoch 2604/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00331]
Epoch 2604/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.17it/s]

End of Epoch 2604 | Train Loss: 0.020709 | Val Loss: 0.304257

Epoch 2605/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00322]
Epoch 2605/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 2605 | Train Loss: 0.024869 | Val Loss: 0.491287

Epoch 2606/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00331]
Epoch 2606/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.62it/s]

End of Epoch 2606 | Train Loss: 0.019634 | Val Loss: 0.487572

Epoch 2607/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00322]
Epoch 2607/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 2607 | Train Loss: 0.023833 | Val Loss: 0.570284

Epoch 2608/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00461]
Epoch 2608/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.77it/s]

End of Epoch 2608 | Train Loss: 0.028625 | Val Loss: 0.678980

Epoch 2609/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.00438]
Epoch 2609/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.34it/s]

End of Epoch 2609 | Train Loss: 0.015943 | Val Loss: 0.154488

Epoch 2610/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00418]
Epoch 2610/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.70it/s]

End of Epoch 2610 | Train Loss: 0.022340 | Val Loss: 0.576791

Epoch 2611/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00467]
Epoch 2611/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 2611 | Train Loss: 0.029294 | Val Loss: 0.358005

Epoch 2612/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0387]
Epoch 2612/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 2612 | Train Loss: 0.021186 | Val Loss: 0.601703

Epoch 2613/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0039]
Epoch 2613/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 2613 | Train Loss: 0.027512 | Val Loss: 0.588078

Epoch 2614/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00425]
Epoch 2614/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 2614 | Train Loss: 0.016281 | Val Loss: 0.483034

Epoch 2615/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00272]
Epoch 2615/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 2615 | Train Loss: 0.022255 | Val Loss: 0.438743

Epoch 2616/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00277]
Epoch 2616/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 2616 | Train Loss: 0.019373 | Val Loss: 0.462372

Epoch 2617/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00468]
Epoch 2617/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.19it/s]

End of Epoch 2617 | Train Loss: 0.019005 | Val Loss: 0.391720

Epoch 2618/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00382]
Epoch 2618/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 2618 | Train Loss: 0.023944 | Val Loss: 0.782305

Epoch 2619/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00396]
Epoch 2619/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.04it/s]

End of Epoch 2619 | Train Loss: 0.026194 | Val Loss: 0.381727

Epoch 2620/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00357]
Epoch 2620/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.72it/s]

End of Epoch 2620 | Train Loss: 0.026321 | Val Loss: 0.231826

Epoch 2621/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.357]
Epoch 2621/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.18it/s]

End of Epoch 2621 | Train Loss: 0.024434 | Val Loss: 0.486933

Epoch 2622/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0131]
Epoch 2622/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.78it/s]

End of Epoch 2622 | Train Loss: 0.023906 | Val Loss: 0.586657

Epoch 2623/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.011]
Epoch 2623/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 2623 | Train Loss: 0.024896 | Val Loss: 0.607923

Epoch 2624/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.006]
Epoch 2624/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 2624 | Train Loss: 0.024395 | Val Loss: 0.432406

Epoch 2625/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00694]
Epoch 2625/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 2625 | Train Loss: 0.026347 | Val Loss: 0.684984

Epoch 2626/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00512]
Epoch 2626/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.61it/s]

End of Epoch 2626 | Train Loss: 0.025170 | Val Loss: 0.268841

Epoch 2627/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0828]
Epoch 2627/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.73it/s]

End of Epoch 2627 | Train Loss: 0.018872 | Val Loss: 0.571981

Epoch 2628/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00881]
Epoch 2628/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 2628 | Train Loss: 0.025071 | Val Loss: 0.678941

Epoch 2629/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.0035]
Epoch 2629/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 2629 | Train Loss: 0.019293 | Val Loss: 1.212196

Epoch 2630/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00241]
Epoch 2630/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 2630 | Train Loss: 0.019342 | Val Loss: 0.557227

Epoch 2631/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00262]
Epoch 2631/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.30it/s]

End of Epoch 2631 | Train Loss: 0.018661 | Val Loss: 0.551104

Epoch 2632/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00316]
Epoch 2632/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 2632 | Train Loss: 0.016277 | Val Loss: 0.396338

Epoch 2633/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00339]
Epoch 2633/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.18it/s]

End of Epoch 2633 | Train Loss: 0.022848 | Val Loss: 0.616683

Epoch 2634/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00376]
Epoch 2634/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.20it/s]

End of Epoch 2634 | Train Loss: 0.019491 | Val Loss: 0.393713

Epoch 2635/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00427]
Epoch 2635/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.58it/s]

End of Epoch 2635 | Train Loss: 0.019476 | Val Loss: 0.820684

Epoch 2636/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0147]
Epoch 2636/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.14it/s]

End of Epoch 2636 | Train Loss: 0.025653 | Val Loss: 0.515713

Epoch 2637/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0072]
Epoch 2637/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 2637 | Train Loss: 0.025529 | Val Loss: 0.579669

Epoch 2638/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00274]
Epoch 2638/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.20it/s]

End of Epoch 2638 | Train Loss: 0.024190 | Val Loss: 0.535820

Epoch 2639/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00534]
Epoch 2639/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 2639 | Train Loss: 0.021542 | Val Loss: 0.640965

Epoch 2640/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0147]
Epoch 2640/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.46it/s]

End of Epoch 2640 | Train Loss: 0.024277 | Val Loss: 0.767871

Epoch 2641/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00373]
Epoch 2641/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 2641 | Train Loss: 0.018396 | Val Loss: 0.214360

Epoch 2642/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0093]
Epoch 2642/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.25it/s]

End of Epoch 2642 | Train Loss: 0.022890 | Val Loss: 0.286662

Epoch 2643/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00335]
Epoch 2643/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.97it/s]

End of Epoch 2643 | Train Loss: 0.018213 | Val Loss: 0.730695

Epoch 2644/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0206]
Epoch 2644/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.73it/s]

End of Epoch 2644 | Train Loss: 0.023074 | Val Loss: 0.579842

Epoch 2645/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0028]
Epoch 2645/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.06it/s]

End of Epoch 2645 | Train Loss: 0.018985 | Val Loss: 0.392609

Epoch 2646/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00305]
Epoch 2646/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 2646 | Train Loss: 0.021213 | Val Loss: 0.332475

Epoch 2647/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.016]
Epoch 2647/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.50it/s]

End of Epoch 2647 | Train Loss: 0.023120 | Val Loss: 0.369413

Epoch 2648/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0329]
Epoch 2648/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 2648 | Train Loss: 0.025030 | Val Loss: 0.661158

Epoch 2649/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00586]
Epoch 2649/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.39it/s]

End of Epoch 2649 | Train Loss: 0.021329 | Val Loss: 0.515748

Epoch 2650/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0369]
Epoch 2650/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.42it/s]

End of Epoch 2650 | Train Loss: 0.021886 | Val Loss: 0.453874

Epoch 2651/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.0037]
Epoch 2651/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.88it/s]

End of Epoch 2651 | Train Loss: 0.019015 | Val Loss: 0.387693

Epoch 2652/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00429]
Epoch 2652/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.94it/s]

End of Epoch 2652 | Train Loss: 0.025515 | Val Loss: 0.368160

Epoch 2653/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00257]
Epoch 2653/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.57it/s]

End of Epoch 2653 | Train Loss: 0.024549 | Val Loss: 0.954308

Epoch 2654/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0136]
Epoch 2654/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 2654 | Train Loss: 0.019216 | Val Loss: 0.802963

Epoch 2655/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00372]
Epoch 2655/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.27it/s]

End of Epoch 2655 | Train Loss: 0.024445 | Val Loss: 0.579174

Epoch 2656/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00315]
Epoch 2656/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 2656 | Train Loss: 0.025089 | Val Loss: 0.549019

Epoch 2657/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00354]
Epoch 2657/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.24it/s]

End of Epoch 2657 | Train Loss: 0.020545 | Val Loss: 0.348098

Epoch 2658/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.0362]
Epoch 2658/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.49it/s]

End of Epoch 2658 | Train Loss: 0.027390 | Val Loss: 0.453775

Epoch 2659/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00465]
Epoch 2659/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.32it/s]

End of Epoch 2659 | Train Loss: 0.019092 | Val Loss: 0.603911

Epoch 2660/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00382]
Epoch 2660/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.09it/s]

End of Epoch 2660 | Train Loss: 0.024238 | Val Loss: 0.485402

Epoch 2661/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00367]
Epoch 2661/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.97it/s]

End of Epoch 2661 | Train Loss: 0.023390 | Val Loss: 0.383636

Epoch 2662/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00301]
Epoch 2662/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.67it/s]

End of Epoch 2662 | Train Loss: 0.021326 | Val Loss: 0.448530

Epoch 2663/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00332]
Epoch 2663/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 2663 | Train Loss: 0.028400 | Val Loss: 0.558801

Epoch 2664/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0102]
Epoch 2664/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.48it/s]

End of Epoch 2664 | Train Loss: 0.024710 | Val Loss: 0.706609

Epoch 2665/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0062]
Epoch 2665/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.95it/s]

End of Epoch 2665 | Train Loss: 0.020616 | Val Loss: 0.506277

Epoch 2666/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0034]
Epoch 2666/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.35it/s]

End of Epoch 2666 | Train Loss: 0.019867 | Val Loss: 0.755211

Epoch 2667/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.0104]
Epoch 2667/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.06it/s]

End of Epoch 2667 | Train Loss: 0.024482 | Val Loss: 0.406896

Epoch 2668/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0735]
Epoch 2668/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 2668 | Train Loss: 0.024664 | Val Loss: 0.414083

Epoch 2669/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.43it/s, loss=0.00303]
Epoch 2669/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 2669 | Train Loss: 0.027398 | Val Loss: 0.639276

Epoch 2670/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0032]
Epoch 2670/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.05it/s]

End of Epoch 2670 | Train Loss: 0.022707 | Val Loss: 0.447209

Epoch 2671/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00305]
Epoch 2671/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 2671 | Train Loss: 0.020106 | Val Loss: 0.560254

Epoch 2672/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.67it/s, loss=0.0208]
Epoch 2672/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.74it/s]

End of Epoch 2672 | Train Loss: 0.024644 | Val Loss: 0.467715

Epoch 2673/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00334]
Epoch 2673/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 2673 | Train Loss: 0.017311 | Val Loss: 0.696764

Epoch 2674/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00261]
Epoch 2674/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.60it/s]

End of Epoch 2674 | Train Loss: 0.024488 | Val Loss: 0.375604

Epoch 2675/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00305]
Epoch 2675/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 2675 | Train Loss: 0.025106 | Val Loss: 0.323101

Epoch 2676/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0115]
Epoch 2676/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 2676 | Train Loss: 0.027293 | Val Loss: 0.343730

Epoch 2677/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00325]
Epoch 2677/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.66it/s]

End of Epoch 2677 | Train Loss: 0.023845 | Val Loss: 0.587520

Epoch 2678/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00661]
Epoch 2678/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 2678 | Train Loss: 0.024335 | Val Loss: 0.210210

Epoch 2679/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00388]
Epoch 2679/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.25it/s]

End of Epoch 2679 | Train Loss: 0.018901 | Val Loss: 0.510762

Epoch 2680/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00597]
Epoch 2680/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.98it/s]

End of Epoch 2680 | Train Loss: 0.020323 | Val Loss: 0.807654

Epoch 2681/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00315]
Epoch 2681/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.41it/s]

End of Epoch 2681 | Train Loss: 0.020059 | Val Loss: 0.946049

Epoch 2682/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00418]
Epoch 2682/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.07it/s]

End of Epoch 2682 | Train Loss: 0.028998 | Val Loss: 0.597500

Epoch 2683/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00314]
Epoch 2683/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.14it/s]

End of Epoch 2683 | Train Loss: 0.026770 | Val Loss: 0.326866

Epoch 2684/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00356]
Epoch 2684/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 2684 | Train Loss: 0.021345 | Val Loss: 0.638036

Epoch 2685/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00749]
Epoch 2685/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.45it/s]

End of Epoch 2685 | Train Loss: 0.021265 | Val Loss: 0.340404

Epoch 2686/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00375]
Epoch 2686/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.27it/s]

End of Epoch 2686 | Train Loss: 0.024144 | Val Loss: 0.360386

Epoch 2687/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00601]
Epoch 2687/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 2687 | Train Loss: 0.020034 | Val Loss: 0.754880

Epoch 2688/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00356]
Epoch 2688/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.05it/s]

End of Epoch 2688 | Train Loss: 0.023696 | Val Loss: 0.603107

Epoch 2689/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00304]
Epoch 2689/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.47it/s]

End of Epoch 2689 | Train Loss: 0.024060 | Val Loss: 0.408256

Epoch 2690/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00325]
Epoch 2690/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.58it/s]

End of Epoch 2690 | Train Loss: 0.023533 | Val Loss: 0.701188

Epoch 2691/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.005]
Epoch 2691/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.55it/s]

End of Epoch 2691 | Train Loss: 0.025686 | Val Loss: 0.509436

Epoch 2692/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0244]
Epoch 2692/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.66it/s]

End of Epoch 2692 | Train Loss: 0.021270 | Val Loss: 0.270426

Epoch 2693/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00554]
Epoch 2693/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.84it/s]

End of Epoch 2693 | Train Loss: 0.022067 | Val Loss: 0.406374

Epoch 2694/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00553]
Epoch 2694/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.44it/s]

End of Epoch 2694 | Train Loss: 0.023672 | Val Loss: 0.413473

Epoch 2695/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00921]
Epoch 2695/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.05it/s]

End of Epoch 2695 | Train Loss: 0.017447 | Val Loss: 0.538660

Epoch 2696/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00342]
Epoch 2696/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.71it/s]

End of Epoch 2696 | Train Loss: 0.023433 | Val Loss: 0.408075

Epoch 2697/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0179]
Epoch 2697/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 2697 | Train Loss: 0.016758 | Val Loss: 0.762123

Epoch 2698/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00391]
Epoch 2698/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.99it/s]

End of Epoch 2698 | Train Loss: 0.024897 | Val Loss: 0.446601

Epoch 2699/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00676]
Epoch 2699/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 2699 | Train Loss: 0.023878 | Val Loss: 0.507230

Epoch 2700/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00313]
Epoch 2700/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.12it/s]

End of Epoch 2700 | Train Loss: 0.022351 | Val Loss: 0.306821

Epoch 2701/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00583]
Epoch 2701/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 2701 | Train Loss: 0.025700 | Val Loss: 0.551249

Epoch 2702/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0203]
Epoch 2702/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.81it/s]

End of Epoch 2702 | Train Loss: 0.024624 | Val Loss: 0.538897

Epoch 2703/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00451]
Epoch 2703/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.83it/s]

End of Epoch 2703 | Train Loss: 0.017860 | Val Loss: 0.250310

Epoch 2704/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0132]
Epoch 2704/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.69it/s]

End of Epoch 2704 | Train Loss: 0.022159 | Val Loss: 0.339969

Epoch 2705/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00351]
Epoch 2705/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.22it/s]

End of Epoch 2705 | Train Loss: 0.020554 | Val Loss: 0.366591

Epoch 2706/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00293]
Epoch 2706/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 2706 | Train Loss: 0.020801 | Val Loss: 0.273290

Epoch 2707/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00638]
Epoch 2707/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.93it/s]

End of Epoch 2707 | Train Loss: 0.017225 | Val Loss: 0.596818

Epoch 2708/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0044]
Epoch 2708/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.99it/s]

End of Epoch 2708 | Train Loss: 0.021039 | Val Loss: 0.381191

Epoch 2709/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00235]
Epoch 2709/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 2709 | Train Loss: 0.021184 | Val Loss: 0.573151

Epoch 2710/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00354]
Epoch 2710/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.28it/s]

End of Epoch 2710 | Train Loss: 0.019749 | Val Loss: 0.187001

Epoch 2711/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00365]
Epoch 2711/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.83it/s]

End of Epoch 2711 | Train Loss: 0.028679 | Val Loss: 0.082497
New Best Model Saved (Val Loss: 0.082497)

Epoch 2712/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00358]
Epoch 2712/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 2712 | Train Loss: 0.017323 | Val Loss: 0.750574

Epoch 2713/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00344]
Epoch 2713/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 2713 | Train Loss: 0.025299 | Val Loss: 0.275102

Epoch 2714/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00418]
Epoch 2714/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.83it/s]

End of Epoch 2714 | Train Loss: 0.022006 | Val Loss: 0.491936

Epoch 2715/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00291]
Epoch 2715/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 2715 | Train Loss: 0.017424 | Val Loss: 0.434555

Epoch 2716/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00312]
Epoch 2716/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.65it/s]

End of Epoch 2716 | Train Loss: 0.020552 | Val Loss: 0.285213

Epoch 2717/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00409]
Epoch 2717/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.30it/s]

End of Epoch 2717 | Train Loss: 0.021323 | Val Loss: 0.258622

Epoch 2718/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.56it/s, loss=0.00347]
Epoch 2718/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.88it/s]

End of Epoch 2718 | Train Loss: 0.021234 | Val Loss: 0.478968

Epoch 2719/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0122]
Epoch 2719/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.43it/s]

End of Epoch 2719 | Train Loss: 0.020599 | Val Loss: 0.363344

Epoch 2720/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00256]
Epoch 2720/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 2720 | Train Loss: 0.022244 | Val Loss: 0.285581

Epoch 2721/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00387]
Epoch 2721/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 2721 | Train Loss: 0.023161 | Val Loss: 0.297291

Epoch 2722/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00288]
Epoch 2722/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.87it/s]

End of Epoch 2722 | Train Loss: 0.022654 | Val Loss: 0.477855

Epoch 2723/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0084]
Epoch 2723/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 2723 | Train Loss: 0.027399 | Val Loss: 0.489131

Epoch 2724/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0054]
Epoch 2724/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.95it/s]

End of Epoch 2724 | Train Loss: 0.019408 | Val Loss: 0.546508

Epoch 2725/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00566]
Epoch 2725/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.57it/s]

End of Epoch 2725 | Train Loss: 0.026496 | Val Loss: 0.395760

Epoch 2726/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00305]
Epoch 2726/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 2726 | Train Loss: 0.014959 | Val Loss: 0.434000

Epoch 2727/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.188]
Epoch 2727/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.78it/s]

End of Epoch 2727 | Train Loss: 0.020092 | Val Loss: 0.469875

Epoch 2728/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00692]
Epoch 2728/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 2728 | Train Loss: 0.026007 | Val Loss: 0.389112

Epoch 2729/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.42it/s, loss=0.00821]
Epoch 2729/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 2729 | Train Loss: 0.023260 | Val Loss: 0.316709

Epoch 2730/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00896]
Epoch 2730/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.68it/s]

End of Epoch 2730 | Train Loss: 0.016331 | Val Loss: 1.035822

Epoch 2731/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0162]
Epoch 2731/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.61it/s]

End of Epoch 2731 | Train Loss: 0.021206 | Val Loss: 0.554102

Epoch 2732/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00516]
Epoch 2732/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.74it/s]

End of Epoch 2732 | Train Loss: 0.018636 | Val Loss: 0.477660

Epoch 2733/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0068]
Epoch 2733/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.90it/s]

End of Epoch 2733 | Train Loss: 0.027564 | Val Loss: 0.773482

Epoch 2734/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00309]
Epoch 2734/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.31it/s]

End of Epoch 2734 | Train Loss: 0.017816 | Val Loss: 0.465266

Epoch 2735/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00765]
Epoch 2735/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.29it/s]

End of Epoch 2735 | Train Loss: 0.016749 | Val Loss: 0.532990

Epoch 2736/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00351]
Epoch 2736/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.45it/s]

End of Epoch 2736 | Train Loss: 0.019654 | Val Loss: 0.306894

Epoch 2737/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0597]
Epoch 2737/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 2737 | Train Loss: 0.022751 | Val Loss: 0.633869

Epoch 2738/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00308]
Epoch 2738/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 2738 | Train Loss: 0.024357 | Val Loss: 0.166144

Epoch 2739/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00328]
Epoch 2739/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.56it/s]

End of Epoch 2739 | Train Loss: 0.023543 | Val Loss: 0.379256

Epoch 2740/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00452]
Epoch 2740/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.34it/s]

End of Epoch 2740 | Train Loss: 0.024717 | Val Loss: 0.240365

Epoch 2741/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0584]
Epoch 2741/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.05it/s]

End of Epoch 2741 | Train Loss: 0.020233 | Val Loss: 0.265425

Epoch 2742/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00387]
Epoch 2742/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 2742 | Train Loss: 0.022029 | Val Loss: 0.470473

Epoch 2743/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00369]
Epoch 2743/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.91it/s]

End of Epoch 2743 | Train Loss: 0.019468 | Val Loss: 0.478678

Epoch 2744/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00736]
Epoch 2744/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 2744 | Train Loss: 0.021672 | Val Loss: 0.526601

Epoch 2745/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00369]
Epoch 2745/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.90it/s]

End of Epoch 2745 | Train Loss: 0.020138 | Val Loss: 0.502905

Epoch 2746/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00487]
Epoch 2746/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 2746 | Train Loss: 0.020213 | Val Loss: 0.857265

Epoch 2747/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00284]
Epoch 2747/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.70it/s]

End of Epoch 2747 | Train Loss: 0.022588 | Val Loss: 0.814343

Epoch 2748/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0034]
Epoch 2748/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.86it/s]

End of Epoch 2748 | Train Loss: 0.019777 | Val Loss: 0.421404

Epoch 2749/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0274]
Epoch 2749/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 2749 | Train Loss: 0.016789 | Val Loss: 0.792007

Epoch 2750/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00338]
Epoch 2750/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.88it/s]

End of Epoch 2750 | Train Loss: 0.023089 | Val Loss: 0.706295

Epoch 2751/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00281]
Epoch 2751/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.12it/s]

End of Epoch 2751 | Train Loss: 0.020186 | Val Loss: 0.565905

Epoch 2752/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00352]
Epoch 2752/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.20it/s]

End of Epoch 2752 | Train Loss: 0.023620 | Val Loss: 0.502984

Epoch 2753/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0027]
Epoch 2753/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 2753 | Train Loss: 0.020326 | Val Loss: 0.366586

Epoch 2754/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.0147]
Epoch 2754/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.76it/s]

End of Epoch 2754 | Train Loss: 0.021185 | Val Loss: 0.492425

Epoch 2755/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0225]
Epoch 2755/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 2755 | Train Loss: 0.023537 | Val Loss: 0.374572

Epoch 2756/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00483]
Epoch 2756/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 2756 | Train Loss: 0.026748 | Val Loss: 0.616168

Epoch 2757/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00553]
Epoch 2757/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.93it/s]

End of Epoch 2757 | Train Loss: 0.021622 | Val Loss: 0.878144

Epoch 2758/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00298]
Epoch 2758/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 2758 | Train Loss: 0.015838 | Val Loss: 0.350714

Epoch 2759/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0135]
Epoch 2759/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.60it/s]

End of Epoch 2759 | Train Loss: 0.023851 | Val Loss: 0.537563

Epoch 2760/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0033]
Epoch 2760/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 2760 | Train Loss: 0.022654 | Val Loss: 0.447274

Epoch 2761/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00301]
Epoch 2761/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 2761 | Train Loss: 0.023314 | Val Loss: 0.391725

Epoch 2762/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00403]
Epoch 2762/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.88it/s]

End of Epoch 2762 | Train Loss: 0.024047 | Val Loss: 0.597212

Epoch 2763/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00452]
Epoch 2763/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 2763 | Train Loss: 0.020555 | Val Loss: 0.425181

Epoch 2764/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00382]
Epoch 2764/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 2764 | Train Loss: 0.028580 | Val Loss: 0.310718

Epoch 2765/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00796]
Epoch 2765/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 2765 | Train Loss: 0.021426 | Val Loss: 0.481030

Epoch 2766/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0069]
Epoch 2766/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 2766 | Train Loss: 0.027785 | Val Loss: 0.471382

Epoch 2767/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00497]
Epoch 2767/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 2767 | Train Loss: 0.021545 | Val Loss: 0.536984

Epoch 2768/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00447]
Epoch 2768/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 2768 | Train Loss: 0.022223 | Val Loss: 0.989976

Epoch 2769/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.46it/s, loss=0.00388]
Epoch 2769/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 2769 | Train Loss: 0.022476 | Val Loss: 0.186398

Epoch 2770/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00254]
Epoch 2770/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.21it/s]

End of Epoch 2770 | Train Loss: 0.018215 | Val Loss: 0.434747

Epoch 2771/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.203]
Epoch 2771/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 2771 | Train Loss: 0.024819 | Val Loss: 0.586072

Epoch 2772/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00369]
Epoch 2772/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 2772 | Train Loss: 0.023139 | Val Loss: 0.377044

Epoch 2773/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.04]
Epoch 2773/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.74it/s]

End of Epoch 2773 | Train Loss: 0.023778 | Val Loss: 0.576023

Epoch 2774/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0028]
Epoch 2774/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.66it/s]

End of Epoch 2774 | Train Loss: 0.019175 | Val Loss: 0.380366

Epoch 2775/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00345]
Epoch 2775/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.39it/s]

End of Epoch 2775 | Train Loss: 0.012988 | Val Loss: 0.319145

Epoch 2776/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.014]
Epoch 2776/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2776 | Train Loss: 0.014944 | Val Loss: 0.534159

Epoch 2777/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0054]
Epoch 2777/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.65it/s]

End of Epoch 2777 | Train Loss: 0.020058 | Val Loss: 0.699245

Epoch 2778/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00335]
Epoch 2778/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.54it/s]

End of Epoch 2778 | Train Loss: 0.018834 | Val Loss: 0.308249

Epoch 2779/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00277]
Epoch 2779/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.05it/s]

End of Epoch 2779 | Train Loss: 0.019629 | Val Loss: 0.704955

Epoch 2780/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0313]
Epoch 2780/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.57it/s]

End of Epoch 2780 | Train Loss: 0.024593 | Val Loss: 0.206884

Epoch 2781/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00653]
Epoch 2781/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 2781 | Train Loss: 0.020121 | Val Loss: 0.500962

Epoch 2782/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00353]
Epoch 2782/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.09it/s]

End of Epoch 2782 | Train Loss: 0.019662 | Val Loss: 0.646118

Epoch 2783/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00388]
Epoch 2783/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.22it/s]

End of Epoch 2783 | Train Loss: 0.017513 | Val Loss: 0.564253

Epoch 2784/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00343]
Epoch 2784/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.60it/s]

End of Epoch 2784 | Train Loss: 0.023658 | Val Loss: 0.554072

Epoch 2785/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00345]
Epoch 2785/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.43it/s]

End of Epoch 2785 | Train Loss: 0.026760 | Val Loss: 0.527235

Epoch 2786/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00259]
Epoch 2786/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 2786 | Train Loss: 0.020016 | Val Loss: 0.426002

Epoch 2787/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00394]
Epoch 2787/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.56it/s]

End of Epoch 2787 | Train Loss: 0.022869 | Val Loss: 0.572215

Epoch 2788/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.47it/s, loss=0.00595]
Epoch 2788/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 2788 | Train Loss: 0.019458 | Val Loss: 0.455218

Epoch 2789/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00361]
Epoch 2789/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.73it/s]

End of Epoch 2789 | Train Loss: 0.024184 | Val Loss: 0.387871

Epoch 2790/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0169]
Epoch 2790/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.24it/s]

End of Epoch 2790 | Train Loss: 0.020249 | Val Loss: 0.412262

Epoch 2791/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00251]
Epoch 2791/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 2791 | Train Loss: 0.018925 | Val Loss: 0.573383

Epoch 2792/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00264]
Epoch 2792/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 2792 | Train Loss: 0.019008 | Val Loss: 0.705912

Epoch 2793/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0085]
Epoch 2793/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 2793 | Train Loss: 0.022122 | Val Loss: 0.809764

Epoch 2794/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00299]
Epoch 2794/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 2794 | Train Loss: 0.028194 | Val Loss: 0.343685

Epoch 2795/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0146]
Epoch 2795/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 2795 | Train Loss: 0.018776 | Val Loss: 0.606735

Epoch 2796/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00263]
Epoch 2796/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.74it/s]

End of Epoch 2796 | Train Loss: 0.020378 | Val Loss: 0.324799

Epoch 2797/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00347]
Epoch 2797/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.94it/s]

End of Epoch 2797 | Train Loss: 0.024797 | Val Loss: 0.372440

Epoch 2798/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00372]
Epoch 2798/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.37it/s]

End of Epoch 2798 | Train Loss: 0.022830 | Val Loss: 0.467461

Epoch 2799/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0036]
Epoch 2799/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.44it/s]

End of Epoch 2799 | Train Loss: 0.019635 | Val Loss: 0.576367

Epoch 2800/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00533]
Epoch 2800/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.63it/s]

End of Epoch 2800 | Train Loss: 0.021353 | Val Loss: 0.373061

Epoch 2801/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00283]
Epoch 2801/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.28it/s]

End of Epoch 2801 | Train Loss: 0.022311 | Val Loss: 0.139400

Epoch 2802/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0117]
Epoch 2802/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.70it/s]

End of Epoch 2802 | Train Loss: 0.017028 | Val Loss: 0.263166

Epoch 2803/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00681]
Epoch 2803/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 2803 | Train Loss: 0.017412 | Val Loss: 0.300445

Epoch 2804/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00808]
Epoch 2804/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.34it/s]

End of Epoch 2804 | Train Loss: 0.021079 | Val Loss: 0.412383

Epoch 2805/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00383]
Epoch 2805/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.41it/s]

End of Epoch 2805 | Train Loss: 0.017256 | Val Loss: 0.619036

Epoch 2806/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00688]
Epoch 2806/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.97it/s]

End of Epoch 2806 | Train Loss: 0.021446 | Val Loss: 0.268581

Epoch 2807/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00441]
Epoch 2807/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 2807 | Train Loss: 0.028010 | Val Loss: 0.290177

Epoch 2808/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.56it/s, loss=0.0159]
Epoch 2808/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.07it/s]

End of Epoch 2808 | Train Loss: 0.022044 | Val Loss: 0.346709

Epoch 2809/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0029]
Epoch 2809/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.86it/s]

End of Epoch 2809 | Train Loss: 0.019098 | Val Loss: 0.320368

Epoch 2810/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00318]
Epoch 2810/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.65it/s]

End of Epoch 2810 | Train Loss: 0.024963 | Val Loss: 0.659097

Epoch 2811/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00281]
Epoch 2811/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.90it/s]

End of Epoch 2811 | Train Loss: 0.022564 | Val Loss: 0.417212

Epoch 2812/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0114]
Epoch 2812/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 2812 | Train Loss: 0.025664 | Val Loss: 0.510892

Epoch 2813/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00305]
Epoch 2813/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 2813 | Train Loss: 0.021348 | Val Loss: 0.402808

Epoch 2814/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00321]
Epoch 2814/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.34it/s]

End of Epoch 2814 | Train Loss: 0.018817 | Val Loss: 0.337605

Epoch 2815/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0021]
Epoch 2815/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.83it/s]

End of Epoch 2815 | Train Loss: 0.022220 | Val Loss: 0.526919

Epoch 2816/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0177]
Epoch 2816/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.78it/s]

End of Epoch 2816 | Train Loss: 0.022692 | Val Loss: 0.663541

Epoch 2817/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00339]
Epoch 2817/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.56it/s]

End of Epoch 2817 | Train Loss: 0.020200 | Val Loss: 0.426220

Epoch 2818/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00281]
Epoch 2818/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 2818 | Train Loss: 0.024118 | Val Loss: 0.599487

Epoch 2819/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.27it/s, loss=0.00282]
Epoch 2819/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 2819 | Train Loss: 0.021934 | Val Loss: 0.388467

Epoch 2820/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00268]
Epoch 2820/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.64it/s]

End of Epoch 2820 | Train Loss: 0.019762 | Val Loss: 0.210011

Epoch 2821/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00231]
Epoch 2821/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.36it/s]

End of Epoch 2821 | Train Loss: 0.019689 | Val Loss: 0.347414

Epoch 2822/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00385]
Epoch 2822/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.35it/s]

End of Epoch 2822 | Train Loss: 0.025434 | Val Loss: 1.078212

Epoch 2823/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0109]
Epoch 2823/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 2823 | Train Loss: 0.024052 | Val Loss: 0.714378

Epoch 2824/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00496]
Epoch 2824/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.19it/s]

End of Epoch 2824 | Train Loss: 0.024548 | Val Loss: 0.809670

Epoch 2825/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.951]
Epoch 2825/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.98it/s]

End of Epoch 2825 | Train Loss: 0.040756 | Val Loss: 0.693289

Epoch 2826/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00326]
Epoch 2826/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.48it/s]

End of Epoch 2826 | Train Loss: 0.027359 | Val Loss: 0.190126

Epoch 2827/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.393]
Epoch 2827/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.10it/s]

End of Epoch 2827 | Train Loss: 0.023614 | Val Loss: 0.542943

Epoch 2828/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00327]
Epoch 2828/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.80it/s]

End of Epoch 2828 | Train Loss: 0.028386 | Val Loss: 0.516899

Epoch 2829/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0171]
Epoch 2829/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 2829 | Train Loss: 0.022589 | Val Loss: 0.273163

Epoch 2830/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0034]
Epoch 2830/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.86it/s]

End of Epoch 2830 | Train Loss: 0.025766 | Val Loss: 0.442441

Epoch 2831/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00974]
Epoch 2831/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.30it/s]

End of Epoch 2831 | Train Loss: 0.018684 | Val Loss: 0.613671

Epoch 2832/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0029]
Epoch 2832/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 2832 | Train Loss: 0.015808 | Val Loss: 0.263630

Epoch 2833/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00339]
Epoch 2833/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 2833 | Train Loss: 0.020401 | Val Loss: 0.397204

Epoch 2834/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00588]
Epoch 2834/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 2834 | Train Loss: 0.020969 | Val Loss: 0.366258

Epoch 2835/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00345]
Epoch 2835/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.39it/s]

End of Epoch 2835 | Train Loss: 0.019591 | Val Loss: 0.395702

Epoch 2836/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00267]
Epoch 2836/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.97it/s]

End of Epoch 2836 | Train Loss: 0.017393 | Val Loss: 0.322276

Epoch 2837/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00312]
Epoch 2837/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.77it/s]

End of Epoch 2837 | Train Loss: 0.013356 | Val Loss: 0.776285

Epoch 2838/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0258]
Epoch 2838/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 2838 | Train Loss: 0.023114 | Val Loss: 0.273952

Epoch 2839/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00369]
Epoch 2839/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.33it/s]

End of Epoch 2839 | Train Loss: 0.014689 | Val Loss: 0.831449

Epoch 2840/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0777]
Epoch 2840/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.80it/s]

End of Epoch 2840 | Train Loss: 0.018117 | Val Loss: 0.573238

Epoch 2841/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00326]
Epoch 2841/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.14it/s]

End of Epoch 2841 | Train Loss: 0.021510 | Val Loss: 0.521539

Epoch 2842/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00542]
Epoch 2842/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.81it/s]

End of Epoch 2842 | Train Loss: 0.016826 | Val Loss: 0.417946

Epoch 2843/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00471]
Epoch 2843/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 2843 | Train Loss: 0.020839 | Val Loss: 0.601517

Epoch 2844/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00713]
Epoch 2844/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 2844 | Train Loss: 0.024444 | Val Loss: 0.311201

Epoch 2845/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00274]
Epoch 2845/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 2845 | Train Loss: 0.022519 | Val Loss: 0.486654

Epoch 2846/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.004]
Epoch 2846/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 2846 | Train Loss: 0.020495 | Val Loss: 0.739869

Epoch 2847/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00348]
Epoch 2847/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.40it/s]

End of Epoch 2847 | Train Loss: 0.027810 | Val Loss: 0.471120

Epoch 2848/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.50it/s, loss=0.00308]
Epoch 2848/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 2848 | Train Loss: 0.022649 | Val Loss: 0.500392

Epoch 2849/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00315]
Epoch 2849/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.10it/s]

End of Epoch 2849 | Train Loss: 0.018036 | Val Loss: 0.718370

Epoch 2850/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00339]
Epoch 2850/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.34it/s]

End of Epoch 2850 | Train Loss: 0.020158 | Val Loss: 0.444903

Epoch 2851/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0211]
Epoch 2851/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.53it/s]

End of Epoch 2851 | Train Loss: 0.020799 | Val Loss: 0.895106

Epoch 2852/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0167]
Epoch 2852/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.08it/s]

End of Epoch 2852 | Train Loss: 0.020631 | Val Loss: 0.700890

Epoch 2853/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00259]
Epoch 2853/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.37it/s]

End of Epoch 2853 | Train Loss: 0.023064 | Val Loss: 0.449539

Epoch 2854/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.004]
Epoch 2854/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 2854 | Train Loss: 0.023729 | Val Loss: 0.224665

Epoch 2855/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00611]
Epoch 2855/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.45it/s]

End of Epoch 2855 | Train Loss: 0.028936 | Val Loss: 0.127784

Epoch 2856/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00327]
Epoch 2856/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 2856 | Train Loss: 0.024783 | Val Loss: 0.806095

Epoch 2857/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00612]
Epoch 2857/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 2857 | Train Loss: 0.017425 | Val Loss: 0.590820

Epoch 2858/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0023]
Epoch 2858/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.53it/s]

End of Epoch 2858 | Train Loss: 0.028364 | Val Loss: 0.232238

Epoch 2859/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00271]
Epoch 2859/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 2859 | Train Loss: 0.017974 | Val Loss: 0.580481

Epoch 2860/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00406]
Epoch 2860/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 2860 | Train Loss: 0.018154 | Val Loss: 0.529006

Epoch 2861/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00435]
Epoch 2861/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.14it/s]

End of Epoch 2861 | Train Loss: 0.023351 | Val Loss: 0.372099

Epoch 2862/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0129]
Epoch 2862/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.33it/s]

End of Epoch 2862 | Train Loss: 0.022899 | Val Loss: 0.371526

Epoch 2863/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0109]
Epoch 2863/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 2863 | Train Loss: 0.016729 | Val Loss: 0.395949

Epoch 2864/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00512]
Epoch 2864/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.50it/s]

End of Epoch 2864 | Train Loss: 0.017363 | Val Loss: 0.900003

Epoch 2865/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00491]
Epoch 2865/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.96it/s]

End of Epoch 2865 | Train Loss: 0.020972 | Val Loss: 0.609833

Epoch 2866/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00576]
Epoch 2866/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.46it/s]

End of Epoch 2866 | Train Loss: 0.020262 | Val Loss: 0.665730

Epoch 2867/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00558]
Epoch 2867/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 2867 | Train Loss: 0.016936 | Val Loss: 0.702668

Epoch 2868/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.59it/s, loss=0.00305]
Epoch 2868/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.55it/s]

End of Epoch 2868 | Train Loss: 0.019708 | Val Loss: 0.378101

Epoch 2869/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.486]
Epoch 2869/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.02it/s]

End of Epoch 2869 | Train Loss: 0.031231 | Val Loss: 0.416656

Epoch 2870/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00407]
Epoch 2870/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.82it/s]

End of Epoch 2870 | Train Loss: 0.033829 | Val Loss: 0.543665

Epoch 2871/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0053]
Epoch 2871/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.37it/s]

End of Epoch 2871 | Train Loss: 0.027214 | Val Loss: 0.354946

Epoch 2872/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00327]
Epoch 2872/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.38it/s]

End of Epoch 2872 | Train Loss: 0.020613 | Val Loss: 0.533135

Epoch 2873/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00563]
Epoch 2873/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 2873 | Train Loss: 0.020383 | Val Loss: 0.386046

Epoch 2874/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0537]
Epoch 2874/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.00it/s]

End of Epoch 2874 | Train Loss: 0.020700 | Val Loss: 0.527454

Epoch 2875/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00405]
Epoch 2875/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.03it/s]

End of Epoch 2875 | Train Loss: 0.027571 | Val Loss: 0.262956

Epoch 2876/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00581]
Epoch 2876/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 2876 | Train Loss: 0.028856 | Val Loss: 0.607969

Epoch 2877/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00805]
Epoch 2877/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.96it/s]

End of Epoch 2877 | Train Loss: 0.024446 | Val Loss: 0.360348

Epoch 2878/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00393]
Epoch 2878/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.14it/s]

End of Epoch 2878 | Train Loss: 0.025253 | Val Loss: 0.514375

Epoch 2879/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00269]
Epoch 2879/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.57it/s]

End of Epoch 2879 | Train Loss: 0.021879 | Val Loss: 0.442995

Epoch 2880/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00305]
Epoch 2880/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 2880 | Train Loss: 0.026037 | Val Loss: 0.516780

Epoch 2881/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00256]
Epoch 2881/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.18it/s]

End of Epoch 2881 | Train Loss: 0.018892 | Val Loss: 0.504403

Epoch 2882/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00531]
Epoch 2882/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 2882 | Train Loss: 0.027760 | Val Loss: 0.436284

Epoch 2883/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00407]
Epoch 2883/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 2883 | Train Loss: 0.022458 | Val Loss: 0.374155

Epoch 2884/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0276]
Epoch 2884/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.04it/s]

End of Epoch 2884 | Train Loss: 0.016942 | Val Loss: 0.501148

Epoch 2885/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0228]
Epoch 2885/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.21it/s]

End of Epoch 2885 | Train Loss: 0.015567 | Val Loss: 0.236437

Epoch 2886/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0131]
Epoch 2886/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 2886 | Train Loss: 0.018190 | Val Loss: 0.603528

Epoch 2887/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00323]
Epoch 2887/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 2887 | Train Loss: 0.018962 | Val Loss: 0.366076

Epoch 2888/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.0152]
Epoch 2888/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.99it/s]

End of Epoch 2888 | Train Loss: 0.023245 | Val Loss: 0.500142

Epoch 2889/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00566]
Epoch 2889/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.87it/s]

End of Epoch 2889 | Train Loss: 0.022936 | Val Loss: 0.506780

Epoch 2890/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00989]
Epoch 2890/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 2890 | Train Loss: 0.015245 | Val Loss: 0.585674

Epoch 2891/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0194]
Epoch 2891/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.65it/s]

End of Epoch 2891 | Train Loss: 0.016936 | Val Loss: 0.575227

Epoch 2892/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00316]
Epoch 2892/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 2892 | Train Loss: 0.020813 | Val Loss: 0.289710

Epoch 2893/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0457]
Epoch 2893/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 2893 | Train Loss: 0.024659 | Val Loss: 0.459848

Epoch 2894/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00527]
Epoch 2894/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 2894 | Train Loss: 0.016231 | Val Loss: 0.335731

Epoch 2895/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00266]
Epoch 2895/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 2895 | Train Loss: 0.024075 | Val Loss: 0.502357

Epoch 2896/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00385]
Epoch 2896/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 2896 | Train Loss: 0.022898 | Val Loss: 1.023959

Epoch 2897/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00387]
Epoch 2897/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 2897 | Train Loss: 0.024871 | Val Loss: 0.696403

Epoch 2898/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00305]
Epoch 2898/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.97it/s]

End of Epoch 2898 | Train Loss: 0.023816 | Val Loss: 0.422857

Epoch 2899/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00315]
Epoch 2899/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.37it/s]

End of Epoch 2899 | Train Loss: 0.020914 | Val Loss: 0.675761

Epoch 2900/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00339]
Epoch 2900/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.05it/s]

End of Epoch 2900 | Train Loss: 0.021142 | Val Loss: 0.398987

Epoch 2901/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00311]
Epoch 2901/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.01it/s]

End of Epoch 2901 | Train Loss: 0.020329 | Val Loss: 0.177847

Epoch 2902/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00291]
Epoch 2902/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.03it/s]

End of Epoch 2902 | Train Loss: 0.018136 | Val Loss: 0.478775

Epoch 2903/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00314]
Epoch 2903/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 90.63it/s]

End of Epoch 2903 | Train Loss: 0.020906 | Val Loss: 0.635576

Epoch 2904/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00327]
Epoch 2904/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.13it/s]

End of Epoch 2904 | Train Loss: 0.024924 | Val Loss: 0.361494

Epoch 2905/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00384]
Epoch 2905/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 80.78it/s]

End of Epoch 2905 | Train Loss: 0.029328 | Val Loss: 0.286291

Epoch 2906/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0223]
Epoch 2906/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.94it/s]

End of Epoch 2906 | Train Loss: 0.020527 | Val Loss: 0.493578

Epoch 2907/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00284]
Epoch 2907/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 2907 | Train Loss: 0.020876 | Val Loss: 0.714361

Epoch 2908/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00316]
Epoch 2908/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.00it/s]

End of Epoch 2908 | Train Loss: 0.014669 | Val Loss: 0.642166

Epoch 2909/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0243]
Epoch 2909/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 2909 | Train Loss: 0.019811 | Val Loss: 0.423119

Epoch 2910/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.637]
Epoch 2910/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 2910 | Train Loss: 0.032809 | Val Loss: 0.423176

Epoch 2911/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0145]
Epoch 2911/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 2911 | Train Loss: 0.032739 | Val Loss: 0.569786

Epoch 2912/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00342]
Epoch 2912/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.15it/s]

End of Epoch 2912 | Train Loss: 0.016481 | Val Loss: 0.243399

Epoch 2913/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0224]
Epoch 2913/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.77it/s]

End of Epoch 2913 | Train Loss: 0.018805 | Val Loss: 0.894718

Epoch 2914/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00344]
Epoch 2914/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.55it/s]

End of Epoch 2914 | Train Loss: 0.022991 | Val Loss: 0.663050

Epoch 2915/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0033]
Epoch 2915/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.59it/s]

End of Epoch 2915 | Train Loss: 0.024791 | Val Loss: 0.427050

Epoch 2916/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00798]
Epoch 2916/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.09it/s]

End of Epoch 2916 | Train Loss: 0.025900 | Val Loss: 0.483361

Epoch 2917/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.04]
Epoch 2917/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 2917 | Train Loss: 0.023379 | Val Loss: 0.589845

Epoch 2918/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00374]
Epoch 2918/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.49it/s]

End of Epoch 2918 | Train Loss: 0.019243 | Val Loss: 0.365104

Epoch 2919/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00404]
Epoch 2919/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.59it/s]

End of Epoch 2919 | Train Loss: 0.014729 | Val Loss: 0.591432

Epoch 2920/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00282]
Epoch 2920/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 2920 | Train Loss: 0.020286 | Val Loss: 0.460492

Epoch 2921/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00264]
Epoch 2921/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.70it/s]

End of Epoch 2921 | Train Loss: 0.020108 | Val Loss: 0.520672

Epoch 2922/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0404]
Epoch 2922/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.52it/s]

End of Epoch 2922 | Train Loss: 0.017152 | Val Loss: 0.391841

Epoch 2923/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00593]
Epoch 2923/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.53it/s]

End of Epoch 2923 | Train Loss: 0.021595 | Val Loss: 0.368710

Epoch 2924/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0385]
Epoch 2924/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.21it/s]

End of Epoch 2924 | Train Loss: 0.025502 | Val Loss: 0.409382

Epoch 2925/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00343]
Epoch 2925/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 2925 | Train Loss: 0.016896 | Val Loss: 0.650778

Epoch 2926/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00325]
Epoch 2926/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 2926 | Train Loss: 0.022083 | Val Loss: 0.308006

Epoch 2927/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00232]
Epoch 2927/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 2927 | Train Loss: 0.021487 | Val Loss: 0.792270

Epoch 2928/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00394]
Epoch 2928/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 2928 | Train Loss: 0.019575 | Val Loss: 0.279077

Epoch 2929/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00398]
Epoch 2929/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.75it/s]

End of Epoch 2929 | Train Loss: 0.015117 | Val Loss: 0.465922

Epoch 2930/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00337]
Epoch 2930/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.29it/s]

End of Epoch 2930 | Train Loss: 0.018979 | Val Loss: 0.375306

Epoch 2931/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0154]
Epoch 2931/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.25it/s]

End of Epoch 2931 | Train Loss: 0.020916 | Val Loss: 0.690599

Epoch 2932/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00255]
Epoch 2932/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.92it/s]

End of Epoch 2932 | Train Loss: 0.024567 | Val Loss: 0.349469

Epoch 2933/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00576]
Epoch 2933/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 2933 | Train Loss: 0.018316 | Val Loss: 0.667803

Epoch 2934/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00318]
Epoch 2934/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.98it/s]

End of Epoch 2934 | Train Loss: 0.016785 | Val Loss: 0.389900

Epoch 2935/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00461]
Epoch 2935/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.05it/s]

End of Epoch 2935 | Train Loss: 0.026594 | Val Loss: 0.627295

Epoch 2936/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00351]
Epoch 2936/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 2936 | Train Loss: 0.022289 | Val Loss: 0.465569

Epoch 2937/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0163]
Epoch 2937/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 2937 | Train Loss: 0.017656 | Val Loss: 0.438296

Epoch 2938/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0115]
Epoch 2938/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.56it/s]

End of Epoch 2938 | Train Loss: 0.021554 | Val Loss: 0.527952

Epoch 2939/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00281]
Epoch 2939/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.53it/s]

End of Epoch 2939 | Train Loss: 0.021221 | Val Loss: 0.619475

Epoch 2940/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00493]
Epoch 2940/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.34it/s]

End of Epoch 2940 | Train Loss: 0.026455 | Val Loss: 0.479780

Epoch 2941/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0101]
Epoch 2941/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 2941 | Train Loss: 0.019573 | Val Loss: 0.446349

Epoch 2942/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00456]
Epoch 2942/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.31it/s]

End of Epoch 2942 | Train Loss: 0.014249 | Val Loss: 0.420861

Epoch 2943/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00296]
Epoch 2943/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 2943 | Train Loss: 0.021800 | Val Loss: 0.202484

Epoch 2944/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00735]
Epoch 2944/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.45it/s]

End of Epoch 2944 | Train Loss: 0.015877 | Val Loss: 0.174239

Epoch 2945/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00437]
Epoch 2945/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 2945 | Train Loss: 0.017822 | Val Loss: 0.819803

Epoch 2946/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0211]
Epoch 2946/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.55it/s]

End of Epoch 2946 | Train Loss: 0.018805 | Val Loss: 0.342004

Epoch 2947/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00327]
Epoch 2947/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 2947 | Train Loss: 0.023661 | Val Loss: 0.558364

Epoch 2948/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.00287]
Epoch 2948/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 2948 | Train Loss: 0.028035 | Val Loss: 0.949339

Epoch 2949/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0598]
Epoch 2949/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.83it/s]

End of Epoch 2949 | Train Loss: 0.025925 | Val Loss: 0.350280

Epoch 2950/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0721]
Epoch 2950/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 2950 | Train Loss: 0.024529 | Val Loss: 0.356615

Epoch 2951/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.395]
Epoch 2951/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.73it/s]

End of Epoch 2951 | Train Loss: 0.028971 | Val Loss: 0.545621

Epoch 2952/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00326]
Epoch 2952/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 2952 | Train Loss: 0.025365 | Val Loss: 0.350275

Epoch 2953/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00439]
Epoch 2953/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.21it/s]

End of Epoch 2953 | Train Loss: 0.014591 | Val Loss: 0.468585

Epoch 2954/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.964]
Epoch 2954/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 2954 | Train Loss: 0.029050 | Val Loss: 0.288260

Epoch 2955/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.304]
Epoch 2955/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.85it/s]

End of Epoch 2955 | Train Loss: 0.030976 | Val Loss: 0.897129

Epoch 2956/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00344]
Epoch 2956/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.85it/s]

End of Epoch 2956 | Train Loss: 0.030708 | Val Loss: 0.705158

Epoch 2957/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00638]
Epoch 2957/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 2957 | Train Loss: 0.026527 | Val Loss: 0.749056

Epoch 2958/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00443]
Epoch 2958/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.01it/s]

End of Epoch 2958 | Train Loss: 0.021221 | Val Loss: 0.504748

Epoch 2959/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00364]
Epoch 2959/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.14it/s]

End of Epoch 2959 | Train Loss: 0.017850 | Val Loss: 0.569364

Epoch 2960/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.467]
Epoch 2960/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 2960 | Train Loss: 0.022460 | Val Loss: 0.562684

Epoch 2961/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00355]
Epoch 2961/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 2961 | Train Loss: 0.028564 | Val Loss: 0.337469

Epoch 2962/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00441]
Epoch 2962/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.18it/s]

End of Epoch 2962 | Train Loss: 0.017771 | Val Loss: 0.408992

Epoch 2963/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00392]
Epoch 2963/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.87it/s]

End of Epoch 2963 | Train Loss: 0.020635 | Val Loss: 0.797622

Epoch 2964/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00354]
Epoch 2964/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.61it/s]

End of Epoch 2964 | Train Loss: 0.023087 | Val Loss: 0.315384

Epoch 2965/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00446]
Epoch 2965/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 2965 | Train Loss: 0.018062 | Val Loss: 0.590955

Epoch 2966/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00272]
Epoch 2966/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.94it/s]

End of Epoch 2966 | Train Loss: 0.022889 | Val Loss: 0.624399

Epoch 2967/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00328]
Epoch 2967/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.59it/s]

End of Epoch 2967 | Train Loss: 0.020278 | Val Loss: 0.375086

Epoch 2968/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.475]
Epoch 2968/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.55it/s]

End of Epoch 2968 | Train Loss: 0.026589 | Val Loss: 0.506292

Epoch 2969/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00432]
Epoch 2969/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 2969 | Train Loss: 0.034532 | Val Loss: 0.702155

Epoch 2970/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00243]
Epoch 2970/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 2970 | Train Loss: 0.016924 | Val Loss: 0.273896

Epoch 2971/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00241]
Epoch 2971/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.84it/s]

End of Epoch 2971 | Train Loss: 0.021997 | Val Loss: 0.480220

Epoch 2972/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00307]
Epoch 2972/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.61it/s]

End of Epoch 2972 | Train Loss: 0.016884 | Val Loss: 0.679145

Epoch 2973/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.023]
Epoch 2973/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.96it/s]

End of Epoch 2973 | Train Loss: 0.023048 | Val Loss: 0.513021

Epoch 2974/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00267]
Epoch 2974/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.69it/s]

End of Epoch 2974 | Train Loss: 0.020341 | Val Loss: 0.431682

Epoch 2975/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00361]
Epoch 2975/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 2975 | Train Loss: 0.023316 | Val Loss: 0.596883

Epoch 2976/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00763]
Epoch 2976/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.57it/s]

End of Epoch 2976 | Train Loss: 0.019635 | Val Loss: 0.578993

Epoch 2977/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0035]
Epoch 2977/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.04it/s]

End of Epoch 2977 | Train Loss: 0.022277 | Val Loss: 0.390150

Epoch 2978/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.36]
Epoch 2978/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.91it/s]

End of Epoch 2978 | Train Loss: 0.022008 | Val Loss: 0.560930

Epoch 2979/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00533]
Epoch 2979/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.49it/s]

End of Epoch 2979 | Train Loss: 0.031107 | Val Loss: 0.463344

Epoch 2980/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0035]
Epoch 2980/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 2980 | Train Loss: 0.019734 | Val Loss: 0.332555

Epoch 2981/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.11]
Epoch 2981/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 2981 | Train Loss: 0.021792 | Val Loss: 0.712516

Epoch 2982/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0359]
Epoch 2982/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 2982 | Train Loss: 0.024137 | Val Loss: 0.206132

Epoch 2983/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0122]
Epoch 2983/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 2983 | Train Loss: 0.018780 | Val Loss: 0.243680

Epoch 2984/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00398]
Epoch 2984/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.96it/s]

End of Epoch 2984 | Train Loss: 0.020438 | Val Loss: 0.342245

Epoch 2985/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00341]
Epoch 2985/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.81it/s]

End of Epoch 2985 | Train Loss: 0.022017 | Val Loss: 0.316629

Epoch 2986/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00276]
Epoch 2986/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.84it/s]

End of Epoch 2986 | Train Loss: 0.014970 | Val Loss: 0.820809

Epoch 2987/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00335]
Epoch 2987/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.73it/s]

End of Epoch 2987 | Train Loss: 0.020347 | Val Loss: 0.848556

Epoch 2988/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00444]
Epoch 2988/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.80it/s]

End of Epoch 2988 | Train Loss: 0.025933 | Val Loss: 0.238046

Epoch 2989/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0282]
Epoch 2989/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.10it/s]

End of Epoch 2989 | Train Loss: 0.025414 | Val Loss: 0.475053

Epoch 2990/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0831]
Epoch 2990/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.82it/s]

End of Epoch 2990 | Train Loss: 0.017221 | Val Loss: 0.737969

Epoch 2991/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0129]
Epoch 2991/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.51it/s]

End of Epoch 2991 | Train Loss: 0.020741 | Val Loss: 0.238255

Epoch 2992/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00513]
Epoch 2992/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.03it/s]

End of Epoch 2992 | Train Loss: 0.025159 | Val Loss: 0.400447

Epoch 2993/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00421]
Epoch 2993/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 2993 | Train Loss: 0.022931 | Val Loss: 0.989398

Epoch 2994/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0181]
Epoch 2994/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 2994 | Train Loss: 0.021935 | Val Loss: 0.200117

Epoch 2995/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00588]
Epoch 2995/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.58it/s]

End of Epoch 2995 | Train Loss: 0.019264 | Val Loss: 0.648283

Epoch 2996/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00377]
Epoch 2996/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 2996 | Train Loss: 0.027847 | Val Loss: 0.667031

Epoch 2997/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00296]
Epoch 2997/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 2997 | Train Loss: 0.028054 | Val Loss: 0.229027

Epoch 2998/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0064]
Epoch 2998/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.08it/s]

End of Epoch 2998 | Train Loss: 0.022056 | Val Loss: 0.217569

Epoch 2999/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0024]
Epoch 2999/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 2999 | Train Loss: 0.025259 | Val Loss: 0.240943

Epoch 3000/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00221]
Epoch 3000/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.01it/s]

End of Epoch 3000 | Train Loss: 0.020262 | Val Loss: 0.591800

Epoch 3001/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00582]
Epoch 3001/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 3001 | Train Loss: 0.025077 | Val Loss: 0.434443

Epoch 3002/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0062]
Epoch 3002/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.09it/s]

End of Epoch 3002 | Train Loss: 0.022653 | Val Loss: 0.492453

Epoch 3003/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00237]
Epoch 3003/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.45it/s]

End of Epoch 3003 | Train Loss: 0.018149 | Val Loss: 0.301424

Epoch 3004/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00825]
Epoch 3004/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 3004 | Train Loss: 0.019022 | Val Loss: 0.375926

Epoch 3005/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00873]
Epoch 3005/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 3005 | Train Loss: 0.021554 | Val Loss: 0.394854

Epoch 3006/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00358]
Epoch 3006/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.36it/s]

End of Epoch 3006 | Train Loss: 0.016109 | Val Loss: 0.275755

Epoch 3007/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00214]
Epoch 3007/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 3007 | Train Loss: 0.016637 | Val Loss: 0.241861

Epoch 3008/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.34it/s, loss=0.00466]
Epoch 3008/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 3008 | Train Loss: 0.023515 | Val Loss: 0.623857

Epoch 3009/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0132]
Epoch 3009/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 3009 | Train Loss: 0.026316 | Val Loss: 0.313879

Epoch 3010/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00259]
Epoch 3010/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 3010 | Train Loss: 0.017059 | Val Loss: 0.540484

Epoch 3011/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00573]
Epoch 3011/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.75it/s]

End of Epoch 3011 | Train Loss: 0.020905 | Val Loss: 0.385374

Epoch 3012/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00657]
Epoch 3012/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.46it/s]

End of Epoch 3012 | Train Loss: 0.019671 | Val Loss: 0.514494

Epoch 3013/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0042]
Epoch 3013/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.90it/s]

End of Epoch 3013 | Train Loss: 0.029388 | Val Loss: 0.363724

Epoch 3014/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0142]
Epoch 3014/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.70it/s]

End of Epoch 3014 | Train Loss: 0.024037 | Val Loss: 0.851853

Epoch 3015/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00305]
Epoch 3015/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.51it/s]

End of Epoch 3015 | Train Loss: 0.021740 | Val Loss: 0.803063

Epoch 3016/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00319]
Epoch 3016/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.73it/s]

End of Epoch 3016 | Train Loss: 0.015964 | Val Loss: 0.276630

Epoch 3017/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00268]
Epoch 3017/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.49it/s]

End of Epoch 3017 | Train Loss: 0.016757 | Val Loss: 0.592565

Epoch 3018/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00345]
Epoch 3018/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.15it/s]

End of Epoch 3018 | Train Loss: 0.020000 | Val Loss: 0.665442

Epoch 3019/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0156]
Epoch 3019/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.97it/s]

End of Epoch 3019 | Train Loss: 0.021726 | Val Loss: 0.319123

Epoch 3020/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.116]
Epoch 3020/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.14it/s]

End of Epoch 3020 | Train Loss: 0.016749 | Val Loss: 0.413308

Epoch 3021/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0034]
Epoch 3021/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.39it/s]

End of Epoch 3021 | Train Loss: 0.018474 | Val Loss: 0.569417

Epoch 3022/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00369]
Epoch 3022/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.25it/s]

End of Epoch 3022 | Train Loss: 0.018062 | Val Loss: 0.385715

Epoch 3023/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00324]
Epoch 3023/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 3023 | Train Loss: 0.017541 | Val Loss: 0.505467

Epoch 3024/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0962]
Epoch 3024/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 3024 | Train Loss: 0.022169 | Val Loss: 0.556574

Epoch 3025/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00429]
Epoch 3025/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.50it/s]

End of Epoch 3025 | Train Loss: 0.019713 | Val Loss: 0.399126

Epoch 3026/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00282]
Epoch 3026/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 3026 | Train Loss: 0.020465 | Val Loss: 0.413030

Epoch 3027/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00428]
Epoch 3027/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.67it/s]

End of Epoch 3027 | Train Loss: 0.018771 | Val Loss: 0.519878

Epoch 3028/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.45it/s, loss=0.0157]
Epoch 3028/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.58it/s]

End of Epoch 3028 | Train Loss: 0.017471 | Val Loss: 0.711666

Epoch 3029/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00226]
Epoch 3029/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 3029 | Train Loss: 0.014088 | Val Loss: 0.446810

Epoch 3030/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0046]
Epoch 3030/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.15it/s]

End of Epoch 3030 | Train Loss: 0.019255 | Val Loss: 0.279490

Epoch 3031/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00347]
Epoch 3031/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.51it/s]

End of Epoch 3031 | Train Loss: 0.022699 | Val Loss: 0.977683

Epoch 3032/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00234]
Epoch 3032/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.33it/s]

End of Epoch 3032 | Train Loss: 0.020852 | Val Loss: 0.354871

Epoch 3033/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00276]
Epoch 3033/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.42it/s]

End of Epoch 3033 | Train Loss: 0.020666 | Val Loss: 0.729710

Epoch 3034/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00364]
Epoch 3034/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.27it/s]

End of Epoch 3034 | Train Loss: 0.022784 | Val Loss: 0.919210

Epoch 3035/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00246]
Epoch 3035/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.73it/s]

End of Epoch 3035 | Train Loss: 0.021462 | Val Loss: 0.470500

Epoch 3036/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0028]
Epoch 3036/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.51it/s]

End of Epoch 3036 | Train Loss: 0.020864 | Val Loss: 0.321464

Epoch 3037/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00221]
Epoch 3037/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 3037 | Train Loss: 0.020267 | Val Loss: 0.583363

Epoch 3038/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00267]
Epoch 3038/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.08it/s]

End of Epoch 3038 | Train Loss: 0.018920 | Val Loss: 0.300311

Epoch 3039/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00448]
Epoch 3039/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.89it/s]

End of Epoch 3039 | Train Loss: 0.016278 | Val Loss: 0.514506

Epoch 3040/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.144]
Epoch 3040/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 3040 | Train Loss: 0.021882 | Val Loss: 0.628432

Epoch 3041/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00702]
Epoch 3041/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.31it/s]

End of Epoch 3041 | Train Loss: 0.024771 | Val Loss: 0.470948

Epoch 3042/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00697]
Epoch 3042/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.34it/s]

End of Epoch 3042 | Train Loss: 0.017766 | Val Loss: 0.262581

Epoch 3043/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00481]
Epoch 3043/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 3043 | Train Loss: 0.018132 | Val Loss: 0.434644

Epoch 3044/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00314]
Epoch 3044/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.35it/s]

End of Epoch 3044 | Train Loss: 0.017226 | Val Loss: 0.407272

Epoch 3045/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0177]
Epoch 3045/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.84it/s]

End of Epoch 3045 | Train Loss: 0.018268 | Val Loss: 0.342568

Epoch 3046/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00559]
Epoch 3046/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 3046 | Train Loss: 0.016429 | Val Loss: 0.458748

Epoch 3047/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00259]
Epoch 3047/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.19it/s]

End of Epoch 3047 | Train Loss: 0.012138 | Val Loss: 0.309271

Epoch 3048/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.00345]
Epoch 3048/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.28it/s]

End of Epoch 3048 | Train Loss: 0.021027 | Val Loss: 0.258133

Epoch 3049/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0511]
Epoch 3049/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.65it/s]

End of Epoch 3049 | Train Loss: 0.025882 | Val Loss: 0.694329

Epoch 3050/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00271]
Epoch 3050/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.94it/s]

End of Epoch 3050 | Train Loss: 0.021298 | Val Loss: 0.787496

Epoch 3051/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00351]
Epoch 3051/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 3051 | Train Loss: 0.021689 | Val Loss: 0.427337

Epoch 3052/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00278]
Epoch 3052/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.47it/s]

End of Epoch 3052 | Train Loss: 0.023241 | Val Loss: 0.452200

Epoch 3053/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0115]
Epoch 3053/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.41it/s]

End of Epoch 3053 | Train Loss: 0.025553 | Val Loss: 0.252447

Epoch 3054/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00409]
Epoch 3054/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.58it/s]

End of Epoch 3054 | Train Loss: 0.021889 | Val Loss: 0.612538

Epoch 3055/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00345]
Epoch 3055/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.46it/s]

End of Epoch 3055 | Train Loss: 0.017025 | Val Loss: 0.719826

Epoch 3056/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00293]
Epoch 3056/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 3056 | Train Loss: 0.019690 | Val Loss: 0.568696

Epoch 3057/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00383]
Epoch 3057/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 3057 | Train Loss: 0.018980 | Val Loss: 0.382966

Epoch 3058/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0258]
Epoch 3058/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 3058 | Train Loss: 0.022366 | Val Loss: 0.348237

Epoch 3059/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00275]
Epoch 3059/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 3059 | Train Loss: 0.016512 | Val Loss: 0.412659

Epoch 3060/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.327]
Epoch 3060/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.20it/s]

End of Epoch 3060 | Train Loss: 0.026132 | Val Loss: 0.328939

Epoch 3061/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00241]
Epoch 3061/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 3061 | Train Loss: 0.024550 | Val Loss: 0.569442

Epoch 3062/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0031]
Epoch 3062/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 3062 | Train Loss: 0.016237 | Val Loss: 0.745836

Epoch 3063/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00352]
Epoch 3063/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.38it/s]

End of Epoch 3063 | Train Loss: 0.019140 | Val Loss: 0.809867

Epoch 3064/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00392]
Epoch 3064/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.31it/s]

End of Epoch 3064 | Train Loss: 0.015360 | Val Loss: 0.368373

Epoch 3065/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00454]
Epoch 3065/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.02it/s]

End of Epoch 3065 | Train Loss: 0.023414 | Val Loss: 0.259765

Epoch 3066/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.0025]
Epoch 3066/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.51it/s]

End of Epoch 3066 | Train Loss: 0.017455 | Val Loss: 0.345939

Epoch 3067/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00254]
Epoch 3067/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.00it/s]

End of Epoch 3067 | Train Loss: 0.024806 | Val Loss: 0.226829

Epoch 3068/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.35it/s, loss=0.00731]
Epoch 3068/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 3068 | Train Loss: 0.017301 | Val Loss: 0.799128

Epoch 3069/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00437]
Epoch 3069/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.68it/s]

End of Epoch 3069 | Train Loss: 0.018629 | Val Loss: 0.343699

Epoch 3070/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00268]
Epoch 3070/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 3070 | Train Loss: 0.017203 | Val Loss: 0.422558

Epoch 3071/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00262]
Epoch 3071/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.55it/s]

End of Epoch 3071 | Train Loss: 0.015700 | Val Loss: 0.436060

Epoch 3072/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0443]
Epoch 3072/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 3072 | Train Loss: 0.021958 | Val Loss: 0.399185

Epoch 3073/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.107]
Epoch 3073/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.65it/s]

End of Epoch 3073 | Train Loss: 0.026196 | Val Loss: 0.437491

Epoch 3074/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.306]
Epoch 3074/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 3074 | Train Loss: 0.030291 | Val Loss: 0.366291

Epoch 3075/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00278]
Epoch 3075/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 3075 | Train Loss: 0.028100 | Val Loss: 0.687946

Epoch 3076/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00314]
Epoch 3076/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.60it/s]

End of Epoch 3076 | Train Loss: 0.023830 | Val Loss: 0.265735

Epoch 3077/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00533]
Epoch 3077/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.27it/s]

End of Epoch 3077 | Train Loss: 0.020564 | Val Loss: 0.431514

Epoch 3078/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00261]
Epoch 3078/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.17it/s]

End of Epoch 3078 | Train Loss: 0.020481 | Val Loss: 0.456231

Epoch 3079/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0298]
Epoch 3079/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 3079 | Train Loss: 0.016439 | Val Loss: 0.676912

Epoch 3080/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00358]
Epoch 3080/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.78it/s]

End of Epoch 3080 | Train Loss: 0.018072 | Val Loss: 0.716467

Epoch 3081/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00401]
Epoch 3081/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.78it/s]

End of Epoch 3081 | Train Loss: 0.023672 | Val Loss: 0.444928

Epoch 3082/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.003]
Epoch 3082/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.57it/s]

End of Epoch 3082 | Train Loss: 0.026941 | Val Loss: 0.680173

Epoch 3083/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0052]
Epoch 3083/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.91it/s]

End of Epoch 3083 | Train Loss: 0.018830 | Val Loss: 0.524361

Epoch 3084/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00271]
Epoch 3084/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.59it/s]

End of Epoch 3084 | Train Loss: 0.021128 | Val Loss: 0.571045

Epoch 3085/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00354]
Epoch 3085/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 3085 | Train Loss: 0.023174 | Val Loss: 0.445975

Epoch 3086/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00486]
Epoch 3086/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.18it/s]

End of Epoch 3086 | Train Loss: 0.020841 | Val Loss: 0.428586

Epoch 3087/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0159]
Epoch 3087/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 3087 | Train Loss: 0.019728 | Val Loss: 0.527233

Epoch 3088/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.41it/s, loss=0.0032]
Epoch 3088/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.01it/s]

End of Epoch 3088 | Train Loss: 0.023368 | Val Loss: 0.761235

Epoch 3089/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00264]
Epoch 3089/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.24it/s]

End of Epoch 3089 | Train Loss: 0.021846 | Val Loss: 0.365503

Epoch 3090/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00272]
Epoch 3090/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.21it/s]

End of Epoch 3090 | Train Loss: 0.023016 | Val Loss: 0.261463

Epoch 3091/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0036]
Epoch 3091/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.81it/s]

End of Epoch 3091 | Train Loss: 0.023712 | Val Loss: 0.437573

Epoch 3092/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00249]
Epoch 3092/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.31it/s]

End of Epoch 3092 | Train Loss: 0.020957 | Val Loss: 0.937379

Epoch 3093/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00306]
Epoch 3093/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.93it/s]

End of Epoch 3093 | Train Loss: 0.019586 | Val Loss: 0.380939

Epoch 3094/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0035]
Epoch 3094/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.93it/s]

End of Epoch 3094 | Train Loss: 0.019922 | Val Loss: 0.429849

Epoch 3095/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00275]
Epoch 3095/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.75it/s]

End of Epoch 3095 | Train Loss: 0.018547 | Val Loss: 0.326445

Epoch 3096/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00315]
Epoch 3096/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 3096 | Train Loss: 0.019777 | Val Loss: 0.403378

Epoch 3097/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0073]
Epoch 3097/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.80it/s]

End of Epoch 3097 | Train Loss: 0.014865 | Val Loss: 0.423140

Epoch 3098/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00457]
Epoch 3098/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 3098 | Train Loss: 0.016858 | Val Loss: 0.609759

Epoch 3099/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.01]
Epoch 3099/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.07it/s]

End of Epoch 3099 | Train Loss: 0.020718 | Val Loss: 0.438656

Epoch 3100/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0099]
Epoch 3100/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.80it/s]

End of Epoch 3100 | Train Loss: 0.024020 | Val Loss: 0.260349

Epoch 3101/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0114]
Epoch 3101/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.53it/s]

End of Epoch 3101 | Train Loss: 0.014871 | Val Loss: 0.441537

Epoch 3102/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.012]
Epoch 3102/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.07it/s]

End of Epoch 3102 | Train Loss: 0.016284 | Val Loss: 0.432795

Epoch 3103/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00397]
Epoch 3103/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.00it/s]

End of Epoch 3103 | Train Loss: 0.020242 | Val Loss: 0.371859

Epoch 3104/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00325]
Epoch 3104/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.33it/s]

End of Epoch 3104 | Train Loss: 0.022620 | Val Loss: 0.761536

Epoch 3105/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00271]
Epoch 3105/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 3105 | Train Loss: 0.026009 | Val Loss: 0.447703

Epoch 3106/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00206]
Epoch 3106/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.90it/s]

End of Epoch 3106 | Train Loss: 0.020009 | Val Loss: 0.625273

Epoch 3107/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00359]
Epoch 3107/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.23it/s]

End of Epoch 3107 | Train Loss: 0.020358 | Val Loss: 0.607241

Epoch 3108/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.49it/s, loss=0.00848]
Epoch 3108/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.46it/s]

End of Epoch 3108 | Train Loss: 0.016970 | Val Loss: 0.685945

Epoch 3109/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.0994]
Epoch 3109/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.63it/s]

End of Epoch 3109 | Train Loss: 0.025675 | Val Loss: 0.218352

Epoch 3110/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.0044]
Epoch 3110/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 3110 | Train Loss: 0.024008 | Val Loss: 0.749191

Epoch 3111/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00474]
Epoch 3111/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.84it/s]

End of Epoch 3111 | Train Loss: 0.023374 | Val Loss: 0.334666

Epoch 3112/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00548]
Epoch 3112/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.03it/s]

End of Epoch 3112 | Train Loss: 0.016275 | Val Loss: 0.330976

Epoch 3113/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00481]
Epoch 3113/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.77it/s]

End of Epoch 3113 | Train Loss: 0.015824 | Val Loss: 0.380210

Epoch 3114/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00295]
Epoch 3114/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 3114 | Train Loss: 0.024172 | Val Loss: 0.465081

Epoch 3115/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.0326]
Epoch 3115/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.39it/s]

End of Epoch 3115 | Train Loss: 0.022457 | Val Loss: 0.365499

Epoch 3116/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00348]
Epoch 3116/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 3116 | Train Loss: 0.019198 | Val Loss: 0.735200

Epoch 3117/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0824]
Epoch 3117/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 3117 | Train Loss: 0.021896 | Val Loss: 0.481323

Epoch 3118/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00633]
Epoch 3118/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.37it/s]

End of Epoch 3118 | Train Loss: 0.024503 | Val Loss: 0.513668

Epoch 3119/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00336]
Epoch 3119/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.26it/s]

End of Epoch 3119 | Train Loss: 0.026757 | Val Loss: 0.588893

Epoch 3120/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00217]
Epoch 3120/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.37it/s]

End of Epoch 3120 | Train Loss: 0.020239 | Val Loss: 0.435085

Epoch 3121/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00369]
Epoch 3121/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.49it/s]

End of Epoch 3121 | Train Loss: 0.017833 | Val Loss: 0.519935

Epoch 3122/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0122]
Epoch 3122/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.26it/s]

End of Epoch 3122 | Train Loss: 0.015077 | Val Loss: 0.279756

Epoch 3123/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00334]
Epoch 3123/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.43it/s]

End of Epoch 3123 | Train Loss: 0.021861 | Val Loss: 0.323394

Epoch 3124/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0109]
Epoch 3124/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.02it/s]

End of Epoch 3124 | Train Loss: 0.019006 | Val Loss: 0.707103

Epoch 3125/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00483]
Epoch 3125/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.66it/s]

End of Epoch 3125 | Train Loss: 0.012704 | Val Loss: 0.594071

Epoch 3126/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0025]
Epoch 3126/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.10it/s]

End of Epoch 3126 | Train Loss: 0.022973 | Val Loss: 0.239543

Epoch 3127/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00772]
Epoch 3127/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.66it/s]

End of Epoch 3127 | Train Loss: 0.018446 | Val Loss: 0.481486

Epoch 3128/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.30it/s, loss=0.00292]
Epoch 3128/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.08it/s]

End of Epoch 3128 | Train Loss: 0.025380 | Val Loss: 0.385714

Epoch 3129/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00421]
Epoch 3129/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 3129 | Train Loss: 0.019605 | Val Loss: 0.547385

Epoch 3130/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00394]
Epoch 3130/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 3130 | Train Loss: 0.018425 | Val Loss: 0.460891

Epoch 3131/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00819]
Epoch 3131/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 3131 | Train Loss: 0.022217 | Val Loss: 0.514411

Epoch 3132/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.138]
Epoch 3132/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.78it/s]

End of Epoch 3132 | Train Loss: 0.023217 | Val Loss: 0.723997

Epoch 3133/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00527]
Epoch 3133/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.37it/s]

End of Epoch 3133 | Train Loss: 0.030571 | Val Loss: 0.487514

Epoch 3134/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00346]
Epoch 3134/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 3134 | Train Loss: 0.015322 | Val Loss: 0.329959

Epoch 3135/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00591]
Epoch 3135/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 3135 | Train Loss: 0.020448 | Val Loss: 0.426468

Epoch 3136/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00351]
Epoch 3136/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 3136 | Train Loss: 0.018504 | Val Loss: 0.314369

Epoch 3137/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00476]
Epoch 3137/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.26it/s]

End of Epoch 3137 | Train Loss: 0.022758 | Val Loss: 0.405811

Epoch 3138/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00407]
Epoch 3138/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.90it/s]

End of Epoch 3138 | Train Loss: 0.022473 | Val Loss: 0.236639

Epoch 3139/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00324]
Epoch 3139/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.84it/s]

End of Epoch 3139 | Train Loss: 0.019301 | Val Loss: 0.392118

Epoch 3140/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00338]
Epoch 3140/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 3140 | Train Loss: 0.019038 | Val Loss: 0.282784

Epoch 3141/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00253]
Epoch 3141/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.62it/s]

End of Epoch 3141 | Train Loss: 0.015376 | Val Loss: 0.400155

Epoch 3142/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0165]
Epoch 3142/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.17it/s]

End of Epoch 3142 | Train Loss: 0.019761 | Val Loss: 0.467933

Epoch 3143/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00853]
Epoch 3143/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 3143 | Train Loss: 0.021019 | Val Loss: 0.611347

Epoch 3144/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00366]
Epoch 3144/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 3144 | Train Loss: 0.020617 | Val Loss: 0.750351

Epoch 3145/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.0021]
Epoch 3145/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 3145 | Train Loss: 0.024924 | Val Loss: 0.313537

Epoch 3146/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00431]
Epoch 3146/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.73it/s]

End of Epoch 3146 | Train Loss: 0.020197 | Val Loss: 0.295459

Epoch 3147/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00343]
Epoch 3147/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.39it/s]

End of Epoch 3147 | Train Loss: 0.022583 | Val Loss: 0.415513

Epoch 3148/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.32it/s, loss=0.00389]
Epoch 3148/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.73it/s]

End of Epoch 3148 | Train Loss: 0.018400 | Val Loss: 1.051618

Epoch 3149/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00233]
Epoch 3149/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.52it/s]

End of Epoch 3149 | Train Loss: 0.021607 | Val Loss: 0.528797

Epoch 3150/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00455]
Epoch 3150/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.06it/s]

End of Epoch 3150 | Train Loss: 0.017387 | Val Loss: 0.533444

Epoch 3151/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00246]
Epoch 3151/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.24it/s]

End of Epoch 3151 | Train Loss: 0.018111 | Val Loss: 0.543422

Epoch 3152/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0727]
Epoch 3152/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.13it/s]

End of Epoch 3152 | Train Loss: 0.021508 | Val Loss: 0.667931

Epoch 3153/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00545]
Epoch 3153/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.44it/s]

End of Epoch 3153 | Train Loss: 0.019718 | Val Loss: 0.616817

Epoch 3154/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00501]
Epoch 3154/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.04it/s]

End of Epoch 3154 | Train Loss: 0.022024 | Val Loss: 0.348807

Epoch 3155/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00225]
Epoch 3155/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 3155 | Train Loss: 0.019511 | Val Loss: 0.310655

Epoch 3156/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.015]
Epoch 3156/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.10it/s]

End of Epoch 3156 | Train Loss: 0.024120 | Val Loss: 0.256066

Epoch 3157/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00263]
Epoch 3157/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 3157 | Train Loss: 0.016161 | Val Loss: 0.583549

Epoch 3158/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00301]
Epoch 3158/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.76it/s]

End of Epoch 3158 | Train Loss: 0.018863 | Val Loss: 0.416899

Epoch 3159/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00473]
Epoch 3159/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.72it/s]

End of Epoch 3159 | Train Loss: 0.021487 | Val Loss: 0.338970

Epoch 3160/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00219]
Epoch 3160/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.26it/s]

End of Epoch 3160 | Train Loss: 0.020057 | Val Loss: 0.267550

Epoch 3161/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00549]
Epoch 3161/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.07it/s]

End of Epoch 3161 | Train Loss: 0.021530 | Val Loss: 0.249980

Epoch 3162/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00768]
Epoch 3162/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.48it/s]

End of Epoch 3162 | Train Loss: 0.020001 | Val Loss: 0.378818

Epoch 3163/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00301]
Epoch 3163/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.36it/s]

End of Epoch 3163 | Train Loss: 0.021203 | Val Loss: 0.555283

Epoch 3164/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0421]
Epoch 3164/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 3164 | Train Loss: 0.017815 | Val Loss: 0.351670

Epoch 3165/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00279]
Epoch 3165/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.13it/s]

End of Epoch 3165 | Train Loss: 0.018202 | Val Loss: 0.501262

Epoch 3166/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00837]
Epoch 3166/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.98it/s]

End of Epoch 3166 | Train Loss: 0.022275 | Val Loss: 0.224476

Epoch 3167/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00382]
Epoch 3167/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.64it/s]

End of Epoch 3167 | Train Loss: 0.019109 | Val Loss: 0.430146

Epoch 3168/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.017]
Epoch 3168/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.22it/s]

End of Epoch 3168 | Train Loss: 0.020376 | Val Loss: 0.551536

Epoch 3169/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00275]
Epoch 3169/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.60it/s]

End of Epoch 3169 | Train Loss: 0.020783 | Val Loss: 0.374908

Epoch 3170/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00485]
Epoch 3170/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.53it/s]

End of Epoch 3170 | Train Loss: 0.019205 | Val Loss: 0.396321

Epoch 3171/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00889]
Epoch 3171/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.20it/s]

End of Epoch 3171 | Train Loss: 0.026032 | Val Loss: 0.203098

Epoch 3172/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00469]
Epoch 3172/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 3172 | Train Loss: 0.017447 | Val Loss: 0.825080

Epoch 3173/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00299]
Epoch 3173/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 3173 | Train Loss: 0.020316 | Val Loss: 0.357875

Epoch 3174/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00335]
Epoch 3174/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.69it/s]

End of Epoch 3174 | Train Loss: 0.015577 | Val Loss: 0.304036

Epoch 3175/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00335]
Epoch 3175/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.48it/s]

End of Epoch 3175 | Train Loss: 0.019705 | Val Loss: 0.680761

Epoch 3176/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00515]
Epoch 3176/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.56it/s]

End of Epoch 3176 | Train Loss: 0.014075 | Val Loss: 0.448981

Epoch 3177/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00322]
Epoch 3177/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.17it/s]

End of Epoch 3177 | Train Loss: 0.019366 | Val Loss: 0.448903

Epoch 3178/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00276]
Epoch 3178/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.30it/s]

End of Epoch 3178 | Train Loss: 0.016261 | Val Loss: 0.620782

Epoch 3179/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0187]
Epoch 3179/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 3179 | Train Loss: 0.022959 | Val Loss: 0.626669

Epoch 3180/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00436]
Epoch 3180/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.29it/s]

End of Epoch 3180 | Train Loss: 0.019211 | Val Loss: 0.251901

Epoch 3181/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00557]
Epoch 3181/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.58it/s]

End of Epoch 3181 | Train Loss: 0.018331 | Val Loss: 0.421560

Epoch 3182/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00238]
Epoch 3182/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.71it/s]

End of Epoch 3182 | Train Loss: 0.017483 | Val Loss: 0.473491

Epoch 3183/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00202]
Epoch 3183/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.91it/s]

End of Epoch 3183 | Train Loss: 0.017756 | Val Loss: 0.352031

Epoch 3184/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00292]
Epoch 3184/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 3184 | Train Loss: 0.021794 | Val Loss: 0.743150

Epoch 3185/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00307]
Epoch 3185/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.80it/s]

End of Epoch 3185 | Train Loss: 0.018026 | Val Loss: 1.094714

Epoch 3186/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00532]
Epoch 3186/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.69it/s]

End of Epoch 3186 | Train Loss: 0.021534 | Val Loss: 0.666865

Epoch 3187/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00253]
Epoch 3187/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.69it/s]

End of Epoch 3187 | Train Loss: 0.019259 | Val Loss: 0.531943

Epoch 3188/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.42it/s, loss=0.00369]
Epoch 3188/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 3188 | Train Loss: 0.017452 | Val Loss: 0.397774

Epoch 3189/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00267]
Epoch 3189/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.24it/s]

End of Epoch 3189 | Train Loss: 0.018401 | Val Loss: 0.586832

Epoch 3190/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00407]
Epoch 3190/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 3190 | Train Loss: 0.016277 | Val Loss: 0.718212

Epoch 3191/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0033]
Epoch 3191/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.77it/s]

End of Epoch 3191 | Train Loss: 0.018887 | Val Loss: 0.227989

Epoch 3192/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00363]
Epoch 3192/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.79it/s]

End of Epoch 3192 | Train Loss: 0.020584 | Val Loss: 0.881819

Epoch 3193/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00762]
Epoch 3193/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.73it/s]

End of Epoch 3193 | Train Loss: 0.018076 | Val Loss: 0.721008

Epoch 3194/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0034]
Epoch 3194/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 3194 | Train Loss: 0.019923 | Val Loss: 0.636589

Epoch 3195/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00362]
Epoch 3195/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.52it/s]

End of Epoch 3195 | Train Loss: 0.017586 | Val Loss: 0.786605

Epoch 3196/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00224]
Epoch 3196/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 3196 | Train Loss: 0.017905 | Val Loss: 0.496619

Epoch 3197/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00671]
Epoch 3197/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.23it/s]

End of Epoch 3197 | Train Loss: 0.019326 | Val Loss: 0.293794

Epoch 3198/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00791]
Epoch 3198/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.94it/s]

End of Epoch 3198 | Train Loss: 0.024282 | Val Loss: 0.374925

Epoch 3199/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00371]
Epoch 3199/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.35it/s]

End of Epoch 3199 | Train Loss: 0.022336 | Val Loss: 0.250081

Epoch 3200/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00231]
Epoch 3200/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.82it/s]

End of Epoch 3200 | Train Loss: 0.019614 | Val Loss: 0.681309

Epoch 3201/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00217]
Epoch 3201/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.84it/s]

End of Epoch 3201 | Train Loss: 0.017874 | Val Loss: 0.534537

Epoch 3202/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00325]
Epoch 3202/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.27it/s]

End of Epoch 3202 | Train Loss: 0.019204 | Val Loss: 0.701123

Epoch 3203/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.0032]
Epoch 3203/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.78it/s]

End of Epoch 3203 | Train Loss: 0.015123 | Val Loss: 0.563236

Epoch 3204/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.0437]
Epoch 3204/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.15it/s]

End of Epoch 3204 | Train Loss: 0.022017 | Val Loss: 0.272203

Epoch 3205/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0308]
Epoch 3205/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 3205 | Train Loss: 0.015907 | Val Loss: 0.871983

Epoch 3206/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00346]
Epoch 3206/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 90.29it/s]

End of Epoch 3206 | Train Loss: 0.026159 | Val Loss: 0.524090

Epoch 3207/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0038]
Epoch 3207/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.92it/s]

End of Epoch 3207 | Train Loss: 0.020211 | Val Loss: 0.410625

Epoch 3208/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00314]
Epoch 3208/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.19it/s]

End of Epoch 3208 | Train Loss: 0.018143 | Val Loss: 0.452713

Epoch 3209/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00492]
Epoch 3209/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 3209 | Train Loss: 0.021764 | Val Loss: 0.260658

Epoch 3210/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00289]
Epoch 3210/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.28it/s]

End of Epoch 3210 | Train Loss: 0.020205 | Val Loss: 0.514162

Epoch 3211/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.003]
Epoch 3211/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.72it/s]

End of Epoch 3211 | Train Loss: 0.023122 | Val Loss: 0.281326

Epoch 3212/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00188]
Epoch 3212/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.93it/s]

End of Epoch 3212 | Train Loss: 0.021223 | Val Loss: 0.709763

Epoch 3213/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00318]
Epoch 3213/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.55it/s]

End of Epoch 3213 | Train Loss: 0.017822 | Val Loss: 0.401861

Epoch 3214/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00273]
Epoch 3214/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.71it/s]

End of Epoch 3214 | Train Loss: 0.018257 | Val Loss: 0.286422

Epoch 3215/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00348]
Epoch 3215/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 3215 | Train Loss: 0.019749 | Val Loss: 0.451522

Epoch 3216/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0186]
Epoch 3216/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.07it/s]

End of Epoch 3216 | Train Loss: 0.021559 | Val Loss: 0.744952

Epoch 3217/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0663]
Epoch 3217/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 3217 | Train Loss: 0.023853 | Val Loss: 0.514577

Epoch 3218/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.154]
Epoch 3218/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 3218 | Train Loss: 0.022657 | Val Loss: 0.555470

Epoch 3219/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00287]
Epoch 3219/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.11it/s]

End of Epoch 3219 | Train Loss: 0.021607 | Val Loss: 0.513233

Epoch 3220/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00805]
Epoch 3220/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.66it/s]

End of Epoch 3220 | Train Loss: 0.019574 | Val Loss: 0.273610

Epoch 3221/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.02]
Epoch 3221/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.63it/s]

End of Epoch 3221 | Train Loss: 0.021873 | Val Loss: 0.298050

Epoch 3222/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00369]
Epoch 3222/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.63it/s]

End of Epoch 3222 | Train Loss: 0.024891 | Val Loss: 0.307122

Epoch 3223/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00449]
Epoch 3223/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.11it/s]

End of Epoch 3223 | Train Loss: 0.023010 | Val Loss: 0.363282

Epoch 3224/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00731]
Epoch 3224/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.62it/s]

End of Epoch 3224 | Train Loss: 0.026010 | Val Loss: 0.172962

Epoch 3225/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0183]
Epoch 3225/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.79it/s]

End of Epoch 3225 | Train Loss: 0.017775 | Val Loss: 0.518339

Epoch 3226/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00291]
Epoch 3226/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 3226 | Train Loss: 0.018237 | Val Loss: 0.563857

Epoch 3227/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00397]
Epoch 3227/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.74it/s]

End of Epoch 3227 | Train Loss: 0.020504 | Val Loss: 0.471188

Epoch 3228/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.0225]
Epoch 3228/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.54it/s]

End of Epoch 3228 | Train Loss: 0.024727 | Val Loss: 0.769027

Epoch 3229/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00261]
Epoch 3229/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.84it/s]

End of Epoch 3229 | Train Loss: 0.016932 | Val Loss: 0.344101

Epoch 3230/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.287]
Epoch 3230/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 3230 | Train Loss: 0.017673 | Val Loss: 0.471419

Epoch 3231/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00354]
Epoch 3231/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 3231 | Train Loss: 0.027504 | Val Loss: 0.625542

Epoch 3232/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00226]
Epoch 3232/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.92it/s]

End of Epoch 3232 | Train Loss: 0.013849 | Val Loss: 0.430752

Epoch 3233/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00299]
Epoch 3233/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.11it/s]

End of Epoch 3233 | Train Loss: 0.013491 | Val Loss: 0.279528

Epoch 3234/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00324]
Epoch 3234/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 3234 | Train Loss: 0.018183 | Val Loss: 0.309749

Epoch 3235/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0072]
Epoch 3235/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.55it/s]

End of Epoch 3235 | Train Loss: 0.017637 | Val Loss: 0.885020

Epoch 3236/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00431]
Epoch 3236/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 3236 | Train Loss: 0.016716 | Val Loss: 0.580601

Epoch 3237/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0933]
Epoch 3237/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 3237 | Train Loss: 0.019964 | Val Loss: 0.484219

Epoch 3238/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00554]
Epoch 3238/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.48it/s]

End of Epoch 3238 | Train Loss: 0.019453 | Val Loss: 0.296539

Epoch 3239/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00244]
Epoch 3239/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 3239 | Train Loss: 0.017405 | Val Loss: 0.414176

Epoch 3240/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00293]
Epoch 3240/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.64it/s]

End of Epoch 3240 | Train Loss: 0.020704 | Val Loss: 0.482405

Epoch 3241/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00293]
Epoch 3241/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.26it/s]

End of Epoch 3241 | Train Loss: 0.024826 | Val Loss: 0.536510

Epoch 3242/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0163]
Epoch 3242/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.15it/s]

End of Epoch 3242 | Train Loss: 0.016248 | Val Loss: 0.284759

Epoch 3243/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00298]
Epoch 3243/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.88it/s]

End of Epoch 3243 | Train Loss: 0.021327 | Val Loss: 0.269969

Epoch 3244/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00348]
Epoch 3244/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 3244 | Train Loss: 0.016206 | Val Loss: 0.445381

Epoch 3245/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00307]
Epoch 3245/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 3245 | Train Loss: 0.013289 | Val Loss: 0.630479

Epoch 3246/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00262]
Epoch 3246/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.72it/s]

End of Epoch 3246 | Train Loss: 0.019739 | Val Loss: 0.423940

Epoch 3247/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.0137]
Epoch 3247/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.75it/s]

End of Epoch 3247 | Train Loss: 0.019838 | Val Loss: 0.642730

Epoch 3248/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00277]
Epoch 3248/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.72it/s]

End of Epoch 3248 | Train Loss: 0.017871 | Val Loss: 0.257159

Epoch 3249/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.30it/s, loss=0.00524]
Epoch 3249/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.28it/s]

End of Epoch 3249 | Train Loss: 0.018052 | Val Loss: 0.517288

Epoch 3250/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0027]
Epoch 3250/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.86it/s]

End of Epoch 3250 | Train Loss: 0.023517 | Val Loss: 0.277450

Epoch 3251/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00316]
Epoch 3251/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 3251 | Train Loss: 0.022936 | Val Loss: 0.526513

Epoch 3252/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0048]
Epoch 3252/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 3252 | Train Loss: 0.020669 | Val Loss: 0.408591

Epoch 3253/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00229]
Epoch 3253/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.08it/s]

End of Epoch 3253 | Train Loss: 0.020708 | Val Loss: 0.485561

Epoch 3254/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00565]
Epoch 3254/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.52it/s]

End of Epoch 3254 | Train Loss: 0.018382 | Val Loss: 0.191592

Epoch 3255/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00515]
Epoch 3255/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.48it/s]

End of Epoch 3255 | Train Loss: 0.015617 | Val Loss: 0.717088

Epoch 3256/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0191]
Epoch 3256/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.12it/s]

End of Epoch 3256 | Train Loss: 0.021461 | Val Loss: 0.458669

Epoch 3257/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0498]
Epoch 3257/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.50it/s]

End of Epoch 3257 | Train Loss: 0.018114 | Val Loss: 0.871425

Epoch 3258/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00334]
Epoch 3258/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.78it/s]

End of Epoch 3258 | Train Loss: 0.016930 | Val Loss: 0.789941

Epoch 3259/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00545]
Epoch 3259/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 3259 | Train Loss: 0.018733 | Val Loss: 0.723653

Epoch 3260/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.133]
Epoch 3260/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.03it/s]

End of Epoch 3260 | Train Loss: 0.020391 | Val Loss: 0.628891

Epoch 3261/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00663]
Epoch 3261/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.26it/s]

End of Epoch 3261 | Train Loss: 0.018342 | Val Loss: 0.452790

Epoch 3262/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00322]
Epoch 3262/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 3262 | Train Loss: 0.020833 | Val Loss: 0.463531

Epoch 3263/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0691]
Epoch 3263/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.38it/s]

End of Epoch 3263 | Train Loss: 0.020257 | Val Loss: 0.528848

Epoch 3264/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00237]
Epoch 3264/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.25it/s]

End of Epoch 3264 | Train Loss: 0.020324 | Val Loss: 0.405901

Epoch 3265/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00389]
Epoch 3265/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.95it/s]

End of Epoch 3265 | Train Loss: 0.018130 | Val Loss: 0.728884

Epoch 3266/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00316]
Epoch 3266/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 3266 | Train Loss: 0.020252 | Val Loss: 0.367380

Epoch 3267/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0273]
Epoch 3267/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.74it/s]

End of Epoch 3267 | Train Loss: 0.016360 | Val Loss: 0.262970

Epoch 3268/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.00256]
Epoch 3268/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.49it/s]

End of Epoch 3268 | Train Loss: 0.024578 | Val Loss: 0.210801

Epoch 3269/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00287]
Epoch 3269/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.21it/s]

End of Epoch 3269 | Train Loss: 0.022411 | Val Loss: 0.771602

Epoch 3270/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0336]
Epoch 3270/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.96it/s]

End of Epoch 3270 | Train Loss: 0.023112 | Val Loss: 0.525006

Epoch 3271/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00547]
Epoch 3271/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.96it/s]

End of Epoch 3271 | Train Loss: 0.024853 | Val Loss: 0.753087

Epoch 3272/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00199]
Epoch 3272/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.99it/s]

End of Epoch 3272 | Train Loss: 0.015590 | Val Loss: 0.384708

Epoch 3273/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00801]
Epoch 3273/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 3273 | Train Loss: 0.017856 | Val Loss: 0.754285

Epoch 3274/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00219]
Epoch 3274/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.55it/s]

End of Epoch 3274 | Train Loss: 0.013759 | Val Loss: 0.410747

Epoch 3275/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.02]
Epoch 3275/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.06it/s]

End of Epoch 3275 | Train Loss: 0.017701 | Val Loss: 0.433278

Epoch 3276/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00456]
Epoch 3276/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.22it/s]

End of Epoch 3276 | Train Loss: 0.016097 | Val Loss: 0.413894

Epoch 3277/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.738]
Epoch 3277/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.66it/s]

End of Epoch 3277 | Train Loss: 0.027506 | Val Loss: 0.625599

Epoch 3278/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00321]
Epoch 3278/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.30it/s]

End of Epoch 3278 | Train Loss: 0.027103 | Val Loss: 0.281645

Epoch 3279/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00225]
Epoch 3279/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.17it/s]

End of Epoch 3279 | Train Loss: 0.016636 | Val Loss: 0.481912

Epoch 3280/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00287]
Epoch 3280/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.14it/s]

End of Epoch 3280 | Train Loss: 0.018730 | Val Loss: 0.624908

Epoch 3281/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0258]
Epoch 3281/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 3281 | Train Loss: 0.025398 | Val Loss: 0.593439

Epoch 3282/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0025]
Epoch 3282/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 3282 | Train Loss: 0.018111 | Val Loss: 0.674174

Epoch 3283/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.26it/s, loss=0.0102]
Epoch 3283/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 3283 | Train Loss: 0.021151 | Val Loss: 0.447503

Epoch 3284/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00275]
Epoch 3284/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 3284 | Train Loss: 0.024910 | Val Loss: 0.293182

Epoch 3285/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.455]
Epoch 3285/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 3285 | Train Loss: 0.022489 | Val Loss: 0.360067

Epoch 3286/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0044]
Epoch 3286/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.36it/s]

End of Epoch 3286 | Train Loss: 0.027073 | Val Loss: 0.430575

Epoch 3287/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.0047]
Epoch 3287/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.40it/s]

End of Epoch 3287 | Train Loss: 0.023114 | Val Loss: 0.481159

Epoch 3288/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0119]
Epoch 3288/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.68it/s]

End of Epoch 3288 | Train Loss: 0.016205 | Val Loss: 0.348846

Epoch 3289/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.0038]
Epoch 3289/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.92it/s]

End of Epoch 3289 | Train Loss: 0.015287 | Val Loss: 0.359462

Epoch 3290/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0074]
Epoch 3290/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 3290 | Train Loss: 0.019215 | Val Loss: 0.602254

Epoch 3291/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00348]
Epoch 3291/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.13it/s]

End of Epoch 3291 | Train Loss: 0.020683 | Val Loss: 0.392929

Epoch 3292/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00252]
Epoch 3292/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.51it/s]

End of Epoch 3292 | Train Loss: 0.019286 | Val Loss: 0.346209

Epoch 3293/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00302]
Epoch 3293/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.83it/s]

End of Epoch 3293 | Train Loss: 0.017326 | Val Loss: 0.477122

Epoch 3294/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00275]
Epoch 3294/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 3294 | Train Loss: 0.017671 | Val Loss: 0.379057

Epoch 3295/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00378]
Epoch 3295/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.42it/s]

End of Epoch 3295 | Train Loss: 0.018690 | Val Loss: 0.397932

Epoch 3296/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00331]
Epoch 3296/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 3296 | Train Loss: 0.015211 | Val Loss: 0.720146

Epoch 3297/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00291]
Epoch 3297/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.27it/s]

End of Epoch 3297 | Train Loss: 0.016833 | Val Loss: 0.518790

Epoch 3298/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00271]
Epoch 3298/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 3298 | Train Loss: 0.021036 | Val Loss: 0.372438

Epoch 3299/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00239]
Epoch 3299/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 3299 | Train Loss: 0.019795 | Val Loss: 0.616785

Epoch 3300/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00289]
Epoch 3300/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.28it/s]

End of Epoch 3300 | Train Loss: 0.017841 | Val Loss: 0.287493

Epoch 3301/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0039]
Epoch 3301/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.11it/s]

End of Epoch 3301 | Train Loss: 0.023121 | Val Loss: 0.260008

Epoch 3302/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00244]
Epoch 3302/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.95it/s]

End of Epoch 3302 | Train Loss: 0.017880 | Val Loss: 0.439254

Epoch 3303/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00242]
Epoch 3303/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 3303 | Train Loss: 0.017228 | Val Loss: 0.269122

Epoch 3304/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.012]
Epoch 3304/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.98it/s]

End of Epoch 3304 | Train Loss: 0.016969 | Val Loss: 0.453380

Epoch 3305/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00283]
Epoch 3305/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.99it/s]

End of Epoch 3305 | Train Loss: 0.022026 | Val Loss: 0.544365

Epoch 3306/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0028]
Epoch 3306/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.03it/s]

End of Epoch 3306 | Train Loss: 0.019244 | Val Loss: 0.471186

Epoch 3307/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00267]
Epoch 3307/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.01it/s]

End of Epoch 3307 | Train Loss: 0.022119 | Val Loss: 0.417004

Epoch 3308/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00341]
Epoch 3308/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 3308 | Train Loss: 0.022691 | Val Loss: 0.546946

Epoch 3309/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.44it/s, loss=0.00402]
Epoch 3309/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.57it/s]

End of Epoch 3309 | Train Loss: 0.019053 | Val Loss: 0.415928

Epoch 3310/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.30it/s, loss=0.0139]
Epoch 3310/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 3310 | Train Loss: 0.019274 | Val Loss: 0.498649

Epoch 3311/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00262]
Epoch 3311/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 3311 | Train Loss: 0.019877 | Val Loss: 0.444873

Epoch 3312/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.193]
Epoch 3312/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.90it/s]

End of Epoch 3312 | Train Loss: 0.022653 | Val Loss: 0.359264

Epoch 3313/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00276]
Epoch 3313/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.35it/s]

End of Epoch 3313 | Train Loss: 0.017248 | Val Loss: 0.873409

Epoch 3314/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00927]
Epoch 3314/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.45it/s]

End of Epoch 3314 | Train Loss: 0.017266 | Val Loss: 0.351966

Epoch 3315/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00307]
Epoch 3315/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 3315 | Train Loss: 0.018250 | Val Loss: 0.367041

Epoch 3316/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00562]
Epoch 3316/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.06it/s]

End of Epoch 3316 | Train Loss: 0.019395 | Val Loss: 0.672836

Epoch 3317/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00366]
Epoch 3317/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.57it/s]

End of Epoch 3317 | Train Loss: 0.027788 | Val Loss: 0.321250

Epoch 3318/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0025]
Epoch 3318/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.86it/s]

End of Epoch 3318 | Train Loss: 0.017305 | Val Loss: 0.319098

Epoch 3319/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0208]
Epoch 3319/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.02it/s]

End of Epoch 3319 | Train Loss: 0.018914 | Val Loss: 0.424614

Epoch 3320/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00344]
Epoch 3320/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.46it/s]

End of Epoch 3320 | Train Loss: 0.016332 | Val Loss: 0.336884

Epoch 3321/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.0181]
Epoch 3321/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.03it/s]

End of Epoch 3321 | Train Loss: 0.022078 | Val Loss: 0.502526

Epoch 3322/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.0132]
Epoch 3322/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 3322 | Train Loss: 0.022916 | Val Loss: 0.242945

Epoch 3323/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00638]
Epoch 3323/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.01it/s]

End of Epoch 3323 | Train Loss: 0.020661 | Val Loss: 0.308549

Epoch 3324/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.55it/s, loss=0.00452]
Epoch 3324/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 3324 | Train Loss: 0.018010 | Val Loss: 0.732307

Epoch 3325/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00604]
Epoch 3325/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 3325 | Train Loss: 0.024358 | Val Loss: 0.658219

Epoch 3326/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0152]
Epoch 3326/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.31it/s]

End of Epoch 3326 | Train Loss: 0.019671 | Val Loss: 0.940982

Epoch 3327/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00279]
Epoch 3327/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 3327 | Train Loss: 0.016942 | Val Loss: 0.933420

Epoch 3328/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00261]
Epoch 3328/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.92it/s]

End of Epoch 3328 | Train Loss: 0.016962 | Val Loss: 0.472787

Epoch 3329/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.50it/s, loss=0.00331]
Epoch 3329/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 3329 | Train Loss: 0.023227 | Val Loss: 0.335389

Epoch 3330/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0237]
Epoch 3330/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.38it/s]

End of Epoch 3330 | Train Loss: 0.021497 | Val Loss: 0.474861

Epoch 3331/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00293]
Epoch 3331/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 3331 | Train Loss: 0.022302 | Val Loss: 0.228880

Epoch 3332/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0043]
Epoch 3332/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.08it/s]

End of Epoch 3332 | Train Loss: 0.017627 | Val Loss: 0.402612

Epoch 3333/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.00264]
Epoch 3333/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.76it/s]

End of Epoch 3333 | Train Loss: 0.018890 | Val Loss: 0.437073

Epoch 3334/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.0117]
Epoch 3334/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.32it/s]

End of Epoch 3334 | Train Loss: 0.020719 | Val Loss: 0.629965

Epoch 3335/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.314]
Epoch 3335/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 3335 | Train Loss: 0.019738 | Val Loss: 0.562473

Epoch 3336/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00414]
Epoch 3336/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.96it/s]

End of Epoch 3336 | Train Loss: 0.026784 | Val Loss: 0.479918

Epoch 3337/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00278]
Epoch 3337/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.98it/s]

End of Epoch 3337 | Train Loss: 0.018168 | Val Loss: 0.589137

Epoch 3338/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00681]
Epoch 3338/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.68it/s]

End of Epoch 3338 | Train Loss: 0.016816 | Val Loss: 0.450408

Epoch 3339/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00291]
Epoch 3339/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 3339 | Train Loss: 0.019381 | Val Loss: 0.667633

Epoch 3340/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00348]
Epoch 3340/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 3340 | Train Loss: 0.015602 | Val Loss: 0.424426

Epoch 3341/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.0387]
Epoch 3341/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 3341 | Train Loss: 0.013820 | Val Loss: 0.352118

Epoch 3342/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00498]
Epoch 3342/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.61it/s]

End of Epoch 3342 | Train Loss: 0.017359 | Val Loss: 0.676359

Epoch 3343/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.012]
Epoch 3343/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.47it/s]

End of Epoch 3343 | Train Loss: 0.018109 | Val Loss: 0.365557

Epoch 3344/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.0156]
Epoch 3344/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.40it/s]

End of Epoch 3344 | Train Loss: 0.021278 | Val Loss: 0.523944

Epoch 3345/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00289]
Epoch 3345/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.56it/s]

End of Epoch 3345 | Train Loss: 0.019762 | Val Loss: 0.230425

Epoch 3346/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00349]
Epoch 3346/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.18it/s]

End of Epoch 3346 | Train Loss: 0.019406 | Val Loss: 0.242844

Epoch 3347/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0105]
Epoch 3347/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.78it/s]

End of Epoch 3347 | Train Loss: 0.018167 | Val Loss: 0.295566

Epoch 3348/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00224]
Epoch 3348/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.97it/s]

End of Epoch 3348 | Train Loss: 0.016998 | Val Loss: 0.390303

Epoch 3349/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.67it/s, loss=0.00248]
Epoch 3349/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.13it/s]

End of Epoch 3349 | Train Loss: 0.015646 | Val Loss: 0.440426

Epoch 3350/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00406]
Epoch 3350/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.32it/s]

End of Epoch 3350 | Train Loss: 0.027517 | Val Loss: 0.415744

Epoch 3351/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.924]
Epoch 3351/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.19it/s]

End of Epoch 3351 | Train Loss: 0.030404 | Val Loss: 0.321268

Epoch 3352/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00374]
Epoch 3352/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.40it/s]

End of Epoch 3352 | Train Loss: 0.023269 | Val Loss: 0.876918

Epoch 3353/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00406]
Epoch 3353/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 3353 | Train Loss: 0.022689 | Val Loss: 0.435027

Epoch 3354/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0931]
Epoch 3354/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.75it/s]

End of Epoch 3354 | Train Loss: 0.023532 | Val Loss: 0.898294

Epoch 3355/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0125]
Epoch 3355/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 3355 | Train Loss: 0.020066 | Val Loss: 0.397745

Epoch 3356/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0844]
Epoch 3356/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.77it/s]

End of Epoch 3356 | Train Loss: 0.014874 | Val Loss: 0.626585

Epoch 3357/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.484]
Epoch 3357/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.41it/s]

End of Epoch 3357 | Train Loss: 0.019176 | Val Loss: 0.458819

Epoch 3358/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00306]
Epoch 3358/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.26it/s]

End of Epoch 3358 | Train Loss: 0.023051 | Val Loss: 0.246021

Epoch 3359/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00593]
Epoch 3359/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 3359 | Train Loss: 0.026020 | Val Loss: 0.509528

Epoch 3360/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00277]
Epoch 3360/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.94it/s]

End of Epoch 3360 | Train Loss: 0.020690 | Val Loss: 0.082273
New Best Model Saved (Val Loss: 0.082273)

Epoch 3361/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00295]
Epoch 3361/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.34it/s]

End of Epoch 3361 | Train Loss: 0.015083 | Val Loss: 0.488030

Epoch 3362/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00557]
Epoch 3362/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.07it/s]

End of Epoch 3362 | Train Loss: 0.021989 | Val Loss: 0.523550

Epoch 3363/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00329]
Epoch 3363/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 3363 | Train Loss: 0.018066 | Val Loss: 0.368223

Epoch 3364/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0628]
Epoch 3364/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.90it/s]

End of Epoch 3364 | Train Loss: 0.019466 | Val Loss: 0.293504

Epoch 3365/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.238]
Epoch 3365/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 3365 | Train Loss: 0.020060 | Val Loss: 0.570052

Epoch 3366/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00332]
Epoch 3366/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.13it/s]

End of Epoch 3366 | Train Loss: 0.021011 | Val Loss: 0.585446

Epoch 3367/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00274]
Epoch 3367/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.78it/s]

End of Epoch 3367 | Train Loss: 0.017660 | Val Loss: 0.358430

Epoch 3368/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00761]
Epoch 3368/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.87it/s]

End of Epoch 3368 | Train Loss: 0.019011 | Val Loss: 0.401952

Epoch 3369/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.00275]
Epoch 3369/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 3369 | Train Loss: 0.021048 | Val Loss: 0.445239

Epoch 3370/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00297]
Epoch 3370/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.62it/s]

End of Epoch 3370 | Train Loss: 0.016332 | Val Loss: 0.228218

Epoch 3371/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.0223]
Epoch 3371/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.59it/s]

End of Epoch 3371 | Train Loss: 0.020968 | Val Loss: 0.697877

Epoch 3372/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.01]
Epoch 3372/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.67it/s]

End of Epoch 3372 | Train Loss: 0.018721 | Val Loss: 0.392391

Epoch 3373/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.0103]
Epoch 3373/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.80it/s]

End of Epoch 3373 | Train Loss: 0.016265 | Val Loss: 1.022615

Epoch 3374/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.25it/s, loss=0.00641]
Epoch 3374/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.49it/s]

End of Epoch 3374 | Train Loss: 0.020782 | Val Loss: 0.398159

Epoch 3375/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00403]
Epoch 3375/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.04it/s]

End of Epoch 3375 | Train Loss: 0.018472 | Val Loss: 0.356069

Epoch 3376/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00877]
Epoch 3376/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 3376 | Train Loss: 0.020350 | Val Loss: 0.882382

Epoch 3377/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00552]
Epoch 3377/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.45it/s]

End of Epoch 3377 | Train Loss: 0.017948 | Val Loss: 0.430650

Epoch 3378/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00413]
Epoch 3378/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.22it/s]

End of Epoch 3378 | Train Loss: 0.027020 | Val Loss: 0.506084

Epoch 3379/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0023]
Epoch 3379/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.18it/s]

End of Epoch 3379 | Train Loss: 0.021504 | Val Loss: 0.605249

Epoch 3380/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00347]
Epoch 3380/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.82it/s]

End of Epoch 3380 | Train Loss: 0.018674 | Val Loss: 0.448391

Epoch 3381/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00274]
Epoch 3381/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.08it/s]

End of Epoch 3381 | Train Loss: 0.022483 | Val Loss: 0.475898

Epoch 3382/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00412]
Epoch 3382/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.18it/s]

End of Epoch 3382 | Train Loss: 0.019835 | Val Loss: 0.504918

Epoch 3383/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.0029]
Epoch 3383/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 3383 | Train Loss: 0.024535 | Val Loss: 0.406634

Epoch 3384/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00255]
Epoch 3384/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.15it/s]

End of Epoch 3384 | Train Loss: 0.019324 | Val Loss: 0.374744

Epoch 3385/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0046]
Epoch 3385/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.83it/s]

End of Epoch 3385 | Train Loss: 0.018146 | Val Loss: 0.620805

Epoch 3386/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00259]
Epoch 3386/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.64it/s]

End of Epoch 3386 | Train Loss: 0.021598 | Val Loss: 0.459134

Epoch 3387/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00261]
Epoch 3387/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.52it/s]

End of Epoch 3387 | Train Loss: 0.014047 | Val Loss: 0.391322

Epoch 3388/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00356]
Epoch 3388/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.68it/s]

End of Epoch 3388 | Train Loss: 0.017744 | Val Loss: 0.296839

Epoch 3389/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.37it/s, loss=0.00308]
Epoch 3389/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.00it/s]

End of Epoch 3389 | Train Loss: 0.020321 | Val Loss: 0.247485

Epoch 3390/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.00387]
Epoch 3390/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.24it/s]

End of Epoch 3390 | Train Loss: 0.019582 | Val Loss: 0.226857

Epoch 3391/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00598]
Epoch 3391/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.46it/s]

End of Epoch 3391 | Train Loss: 0.017520 | Val Loss: 0.482942

Epoch 3392/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.31it/s, loss=0.00291]
Epoch 3392/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.74it/s]

End of Epoch 3392 | Train Loss: 0.021754 | Val Loss: 0.478125

Epoch 3393/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00978]
Epoch 3393/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.34it/s]

End of Epoch 3393 | Train Loss: 0.022099 | Val Loss: 0.312875

Epoch 3394/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0113]
Epoch 3394/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.16it/s]

End of Epoch 3394 | Train Loss: 0.018524 | Val Loss: 0.509454

Epoch 3395/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00281]
Epoch 3395/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.74it/s]

End of Epoch 3395 | Train Loss: 0.016369 | Val Loss: 0.666268

Epoch 3396/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00382]
Epoch 3396/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 3396 | Train Loss: 0.023405 | Val Loss: 0.344027

Epoch 3397/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00413]
Epoch 3397/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.60it/s]

End of Epoch 3397 | Train Loss: 0.019121 | Val Loss: 0.543543

Epoch 3398/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00389]
Epoch 3398/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.95it/s]

End of Epoch 3398 | Train Loss: 0.014746 | Val Loss: 0.565052

Epoch 3399/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00409]
Epoch 3399/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.94it/s]

End of Epoch 3399 | Train Loss: 0.013720 | Val Loss: 0.425303

Epoch 3400/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00304]
Epoch 3400/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.50it/s]

End of Epoch 3400 | Train Loss: 0.019646 | Val Loss: 0.483659

Epoch 3401/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00373]
Epoch 3401/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.65it/s]

End of Epoch 3401 | Train Loss: 0.011664 | Val Loss: 0.480608

Epoch 3402/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.00331]
Epoch 3402/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.86it/s]

End of Epoch 3402 | Train Loss: 0.019362 | Val Loss: 1.034526

Epoch 3403/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00339]
Epoch 3403/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.34it/s]

End of Epoch 3403 | Train Loss: 0.019070 | Val Loss: 0.333884

Epoch 3404/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00447]
Epoch 3404/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.92it/s]

End of Epoch 3404 | Train Loss: 0.017374 | Val Loss: 0.656870

Epoch 3405/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00446]
Epoch 3405/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.61it/s]

End of Epoch 3405 | Train Loss: 0.019832 | Val Loss: 0.352905

Epoch 3406/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00329]
Epoch 3406/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.67it/s]

End of Epoch 3406 | Train Loss: 0.014844 | Val Loss: 0.405839

Epoch 3407/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0024]
Epoch 3407/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.78it/s]

End of Epoch 3407 | Train Loss: 0.015614 | Val Loss: 0.559783

Epoch 3408/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00318]
Epoch 3408/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.53it/s]

End of Epoch 3408 | Train Loss: 0.024245 | Val Loss: 0.520103

Epoch 3409/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.0182]
Epoch 3409/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 3409 | Train Loss: 0.019884 | Val Loss: 0.396636

Epoch 3410/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0023]
Epoch 3410/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.12it/s]

End of Epoch 3410 | Train Loss: 0.020922 | Val Loss: 0.535370

Epoch 3411/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00293]
Epoch 3411/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.30it/s]

End of Epoch 3411 | Train Loss: 0.021162 | Val Loss: 0.373251

Epoch 3412/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00332]
Epoch 3412/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.22it/s]

End of Epoch 3412 | Train Loss: 0.016924 | Val Loss: 0.352846

Epoch 3413/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00398]
Epoch 3413/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 3413 | Train Loss: 0.017254 | Val Loss: 0.464787

Epoch 3414/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00227]
Epoch 3414/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.18it/s]

End of Epoch 3414 | Train Loss: 0.018829 | Val Loss: 0.294773

Epoch 3415/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00311]
Epoch 3415/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 3415 | Train Loss: 0.020318 | Val Loss: 0.306927

Epoch 3416/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.321]
Epoch 3416/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 3416 | Train Loss: 0.025344 | Val Loss: 0.651161

Epoch 3417/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.00291]
Epoch 3417/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 82.36it/s]

End of Epoch 3417 | Train Loss: 0.022576 | Val Loss: 0.385718

Epoch 3418/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00318]
Epoch 3418/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 3418 | Train Loss: 0.016456 | Val Loss: 0.468902

Epoch 3419/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.0157]
Epoch 3419/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.78it/s]

End of Epoch 3419 | Train Loss: 0.017773 | Val Loss: 0.438646

Epoch 3420/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00288]
Epoch 3420/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.86it/s]

End of Epoch 3420 | Train Loss: 0.023958 | Val Loss: 0.389072

Epoch 3421/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0188]
Epoch 3421/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 3421 | Train Loss: 0.021769 | Val Loss: 0.429486

Epoch 3422/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00422]
Epoch 3422/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.06it/s]

End of Epoch 3422 | Train Loss: 0.015037 | Val Loss: 0.391624

Epoch 3423/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00703]
Epoch 3423/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.43it/s]

End of Epoch 3423 | Train Loss: 0.016156 | Val Loss: 0.590995

Epoch 3424/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00956]
Epoch 3424/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 3424 | Train Loss: 0.023878 | Val Loss: 0.811582

Epoch 3425/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00237]
Epoch 3425/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.10it/s]

End of Epoch 3425 | Train Loss: 0.022810 | Val Loss: 0.884109

Epoch 3426/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00255]
Epoch 3426/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.06it/s]

End of Epoch 3426 | Train Loss: 0.018509 | Val Loss: 0.379542

Epoch 3427/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00546]
Epoch 3427/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.18it/s]

End of Epoch 3427 | Train Loss: 0.022813 | Val Loss: 0.526004

Epoch 3428/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00272]
Epoch 3428/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.70it/s]

End of Epoch 3428 | Train Loss: 0.016076 | Val Loss: 0.609953

Epoch 3429/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00306]
Epoch 3429/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.02it/s]

End of Epoch 3429 | Train Loss: 0.015894 | Val Loss: 0.404607

Epoch 3430/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0117]
Epoch 3430/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.41it/s]

End of Epoch 3430 | Train Loss: 0.018687 | Val Loss: 0.639845

Epoch 3431/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00437]
Epoch 3431/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.98it/s]

End of Epoch 3431 | Train Loss: 0.017797 | Val Loss: 0.456788

Epoch 3432/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.60it/s, loss=0.00388]
Epoch 3432/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.91it/s]

End of Epoch 3432 | Train Loss: 0.021342 | Val Loss: 0.865282

Epoch 3433/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00209]
Epoch 3433/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.57it/s]

End of Epoch 3433 | Train Loss: 0.015479 | Val Loss: 0.864077

Epoch 3434/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00299]
Epoch 3434/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.47it/s]

End of Epoch 3434 | Train Loss: 0.022618 | Val Loss: 0.479834

Epoch 3435/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0097]
Epoch 3435/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.53it/s]

End of Epoch 3435 | Train Loss: 0.019130 | Val Loss: 0.624277

Epoch 3436/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00341]
Epoch 3436/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.44it/s]

End of Epoch 3436 | Train Loss: 0.020684 | Val Loss: 0.789137

Epoch 3437/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0126]
Epoch 3437/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.20it/s]

End of Epoch 3437 | Train Loss: 0.014870 | Val Loss: 0.382959

Epoch 3438/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.0127]
Epoch 3438/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.32it/s]

End of Epoch 3438 | Train Loss: 0.020475 | Val Loss: 0.455271

Epoch 3439/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00265]
Epoch 3439/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.73it/s]

End of Epoch 3439 | Train Loss: 0.019832 | Val Loss: 0.318414

Epoch 3440/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00257]
Epoch 3440/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.89it/s]

End of Epoch 3440 | Train Loss: 0.015118 | Val Loss: 0.353237

Epoch 3441/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.19it/s, loss=0.003]
Epoch 3441/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.68it/s]

End of Epoch 3441 | Train Loss: 0.015158 | Val Loss: 0.486933

Epoch 3442/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00212]
Epoch 3442/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 3442 | Train Loss: 0.017593 | Val Loss: 0.525080

Epoch 3443/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00313]
Epoch 3443/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.12it/s]

End of Epoch 3443 | Train Loss: 0.021062 | Val Loss: 0.734746

Epoch 3444/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00354]
Epoch 3444/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.58it/s]

End of Epoch 3444 | Train Loss: 0.024007 | Val Loss: 0.471637

Epoch 3445/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0131]
Epoch 3445/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.53it/s]

End of Epoch 3445 | Train Loss: 0.020031 | Val Loss: 0.513837

Epoch 3446/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00323]
Epoch 3446/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 3446 | Train Loss: 0.023745 | Val Loss: 0.443158

Epoch 3447/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00278]
Epoch 3447/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.51it/s]

End of Epoch 3447 | Train Loss: 0.018676 | Val Loss: 0.465147

Epoch 3448/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00281]
Epoch 3448/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 3448 | Train Loss: 0.019664 | Val Loss: 0.528478

Epoch 3449/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.00227]
Epoch 3449/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.93it/s]

End of Epoch 3449 | Train Loss: 0.019431 | Val Loss: 0.522082

Epoch 3450/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00952]
Epoch 3450/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.17it/s]

End of Epoch 3450 | Train Loss: 0.024754 | Val Loss: 0.484142

Epoch 3451/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00256]
Epoch 3451/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.80it/s]

End of Epoch 3451 | Train Loss: 0.013727 | Val Loss: 0.444877

Epoch 3452/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00253]
Epoch 3452/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.35it/s]

End of Epoch 3452 | Train Loss: 0.014948 | Val Loss: 0.585052

Epoch 3453/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.32it/s, loss=0.00355]
Epoch 3453/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.96it/s]

End of Epoch 3453 | Train Loss: 0.015671 | Val Loss: 0.491511

Epoch 3454/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.00502]
Epoch 3454/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.04it/s]

End of Epoch 3454 | Train Loss: 0.019146 | Val Loss: 0.756370

Epoch 3455/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00278]
Epoch 3455/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.79it/s]

End of Epoch 3455 | Train Loss: 0.017880 | Val Loss: 0.465821

Epoch 3456/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.0328]
Epoch 3456/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.33it/s]

End of Epoch 3456 | Train Loss: 0.017355 | Val Loss: 0.477384

Epoch 3457/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00427]
Epoch 3457/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.28it/s]

End of Epoch 3457 | Train Loss: 0.018122 | Val Loss: 0.757671

Epoch 3458/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00347]
Epoch 3458/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 3458 | Train Loss: 0.021248 | Val Loss: 0.336337

Epoch 3459/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00344]
Epoch 3459/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.28it/s]

End of Epoch 3459 | Train Loss: 0.019386 | Val Loss: 0.563362

Epoch 3460/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00325]
Epoch 3460/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.77it/s]

End of Epoch 3460 | Train Loss: 0.016574 | Val Loss: 0.778851

Epoch 3461/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00208]
Epoch 3461/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.53it/s]

End of Epoch 3461 | Train Loss: 0.014978 | Val Loss: 1.020880

Epoch 3462/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00304]
Epoch 3462/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.41it/s]

End of Epoch 3462 | Train Loss: 0.021827 | Val Loss: 0.585617

Epoch 3463/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00195]
Epoch 3463/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.22it/s]

End of Epoch 3463 | Train Loss: 0.019590 | Val Loss: 0.590922

Epoch 3464/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00575]
Epoch 3464/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 3464 | Train Loss: 0.022817 | Val Loss: 0.706629

Epoch 3465/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0217]
Epoch 3465/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.23it/s]

End of Epoch 3465 | Train Loss: 0.023205 | Val Loss: 0.514463

Epoch 3466/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0182]
Epoch 3466/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.95it/s]

End of Epoch 3466 | Train Loss: 0.018971 | Val Loss: 0.735395

Epoch 3467/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00255]
Epoch 3467/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.18it/s]

End of Epoch 3467 | Train Loss: 0.015248 | Val Loss: 0.281984

Epoch 3468/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00251]
Epoch 3468/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 3468 | Train Loss: 0.020923 | Val Loss: 0.483548

Epoch 3469/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00453]
Epoch 3469/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 3469 | Train Loss: 0.018653 | Val Loss: 0.715336

Epoch 3470/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.57it/s, loss=0.168]
Epoch 3470/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 3470 | Train Loss: 0.016451 | Val Loss: 0.450631

Epoch 3471/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00332]
Epoch 3471/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 3471 | Train Loss: 0.028182 | Val Loss: 0.296094

Epoch 3472/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00278]
Epoch 3472/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.52it/s]

End of Epoch 3472 | Train Loss: 0.019012 | Val Loss: 0.493342

Epoch 3473/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0938]
Epoch 3473/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.01it/s]

End of Epoch 3473 | Train Loss: 0.021422 | Val Loss: 0.499715

Epoch 3474/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00268]
Epoch 3474/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 3474 | Train Loss: 0.019664 | Val Loss: 0.367994

Epoch 3475/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00962]
Epoch 3475/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.72it/s]

End of Epoch 3475 | Train Loss: 0.016719 | Val Loss: 0.364222

Epoch 3476/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00266]
Epoch 3476/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.42it/s]

End of Epoch 3476 | Train Loss: 0.018629 | Val Loss: 0.380997

Epoch 3477/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00288]
Epoch 3477/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 3477 | Train Loss: 0.017629 | Val Loss: 0.525248

Epoch 3478/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00399]
Epoch 3478/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.03it/s]

End of Epoch 3478 | Train Loss: 0.016940 | Val Loss: 0.544216

Epoch 3479/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00392]
Epoch 3479/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.27it/s]

End of Epoch 3479 | Train Loss: 0.024676 | Val Loss: 0.378176

Epoch 3480/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.0219]
Epoch 3480/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.44it/s]

End of Epoch 3480 | Train Loss: 0.017867 | Val Loss: 0.805233

Epoch 3481/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00232]
Epoch 3481/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.03it/s]

End of Epoch 3481 | Train Loss: 0.013989 | Val Loss: 0.592547

Epoch 3482/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00248]
Epoch 3482/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.81it/s]

End of Epoch 3482 | Train Loss: 0.015269 | Val Loss: 0.660059

Epoch 3483/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00285]
Epoch 3483/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.29it/s]

End of Epoch 3483 | Train Loss: 0.018581 | Val Loss: 0.417722

Epoch 3484/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00265]
Epoch 3484/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 3484 | Train Loss: 0.018592 | Val Loss: 0.461940

Epoch 3485/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00749]
Epoch 3485/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 3485 | Train Loss: 0.016842 | Val Loss: 0.417322

Epoch 3486/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0032]
Epoch 3486/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 3486 | Train Loss: 0.017015 | Val Loss: 0.905883

Epoch 3487/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0031]
Epoch 3487/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.98it/s]

End of Epoch 3487 | Train Loss: 0.017382 | Val Loss: 0.464655

Epoch 3488/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.17it/s, loss=0.00309]
Epoch 3488/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.56it/s]

End of Epoch 3488 | Train Loss: 0.017858 | Val Loss: 0.311561

Epoch 3489/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00212]
Epoch 3489/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.31it/s]

End of Epoch 3489 | Train Loss: 0.017438 | Val Loss: 0.314191

Epoch 3490/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.32it/s, loss=0.00589]
Epoch 3490/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 3490 | Train Loss: 0.020084 | Val Loss: 0.476653

Epoch 3491/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00963]
Epoch 3491/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.08it/s]

End of Epoch 3491 | Train Loss: 0.016055 | Val Loss: 0.447747

Epoch 3492/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.00454]
Epoch 3492/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.23it/s]

End of Epoch 3492 | Train Loss: 0.013905 | Val Loss: 0.221981

Epoch 3493/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00232]
Epoch 3493/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.22it/s]

End of Epoch 3493 | Train Loss: 0.012953 | Val Loss: 0.517518

Epoch 3494/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00585]
Epoch 3494/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.18it/s]

End of Epoch 3494 | Train Loss: 0.021086 | Val Loss: 0.570679

Epoch 3495/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.385]
Epoch 3495/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.57it/s]

End of Epoch 3495 | Train Loss: 0.019103 | Val Loss: 0.636512

Epoch 3496/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00313]
Epoch 3496/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 3496 | Train Loss: 0.030839 | Val Loss: 0.460827

Epoch 3497/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00482]
Epoch 3497/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.89it/s]

End of Epoch 3497 | Train Loss: 0.021260 | Val Loss: 0.695190

Epoch 3498/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00692]
Epoch 3498/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 3498 | Train Loss: 0.017613 | Val Loss: 0.273339

Epoch 3499/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.603]
Epoch 3499/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.25it/s]

End of Epoch 3499 | Train Loss: 0.027304 | Val Loss: 0.553491

Epoch 3500/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00272]
Epoch 3500/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 3500 | Train Loss: 0.028846 | Val Loss: 0.508151

Epoch 3501/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00228]
Epoch 3501/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.20it/s]

End of Epoch 3501 | Train Loss: 0.014357 | Val Loss: 0.456133

Epoch 3502/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00326]
Epoch 3502/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.11it/s]

End of Epoch 3502 | Train Loss: 0.023360 | Val Loss: 0.879824

Epoch 3503/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00515]
Epoch 3503/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.55it/s]

End of Epoch 3503 | Train Loss: 0.020228 | Val Loss: 0.250911

Epoch 3504/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00253]
Epoch 3504/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 3504 | Train Loss: 0.021387 | Val Loss: 0.427809

Epoch 3505/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00447]
Epoch 3505/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.63it/s]

End of Epoch 3505 | Train Loss: 0.017679 | Val Loss: 0.739236

Epoch 3506/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0116]
Epoch 3506/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.52it/s]

End of Epoch 3506 | Train Loss: 0.015657 | Val Loss: 0.709469

Epoch 3507/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0032]
Epoch 3507/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.42it/s]

End of Epoch 3507 | Train Loss: 0.025234 | Val Loss: 0.613638

Epoch 3508/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00338]
Epoch 3508/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.89it/s]

End of Epoch 3508 | Train Loss: 0.016799 | Val Loss: 0.586020

Epoch 3509/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00299]
Epoch 3509/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.03it/s]

End of Epoch 3509 | Train Loss: 0.016031 | Val Loss: 0.600962

Epoch 3510/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.61it/s, loss=0.00246]
Epoch 3510/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.42it/s]

End of Epoch 3510 | Train Loss: 0.023485 | Val Loss: 0.355366

Epoch 3511/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00191]
Epoch 3511/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.89it/s]

End of Epoch 3511 | Train Loss: 0.015661 | Val Loss: 0.295697

Epoch 3512/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00547]
Epoch 3512/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.30it/s]

End of Epoch 3512 | Train Loss: 0.024632 | Val Loss: 0.668574

Epoch 3513/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0025]
Epoch 3513/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.92it/s]

End of Epoch 3513 | Train Loss: 0.018761 | Val Loss: 0.572529

Epoch 3514/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00689]
Epoch 3514/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.27it/s]

End of Epoch 3514 | Train Loss: 0.020363 | Val Loss: 0.458852

Epoch 3515/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0227]
Epoch 3515/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.09it/s]

End of Epoch 3515 | Train Loss: 0.020936 | Val Loss: 0.835233

Epoch 3516/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00471]
Epoch 3516/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.65it/s]

End of Epoch 3516 | Train Loss: 0.024008 | Val Loss: 0.473670

Epoch 3517/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.11it/s, loss=0.00893]
Epoch 3517/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.70it/s]

End of Epoch 3517 | Train Loss: 0.015175 | Val Loss: 0.624936

Epoch 3518/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00214]
Epoch 3518/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.09it/s]

End of Epoch 3518 | Train Loss: 0.014648 | Val Loss: 0.469343

Epoch 3519/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00388]
Epoch 3519/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.77it/s]

End of Epoch 3519 | Train Loss: 0.019242 | Val Loss: 0.603770

Epoch 3520/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00336]
Epoch 3520/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.77it/s]

End of Epoch 3520 | Train Loss: 0.022238 | Val Loss: 0.542354

Epoch 3521/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00275]
Epoch 3521/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.23it/s]

End of Epoch 3521 | Train Loss: 0.018490 | Val Loss: 0.683489

Epoch 3522/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00905]
Epoch 3522/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 3522 | Train Loss: 0.021068 | Val Loss: 0.452441

Epoch 3523/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00254]
Epoch 3523/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 3523 | Train Loss: 0.013460 | Val Loss: 0.603159

Epoch 3524/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.0165]
Epoch 3524/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.70it/s]

End of Epoch 3524 | Train Loss: 0.011733 | Val Loss: 0.448957

Epoch 3525/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.21it/s, loss=0.00236]
Epoch 3525/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.65it/s]

End of Epoch 3525 | Train Loss: 0.018765 | Val Loss: 0.325049

Epoch 3526/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00818]
Epoch 3526/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.88it/s]

End of Epoch 3526 | Train Loss: 0.017639 | Val Loss: 0.406370

Epoch 3527/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00265]
Epoch 3527/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.58it/s]

End of Epoch 3527 | Train Loss: 0.016793 | Val Loss: 0.480451

Epoch 3528/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00694]
Epoch 3528/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.02it/s]

End of Epoch 3528 | Train Loss: 0.024629 | Val Loss: 0.334151

Epoch 3529/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00241]
Epoch 3529/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 3529 | Train Loss: 0.016595 | Val Loss: 0.287402

Epoch 3530/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00722]
Epoch 3530/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 3530 | Train Loss: 0.021412 | Val Loss: 0.586546

Epoch 3531/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0123]
Epoch 3531/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.60it/s]

End of Epoch 3531 | Train Loss: 0.015031 | Val Loss: 0.292046

Epoch 3532/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00284]
Epoch 3532/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.42it/s]

End of Epoch 3532 | Train Loss: 0.018384 | Val Loss: 0.680986

Epoch 3533/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00345]
Epoch 3533/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.27it/s]

End of Epoch 3533 | Train Loss: 0.017389 | Val Loss: 0.825137

Epoch 3534/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00208]
Epoch 3534/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.84it/s]

End of Epoch 3534 | Train Loss: 0.016703 | Val Loss: 0.385336

Epoch 3535/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00297]
Epoch 3535/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.11it/s]

End of Epoch 3535 | Train Loss: 0.018870 | Val Loss: 0.469463

Epoch 3536/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.0447]
Epoch 3536/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.63it/s]

End of Epoch 3536 | Train Loss: 0.018669 | Val Loss: 1.027657

Epoch 3537/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00485]
Epoch 3537/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.00it/s]

End of Epoch 3537 | Train Loss: 0.020552 | Val Loss: 0.194353

Epoch 3538/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00359]
Epoch 3538/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.43it/s]

End of Epoch 3538 | Train Loss: 0.019605 | Val Loss: 0.459730

Epoch 3539/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00306]
Epoch 3539/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.02it/s]

End of Epoch 3539 | Train Loss: 0.015619 | Val Loss: 0.499804

Epoch 3540/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.014]
Epoch 3540/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.45it/s]

End of Epoch 3540 | Train Loss: 0.017602 | Val Loss: 0.223380

Epoch 3541/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00913]
Epoch 3541/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.37it/s]

End of Epoch 3541 | Train Loss: 0.014432 | Val Loss: 0.758542

Epoch 3542/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00348]
Epoch 3542/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.92it/s]

End of Epoch 3542 | Train Loss: 0.020880 | Val Loss: 0.414344

Epoch 3543/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00308]
Epoch 3543/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.68it/s]

End of Epoch 3543 | Train Loss: 0.025263 | Val Loss: 0.351910

Epoch 3544/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0275]
Epoch 3544/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.00it/s]

End of Epoch 3544 | Train Loss: 0.022092 | Val Loss: 0.713724

Epoch 3545/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00361]
Epoch 3545/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.81it/s]

End of Epoch 3545 | Train Loss: 0.019815 | Val Loss: 0.381671

Epoch 3546/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0145]
Epoch 3546/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.10it/s]

End of Epoch 3546 | Train Loss: 0.023191 | Val Loss: 0.503431

Epoch 3547/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00333]
Epoch 3547/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.44it/s]

End of Epoch 3547 | Train Loss: 0.020603 | Val Loss: 0.446564

Epoch 3548/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00337]
Epoch 3548/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.18it/s]

End of Epoch 3548 | Train Loss: 0.020253 | Val Loss: 0.379672

Epoch 3549/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.0263]
Epoch 3549/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.42it/s]

End of Epoch 3549 | Train Loss: 0.016690 | Val Loss: 0.178051

Epoch 3550/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.51it/s, loss=0.00572]
Epoch 3550/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.39it/s]

End of Epoch 3550 | Train Loss: 0.018668 | Val Loss: 0.457712

Epoch 3551/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00291]
Epoch 3551/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.60it/s]

End of Epoch 3551 | Train Loss: 0.015174 | Val Loss: 0.632257

Epoch 3552/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00239]
Epoch 3552/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.40it/s]

End of Epoch 3552 | Train Loss: 0.017529 | Val Loss: 0.351106

Epoch 3553/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0103]
Epoch 3553/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.83it/s]

End of Epoch 3553 | Train Loss: 0.018922 | Val Loss: 0.644764

Epoch 3554/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0132]
Epoch 3554/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.91it/s]

End of Epoch 3554 | Train Loss: 0.016180 | Val Loss: 0.383283

Epoch 3555/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.08it/s, loss=0.00282]
Epoch 3555/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.92it/s]

End of Epoch 3555 | Train Loss: 0.015992 | Val Loss: 0.700970

Epoch 3556/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0118]
Epoch 3556/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.10it/s]

End of Epoch 3556 | Train Loss: 0.019871 | Val Loss: 0.389265

Epoch 3557/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0341]
Epoch 3557/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.38it/s]

End of Epoch 3557 | Train Loss: 0.016659 | Val Loss: 0.742325

Epoch 3558/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.0107]
Epoch 3558/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.00it/s]

End of Epoch 3558 | Train Loss: 0.017642 | Val Loss: 0.399649

Epoch 3559/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00312]
Epoch 3559/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.41it/s]

End of Epoch 3559 | Train Loss: 0.013261 | Val Loss: 0.548656

Epoch 3560/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00474]
Epoch 3560/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.26it/s]

End of Epoch 3560 | Train Loss: 0.017874 | Val Loss: 0.524108

Epoch 3561/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00615]
Epoch 3561/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 3561 | Train Loss: 0.020599 | Val Loss: 0.753038

Epoch 3562/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.74it/s, loss=0.00332]
Epoch 3562/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.26it/s]

End of Epoch 3562 | Train Loss: 0.021341 | Val Loss: 0.616718

Epoch 3563/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.0237]
Epoch 3563/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.86it/s]

End of Epoch 3563 | Train Loss: 0.020420 | Val Loss: 0.338725

Epoch 3564/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.00222]
Epoch 3564/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.56it/s]

End of Epoch 3564 | Train Loss: 0.016937 | Val Loss: 0.728745

Epoch 3565/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00238]
Epoch 3565/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.07it/s]

End of Epoch 3565 | Train Loss: 0.016789 | Val Loss: 0.470977

Epoch 3566/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00354]
Epoch 3566/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.61it/s]

End of Epoch 3566 | Train Loss: 0.019572 | Val Loss: 0.356221

Epoch 3567/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00399]
Epoch 3567/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.77it/s]

End of Epoch 3567 | Train Loss: 0.020879 | Val Loss: 0.498200

Epoch 3568/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0122]
Epoch 3568/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.83it/s]

End of Epoch 3568 | Train Loss: 0.012150 | Val Loss: 0.510178

Epoch 3569/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00233]
Epoch 3569/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.50it/s]

End of Epoch 3569 | Train Loss: 0.019659 | Val Loss: 0.481910

Epoch 3570/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00376]
Epoch 3570/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.05it/s]

End of Epoch 3570 | Train Loss: 0.016631 | Val Loss: 0.361110

Epoch 3571/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00298]
Epoch 3571/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.21it/s]

End of Epoch 3571 | Train Loss: 0.018888 | Val Loss: 0.409023

Epoch 3572/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00245]
Epoch 3572/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.98it/s]

End of Epoch 3572 | Train Loss: 0.022003 | Val Loss: 0.365526

Epoch 3573/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0256]
Epoch 3573/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.13it/s]

End of Epoch 3573 | Train Loss: 0.021040 | Val Loss: 0.322497

Epoch 3574/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00371]
Epoch 3574/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.04it/s]

End of Epoch 3574 | Train Loss: 0.018480 | Val Loss: 0.329499

Epoch 3575/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00965]
Epoch 3575/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.33it/s]

End of Epoch 3575 | Train Loss: 0.017628 | Val Loss: 0.912719

Epoch 3576/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00217]
Epoch 3576/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.15it/s]

End of Epoch 3576 | Train Loss: 0.017838 | Val Loss: 0.272285

Epoch 3577/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00965]
Epoch 3577/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 3577 | Train Loss: 0.020967 | Val Loss: 0.381355

Epoch 3578/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00322]
Epoch 3578/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 3578 | Train Loss: 0.017519 | Val Loss: 0.639184

Epoch 3579/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00319]
Epoch 3579/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.94it/s]

End of Epoch 3579 | Train Loss: 0.024020 | Val Loss: 0.208106

Epoch 3580/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0306]
Epoch 3580/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.37it/s]

End of Epoch 3580 | Train Loss: 0.018309 | Val Loss: 0.462501

Epoch 3581/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.0109]
Epoch 3581/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.75it/s]

End of Epoch 3581 | Train Loss: 0.017302 | Val Loss: 0.485216

Epoch 3582/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00247]
Epoch 3582/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.19it/s]

End of Epoch 3582 | Train Loss: 0.017518 | Val Loss: 0.807994

Epoch 3583/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00245]
Epoch 3583/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.06it/s]

End of Epoch 3583 | Train Loss: 0.021206 | Val Loss: 0.495503

Epoch 3584/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00231]
Epoch 3584/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.82it/s]

End of Epoch 3584 | Train Loss: 0.019796 | Val Loss: 0.701459

Epoch 3585/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0236]
Epoch 3585/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 3585 | Train Loss: 0.015001 | Val Loss: 0.710607

Epoch 3586/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.0101]
Epoch 3586/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.21it/s]

End of Epoch 3586 | Train Loss: 0.017574 | Val Loss: 0.341984

Epoch 3587/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.558]
Epoch 3587/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.54it/s]

End of Epoch 3587 | Train Loss: 0.023393 | Val Loss: 0.163439

Epoch 3588/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00609]
Epoch 3588/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.46it/s]

End of Epoch 3588 | Train Loss: 0.026296 | Val Loss: 0.325857

Epoch 3589/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.22it/s, loss=0.00384]
Epoch 3589/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.07it/s]

End of Epoch 3589 | Train Loss: 0.019110 | Val Loss: 0.466046

Epoch 3590/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00252]
Epoch 3590/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.81it/s]

End of Epoch 3590 | Train Loss: 0.023715 | Val Loss: 0.402510

Epoch 3591/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00578]
Epoch 3591/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.80it/s]

End of Epoch 3591 | Train Loss: 0.017948 | Val Loss: 0.557674

Epoch 3592/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.00374]
Epoch 3592/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.66it/s]

End of Epoch 3592 | Train Loss: 0.018615 | Val Loss: 0.727164

Epoch 3593/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.15it/s, loss=0.00318]
Epoch 3593/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.04it/s]

End of Epoch 3593 | Train Loss: 0.020051 | Val Loss: 0.459159

Epoch 3594/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00259]
Epoch 3594/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.45it/s]

End of Epoch 3594 | Train Loss: 0.018413 | Val Loss: 0.528637

Epoch 3595/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00381]
Epoch 3595/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.27it/s]

End of Epoch 3595 | Train Loss: 0.023144 | Val Loss: 0.352940

Epoch 3596/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00257]
Epoch 3596/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.39it/s]

End of Epoch 3596 | Train Loss: 0.021277 | Val Loss: 0.570763

Epoch 3597/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.0039]
Epoch 3597/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.79it/s]

End of Epoch 3597 | Train Loss: 0.021361 | Val Loss: 0.665172

Epoch 3598/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.0921]
Epoch 3598/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.70it/s]

End of Epoch 3598 | Train Loss: 0.017767 | Val Loss: 0.715046

Epoch 3599/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00294]
Epoch 3599/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.09it/s]

End of Epoch 3599 | Train Loss: 0.018751 | Val Loss: 0.341455

Epoch 3600/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00219]
Epoch 3600/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.52it/s]

End of Epoch 3600 | Train Loss: 0.013130 | Val Loss: 0.928027

Epoch 3601/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00458]
Epoch 3601/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.29it/s]

End of Epoch 3601 | Train Loss: 0.025462 | Val Loss: 0.339821

Epoch 3602/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00384]
Epoch 3602/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.11it/s]

End of Epoch 3602 | Train Loss: 0.020791 | Val Loss: 0.347729

Epoch 3603/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.00371]
Epoch 3603/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.35it/s]

End of Epoch 3603 | Train Loss: 0.020193 | Val Loss: 0.351211

Epoch 3604/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0025]
Epoch 3604/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.57it/s]

End of Epoch 3604 | Train Loss: 0.012739 | Val Loss: 0.423711

Epoch 3605/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0149]
Epoch 3605/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.72it/s]

End of Epoch 3605 | Train Loss: 0.023476 | Val Loss: 0.388535

Epoch 3606/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.29it/s, loss=0.00316]
Epoch 3606/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.45it/s]

End of Epoch 3606 | Train Loss: 0.016429 | Val Loss: 0.446687

Epoch 3607/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0023]
Epoch 3607/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.58it/s]

End of Epoch 3607 | Train Loss: 0.018618 | Val Loss: 0.491450

Epoch 3608/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.0022]
Epoch 3608/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 3608 | Train Loss: 0.016209 | Val Loss: 0.518018

Epoch 3609/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00724]
Epoch 3609/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 3609 | Train Loss: 0.018763 | Val Loss: 0.450806

Epoch 3610/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.48it/s, loss=0.00389]
Epoch 3610/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.68it/s]

End of Epoch 3610 | Train Loss: 0.022176 | Val Loss: 0.244017

Epoch 3611/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00368]
Epoch 3611/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.12it/s]

End of Epoch 3611 | Train Loss: 0.021385 | Val Loss: 0.557352

Epoch 3612/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.0156]
Epoch 3612/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.86it/s]

End of Epoch 3612 | Train Loss: 0.015829 | Val Loss: 0.593228

Epoch 3613/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00343]
Epoch 3613/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 3613 | Train Loss: 0.022628 | Val Loss: 0.758987

Epoch 3614/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00338]
Epoch 3614/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.82it/s]

End of Epoch 3614 | Train Loss: 0.015643 | Val Loss: 0.285734

Epoch 3615/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00254]
Epoch 3615/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 118.18it/s]

End of Epoch 3615 | Train Loss: 0.020585 | Val Loss: 0.540419

Epoch 3616/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00644]
Epoch 3616/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.27it/s]

End of Epoch 3616 | Train Loss: 0.019100 | Val Loss: 0.548950

Epoch 3617/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00811]
Epoch 3617/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 3617 | Train Loss: 0.024792 | Val Loss: 0.446358

Epoch 3618/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0035]
Epoch 3618/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.86it/s]

End of Epoch 3618 | Train Loss: 0.020727 | Val Loss: 0.418708

Epoch 3619/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.01]
Epoch 3619/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.63it/s]

End of Epoch 3619 | Train Loss: 0.019909 | Val Loss: 0.462593

Epoch 3620/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00279]
Epoch 3620/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.50it/s]

End of Epoch 3620 | Train Loss: 0.012952 | Val Loss: 0.265348

Epoch 3621/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00409]
Epoch 3621/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.81it/s]

End of Epoch 3621 | Train Loss: 0.018672 | Val Loss: 1.112989

Epoch 3622/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00317]
Epoch 3622/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.22it/s]

End of Epoch 3622 | Train Loss: 0.026829 | Val Loss: 0.574549

Epoch 3623/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00333]
Epoch 3623/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.77it/s]

End of Epoch 3623 | Train Loss: 0.019825 | Val Loss: 0.487696

Epoch 3624/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.68it/s, loss=0.0025]
Epoch 3624/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.12it/s]

End of Epoch 3624 | Train Loss: 0.020734 | Val Loss: 0.584383

Epoch 3625/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00318]
Epoch 3625/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.43it/s]

End of Epoch 3625 | Train Loss: 0.020598 | Val Loss: 0.374628

Epoch 3626/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0172]
Epoch 3626/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.57it/s]

End of Epoch 3626 | Train Loss: 0.020641 | Val Loss: 0.367298

Epoch 3627/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00318]
Epoch 3627/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.82it/s]

End of Epoch 3627 | Train Loss: 0.016395 | Val Loss: 0.713548

Epoch 3628/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.017]
Epoch 3628/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.97it/s]

End of Epoch 3628 | Train Loss: 0.015704 | Val Loss: 0.653277

Epoch 3629/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0515]
Epoch 3629/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.88it/s]

End of Epoch 3629 | Train Loss: 0.023385 | Val Loss: 0.432480

Epoch 3630/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0082]
Epoch 3630/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 3630 | Train Loss: 0.019465 | Val Loss: 0.892667

Epoch 3631/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.50it/s, loss=0.317]
Epoch 3631/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.83it/s]

End of Epoch 3631 | Train Loss: 0.020907 | Val Loss: 0.689887

Epoch 3632/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00318]
Epoch 3632/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.47it/s]

End of Epoch 3632 | Train Loss: 0.022703 | Val Loss: 0.527837

Epoch 3633/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00248]
Epoch 3633/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.47it/s]

End of Epoch 3633 | Train Loss: 0.020232 | Val Loss: 0.401747

Epoch 3634/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00208]
Epoch 3634/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.91it/s]

End of Epoch 3634 | Train Loss: 0.020416 | Val Loss: 0.456255

Epoch 3635/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0024]
Epoch 3635/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.06it/s]

End of Epoch 3635 | Train Loss: 0.013175 | Val Loss: 0.351571

Epoch 3636/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00559]
Epoch 3636/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.70it/s]

End of Epoch 3636 | Train Loss: 0.021001 | Val Loss: 0.522829

Epoch 3637/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00331]
Epoch 3637/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.37it/s]

End of Epoch 3637 | Train Loss: 0.020412 | Val Loss: 0.488133

Epoch 3638/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00355]
Epoch 3638/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 3638 | Train Loss: 0.013280 | Val Loss: 0.577337

Epoch 3639/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00385]
Epoch 3639/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 3639 | Train Loss: 0.023219 | Val Loss: 0.937656

Epoch 3640/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0106]
Epoch 3640/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.81it/s]

End of Epoch 3640 | Train Loss: 0.017161 | Val Loss: 0.541347

Epoch 3641/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.16it/s, loss=0.00913]
Epoch 3641/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.45it/s]

End of Epoch 3641 | Train Loss: 0.020793 | Val Loss: 0.512845

Epoch 3642/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00552]
Epoch 3642/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.10it/s]

End of Epoch 3642 | Train Loss: 0.019840 | Val Loss: 0.425324

Epoch 3643/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.00it/s, loss=0.0024]
Epoch 3643/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.26it/s]

End of Epoch 3643 | Train Loss: 0.017020 | Val Loss: 0.424268

Epoch 3644/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.317]
Epoch 3644/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.53it/s]

End of Epoch 3644 | Train Loss: 0.019454 | Val Loss: 0.699720

Epoch 3645/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 18.00it/s, loss=0.00564]
Epoch 3645/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.55it/s]

End of Epoch 3645 | Train Loss: 0.027684 | Val Loss: 0.344359

Epoch 3646/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.0674]
Epoch 3646/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 3646 | Train Loss: 0.016340 | Val Loss: 0.540881

Epoch 3647/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0181]
Epoch 3647/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 3647 | Train Loss: 0.016896 | Val Loss: 0.570029

Epoch 3648/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0485]
Epoch 3648/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.67it/s]

End of Epoch 3648 | Train Loss: 0.015507 | Val Loss: 0.313702

Epoch 3649/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00421]
Epoch 3649/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.42it/s]

End of Epoch 3649 | Train Loss: 0.019738 | Val Loss: 0.484247

Epoch 3650/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00276]
Epoch 3650/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 3650 | Train Loss: 0.014845 | Val Loss: 0.511831

Epoch 3651/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.66it/s, loss=0.00496]
Epoch 3651/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.93it/s]

End of Epoch 3651 | Train Loss: 0.020153 | Val Loss: 0.506500

Epoch 3652/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.13it/s, loss=0.00197]
Epoch 3652/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.06it/s]

End of Epoch 3652 | Train Loss: 0.019165 | Val Loss: 0.815142

Epoch 3653/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.18it/s, loss=0.00271]
Epoch 3653/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.04it/s]

End of Epoch 3653 | Train Loss: 0.019757 | Val Loss: 0.321531

Epoch 3654/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.20it/s, loss=0.00266]
Epoch 3654/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 3654 | Train Loss: 0.015370 | Val Loss: 0.485475

Epoch 3655/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.0046]
Epoch 3655/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 3655 | Train Loss: 0.014894 | Val Loss: 0.776386

Epoch 3656/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00181]
Epoch 3656/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 3656 | Train Loss: 0.013634 | Val Loss: 0.372097

Epoch 3657/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00268]
Epoch 3657/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.44it/s]

End of Epoch 3657 | Train Loss: 0.018225 | Val Loss: 0.765725

Epoch 3658/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00894]
Epoch 3658/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.02it/s]

End of Epoch 3658 | Train Loss: 0.011104 | Val Loss: 0.827159

Epoch 3659/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00644]
Epoch 3659/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.32it/s]

End of Epoch 3659 | Train Loss: 0.014669 | Val Loss: 0.295302

Epoch 3660/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.131]
Epoch 3660/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.71it/s]

End of Epoch 3660 | Train Loss: 0.017461 | Val Loss: 0.354135

Epoch 3661/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.00564]
Epoch 3661/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.69it/s]

End of Epoch 3661 | Train Loss: 0.021961 | Val Loss: 0.709564

Epoch 3662/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00241]
Epoch 3662/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.50it/s]

End of Epoch 3662 | Train Loss: 0.018592 | Val Loss: 0.316758

Epoch 3663/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00701]
Epoch 3663/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.15it/s]

End of Epoch 3663 | Train Loss: 0.017429 | Val Loss: 0.554536

Epoch 3664/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.00339]
Epoch 3664/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.13it/s]

End of Epoch 3664 | Train Loss: 0.022682 | Val Loss: 0.424083

Epoch 3665/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00231]
Epoch 3665/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.42it/s]

End of Epoch 3665 | Train Loss: 0.015430 | Val Loss: 0.845442

Epoch 3666/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0169]
Epoch 3666/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.04it/s]

End of Epoch 3666 | Train Loss: 0.017119 | Val Loss: 0.557247

Epoch 3667/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00909]
Epoch 3667/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.65it/s]

End of Epoch 3667 | Train Loss: 0.019051 | Val Loss: 0.340725

Epoch 3668/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00211]
Epoch 3668/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.19it/s]

End of Epoch 3668 | Train Loss: 0.015013 | Val Loss: 0.603834

Epoch 3669/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0042]
Epoch 3669/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.21it/s]

End of Epoch 3669 | Train Loss: 0.016376 | Val Loss: 0.499199

Epoch 3670/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00314]
Epoch 3670/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.97it/s]

End of Epoch 3670 | Train Loss: 0.016556 | Val Loss: 0.273013

Epoch 3671/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.52it/s, loss=0.0282]
Epoch 3671/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.24it/s]

End of Epoch 3671 | Train Loss: 0.012415 | Val Loss: 0.374299

Epoch 3672/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.00212]
Epoch 3672/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.45it/s]

End of Epoch 3672 | Train Loss: 0.016861 | Val Loss: 0.948057

Epoch 3673/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00242]
Epoch 3673/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.36it/s]

End of Epoch 3673 | Train Loss: 0.013787 | Val Loss: 0.409433

Epoch 3674/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00291]
Epoch 3674/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.70it/s]

End of Epoch 3674 | Train Loss: 0.013218 | Val Loss: 0.245532

Epoch 3675/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00325]
Epoch 3675/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.71it/s]

End of Epoch 3675 | Train Loss: 0.016708 | Val Loss: 0.133724

Epoch 3676/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00931]
Epoch 3676/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.18it/s]

End of Epoch 3676 | Train Loss: 0.018390 | Val Loss: 0.348241

Epoch 3677/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00458]
Epoch 3677/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.39it/s]

End of Epoch 3677 | Train Loss: 0.022794 | Val Loss: 0.725211

Epoch 3678/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00235]
Epoch 3678/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.70it/s]

End of Epoch 3678 | Train Loss: 0.024028 | Val Loss: 0.514702

Epoch 3679/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00627]
Epoch 3679/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.62it/s]

End of Epoch 3679 | Train Loss: 0.019264 | Val Loss: 0.724361

Epoch 3680/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.00248]
Epoch 3680/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.91it/s]

End of Epoch 3680 | Train Loss: 0.016796 | Val Loss: 0.389132

Epoch 3681/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.0122]
Epoch 3681/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.40it/s]

End of Epoch 3681 | Train Loss: 0.020501 | Val Loss: 0.475419

Epoch 3682/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0211]
Epoch 3682/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.08it/s]

End of Epoch 3682 | Train Loss: 0.015391 | Val Loss: 0.330935

Epoch 3683/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00204]
Epoch 3683/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.85it/s]

End of Epoch 3683 | Train Loss: 0.016802 | Val Loss: 0.143043

Epoch 3684/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0123]
Epoch 3684/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.01it/s]

End of Epoch 3684 | Train Loss: 0.018657 | Val Loss: 0.771207

Epoch 3685/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.046]
Epoch 3685/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.70it/s]

End of Epoch 3685 | Train Loss: 0.020353 | Val Loss: 0.448134

Epoch 3686/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0107]
Epoch 3686/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 3686 | Train Loss: 0.016664 | Val Loss: 0.697659

Epoch 3687/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.77it/s, loss=0.0279]
Epoch 3687/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.10it/s]

End of Epoch 3687 | Train Loss: 0.014936 | Val Loss: 0.888346

Epoch 3688/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00276]
Epoch 3688/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.61it/s]

End of Epoch 3688 | Train Loss: 0.020139 | Val Loss: 0.440262

Epoch 3689/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.018]
Epoch 3689/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.80it/s]

End of Epoch 3689 | Train Loss: 0.018703 | Val Loss: 0.644017

Epoch 3690/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.97it/s, loss=0.00416]
Epoch 3690/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.12it/s]

End of Epoch 3690 | Train Loss: 0.015808 | Val Loss: 0.850560

Epoch 3691/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.0025]
Epoch 3691/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.31it/s]

End of Epoch 3691 | Train Loss: 0.021208 | Val Loss: 0.165703

Epoch 3692/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00229]
Epoch 3692/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.02it/s]

End of Epoch 3692 | Train Loss: 0.011113 | Val Loss: 0.367344

Epoch 3693/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00536]
Epoch 3693/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.33it/s]

End of Epoch 3693 | Train Loss: 0.024142 | Val Loss: 0.339215

Epoch 3694/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.24it/s, loss=0.003]
Epoch 3694/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.71it/s]

End of Epoch 3694 | Train Loss: 0.020240 | Val Loss: 0.856165

Epoch 3695/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00615]
Epoch 3695/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.03it/s]

End of Epoch 3695 | Train Loss: 0.014364 | Val Loss: 0.391603

Epoch 3696/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.0024]
Epoch 3696/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.79it/s]

End of Epoch 3696 | Train Loss: 0.017796 | Val Loss: 0.344493

Epoch 3697/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0109]
Epoch 3697/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.85it/s]

End of Epoch 3697 | Train Loss: 0.016752 | Val Loss: 0.392877

Epoch 3698/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00331]
Epoch 3698/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.04it/s]

End of Epoch 3698 | Train Loss: 0.016011 | Val Loss: 0.356928

Epoch 3699/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00272]
Epoch 3699/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.95it/s]

End of Epoch 3699 | Train Loss: 0.013535 | Val Loss: 0.404097

Epoch 3700/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00422]
Epoch 3700/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.63it/s]

End of Epoch 3700 | Train Loss: 0.021274 | Val Loss: 0.359893

Epoch 3701/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00266]
Epoch 3701/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.68it/s]

End of Epoch 3701 | Train Loss: 0.017276 | Val Loss: 0.358236

Epoch 3702/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00298]
Epoch 3702/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 3702 | Train Loss: 0.015043 | Val Loss: 0.566970

Epoch 3703/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.23it/s, loss=0.00225]
Epoch 3703/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.83it/s]

End of Epoch 3703 | Train Loss: 0.015471 | Val Loss: 0.773067

Epoch 3704/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.37it/s, loss=0.00263]
Epoch 3704/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.80it/s]

End of Epoch 3704 | Train Loss: 0.016623 | Val Loss: 0.576879

Epoch 3705/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.34it/s, loss=0.0222]
Epoch 3705/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.09it/s]

End of Epoch 3705 | Train Loss: 0.021967 | Val Loss: 0.518313

Epoch 3706/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.28it/s, loss=0.00221]
Epoch 3706/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 3706 | Train Loss: 0.019596 | Val Loss: 0.813350

Epoch 3707/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00205]
Epoch 3707/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.22it/s]

End of Epoch 3707 | Train Loss: 0.018145 | Val Loss: 0.266174

Epoch 3708/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00246]
Epoch 3708/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.40it/s]

End of Epoch 3708 | Train Loss: 0.016790 | Val Loss: 0.435248

Epoch 3709/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.63it/s, loss=0.00276]
Epoch 3709/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.04it/s]

End of Epoch 3709 | Train Loss: 0.018959 | Val Loss: 0.469026

Epoch 3710/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00559]
Epoch 3710/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.77it/s]

End of Epoch 3710 | Train Loss: 0.019007 | Val Loss: 0.658017

Epoch 3711/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.00319]
Epoch 3711/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 106.78it/s]

End of Epoch 3711 | Train Loss: 0.020027 | Val Loss: 0.561395

Epoch 3712/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00204]
Epoch 3712/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.40it/s]

End of Epoch 3712 | Train Loss: 0.019985 | Val Loss: 0.502778

Epoch 3713/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00977]
Epoch 3713/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.64it/s]

End of Epoch 3713 | Train Loss: 0.021398 | Val Loss: 0.412028

Epoch 3714/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00231]
Epoch 3714/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.80it/s]

End of Epoch 3714 | Train Loss: 0.017629 | Val Loss: 0.682743

Epoch 3715/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00266]
Epoch 3715/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.43it/s]

End of Epoch 3715 | Train Loss: 0.018472 | Val Loss: 0.443976

Epoch 3716/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00292]
Epoch 3716/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.28it/s]

End of Epoch 3716 | Train Loss: 0.014169 | Val Loss: 0.628028

Epoch 3717/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.80it/s, loss=0.0134]
Epoch 3717/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.41it/s]

End of Epoch 3717 | Train Loss: 0.014619 | Val Loss: 0.485224

Epoch 3718/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00391]
Epoch 3718/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.61it/s]

End of Epoch 3718 | Train Loss: 0.015903 | Val Loss: 0.266577

Epoch 3719/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00262]
Epoch 3719/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 3719 | Train Loss: 0.019572 | Val Loss: 0.395008

Epoch 3720/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00196]
Epoch 3720/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.41it/s]

End of Epoch 3720 | Train Loss: 0.015765 | Val Loss: 0.525327

Epoch 3721/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00298]
Epoch 3721/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.09it/s]

End of Epoch 3721 | Train Loss: 0.018772 | Val Loss: 0.423378

Epoch 3722/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00458]
Epoch 3722/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 104.51it/s]

End of Epoch 3722 | Train Loss: 0.016549 | Val Loss: 0.442478

Epoch 3723/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00287]
Epoch 3723/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 3723 | Train Loss: 0.017967 | Val Loss: 0.550657

Epoch 3724/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00853]
Epoch 3724/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.77it/s]

End of Epoch 3724 | Train Loss: 0.018184 | Val Loss: 0.271210

Epoch 3725/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00693]
Epoch 3725/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 3725 | Train Loss: 0.022393 | Val Loss: 0.366037

Epoch 3726/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.0105]
Epoch 3726/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.69it/s]

End of Epoch 3726 | Train Loss: 0.020510 | Val Loss: 0.654773

Epoch 3727/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.90it/s, loss=0.00734]
Epoch 3727/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.62it/s]

End of Epoch 3727 | Train Loss: 0.016135 | Val Loss: 0.504821

Epoch 3728/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.95it/s, loss=0.00302]
Epoch 3728/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.85it/s]

End of Epoch 3728 | Train Loss: 0.018611 | Val Loss: 0.418933

Epoch 3729/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00279]
Epoch 3729/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.42it/s]

End of Epoch 3729 | Train Loss: 0.016811 | Val Loss: 0.251558

Epoch 3730/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00248]
Epoch 3730/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.87it/s]

End of Epoch 3730 | Train Loss: 0.013653 | Val Loss: 0.308768

Epoch 3731/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.49it/s, loss=0.00384]
Epoch 3731/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.66it/s]

End of Epoch 3731 | Train Loss: 0.017918 | Val Loss: 0.720633

Epoch 3732/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00404]
Epoch 3732/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.35it/s]

End of Epoch 3732 | Train Loss: 0.020074 | Val Loss: 0.428709

Epoch 3733/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.59it/s, loss=0.00798]
Epoch 3733/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.51it/s]

End of Epoch 3733 | Train Loss: 0.018328 | Val Loss: 0.401589

Epoch 3734/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.65it/s, loss=0.00334]
Epoch 3734/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.49it/s]

End of Epoch 3734 | Train Loss: 0.018327 | Val Loss: 0.485525

Epoch 3735/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00412]
Epoch 3735/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.34it/s]

End of Epoch 3735 | Train Loss: 0.018431 | Val Loss: 0.389021

Epoch 3736/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.69it/s, loss=0.0542]
Epoch 3736/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.16it/s]

End of Epoch 3736 | Train Loss: 0.024760 | Val Loss: 0.332803

Epoch 3737/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.82it/s, loss=0.0825]
Epoch 3737/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.60it/s]

End of Epoch 3737 | Train Loss: 0.016758 | Val Loss: 0.439915

Epoch 3738/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.00571]
Epoch 3738/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.07it/s]

End of Epoch 3738 | Train Loss: 0.026575 | Val Loss: 0.297097

Epoch 3739/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.0107]
Epoch 3739/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.50it/s]

End of Epoch 3739 | Train Loss: 0.015832 | Val Loss: 0.585173

Epoch 3740/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.0465]
Epoch 3740/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.63it/s]

End of Epoch 3740 | Train Loss: 0.020799 | Val Loss: 0.392949

Epoch 3741/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00309]
Epoch 3741/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.60it/s]

End of Epoch 3741 | Train Loss: 0.023058 | Val Loss: 0.481280

Epoch 3742/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.00406]
Epoch 3742/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.23it/s]

End of Epoch 3742 | Train Loss: 0.017786 | Val Loss: 0.576972

Epoch 3743/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00215]
Epoch 3743/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.06it/s]

End of Epoch 3743 | Train Loss: 0.015620 | Val Loss: 0.662013

Epoch 3744/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00257]
Epoch 3744/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 3744 | Train Loss: 0.021150 | Val Loss: 0.365586

Epoch 3745/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00249]
Epoch 3745/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.83it/s]

End of Epoch 3745 | Train Loss: 0.012280 | Val Loss: 0.329443

Epoch 3746/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00433]
Epoch 3746/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.85it/s]

End of Epoch 3746 | Train Loss: 0.011861 | Val Loss: 0.254262

Epoch 3747/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00227]
Epoch 3747/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 3747 | Train Loss: 0.022745 | Val Loss: 0.507307

Epoch 3748/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00377]
Epoch 3748/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.81it/s]

End of Epoch 3748 | Train Loss: 0.017915 | Val Loss: 0.724212

Epoch 3749/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0108]
Epoch 3749/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 3749 | Train Loss: 0.014628 | Val Loss: 0.628538

Epoch 3750/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.02it/s, loss=0.00256]
Epoch 3750/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.64it/s]

End of Epoch 3750 | Train Loss: 0.014747 | Val Loss: 0.791101

Epoch 3751/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00843]
Epoch 3751/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.46it/s]

End of Epoch 3751 | Train Loss: 0.014189 | Val Loss: 0.492182

Epoch 3752/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.44it/s, loss=0.0101]
Epoch 3752/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.00it/s]

End of Epoch 3752 | Train Loss: 0.020845 | Val Loss: 0.660199

Epoch 3753/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00458]
Epoch 3753/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.08it/s]

End of Epoch 3753 | Train Loss: 0.020822 | Val Loss: 0.847109

Epoch 3754/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.00425]
Epoch 3754/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.73it/s]

End of Epoch 3754 | Train Loss: 0.017905 | Val Loss: 0.379183

Epoch 3755/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.00295]
Epoch 3755/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.49it/s]

End of Epoch 3755 | Train Loss: 0.020890 | Val Loss: 0.750702

Epoch 3756/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0033]
Epoch 3756/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.40it/s]

End of Epoch 3756 | Train Loss: 0.022303 | Val Loss: 0.484747

Epoch 3757/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00256]
Epoch 3757/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.16it/s]

End of Epoch 3757 | Train Loss: 0.020001 | Val Loss: 0.398952

Epoch 3758/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.00289]
Epoch 3758/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 103.50it/s]

End of Epoch 3758 | Train Loss: 0.016277 | Val Loss: 0.409237

Epoch 3759/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00259]
Epoch 3759/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.22it/s]

End of Epoch 3759 | Train Loss: 0.017832 | Val Loss: 0.510647

Epoch 3760/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.0381]
Epoch 3760/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.96it/s]

End of Epoch 3760 | Train Loss: 0.020530 | Val Loss: 0.661144

Epoch 3761/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00774]
Epoch 3761/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.79it/s]

End of Epoch 3761 | Train Loss: 0.019871 | Val Loss: 0.388481

Epoch 3762/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.01]
Epoch 3762/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.75it/s]

End of Epoch 3762 | Train Loss: 0.018296 | Val Loss: 0.410463

Epoch 3763/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.00207]
Epoch 3763/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.45it/s]

End of Epoch 3763 | Train Loss: 0.016544 | Val Loss: 0.484442

Epoch 3764/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00298]
Epoch 3764/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.54it/s]

End of Epoch 3764 | Train Loss: 0.017682 | Val Loss: 0.260792

Epoch 3765/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00244]
Epoch 3765/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.98it/s]

End of Epoch 3765 | Train Loss: 0.011095 | Val Loss: 0.668084

Epoch 3766/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.00389]
Epoch 3766/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.63it/s]

End of Epoch 3766 | Train Loss: 0.016354 | Val Loss: 0.332094

Epoch 3767/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.71it/s, loss=0.00277]
Epoch 3767/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.47it/s]

End of Epoch 3767 | Train Loss: 0.016637 | Val Loss: 0.434833

Epoch 3768/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00442]
Epoch 3768/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.86it/s]

End of Epoch 3768 | Train Loss: 0.018143 | Val Loss: 0.259929

Epoch 3769/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00227]
Epoch 3769/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.87it/s]

End of Epoch 3769 | Train Loss: 0.020192 | Val Loss: 0.661762

Epoch 3770/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.07it/s, loss=0.0101]
Epoch 3770/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.78it/s]

End of Epoch 3770 | Train Loss: 0.014561 | Val Loss: 0.733088

Epoch 3771/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00611]
Epoch 3771/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.26it/s]

End of Epoch 3771 | Train Loss: 0.015654 | Val Loss: 0.247475

Epoch 3772/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.64it/s, loss=0.00402]
Epoch 3772/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.54it/s]

End of Epoch 3772 | Train Loss: 0.016383 | Val Loss: 0.830836

Epoch 3773/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00241]
Epoch 3773/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.80it/s]

End of Epoch 3773 | Train Loss: 0.020816 | Val Loss: 0.366261

Epoch 3774/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00725]
Epoch 3774/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.02it/s]

End of Epoch 3774 | Train Loss: 0.016045 | Val Loss: 0.912004

Epoch 3775/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.00227]
Epoch 3775/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.48it/s]

End of Epoch 3775 | Train Loss: 0.016076 | Val Loss: 0.377945

Epoch 3776/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.83it/s, loss=0.0243]
Epoch 3776/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.92it/s]

End of Epoch 3776 | Train Loss: 0.019100 | Val Loss: 0.441567

Epoch 3777/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.88it/s, loss=0.00351]
Epoch 3777/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 110.83it/s]

End of Epoch 3777 | Train Loss: 0.019006 | Val Loss: 0.739669

Epoch 3778/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00254]
Epoch 3778/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.84it/s]

End of Epoch 3778 | Train Loss: 0.013877 | Val Loss: 0.409671

Epoch 3779/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.00227]
Epoch 3779/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.97it/s]

End of Epoch 3779 | Train Loss: 0.019910 | Val Loss: 0.554626

Epoch 3780/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.85it/s, loss=0.0124]
Epoch 3780/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.73it/s]

End of Epoch 3780 | Train Loss: 0.018637 | Val Loss: 0.249894

Epoch 3781/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00335]
Epoch 3781/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.50it/s]

End of Epoch 3781 | Train Loss: 0.021697 | Val Loss: 0.472171

Epoch 3782/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.04it/s, loss=0.00563]
Epoch 3782/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.04it/s]

End of Epoch 3782 | Train Loss: 0.016796 | Val Loss: 0.511008

Epoch 3783/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.00438]
Epoch 3783/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.65it/s]

End of Epoch 3783 | Train Loss: 0.024465 | Val Loss: 0.411046

Epoch 3784/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.0024]
Epoch 3784/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.51it/s]

End of Epoch 3784 | Train Loss: 0.022144 | Val Loss: 0.345174

Epoch 3785/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00502]
Epoch 3785/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 105.33it/s]

End of Epoch 3785 | Train Loss: 0.020265 | Val Loss: 0.342673

Epoch 3786/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00311]
Epoch 3786/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.37it/s]

End of Epoch 3786 | Train Loss: 0.019728 | Val Loss: 0.426674

Epoch 3787/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.62it/s, loss=0.0119]
Epoch 3787/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.60it/s]

End of Epoch 3787 | Train Loss: 0.018167 | Val Loss: 0.433594

Epoch 3788/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00238]
Epoch 3788/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.97it/s]

End of Epoch 3788 | Train Loss: 0.016180 | Val Loss: 0.410392

Epoch 3789/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.73it/s, loss=0.0031]
Epoch 3789/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 111.27it/s]

End of Epoch 3789 | Train Loss: 0.020408 | Val Loss: 0.398448

Epoch 3790/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.78it/s, loss=0.00307]
Epoch 3790/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.33it/s]

End of Epoch 3790 | Train Loss: 0.014096 | Val Loss: 0.276526

Epoch 3791/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.72it/s, loss=0.00374]
Epoch 3791/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.24it/s]

End of Epoch 3791 | Train Loss: 0.014705 | Val Loss: 0.306963

Epoch 3792/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.00386]
Epoch 3792/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.31it/s]

End of Epoch 3792 | Train Loss: 0.020770 | Val Loss: 0.269093

Epoch 3793/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00293]
Epoch 3793/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.62it/s]

End of Epoch 3793 | Train Loss: 0.019465 | Val Loss: 0.311396

Epoch 3794/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.91it/s, loss=0.0475]
Epoch 3794/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.35it/s]

End of Epoch 3794 | Train Loss: 0.015375 | Val Loss: 0.320392

Epoch 3795/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.0024]
Epoch 3795/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.01it/s]

End of Epoch 3795 | Train Loss: 0.017200 | Val Loss: 0.608350

Epoch 3796/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.70it/s, loss=0.00485]
Epoch 3796/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.99it/s]

End of Epoch 3796 | Train Loss: 0.013699 | Val Loss: 0.456077

Epoch 3797/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.54it/s, loss=0.00241]
Epoch 3797/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.52it/s]

End of Epoch 3797 | Train Loss: 0.016790 | Val Loss: 0.528783

Epoch 3798/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00313]
Epoch 3798/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 102.94it/s]

End of Epoch 3798 | Train Loss: 0.018107 | Val Loss: 0.298216

Epoch 3799/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.75it/s, loss=0.00233]
Epoch 3799/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.46it/s]

End of Epoch 3799 | Train Loss: 0.016618 | Val Loss: 0.887733

Epoch 3800/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.03it/s, loss=0.053]
Epoch 3800/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.23it/s]

End of Epoch 3800 | Train Loss: 0.013728 | Val Loss: 0.446279

Epoch 3801/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.99it/s, loss=0.0108]
Epoch 3801/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.43it/s]

End of Epoch 3801 | Train Loss: 0.015371 | Val Loss: 0.650187

Epoch 3802/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.87it/s, loss=0.00266]
Epoch 3802/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 108.27it/s]

End of Epoch 3802 | Train Loss: 0.020869 | Val Loss: 0.339642

Epoch 3803/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.00241]
Epoch 3803/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.59it/s]

End of Epoch 3803 | Train Loss: 0.029043 | Val Loss: 0.550094

Epoch 3804/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.09it/s, loss=0.00313]
Epoch 3804/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.28it/s]

End of Epoch 3804 | Train Loss: 0.017650 | Val Loss: 0.594796

Epoch 3805/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.76it/s, loss=0.00265]
Epoch 3805/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.67it/s]

End of Epoch 3805 | Train Loss: 0.019787 | Val Loss: 0.576636

Epoch 3806/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.93it/s, loss=0.00467]
Epoch 3806/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.00it/s]

End of Epoch 3806 | Train Loss: 0.022297 | Val Loss: 0.441677

Epoch 3807/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.89it/s, loss=0.00339]
Epoch 3807/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.89it/s]

End of Epoch 3807 | Train Loss: 0.020120 | Val Loss: 0.253000

Epoch 3808/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.0487]
Epoch 3808/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.97it/s]

End of Epoch 3808 | Train Loss: 0.018177 | Val Loss: 0.348669

Epoch 3809/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.05it/s, loss=0.00266]
Epoch 3809/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.27it/s]

End of Epoch 3809 | Train Loss: 0.015638 | Val Loss: 0.855729

Epoch 3810/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.94it/s, loss=0.00225]
Epoch 3810/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.12it/s]

End of Epoch 3810 | Train Loss: 0.023414 | Val Loss: 0.378369

Epoch 3811/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.00243]
Epoch 3811/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 115.68it/s]

End of Epoch 3811 | Train Loss: 0.017438 | Val Loss: 0.644071

Epoch 3812/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.58it/s, loss=0.231]
Epoch 3812/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.01it/s]

End of Epoch 3812 | Train Loss: 0.020301 | Val Loss: 0.450298

Epoch 3813/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.12it/s, loss=0.00241]
Epoch 3813/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 117.18it/s]

End of Epoch 3813 | Train Loss: 0.023751 | Val Loss: 0.456007

Epoch 3814/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.98it/s, loss=0.0027]
Epoch 3814/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.38it/s]

End of Epoch 3814 | Train Loss: 0.016091 | Val Loss: 0.712473

Epoch 3815/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.01it/s, loss=0.0333]
Epoch 3815/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 112.93it/s]

End of Epoch 3815 | Train Loss: 0.015821 | Val Loss: 0.438622

Epoch 3816/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.10it/s, loss=0.0632]
Epoch 3816/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 113.35it/s]

End of Epoch 3816 | Train Loss: 0.011886 | Val Loss: 0.464845

Epoch 3817/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.86it/s, loss=0.00212]
Epoch 3817/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 109.38it/s]

End of Epoch 3817 | Train Loss: 0.016450 | Val Loss: 0.390300

Epoch 3818/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.79it/s, loss=0.00431]
Epoch 3818/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 107.41it/s]

End of Epoch 3818 | Train Loss: 0.015643 | Val Loss: 0.223083

Epoch 3819/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.81it/s, loss=0.00319]
Epoch 3819/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 77.35it/s]

End of Epoch 3819 | Train Loss: 0.016287 | Val Loss: 0.598966

Epoch 3820/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.14it/s, loss=0.014]
Epoch 3820/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.85it/s]

End of Epoch 3820 | Train Loss: 0.017516 | Val Loss: 0.684840

Epoch 3821/10000 [Train]: 100%|██████████| 90/90 [00:04<00:00, 18.06it/s, loss=0.00339]
Epoch 3821/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.19it/s]

End of Epoch 3821 | Train Loss: 0.022262 | Val Loss: 0.558153

Epoch 3822/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.96it/s, loss=0.0304]
Epoch 3822/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.48it/s]

End of Epoch 3822 | Train Loss: 0.018280 | Val Loss: 0.145634

Epoch 3823/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.92it/s, loss=0.0034]
Epoch 3823/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 114.84it/s]

End of Epoch 3823 | Train Loss: 0.017051 | Val Loss: 0.599656

Epoch 3824/10000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 17.84it/s, loss=0.0019]
Epoch 3824/10000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 116.94it/s]

End of Epoch 3824 | Train Loss: 0.013750 | Val Loss: 0.224579

Epoch 3825/10000 [Train]:  62%|██████▏   | 56/90 [00:03<00:01, 17.95it/s, loss=0.00391]

In [ ]:
batch = next(iter(test_loader))
print(f"x: {batch['x'].shape}, x_cond: {batch['x_cond'].shape}, dates: {batch['dates'].shape}")

In [ ]:
def transform_dates(dates: torch.Tensor) -> pd.DatetimeIndex:
    dates_np = dates.cpu().numpy()
    dates_pd = pd.to_datetime(dates_np.flatten(), unit='ns')
    return dates_pd

In [ ]:
transform_dates(batch['dates'])

In [ ]:
def autoregressive(x: np.ndarray, x_cond: np.ndarray, steps: int, n_samples: int):
    B, W, A, F_target = x.shape
    period_curr = W - steps
    device = next(engine.model.parameters()).device

    x_curr = torch.as_tensor(x[:, :period_curr, :, :], dtype=torch.float32).to(device)
    x_cond_curr = torch.as_tensor(x_cond[:, :period_curr, :, :], dtype=torch.float32).to(device)

    x_curr = x_curr.to(device)
    x_cond_curr = x_cond_curr.to(device)

    # Monte Carlo Build
    x_curr = x_curr.repeat(n_samples, 1, 1, 1)
    x_cond_curr = x_cond_curr.repeat(n_samples, 1, 1, 1)

    results = []
    print(f"Start Auto-regression: Initial W={period_curr}, Target Steps={steps}")

    pbar = tqdm(range(steps))
    for i in pbar:
        pbar.set_description(f"window size {x_curr.shape[1]}...")
        batch = {
            "x": x_curr,
            "x_cond": x_cond_curr
        }

        _, next_step_x, _, _ = engine.simulate(batch, steps=1, inverse_scale=False)
        
        results.append(next_step_x)
        
        x_curr = torch.cat([x_curr, next_step_x], dim=1)
            
        idx = period_curr + i
            
        next_cond_slice_np = x_cond[:, idx : idx+1, :, :]
            
        next_cond_slice = torch.as_tensor(next_cond_slice_np, dtype=torch.float32).to(device)
        next_cond_slice = next_cond_slice.repeat(n_samples, 1, 1, 1)

        x_cond_curr = torch.cat([x_cond_curr, next_cond_slice], dim=1)

    scaled_sim_genai = torch.cat(results, dim=1).cpu().numpy()
    sim_genai, sim_genai_cond = inverse_scale_pair(scaled_sim_genai, x_cond_curr[:, -steps:, : ,:], scaler)
    
    scaled_full_sim_genai = x_curr.detach().cpu().numpy()
    full_sim_genai, full_sim_genai_cond = inverse_scale_pair(scaled_full_sim_genai, x_cond_curr, scaler)
    
    return full_sim_genai, sim_genai, full_sim_genai_cond, sim_genai_cond

In [ ]:
full_sim_genai, sim_genai, _, _ = autoregressive(batch['x'], batch['x_cond'], 8, 1000)
print(f"x_curr: {x_curr.shape}, final_prediction: {final_prediction.shape}")

In [ ]:
gt, gt_cond = inverse_scale_pair(batch['x'], batch['x_cond'], scaler)
stats_batch = {
    'x': torch.as_tensor(gt).to(device),
    'x_cond': torch.as_tensor(gt_cond).to(device)
}
sim_stats = engine.gbm_simulate(stats_batch, steps=8, n_samples=1000)
sim_stats.shape

In [ ]:
rand_ind = np.random.randint(0, len(sim_genai))
sim_genai_sample = sim_genai[rand_ind].squeeze(-1)
sim_stats_sample = sim_stats[rand_ind].squeeze(-1)
print(f"sim_genai_sample: {sim_genai_sample.shape}, sim_stats_sample: {sim_stats_sample.shape}")

In [ ]:
dates = transform_dates(batch['dates'])
dates.shape

In [ ]:
engine.benchmark(gt=gt, sim_genai=sim_genai_sample, sim_stats=sim_stats_sample, dates=dates)