# Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import logging
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
import talib as ta
from torch import optim
from torch.utils.data import DataLoader, Dataset, TensorDataset, random_split
from tqdm import tqdm
from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.optim import AdamW
from utils import scale, inverse_scale, inverse_scale_pair, inspect
from utils.paths import CHECKPOINTS_DIR
from pypfopt import risk_models, expected_returns, plotting, EfficientFrontier

# Own Libs
from config import *
from entities import *
from strategies import *
from datasets import *
from engine import Engine
from models import DiffusionTransformer, Diffusion

# Setup

In [2]:
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('matplotlib').setLevel(logging.WARNING)

In [3]:
cfg = TrainConfig(epochs=1000, window_size=64, steps_to_sim=12, num_sims=100)
window_size = cfg.window_size
device = cfg.device
batch_size = cfg.batch_size
epochs = cfg.epochs
sim_steps = cfg.steps_to_sim
num_sims = cfg.num_sims

# Optimizer
weight_decay = cfg.optimizer.weight_decay
lr = cfg.optimizer.lr

time_range = {
    'start_date': '2021-01-01',
    'end_date': '2024-12-31'
}

ddpm = {
    'timesteps': int(1000),
    'beta_start': 0.0001,
    'beta_end': 0.02
}

ddpm_transformer = {
    'window_size': window_size,
    'd_model': 64,
    'nhead': 4,
    'num_layers': 64,
    'dim_feedforward': 512,
    'dropout': 0.1
}

The history saving thread hit an unexpected error (OperationalError('database is locked')).History will not be written to the database.

# Data [N, W, A, F]
**[N, T, A, F]** means: 
* **N**: Num of Window or Num of Batch
* **W**: Window
* **A**: Assets
* **F**: Features or Channels

In [4]:
def time_range_info(df):
    info = (df.index.min(), df.index.max())
    print(f"Data range: {info[0]} to {info[1]}")
    
    duration = df.index.max() - df.index.min()
    print(f"Total duration: {duration}")

def time_range_mask(df, start_date, end_date):
    mask = (df.index >= start_date) & (df.index <= end_date)
    return mask

In [5]:
symbols = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO']
freq = "1d"

# Basket
basket = Basket(symbols=symbols)
basket.load_all_assets(freq=freq)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

DEBUG:entities.basket:Initialized Asset Basket: ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO'] with 0 assets which loaded.
INFO:entities.basket:Starting batch load for 14 symbols...
DEBUG:entities.basket:Attempting to load AAPL...
DEBUG:entities.asset:Initialized Asset: AAPL with 2724 rows.
INFO:entities.basket:Successfully loaded AAPL (2724 rows).
DEBUG:entities.basket:Attempting to load TSLA...
DEBUG:entities.asset:Initialized Asset: TSLA with 2760 rows.
INFO:entities.basket:Successfully loaded TSLA (2760 rows).
DEBUG:entities.basket:Attempting to load MSFT...
DEBUG:entities.asset:Initialized Asset: MSFT with 2724 rows.
INFO:entities.basket:Successfully loaded MSFT (2724 rows).
DEBUG:entities.basket:Attempting to load NVDA...
DEBUG:entities.asset:Initialized Asset: NVDA with 2724 rows.
INFO:entities.basket:Successfully loaded NVDA (2724 rows).
DEBUG:entities.basket:Attempting to load GOOGL...
DEBUG:entities.asset:Initialized Asset: GOOGL with 2760 rows.
INFO:entities.basket:Successfully loaded GOOGL (2760 rows).
DEBUG:entities.basket:Attempting to load AMZN...
DEBUG:entities.asset:Initialized Asset: AMZN with 2760 rows.
INFO:entities.basket:Successfully loaded AMZN (2760 rows).
DEBUG:entities.basket:Attempting to load GOOG...
DEBUG:entities.asset:Initialized Asset: GOOG with 1464 rows.
INFO:entities.basket:Successfully loaded GOOG (1464 rows).
DEBUG:entities.basket:Attempting to load META...
DEBUG:entities.asset:Initialized Asset: META with 2760 rows.
INFO:entities.basket:Successfully loaded META (2760 rows).
DEBUG:entities.basket:Attempting to load AVGO...
DEBUG:entities.asset:Initialized Asset: AVGO with 2724 rows.
INFO:entities.basket:Successfully loaded AVGO (2724 rows).
DEBUG:entities.basket:Attempting to load ORCL...
DEBUG:entities.asset:Initialized Asset: ORCL with 2724 rows.
INFO:entities.basket:Successfully loaded ORCL (2724 rows).
DEBUG:entities.basket:Attempting to load CRM...
DEBUG:entities.asset:Initialized Asset: CRM with 2724 rows.
INFO:entities.basket:Successfully loaded CRM (2724 rows).
DEBUG:entities.basket:Attempting to load ADBE...
DEBUG:entities.asset:Initialized Asset: ADBE with 2724 rows.
INFO:entities.basket:Successfully loaded ADBE (2724 rows).
DEBUG:entities.basket:Attempting to load AMD...
DEBUG:entities.asset:Initialized Asset: AMD with 2724 rows.
INFO:entities.basket:Successfully loaded AMD (2724 rows).
DEBUG:entities.basket:Attempting to load CSCO...
DEBUG:entities.asset:Initialized Asset: CSCO with 2724 rows.
INFO:entities.basket:Successfully loaded CSCO (2724 rows).
INFO:entities.basket:Batch load complete. Success: 14/14. Total assets in basket: 14

Basket data shape: (2760, 70)

                 AAPL                                                \
                Close       High        Low       Open       Volume
Date
2015-01-02  24.261047  24.729270  23.821672  24.718174  212818400.0
2015-01-05  23.577574  24.110150  23.391173  24.030263  257142000.0
2015-01-06  23.579794  23.839424  23.218085  23.641928  263188400.0
2015-01-07  23.910433  24.010290  23.677430  23.788384  160423600.0
2015-01-08  24.829119  24.886815  24.121236  24.238848  237458000.0

                 TSLA                                             ...   AMD  \
                Close       High        Low       Open    Volume  ... Close
Date                                                              ...
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  ...  2.67
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  ...  2.66
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  ...  2.63
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  ...  2.58
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  ...  2.61

                                               CSCO                        \
            High   Low  Open      Volume      Close       High        Low
Date
2015-01-02  2.67  2.67  2.67         0.0  19.815605  20.181631  19.650534
2015-01-05  2.70  2.64  2.67   8878200.0  19.420874  19.700776  19.377812
2015-01-06  2.66  2.55  2.65  13912500.0  19.413698  19.865848  19.406522
2015-01-07  2.65  2.54  2.63  12377600.0  19.593126  19.664896  19.363463
2015-01-08  2.65  2.56  2.59  11136600.0  19.743843  20.160107  19.715135


                 Open      Volume
Date
2015-01-02  19.995029  22926500.0
2015-01-05  19.607475  29460600.0
2015-01-06  19.478291  47297600.0
2015-01-07  19.478295  27570800.0
2015-01-08  19.765374  40907000.0

[5 rows x 70 columns]

## Time Range Custom

In [6]:
time_range_info(basket.data)

for symbol, asset in basket.assets.items():
    mask = time_range_mask(asset.data, time_range['start_date'], time_range['end_date'])
    asset.data = asset.data[mask]

time_range_info(basket.data)

Data range: 2015-01-02 00:00:00 to 2025-12-22 00:00:00
Total duration: 4007 days 00:00:00
Data range: 2021-01-04 00:00:00 to 2024-12-31 00:00:00
Total duration: 1457 days 00:00:00

## Features/Channels ($F$)
1. Find Joint Distribution $F_{\text{date\ A}} \cap F_{\text{date\ B}}$ with intersection
2. Select $F$ to norm as Return values

In [7]:
targets = ["Close"]
features = basket.get_unique_features()
print(f"Features:\t{features}\nTargets:\t{targets}")

Features:	['Close', 'High', 'Low', 'Open', 'Volume']
Targets:	['Close']

In [8]:
print(f"Basket data shape before Joint: {basket.data.shape}")

joint_strategy = IntersectionStrategy()
basket.align(joint_strategy)

print(f"Basket data shape after Joint: {basket.data.shape}")

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 1005 rows
DEBUG:entities.basket:Aligned data shape: (1005, 70)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 1005)

Basket data shape before Joint: (1005, 70)
Basket data shape after Joint: (1005, 70)

In [9]:
basket.to_returns(features=targets, log=True, keep=False)
targets = basket.get_keyword_features("Returns")
features = basket.get_unique_features()

print(f"Features:\t{features}\nTargets:\t{targets}")
basket.data.head(5)

DEBUG:entities.asset:AAPL converted to Returns (log=True)
DEBUG:entities.asset:TSLA converted to Returns (log=True)
DEBUG:entities.asset:MSFT converted to Returns (log=True)
DEBUG:entities.asset:NVDA converted to Returns (log=True)
DEBUG:entities.asset:GOOGL converted to Returns (log=True)
DEBUG:entities.asset:AMZN converted to Returns (log=True)
DEBUG:entities.asset:GOOG converted to Returns (log=True)
DEBUG:entities.asset:META converted to Returns (log=True)
DEBUG:entities.asset:AVGO converted to Returns (log=True)
DEBUG:entities.asset:ORCL converted to Returns (log=True)
DEBUG:entities.asset:CRM converted to Returns (log=True)
DEBUG:entities.asset:ADBE converted to Returns (log=True)
DEBUG:entities.asset:AMD converted to Returns (log=True)
DEBUG:entities.asset:CSCO converted to Returns (log=True)

Features:	['Close_Log_Returns', 'High', 'Low', 'Open', 'Volume']
Targets:	{'Close_Log_Returns'}

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                  TSLA                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  246.946671  239.733337  241.220001   96735600          0.007291
2021-01-06  258.000000  249.699997  252.830002  134100000          0.027995
2021-01-07  272.329987  258.399994  259.209991  154496700          0.076448
2021-01-08  294.829987  279.463318  285.333344  225166500          0.075481
2021-01-11  284.809998  267.873322  283.133331  177904800         -0.081442

            ...        AMD                                                    \
            ...       High        Low       Open    Volume Close_Log_Returns
Date        ...
2021-01-05  ...  93.209999  91.410004  92.099998  34208000          0.005079
2021-01-06  ...  92.279999  89.459999  91.620003  51911700         -0.026654
2021-01-07  ...  95.510002  91.199997  91.330002  42897200          0.052090
2021-01-08  ...  96.400002  93.269997  95.980003  39816400         -0.006114
2021-01-11  ...  99.230003  93.760002  94.029999  48600200          0.027839

                 CSCO
                 High        Low       Open    Volume Close_Log_Returns
Date
2021-01-05  38.335017  37.734811  37.995770  17763700          0.000455
2021-01-06  39.030909  38.178440  38.387210  21823100          0.009505
2021-01-07  39.239677  38.422000  38.448099  18218800          0.012534
2021-01-08  39.500638  38.491593  38.691662  20936300          0.002222
2021-01-11  39.970367  39.161391  39.274475  25058200          0.006636

[5 rows x 70 columns]

## Add Indicators as Features ($F$)

In [10]:
# Indicator
time_prd = 20
fast_prd, slow_prd, signal_prd = 12, 26, 9

for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        s = df[target]
        
        df[f"SMA_{time_prd} {target}"] = ta.SMA(s, timeperiod=time_prd)
        df[f"EMA_{time_prd} {target}"] = ta.EMA(s, timeperiod=time_prd)
        df[f"RSI_{time_prd} {target}"] = ta.RSI(s, timeperiod=time_prd)
        
        macd, signal, hist = ta.MACD(s, fastperiod=fast_prd, slowperiod=slow_prd, signalperiod=signal_prd)
        df[f"MACD {target}"] = macd
        df[f"MACD_Sig {target}"] = signal
        df[f"MACD_Hist {target}"] = hist

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (1004, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-01-05                      NaN                    NaN
2021-01-06                      NaN                    NaN
2021-01-07                      NaN                    NaN
2021-01-08                      NaN                    NaN
2021-01-11                      NaN                    NaN

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-01-05                        NaN  ...  37.734811  37.995770  17763700
2021-01-06                        NaN  ...  38.178440  38.387210  21823100
2021-01-07                        NaN  ...  38.422000  38.448099  18218800
2021-01-08                        NaN  ...  38.491593  38.691662  20936300
2021-01-11                        NaN  ...  39.161391  39.274475  25058200

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-01-05          0.000455                      NaN
2021-01-06          0.009505                      NaN
2021-01-07          0.012534                      NaN
2021-01-08          0.002222                      NaN
2021-01-11          0.006636                      NaN

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-01-05                    NaN                        NaN
2021-01-06                    NaN                        NaN
2021-01-07                    NaN                        NaN
2021-01-08                    NaN                        NaN
2021-01-11                    NaN                        NaN


           MACD_Hist Close_Log_Returns
Date
2021-01-05                         NaN
2021-01-06                         NaN
2021-01-07                         NaN
2021-01-08                         NaN
2021-01-11                         NaN

[5 rows x 154 columns]

## Additional! Shift data for future simulation (forward)

In [11]:
for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        df[f"SMA_{time_prd} {target}"] = df[f"SMA_{time_prd} {target}"].shift(1)
        df[f"EMA_{time_prd} {target}"] = df[f"EMA_{time_prd} {target}"].shift(1)
        df[f"RSI_{time_prd} {target}"] = df[f"RSI_{time_prd} {target}"].shift(1)
        df[f"MACD {target}"] = df[f"MACD {target}"].shift(1)
        df[f"MACD_Sig {target}"] = df[f"MACD_Sig {target}"].shift(1)
        df[f"MACD_Hist {target}"] = df[f"MACD_Hist {target}"].shift(1)

    asset.data = df.dropna() 
    
print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (970, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-02-24  122.527972  119.278390  121.922948  111039900         -0.004060
2021-02-25  123.406232  117.629191  121.669217  148199500         -0.035402
2021-02-26  121.835107  118.273246  119.629680  164560400          0.002229
2021-03-01  124.840766  119.824887  120.761704  116307900          0.052452
2021-03-02  125.611668  121.991258  125.309156  102260900         -0.021115

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                -0.006281                -0.004764
2021-02-25                -0.006568                -0.004697
2021-02-26                -0.007952                -0.007621
2021-03-01                -0.006060                -0.006683
2021-03-02                -0.001531                -0.001051

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                49.443327              -0.005006
2021-02-25                49.042061              -0.004288
2021-02-26                44.959599              -0.006177
2021-03-01                50.199121              -0.004584
2021-03-02                56.073523               0.000722

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-02-24                  -0.005451  ...  39.178786  39.352760  17823600
2021-02-25                  -0.005218  ...  39.352752  39.657204  21916700
2021-02-26                  -0.005410  ...  38.935217  39.648511  22144900
2021-03-01                  -0.005245  ...  39.335356  39.335356  17394100
2021-03-02                  -0.004051  ...  39.509325  39.952959  14833000

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24          0.005041                 0.000530
2021-02-25         -0.004822                 0.000527
2021-02-26         -0.014382                -0.000197
2021-03-01          0.023131                -0.000521
2021-03-02         -0.008749                 0.001481

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.001497                50.527952
2021-02-25                -0.000874                51.224838
2021-02-26                -0.001250                49.039717
2021-03-01                -0.002501                46.994221
2021-03-02                -0.000060                54.783902

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.001681                  -0.000759
2021-02-25              -0.000967                  -0.000801
2021-02-26              -0.001184                  -0.000877
2021-03-01              -0.002102                  -0.001122
2021-03-02               0.000194                  -0.000859


           MACD_Hist Close_Log_Returns
Date
2021-02-24                   -0.000923
2021-02-25                   -0.000167
2021-02-26                   -0.000307
2021-03-01                   -0.000980
2021-03-02                    0.001053

[5 rows x 154 columns]

In [12]:
basket.align(joint_strategy)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 970 rows
DEBUG:entities.basket:Aligned data shape: (970, 154)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 970)

Basket data shape: (970, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-02-24  122.527972  119.278390  121.922948  111039900         -0.004060
2021-02-25  123.406232  117.629191  121.669217  148199500         -0.035402
2021-02-26  121.835107  118.273246  119.629680  164560400          0.002229
2021-03-01  124.840766  119.824887  120.761704  116307900          0.052452
2021-03-02  125.611668  121.991258  125.309156  102260900         -0.021115

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                -0.006281                -0.004764
2021-02-25                -0.006568                -0.004697
2021-02-26                -0.007952                -0.007621
2021-03-01                -0.006060                -0.006683
2021-03-02                -0.001531                -0.001051

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                49.443327              -0.005006
2021-02-25                49.042061              -0.004288
2021-02-26                44.959599              -0.006177
2021-03-01                50.199121              -0.004584
2021-03-02                56.073523               0.000722

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-02-24                  -0.005451  ...  39.178786  39.352760  17823600
2021-02-25                  -0.005218  ...  39.352752  39.657204  21916700
2021-02-26                  -0.005410  ...  38.935217  39.648511  22144900
2021-03-01                  -0.005245  ...  39.335356  39.335356  17394100
2021-03-02                  -0.004051  ...  39.509325  39.952959  14833000

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24          0.005041                 0.000530
2021-02-25         -0.004822                 0.000527
2021-02-26         -0.014382                -0.000197
2021-03-01          0.023131                -0.000521
2021-03-02         -0.008749                 0.001481

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.001497                50.527952
2021-02-25                -0.000874                51.224838
2021-02-26                -0.001250                49.039717
2021-03-01                -0.002501                46.994221
2021-03-02                -0.000060                54.783902

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.001681                  -0.000759
2021-02-25              -0.000967                  -0.000801
2021-02-26              -0.001184                  -0.000877
2021-03-01              -0.002102                  -0.001122
2021-03-02               0.000194                  -0.000859


           MACD_Hist Close_Log_Returns
Date
2021-02-24                   -0.000923
2021-02-25                   -0.000167
2021-02-26                   -0.000307
2021-03-01                   -0.000980
2021-03-02                    0.001053

[5 rows x 154 columns]

## Filter only Target Features ($F_{target} $)

In [13]:
targets = basket.get_keyword_features("Returns")
print(f"Targets: {targets}")


for symbol, asset in basket.assets.items():
    mask = asset.data.columns.isin(targets)
    asset.data = asset.data.loc[:, mask]

print(f"Basket shape: {basket.data.shape}")
basket.data.head(5)

Targets: {'Close_Log_Returns', 'MACD_Hist Close_Log_Returns', 'EMA_20 Close_Log_Returns', 'RSI_20 Close_Log_Returns', 'SMA_20 Close_Log_Returns', 'MACD_Sig Close_Log_Returns', 'MACD Close_Log_Returns'}
Basket shape: (970, 98)

                        AAPL                           \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-24         -0.004060                -0.006281
2021-02-25         -0.035402                -0.006568
2021-02-26          0.002229                -0.007952
2021-03-01          0.052452                -0.006060
2021-03-02         -0.021115                -0.001531

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-24                -0.004764                49.443327
2021-02-25                -0.004697                49.042061
2021-02-26                -0.007621                44.959599
2021-03-01                -0.006683                50.199121
2021-03-02                -0.001051                56.073523

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.005006                  -0.005451
2021-02-25              -0.004288                  -0.005218
2021-02-26              -0.006177                  -0.005410
2021-03-01              -0.004584                  -0.005245
2021-03-02               0.000722                  -0.004051

                                                    TSLA  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-24                    0.000445          0.059954
2021-02-25                    0.000930         -0.084024
2021-02-26                   -0.000767         -0.009899
2021-03-01                    0.000661          0.061615
2021-03-02                    0.004773         -0.045549

                                                              ...  \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns  ...
Date                                                          ...
2021-02-24                -0.011570                -0.012856  ...
2021-02-25                -0.008703                -0.005921  ...
2021-02-26                -0.011820                -0.013360  ...
2021-03-01                -0.010625                -0.013030  ...
2021-03-02                -0.004971                -0.005921  ...

                              AMD                             \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-24              -0.004678                  -0.002595
2021-02-25              -0.001476                  -0.002371
2021-02-26              -0.005253                  -0.002947
2021-03-01              -0.001896                  -0.002737
2021-03-02               0.000513                  -0.002087

                                                    CSCO  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-24                   -0.002084          0.005041
2021-02-25                    0.000895         -0.004822
2021-02-26                   -0.002306         -0.014382
2021-03-01                    0.000841          0.023131
2021-03-02                    0.002600         -0.008749

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-24                 0.000530                -0.001497
2021-02-25                 0.000527                -0.000874
2021-02-26                -0.000197                -0.001250
2021-03-01                -0.000521                -0.002501
2021-03-02                 0.001481                -0.000060

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-24                50.527952              -0.001681
2021-02-25                51.224838              -0.000967
2021-02-26                49.039717              -0.001184
2021-03-01                46.994221              -0.002102
2021-03-02                54.783902               0.000194


           MACD_Sig Close_Log_Returns MACD_Hist Close_Log_Returns
Date
2021-02-24                  -0.000759                   -0.000923
2021-02-25                  -0.000801                   -0.000167
2021-02-26                  -0.000877                   -0.000307
2021-03-01                  -0.001122                   -0.000980
2021-03-02                  -0.000859                    0.001053

[5 rows x 98 columns]

# Dataset & Dataloader

In [14]:
n_obs = len(basket.data)
n_assets = basket.data.columns.levels[0].size
n_features = basket.data.columns.levels[1].size

print(n_obs, n_assets, n_features)

basket_np = basket.data.values.reshape(n_obs, n_assets, n_features)
basket_np.shape

970 14 7

(970, 14, 7)

## Ratio Dataset

In [15]:
ratios = [0.8, 0.1, 0.1]
total_count = len(basket_np)
train_count = int(total_count * ratios[0])
val_count = int(total_count * ratios[1])
test_count = total_count - train_count - val_count

print(f"Ratios DS\nTrain:\t{train_count}\nVal:\t{val_count}\nTest:\t{test_count}\nTotal:\t{total_count}")

Ratios DS
Train:	776
Val:	97
Test:	97
Total:	970

In [16]:
all_dates = basket.data.index.get_level_values(0).unique().to_numpy()
print(f"Dates shape: {all_dates.shape}")

Dates shape: (970,)

In [17]:
end_val = train_count + val_count

# Ratios
train_part = basket_np[:train_count]
val_part = basket_np[train_count:end_val]
test_part = basket_np[end_val:]

train_dates = all_dates[:train_count]
val_dates   = all_dates[train_count:end_val]
test_dates  = all_dates[end_val:]

print(f"Train: {train_part.shape}\nVal: {val_part.shape}\nTest:{test_part.shape}")
print(f"Train Dates: {train_dates.shape}\nVal Dates: {val_dates.shape}\nTest Dates:{test_dates.shape}")

Train: (776, 14, 7)
Val: (97, 14, 7)
Test:(97, 14, 7)
Train Dates: (776,)
Val Dates: (97,)
Test Dates:(97,)

## Scale Dataset

In [18]:
# scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = StandardScaler()

# Require 2D Numpy Array
T, A, F = train_part.shape
scaler.fit(train_part.reshape(-1, F))

scaled_train_part = scale(train_part, scaler)
scaled_val_part = scale(val_part, scaler)
scaled_test_part = scale(test_part, scaler)

inspect(scaled_train_part, "Scaled Train Part")
inspect(scaled_val_part, "Scaled Val Part")
inspect(scaled_test_part, "Scaled Test Part")
print(f"Train:\t{scaled_train_part.shape}\nVal:\t{scaled_val_part.shape}\nTest:\t{scaled_test_part.shape}")

--- Inspecting: Scaled Train Part ---
------------------------------------
Shape: (776, 14, 7)
Min:   -12.4922
Max:   8.8458
Mean:  0.0000
Std:   1.0000
------------------------------------
--- Inspecting: Scaled Val Part ---
------------------------------------
Shape: (97, 14, 7)
Min:   -8.9719
Max:   6.1577
Mean:  -0.0437
Std:   0.9942
------------------------------------
--- Inspecting: Scaled Test Part ---
------------------------------------
Shape: (97, 14, 7)
Min:   -6.1881
Max:   8.8664
Mean:  0.1223
Std:   0.9497
------------------------------------
Train:	(776, 14, 7)
Val:	(97, 14, 7)
Test:	(97, 14, 7)

## Dataloader

In [19]:
train_ds = MarketDataset(data=scaled_train_part, dates=train_dates, window_size=window_size)
val_ds = MarketDataset(data=scaled_val_part, dates=val_dates, window_size=window_size)
test_ds = MarketDataset(data=scaled_test_part, dates=test_dates, window_size=window_size)

print(f"Num of Windows\nTrain DS: {len(train_ds)}, Val Ds: {len(val_ds)}, Test DS: {len(test_ds)}\n")
print(f"A sample shape from Train DS\n\tx: {train_ds[0]['x'].shape},\n\tx_cond: {train_ds[0]['x_cond'].shape}")

Num of Windows
Train DS: 713, Val Ds: 34, Test DS: 34

A sample shape from Train DS
	x: (64, 14, 1),
	x_cond: (64, 14, 6)

In [20]:
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False)

batch = next(iter(train_loader))
print(len(train_loader))
print(batch["x"].shape)
print(batch["x_cond"].shape)

90
torch.Size([8, 64, 14, 1])
torch.Size([8, 64, 14, 6])

# Model, Engine
Use *Condition DDPM*

In [21]:
# n_window mean batch size
n_window, window, n_assets, n_features = batch["x"].shape
n_window, window, n_assets, n_conds = batch["x_cond"].shape
ddpm_transformer['n_cond'] = n_conds

print(n_assets, n_features, n_conds)

input_channels = n_assets * n_features
cond_channels = n_assets * n_conds
print(input_channels, cond_channels)

14 1 6
14 84

In [22]:
model = DiffusionTransformer(
    n_features=input_channels,
    n_cond=cond_channels,        
    window_size=window_size,             
    d_model=ddpm_transformer['d_model'],                
    nhead=ddpm_transformer['nhead'],
    num_layers=ddpm_transformer['num_layers'],
    dim_feedforward=ddpm_transformer['dim_feedforward'],
    dropout=ddpm_transformer['dropout']
).to(device)

In [23]:
diffusion = Diffusion(model, timesteps=ddpm['timesteps'], beta_start=ddpm['beta_start'], beta_end=ddpm['beta_end']).to(device)

In [24]:
optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

In [25]:
engine = Engine(
    train_dataloader=train_loader,
    val_dataloader=val_loader,
    model=diffusion,
    scaler=scaler,
    optimizer=optimizer,
    device=device,
    file_name=f"ddpm_transformer_d{ddpm_transformer['d_model']}_l{ddpm_transformer['num_layers']}",
)

In [26]:
engine.fit(epochs)

INFO:engine.trainer:Engine started Training for 1000 epochs on cuda...
Epoch 1/1000 [Train]: 100%|██████████| 90/90 [00:25<00:00,  3.52it/s, loss=0.986]
Epoch 1/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.95it/s]

End of Epoch 1 | Train Loss: 1.020402 | Val Loss: 1.023451
New Best Model Saved (Val Loss: 1.023451)

Epoch 2/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.18it/s, loss=0.995]
Epoch 2/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 2 | Train Loss: 1.005711 | Val Loss: 0.979984
New Best Model Saved (Val Loss: 0.979984)

Epoch 3/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.03]
Epoch 3/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 3 | Train Loss: 1.006861 | Val Loss: 1.007968

Epoch 4/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.881]
Epoch 4/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 4 | Train Loss: 1.002724 | Val Loss: 1.017864

Epoch 5/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.05]
Epoch 5/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 5 | Train Loss: 1.005646 | Val Loss: 1.004085

Epoch 6/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 6/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 6 | Train Loss: 1.005771 | Val Loss: 0.995791

Epoch 7/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.995]
Epoch 7/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 7 | Train Loss: 1.000808 | Val Loss: 1.004916

Epoch 8/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 8/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.27it/s]

End of Epoch 8 | Train Loss: 1.004274 | Val Loss: 0.997981

Epoch 9/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=1.09]
Epoch 9/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 9 | Train Loss: 1.006616 | Val Loss: 1.011234

Epoch 10/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.941]
Epoch 10/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.79it/s]

End of Epoch 10 | Train Loss: 1.002107 | Val Loss: 0.994761

Epoch 11/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.921]
Epoch 11/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.02it/s]

End of Epoch 11 | Train Loss: 1.002996 | Val Loss: 0.984634

Epoch 12/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.17it/s, loss=1.09]
Epoch 12/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.19it/s]

End of Epoch 12 | Train Loss: 1.004080 | Val Loss: 1.000863

Epoch 13/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.02]
Epoch 13/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 13 | Train Loss: 1.002748 | Val Loss: 0.996066

Epoch 14/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.01]
Epoch 14/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.20it/s]

End of Epoch 14 | Train Loss: 1.004781 | Val Loss: 1.000871

Epoch 15/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.18it/s, loss=0.941]
Epoch 15/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 15 | Train Loss: 1.001928 | Val Loss: 0.995588

Epoch 16/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.981]
Epoch 16/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 16 | Train Loss: 1.000548 | Val Loss: 0.997615

Epoch 17/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=1.06]
Epoch 17/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 17 | Train Loss: 1.003629 | Val Loss: 0.978963
New Best Model Saved (Val Loss: 0.978963)

Epoch 18/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.02]
Epoch 18/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 18 | Train Loss: 1.000458 | Val Loss: 0.991097

Epoch 19/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.927]
Epoch 19/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.25it/s]

End of Epoch 19 | Train Loss: 1.000036 | Val Loss: 1.009779

Epoch 20/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.925]
Epoch 20/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.16it/s]

End of Epoch 20 | Train Loss: 1.000394 | Val Loss: 0.985366

Epoch 21/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.29it/s, loss=1.01]
Epoch 21/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 21 | Train Loss: 1.000322 | Val Loss: 0.999730

Epoch 22/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.949]
Epoch 22/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 22 | Train Loss: 1.003331 | Val Loss: 0.998760

Epoch 23/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.03]
Epoch 23/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 23 | Train Loss: 1.001946 | Val Loss: 0.995055

Epoch 24/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.946]
Epoch 24/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 24 | Train Loss: 0.997459 | Val Loss: 1.015108

Epoch 25/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.05]
Epoch 25/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 25 | Train Loss: 1.003229 | Val Loss: 0.992720

Epoch 26/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.18it/s, loss=1.01]
Epoch 26/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 26 | Train Loss: 1.000058 | Val Loss: 0.991253

Epoch 27/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.04]
Epoch 27/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 27 | Train Loss: 1.000948 | Val Loss: 1.011139

Epoch 28/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.02]
Epoch 28/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 28 | Train Loss: 1.000087 | Val Loss: 1.010239

Epoch 29/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.978]
Epoch 29/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 29 | Train Loss: 1.000418 | Val Loss: 1.013344

Epoch 30/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.01]
Epoch 30/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 30 | Train Loss: 0.998290 | Val Loss: 1.001668

Epoch 31/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.995]
Epoch 31/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 31 | Train Loss: 1.000110 | Val Loss: 1.006082

Epoch 32/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.989]
Epoch 32/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 32 | Train Loss: 1.000769 | Val Loss: 1.006789

Epoch 33/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.999]
Epoch 33/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 33 | Train Loss: 1.001718 | Val Loss: 0.999883

Epoch 34/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.997]
Epoch 34/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 34 | Train Loss: 1.001735 | Val Loss: 0.994339

Epoch 35/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.993]
Epoch 35/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 35 | Train Loss: 1.002445 | Val Loss: 1.000536

Epoch 36/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.17it/s, loss=1.02]
Epoch 36/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.73it/s]

End of Epoch 36 | Train Loss: 1.000919 | Val Loss: 0.994474

Epoch 37/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.935]
Epoch 37/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 37 | Train Loss: 1.001785 | Val Loss: 0.996410

Epoch 38/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.945]
Epoch 38/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 38 | Train Loss: 1.000346 | Val Loss: 0.997892

Epoch 39/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.951]
Epoch 39/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.92it/s]

End of Epoch 39 | Train Loss: 0.997172 | Val Loss: 0.991495

Epoch 40/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.989]
Epoch 40/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.16it/s]

End of Epoch 40 | Train Loss: 1.002443 | Val Loss: 1.011128

Epoch 41/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.02]
Epoch 41/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 41 | Train Loss: 1.000887 | Val Loss: 1.003752

Epoch 42/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.91]
Epoch 42/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 42 | Train Loss: 1.000973 | Val Loss: 1.004908

Epoch 43/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.17it/s, loss=1.03]
Epoch 43/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.41it/s]

End of Epoch 43 | Train Loss: 0.999039 | Val Loss: 0.992557

Epoch 44/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=1.05]
Epoch 44/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 44 | Train Loss: 1.002065 | Val Loss: 0.994563

Epoch 45/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.09]
Epoch 45/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 45 | Train Loss: 1.001888 | Val Loss: 1.011476

Epoch 46/1000 [Train]: 100%|██████████| 90/90 [00:23<00:00,  3.83it/s, loss=1.02]
Epoch 46/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.14it/s]

End of Epoch 46 | Train Loss: 1.000844 | Val Loss: 1.009681

Epoch 47/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.05]
Epoch 47/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 47 | Train Loss: 1.000928 | Val Loss: 0.994100

Epoch 48/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.97]
Epoch 48/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 48 | Train Loss: 0.999869 | Val Loss: 0.994635

Epoch 49/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 49/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 49 | Train Loss: 1.002788 | Val Loss: 1.008835

Epoch 50/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.928]
Epoch 50/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 50 | Train Loss: 1.000642 | Val Loss: 0.990547

Epoch 51/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1]
Epoch 51/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 51 | Train Loss: 1.001746 | Val Loss: 0.998652

Epoch 52/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.988]
Epoch 52/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 52 | Train Loss: 1.000354 | Val Loss: 0.992621

Epoch 53/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.924]
Epoch 53/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 53 | Train Loss: 0.998359 | Val Loss: 1.010383

Epoch 54/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 54/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 54 | Train Loss: 1.002354 | Val Loss: 1.018796

Epoch 55/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.922]
Epoch 55/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 55 | Train Loss: 0.998469 | Val Loss: 0.999065

Epoch 56/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.06]
Epoch 56/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 56 | Train Loss: 1.002850 | Val Loss: 0.989146

Epoch 57/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.971]
Epoch 57/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 57 | Train Loss: 1.001385 | Val Loss: 0.992336

Epoch 58/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 58/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 58 | Train Loss: 1.000086 | Val Loss: 0.996259

Epoch 59/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.03]
Epoch 59/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 59 | Train Loss: 0.999473 | Val Loss: 0.995555

Epoch 60/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.29it/s, loss=1.02]
Epoch 60/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 60 | Train Loss: 1.000991 | Val Loss: 1.002746

Epoch 61/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.993]
Epoch 61/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 61 | Train Loss: 1.001160 | Val Loss: 1.002388

Epoch 62/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.993]
Epoch 62/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 62 | Train Loss: 1.003620 | Val Loss: 0.996320

Epoch 63/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.934]
Epoch 63/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.96it/s]

End of Epoch 63 | Train Loss: 0.996308 | Val Loss: 1.015253

Epoch 64/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.985]
Epoch 64/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 64 | Train Loss: 1.004098 | Val Loss: 1.000327

Epoch 65/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 65/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.95it/s]

End of Epoch 65 | Train Loss: 1.001936 | Val Loss: 0.998526

Epoch 66/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.07]
Epoch 66/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 66 | Train Loss: 1.002867 | Val Loss: 0.996312

Epoch 67/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 67/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 67 | Train Loss: 1.001712 | Val Loss: 1.000299

Epoch 68/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.918]
Epoch 68/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 68 | Train Loss: 1.001037 | Val Loss: 1.008637

Epoch 69/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.96]
Epoch 69/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 69 | Train Loss: 1.001782 | Val Loss: 0.993958

Epoch 70/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.957]
Epoch 70/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 70 | Train Loss: 1.000588 | Val Loss: 0.990334

Epoch 71/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.978]
Epoch 71/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 71 | Train Loss: 1.001680 | Val Loss: 1.026144

Epoch 72/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1]
Epoch 72/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.91it/s]

End of Epoch 72 | Train Loss: 0.999783 | Val Loss: 1.012288

Epoch 73/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.05]
Epoch 73/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 73 | Train Loss: 1.003341 | Val Loss: 1.005794

Epoch 74/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.995]
Epoch 74/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 74 | Train Loss: 0.998680 | Val Loss: 1.006091

Epoch 75/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.965]
Epoch 75/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 75 | Train Loss: 1.000038 | Val Loss: 0.986504

Epoch 76/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.985]
Epoch 76/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 76 | Train Loss: 1.000450 | Val Loss: 1.012883

Epoch 77/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1]
Epoch 77/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 77 | Train Loss: 1.002556 | Val Loss: 1.010026

Epoch 78/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.996]
Epoch 78/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 78 | Train Loss: 1.001050 | Val Loss: 0.999010

Epoch 79/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.934]
Epoch 79/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 79 | Train Loss: 1.001548 | Val Loss: 0.994821

Epoch 80/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.928]
Epoch 80/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 80 | Train Loss: 0.997003 | Val Loss: 0.997702

Epoch 81/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.05]
Epoch 81/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.88it/s]

End of Epoch 81 | Train Loss: 1.001915 | Val Loss: 0.997000

Epoch 82/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.939]
Epoch 82/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 82 | Train Loss: 0.996727 | Val Loss: 1.001517

Epoch 83/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.986]
Epoch 83/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 83 | Train Loss: 0.999849 | Val Loss: 0.989772

Epoch 84/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.997]
Epoch 84/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 84 | Train Loss: 0.999705 | Val Loss: 1.000372

Epoch 85/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.93]
Epoch 85/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.84it/s]

End of Epoch 85 | Train Loss: 0.997568 | Val Loss: 1.011245

Epoch 86/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.02]
Epoch 86/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 86 | Train Loss: 0.998414 | Val Loss: 1.002663

Epoch 87/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.937]
Epoch 87/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.85it/s]

End of Epoch 87 | Train Loss: 0.999663 | Val Loss: 1.000117

Epoch 88/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.03]
Epoch 88/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.96it/s]

End of Epoch 88 | Train Loss: 1.002082 | Val Loss: 0.999002

Epoch 89/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.1]
Epoch 89/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.94it/s]

End of Epoch 89 | Train Loss: 1.003455 | Val Loss: 1.012205

Epoch 90/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.03]
Epoch 90/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 90 | Train Loss: 0.999271 | Val Loss: 1.014061

Epoch 91/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.937]
Epoch 91/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 91 | Train Loss: 1.000803 | Val Loss: 1.001933

Epoch 92/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.946]
Epoch 92/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.06it/s]

End of Epoch 92 | Train Loss: 0.999895 | Val Loss: 1.007122

Epoch 93/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.964]
Epoch 93/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.92it/s]

End of Epoch 93 | Train Loss: 1.003402 | Val Loss: 1.006061

Epoch 94/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.17it/s, loss=1]
Epoch 94/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 94 | Train Loss: 1.001324 | Val Loss: 0.987844

Epoch 95/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.952]
Epoch 95/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 95 | Train Loss: 1.004708 | Val Loss: 0.982438

Epoch 96/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 96/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 96 | Train Loss: 0.998695 | Val Loss: 1.007012

Epoch 97/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.936]
Epoch 97/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.90it/s]

End of Epoch 97 | Train Loss: 1.001244 | Val Loss: 1.010813

Epoch 98/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.932]
Epoch 98/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 98 | Train Loss: 0.996273 | Val Loss: 0.982787

Epoch 99/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.934]
Epoch 99/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 99 | Train Loss: 0.996163 | Val Loss: 1.002353

Epoch 100/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.01]
Epoch 100/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 100 | Train Loss: 1.002438 | Val Loss: 0.995140

Epoch 101/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.03]
Epoch 101/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 101 | Train Loss: 1.001334 | Val Loss: 0.997325

Epoch 102/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.979]
Epoch 102/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 102 | Train Loss: 1.004773 | Val Loss: 0.992212

Epoch 103/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.09]
Epoch 103/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.04it/s]

End of Epoch 103 | Train Loss: 0.999986 | Val Loss: 1.002813

Epoch 104/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.01]
Epoch 104/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 104 | Train Loss: 1.001872 | Val Loss: 1.002546

Epoch 105/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.89]
Epoch 105/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 105 | Train Loss: 0.997842 | Val Loss: 0.996105

Epoch 106/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.963]
Epoch 106/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.09it/s]

End of Epoch 106 | Train Loss: 0.998796 | Val Loss: 0.997010

Epoch 107/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.938]
Epoch 107/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 107 | Train Loss: 1.003865 | Val Loss: 1.017873

Epoch 108/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.992]
Epoch 108/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.24it/s]

End of Epoch 108 | Train Loss: 0.995984 | Val Loss: 0.993254

Epoch 109/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 109/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 109 | Train Loss: 0.999656 | Val Loss: 1.001591

Epoch 110/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 110/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 110 | Train Loss: 1.000686 | Val Loss: 1.003005

Epoch 111/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.02]
Epoch 111/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.13it/s]

End of Epoch 111 | Train Loss: 0.997600 | Val Loss: 1.000700

Epoch 112/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 112/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 112 | Train Loss: 0.996864 | Val Loss: 1.012891

Epoch 113/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.925]
Epoch 113/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 113 | Train Loss: 0.998092 | Val Loss: 1.002488

Epoch 114/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.07]
Epoch 114/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 114 | Train Loss: 1.002487 | Val Loss: 1.009867

Epoch 115/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 115/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.15it/s]

End of Epoch 115 | Train Loss: 0.999695 | Val Loss: 0.994492

Epoch 116/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.92]
Epoch 116/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 116 | Train Loss: 1.000824 | Val Loss: 0.996456

Epoch 117/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.06]
Epoch 117/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 117 | Train Loss: 1.001626 | Val Loss: 0.997390

Epoch 118/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.03]
Epoch 118/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.29it/s]

End of Epoch 118 | Train Loss: 1.001563 | Val Loss: 0.994266

Epoch 119/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.969]
Epoch 119/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 119 | Train Loss: 1.001288 | Val Loss: 1.017122

Epoch 120/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.05]
Epoch 120/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 120 | Train Loss: 1.002600 | Val Loss: 1.000138

Epoch 121/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 121/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.77it/s]

End of Epoch 121 | Train Loss: 1.000839 | Val Loss: 1.013736

Epoch 122/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 122/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 122 | Train Loss: 1.000624 | Val Loss: 0.997734

Epoch 123/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1]
Epoch 123/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 123 | Train Loss: 1.000322 | Val Loss: 1.003070

Epoch 124/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.92]
Epoch 124/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 124 | Train Loss: 0.999204 | Val Loss: 1.002636

Epoch 125/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 125/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 125 | Train Loss: 0.999209 | Val Loss: 1.005800

Epoch 126/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.911]
Epoch 126/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 126 | Train Loss: 0.999061 | Val Loss: 1.006695

Epoch 127/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.01]
Epoch 127/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 127 | Train Loss: 0.999409 | Val Loss: 0.995253

Epoch 128/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.982]
Epoch 128/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 128 | Train Loss: 0.998364 | Val Loss: 0.984058

Epoch 129/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.955]
Epoch 129/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.05it/s]

End of Epoch 129 | Train Loss: 0.997232 | Val Loss: 0.980689

Epoch 130/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.02]
Epoch 130/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 130 | Train Loss: 1.002183 | Val Loss: 0.992792

Epoch 131/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.9]
Epoch 131/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 131 | Train Loss: 0.999666 | Val Loss: 0.996719

Epoch 132/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.981]
Epoch 132/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 132 | Train Loss: 1.000887 | Val Loss: 1.022940

Epoch 133/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.06]
Epoch 133/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 133 | Train Loss: 1.002110 | Val Loss: 1.000178

Epoch 134/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.08]
Epoch 134/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 134 | Train Loss: 0.997451 | Val Loss: 1.004675

Epoch 135/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.948]
Epoch 135/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 135 | Train Loss: 0.996265 | Val Loss: 1.009379

Epoch 136/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1]
Epoch 136/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 136 | Train Loss: 1.000262 | Val Loss: 1.012917

Epoch 137/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.09]
Epoch 137/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 137 | Train Loss: 0.998765 | Val Loss: 1.007143

Epoch 138/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 138/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 138 | Train Loss: 0.999591 | Val Loss: 0.985821

Epoch 139/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 139/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 139 | Train Loss: 1.003574 | Val Loss: 1.010874

Epoch 140/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 140/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 140 | Train Loss: 1.000613 | Val Loss: 0.996626

Epoch 141/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.07]
Epoch 141/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 141 | Train Loss: 1.000345 | Val Loss: 1.006269

Epoch 142/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.988]
Epoch 142/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 142 | Train Loss: 1.002265 | Val Loss: 0.994494

Epoch 143/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.06]
Epoch 143/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 143 | Train Loss: 1.001087 | Val Loss: 1.001981

Epoch 144/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.952]
Epoch 144/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 144 | Train Loss: 0.999461 | Val Loss: 1.016120

Epoch 145/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.04]
Epoch 145/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 145 | Train Loss: 1.001774 | Val Loss: 1.000550

Epoch 146/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.969]
Epoch 146/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 146 | Train Loss: 1.003251 | Val Loss: 1.002746

Epoch 147/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.978]
Epoch 147/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.25it/s]

End of Epoch 147 | Train Loss: 0.998230 | Val Loss: 1.001108

Epoch 148/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.01]
Epoch 148/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 148 | Train Loss: 1.002380 | Val Loss: 0.998059

Epoch 149/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=1.05]
Epoch 149/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 149 | Train Loss: 1.003308 | Val Loss: 0.987657

Epoch 150/1000 [Train]: 100%|██████████| 90/90 [00:22<00:00,  3.97it/s, loss=0.973]
Epoch 150/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 150 | Train Loss: 1.000819 | Val Loss: 0.997495

Epoch 151/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.947]
Epoch 151/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.14it/s]

End of Epoch 151 | Train Loss: 0.995718 | Val Loss: 1.016828

Epoch 152/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.13it/s, loss=0.996]
Epoch 152/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.10it/s]

End of Epoch 152 | Train Loss: 1.000812 | Val Loss: 0.979661

Epoch 153/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.982]
Epoch 153/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.85it/s]

End of Epoch 153 | Train Loss: 1.000354 | Val Loss: 1.001087

Epoch 154/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.934]
Epoch 154/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 154 | Train Loss: 0.999879 | Val Loss: 0.998172

Epoch 155/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.941]
Epoch 155/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 155 | Train Loss: 1.001951 | Val Loss: 1.006914

Epoch 156/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.04]
Epoch 156/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.93it/s]

End of Epoch 156 | Train Loss: 1.002316 | Val Loss: 1.006255

Epoch 157/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.989]
Epoch 157/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 157 | Train Loss: 0.999935 | Val Loss: 0.994850

Epoch 158/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.03]
Epoch 158/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 158 | Train Loss: 1.001080 | Val Loss: 0.997344

Epoch 159/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.942]
Epoch 159/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 159 | Train Loss: 1.001317 | Val Loss: 0.984541

Epoch 160/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.05]
Epoch 160/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 160 | Train Loss: 1.001524 | Val Loss: 1.000323

Epoch 161/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.04]
Epoch 161/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 161 | Train Loss: 1.005004 | Val Loss: 0.991294

Epoch 162/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.974]
Epoch 162/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 162 | Train Loss: 1.000533 | Val Loss: 0.989884

Epoch 163/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.05]
Epoch 163/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 163 | Train Loss: 1.001038 | Val Loss: 1.005259

Epoch 164/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 164/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 164 | Train Loss: 1.003828 | Val Loss: 1.009203

Epoch 165/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.02]
Epoch 165/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 165 | Train Loss: 1.002167 | Val Loss: 1.002706

Epoch 166/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.05]
Epoch 166/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 166 | Train Loss: 1.002747 | Val Loss: 0.992596

Epoch 167/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 167/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 167 | Train Loss: 0.999801 | Val Loss: 1.004331

Epoch 168/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 168/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 168 | Train Loss: 1.001429 | Val Loss: 0.980730

Epoch 169/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.01]
Epoch 169/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 169 | Train Loss: 1.001553 | Val Loss: 0.997863

Epoch 170/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 170/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 170 | Train Loss: 1.001008 | Val Loss: 0.995143

Epoch 171/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.991]
Epoch 171/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.95it/s]

End of Epoch 171 | Train Loss: 0.997513 | Val Loss: 1.002102

Epoch 172/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1.11]
Epoch 172/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 172 | Train Loss: 1.005746 | Val Loss: 0.998426

Epoch 173/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.983]
Epoch 173/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.19it/s]

End of Epoch 173 | Train Loss: 0.998745 | Val Loss: 1.001590

Epoch 174/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.932]
Epoch 174/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 174 | Train Loss: 0.999804 | Val Loss: 1.006283

Epoch 175/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.988]
Epoch 175/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 175 | Train Loss: 0.994268 | Val Loss: 1.005977

Epoch 176/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.979]
Epoch 176/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.80it/s]

End of Epoch 176 | Train Loss: 1.001238 | Val Loss: 0.994213

Epoch 177/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.945]
Epoch 177/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 177 | Train Loss: 1.001062 | Val Loss: 1.002250

Epoch 178/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.11]
Epoch 178/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 178 | Train Loss: 1.003579 | Val Loss: 1.010991

Epoch 179/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 179/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.01it/s]

End of Epoch 179 | Train Loss: 0.999594 | Val Loss: 0.983525

Epoch 180/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.17]
Epoch 180/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.95it/s]

End of Epoch 180 | Train Loss: 1.003127 | Val Loss: 1.007298

Epoch 181/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.951]
Epoch 181/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.94it/s]

End of Epoch 181 | Train Loss: 1.000795 | Val Loss: 0.980623

Epoch 182/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.989]
Epoch 182/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 182 | Train Loss: 0.997593 | Val Loss: 0.990473

Epoch 183/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.952]
Epoch 183/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 183 | Train Loss: 1.001079 | Val Loss: 0.984831

Epoch 184/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.944]
Epoch 184/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 184 | Train Loss: 0.999315 | Val Loss: 1.016987

Epoch 185/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.976]
Epoch 185/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 185 | Train Loss: 1.003057 | Val Loss: 1.014832

Epoch 186/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.958]
Epoch 186/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 186 | Train Loss: 0.999312 | Val Loss: 1.002749

Epoch 187/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.922]
Epoch 187/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 187 | Train Loss: 0.998142 | Val Loss: 1.010556

Epoch 188/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.945]
Epoch 188/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 188 | Train Loss: 0.999601 | Val Loss: 1.007582

Epoch 189/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.12]
Epoch 189/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 189 | Train Loss: 1.000283 | Val Loss: 1.000028

Epoch 190/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.01]
Epoch 190/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 190 | Train Loss: 1.003120 | Val Loss: 0.992283

Epoch 191/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.08]
Epoch 191/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 191 | Train Loss: 1.001439 | Val Loss: 0.986011

Epoch 192/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 192/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 192 | Train Loss: 0.999484 | Val Loss: 1.001206

Epoch 193/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 193/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 193 | Train Loss: 0.998543 | Val Loss: 1.000127

Epoch 194/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.927]
Epoch 194/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 194 | Train Loss: 0.998271 | Val Loss: 0.993775

Epoch 195/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.985]
Epoch 195/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.84it/s]

End of Epoch 195 | Train Loss: 1.000977 | Val Loss: 1.012040

Epoch 196/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.921]
Epoch 196/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 196 | Train Loss: 0.997350 | Val Loss: 1.007101

Epoch 197/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 197/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 197 | Train Loss: 1.000644 | Val Loss: 0.989370

Epoch 198/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 198/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 198 | Train Loss: 0.999720 | Val Loss: 1.011931

Epoch 199/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.991]
Epoch 199/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 199 | Train Loss: 0.999262 | Val Loss: 0.993317

Epoch 200/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.924]
Epoch 200/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.21it/s]

End of Epoch 200 | Train Loss: 0.999713 | Val Loss: 1.010361

Epoch 201/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.964]
Epoch 201/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 201 | Train Loss: 0.997716 | Val Loss: 0.994003

Epoch 202/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.981]
Epoch 202/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 202 | Train Loss: 1.000165 | Val Loss: 0.994578

Epoch 203/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.936]
Epoch 203/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.22it/s]

End of Epoch 203 | Train Loss: 0.998383 | Val Loss: 0.995838

Epoch 204/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1]
Epoch 204/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 204 | Train Loss: 0.999976 | Val Loss: 1.003901

Epoch 205/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.987]
Epoch 205/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 205 | Train Loss: 1.001971 | Val Loss: 0.994599

Epoch 206/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.984]
Epoch 206/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 206 | Train Loss: 1.002718 | Val Loss: 1.004543

Epoch 207/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.935]
Epoch 207/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 207 | Train Loss: 0.999578 | Val Loss: 0.990277

Epoch 208/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1]
Epoch 208/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 208 | Train Loss: 1.001756 | Val Loss: 1.008699

Epoch 209/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.99]
Epoch 209/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.22it/s]

End of Epoch 209 | Train Loss: 1.002214 | Val Loss: 1.010247

Epoch 210/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.988]
Epoch 210/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.22it/s]

End of Epoch 210 | Train Loss: 1.002198 | Val Loss: 1.006166

Epoch 211/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 211/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.21it/s]

End of Epoch 211 | Train Loss: 1.000071 | Val Loss: 0.991293

Epoch 212/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.933]
Epoch 212/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 212 | Train Loss: 0.999881 | Val Loss: 0.997216

Epoch 213/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.997]
Epoch 213/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.98it/s]

End of Epoch 213 | Train Loss: 1.000354 | Val Loss: 1.006983

Epoch 214/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 214/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.18it/s]

End of Epoch 214 | Train Loss: 1.000552 | Val Loss: 1.015019

Epoch 215/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.968]
Epoch 215/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 215 | Train Loss: 0.999521 | Val Loss: 0.996636

Epoch 216/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 216/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 216 | Train Loss: 0.998442 | Val Loss: 1.012133

Epoch 217/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.932]
Epoch 217/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 217 | Train Loss: 0.999645 | Val Loss: 0.998545

Epoch 218/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.941]
Epoch 218/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 218 | Train Loss: 0.997441 | Val Loss: 1.007034

Epoch 219/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.932]
Epoch 219/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 219 | Train Loss: 0.996897 | Val Loss: 0.978734
New Best Model Saved (Val Loss: 0.978734)

Epoch 220/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.948]
Epoch 220/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 220 | Train Loss: 0.996834 | Val Loss: 0.991614

Epoch 221/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.14it/s, loss=1]
Epoch 221/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.08it/s]

End of Epoch 221 | Train Loss: 1.001369 | Val Loss: 1.018014

Epoch 222/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.927]
Epoch 222/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.94it/s]

End of Epoch 222 | Train Loss: 0.999462 | Val Loss: 1.010701

Epoch 223/1000 [Train]: 100%|██████████| 90/90 [00:23<00:00,  3.79it/s, loss=1.05]
Epoch 223/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 223 | Train Loss: 1.001855 | Val Loss: 1.011738

Epoch 224/1000 [Train]: 100%|██████████| 90/90 [00:24<00:00,  3.61it/s, loss=1.03]
Epoch 224/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 224 | Train Loss: 1.001730 | Val Loss: 1.009149

Epoch 225/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.989]
Epoch 225/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 225 | Train Loss: 0.998740 | Val Loss: 1.009295

Epoch 226/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.965]
Epoch 226/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 226 | Train Loss: 1.000602 | Val Loss: 0.999965

Epoch 227/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.976]
Epoch 227/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 227 | Train Loss: 1.000732 | Val Loss: 0.989874

Epoch 228/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.932]
Epoch 228/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 228 | Train Loss: 1.001340 | Val Loss: 0.999438

Epoch 229/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 229/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 229 | Train Loss: 0.997747 | Val Loss: 1.015799

Epoch 230/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.03]
Epoch 230/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 230 | Train Loss: 0.996182 | Val Loss: 0.985498

Epoch 231/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.04]
Epoch 231/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.83it/s]

End of Epoch 231 | Train Loss: 0.999012 | Val Loss: 0.991260

Epoch 232/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.05]
Epoch 232/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 232 | Train Loss: 1.002859 | Val Loss: 1.002227

Epoch 233/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.929]
Epoch 233/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 233 | Train Loss: 0.997210 | Val Loss: 0.988664

Epoch 234/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.987]
Epoch 234/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 234 | Train Loss: 0.997279 | Val Loss: 1.003930

Epoch 235/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 235/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.33it/s]

End of Epoch 235 | Train Loss: 0.999690 | Val Loss: 1.002646

Epoch 236/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.992]
Epoch 236/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.32it/s]

End of Epoch 236 | Train Loss: 1.001298 | Val Loss: 1.002808

Epoch 237/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.09]
Epoch 237/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.76it/s]

End of Epoch 237 | Train Loss: 0.998306 | Val Loss: 0.990098

Epoch 238/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.02]
Epoch 238/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 238 | Train Loss: 0.997479 | Val Loss: 0.987631

Epoch 239/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.965]
Epoch 239/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.06it/s]

End of Epoch 239 | Train Loss: 1.002309 | Val Loss: 0.998625

Epoch 240/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.1]
Epoch 240/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 240 | Train Loss: 1.005864 | Val Loss: 0.993252

Epoch 241/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.996]
Epoch 241/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.82it/s]

End of Epoch 241 | Train Loss: 1.000978 | Val Loss: 0.990776

Epoch 242/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.94]
Epoch 242/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.70it/s]

End of Epoch 242 | Train Loss: 0.996999 | Val Loss: 1.000188

Epoch 243/1000 [Train]: 100%|██████████| 90/90 [00:22<00:00,  4.04it/s, loss=0.959]
Epoch 243/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 243 | Train Loss: 1.000361 | Val Loss: 0.994089

Epoch 244/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.987]
Epoch 244/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 244 | Train Loss: 1.001604 | Val Loss: 1.001967

Epoch 245/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.998]
Epoch 245/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 245 | Train Loss: 1.000253 | Val Loss: 1.006986

Epoch 246/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.971]
Epoch 246/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 246 | Train Loss: 1.002195 | Val Loss: 0.991487

Epoch 247/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.909]
Epoch 247/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 247 | Train Loss: 0.998217 | Val Loss: 1.007478

Epoch 248/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 248/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 248 | Train Loss: 1.000038 | Val Loss: 0.994888

Epoch 249/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.05]
Epoch 249/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 249 | Train Loss: 0.997591 | Val Loss: 1.000376

Epoch 250/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.938]
Epoch 250/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 250 | Train Loss: 0.999116 | Val Loss: 0.986663

Epoch 251/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.18it/s, loss=0.981]
Epoch 251/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 251 | Train Loss: 1.001777 | Val Loss: 1.008258

Epoch 252/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.992]
Epoch 252/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 252 | Train Loss: 0.998362 | Val Loss: 1.013030

Epoch 253/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.908]
Epoch 253/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 253 | Train Loss: 0.999461 | Val Loss: 0.998340

Epoch 254/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=1.06]
Epoch 254/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 254 | Train Loss: 1.000378 | Val Loss: 1.007766

Epoch 255/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=1.07]
Epoch 255/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 255 | Train Loss: 1.000238 | Val Loss: 1.015867

Epoch 256/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.949]
Epoch 256/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 256 | Train Loss: 0.998442 | Val Loss: 1.006890

Epoch 257/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 257/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 257 | Train Loss: 1.001242 | Val Loss: 0.999390

Epoch 258/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.07]
Epoch 258/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.32it/s]

End of Epoch 258 | Train Loss: 1.001973 | Val Loss: 1.000476

Epoch 259/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.986]
Epoch 259/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 259 | Train Loss: 0.998254 | Val Loss: 1.000164

Epoch 260/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.972]
Epoch 260/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 260 | Train Loss: 1.002184 | Val Loss: 1.005858

Epoch 261/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.943]
Epoch 261/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.73it/s]

End of Epoch 261 | Train Loss: 0.999351 | Val Loss: 1.031021

Epoch 262/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1]
Epoch 262/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 262 | Train Loss: 0.998551 | Val Loss: 1.004576

Epoch 263/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 263/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.98it/s]

End of Epoch 263 | Train Loss: 0.999590 | Val Loss: 1.004648

Epoch 264/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1.02]
Epoch 264/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 264 | Train Loss: 0.999082 | Val Loss: 1.010826

Epoch 265/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.988]
Epoch 265/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 265 | Train Loss: 1.001386 | Val Loss: 1.031409

Epoch 266/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.01]
Epoch 266/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 266 | Train Loss: 1.001731 | Val Loss: 1.003465

Epoch 267/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.13]
Epoch 267/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 267 | Train Loss: 1.002067 | Val Loss: 1.000968

Epoch 268/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.09]
Epoch 268/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 268 | Train Loss: 1.002190 | Val Loss: 1.000557

Epoch 269/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 269/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 269 | Train Loss: 0.999880 | Val Loss: 1.008221

Epoch 270/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.984]
Epoch 270/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 270 | Train Loss: 1.001138 | Val Loss: 0.995578

Epoch 271/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=1.05]
Epoch 271/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 271 | Train Loss: 1.002980 | Val Loss: 0.995345

Epoch 272/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.995]
Epoch 272/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.35it/s]

End of Epoch 272 | Train Loss: 1.000483 | Val Loss: 0.984352

Epoch 273/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.945]
Epoch 273/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.91it/s]

End of Epoch 273 | Train Loss: 0.998319 | Val Loss: 1.013206

Epoch 274/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.01]
Epoch 274/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 274 | Train Loss: 0.999051 | Val Loss: 1.022947

Epoch 275/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.02]
Epoch 275/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 275 | Train Loss: 1.000440 | Val Loss: 0.988912

Epoch 276/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.911]
Epoch 276/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 276 | Train Loss: 0.997414 | Val Loss: 0.979620

Epoch 277/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.975]
Epoch 277/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.09it/s]

End of Epoch 277 | Train Loss: 1.000199 | Val Loss: 0.999129

Epoch 278/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.985]
Epoch 278/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.29it/s]

End of Epoch 278 | Train Loss: 1.000199 | Val Loss: 0.999897

Epoch 279/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 279/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 279 | Train Loss: 1.000829 | Val Loss: 0.999770

Epoch 280/1000 [Train]: 100%|██████████| 90/90 [00:24<00:00,  3.61it/s, loss=0.918]
Epoch 280/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 280 | Train Loss: 1.000815 | Val Loss: 1.017204

Epoch 281/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.957]
Epoch 281/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 281 | Train Loss: 1.001473 | Val Loss: 0.999414

Epoch 282/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.956]
Epoch 282/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 282 | Train Loss: 1.000494 | Val Loss: 0.996167

Epoch 283/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.05]
Epoch 283/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.43it/s]

End of Epoch 283 | Train Loss: 1.000415 | Val Loss: 1.007560

Epoch 284/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.973]
Epoch 284/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 284 | Train Loss: 1.000207 | Val Loss: 1.015988

Epoch 285/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.07]
Epoch 285/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 285 | Train Loss: 1.002802 | Val Loss: 1.001044

Epoch 286/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.898]
Epoch 286/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 286 | Train Loss: 1.000868 | Val Loss: 1.013188

Epoch 287/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.05]
Epoch 287/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 287 | Train Loss: 0.997956 | Val Loss: 1.007792

Epoch 288/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.955]
Epoch 288/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 288 | Train Loss: 0.999497 | Val Loss: 0.997111

Epoch 289/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.07]
Epoch 289/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 289 | Train Loss: 0.997953 | Val Loss: 0.981274

Epoch 290/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.955]
Epoch 290/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 290 | Train Loss: 0.997292 | Val Loss: 1.000484

Epoch 291/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.07]
Epoch 291/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 291 | Train Loss: 1.001078 | Val Loss: 0.987619

Epoch 292/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.05]
Epoch 292/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 292 | Train Loss: 1.003739 | Val Loss: 0.989432

Epoch 293/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 293/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 293 | Train Loss: 0.997523 | Val Loss: 1.017376

Epoch 294/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.985]
Epoch 294/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.23it/s]

End of Epoch 294 | Train Loss: 1.002859 | Val Loss: 0.991391

Epoch 295/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 295/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 295 | Train Loss: 1.001171 | Val Loss: 0.989076

Epoch 296/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.91]
Epoch 296/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 296 | Train Loss: 0.998878 | Val Loss: 1.005579

Epoch 297/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.05]
Epoch 297/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 297 | Train Loss: 0.999837 | Val Loss: 0.998359

Epoch 298/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1]
Epoch 298/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 298 | Train Loss: 0.997946 | Val Loss: 0.996450

Epoch 299/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.954]
Epoch 299/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 299 | Train Loss: 1.001561 | Val Loss: 0.996881

Epoch 300/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.994]
Epoch 300/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 300 | Train Loss: 1.002268 | Val Loss: 1.005461

Epoch 301/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.931]
Epoch 301/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 301 | Train Loss: 0.997441 | Val Loss: 1.000052

Epoch 302/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.973]
Epoch 302/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.18it/s]

End of Epoch 302 | Train Loss: 0.998826 | Val Loss: 1.013542

Epoch 303/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.946]
Epoch 303/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 303 | Train Loss: 1.001667 | Val Loss: 0.992883

Epoch 304/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.08]
Epoch 304/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 304 | Train Loss: 0.996960 | Val Loss: 1.006022

Epoch 305/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 305/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 305 | Train Loss: 0.998129 | Val Loss: 0.997290

Epoch 306/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1.05]
Epoch 306/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.08it/s]

End of Epoch 306 | Train Loss: 1.002345 | Val Loss: 1.003970

Epoch 307/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.961]
Epoch 307/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 307 | Train Loss: 0.998843 | Val Loss: 0.987952

Epoch 308/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.984]
Epoch 308/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 308 | Train Loss: 1.000767 | Val Loss: 1.004314

Epoch 309/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.15it/s, loss=0.889]
Epoch 309/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.06it/s]

End of Epoch 309 | Train Loss: 1.001154 | Val Loss: 1.007249

Epoch 310/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.07]
Epoch 310/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 310 | Train Loss: 0.999829 | Val Loss: 1.004054

Epoch 311/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.962]
Epoch 311/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.10it/s]

End of Epoch 311 | Train Loss: 0.997897 | Val Loss: 1.004207

Epoch 312/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.01]
Epoch 312/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 312 | Train Loss: 0.999605 | Val Loss: 1.006338

Epoch 313/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.956]
Epoch 313/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.27it/s]

End of Epoch 313 | Train Loss: 1.002055 | Val Loss: 0.992288

Epoch 314/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.953]
Epoch 314/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.18it/s]

End of Epoch 314 | Train Loss: 1.001062 | Val Loss: 0.995382

Epoch 315/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 315/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 315 | Train Loss: 1.001263 | Val Loss: 0.995697

Epoch 316/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.08]
Epoch 316/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 316 | Train Loss: 0.998269 | Val Loss: 1.001396

Epoch 317/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 317/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 317 | Train Loss: 1.000478 | Val Loss: 1.008916

Epoch 318/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 318/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 318 | Train Loss: 0.997617 | Val Loss: 1.006603

Epoch 319/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 319/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 319 | Train Loss: 1.000470 | Val Loss: 0.986803

Epoch 320/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.954]
Epoch 320/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.74it/s]

End of Epoch 320 | Train Loss: 1.000091 | Val Loss: 1.003368

Epoch 321/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.992]
Epoch 321/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.00it/s]

End of Epoch 321 | Train Loss: 0.999399 | Val Loss: 0.979418

Epoch 322/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.968]
Epoch 322/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 322 | Train Loss: 1.001995 | Val Loss: 0.998147

Epoch 323/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 323/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 323 | Train Loss: 1.000278 | Val Loss: 1.003540

Epoch 324/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.981]
Epoch 324/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 324 | Train Loss: 1.001697 | Val Loss: 0.994686

Epoch 325/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 325/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 325 | Train Loss: 0.999357 | Val Loss: 0.983885

Epoch 326/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.992]
Epoch 326/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 326 | Train Loss: 0.999799 | Val Loss: 1.004600

Epoch 327/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.02]
Epoch 327/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 327 | Train Loss: 1.002345 | Val Loss: 1.008189

Epoch 328/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.972]
Epoch 328/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 328 | Train Loss: 1.002286 | Val Loss: 1.002120

Epoch 329/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 329/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 329 | Train Loss: 1.001727 | Val Loss: 1.002951

Epoch 330/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.94]
Epoch 330/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 330 | Train Loss: 0.998865 | Val Loss: 1.003200

Epoch 331/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.978]
Epoch 331/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 331 | Train Loss: 0.999232 | Val Loss: 0.995082

Epoch 332/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 332/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.73it/s]

End of Epoch 332 | Train Loss: 1.002243 | Val Loss: 0.994979

Epoch 333/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.09]
Epoch 333/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 333 | Train Loss: 1.003734 | Val Loss: 1.004364

Epoch 334/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.01]
Epoch 334/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 334 | Train Loss: 1.003621 | Val Loss: 1.009158

Epoch 335/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.07]
Epoch 335/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 335 | Train Loss: 1.001527 | Val Loss: 0.987402

Epoch 336/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.972]
Epoch 336/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.82it/s]

End of Epoch 336 | Train Loss: 0.996755 | Val Loss: 0.980210

Epoch 337/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.01]
Epoch 337/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 337 | Train Loss: 1.001709 | Val Loss: 1.017565

Epoch 338/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.991]
Epoch 338/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 338 | Train Loss: 1.000348 | Val Loss: 1.003980

Epoch 339/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.998]
Epoch 339/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 339 | Train Loss: 1.002048 | Val Loss: 0.997634

Epoch 340/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.973]
Epoch 340/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 340 | Train Loss: 1.000347 | Val Loss: 0.998918

Epoch 341/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 341/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 341 | Train Loss: 1.001211 | Val Loss: 0.987628

Epoch 342/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.998]
Epoch 342/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 342 | Train Loss: 1.001460 | Val Loss: 1.015931

Epoch 343/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.1]
Epoch 343/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 343 | Train Loss: 1.000986 | Val Loss: 1.004737

Epoch 344/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.985]
Epoch 344/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 344 | Train Loss: 0.999423 | Val Loss: 0.999407

Epoch 345/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.918]
Epoch 345/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 345 | Train Loss: 0.998784 | Val Loss: 1.011171

Epoch 346/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.03]
Epoch 346/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 346 | Train Loss: 0.999052 | Val Loss: 1.009082

Epoch 347/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.988]
Epoch 347/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 347 | Train Loss: 1.000473 | Val Loss: 0.997738

Epoch 348/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 348/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 348 | Train Loss: 1.001631 | Val Loss: 1.009318

Epoch 349/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.975]
Epoch 349/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 349 | Train Loss: 0.999373 | Val Loss: 1.004583

Epoch 350/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.993]
Epoch 350/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 350 | Train Loss: 1.000050 | Val Loss: 0.988894

Epoch 351/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.09]
Epoch 351/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 351 | Train Loss: 1.002057 | Val Loss: 1.018852

Epoch 352/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.974]
Epoch 352/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 352 | Train Loss: 0.998572 | Val Loss: 1.015762

Epoch 353/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.989]
Epoch 353/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.18it/s]

End of Epoch 353 | Train Loss: 1.000318 | Val Loss: 0.993615

Epoch 354/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.927]
Epoch 354/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 354 | Train Loss: 0.998156 | Val Loss: 1.002283

Epoch 355/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 355/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.78it/s]

End of Epoch 355 | Train Loss: 0.997218 | Val Loss: 0.993501

Epoch 356/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.09]
Epoch 356/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 356 | Train Loss: 1.002877 | Val Loss: 0.998928

Epoch 357/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 357/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 357 | Train Loss: 1.000438 | Val Loss: 0.984712

Epoch 358/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.1]
Epoch 358/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 358 | Train Loss: 1.000079 | Val Loss: 1.012082

Epoch 359/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.07]
Epoch 359/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 359 | Train Loss: 0.999126 | Val Loss: 0.996476

Epoch 360/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.962]
Epoch 360/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 360 | Train Loss: 1.001351 | Val Loss: 1.000596

Epoch 361/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 361/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 361 | Train Loss: 0.997761 | Val Loss: 0.974521
New Best Model Saved (Val Loss: 0.974521)

Epoch 362/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.973]
Epoch 362/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 362 | Train Loss: 0.997918 | Val Loss: 1.012950

Epoch 363/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.02]
Epoch 363/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.82it/s]

End of Epoch 363 | Train Loss: 0.997928 | Val Loss: 0.994462

Epoch 364/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.29it/s, loss=1.05]
Epoch 364/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 364 | Train Loss: 0.998959 | Val Loss: 1.001745

Epoch 365/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 365/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 365 | Train Loss: 0.996687 | Val Loss: 1.003130

Epoch 366/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.993]
Epoch 366/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 366 | Train Loss: 0.998756 | Val Loss: 0.997263

Epoch 367/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.945]
Epoch 367/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.02it/s]

End of Epoch 367 | Train Loss: 0.999548 | Val Loss: 1.004723

Epoch 368/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.973]
Epoch 368/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.12it/s]

End of Epoch 368 | Train Loss: 1.000952 | Val Loss: 1.014104

Epoch 369/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.907]
Epoch 369/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.13it/s]

End of Epoch 369 | Train Loss: 0.997102 | Val Loss: 0.997909

Epoch 370/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.07]
Epoch 370/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 370 | Train Loss: 1.002658 | Val Loss: 0.999471

Epoch 371/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.03]
Epoch 371/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.19it/s]

End of Epoch 371 | Train Loss: 1.001496 | Val Loss: 1.013610

Epoch 372/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.02]
Epoch 372/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 372 | Train Loss: 1.001864 | Val Loss: 0.994873

Epoch 373/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.02]
Epoch 373/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 373 | Train Loss: 1.001616 | Val Loss: 1.005668

Epoch 374/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.06]
Epoch 374/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 374 | Train Loss: 1.001894 | Val Loss: 0.990710

Epoch 375/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.95]
Epoch 375/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 375 | Train Loss: 0.998746 | Val Loss: 1.003901

Epoch 376/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.11]
Epoch 376/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 376 | Train Loss: 0.999632 | Val Loss: 1.008482

Epoch 377/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.921]
Epoch 377/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 377 | Train Loss: 1.000372 | Val Loss: 0.993940

Epoch 378/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.06]
Epoch 378/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 378 | Train Loss: 0.997702 | Val Loss: 0.980806

Epoch 379/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 379/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 379 | Train Loss: 1.004719 | Val Loss: 1.017447

Epoch 380/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.953]
Epoch 380/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 380 | Train Loss: 1.000961 | Val Loss: 1.003137

Epoch 381/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.983]
Epoch 381/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 381 | Train Loss: 0.997862 | Val Loss: 1.005640

Epoch 382/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.02]
Epoch 382/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.34it/s]

End of Epoch 382 | Train Loss: 0.997360 | Val Loss: 0.994426

Epoch 383/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.04]
Epoch 383/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 383 | Train Loss: 1.003564 | Val Loss: 1.000447

Epoch 384/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.943]
Epoch 384/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 384 | Train Loss: 1.000200 | Val Loss: 0.987257

Epoch 385/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 385/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 385 | Train Loss: 0.997587 | Val Loss: 0.996681

Epoch 386/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.982]
Epoch 386/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.83it/s]

End of Epoch 386 | Train Loss: 0.999649 | Val Loss: 1.002093

Epoch 387/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.992]
Epoch 387/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.24it/s]

End of Epoch 387 | Train Loss: 1.002601 | Val Loss: 1.006824

Epoch 388/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.963]
Epoch 388/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 388 | Train Loss: 1.001161 | Val Loss: 1.005662

Epoch 389/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.07]
Epoch 389/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 389 | Train Loss: 1.002725 | Val Loss: 1.005948

Epoch 390/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.925]
Epoch 390/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 390 | Train Loss: 0.999539 | Val Loss: 0.995152

Epoch 391/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.969]
Epoch 391/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 391 | Train Loss: 0.999540 | Val Loss: 1.008452

Epoch 392/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.993]
Epoch 392/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 392 | Train Loss: 0.999488 | Val Loss: 0.991168

Epoch 393/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.996]
Epoch 393/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 393 | Train Loss: 1.001056 | Val Loss: 1.004001

Epoch 394/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.955]
Epoch 394/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.35it/s]

End of Epoch 394 | Train Loss: 1.002871 | Val Loss: 0.987433

Epoch 395/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.07]
Epoch 395/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.40it/s]

End of Epoch 395 | Train Loss: 0.997137 | Val Loss: 0.987399

Epoch 396/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.943]
Epoch 396/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 396 | Train Loss: 1.000842 | Val Loss: 0.982841

Epoch 397/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.04]
Epoch 397/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 397 | Train Loss: 1.003323 | Val Loss: 1.013248

Epoch 398/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.971]
Epoch 398/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 398 | Train Loss: 1.001595 | Val Loss: 1.001748

Epoch 399/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.996]
Epoch 399/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 399 | Train Loss: 1.001097 | Val Loss: 0.995574

Epoch 400/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.02]
Epoch 400/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 400 | Train Loss: 0.999959 | Val Loss: 1.017893

Epoch 401/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.963]
Epoch 401/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 401 | Train Loss: 1.002290 | Val Loss: 1.002019

Epoch 402/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.957]
Epoch 402/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 402 | Train Loss: 1.002188 | Val Loss: 1.000031

Epoch 403/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.898]
Epoch 403/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.14it/s]

End of Epoch 403 | Train Loss: 0.997188 | Val Loss: 0.991636

Epoch 404/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.02]
Epoch 404/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 404 | Train Loss: 1.000573 | Val Loss: 0.999563

Epoch 405/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.01]
Epoch 405/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.20it/s]

End of Epoch 405 | Train Loss: 1.000079 | Val Loss: 0.994550

Epoch 406/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.976]
Epoch 406/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 406 | Train Loss: 1.002287 | Val Loss: 1.022391

Epoch 407/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.996]
Epoch 407/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.87it/s]

End of Epoch 407 | Train Loss: 1.002004 | Val Loss: 1.015659

Epoch 408/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.939]
Epoch 408/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.98it/s]

End of Epoch 408 | Train Loss: 0.999371 | Val Loss: 0.996589

Epoch 409/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.967]
Epoch 409/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 409 | Train Loss: 1.001653 | Val Loss: 0.990691

Epoch 410/1000 [Train]: 100%|██████████| 90/90 [00:22<00:00,  3.98it/s, loss=0.956]
Epoch 410/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 410 | Train Loss: 1.000224 | Val Loss: 1.000099

Epoch 411/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.927]
Epoch 411/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 411 | Train Loss: 0.996690 | Val Loss: 0.988912

Epoch 412/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.02]
Epoch 412/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 412 | Train Loss: 1.001174 | Val Loss: 1.005856

Epoch 413/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.993]
Epoch 413/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 413 | Train Loss: 1.000813 | Val Loss: 0.992470

Epoch 414/1000 [Train]: 100%|██████████| 90/90 [00:22<00:00,  3.94it/s, loss=0.975]
Epoch 414/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.08it/s]

End of Epoch 414 | Train Loss: 1.000473 | Val Loss: 1.013310

Epoch 415/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.98]
Epoch 415/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 415 | Train Loss: 0.998537 | Val Loss: 0.994978

Epoch 416/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.02]
Epoch 416/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 416 | Train Loss: 1.000899 | Val Loss: 1.004008

Epoch 417/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 417/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 417 | Train Loss: 0.998883 | Val Loss: 0.996022

Epoch 418/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 418/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 418 | Train Loss: 0.999672 | Val Loss: 1.013003

Epoch 419/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=0.976]
Epoch 419/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 419 | Train Loss: 0.997630 | Val Loss: 1.002674

Epoch 420/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.969]
Epoch 420/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 420 | Train Loss: 0.999418 | Val Loss: 1.010860

Epoch 421/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.04]
Epoch 421/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 421 | Train Loss: 0.999431 | Val Loss: 0.987786

Epoch 422/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.949]
Epoch 422/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 422 | Train Loss: 1.000279 | Val Loss: 0.998183

Epoch 423/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.971]
Epoch 423/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 423 | Train Loss: 1.000433 | Val Loss: 1.021602

Epoch 424/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.12]
Epoch 424/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.83it/s]

End of Epoch 424 | Train Loss: 0.998682 | Val Loss: 1.001342

Epoch 425/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 425/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 425 | Train Loss: 0.996136 | Val Loss: 0.997187

Epoch 426/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 426/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 426 | Train Loss: 1.002776 | Val Loss: 0.989462

Epoch 427/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.11]
Epoch 427/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 427 | Train Loss: 0.999135 | Val Loss: 0.998275

Epoch 428/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.988]
Epoch 428/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.20it/s]

End of Epoch 428 | Train Loss: 0.995655 | Val Loss: 0.998707

Epoch 429/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.05]
Epoch 429/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 429 | Train Loss: 1.001133 | Val Loss: 1.008217

Epoch 430/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.96]
Epoch 430/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 430 | Train Loss: 1.001394 | Val Loss: 1.015195

Epoch 431/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.05]
Epoch 431/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 431 | Train Loss: 1.000278 | Val Loss: 0.995383

Epoch 432/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.977]
Epoch 432/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.28it/s]

End of Epoch 432 | Train Loss: 0.998648 | Val Loss: 0.994218

Epoch 433/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.04]
Epoch 433/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 433 | Train Loss: 0.999955 | Val Loss: 1.006593

Epoch 434/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.954]
Epoch 434/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 434 | Train Loss: 0.998292 | Val Loss: 1.005052

Epoch 435/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 435/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.27it/s]

End of Epoch 435 | Train Loss: 1.001329 | Val Loss: 0.991075

Epoch 436/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.945]
Epoch 436/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 436 | Train Loss: 0.998187 | Val Loss: 1.004646

Epoch 437/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 437/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 437 | Train Loss: 1.001102 | Val Loss: 0.999676

Epoch 438/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 438/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 438 | Train Loss: 1.002311 | Val Loss: 1.010463

Epoch 439/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.997]
Epoch 439/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 439 | Train Loss: 1.001336 | Val Loss: 1.002590

Epoch 440/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.908]
Epoch 440/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 440 | Train Loss: 1.000903 | Val Loss: 0.995748

Epoch 441/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.03]
Epoch 441/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 441 | Train Loss: 0.999341 | Val Loss: 0.992869

Epoch 442/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 442/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 442 | Train Loss: 0.998441 | Val Loss: 1.009977

Epoch 443/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1]
Epoch 443/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 443 | Train Loss: 1.001599 | Val Loss: 1.002510

Epoch 444/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 444/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 444 | Train Loss: 1.000640 | Val Loss: 0.997739

Epoch 445/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.986]
Epoch 445/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 445 | Train Loss: 0.998043 | Val Loss: 1.003229

Epoch 446/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.05]
Epoch 446/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 446 | Train Loss: 0.999095 | Val Loss: 1.001530

Epoch 447/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.999]
Epoch 447/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 447 | Train Loss: 0.997745 | Val Loss: 0.986371

Epoch 448/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.998]
Epoch 448/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 448 | Train Loss: 0.998574 | Val Loss: 0.990959

Epoch 449/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.895]
Epoch 449/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.24it/s]

End of Epoch 449 | Train Loss: 0.999942 | Val Loss: 0.996013

Epoch 450/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.04]
Epoch 450/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 450 | Train Loss: 0.997941 | Val Loss: 1.009501

Epoch 451/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.946]
Epoch 451/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 451 | Train Loss: 1.002640 | Val Loss: 0.980636

Epoch 452/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.01]
Epoch 452/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 452 | Train Loss: 0.999685 | Val Loss: 1.001955

Epoch 453/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.931]
Epoch 453/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 453 | Train Loss: 1.001137 | Val Loss: 0.991368

Epoch 454/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 454/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 454 | Train Loss: 0.999378 | Val Loss: 1.002934

Epoch 455/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.987]
Epoch 455/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.18it/s]

End of Epoch 455 | Train Loss: 1.001969 | Val Loss: 1.003601

Epoch 456/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 456/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 456 | Train Loss: 0.997848 | Val Loss: 0.998062

Epoch 457/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.01]
Epoch 457/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 457 | Train Loss: 1.000365 | Val Loss: 1.003976

Epoch 458/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.06]
Epoch 458/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 458 | Train Loss: 0.999375 | Val Loss: 0.988634

Epoch 459/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.976]
Epoch 459/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 459 | Train Loss: 1.000666 | Val Loss: 1.011400

Epoch 460/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.954]
Epoch 460/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 460 | Train Loss: 1.002100 | Val Loss: 0.993326

Epoch 461/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.944]
Epoch 461/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.78it/s]

End of Epoch 461 | Train Loss: 0.998308 | Val Loss: 0.998011

Epoch 462/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.01]
Epoch 462/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 462 | Train Loss: 1.000882 | Val Loss: 0.995702

Epoch 463/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.987]
Epoch 463/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.81it/s]

End of Epoch 463 | Train Loss: 0.997417 | Val Loss: 0.995035

Epoch 464/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.902]
Epoch 464/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 464 | Train Loss: 0.998394 | Val Loss: 1.004011

Epoch 465/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.06]
Epoch 465/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 465 | Train Loss: 1.002005 | Val Loss: 1.010033

Epoch 466/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 466/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 466 | Train Loss: 1.001029 | Val Loss: 1.017287

Epoch 467/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 467/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 467 | Train Loss: 1.000240 | Val Loss: 0.979552

Epoch 468/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.08]
Epoch 468/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 468 | Train Loss: 1.002826 | Val Loss: 0.999864

Epoch 469/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.973]
Epoch 469/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 469 | Train Loss: 0.998867 | Val Loss: 1.012046

Epoch 470/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1.05]
Epoch 470/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 470 | Train Loss: 1.000941 | Val Loss: 1.003527

Epoch 471/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.16it/s, loss=1.05]
Epoch 471/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 471 | Train Loss: 0.999647 | Val Loss: 1.000920

Epoch 472/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.03]
Epoch 472/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 472 | Train Loss: 0.999431 | Val Loss: 0.994140

Epoch 473/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 473/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 473 | Train Loss: 1.000653 | Val Loss: 1.008334

Epoch 474/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.991]
Epoch 474/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 474 | Train Loss: 1.000573 | Val Loss: 1.005661

Epoch 475/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.03]
Epoch 475/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 475 | Train Loss: 0.999337 | Val Loss: 1.004136

Epoch 476/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.982]
Epoch 476/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 476 | Train Loss: 1.000840 | Val Loss: 1.001518

Epoch 477/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.975]
Epoch 477/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.82it/s]

End of Epoch 477 | Train Loss: 0.998692 | Val Loss: 0.988336

Epoch 478/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 478/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 478 | Train Loss: 1.003285 | Val Loss: 1.008841

Epoch 479/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 479/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 479 | Train Loss: 1.000117 | Val Loss: 1.001990

Epoch 480/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.1]
Epoch 480/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 480 | Train Loss: 1.000315 | Val Loss: 1.005029

Epoch 481/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.879]
Epoch 481/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 481 | Train Loss: 0.996757 | Val Loss: 1.007911

Epoch 482/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.984]
Epoch 482/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 482 | Train Loss: 0.999306 | Val Loss: 0.994808

Epoch 483/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.973]
Epoch 483/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 483 | Train Loss: 1.001237 | Val Loss: 1.000824

Epoch 484/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.04]
Epoch 484/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 484 | Train Loss: 0.999629 | Val Loss: 1.002171

Epoch 485/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 485/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 485 | Train Loss: 1.003493 | Val Loss: 1.000197

Epoch 486/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.997]
Epoch 486/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 486 | Train Loss: 0.999235 | Val Loss: 1.004085

Epoch 487/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.02]
Epoch 487/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.83it/s]

End of Epoch 487 | Train Loss: 1.001465 | Val Loss: 1.002580

Epoch 488/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.05]
Epoch 488/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 488 | Train Loss: 0.999306 | Val Loss: 1.008037

Epoch 489/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.05]
Epoch 489/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 489 | Train Loss: 1.000529 | Val Loss: 1.024793

Epoch 490/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.921]
Epoch 490/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 490 | Train Loss: 0.999653 | Val Loss: 1.004239

Epoch 491/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.961]
Epoch 491/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 491 | Train Loss: 1.000298 | Val Loss: 0.992225

Epoch 492/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 492/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 492 | Train Loss: 1.001367 | Val Loss: 1.007932

Epoch 493/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.972]
Epoch 493/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.29it/s]

End of Epoch 493 | Train Loss: 0.998199 | Val Loss: 1.009288

Epoch 494/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.993]
Epoch 494/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 494 | Train Loss: 1.000926 | Val Loss: 0.995243

Epoch 495/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.21it/s, loss=0.963]
Epoch 495/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 495 | Train Loss: 1.001799 | Val Loss: 0.993903

Epoch 496/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.05]
Epoch 496/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.96it/s]

End of Epoch 496 | Train Loss: 1.002168 | Val Loss: 1.016962

Epoch 497/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.964]
Epoch 497/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 497 | Train Loss: 1.000452 | Val Loss: 1.005435

Epoch 498/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.04]
Epoch 498/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 498 | Train Loss: 0.999931 | Val Loss: 0.997312

Epoch 499/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.03]
Epoch 499/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 499 | Train Loss: 1.000347 | Val Loss: 1.007965

Epoch 500/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.06]
Epoch 500/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 500 | Train Loss: 1.001984 | Val Loss: 1.000982

Epoch 501/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.04]
Epoch 501/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 501 | Train Loss: 0.997688 | Val Loss: 0.992749

Epoch 502/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.04]
Epoch 502/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.90it/s]

End of Epoch 502 | Train Loss: 0.998386 | Val Loss: 0.989105

Epoch 503/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.03]
Epoch 503/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.91it/s]

End of Epoch 503 | Train Loss: 1.003627 | Val Loss: 1.011163

Epoch 504/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.29it/s, loss=1.02]
Epoch 504/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 504 | Train Loss: 1.003941 | Val Loss: 0.995130

Epoch 505/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.984]
Epoch 505/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 505 | Train Loss: 0.998597 | Val Loss: 0.996193

Epoch 506/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.03]
Epoch 506/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 506 | Train Loss: 0.999843 | Val Loss: 0.997792

Epoch 507/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 507/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 507 | Train Loss: 1.000353 | Val Loss: 1.011894

Epoch 508/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.983]
Epoch 508/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 508 | Train Loss: 0.999110 | Val Loss: 0.996263

Epoch 509/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.924]
Epoch 509/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 509 | Train Loss: 1.000099 | Val Loss: 0.998950

Epoch 510/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.991]
Epoch 510/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 510 | Train Loss: 0.999174 | Val Loss: 1.005853

Epoch 511/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 511/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.14it/s]

End of Epoch 511 | Train Loss: 1.000399 | Val Loss: 0.992896

Epoch 512/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.928]
Epoch 512/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.15it/s]

End of Epoch 512 | Train Loss: 0.998363 | Val Loss: 0.999832

Epoch 513/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.09]
Epoch 513/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 513 | Train Loss: 0.997905 | Val Loss: 1.003820

Epoch 514/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.01]
Epoch 514/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 514 | Train Loss: 1.003741 | Val Loss: 1.009526

Epoch 515/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.896]
Epoch 515/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 515 | Train Loss: 0.998254 | Val Loss: 1.005053

Epoch 516/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.937]
Epoch 516/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 516 | Train Loss: 0.996999 | Val Loss: 0.992035

Epoch 517/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.02]
Epoch 517/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.23it/s]

End of Epoch 517 | Train Loss: 0.999678 | Val Loss: 0.996731

Epoch 518/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 518/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 518 | Train Loss: 1.001955 | Val Loss: 0.991866

Epoch 519/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.971]
Epoch 519/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 519 | Train Loss: 0.999877 | Val Loss: 0.998169

Epoch 520/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.97]
Epoch 520/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 520 | Train Loss: 1.000207 | Val Loss: 1.001406

Epoch 521/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.923]
Epoch 521/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 521 | Train Loss: 0.998030 | Val Loss: 1.009111

Epoch 522/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.05]
Epoch 522/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 522 | Train Loss: 0.996998 | Val Loss: 0.986644

Epoch 523/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.03]
Epoch 523/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 523 | Train Loss: 0.997636 | Val Loss: 0.996404

Epoch 524/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.95]
Epoch 524/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.91it/s]

End of Epoch 524 | Train Loss: 1.001769 | Val Loss: 0.995512

Epoch 525/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.973]
Epoch 525/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 525 | Train Loss: 1.001197 | Val Loss: 0.992282

Epoch 526/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.96]
Epoch 526/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 526 | Train Loss: 0.998491 | Val Loss: 0.985647

Epoch 527/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 527/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 527 | Train Loss: 0.998833 | Val Loss: 0.992599

Epoch 528/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 528/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 528 | Train Loss: 0.997857 | Val Loss: 0.991734

Epoch 529/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.09]
Epoch 529/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 529 | Train Loss: 1.000205 | Val Loss: 0.987527

Epoch 530/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.04]
Epoch 530/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 530 | Train Loss: 0.997959 | Val Loss: 0.990391

Epoch 531/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.984]
Epoch 531/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 531 | Train Loss: 1.000338 | Val Loss: 0.990939

Epoch 532/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.951]
Epoch 532/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.86it/s]

End of Epoch 532 | Train Loss: 0.996670 | Val Loss: 0.996074

Epoch 533/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.919]
Epoch 533/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 533 | Train Loss: 0.997283 | Val Loss: 0.988194

Epoch 534/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.943]
Epoch 534/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 534 | Train Loss: 0.999355 | Val Loss: 1.004091

Epoch 535/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.982]
Epoch 535/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.22it/s]

End of Epoch 535 | Train Loss: 1.002114 | Val Loss: 1.013290

Epoch 536/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 536/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 536 | Train Loss: 1.002727 | Val Loss: 0.984457

Epoch 537/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 537/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.81it/s]

End of Epoch 537 | Train Loss: 1.000150 | Val Loss: 0.991536

Epoch 538/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 538/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 538 | Train Loss: 1.003339 | Val Loss: 0.997809

Epoch 539/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.02]
Epoch 539/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 539 | Train Loss: 0.998596 | Val Loss: 1.002020

Epoch 540/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.964]
Epoch 540/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.91it/s]

End of Epoch 540 | Train Loss: 0.996659 | Val Loss: 0.997139

Epoch 541/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.99]
Epoch 541/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 541 | Train Loss: 1.000224 | Val Loss: 1.003283

Epoch 542/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.945]
Epoch 542/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 542 | Train Loss: 0.998252 | Val Loss: 1.011574

Epoch 543/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.968]
Epoch 543/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 543 | Train Loss: 0.999532 | Val Loss: 0.999186

Epoch 544/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.949]
Epoch 544/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 544 | Train Loss: 1.001878 | Val Loss: 0.997642

Epoch 545/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.919]
Epoch 545/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 545 | Train Loss: 1.001296 | Val Loss: 0.994752

Epoch 546/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.08]
Epoch 546/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 546 | Train Loss: 1.001607 | Val Loss: 0.998243

Epoch 547/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.16]
Epoch 547/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 547 | Train Loss: 1.003081 | Val Loss: 1.010757

Epoch 548/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 548/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.92it/s]

End of Epoch 548 | Train Loss: 1.000462 | Val Loss: 0.984640

Epoch 549/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1]
Epoch 549/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.27it/s]

End of Epoch 549 | Train Loss: 1.001164 | Val Loss: 0.991830

Epoch 550/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.01]
Epoch 550/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.70it/s]

End of Epoch 550 | Train Loss: 0.998124 | Val Loss: 1.007605

Epoch 551/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.02]
Epoch 551/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.25it/s]

End of Epoch 551 | Train Loss: 0.998700 | Val Loss: 0.990596

Epoch 552/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.965]
Epoch 552/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.23it/s]

End of Epoch 552 | Train Loss: 0.998357 | Val Loss: 1.014792

Epoch 553/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.96]
Epoch 553/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.29it/s]

End of Epoch 553 | Train Loss: 0.999852 | Val Loss: 1.009304

Epoch 554/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1]
Epoch 554/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.58it/s]

End of Epoch 554 | Train Loss: 0.999420 | Val Loss: 1.008977

Epoch 555/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.02]
Epoch 555/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 555 | Train Loss: 0.999302 | Val Loss: 1.005227

Epoch 556/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.965]
Epoch 556/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.21it/s]

End of Epoch 556 | Train Loss: 0.997458 | Val Loss: 1.000730

Epoch 557/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=1.02]
Epoch 557/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 557 | Train Loss: 0.999775 | Val Loss: 1.005306

Epoch 558/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1]
Epoch 558/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.95it/s]

End of Epoch 558 | Train Loss: 1.000187 | Val Loss: 0.984439

Epoch 559/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 559/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 559 | Train Loss: 0.995593 | Val Loss: 0.995669

Epoch 560/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 560/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 560 | Train Loss: 1.002437 | Val Loss: 0.996354

Epoch 561/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.999]
Epoch 561/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 561 | Train Loss: 1.000348 | Val Loss: 0.994427

Epoch 562/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.967]
Epoch 562/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.32it/s]

End of Epoch 562 | Train Loss: 0.998846 | Val Loss: 1.000381

Epoch 563/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.06]
Epoch 563/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 563 | Train Loss: 0.999495 | Val Loss: 0.995577

Epoch 564/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.01]
Epoch 564/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 564 | Train Loss: 1.000521 | Val Loss: 1.011180

Epoch 565/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.921]
Epoch 565/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 565 | Train Loss: 1.000831 | Val Loss: 1.007913

Epoch 566/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 566/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 566 | Train Loss: 1.002460 | Val Loss: 1.005240

Epoch 567/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.06]
Epoch 567/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.84it/s]

End of Epoch 567 | Train Loss: 1.000463 | Val Loss: 0.995659

Epoch 568/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 568/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.65it/s]

End of Epoch 568 | Train Loss: 1.001474 | Val Loss: 0.998254

Epoch 569/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.963]
Epoch 569/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 569 | Train Loss: 1.000061 | Val Loss: 1.013292

Epoch 570/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.01]
Epoch 570/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 570 | Train Loss: 0.998651 | Val Loss: 1.003797

Epoch 571/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.02]
Epoch 571/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 571 | Train Loss: 1.001090 | Val Loss: 1.000259

Epoch 572/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.983]
Epoch 572/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 572 | Train Loss: 0.999927 | Val Loss: 1.022591

Epoch 573/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.988]
Epoch 573/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.99it/s]

End of Epoch 573 | Train Loss: 1.000733 | Val Loss: 1.010645

Epoch 574/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.959]
Epoch 574/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 574 | Train Loss: 0.999945 | Val Loss: 1.002409

Epoch 575/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.927]
Epoch 575/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 575 | Train Loss: 1.000953 | Val Loss: 0.985647

Epoch 576/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.11]
Epoch 576/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 576 | Train Loss: 1.001816 | Val Loss: 0.985387

Epoch 577/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.928]
Epoch 577/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 577 | Train Loss: 1.002157 | Val Loss: 1.004079

Epoch 578/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.07]
Epoch 578/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 578 | Train Loss: 1.001312 | Val Loss: 1.013472

Epoch 579/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 579/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 579 | Train Loss: 0.999979 | Val Loss: 0.990404

Epoch 580/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.974]
Epoch 580/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 580 | Train Loss: 0.996929 | Val Loss: 0.992808

Epoch 581/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.98]
Epoch 581/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.13it/s]

End of Epoch 581 | Train Loss: 1.000631 | Val Loss: 0.977177

Epoch 582/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.991]
Epoch 582/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.96it/s]

End of Epoch 582 | Train Loss: 0.998823 | Val Loss: 0.997374

Epoch 583/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 583/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 583 | Train Loss: 0.998092 | Val Loss: 0.981319

Epoch 584/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.989]
Epoch 584/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 584 | Train Loss: 1.004928 | Val Loss: 1.013485

Epoch 585/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 585/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 585 | Train Loss: 1.002079 | Val Loss: 0.987309

Epoch 586/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.981]
Epoch 586/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 586 | Train Loss: 1.001565 | Val Loss: 0.989915

Epoch 587/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.9]
Epoch 587/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 587 | Train Loss: 0.999837 | Val Loss: 1.018268

Epoch 588/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.992]
Epoch 588/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 588 | Train Loss: 1.000321 | Val Loss: 0.992513

Epoch 589/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 589/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.18it/s]

End of Epoch 589 | Train Loss: 1.000415 | Val Loss: 1.004723

Epoch 590/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.947]
Epoch 590/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 590 | Train Loss: 1.002461 | Val Loss: 0.993869

Epoch 591/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 591/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 591 | Train Loss: 0.999048 | Val Loss: 0.990642

Epoch 592/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.09]
Epoch 592/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 592 | Train Loss: 1.002417 | Val Loss: 1.009146

Epoch 593/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 593/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 593 | Train Loss: 0.998176 | Val Loss: 0.988703

Epoch 594/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.02]
Epoch 594/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 594 | Train Loss: 0.999042 | Val Loss: 1.002200

Epoch 595/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.999]
Epoch 595/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 595 | Train Loss: 0.995529 | Val Loss: 1.000405

Epoch 596/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 596/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 596 | Train Loss: 0.999071 | Val Loss: 1.017072

Epoch 597/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 597/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 597 | Train Loss: 1.000465 | Val Loss: 1.002592

Epoch 598/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.919]
Epoch 598/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 598 | Train Loss: 0.998960 | Val Loss: 1.004686

Epoch 599/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.987]
Epoch 599/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 599 | Train Loss: 0.998753 | Val Loss: 1.012162

Epoch 600/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.994]
Epoch 600/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 600 | Train Loss: 1.001018 | Val Loss: 1.005211

Epoch 601/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.03]
Epoch 601/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 601 | Train Loss: 0.999196 | Val Loss: 0.998934

Epoch 602/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.983]
Epoch 602/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 602 | Train Loss: 1.001271 | Val Loss: 0.988433

Epoch 603/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.963]
Epoch 603/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 603 | Train Loss: 0.999850 | Val Loss: 1.000525

Epoch 604/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.04]
Epoch 604/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 604 | Train Loss: 1.004228 | Val Loss: 1.008127

Epoch 605/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 605/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 605 | Train Loss: 0.999406 | Val Loss: 0.993756

Epoch 606/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.935]
Epoch 606/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 606 | Train Loss: 1.002278 | Val Loss: 1.002422

Epoch 607/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.07]
Epoch 607/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 607 | Train Loss: 1.000129 | Val Loss: 0.989207

Epoch 608/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 608/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 608 | Train Loss: 1.001935 | Val Loss: 1.002577

Epoch 609/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.986]
Epoch 609/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 609 | Train Loss: 1.000464 | Val Loss: 1.016180

Epoch 610/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.03]
Epoch 610/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.94it/s]

End of Epoch 610 | Train Loss: 1.002240 | Val Loss: 0.988989

Epoch 611/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.923]
Epoch 611/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.29it/s]

End of Epoch 611 | Train Loss: 0.997644 | Val Loss: 1.008776

Epoch 612/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 612/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 612 | Train Loss: 0.998667 | Val Loss: 0.999819

Epoch 613/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.08]
Epoch 613/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 613 | Train Loss: 1.001040 | Val Loss: 0.997657

Epoch 614/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.988]
Epoch 614/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 614 | Train Loss: 1.001338 | Val Loss: 0.985287

Epoch 615/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.996]
Epoch 615/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 615 | Train Loss: 1.000707 | Val Loss: 1.018623

Epoch 616/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.997]
Epoch 616/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 616 | Train Loss: 1.000287 | Val Loss: 1.007366

Epoch 617/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 617/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 617 | Train Loss: 1.000926 | Val Loss: 0.985557

Epoch 618/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.1]
Epoch 618/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 618 | Train Loss: 1.000689 | Val Loss: 0.998000

Epoch 619/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 619/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 619 | Train Loss: 1.003701 | Val Loss: 0.992416

Epoch 620/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.944]
Epoch 620/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 620 | Train Loss: 1.000091 | Val Loss: 0.971487
New Best Model Saved (Val Loss: 0.971487)

Epoch 621/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.98]
Epoch 621/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 621 | Train Loss: 0.999728 | Val Loss: 1.006134

Epoch 622/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.976]
Epoch 622/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 622 | Train Loss: 1.000790 | Val Loss: 1.014065

Epoch 623/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 623/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 623 | Train Loss: 1.000061 | Val Loss: 1.002207

Epoch 624/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.901]
Epoch 624/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.40it/s]

End of Epoch 624 | Train Loss: 0.997152 | Val Loss: 0.990793

Epoch 625/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.987]
Epoch 625/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 625 | Train Loss: 0.999281 | Val Loss: 0.995168

Epoch 626/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.997]
Epoch 626/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 626 | Train Loss: 0.997356 | Val Loss: 0.986072

Epoch 627/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 627/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.23it/s]

End of Epoch 627 | Train Loss: 1.000953 | Val Loss: 1.000163

Epoch 628/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.949]
Epoch 628/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 628 | Train Loss: 0.999397 | Val Loss: 1.000965

Epoch 629/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.957]
Epoch 629/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.35it/s]

End of Epoch 629 | Train Loss: 0.998135 | Val Loss: 0.993496

Epoch 630/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.03]
Epoch 630/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 630 | Train Loss: 1.002552 | Val Loss: 0.995219

Epoch 631/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.998]
Epoch 631/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.40it/s]

End of Epoch 631 | Train Loss: 0.999213 | Val Loss: 0.996305

Epoch 632/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 632/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 632 | Train Loss: 1.000338 | Val Loss: 1.006094

Epoch 633/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.97]
Epoch 633/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 633 | Train Loss: 1.000398 | Val Loss: 1.010016

Epoch 634/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 634/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 634 | Train Loss: 1.000855 | Val Loss: 0.993251

Epoch 635/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.989]
Epoch 635/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 635 | Train Loss: 0.998841 | Val Loss: 1.002050

Epoch 636/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.41it/s, loss=0.976]
Epoch 636/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 636 | Train Loss: 1.000522 | Val Loss: 1.000769

Epoch 637/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.41it/s, loss=1.01]
Epoch 637/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 637 | Train Loss: 0.999982 | Val Loss: 0.994266

Epoch 638/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.967]
Epoch 638/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 638 | Train Loss: 0.999216 | Val Loss: 1.015058

Epoch 639/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.02]
Epoch 639/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 639 | Train Loss: 1.002211 | Val Loss: 0.999387

Epoch 640/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.04]
Epoch 640/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 640 | Train Loss: 1.005587 | Val Loss: 1.006413

Epoch 641/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 641/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 641 | Train Loss: 1.000909 | Val Loss: 0.990680

Epoch 642/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.04]
Epoch 642/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 642 | Train Loss: 1.000303 | Val Loss: 1.001735

Epoch 643/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.964]
Epoch 643/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 643 | Train Loss: 0.999688 | Val Loss: 1.000416

Epoch 644/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.97]
Epoch 644/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 644 | Train Loss: 1.001850 | Val Loss: 0.995035

Epoch 645/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.04]
Epoch 645/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.08it/s]

End of Epoch 645 | Train Loss: 1.000301 | Val Loss: 1.001358

Epoch 646/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.06]
Epoch 646/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 646 | Train Loss: 1.000223 | Val Loss: 0.997284

Epoch 647/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.903]
Epoch 647/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 647 | Train Loss: 1.000915 | Val Loss: 1.010756

Epoch 648/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 648/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.95it/s]

End of Epoch 648 | Train Loss: 1.000206 | Val Loss: 0.994834

Epoch 649/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.999]
Epoch 649/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 649 | Train Loss: 0.997553 | Val Loss: 0.990486

Epoch 650/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.01]
Epoch 650/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 650 | Train Loss: 0.998560 | Val Loss: 0.995539

Epoch 651/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.12]
Epoch 651/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 651 | Train Loss: 1.001305 | Val Loss: 0.996791

Epoch 652/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.964]
Epoch 652/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 652 | Train Loss: 0.995797 | Val Loss: 1.010840

Epoch 653/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 653/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 653 | Train Loss: 1.000226 | Val Loss: 0.995208

Epoch 654/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.917]
Epoch 654/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 654 | Train Loss: 0.999162 | Val Loss: 1.006321

Epoch 655/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.04]
Epoch 655/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 655 | Train Loss: 1.000839 | Val Loss: 1.010466

Epoch 656/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.03]
Epoch 656/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.32it/s]

End of Epoch 656 | Train Loss: 1.002039 | Val Loss: 1.016876

Epoch 657/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 657/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 657 | Train Loss: 1.002956 | Val Loss: 1.012131

Epoch 658/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.977]
Epoch 658/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 658 | Train Loss: 0.999915 | Val Loss: 1.015868

Epoch 659/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.957]
Epoch 659/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 659 | Train Loss: 1.000789 | Val Loss: 0.998598

Epoch 660/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 660/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 660 | Train Loss: 1.000123 | Val Loss: 1.006286

Epoch 661/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.942]
Epoch 661/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 661 | Train Loss: 0.999929 | Val Loss: 0.990948

Epoch 662/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.971]
Epoch 662/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 662 | Train Loss: 0.998134 | Val Loss: 0.997349

Epoch 663/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 663/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 663 | Train Loss: 0.997730 | Val Loss: 0.989049

Epoch 664/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.08]
Epoch 664/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 664 | Train Loss: 0.998957 | Val Loss: 0.998637

Epoch 665/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.04]
Epoch 665/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 665 | Train Loss: 1.003898 | Val Loss: 1.001564

Epoch 666/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.97]
Epoch 666/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 666 | Train Loss: 1.000740 | Val Loss: 1.021546

Epoch 667/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.977]
Epoch 667/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 667 | Train Loss: 0.997548 | Val Loss: 1.004869

Epoch 668/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.09]
Epoch 668/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 668 | Train Loss: 1.000829 | Val Loss: 1.016604

Epoch 669/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1]
Epoch 669/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 669 | Train Loss: 1.000953 | Val Loss: 1.006945

Epoch 670/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.899]
Epoch 670/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 670 | Train Loss: 0.999969 | Val Loss: 1.009777

Epoch 671/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.943]
Epoch 671/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 671 | Train Loss: 1.002879 | Val Loss: 0.999530

Epoch 672/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.07]
Epoch 672/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.21it/s]

End of Epoch 672 | Train Loss: 1.001314 | Val Loss: 0.997213

Epoch 673/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.05]
Epoch 673/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 673 | Train Loss: 0.998164 | Val Loss: 0.994699

Epoch 674/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 674/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.24it/s]

End of Epoch 674 | Train Loss: 1.000088 | Val Loss: 1.005894

Epoch 675/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.03]
Epoch 675/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 675 | Train Loss: 0.997832 | Val Loss: 0.999829

Epoch 676/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.965]
Epoch 676/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 676 | Train Loss: 0.999268 | Val Loss: 1.014352

Epoch 677/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.981]
Epoch 677/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 677 | Train Loss: 1.001727 | Val Loss: 1.003746

Epoch 678/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 678/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.21it/s]

End of Epoch 678 | Train Loss: 0.997554 | Val Loss: 1.004182

Epoch 679/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.962]
Epoch 679/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 679 | Train Loss: 0.997191 | Val Loss: 0.996855

Epoch 680/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.961]
Epoch 680/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 680 | Train Loss: 1.001638 | Val Loss: 0.988085

Epoch 681/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 681/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 681 | Train Loss: 0.999822 | Val Loss: 0.992167

Epoch 682/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.994]
Epoch 682/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 682 | Train Loss: 0.997731 | Val Loss: 0.979488

Epoch 683/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 683/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 683 | Train Loss: 1.003773 | Val Loss: 1.007620

Epoch 684/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.999]
Epoch 684/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 684 | Train Loss: 0.998550 | Val Loss: 1.008654

Epoch 685/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 685/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.31it/s]

End of Epoch 685 | Train Loss: 1.000747 | Val Loss: 0.983721

Epoch 686/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.979]
Epoch 686/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 686 | Train Loss: 1.000827 | Val Loss: 0.998609

Epoch 687/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.998]
Epoch 687/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 687 | Train Loss: 0.999947 | Val Loss: 1.018017

Epoch 688/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.15]
Epoch 688/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 688 | Train Loss: 1.003052 | Val Loss: 1.008539

Epoch 689/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.989]
Epoch 689/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 689 | Train Loss: 0.999354 | Val Loss: 0.990833

Epoch 690/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.983]
Epoch 690/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 690 | Train Loss: 0.996586 | Val Loss: 1.004422

Epoch 691/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 691/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.81it/s]

End of Epoch 691 | Train Loss: 1.002334 | Val Loss: 1.004312

Epoch 692/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.907]
Epoch 692/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 692 | Train Loss: 0.999094 | Val Loss: 1.007209

Epoch 693/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.999]
Epoch 693/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 693 | Train Loss: 0.998633 | Val Loss: 1.002927

Epoch 694/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 694/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 694 | Train Loss: 0.997397 | Val Loss: 1.006539

Epoch 695/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.995]
Epoch 695/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 695 | Train Loss: 1.000045 | Val Loss: 0.995240

Epoch 696/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.05]
Epoch 696/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 696 | Train Loss: 0.999931 | Val Loss: 1.004463

Epoch 697/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 697/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 697 | Train Loss: 0.997069 | Val Loss: 0.994795

Epoch 698/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.953]
Epoch 698/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 698 | Train Loss: 1.001559 | Val Loss: 0.993715

Epoch 699/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.07]
Epoch 699/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 699 | Train Loss: 1.000953 | Val Loss: 1.007858

Epoch 700/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.988]
Epoch 700/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.28it/s]

End of Epoch 700 | Train Loss: 1.000632 | Val Loss: 0.991792

Epoch 701/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 701/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 701 | Train Loss: 0.997712 | Val Loss: 1.005937

Epoch 702/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 702/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.81it/s]

End of Epoch 702 | Train Loss: 1.003185 | Val Loss: 0.993045

Epoch 703/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.11]
Epoch 703/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.71it/s]

End of Epoch 703 | Train Loss: 1.001340 | Val Loss: 0.994731

Epoch 704/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.919]
Epoch 704/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 704 | Train Loss: 1.001626 | Val Loss: 1.008927

Epoch 705/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.09]
Epoch 705/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 705 | Train Loss: 1.001160 | Val Loss: 1.018113

Epoch 706/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.03]
Epoch 706/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 706 | Train Loss: 1.002421 | Val Loss: 1.005447

Epoch 707/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.979]
Epoch 707/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 707 | Train Loss: 0.998550 | Val Loss: 1.007668

Epoch 708/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.05]
Epoch 708/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 708 | Train Loss: 0.999086 | Val Loss: 0.992817

Epoch 709/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 709/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 709 | Train Loss: 0.999057 | Val Loss: 1.007521

Epoch 710/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.04]
Epoch 710/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 710 | Train Loss: 0.999154 | Val Loss: 1.005773

Epoch 711/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1]
Epoch 711/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 711 | Train Loss: 0.999007 | Val Loss: 1.003280

Epoch 712/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.966]
Epoch 712/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 712 | Train Loss: 0.999760 | Val Loss: 0.994158

Epoch 713/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.989]
Epoch 713/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 713 | Train Loss: 0.998523 | Val Loss: 1.012057

Epoch 714/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.948]
Epoch 714/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 714 | Train Loss: 0.998468 | Val Loss: 0.986840

Epoch 715/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 715/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 715 | Train Loss: 0.999447 | Val Loss: 0.996355

Epoch 716/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.959]
Epoch 716/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 716 | Train Loss: 0.999024 | Val Loss: 1.002557

Epoch 717/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.929]
Epoch 717/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 717 | Train Loss: 0.995472 | Val Loss: 0.991347

Epoch 718/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.02]
Epoch 718/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.19it/s]

End of Epoch 718 | Train Loss: 0.999293 | Val Loss: 0.990907

Epoch 719/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.979]
Epoch 719/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 719 | Train Loss: 0.996223 | Val Loss: 1.011720

Epoch 720/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.05]
Epoch 720/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 720 | Train Loss: 0.997177 | Val Loss: 0.982976

Epoch 721/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.975]
Epoch 721/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 721 | Train Loss: 1.001423 | Val Loss: 1.003216

Epoch 722/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 722/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 722 | Train Loss: 0.999879 | Val Loss: 0.992229

Epoch 723/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.995]
Epoch 723/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 723 | Train Loss: 1.000628 | Val Loss: 0.995248

Epoch 724/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.05]
Epoch 724/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.18it/s]

End of Epoch 724 | Train Loss: 1.000173 | Val Loss: 1.007564

Epoch 725/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.975]
Epoch 725/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 725 | Train Loss: 1.000381 | Val Loss: 0.991033

Epoch 726/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 726/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 726 | Train Loss: 0.998701 | Val Loss: 1.010028

Epoch 727/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.06]
Epoch 727/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 727 | Train Loss: 0.998429 | Val Loss: 1.002827

Epoch 728/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.09]
Epoch 728/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 728 | Train Loss: 1.004535 | Val Loss: 1.016817

Epoch 729/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.964]
Epoch 729/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 729 | Train Loss: 0.998249 | Val Loss: 1.011826

Epoch 730/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.994]
Epoch 730/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 730 | Train Loss: 1.001113 | Val Loss: 1.018019

Epoch 731/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.988]
Epoch 731/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 731 | Train Loss: 1.003220 | Val Loss: 1.000683

Epoch 732/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.95]
Epoch 732/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.23it/s]

End of Epoch 732 | Train Loss: 1.001053 | Val Loss: 0.995976

Epoch 733/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.999]
Epoch 733/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 733 | Train Loss: 0.999034 | Val Loss: 0.983013

Epoch 734/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.01]
Epoch 734/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 734 | Train Loss: 0.999631 | Val Loss: 1.002374

Epoch 735/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.08]
Epoch 735/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 735 | Train Loss: 1.002517 | Val Loss: 1.017086

Epoch 736/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 736/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 736 | Train Loss: 0.998492 | Val Loss: 1.009154

Epoch 737/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.952]
Epoch 737/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.37it/s]

End of Epoch 737 | Train Loss: 1.002432 | Val Loss: 1.010103

Epoch 738/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.939]
Epoch 738/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 738 | Train Loss: 0.997574 | Val Loss: 0.982262

Epoch 739/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 739/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 739 | Train Loss: 0.999279 | Val Loss: 1.011840

Epoch 740/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 740/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 740 | Train Loss: 0.999231 | Val Loss: 1.004385

Epoch 741/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.991]
Epoch 741/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 741 | Train Loss: 1.000447 | Val Loss: 0.991118

Epoch 742/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.16it/s, loss=1.06]
Epoch 742/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.28it/s]

End of Epoch 742 | Train Loss: 1.001751 | Val Loss: 1.004734

Epoch 743/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1]
Epoch 743/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 743 | Train Loss: 1.001974 | Val Loss: 0.995294

Epoch 744/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.982]
Epoch 744/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 744 | Train Loss: 0.998521 | Val Loss: 0.998823

Epoch 745/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.981]
Epoch 745/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 745 | Train Loss: 1.000294 | Val Loss: 1.003195

Epoch 746/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.995]
Epoch 746/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 746 | Train Loss: 1.000738 | Val Loss: 1.008447

Epoch 747/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.975]
Epoch 747/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 747 | Train Loss: 1.000413 | Val Loss: 1.015819

Epoch 748/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.964]
Epoch 748/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 748 | Train Loss: 1.001123 | Val Loss: 1.004718

Epoch 749/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.05]
Epoch 749/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 749 | Train Loss: 1.001919 | Val Loss: 1.003610

Epoch 750/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.05]
Epoch 750/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 750 | Train Loss: 0.998756 | Val Loss: 1.001090

Epoch 751/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.952]
Epoch 751/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 751 | Train Loss: 0.997920 | Val Loss: 0.990500

Epoch 752/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.978]
Epoch 752/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.73it/s]

End of Epoch 752 | Train Loss: 1.000398 | Val Loss: 1.008691

Epoch 753/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.06]
Epoch 753/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 753 | Train Loss: 1.001184 | Val Loss: 0.988774

Epoch 754/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.04]
Epoch 754/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 754 | Train Loss: 0.999703 | Val Loss: 1.004297

Epoch 755/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=1.02]
Epoch 755/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 755 | Train Loss: 0.999654 | Val Loss: 0.983754

Epoch 756/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 756/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 756 | Train Loss: 0.997532 | Val Loss: 0.998095

Epoch 757/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 757/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 757 | Train Loss: 1.002468 | Val Loss: 1.009188

Epoch 758/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.979]
Epoch 758/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.28it/s]

End of Epoch 758 | Train Loss: 1.001626 | Val Loss: 1.003992

Epoch 759/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.991]
Epoch 759/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.47it/s]

End of Epoch 759 | Train Loss: 1.002433 | Val Loss: 0.996767

Epoch 760/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.05]
Epoch 760/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 760 | Train Loss: 1.000265 | Val Loss: 1.007899

Epoch 761/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.948]
Epoch 761/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.40it/s]

End of Epoch 761 | Train Loss: 1.002307 | Val Loss: 1.013763

Epoch 762/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.1]
Epoch 762/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 762 | Train Loss: 0.999442 | Val Loss: 1.001460

Epoch 763/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.968]
Epoch 763/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.32it/s]

End of Epoch 763 | Train Loss: 1.001736 | Val Loss: 0.999269

Epoch 764/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.96]
Epoch 764/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 764 | Train Loss: 0.998610 | Val Loss: 1.008438

Epoch 765/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.952]
Epoch 765/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 765 | Train Loss: 0.999480 | Val Loss: 0.999411

Epoch 766/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 766/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 766 | Train Loss: 1.001467 | Val Loss: 0.997710

Epoch 767/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.05]
Epoch 767/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 767 | Train Loss: 1.002112 | Val Loss: 1.022071

Epoch 768/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 768/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 768 | Train Loss: 0.997966 | Val Loss: 0.989803

Epoch 769/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1]
Epoch 769/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 769 | Train Loss: 1.001180 | Val Loss: 0.985847

Epoch 770/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.94]
Epoch 770/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.70it/s]

End of Epoch 770 | Train Loss: 0.998779 | Val Loss: 1.000499

Epoch 771/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 771/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 771 | Train Loss: 1.000336 | Val Loss: 0.987543

Epoch 772/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.1]
Epoch 772/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 772 | Train Loss: 1.003288 | Val Loss: 1.017706

Epoch 773/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.09]
Epoch 773/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 773 | Train Loss: 1.004756 | Val Loss: 0.994126

Epoch 774/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.945]
Epoch 774/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.94it/s]

End of Epoch 774 | Train Loss: 0.999903 | Val Loss: 1.008760

Epoch 775/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.897]
Epoch 775/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 775 | Train Loss: 0.999602 | Val Loss: 1.012778

Epoch 776/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.957]
Epoch 776/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.95it/s]

End of Epoch 776 | Train Loss: 0.997832 | Val Loss: 1.004651

Epoch 777/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.99]
Epoch 777/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 777 | Train Loss: 1.000597 | Val Loss: 0.987327

Epoch 778/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.999]
Epoch 778/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 778 | Train Loss: 1.000099 | Val Loss: 1.015097

Epoch 779/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.959]
Epoch 779/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 779 | Train Loss: 1.000857 | Val Loss: 1.005633

Epoch 780/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 780/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 780 | Train Loss: 1.000303 | Val Loss: 0.993707

Epoch 781/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 781/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 781 | Train Loss: 1.001441 | Val Loss: 0.991779

Epoch 782/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.11]
Epoch 782/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 782 | Train Loss: 1.001624 | Val Loss: 0.989006

Epoch 783/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.985]
Epoch 783/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.13it/s]

End of Epoch 783 | Train Loss: 0.999687 | Val Loss: 0.995426

Epoch 784/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.902]
Epoch 784/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 784 | Train Loss: 0.996803 | Val Loss: 1.006532

Epoch 785/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1]
Epoch 785/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 785 | Train Loss: 1.002688 | Val Loss: 0.987341

Epoch 786/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.941]
Epoch 786/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 786 | Train Loss: 1.000124 | Val Loss: 0.996968

Epoch 787/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.07]
Epoch 787/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 787 | Train Loss: 0.999108 | Val Loss: 0.994076

Epoch 788/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.927]
Epoch 788/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 788 | Train Loss: 0.999021 | Val Loss: 0.990201

Epoch 789/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 789/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 789 | Train Loss: 1.002027 | Val Loss: 1.009658

Epoch 790/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 790/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.87it/s]

End of Epoch 790 | Train Loss: 0.999309 | Val Loss: 0.998627

Epoch 791/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 791/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 791 | Train Loss: 1.000271 | Val Loss: 0.991503

Epoch 792/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.924]
Epoch 792/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 792 | Train Loss: 0.997318 | Val Loss: 1.004849

Epoch 793/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 793/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.25it/s]

End of Epoch 793 | Train Loss: 1.001674 | Val Loss: 1.004684

Epoch 794/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.966]
Epoch 794/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 794 | Train Loss: 0.999622 | Val Loss: 0.998429

Epoch 795/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.959]
Epoch 795/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 795 | Train Loss: 0.998100 | Val Loss: 0.999918

Epoch 796/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.912]
Epoch 796/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 796 | Train Loss: 1.000342 | Val Loss: 1.017388

Epoch 797/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.05]
Epoch 797/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 797 | Train Loss: 1.000537 | Val Loss: 1.009501

Epoch 798/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1.01]
Epoch 798/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 798 | Train Loss: 0.998766 | Val Loss: 1.002020

Epoch 799/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.974]
Epoch 799/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.21it/s]

End of Epoch 799 | Train Loss: 0.998211 | Val Loss: 1.004775

Epoch 800/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.955]
Epoch 800/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 800 | Train Loss: 0.997388 | Val Loss: 1.004737

Epoch 801/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 801/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 801 | Train Loss: 1.001081 | Val Loss: 0.990788

Epoch 802/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.985]
Epoch 802/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 802 | Train Loss: 0.997692 | Val Loss: 1.000392

Epoch 803/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1.02]
Epoch 803/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 803 | Train Loss: 0.998221 | Val Loss: 1.014249

Epoch 804/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.02]
Epoch 804/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 804 | Train Loss: 1.002290 | Val Loss: 1.006982

Epoch 805/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=1]
Epoch 805/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 805 | Train Loss: 0.996821 | Val Loss: 1.000177

Epoch 806/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.03]
Epoch 806/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 806 | Train Loss: 0.997400 | Val Loss: 0.993488

Epoch 807/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 807/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.90it/s]

End of Epoch 807 | Train Loss: 1.000180 | Val Loss: 1.002175

Epoch 808/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1]
Epoch 808/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.78it/s]

End of Epoch 808 | Train Loss: 0.999276 | Val Loss: 0.988068

Epoch 809/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.12]
Epoch 809/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.42it/s]

End of Epoch 809 | Train Loss: 1.002988 | Val Loss: 1.000668

Epoch 810/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.07]
Epoch 810/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.22it/s]

End of Epoch 810 | Train Loss: 1.002070 | Val Loss: 1.001208

Epoch 811/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.992]
Epoch 811/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 811 | Train Loss: 0.998478 | Val Loss: 0.995613

Epoch 812/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.919]
Epoch 812/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 812 | Train Loss: 1.000023 | Val Loss: 0.991604

Epoch 813/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1.02]
Epoch 813/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.30it/s]

End of Epoch 813 | Train Loss: 1.001856 | Val Loss: 1.016879

Epoch 814/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.19it/s, loss=0.925]
Epoch 814/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 814 | Train Loss: 1.000537 | Val Loss: 0.983218

Epoch 815/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.01]
Epoch 815/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 815 | Train Loss: 1.001092 | Val Loss: 1.005814

Epoch 816/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.04]
Epoch 816/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 816 | Train Loss: 0.999771 | Val Loss: 1.000427

Epoch 817/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=1]
Epoch 817/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 817 | Train Loss: 0.997743 | Val Loss: 1.005245

Epoch 818/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 818/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 818 | Train Loss: 1.001037 | Val Loss: 1.015073

Epoch 819/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.999]
Epoch 819/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 819 | Train Loss: 1.000699 | Val Loss: 1.003693

Epoch 820/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.1]
Epoch 820/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 820 | Train Loss: 1.002538 | Val Loss: 1.001773

Epoch 821/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.932]
Epoch 821/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 821 | Train Loss: 0.997441 | Val Loss: 0.994938

Epoch 822/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.959]
Epoch 822/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 822 | Train Loss: 0.998123 | Val Loss: 0.995923

Epoch 823/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1.04]
Epoch 823/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 823 | Train Loss: 0.999921 | Val Loss: 0.999352

Epoch 824/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.15it/s, loss=1.05]
Epoch 824/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 824 | Train Loss: 0.998968 | Val Loss: 1.004922

Epoch 825/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 825/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 825 | Train Loss: 0.999881 | Val Loss: 1.012231

Epoch 826/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.01]
Epoch 826/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 826 | Train Loss: 1.000103 | Val Loss: 1.009365

Epoch 827/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.11]
Epoch 827/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 827 | Train Loss: 1.000574 | Val Loss: 0.996443

Epoch 828/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.987]
Epoch 828/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.79it/s]

End of Epoch 828 | Train Loss: 1.002724 | Val Loss: 1.000874

Epoch 829/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.957]
Epoch 829/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 829 | Train Loss: 1.000234 | Val Loss: 0.996527

Epoch 830/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.976]
Epoch 830/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 830 | Train Loss: 0.998511 | Val Loss: 0.999899

Epoch 831/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.09]
Epoch 831/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 831 | Train Loss: 1.002042 | Val Loss: 1.004409

Epoch 832/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.03]
Epoch 832/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 832 | Train Loss: 1.001623 | Val Loss: 1.003752

Epoch 833/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 833/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.84it/s]

End of Epoch 833 | Train Loss: 1.000931 | Val Loss: 0.998014

Epoch 834/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=0.888]
Epoch 834/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 834 | Train Loss: 0.999319 | Val Loss: 0.997324

Epoch 835/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.954]
Epoch 835/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 835 | Train Loss: 0.999576 | Val Loss: 0.996383

Epoch 836/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.07]
Epoch 836/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 836 | Train Loss: 0.998073 | Val Loss: 0.991683

Epoch 837/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.1]
Epoch 837/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.68it/s]

End of Epoch 837 | Train Loss: 1.002201 | Val Loss: 0.995459

Epoch 838/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 838/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 838 | Train Loss: 1.001379 | Val Loss: 1.000252

Epoch 839/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.04]
Epoch 839/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 839 | Train Loss: 0.999018 | Val Loss: 0.999051

Epoch 840/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.968]
Epoch 840/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 840 | Train Loss: 0.998993 | Val Loss: 0.999316

Epoch 841/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.975]
Epoch 841/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.80it/s]

End of Epoch 841 | Train Loss: 1.000535 | Val Loss: 0.991450

Epoch 842/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.954]
Epoch 842/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 842 | Train Loss: 1.001257 | Val Loss: 0.998651

Epoch 843/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.933]
Epoch 843/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.81it/s]

End of Epoch 843 | Train Loss: 0.998012 | Val Loss: 1.019864

Epoch 844/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.992]
Epoch 844/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.76it/s]

End of Epoch 844 | Train Loss: 0.999360 | Val Loss: 0.999273

Epoch 845/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.02]
Epoch 845/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 845 | Train Loss: 0.999387 | Val Loss: 0.986458

Epoch 846/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.15]
Epoch 846/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 846 | Train Loss: 0.997050 | Val Loss: 0.986936

Epoch 847/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.994]
Epoch 847/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 847 | Train Loss: 0.999170 | Val Loss: 0.994458

Epoch 848/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.966]
Epoch 848/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 848 | Train Loss: 0.998267 | Val Loss: 1.001741

Epoch 849/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.978]
Epoch 849/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 849 | Train Loss: 1.000604 | Val Loss: 0.999822

Epoch 850/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.995]
Epoch 850/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 850 | Train Loss: 1.000489 | Val Loss: 0.997708

Epoch 851/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.975]
Epoch 851/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 851 | Train Loss: 0.999652 | Val Loss: 1.021959

Epoch 852/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.04]
Epoch 852/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.89it/s]

End of Epoch 852 | Train Loss: 1.001402 | Val Loss: 0.982039

Epoch 853/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.91]
Epoch 853/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.76it/s]

End of Epoch 853 | Train Loss: 0.996075 | Val Loss: 0.994269

Epoch 854/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.963]
Epoch 854/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 854 | Train Loss: 0.999920 | Val Loss: 1.006186

Epoch 855/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.01]
Epoch 855/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.87it/s]

End of Epoch 855 | Train Loss: 0.999606 | Val Loss: 1.022771

Epoch 856/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.909]
Epoch 856/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.73it/s]

End of Epoch 856 | Train Loss: 0.999386 | Val Loss: 1.026125

Epoch 857/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.04]
Epoch 857/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.69it/s]

End of Epoch 857 | Train Loss: 1.000567 | Val Loss: 0.989421

Epoch 858/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.22it/s, loss=1.06]
Epoch 858/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 858 | Train Loss: 0.999206 | Val Loss: 0.998500

Epoch 859/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.02]
Epoch 859/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.59it/s]

End of Epoch 859 | Train Loss: 1.001919 | Val Loss: 1.005118

Epoch 860/1000 [Train]: 100%|██████████| 90/90 [00:23<00:00,  3.90it/s, loss=1]
Epoch 860/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 22.81it/s]

End of Epoch 860 | Train Loss: 0.999852 | Val Loss: 1.010039

Epoch 861/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.13it/s, loss=1.05]
Epoch 861/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.75it/s]

End of Epoch 861 | Train Loss: 0.999985 | Val Loss: 0.994423

Epoch 862/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.02]
Epoch 862/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.76it/s]

End of Epoch 862 | Train Loss: 1.000528 | Val Loss: 0.998708

Epoch 863/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.992]
Epoch 863/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 863 | Train Loss: 0.997928 | Val Loss: 0.976740

Epoch 864/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 864/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 864 | Train Loss: 0.997704 | Val Loss: 0.998573

Epoch 865/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.906]
Epoch 865/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 865 | Train Loss: 1.001218 | Val Loss: 0.993482

Epoch 866/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.04]
Epoch 866/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 866 | Train Loss: 1.001721 | Val Loss: 0.990168

Epoch 867/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.01]
Epoch 867/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.97it/s]

End of Epoch 867 | Train Loss: 1.000364 | Val Loss: 1.026951

Epoch 868/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.958]
Epoch 868/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 868 | Train Loss: 1.000157 | Val Loss: 0.990894

Epoch 869/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.41it/s, loss=0.904]
Epoch 869/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 869 | Train Loss: 0.999448 | Val Loss: 0.999613

Epoch 870/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.996]
Epoch 870/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 870 | Train Loss: 0.998245 | Val Loss: 0.999531

Epoch 871/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.23it/s, loss=1]
Epoch 871/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.72it/s]

End of Epoch 871 | Train Loss: 1.003446 | Val Loss: 0.997395

Epoch 872/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.15it/s, loss=0.961]
Epoch 872/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.73it/s]

End of Epoch 872 | Train Loss: 0.999529 | Val Loss: 1.018696

Epoch 873/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.20it/s, loss=0.905]
Epoch 873/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 873 | Train Loss: 1.002944 | Val Loss: 0.990581

Epoch 874/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.995]
Epoch 874/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.39it/s]

End of Epoch 874 | Train Loss: 1.001055 | Val Loss: 0.982686

Epoch 875/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.05]
Epoch 875/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 875 | Train Loss: 1.003934 | Val Loss: 0.991841

Epoch 876/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 876/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 876 | Train Loss: 1.001786 | Val Loss: 0.993927

Epoch 877/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.03]
Epoch 877/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 877 | Train Loss: 1.003300 | Val Loss: 1.001475

Epoch 878/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.03]
Epoch 878/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 878 | Train Loss: 1.000196 | Val Loss: 0.978183

Epoch 879/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 879/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 879 | Train Loss: 0.999095 | Val Loss: 1.022365

Epoch 880/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.956]
Epoch 880/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 880 | Train Loss: 0.999699 | Val Loss: 1.014323

Epoch 881/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=1.01]
Epoch 881/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 881 | Train Loss: 0.998140 | Val Loss: 0.997903

Epoch 882/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.948]
Epoch 882/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 882 | Train Loss: 1.001686 | Val Loss: 0.997022

Epoch 883/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.901]
Epoch 883/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 883 | Train Loss: 1.000610 | Val Loss: 0.992418

Epoch 884/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.923]
Epoch 884/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 884 | Train Loss: 1.001041 | Val Loss: 1.010209

Epoch 885/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.986]
Epoch 885/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.99it/s]

End of Epoch 885 | Train Loss: 1.000773 | Val Loss: 1.004459

Epoch 886/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.03]
Epoch 886/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.95it/s]

End of Epoch 886 | Train Loss: 0.998024 | Val Loss: 0.988093

Epoch 887/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.934]
Epoch 887/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 887 | Train Loss: 0.998209 | Val Loss: 1.009399

Epoch 888/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=1.02]
Epoch 888/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 888 | Train Loss: 1.001429 | Val Loss: 1.009998

Epoch 889/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.991]
Epoch 889/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.08it/s]

End of Epoch 889 | Train Loss: 0.998269 | Val Loss: 0.993995

Epoch 890/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 890/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.06it/s]

End of Epoch 890 | Train Loss: 0.998818 | Val Loss: 0.998655

Epoch 891/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.06]
Epoch 891/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 891 | Train Loss: 0.999954 | Val Loss: 1.004564

Epoch 892/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 892/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 892 | Train Loss: 1.002296 | Val Loss: 0.996273

Epoch 893/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.982]
Epoch 893/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.67it/s]

End of Epoch 893 | Train Loss: 1.001721 | Val Loss: 1.003937

Epoch 894/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.07]
Epoch 894/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 894 | Train Loss: 1.000863 | Val Loss: 1.000446

Epoch 895/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=0.982]
Epoch 895/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 895 | Train Loss: 1.000079 | Val Loss: 0.987111

Epoch 896/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.02]
Epoch 896/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 896 | Train Loss: 0.997887 | Val Loss: 0.982197

Epoch 897/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.04]
Epoch 897/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 897 | Train Loss: 1.002857 | Val Loss: 0.994037

Epoch 898/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 898/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 898 | Train Loss: 1.004316 | Val Loss: 1.001692

Epoch 899/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.06]
Epoch 899/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 899 | Train Loss: 0.996712 | Val Loss: 1.002125

Epoch 900/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.879]
Epoch 900/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.77it/s]

End of Epoch 900 | Train Loss: 0.999234 | Val Loss: 0.993895

Epoch 901/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.09]
Epoch 901/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.20it/s]

End of Epoch 901 | Train Loss: 0.998792 | Val Loss: 0.993704

Epoch 902/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.04]
Epoch 902/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 902 | Train Loss: 1.002855 | Val Loss: 1.004992

Epoch 903/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.29it/s, loss=1.03]
Epoch 903/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 903 | Train Loss: 1.001252 | Val Loss: 0.989335

Epoch 904/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 904/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 904 | Train Loss: 1.002537 | Val Loss: 0.998286

Epoch 905/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 905/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.51it/s]

End of Epoch 905 | Train Loss: 0.999039 | Val Loss: 1.018313

Epoch 906/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.934]
Epoch 906/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 906 | Train Loss: 1.000538 | Val Loss: 0.995388

Epoch 907/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=1.11]
Epoch 907/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 907 | Train Loss: 0.999955 | Val Loss: 1.016784

Epoch 908/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.948]
Epoch 908/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.01it/s]

End of Epoch 908 | Train Loss: 0.998000 | Val Loss: 0.995357

Epoch 909/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=0.979]
Epoch 909/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 909 | Train Loss: 1.000403 | Val Loss: 0.995923

Epoch 910/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.08]
Epoch 910/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 910 | Train Loss: 1.004757 | Val Loss: 1.006519

Epoch 911/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.998]
Epoch 911/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.74it/s]

End of Epoch 911 | Train Loss: 1.002264 | Val Loss: 0.996779

Epoch 912/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.38it/s, loss=0.986]
Epoch 912/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 912 | Train Loss: 0.999603 | Val Loss: 0.998094

Epoch 913/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 913/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 913 | Train Loss: 1.001795 | Val Loss: 0.992207

Epoch 914/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.03]
Epoch 914/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 914 | Train Loss: 1.004050 | Val Loss: 1.000659

Epoch 915/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.1]
Epoch 915/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 915 | Train Loss: 1.001239 | Val Loss: 1.005858

Epoch 916/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.944]
Epoch 916/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.15it/s]

End of Epoch 916 | Train Loss: 1.002634 | Val Loss: 0.991705

Epoch 917/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.946]
Epoch 917/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 917 | Train Loss: 1.001323 | Val Loss: 0.994270

Epoch 918/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.982]
Epoch 918/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.63it/s]

End of Epoch 918 | Train Loss: 1.001036 | Val Loss: 0.979620

Epoch 919/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.06]
Epoch 919/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.58it/s]

End of Epoch 919 | Train Loss: 1.003668 | Val Loss: 0.998735

Epoch 920/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1.08]
Epoch 920/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.38it/s]

End of Epoch 920 | Train Loss: 1.001148 | Val Loss: 0.991234

Epoch 921/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.04]
Epoch 921/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.54it/s]

End of Epoch 921 | Train Loss: 1.002300 | Val Loss: 0.996225

Epoch 922/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.919]
Epoch 922/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 922 | Train Loss: 0.999268 | Val Loss: 1.007877

Epoch 923/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1]
Epoch 923/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.36it/s]

End of Epoch 923 | Train Loss: 0.997063 | Val Loss: 1.012713

Epoch 924/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.99]
Epoch 924/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 924 | Train Loss: 0.999323 | Val Loss: 1.010581

Epoch 925/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.01]
Epoch 925/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.25it/s]

End of Epoch 925 | Train Loss: 0.998974 | Val Loss: 1.009220

Epoch 926/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.40it/s, loss=1]
Epoch 926/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.17it/s]

End of Epoch 926 | Train Loss: 0.997846 | Val Loss: 0.978551

Epoch 927/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.07]
Epoch 927/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 927 | Train Loss: 1.001115 | Val Loss: 0.989622

Epoch 928/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.96]
Epoch 928/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 928 | Train Loss: 0.998718 | Val Loss: 1.011053

Epoch 929/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.965]
Epoch 929/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.05it/s]

End of Epoch 929 | Train Loss: 0.998163 | Val Loss: 1.002059

Epoch 930/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.986]
Epoch 930/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 930 | Train Loss: 0.998669 | Val Loss: 0.994077

Epoch 931/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.03]
Epoch 931/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.14it/s]

End of Epoch 931 | Train Loss: 1.003199 | Val Loss: 0.992966

Epoch 932/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.01]
Epoch 932/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.22it/s]

End of Epoch 932 | Train Loss: 0.999498 | Val Loss: 1.005254

Epoch 933/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 933/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 933 | Train Loss: 1.000706 | Val Loss: 1.003617

Epoch 934/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.936]
Epoch 934/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 934 | Train Loss: 1.000173 | Val Loss: 0.997692

Epoch 935/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.929]
Epoch 935/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.61it/s]

End of Epoch 935 | Train Loss: 1.000278 | Val Loss: 1.018873

Epoch 936/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.97]
Epoch 936/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.46it/s]

End of Epoch 936 | Train Loss: 0.997606 | Val Loss: 0.993422

Epoch 937/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.04]
Epoch 937/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.19it/s]

End of Epoch 937 | Train Loss: 0.999959 | Val Loss: 0.992625

Epoch 938/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.03]
Epoch 938/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.89it/s]

End of Epoch 938 | Train Loss: 1.000244 | Val Loss: 1.003270

Epoch 939/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.949]
Epoch 939/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.17it/s]

End of Epoch 939 | Train Loss: 0.996152 | Val Loss: 1.007162

Epoch 940/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.24it/s, loss=0.973]
Epoch 940/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.76it/s]

End of Epoch 940 | Train Loss: 1.000125 | Val Loss: 0.974578

Epoch 941/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=0.988]
Epoch 941/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.02it/s]

End of Epoch 941 | Train Loss: 0.997032 | Val Loss: 1.000219

Epoch 942/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=1.02]
Epoch 942/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.53it/s]

End of Epoch 942 | Train Loss: 0.998807 | Val Loss: 1.001154

Epoch 943/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.05]
Epoch 943/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 943 | Train Loss: 1.002438 | Val Loss: 0.994419

Epoch 944/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.01]
Epoch 944/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 944 | Train Loss: 1.002105 | Val Loss: 1.003123

Epoch 945/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 945/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.98it/s]

End of Epoch 945 | Train Loss: 1.004545 | Val Loss: 0.996401

Epoch 946/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.954]
Epoch 946/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 946 | Train Loss: 0.997406 | Val Loss: 0.993694

Epoch 947/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 947/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 947 | Train Loss: 1.000217 | Val Loss: 0.985722

Epoch 948/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.901]
Epoch 948/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 948 | Train Loss: 0.998456 | Val Loss: 0.993456

Epoch 949/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.939]
Epoch 949/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.28it/s]

End of Epoch 949 | Train Loss: 0.999315 | Val Loss: 0.993797

Epoch 950/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.988]
Epoch 950/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.07it/s]

End of Epoch 950 | Train Loss: 1.001092 | Val Loss: 1.006810

Epoch 951/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.974]
Epoch 951/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 951 | Train Loss: 1.000346 | Val Loss: 1.002668

Epoch 952/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.01]
Epoch 952/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 952 | Train Loss: 1.000113 | Val Loss: 1.005363

Epoch 953/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.962]
Epoch 953/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.06it/s]

End of Epoch 953 | Train Loss: 1.001528 | Val Loss: 1.006620

Epoch 954/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.15it/s, loss=0.974]
Epoch 954/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 954 | Train Loss: 0.999400 | Val Loss: 0.996059

Epoch 955/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.03]
Epoch 955/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.34it/s]

End of Epoch 955 | Train Loss: 1.000370 | Val Loss: 1.000699

Epoch 956/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.944]
Epoch 956/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.44it/s]

End of Epoch 956 | Train Loss: 0.999166 | Val Loss: 0.989717

Epoch 957/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.963]
Epoch 957/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.16it/s]

End of Epoch 957 | Train Loss: 1.000763 | Val Loss: 1.002487

Epoch 958/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.29it/s, loss=0.999]
Epoch 958/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 958 | Train Loss: 1.000439 | Val Loss: 0.994546

Epoch 959/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=1]
Epoch 959/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.00it/s]

End of Epoch 959 | Train Loss: 1.000406 | Val Loss: 0.990112

Epoch 960/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.983]
Epoch 960/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.09it/s]

End of Epoch 960 | Train Loss: 1.001885 | Val Loss: 1.003993

Epoch 961/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.936]
Epoch 961/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 961 | Train Loss: 0.998446 | Val Loss: 1.002554

Epoch 962/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.992]
Epoch 962/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.04it/s]

End of Epoch 962 | Train Loss: 1.002201 | Val Loss: 0.999968

Epoch 963/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.946]
Epoch 963/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.12it/s]

End of Epoch 963 | Train Loss: 0.999592 | Val Loss: 0.997347

Epoch 964/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.986]
Epoch 964/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 964 | Train Loss: 0.998119 | Val Loss: 0.985181

Epoch 965/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=1.02]
Epoch 965/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.65it/s]

End of Epoch 965 | Train Loss: 0.998214 | Val Loss: 1.007199

Epoch 966/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.995]
Epoch 966/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.94it/s]

End of Epoch 966 | Train Loss: 1.000992 | Val Loss: 0.996501

Epoch 967/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.977]
Epoch 967/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.10it/s]

End of Epoch 967 | Train Loss: 0.999562 | Val Loss: 1.000338

Epoch 968/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=0.934]
Epoch 968/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.93it/s]

End of Epoch 968 | Train Loss: 0.996860 | Val Loss: 0.996390

Epoch 969/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 969/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.57it/s]

End of Epoch 969 | Train Loss: 1.000297 | Val Loss: 1.007295

Epoch 970/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=0.98]
Epoch 970/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.33it/s]

End of Epoch 970 | Train Loss: 0.998872 | Val Loss: 1.015093

Epoch 971/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 971/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.55it/s]

End of Epoch 971 | Train Loss: 1.001187 | Val Loss: 0.991208

Epoch 972/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.27it/s, loss=0.993]
Epoch 972/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 972 | Train Loss: 0.999656 | Val Loss: 0.994972

Epoch 973/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.02]
Epoch 973/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 973 | Train Loss: 0.999462 | Val Loss: 0.991516

Epoch 974/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1]
Epoch 974/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.52it/s]

End of Epoch 974 | Train Loss: 0.998930 | Val Loss: 0.999592

Epoch 975/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=0.998]
Epoch 975/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 975 | Train Loss: 0.999676 | Val Loss: 0.999443

Epoch 976/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.30it/s, loss=1.01]
Epoch 976/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 976 | Train Loss: 0.999437 | Val Loss: 1.011434

Epoch 977/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.02]
Epoch 977/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.40it/s]

End of Epoch 977 | Train Loss: 1.000687 | Val Loss: 1.020672

Epoch 978/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.985]
Epoch 978/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 978 | Train Loss: 1.003745 | Val Loss: 1.014589

Epoch 979/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.906]
Epoch 979/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.26it/s]

End of Epoch 979 | Train Loss: 0.996996 | Val Loss: 1.014060

Epoch 980/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=1.02]
Epoch 980/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 27.68it/s]

End of Epoch 980 | Train Loss: 1.001159 | Val Loss: 0.991803

Epoch 981/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.34it/s, loss=1.14]
Epoch 981/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.64it/s]

End of Epoch 981 | Train Loss: 1.000172 | Val Loss: 0.995960

Epoch 982/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.28it/s, loss=0.93]
Epoch 982/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.49it/s]

End of Epoch 982 | Train Loss: 1.000841 | Val Loss: 0.994176

Epoch 983/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.05]
Epoch 983/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 983 | Train Loss: 1.001550 | Val Loss: 0.997209

Epoch 984/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.39it/s, loss=0.911]
Epoch 984/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.03it/s]

End of Epoch 984 | Train Loss: 0.999272 | Val Loss: 0.994696

Epoch 985/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.978]
Epoch 985/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 985 | Train Loss: 0.999589 | Val Loss: 1.000102

Epoch 986/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.906]
Epoch 986/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.11it/s]

End of Epoch 986 | Train Loss: 0.997387 | Val Loss: 0.998907

Epoch 987/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.36it/s, loss=0.904]
Epoch 987/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.66it/s]

End of Epoch 987 | Train Loss: 0.999536 | Val Loss: 0.996914

Epoch 988/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.37it/s, loss=0.962]
Epoch 988/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.28it/s]

End of Epoch 988 | Train Loss: 0.999551 | Val Loss: 0.999335

Epoch 989/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.35it/s, loss=0.944]
Epoch 989/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.93it/s]

End of Epoch 989 | Train Loss: 0.997850 | Val Loss: 0.991889

Epoch 990/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.25it/s, loss=1.02]
Epoch 990/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.45it/s]

End of Epoch 990 | Train Loss: 1.001114 | Val Loss: 1.003625

Epoch 991/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.999]
Epoch 991/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.56it/s]

End of Epoch 991 | Train Loss: 1.000951 | Val Loss: 1.009207

Epoch 992/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1]
Epoch 992/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.43it/s]

End of Epoch 992 | Train Loss: 1.001751 | Val Loss: 0.988315

Epoch 993/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.07]
Epoch 993/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 29.19it/s]

End of Epoch 993 | Train Loss: 1.000953 | Val Loss: 0.996432

Epoch 994/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=1.04]
Epoch 994/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.60it/s]

End of Epoch 994 | Train Loss: 0.999606 | Val Loss: 1.005332

Epoch 995/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1.01]
Epoch 995/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.62it/s]

End of Epoch 995 | Train Loss: 1.000303 | Val Loss: 0.997379

Epoch 996/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.32it/s, loss=1]
Epoch 996/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.41it/s]

End of Epoch 996 | Train Loss: 0.997502 | Val Loss: 0.994147

Epoch 997/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.33it/s, loss=0.975]
Epoch 997/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.50it/s]

End of Epoch 997 | Train Loss: 0.996329 | Val Loss: 1.015153

Epoch 998/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=1.03]
Epoch 998/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.18it/s]

End of Epoch 998 | Train Loss: 0.998591 | Val Loss: 0.999061

Epoch 999/1000 [Train]: 100%|██████████| 90/90 [00:20<00:00,  4.31it/s, loss=0.987]
Epoch 999/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.48it/s]

End of Epoch 999 | Train Loss: 1.000880 | Val Loss: 0.993612

Epoch 1000/1000 [Train]: 100%|██████████| 90/90 [00:21<00:00,  4.26it/s, loss=0.9]
Epoch 1000/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 28.24it/s]

End of Epoch 1000 | Train Loss: 1.000991 | Val Loss: 0.991735

In [27]:
batch = next(iter(test_loader))
print(f"x: {batch['x'].shape}, x_cond: {batch['x_cond'].shape}, dates: {batch['dates'].shape}")

x: torch.Size([1, 64, 14, 1]), x_cond: torch.Size([1, 64, 14, 6]), dates: torch.Size([1, 64])

In [28]:
def transform_dates(dates: torch.Tensor) -> pd.DatetimeIndex:
    dates_np = dates.cpu().numpy()
    dates_pd = pd.to_datetime(dates_np.flatten(), unit='ns')
    return dates_pd

In [29]:
transform_dates(batch['dates'])

DatetimeIndex(['2024-08-14', '2024-08-15', '2024-08-16', '2024-08-19',
               '2024-08-20', '2024-08-21', '2024-08-22', '2024-08-23',
               '2024-08-26', '2024-08-27', '2024-08-28', '2024-08-29',
               '2024-08-30', '2024-09-03', '2024-09-04', '2024-09-05',
               '2024-09-06', '2024-09-09', '2024-09-10', '2024-09-11',
               '2024-09-12', '2024-09-13', '2024-09-16', '2024-09-17',
               '2024-09-18', '2024-09-19', '2024-09-20', '2024-09-23',
               '2024-09-24', '2024-09-25', '2024-09-26', '2024-09-27',
               '2024-09-30', '2024-10-01', '2024-10-02', '2024-10-03',
               '2024-10-04', '2024-10-07', '2024-10-08', '2024-10-09',
               '2024-10-10', '2024-10-11', '2024-10-14', '2024-10-15',
               '2024-10-16', '2024-10-17', '2024-10-18', '2024-10-21',
               '2024-10-22', '2024-10-23', '2024-10-24', '2024-10-25',
               '2024-10-28', '2024-10-29', '2024-10-30', '2024-10-31',
               '2024-11-01', '2024-11-04', '2024-11-05', '2024-11-06',
               '2024-11-07', '2024-11-08', '2024-11-11', '2024-11-12'],
              dtype='datetime64[ns]', freq=None)

In [30]:
def autoregressive(x: np.ndarray, x_cond: np.ndarray, steps: int, n_samples: int):
    B, W, A, F_target = x.shape
    period_curr = W - steps
    device = next(engine.model.parameters()).device

    x_curr = torch.as_tensor(x[:, :period_curr, :, :], dtype=torch.float32).to(device)
    x_cond_curr = torch.as_tensor(x_cond[:, :period_curr, :, :], dtype=torch.float32).to(device)

    x_curr = x_curr.to(device)
    x_cond_curr = x_cond_curr.to(device)

    # Monte Carlo Build
    x_curr = x_curr.repeat(n_samples, 1, 1, 1)
    x_cond_curr = x_cond_curr.repeat(n_samples, 1, 1, 1)

    results = []
    print(f"Start Auto-regression: Initial W={period_curr}, Target Steps={steps}")

    pbar = tqdm(range(steps))
    for i in pbar:
        pbar.set_description(f"window size {x_curr.shape[1]}...")
        batch = {
            "x": x_curr,
            "x_cond": x_cond_curr
        }

        _, next_step_x, _, _ = engine.simulate(batch, steps=1, inverse_scale=False)
        
        results.append(next_step_x)
        
        x_curr = torch.cat([x_curr, next_step_x], dim=1)
            
        idx = period_curr + i
            
        next_cond_slice_np = x_cond[:, idx : idx+1, :, :]
            
        next_cond_slice = torch.as_tensor(next_cond_slice_np, dtype=torch.float32).to(device)
        next_cond_slice = next_cond_slice.repeat(n_samples, 1, 1, 1)

        x_cond_curr = torch.cat([x_cond_curr, next_cond_slice], dim=1)

    scaled_sim_genai = torch.cat(results, dim=1).cpu().numpy()
    sim_genai, sim_genai_cond = inverse_scale_pair(scaled_sim_genai, x_cond_curr[:, -steps:, : ,:], scaler)
    
    scaled_full_sim_genai = x_curr.detach().cpu().numpy()
    full_sim_genai, full_sim_genai_cond = inverse_scale_pair(scaled_full_sim_genai, x_cond_curr, scaler)
    
    return full_sim_genai, sim_genai, full_sim_genai_cond, sim_genai_cond

In [ ]:
full_sim_genai, sim_genai, _, _ = autoregressive(batch['x'], batch['x_cond'], 8, 1000)
print(f"x_curr: {x_curr.shape}, final_prediction: {final_prediction.shape}")

Start Auto-regression: Initial W=56, Target Steps=8

window size 60...:  50%|█████     | 4/8 [10:50<10:55, 163.90s/it]

In [ ]:
gt, gt_cond = inverse_scale_pair(batch['x'], batch['x_cond'], scaler)
stats_batch = {
    'x': torch.as_tensor(gt).to(device),
    'x_cond': torch.as_tensor(gt_cond).to(device)
}
sim_stats = engine.gbm_simulate(stats_batch, steps=8, n_samples=1000)
sim_stats.shape

In [ ]:
rand_ind = np.random.randint(0, len(sim_genai))
sim_genai_sample = sim_genai[rand_ind].squeeze(-1)
sim_stats_sample = sim_stats[rand_ind].squeeze(-1)
print(f"sim_genai_sample: {sim_genai_sample.shape}, sim_stats_sample: {sim_stats_sample.shape}")

In [ ]:
dates = transform_dates(batch['dates'])
dates.shape

In [ ]:
engine.benchmark(gt=gt, sim_genai=sim_genai_sample, sim_stats=sim_stats_sample, dates=dates)