# Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import logging
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
import talib as ta

from torch import optim
from torch.utils.data import DataLoader, Dataset, TensorDataset, random_split
from tqdm import tqdm

from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.optim import AdamW
from utils import SklearnWrapper, verify_scaling
from utils.paths import CHECKPOINTS_DIR
from pypfopt import risk_models, expected_returns, plotting, EfficientFrontier

In [2]:
from config import *
from entities import *
from strategies import *
from datasets import *
from engine import Engine
from models import DiffusionTransformer, Diffusion

# Setup

In [3]:
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('matplotlib').setLevel(logging.WARNING)

In [4]:
cfg = TrainConfig(
    epochs=2000
)
window_size = cfg.window_size
device = cfg.device
batch_size = cfg.batch_size
epochs = cfg.epochs

ddpm = {
    'timesteps': int(1000),
    'beta_start': 0.0001,
    'beta_end': 0.02
}

ddpm_transformer = {
    'n_features': 1,
    'n_cond': 10,
    'window_size': 60,
    'd_model': 128,
    'nhead': 4,
    'num_layers': 3,
    'dim_feedforward': 512,
    'dropout': 0.1
}

# Data [N, W, A, F]
**[N, T, A, F]** means: 
* **N**: Num of Window or Num of Batch
* **W**: Window
* **A**: Assets
* **F**: Features or Channels

In [5]:
symbols = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO']
freq = "1d"

# Basket
basket = Basket(symbols=symbols)
basket.load_all_assets(freq=freq)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

DEBUG:entities.basket:Initialized Asset Basket: ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO'] with 0 assets which loaded.
INFO:entities.basket:Starting batch load for 14 symbols...
DEBUG:entities.basket:Attempting to load AAPL...
DEBUG:entities.asset:Initialized Asset: AAPL with 2724 rows.
INFO:entities.basket:Successfully loaded AAPL (2724 rows).
DEBUG:entities.basket:Attempting to load TSLA...
DEBUG:entities.asset:Initialized Asset: TSLA with 2760 rows.
INFO:entities.basket:Successfully loaded TSLA (2760 rows).
DEBUG:entities.basket:Attempting to load MSFT...
DEBUG:entities.asset:Initialized Asset: MSFT with 2724 rows.
INFO:entities.basket:Successfully loaded MSFT (2724 rows).
DEBUG:entities.basket:Attempting to load NVDA...
DEBUG:entities.asset:Initialized Asset: NVDA with 2724 rows.
INFO:entities.basket:Successfully loaded NVDA (2724 rows).
DEBUG:entities.basket:Attempting to load GOOGL...
DEBUG:entities.asset:Initialized Asset: GOOGL with 2760 rows.
INFO:entities.basket:Successfully loaded GOOGL (2760 rows).
DEBUG:entities.basket:Attempting to load AMZN...
DEBUG:entities.asset:Initialized Asset: AMZN with 2760 rows.
INFO:entities.basket:Successfully loaded AMZN (2760 rows).
DEBUG:entities.basket:Attempting to load GOOG...
DEBUG:entities.asset:Initialized Asset: GOOG with 1464 rows.
INFO:entities.basket:Successfully loaded GOOG (1464 rows).
DEBUG:entities.basket:Attempting to load META...
DEBUG:entities.asset:Initialized Asset: META with 2760 rows.
INFO:entities.basket:Successfully loaded META (2760 rows).
DEBUG:entities.basket:Attempting to load AVGO...
DEBUG:entities.asset:Initialized Asset: AVGO with 2724 rows.
INFO:entities.basket:Successfully loaded AVGO (2724 rows).
DEBUG:entities.basket:Attempting to load ORCL...
DEBUG:entities.asset:Initialized Asset: ORCL with 2724 rows.
INFO:entities.basket:Successfully loaded ORCL (2724 rows).
DEBUG:entities.basket:Attempting to load CRM...
DEBUG:entities.asset:Initialized Asset: CRM with 2724 rows.
INFO:entities.basket:Successfully loaded CRM (2724 rows).
DEBUG:entities.basket:Attempting to load ADBE...
DEBUG:entities.asset:Initialized Asset: ADBE with 2724 rows.
INFO:entities.basket:Successfully loaded ADBE (2724 rows).
DEBUG:entities.basket:Attempting to load AMD...
DEBUG:entities.asset:Initialized Asset: AMD with 2724 rows.
INFO:entities.basket:Successfully loaded AMD (2724 rows).
DEBUG:entities.basket:Attempting to load CSCO...
DEBUG:entities.asset:Initialized Asset: CSCO with 2724 rows.
INFO:entities.basket:Successfully loaded CSCO (2724 rows).
INFO:entities.basket:Batch load complete. Success: 14/14. Total assets in basket: 14

Basket data shape: (2760, 70)

                 AAPL                                                \
                Close       High        Low       Open       Volume
Date
2015-01-02  24.261047  24.729270  23.821672  24.718174  212818400.0
2015-01-05  23.577574  24.110150  23.391173  24.030263  257142000.0
2015-01-06  23.579794  23.839424  23.218085  23.641928  263188400.0
2015-01-07  23.910433  24.010290  23.677430  23.788384  160423600.0
2015-01-08  24.829119  24.886815  24.121236  24.238848  237458000.0

                 TSLA                                             ...   AMD  \
                Close       High        Low       Open    Volume  ... Close
Date                                                              ...
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  ...  2.67
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  ...  2.66
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  ...  2.63
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  ...  2.58
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  ...  2.61

                                               CSCO                        \
            High   Low  Open      Volume      Close       High        Low
Date
2015-01-02  2.67  2.67  2.67         0.0  19.815605  20.181631  19.650534
2015-01-05  2.70  2.64  2.67   8878200.0  19.420874  19.700776  19.377812
2015-01-06  2.66  2.55  2.65  13912500.0  19.413698  19.865848  19.406522
2015-01-07  2.65  2.54  2.63  12377600.0  19.593126  19.664896  19.363463
2015-01-08  2.65  2.56  2.59  11136600.0  19.743843  20.160107  19.715135


                 Open      Volume
Date
2015-01-02  19.995029  22926500.0
2015-01-05  19.607475  29460600.0
2015-01-06  19.478291  47297600.0
2015-01-07  19.478295  27570800.0
2015-01-08  19.765374  40907000.0

[5 rows x 70 columns]

## Features/Channels ($F$)
1. Find Joint Distribution $F_{\text{date\ A}} \cap F_{\text{date\ B}}$ with intersection
2. Select $F$ to norm as Return values

In [6]:
targets = ["Close"]
features = basket.get_unique_features()
print(f"Features:\t{features}\nTargets:\t{targets}")

Features:	['Close', 'High', 'Low', 'Open', 'Volume']
Targets:	['Close']

In [7]:
print(f"Basket data shape before Joint: {basket.data.shape}")

joint_strategy = IntersectionStrategy()
basket.align(joint_strategy)

print(f"Basket data shape after Joint: {basket.data.shape}")

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 1464 rows
DEBUG:entities.basket:Aligned data shape: (1464, 70)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 1464)

Basket data shape before Joint: (2760, 70)
Basket data shape after Joint: (1464, 70)

In [8]:
basket.to_returns(features=targets, log=True, keep=False)
targets = basket.get_keyword_features("Returns")
features = basket.get_unique_features()

print(f"Features:\t{features}\nTargets:\t{targets}")
basket.data.head(5)

DEBUG:entities.asset:AAPL converted to Returns (log=True)
DEBUG:entities.asset:TSLA converted to Returns (log=True)
DEBUG:entities.asset:MSFT converted to Returns (log=True)
DEBUG:entities.asset:NVDA converted to Returns (log=True)
DEBUG:entities.asset:GOOGL converted to Returns (log=True)
DEBUG:entities.asset:AMZN converted to Returns (log=True)
DEBUG:entities.asset:GOOG converted to Returns (log=True)
DEBUG:entities.asset:META converted to Returns (log=True)
DEBUG:entities.asset:AVGO converted to Returns (log=True)
DEBUG:entities.asset:ORCL converted to Returns (log=True)
DEBUG:entities.asset:CRM converted to Returns (log=True)
DEBUG:entities.asset:ADBE converted to Returns (log=True)
DEBUG:entities.asset:AMD converted to Returns (log=True)
DEBUG:entities.asset:CSCO converted to Returns (log=True)

Features:	['Close_Log_Returns', 'High', 'Low', 'Open', 'Volume']
Targets:	{'Close_Log_Returns'}

                 AAPL                                                     \
                 High        Low       Open     Volume Close_Log_Returns
Date
2020-01-03  72.594055  71.608685  71.765667  146322800         -0.009770
2020-01-06  72.444344  70.703034  70.954210  118387200          0.007937
2020-01-07  72.671341  71.845369  72.415337  108872000         -0.004715
2020-01-08  73.526310  71.768094  71.768094  132079200          0.015958
2020-01-09  74.972955  73.951358  74.202527  170108400          0.021018

                 TSLA                                                     ...  \
                 High        Low       Open     Volume Close_Log_Returns  ...
Date                                                                      ...
2020-01-03  30.266666  29.128000  29.366667  266677500          0.029203  ...
2020-01-06  30.104000  29.333332  29.364668  151995000          0.019072  ...
2020-01-07  31.441999  30.224001  30.760000  268231500          0.038067  ...
2020-01-08  33.232666  31.215334  31.580000  467164500          0.048033  ...
2020-01-09  33.253334  31.524668  33.139999  426606000         -0.022189  ...

                  AMD                                                    \
                 High        Low       Open    Volume Close_Log_Returns
Date
2020-01-03  49.389999  47.540001  48.029999  73127400         -0.010236
2020-01-06  48.860001  47.860001  48.020000  47934900         -0.004330
2020-01-07  49.389999  48.040001  49.349998  58061400         -0.002897
2020-01-08  48.299999  47.139999  47.849998  53767000         -0.008743
2020-01-09  49.959999  48.389999  48.939999  76512800          0.023555

                 CSCO
                 High        Low       Open    Volume Close_Log_Returns
Date
2020-01-03  40.453623  39.899004  40.260347  15577400         -0.016450
2020-01-06  40.184715  39.504044  39.613288  22183600          0.003563
2020-01-07  40.100678  39.579670  40.100678  16501900         -0.006507
2020-01-08  40.159507  39.335982  39.470435  25175900          0.000632
2020-01-09  40.235133  39.554462  40.159503  18203600         -0.004218

[5 rows x 70 columns]

### Add Indicators as Features ($F$)

In [9]:
# Indicator
time_prd = 20
fast_prd, slow_prd, signal_prd = 12, 26, 9

for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        s = df[target]
        
        df[f"SMA_{time_prd} {target}"] = ta.SMA(s, timeperiod=time_prd)
        df[f"EMA_{time_prd} {target}"] = ta.EMA(s, timeperiod=time_prd)
        df[f"RSI_{time_prd} {target}"] = ta.RSI(s, timeperiod=time_prd)
        
        macd, signal, hist = ta.MACD(s, fastperiod=fast_prd, slowperiod=slow_prd, signalperiod=signal_prd)
        df[f"MACD {target}"] = macd
        df[f"MACD_Sig {target}"] = signal
        df[f"MACD_Hist {target}"] = hist

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (1463, 154)

                 AAPL                                                     \
                 High        Low       Open     Volume Close_Log_Returns
Date
2020-01-03  72.594055  71.608685  71.765667  146322800         -0.009770
2020-01-06  72.444344  70.703034  70.954210  118387200          0.007937
2020-01-07  72.671341  71.845369  72.415337  108872000         -0.004715
2020-01-08  73.526310  71.768094  71.768094  132079200          0.015958
2020-01-09  74.972955  73.951358  74.202527  170108400          0.021018

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2020-01-03                      NaN                      NaN
2020-01-06                      NaN                      NaN
2020-01-07                      NaN                      NaN
2020-01-08                      NaN                      NaN
2020-01-09                      NaN                      NaN

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2020-01-03                      NaN                    NaN
2020-01-06                      NaN                    NaN
2020-01-07                      NaN                    NaN
2020-01-08                      NaN                    NaN
2020-01-09                      NaN                    NaN

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2020-01-03                        NaN  ...  39.899004  40.260347  15577400
2020-01-06                        NaN  ...  39.504044  39.613288  22183600
2020-01-07                        NaN  ...  39.579670  40.100678  16501900
2020-01-08                        NaN  ...  39.335982  39.470435  25175900
2020-01-09                        NaN  ...  39.554462  40.159503  18203600

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2020-01-03         -0.016450                      NaN
2020-01-06          0.003563                      NaN
2020-01-07         -0.006507                      NaN
2020-01-08          0.000632                      NaN
2020-01-09         -0.004218                      NaN

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2020-01-03                      NaN                      NaN
2020-01-06                      NaN                      NaN
2020-01-07                      NaN                      NaN
2020-01-08                      NaN                      NaN
2020-01-09                      NaN                      NaN

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2020-01-03                    NaN                        NaN
2020-01-06                    NaN                        NaN
2020-01-07                    NaN                        NaN
2020-01-08                    NaN                        NaN
2020-01-09                    NaN                        NaN


           MACD_Hist Close_Log_Returns
Date
2020-01-03                         NaN
2020-01-06                         NaN
2020-01-07                         NaN
2020-01-08                         NaN
2020-01-09                         NaN

[5 rows x 154 columns]

In [10]:
basket.align(joint_strategy)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 1430 rows
DEBUG:entities.basket:Aligned data shape: (1430, 154)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 1430)

Basket data shape: (1430, 154)

                 AAPL                                                     \
                 High        Low       Open     Volume Close_Log_Returns
Date
2020-02-21  77.576610  75.167846  77.133587  129554000         -0.022895
2020-02-24  73.637844  70.018657  71.962610  222195200         -0.048666
2020-02-25  73.238425  69.268208  72.855932  230673600         -0.034459
2020-02-26  72.112718  69.357773  69.365035  198054800          0.015739
2020-02-27  69.236734  66.079924  68.050512  320605600         -0.067603

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2020-02-21                -0.000859                -0.001142
2020-02-24                -0.003148                -0.005668
2020-02-25                -0.003379                -0.008410
2020-02-26                -0.003986                -0.006110
2020-02-27                -0.008402                -0.011966

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2020-02-21                47.685660              -0.003591
2020-02-24                44.698556              -0.006871
2020-02-25                46.638298              -0.008229
2020-02-26                52.796367              -0.005195
2020-02-27                43.935380              -0.009407

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2020-02-21                  -0.001783  ...  38.697334  39.268761  20028700
2020-02-24                  -0.002801  ...  36.974636  37.814969  35295900
2020-02-25                  -0.003886  ...  35.352796  37.016655  48024700
2020-02-26                  -0.004148  ...  35.243558  36.109103  38513200
2020-02-27                  -0.005200  ...  33.621711  34.688934  51442900

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2020-02-21         -0.011809                -0.002834
2020-02-24         -0.050953                -0.005228
2020-02-25         -0.029054                -0.005248
2020-02-26         -0.013663                -0.006246
2020-02-27         -0.051593                -0.008067

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2020-02-21                -0.002368                49.539877
2020-02-24                -0.006995                44.596763
2020-02-25                -0.009096                47.671511
2020-02-26                -0.009531                49.735314
2020-02-27                -0.013537                45.119161

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2020-02-21              -0.001908                  -0.001762
2020-02-24              -0.005450                  -0.002500
2020-02-25              -0.006416                  -0.003283
2020-02-26              -0.005872                  -0.003801
2020-02-27              -0.008404                  -0.004721


           MACD_Hist Close_Log_Returns
Date
2020-02-21                   -0.000145
2020-02-24                   -0.002950
2020-02-25                   -0.003133
2020-02-26                   -0.002071
2020-02-27                   -0.003683

[5 rows x 154 columns]

### Filter only Target Features ($F_{target} $)

In [11]:
targets = basket.get_keyword_features("Returns")
print(f"Targets: {targets}")


for symbol, asset in basket.assets.items():
    mask = asset.data.columns.isin(targets)
    asset.data = asset.data.loc[:, mask]

print(f"Basket shape: {basket.data.shape}")
basket.data.head(5)

Targets: {'SMA_20 Close_Log_Returns', 'EMA_20 Close_Log_Returns', 'MACD_Hist Close_Log_Returns', 'MACD Close_Log_Returns', 'MACD_Sig Close_Log_Returns', 'Close_Log_Returns', 'RSI_20 Close_Log_Returns'}
Basket shape: (1430, 98)

                        AAPL                           \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2020-02-21         -0.022895                -0.000859
2020-02-24         -0.048666                -0.003148
2020-02-25         -0.034459                -0.003379
2020-02-26          0.015739                -0.003986
2020-02-27         -0.067603                -0.008402

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2020-02-21                -0.001142                47.685660
2020-02-24                -0.005668                44.698556
2020-02-25                -0.008410                46.638298
2020-02-26                -0.006110                52.796367
2020-02-27                -0.011966                43.935380

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2020-02-21              -0.003591                  -0.001783
2020-02-24              -0.006871                  -0.002801
2020-02-25              -0.008229                  -0.003886
2020-02-26              -0.005195                  -0.004148
2020-02-27              -0.009407                  -0.005200

                                                    TSLA  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2020-02-21                   -0.001808          0.001766
2020-02-24                   -0.004070         -0.077524
2020-02-25                   -0.004343         -0.041482
2020-02-26                   -0.001047         -0.026745
2020-02-27                   -0.004207         -0.137133

                                                              ...  \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns  ...
Date                                                          ...
2020-02-21                 0.022701                 0.020150  ...
2020-02-24                 0.019474                 0.010847  ...
2020-02-25                 0.018005                 0.005864  ...
2020-02-26                 0.015879                 0.002758  ...
2020-02-27                 0.007794                -0.010565  ...

                              AMD                             \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2020-02-21              -0.005277                   0.000718
2020-02-24              -0.010997                  -0.001625
2020-02-25              -0.011426                  -0.003585
2020-02-26              -0.009208                  -0.004710
2020-02-27              -0.013302                  -0.006428

                                                    CSCO  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2020-02-21                   -0.005995         -0.011809
2020-02-24                   -0.009372         -0.050953
2020-02-25                   -0.007841         -0.029054
2020-02-26                   -0.004498         -0.013663
2020-02-27                   -0.006874         -0.051593

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2020-02-21                -0.002834                -0.002368
2020-02-24                -0.005228                -0.006995
2020-02-25                -0.005248                -0.009096
2020-02-26                -0.006246                -0.009531
2020-02-27                -0.008067                -0.013537

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2020-02-21                49.539877              -0.001908
2020-02-24                44.596763              -0.005450
2020-02-25                47.671511              -0.006416
2020-02-26                49.735314              -0.005872
2020-02-27                45.119161              -0.008404


           MACD_Sig Close_Log_Returns MACD_Hist Close_Log_Returns
Date
2020-02-21                  -0.001762                   -0.000145
2020-02-24                  -0.002500                   -0.002950
2020-02-25                  -0.003283                   -0.003133
2020-02-26                  -0.003801                   -0.002071
2020-02-27                  -0.004721                   -0.003683

[5 rows x 98 columns]

## Dataset & Dataloader

In [12]:
n_obs = len(basket.data)
n_assets = basket.data.columns.levels[0].size
n_features = basket.data.columns.levels[1].size

print(n_obs, n_assets, n_features)

basket_np = basket.data.values.reshape(n_obs, n_assets, n_features)
basket_np.shape

1430 14 7

(1430, 14, 7)

### Ratio Dataset

In [13]:
ratios = [0.8, 0.1, 0.1]
total_count = len(basket_np)
train_count = int(total_count * ratios[0])
val_count = int(total_count * ratios[1])
test_count = total_count - train_count - val_count

print(f"Ratios DS\nTrain:\t{train_count}\nVal:\t{val_count}\nTest:\t{test_count}\nTotal:\t{total_count}")

Ratios DS
Train:	1144
Val:	143
Test:	143
Total:	1430

In [14]:
end_val = train_count + val_count

# Ratios
train_part = basket_np[:train_count]
val_part = basket_np[train_count:end_val]
test_part = basket_np[end_val:]

print(f"Train: {train_part.shape}\nVal: {val_part.shape}\nTest:{test_part.shape}")

Train: (1144, 14, 7)
Val: (143, 14, 7)
Test:(143, 14, 7)

### Scale Dataset

In [15]:
def scale(part: np.ndarray, scaler) -> np.ndarray:
    T, A, F = part.shape
    part_2d = part.reshape(-1, F)

    # print(f"2D Part: {part_2d.shape}")

    scaled_part = scaler.transform(part_2d).reshape(T, A, F)
    return scaled_part.astype(np.float32)

In [16]:
def inspect_scaled_data(data, name):
    if isinstance(data, torch.Tensor):
        data = data.detach().cpu().numpy()

    _min = np.min(data)
    _max = np.max(data)
    _mean = np.mean(data)
    _std = np.std(data)
    
    print(f"--- Inspecting: {name} ---")
    print("-" * 36)
    print(f"Shape: {data.shape}")
    print(f"Min:   {_min:.4f}")
    print(f"Max:   {_max:.4f}")
    print(f"Mean:  {_mean:.4f}")
    print(f"Std:   {_std:.4f}")
    print("-" * 36)
    return _min, _max, _mean, _std

In [17]:
scaler = MinMaxScaler(feature_range=(-1, 1))
# scaler = StandardScaler()

# Require 2D Numpy Array
T, A, F = train_part.shape
scaler.fit(train_part.reshape(-1, F))

scaled_train_part = scale(train_part, scaler)
scaled_val_part = scale(val_part, scaler)
scaled_test_part = scale(test_part, scaler)

inspect_scaled_data(scaled_train_part, "Scaled Train Part")
inspect_scaled_data(scaled_val_part, "Scaled Val Part")
inspect_scaled_data(scaled_test_part, "Scaled Test Part")
print(f"Train:\t{scaled_train_part.shape}\nVal:\t{scaled_val_part.shape}\nTest:\t{scaled_test_part.shape}")

--- Inspecting: Scaled Train Part ---
------------------------------------
Shape: (1144, 14, 7)
Min:   -1.0000
Max:   1.0000
Mean:  0.1377
Std:   0.1432
------------------------------------
--- Inspecting: Scaled Val Part ---
------------------------------------
Shape: (143, 14, 7)
Min:   -0.7688
Max:   1.0350
Mean:  0.1300
Std:   0.1383
------------------------------------
--- Inspecting: Scaled Test Part ---
------------------------------------
Shape: (143, 14, 7)
Min:   -0.6135
Max:   1.2813
Mean:  0.1548
Std:   0.1447
------------------------------------
Train:	(1144, 14, 7)
Val:	(143, 14, 7)
Test:	(143, 14, 7)

### Dataloader

In [18]:
train_ds = MarketDataset(scaled_train_part, window_size=window_size)
val_ds = MarketDataset(scaled_val_part, window_size=window_size)
test_ds = MarketDataset(scaled_test_part, window_size=window_size)

print(f"Num of Windows\nTrain DS: {len(train_ds)}, Val Ds: {len(val_ds)}, Test DS: {len(test_ds)}\n")
print(f"A sample shape from Train DS\n\tx: {train_ds[0]['x'].shape},\n\tx_cond: {train_ds[0]['x_cond'].shape}")

Num of Windows
Train DS: 1081, Val Ds: 80, Test DS: 80

A sample shape from Train DS
	x: (64, 14, 1),
	x_cond: (64, 14, 6)

In [19]:
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=batch_size, shuffle=False)

batch = next(iter(train_loader))
print(len(train_loader))
print(batch["x"].shape)
print(batch["x_cond"].shape)

34
torch.Size([32, 64, 14, 1])
torch.Size([32, 64, 14, 6])

# Model, Engine
Use *Condition DDPM*

In [20]:
# n_window mean batch size
n_window, window, n_assets, n_features = batch["x"].shape
n_window, window, n_assets, n_conds = batch["x_cond"].shape
print(n_assets, n_features, n_conds)

input_channels = n_assets * n_features
cond_channels = n_assets * n_conds
print(input_channels, cond_channels)

14 1 6
14 84

In [21]:
model = DiffusionTransformer(
    n_features=input_channels,
    n_cond=cond_channels,        
    window_size=window_size,             
    d_model=ddpm_transformer['d_model'],                
    nhead=ddpm_transformer['nhead'],
    num_layers=ddpm_transformer['num_layers'],
    dim_feedforward=ddpm_transformer['dim_feedforward'],
    dropout=ddpm_transformer['dropout']
).to(device)

In [22]:
diffusion = Diffusion(model, timesteps=ddpm['timesteps'], beta_start=ddpm['beta_start'], beta_end=ddpm['beta_end']).to(device)

In [23]:
optimizer = AdamW(model.parameters(), lr=cfg.optimizer.lr, weight_decay=cfg.optimizer.weight_decay)

In [24]:
for epoch in range(epochs):
    diffusion.train()
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
    
    for batch in pbar:
        # x: [32, 64, 14, 1]
        x_raw = batch["x"].to(device).float()
        
        # x_cond: [32, 64, 14, 6]
        cond_raw = batch["x_cond"].to(device).float()
        
        batch_size = x_raw.shape[0]

        # print(f"x_raw: {x_raw.shape}, cond_raw: {cond_raw.shape}, batch_size: {batch_size}")
        
        # RESHAPE  (Flatten Assets)
        # x: [32, 64, 14, 1] -> [32, 64, 14]
        x_flat = x_raw.view(batch_size, 64, -1) 
        
        # cond: [32, 64, 14, 6] -> [32, 64, 14*6] -> [32, 64, 84] 
        cond_flat = cond_raw.view(batch_size, 64, -1)

        # print(f"x_flat: {x_flat.shape}, cond_flat: {cond_flat.shape}")
        
        optimizer.zero_grad()
        loss = diffusion(x_flat, cond_flat)
        
        loss.backward()
        optimizer.step()
        
    print(f"Epoch {epoch} Loss: {loss.item()}")
    if (epoch + 1) % 10 == 0:
        torch.save(diffusion.state_dict(), f"checkpoints/v8_ckpt_{epoch+1}.pt")

Epoch 1/2000: 100%|██████████| 34/34 [00:03<00:00,  9.10it/s]

Epoch 0 Loss: 0.9452962875366211

Epoch 2/2000: 100%|██████████| 34/34 [00:00<00:00, 64.28it/s]

Epoch 1 Loss: 0.8296117186546326

Epoch 3/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 2 Loss: 0.6910073161125183

Epoch 4/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 3 Loss: 0.41167548298835754

Epoch 5/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 4 Loss: 0.2789958417415619

Epoch 6/2000: 100%|██████████| 34/34 [00:00<00:00, 64.95it/s]

Epoch 5 Loss: 0.20352588593959808

Epoch 7/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 6 Loss: 0.24077889323234558

Epoch 8/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 7 Loss: 0.08473565429449081

Epoch 9/2000: 100%|██████████| 34/34 [00:00<00:00, 65.01it/s]

Epoch 8 Loss: 0.17160402238368988

Epoch 10/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 9 Loss: 0.18817105889320374

Epoch 11/2000: 100%|██████████| 34/34 [00:00<00:00, 64.33it/s]

Epoch 10 Loss: 0.06872975081205368

Epoch 12/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 11 Loss: 0.07228127866983414

Epoch 13/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 12 Loss: 0.17577287554740906

Epoch 14/2000: 100%|██████████| 34/34 [00:00<00:00, 62.21it/s]

Epoch 13 Loss: 0.13802343606948853

Epoch 15/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 14 Loss: 0.18240846693515778

Epoch 16/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 15 Loss: 0.13465052843093872

Epoch 17/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 16 Loss: 0.13192620873451233

Epoch 18/2000: 100%|██████████| 34/34 [00:00<00:00, 62.24it/s]

Epoch 17 Loss: 0.08264037221670151

Epoch 19/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 18 Loss: 0.1059781089425087

Epoch 20/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 19 Loss: 0.07038630545139313

Epoch 21/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 20 Loss: 0.10286104679107666

Epoch 22/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 21 Loss: 0.07410655170679092

Epoch 23/2000: 100%|██████████| 34/34 [00:00<00:00, 56.81it/s]

Epoch 22 Loss: 0.10242860019207001

Epoch 24/2000: 100%|██████████| 34/34 [00:00<00:00, 56.37it/s]

Epoch 23 Loss: 0.049267277121543884

Epoch 25/2000: 100%|██████████| 34/34 [00:00<00:00, 56.29it/s]

Epoch 24 Loss: 0.05713169649243355

Epoch 26/2000: 100%|██████████| 34/34 [00:00<00:00, 55.97it/s]

Epoch 25 Loss: 0.06603645533323288

Epoch 27/2000: 100%|██████████| 34/34 [00:00<00:00, 56.27it/s]

Epoch 26 Loss: 0.06305675208568573

Epoch 28/2000: 100%|██████████| 34/34 [00:00<00:00, 62.31it/s]

Epoch 27 Loss: 0.11645131558179855

Epoch 29/2000: 100%|██████████| 34/34 [00:00<00:00, 62.99it/s]

Epoch 28 Loss: 0.03961702808737755

Epoch 30/2000: 100%|██████████| 34/34 [00:00<00:00, 63.47it/s]

Epoch 29 Loss: 0.04516095295548439

Epoch 31/2000: 100%|██████████| 34/34 [00:00<00:00, 62.10it/s]

Epoch 30 Loss: 0.06267450749874115

Epoch 32/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 31 Loss: 0.07186714559793472

Epoch 33/2000: 100%|██████████| 34/34 [00:00<00:00, 62.16it/s]

Epoch 32 Loss: 0.0400824211537838

Epoch 34/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 33 Loss: 0.05521288141608238

Epoch 35/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 34 Loss: 0.04860135167837143

Epoch 36/2000: 100%|██████████| 34/34 [00:00<00:00, 62.22it/s]

Epoch 35 Loss: 0.05417230725288391

Epoch 37/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 36 Loss: 0.08352012932300568

Epoch 38/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 37 Loss: 0.06716004759073257

Epoch 39/2000: 100%|██████████| 34/34 [00:00<00:00, 62.05it/s]

Epoch 38 Loss: 0.03838884457945824

Epoch 40/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 39 Loss: 0.04077306389808655

Epoch 41/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 40 Loss: 0.0689348578453064

Epoch 42/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 41 Loss: 0.07192245870828629

Epoch 43/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 42 Loss: 0.0649767816066742

Epoch 44/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 43 Loss: 0.046039242297410965

Epoch 45/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 44 Loss: 0.022216256707906723

Epoch 46/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 45 Loss: 0.04241301864385605

Epoch 47/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 46 Loss: 0.028790097683668137

Epoch 48/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 47 Loss: 0.07053413987159729

Epoch 49/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 48 Loss: 0.05717127025127411

Epoch 50/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 49 Loss: 0.03021189197897911

Epoch 51/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 50 Loss: 0.026474958285689354

Epoch 52/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 51 Loss: 0.024334441870450974

Epoch 53/2000: 100%|██████████| 34/34 [00:00<00:00, 62.08it/s]

Epoch 52 Loss: 0.07679259032011032

Epoch 54/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 53 Loss: 0.03845623880624771

Epoch 55/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 54 Loss: 0.02000749111175537

Epoch 56/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 55 Loss: 0.1067001149058342

Epoch 57/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 56 Loss: 0.06361721456050873

Epoch 58/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 57 Loss: 0.0434202142059803

Epoch 59/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 58 Loss: 0.07128892093896866

Epoch 60/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 59 Loss: 0.03431738168001175

Epoch 61/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 60 Loss: 0.021773425862193108

Epoch 62/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 61 Loss: 0.03470499441027641

Epoch 63/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 62 Loss: 0.03668912500143051

Epoch 64/2000: 100%|██████████| 34/34 [00:00<00:00, 62.51it/s]

Epoch 63 Loss: 0.024441609159111977

Epoch 65/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 64 Loss: 0.022480063140392303

Epoch 66/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 65 Loss: 0.024038322269916534

Epoch 67/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 66 Loss: 0.037687547504901886

Epoch 68/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 67 Loss: 0.018037322908639908

Epoch 69/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 68 Loss: 0.0334179662168026

Epoch 70/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 69 Loss: 0.07752466201782227

Epoch 71/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 70 Loss: 0.03559275344014168

Epoch 72/2000: 100%|██████████| 34/34 [00:00<00:00, 62.62it/s]

Epoch 71 Loss: 0.04985649138689041

Epoch 73/2000: 100%|██████████| 34/34 [00:00<00:00, 62.74it/s]

Epoch 72 Loss: 0.06447650492191315

Epoch 74/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 73 Loss: 0.05385833606123924

Epoch 75/2000: 100%|██████████| 34/34 [00:00<00:00, 62.65it/s]

Epoch 74 Loss: 0.014765995554625988

Epoch 76/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 75 Loss: 0.04699936881661415

Epoch 77/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 76 Loss: 0.04814574122428894

Epoch 78/2000: 100%|██████████| 34/34 [00:00<00:00, 62.69it/s]

Epoch 77 Loss: 0.014906130731105804

Epoch 79/2000: 100%|██████████| 34/34 [00:00<00:00, 62.58it/s]

Epoch 78 Loss: 0.03360162675380707

Epoch 80/2000: 100%|██████████| 34/34 [00:00<00:00, 62.52it/s]

Epoch 79 Loss: 0.03029691055417061

Epoch 81/2000: 100%|██████████| 34/34 [00:00<00:00, 62.63it/s]

Epoch 80 Loss: 0.04099135100841522

Epoch 82/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 81 Loss: 0.03539038449525833

Epoch 83/2000: 100%|██████████| 34/34 [00:00<00:00, 62.61it/s]

Epoch 82 Loss: 0.020887451246380806

Epoch 84/2000: 100%|██████████| 34/34 [00:00<00:00, 62.54it/s]

Epoch 83 Loss: 0.03464208543300629

Epoch 85/2000: 100%|██████████| 34/34 [00:00<00:00, 62.61it/s]

Epoch 84 Loss: 0.015450927428901196

Epoch 86/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 85 Loss: 0.0901336520910263

Epoch 87/2000: 100%|██████████| 34/34 [00:00<00:00, 62.64it/s]

Epoch 86 Loss: 0.08024999499320984

Epoch 88/2000: 100%|██████████| 34/34 [00:00<00:00, 62.58it/s]

Epoch 87 Loss: 0.024068310856819153

Epoch 89/2000: 100%|██████████| 34/34 [00:00<00:00, 62.69it/s]

Epoch 88 Loss: 0.03512014076113701

Epoch 90/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 89 Loss: 0.027594825252890587

Epoch 91/2000: 100%|██████████| 34/34 [00:00<00:00, 62.58it/s]

Epoch 90 Loss: 0.03942224010825157

Epoch 92/2000: 100%|██████████| 34/34 [00:00<00:00, 62.53it/s]

Epoch 91 Loss: 0.02162695862352848

Epoch 93/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 92 Loss: 0.014853616245090961

Epoch 94/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 93 Loss: 0.04282517358660698

Epoch 95/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 94 Loss: 0.03400033339858055

Epoch 96/2000: 100%|██████████| 34/34 [00:00<00:00, 62.61it/s]

Epoch 95 Loss: 0.04277077689766884

Epoch 97/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 96 Loss: 0.01666809618473053

Epoch 98/2000: 100%|██████████| 34/34 [00:00<00:00, 62.69it/s]

Epoch 97 Loss: 0.02113622985780239

Epoch 99/2000: 100%|██████████| 34/34 [00:00<00:00, 62.78it/s]

Epoch 98 Loss: 0.03969406709074974

Epoch 100/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 99 Loss: 0.07227932661771774

Epoch 101/2000: 100%|██████████| 34/34 [00:00<00:00, 62.92it/s]

Epoch 100 Loss: 0.05736112967133522

Epoch 102/2000: 100%|██████████| 34/34 [00:00<00:00, 62.79it/s]

Epoch 101 Loss: 0.03444599732756615

Epoch 103/2000: 100%|██████████| 34/34 [00:00<00:00, 62.99it/s]

Epoch 102 Loss: 0.012974252924323082

Epoch 104/2000: 100%|██████████| 34/34 [00:00<00:00, 63.01it/s]

Epoch 103 Loss: 0.043655432760715485

Epoch 105/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 104 Loss: 0.035180091857910156

Epoch 106/2000: 100%|██████████| 34/34 [00:00<00:00, 62.98it/s]

Epoch 105 Loss: 0.04242013767361641

Epoch 107/2000: 100%|██████████| 34/34 [00:00<00:00, 62.77it/s]

Epoch 106 Loss: 0.023075535893440247

Epoch 108/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 107 Loss: 0.01506446860730648

Epoch 109/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 108 Loss: 0.011198208667337894

Epoch 110/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 109 Loss: 0.05257638543844223

Epoch 111/2000: 100%|██████████| 34/34 [00:00<00:00, 62.23it/s]

Epoch 110 Loss: 0.018742360174655914

Epoch 112/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 111 Loss: 0.030267303809523582

Epoch 113/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 112 Loss: 0.012255912646651268

Epoch 114/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 113 Loss: 0.030464503914117813

Epoch 115/2000: 100%|██████████| 34/34 [00:00<00:00, 62.87it/s]

Epoch 114 Loss: 0.017892738804221153

Epoch 116/2000: 100%|██████████| 34/34 [00:00<00:00, 62.64it/s]

Epoch 115 Loss: 0.054762549698352814

Epoch 117/2000: 100%|██████████| 34/34 [00:00<00:00, 62.76it/s]

Epoch 116 Loss: 0.024735962972044945

Epoch 118/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 117 Loss: 0.026460452005267143

Epoch 119/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 118 Loss: 0.02000539004802704

Epoch 120/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 119 Loss: 0.01050514169037342

Epoch 121/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 120 Loss: 0.04529079422354698

Epoch 122/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 121 Loss: 0.011643324978649616

Epoch 123/2000: 100%|██████████| 34/34 [00:00<00:00, 63.06it/s]

Epoch 122 Loss: 0.08132923394441605

Epoch 124/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 123 Loss: 0.014621342532336712

Epoch 125/2000: 100%|██████████| 34/34 [00:00<00:00, 62.53it/s]

Epoch 124 Loss: 0.045068856328725815

Epoch 126/2000: 100%|██████████| 34/34 [00:00<00:00, 62.52it/s]

Epoch 125 Loss: 0.013067442923784256

Epoch 127/2000: 100%|██████████| 34/34 [00:00<00:00, 62.92it/s]

Epoch 126 Loss: 0.05151411145925522

Epoch 128/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 127 Loss: 0.011451762169599533

Epoch 129/2000: 100%|██████████| 34/34 [00:00<00:00, 62.91it/s]

Epoch 128 Loss: 0.036137279123067856

Epoch 130/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 129 Loss: 0.037154316902160645

Epoch 131/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 130 Loss: 0.010960719548165798

Epoch 132/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 131 Loss: 0.028621425852179527

Epoch 133/2000: 100%|██████████| 34/34 [00:00<00:00, 62.77it/s]

Epoch 132 Loss: 0.017550459131598473

Epoch 134/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 133 Loss: 0.015486126765608788

Epoch 135/2000: 100%|██████████| 34/34 [00:00<00:00, 62.76it/s]

Epoch 134 Loss: 0.04371928423643112

Epoch 136/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 135 Loss: 0.017250632867217064

Epoch 137/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 136 Loss: 0.03355495631694794

Epoch 138/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 137 Loss: 0.02639593929052353

Epoch 139/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 138 Loss: 0.017306052148342133

Epoch 140/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 139 Loss: 0.04357912018895149

Epoch 141/2000: 100%|██████████| 34/34 [00:00<00:00, 62.87it/s]

Epoch 140 Loss: 0.050340138375759125

Epoch 142/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 141 Loss: 0.0486694872379303

Epoch 143/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 142 Loss: 0.013578169979155064

Epoch 144/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 143 Loss: 0.022848287597298622

Epoch 145/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 144 Loss: 0.0520600900053978

Epoch 146/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 145 Loss: 0.015518100000917912

Epoch 147/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 146 Loss: 0.020752083510160446

Epoch 148/2000: 100%|██████████| 34/34 [00:00<00:00, 61.57it/s]

Epoch 147 Loss: 0.02271350473165512

Epoch 149/2000: 100%|██████████| 34/34 [00:00<00:00, 63.41it/s]

Epoch 148 Loss: 0.011031581088900566

Epoch 150/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 149 Loss: 0.02376585826277733

Epoch 151/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 150 Loss: 0.010761355981230736

Epoch 152/2000: 100%|██████████| 34/34 [00:00<00:00, 60.51it/s]

Epoch 151 Loss: 0.018861522898077965

Epoch 153/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 152 Loss: 0.012207437306642532

Epoch 154/2000: 100%|██████████| 34/34 [00:00<00:00, 62.24it/s]

Epoch 153 Loss: 0.01580084301531315

Epoch 155/2000: 100%|██████████| 34/34 [00:00<00:00, 62.10it/s]

Epoch 154 Loss: 0.011054913513362408

Epoch 156/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 155 Loss: 0.04440223053097725

Epoch 157/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 156 Loss: 0.04561460018157959

Epoch 158/2000: 100%|██████████| 34/34 [00:00<00:00, 62.22it/s]

Epoch 157 Loss: 0.012192370370030403

Epoch 159/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 158 Loss: 0.02258864976465702

Epoch 160/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 159 Loss: 0.015049923211336136

Epoch 161/2000: 100%|██████████| 34/34 [00:00<00:00, 60.42it/s]

Epoch 160 Loss: 0.011359804309904575

Epoch 162/2000: 100%|██████████| 34/34 [00:00<00:00, 62.21it/s]

Epoch 161 Loss: 0.021045206114649773

Epoch 163/2000: 100%|██████████| 34/34 [00:00<00:00, 62.03it/s]

Epoch 162 Loss: 0.02010197751224041

Epoch 164/2000: 100%|██████████| 34/34 [00:00<00:00, 63.32it/s]

Epoch 163 Loss: 0.031283337622880936

Epoch 165/2000: 100%|██████████| 34/34 [00:00<00:00, 63.39it/s]

Epoch 164 Loss: 0.008268380537629128

Epoch 166/2000: 100%|██████████| 34/34 [00:00<00:00, 63.45it/s]

Epoch 165 Loss: 0.04418686777353287

Epoch 167/2000: 100%|██████████| 34/34 [00:00<00:00, 63.35it/s]

Epoch 166 Loss: 0.010829968377947807

Epoch 168/2000: 100%|██████████| 34/34 [00:00<00:00, 63.38it/s]

Epoch 167 Loss: 0.01370607316493988

Epoch 169/2000: 100%|██████████| 34/34 [00:00<00:00, 63.30it/s]

Epoch 168 Loss: 0.022430740296840668

Epoch 170/2000: 100%|██████████| 34/34 [00:00<00:00, 63.10it/s]

Epoch 169 Loss: 0.04936883598566055

Epoch 171/2000: 100%|██████████| 34/34 [00:00<00:00, 63.04it/s]

Epoch 170 Loss: 0.010535800829529762

Epoch 172/2000: 100%|██████████| 34/34 [00:00<00:00, 63.45it/s]

Epoch 171 Loss: 0.00999289471656084

Epoch 173/2000: 100%|██████████| 34/34 [00:00<00:00, 63.50it/s]

Epoch 172 Loss: 0.026444969698786736

Epoch 174/2000: 100%|██████████| 34/34 [00:00<00:00, 63.42it/s]

Epoch 173 Loss: 0.013273215852677822

Epoch 175/2000: 100%|██████████| 34/34 [00:00<00:00, 63.43it/s]

Epoch 174 Loss: 0.007848179899156094

Epoch 176/2000: 100%|██████████| 34/34 [00:00<00:00, 63.45it/s]

Epoch 175 Loss: 0.026067115366458893

Epoch 177/2000: 100%|██████████| 34/34 [00:00<00:00, 63.55it/s]

Epoch 176 Loss: 0.023884018883109093

Epoch 178/2000: 100%|██████████| 34/34 [00:00<00:00, 63.52it/s]

Epoch 177 Loss: 0.04745664820075035

Epoch 179/2000: 100%|██████████| 34/34 [00:00<00:00, 63.52it/s]

Epoch 178 Loss: 0.011688114143908024

Epoch 180/2000: 100%|██████████| 34/34 [00:00<00:00, 63.38it/s]

Epoch 179 Loss: 0.012717809528112411

Epoch 181/2000: 100%|██████████| 34/34 [00:00<00:00, 63.49it/s]

Epoch 180 Loss: 0.037533268332481384

Epoch 182/2000: 100%|██████████| 34/34 [00:00<00:00, 63.55it/s]

Epoch 181 Loss: 0.015791835263371468

Epoch 183/2000: 100%|██████████| 34/34 [00:00<00:00, 63.61it/s]

Epoch 182 Loss: 0.01969238556921482

Epoch 184/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 183 Loss: 0.010088472627103329

Epoch 185/2000: 100%|██████████| 34/34 [00:00<00:00, 62.19it/s]

Epoch 184 Loss: 0.045270081609487534

Epoch 186/2000: 100%|██████████| 34/34 [00:00<00:00, 62.27it/s]

Epoch 185 Loss: 0.037023935467004776

Epoch 187/2000: 100%|██████████| 34/34 [00:00<00:00, 62.27it/s]

Epoch 186 Loss: 0.010241972282528877

Epoch 188/2000: 100%|██████████| 34/34 [00:00<00:00, 62.24it/s]

Epoch 187 Loss: 0.015525802969932556

Epoch 189/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 188 Loss: 0.04690995439887047

Epoch 190/2000: 100%|██████████| 34/34 [00:00<00:00, 62.27it/s]

Epoch 189 Loss: 0.014291004277765751

Epoch 191/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 190 Loss: 0.021020198240876198

Epoch 192/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 191 Loss: 0.028176963329315186

Epoch 193/2000: 100%|██████████| 34/34 [00:00<00:00, 62.29it/s]

Epoch 192 Loss: 0.010800493881106377

Epoch 194/2000: 100%|██████████| 34/34 [00:00<00:00, 62.21it/s]

Epoch 193 Loss: 0.030010690912604332

Epoch 195/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 194 Loss: 0.012805680744349957

Epoch 196/2000: 100%|██████████| 34/34 [00:00<00:00, 62.03it/s]

Epoch 195 Loss: 0.008921637199819088

Epoch 197/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 196 Loss: 0.02005326747894287

Epoch 198/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 197 Loss: 0.016890354454517365

Epoch 199/2000: 100%|██████████| 34/34 [00:00<00:00, 62.05it/s]

Epoch 198 Loss: 0.045119404792785645

Epoch 200/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 199 Loss: 0.013304786756634712

Epoch 201/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 200 Loss: 0.009862675331532955

Epoch 202/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 201 Loss: 0.040760982781648636

Epoch 203/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 202 Loss: 0.027946896851062775

Epoch 204/2000: 100%|██████████| 34/34 [00:00<00:00, 62.14it/s]

Epoch 203 Loss: 0.04155293107032776

Epoch 205/2000: 100%|██████████| 34/34 [00:00<00:00, 62.10it/s]

Epoch 204 Loss: 0.007970059290528297

Epoch 206/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 205 Loss: 0.006568758748471737

Epoch 207/2000: 100%|██████████| 34/34 [00:00<00:00, 62.12it/s]

Epoch 206 Loss: 0.034908097237348557

Epoch 208/2000: 100%|██████████| 34/34 [00:00<00:00, 62.05it/s]

Epoch 207 Loss: 0.010419407859444618

Epoch 209/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 208 Loss: 0.042699094861745834

Epoch 210/2000: 100%|██████████| 34/34 [00:00<00:00, 62.23it/s]

Epoch 209 Loss: 0.013023399747908115

Epoch 211/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 210 Loss: 0.014242884702980518

Epoch 212/2000: 100%|██████████| 34/34 [00:00<00:00, 62.11it/s]

Epoch 211 Loss: 0.013320914469659328

Epoch 213/2000: 100%|██████████| 34/34 [00:00<00:00, 62.16it/s]

Epoch 212 Loss: 0.020442267879843712

Epoch 214/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 213 Loss: 0.031888753175735474

Epoch 215/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 214 Loss: 0.014474192634224892

Epoch 216/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 215 Loss: 0.034766461700201035

Epoch 217/2000: 100%|██████████| 34/34 [00:00<00:00, 62.19it/s]

Epoch 216 Loss: 0.0072706700302660465

Epoch 218/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 217 Loss: 0.02674173004925251

Epoch 219/2000: 100%|██████████| 34/34 [00:00<00:00, 62.19it/s]

Epoch 218 Loss: 0.014699164777994156

Epoch 220/2000: 100%|██████████| 34/34 [00:00<00:00, 62.29it/s]

Epoch 219 Loss: 0.011953051201999187

Epoch 221/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 220 Loss: 0.024936093017458916

Epoch 222/2000: 100%|██████████| 34/34 [00:00<00:00, 62.27it/s]

Epoch 221 Loss: 0.03127724304795265

Epoch 223/2000: 100%|██████████| 34/34 [00:00<00:00, 62.27it/s]

Epoch 222 Loss: 0.006466925609856844

Epoch 224/2000: 100%|██████████| 34/34 [00:00<00:00, 62.13it/s]

Epoch 223 Loss: 0.011314126662909985

Epoch 225/2000: 100%|██████████| 34/34 [00:00<00:00, 62.60it/s]

Epoch 224 Loss: 0.008140596561133862

Epoch 226/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 225 Loss: 0.007305649109184742

Epoch 227/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 226 Loss: 0.05715520679950714

Epoch 228/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 227 Loss: 0.02086922526359558

Epoch 229/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 228 Loss: 0.06623455882072449

Epoch 230/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 229 Loss: 0.010470052249729633

Epoch 231/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 230 Loss: 0.01931918039917946

Epoch 232/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 231 Loss: 0.010075550526380539

Epoch 233/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 232 Loss: 0.02873137779533863

Epoch 234/2000: 100%|██████████| 34/34 [00:00<00:00, 63.65it/s]

Epoch 233 Loss: 0.013896917924284935

Epoch 235/2000: 100%|██████████| 34/34 [00:00<00:00, 63.67it/s]

Epoch 234 Loss: 0.0566331185400486

Epoch 236/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 235 Loss: 0.01575995609164238

Epoch 237/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 236 Loss: 0.043527260422706604

Epoch 238/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 237 Loss: 0.012980329804122448

Epoch 239/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 238 Loss: 0.010984153486788273

Epoch 240/2000: 100%|██████████| 34/34 [00:00<00:00, 63.41it/s]

Epoch 239 Loss: 0.041078805923461914

Epoch 241/2000: 100%|██████████| 34/34 [00:00<00:00, 63.95it/s]

Epoch 240 Loss: 0.02097851037979126

Epoch 242/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 241 Loss: 0.05410878360271454

Epoch 243/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 242 Loss: 0.005416800267994404

Epoch 244/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 243 Loss: 0.008384539745748043

Epoch 245/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 244 Loss: 0.015382837504148483

Epoch 246/2000: 100%|██████████| 34/34 [00:00<00:00, 63.15it/s]

Epoch 245 Loss: 0.005362471099942923

Epoch 247/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 246 Loss: 0.010021897032856941

Epoch 248/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 247 Loss: 0.03896837309002876

Epoch 249/2000: 100%|██████████| 34/34 [00:00<00:00, 63.86it/s]

Epoch 248 Loss: 0.048251572996377945

Epoch 250/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 249 Loss: 0.009561259299516678

Epoch 251/2000: 100%|██████████| 34/34 [00:00<00:00, 64.01it/s]

Epoch 250 Loss: 0.005514124874025583

Epoch 252/2000: 100%|██████████| 34/34 [00:00<00:00, 63.86it/s]

Epoch 251 Loss: 0.00959835946559906

Epoch 253/2000: 100%|██████████| 34/34 [00:00<00:00, 63.69it/s]

Epoch 252 Loss: 0.006061884108930826

Epoch 254/2000: 100%|██████████| 34/34 [00:00<00:00, 63.37it/s]

Epoch 253 Loss: 0.053407397121191025

Epoch 255/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 254 Loss: 0.00882810354232788

Epoch 256/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 255 Loss: 0.01392725482583046

Epoch 257/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 256 Loss: 0.0070001063868403435

Epoch 258/2000: 100%|██████████| 34/34 [00:00<00:00, 63.77it/s]

Epoch 257 Loss: 0.03674013540148735

Epoch 259/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 258 Loss: 0.0239010788500309

Epoch 260/2000: 100%|██████████| 34/34 [00:00<00:00, 63.46it/s]

Epoch 259 Loss: 0.01625683903694153

Epoch 261/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 260 Loss: 0.0280231311917305

Epoch 262/2000: 100%|██████████| 34/34 [00:00<00:00, 63.77it/s]

Epoch 261 Loss: 0.015176921151578426

Epoch 263/2000: 100%|██████████| 34/34 [00:00<00:00, 63.67it/s]

Epoch 262 Loss: 0.006190876010805368

Epoch 264/2000: 100%|██████████| 34/34 [00:00<00:00, 63.52it/s]

Epoch 263 Loss: 0.038441285490989685

Epoch 265/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 264 Loss: 0.008395724929869175

Epoch 266/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 265 Loss: 0.007916375063359737

Epoch 267/2000: 100%|██████████| 34/34 [00:00<00:00, 63.89it/s]

Epoch 266 Loss: 0.019327521324157715

Epoch 268/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 267 Loss: 0.009258785285055637

Epoch 269/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 268 Loss: 0.04366772621870041

Epoch 270/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 269 Loss: 0.004849784541875124

Epoch 271/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 270 Loss: 0.010185488499701023

Epoch 272/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 271 Loss: 0.025174492970108986

Epoch 273/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 272 Loss: 0.012626860290765762

Epoch 274/2000: 100%|██████████| 34/34 [00:00<00:00, 63.36it/s]

Epoch 273 Loss: 0.011911233887076378

Epoch 275/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 274 Loss: 0.009216376580297947

Epoch 276/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 275 Loss: 0.017176726832985878

Epoch 277/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 276 Loss: 0.03877103328704834

Epoch 278/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 277 Loss: 0.019094398245215416

Epoch 279/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 278 Loss: 0.02548161707818508

Epoch 280/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 279 Loss: 0.009633896872401237

Epoch 281/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 280 Loss: 0.01400209404528141

Epoch 282/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 281 Loss: 0.022881845012307167

Epoch 283/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 282 Loss: 0.009867615066468716

Epoch 284/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 283 Loss: 0.006529712583869696

Epoch 285/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 284 Loss: 0.02298731729388237

Epoch 286/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 285 Loss: 0.00912549253553152

Epoch 287/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 286 Loss: 0.005893134977668524

Epoch 288/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 287 Loss: 0.010570329613983631

Epoch 289/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 288 Loss: 0.004631297662854195

Epoch 290/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 289 Loss: 0.057903751730918884

Epoch 291/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 290 Loss: 0.041434064507484436

Epoch 292/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 291 Loss: 0.017686279490590096

Epoch 293/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 292 Loss: 0.006270614452660084

Epoch 294/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 293 Loss: 0.02198881097137928

Epoch 295/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 294 Loss: 0.00845181755721569

Epoch 296/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 295 Loss: 0.012462795712053776

Epoch 297/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 296 Loss: 0.03103809617459774

Epoch 298/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 297 Loss: 0.00927808228880167

Epoch 299/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 298 Loss: 0.015269394032657146

Epoch 300/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 299 Loss: 0.01587037369608879

Epoch 301/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 300 Loss: 0.01484689675271511

Epoch 302/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 301 Loss: 0.015198997221887112

Epoch 303/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 302 Loss: 0.0068558501079678535

Epoch 304/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 303 Loss: 0.045160844922065735

Epoch 305/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 304 Loss: 0.058280594646930695

Epoch 306/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 305 Loss: 0.033307891339063644

Epoch 307/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 306 Loss: 0.031606610864400864

Epoch 308/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 307 Loss: 0.013940529897809029

Epoch 309/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 308 Loss: 0.008423619903624058

Epoch 310/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 309 Loss: 0.012949440628290176

Epoch 311/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 310 Loss: 0.015293180011212826

Epoch 312/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 311 Loss: 0.04876217246055603

Epoch 313/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 312 Loss: 0.012266692705452442

Epoch 314/2000: 100%|██████████| 34/34 [00:00<00:00, 64.92it/s]

Epoch 313 Loss: 0.006635704077780247

Epoch 315/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 314 Loss: 0.01884734071791172

Epoch 316/2000: 100%|██████████| 34/34 [00:00<00:00, 64.92it/s]

Epoch 315 Loss: 0.01826881617307663

Epoch 317/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 316 Loss: 0.008798770606517792

Epoch 318/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 317 Loss: 0.013047651387751102

Epoch 319/2000: 100%|██████████| 34/34 [00:00<00:00, 65.14it/s]

Epoch 318 Loss: 0.05997972562909126

Epoch 320/2000: 100%|██████████| 34/34 [00:00<00:00, 65.63it/s]

Epoch 319 Loss: 0.02415263094007969

Epoch 321/2000: 100%|██████████| 34/34 [00:00<00:00, 65.56it/s]

Epoch 320 Loss: 0.005944192875176668

Epoch 322/2000: 100%|██████████| 34/34 [00:00<00:00, 59.24it/s]

Epoch 321 Loss: 0.028829628601670265

Epoch 323/2000: 100%|██████████| 34/34 [00:00<00:00, 56.03it/s]

Epoch 322 Loss: 0.0094238156452775

Epoch 324/2000: 100%|██████████| 34/34 [00:00<00:00, 55.97it/s]

Epoch 323 Loss: 0.014471336267888546

Epoch 325/2000: 100%|██████████| 34/34 [00:00<00:00, 56.22it/s]

Epoch 324 Loss: 0.029856817796826363

Epoch 326/2000: 100%|██████████| 34/34 [00:00<00:00, 59.65it/s]

Epoch 325 Loss: 0.01605955697596073

Epoch 327/2000: 100%|██████████| 34/34 [00:00<00:00, 63.22it/s]

Epoch 326 Loss: 0.006214685272425413

Epoch 328/2000: 100%|██████████| 34/34 [00:00<00:00, 63.38it/s]

Epoch 327 Loss: 0.005048711784183979

Epoch 329/2000: 100%|██████████| 34/34 [00:00<00:00, 63.37it/s]

Epoch 328 Loss: 0.00995322223752737

Epoch 330/2000: 100%|██████████| 34/34 [00:00<00:00, 63.33it/s]

Epoch 329 Loss: 0.015970511361956596

Epoch 331/2000: 100%|██████████| 34/34 [00:00<00:00, 63.34it/s]

Epoch 330 Loss: 0.010950825177133083

Epoch 332/2000: 100%|██████████| 34/34 [00:00<00:00, 63.33it/s]

Epoch 331 Loss: 0.004037952516227961

Epoch 333/2000: 100%|██████████| 34/34 [00:00<00:00, 63.27it/s]

Epoch 332 Loss: 0.01755812205374241

Epoch 334/2000: 100%|██████████| 34/34 [00:00<00:00, 63.32it/s]

Epoch 333 Loss: 0.011720245704054832

Epoch 335/2000: 100%|██████████| 34/34 [00:00<00:00, 63.27it/s]

Epoch 334 Loss: 0.008824661374092102

Epoch 336/2000: 100%|██████████| 34/34 [00:00<00:00, 63.27it/s]

Epoch 335 Loss: 0.06422518938779831

Epoch 337/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 336 Loss: 0.04514468461275101

Epoch 338/2000: 100%|██████████| 34/34 [00:00<00:00, 63.28it/s]

Epoch 337 Loss: 0.006183517165482044

Epoch 339/2000: 100%|██████████| 34/34 [00:00<00:00, 63.40it/s]

Epoch 338 Loss: 0.012175966054201126

Epoch 340/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 339 Loss: 0.009486443363130093

Epoch 341/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 340 Loss: 0.0045947907492518425

Epoch 342/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 341 Loss: 0.011381778866052628

Epoch 343/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 342 Loss: 0.043237004429101944

Epoch 344/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 343 Loss: 0.02532918006181717

Epoch 345/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 344 Loss: 0.02786475606262684

Epoch 346/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 345 Loss: 0.07839993387460709

Epoch 347/2000: 100%|██████████| 34/34 [00:00<00:00, 62.87it/s]

Epoch 346 Loss: 0.020124061033129692

Epoch 348/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 347 Loss: 0.010926402173936367

Epoch 349/2000: 100%|██████████| 34/34 [00:00<00:00, 62.79it/s]

Epoch 348 Loss: 0.01949581317603588

Epoch 350/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 349 Loss: 0.03920689970254898

Epoch 351/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 350 Loss: 0.005666900891810656

Epoch 352/2000: 100%|██████████| 34/34 [00:00<00:00, 62.87it/s]

Epoch 351 Loss: 0.003725523827597499

Epoch 353/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 352 Loss: 0.0078456811606884

Epoch 354/2000: 100%|██████████| 34/34 [00:00<00:00, 62.62it/s]

Epoch 353 Loss: 0.004192648455500603

Epoch 355/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 354 Loss: 0.008408970199525356

Epoch 356/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 355 Loss: 0.025351479649543762

Epoch 357/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 356 Loss: 0.012523175217211246

Epoch 358/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 357 Loss: 0.007636707276105881

Epoch 359/2000: 100%|██████████| 34/34 [00:00<00:00, 63.03it/s]

Epoch 358 Loss: 0.06523777544498444

Epoch 360/2000: 100%|██████████| 34/34 [00:00<00:00, 63.20it/s]

Epoch 359 Loss: 0.004024042282253504

Epoch 361/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 360 Loss: 0.006235506851226091

Epoch 362/2000: 100%|██████████| 34/34 [00:00<00:00, 63.14it/s]

Epoch 361 Loss: 0.0031824095640331507

Epoch 363/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 362 Loss: 0.004640048369765282

Epoch 364/2000: 100%|██████████| 34/34 [00:00<00:00, 62.66it/s]

Epoch 363 Loss: 0.05111894756555557

Epoch 365/2000: 100%|██████████| 34/34 [00:00<00:00, 63.09it/s]

Epoch 364 Loss: 0.03631819412112236

Epoch 366/2000: 100%|██████████| 34/34 [00:00<00:00, 63.18it/s]

Epoch 365 Loss: 0.04950909689068794

Epoch 367/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 366 Loss: 0.006073922850191593

Epoch 368/2000: 100%|██████████| 34/34 [00:00<00:00, 63.13it/s]

Epoch 367 Loss: 0.00449488265439868

Epoch 369/2000: 100%|██████████| 34/34 [00:00<00:00, 60.70it/s]

Epoch 368 Loss: 0.004596434999257326

Epoch 370/2000: 100%|██████████| 34/34 [00:00<00:00, 63.05it/s]

Epoch 369 Loss: 0.024105574935674667

Epoch 371/2000: 100%|██████████| 34/34 [00:00<00:00, 63.03it/s]

Epoch 370 Loss: 0.01688849739730358

Epoch 372/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 371 Loss: 0.03713986277580261

Epoch 373/2000: 100%|██████████| 34/34 [00:00<00:00, 62.98it/s]

Epoch 372 Loss: 0.022277401760220528

Epoch 374/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 373 Loss: 0.05252134054899216

Epoch 375/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 374 Loss: 0.005619332194328308

Epoch 376/2000: 100%|██████████| 34/34 [00:00<00:00, 62.99it/s]

Epoch 375 Loss: 0.009463611990213394

Epoch 377/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 376 Loss: 0.029841601848602295

Epoch 378/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 377 Loss: 0.004875884857028723

Epoch 379/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 378 Loss: 0.0033209200482815504

Epoch 380/2000: 100%|██████████| 34/34 [00:00<00:00, 62.66it/s]

Epoch 379 Loss: 0.0327063649892807

Epoch 381/2000: 100%|██████████| 34/34 [00:00<00:00, 62.11it/s]

Epoch 380 Loss: 0.016319509595632553

Epoch 382/2000: 100%|██████████| 34/34 [00:00<00:00, 62.57it/s]

Epoch 381 Loss: 0.004375581629574299

Epoch 383/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 382 Loss: 0.00729749072343111

Epoch 384/2000: 100%|██████████| 34/34 [00:00<00:00, 62.51it/s]

Epoch 383 Loss: 0.01007892843335867

Epoch 385/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 384 Loss: 0.026957310736179352

Epoch 386/2000: 100%|██████████| 34/34 [00:00<00:00, 62.73it/s]

Epoch 385 Loss: 0.04581401124596596

Epoch 387/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 386 Loss: 0.015190331265330315

Epoch 388/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 387 Loss: 0.011408161371946335

Epoch 389/2000: 100%|██████████| 34/34 [00:00<00:00, 62.75it/s]

Epoch 388 Loss: 0.019487928599119186

Epoch 390/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 389 Loss: 0.008712145499885082

Epoch 391/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 390 Loss: 0.012291749007999897

Epoch 392/2000: 100%|██████████| 34/34 [00:00<00:00, 62.67it/s]

Epoch 391 Loss: 0.01589139550924301

Epoch 393/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 392 Loss: 0.040275778621435165

Epoch 394/2000: 100%|██████████| 34/34 [00:00<00:00, 62.62it/s]

Epoch 393 Loss: 0.007552731782197952

Epoch 395/2000: 100%|██████████| 34/34 [00:00<00:00, 62.72it/s]

Epoch 394 Loss: 0.03983891010284424

Epoch 396/2000: 100%|██████████| 34/34 [00:00<00:00, 62.77it/s]

Epoch 395 Loss: 0.009199006482958794

Epoch 397/2000: 100%|██████████| 34/34 [00:00<00:00, 62.70it/s]

Epoch 396 Loss: 0.003894153283908963

Epoch 398/2000: 100%|██████████| 34/34 [00:00<00:00, 62.73it/s]

Epoch 397 Loss: 0.005524810403585434

Epoch 399/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 398 Loss: 0.022399142384529114

Epoch 400/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 399 Loss: 0.0030204339418560266

Epoch 401/2000: 100%|██████████| 34/34 [00:00<00:00, 62.57it/s]

Epoch 400 Loss: 0.006226420868188143

Epoch 402/2000: 100%|██████████| 34/34 [00:00<00:00, 62.57it/s]

Epoch 401 Loss: 0.016110412776470184

Epoch 403/2000: 100%|██████████| 34/34 [00:00<00:00, 62.73it/s]

Epoch 402 Loss: 0.015930399298667908

Epoch 404/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 403 Loss: 0.0189933180809021

Epoch 405/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 404 Loss: 0.01916542835533619

Epoch 406/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 405 Loss: 0.006445157807320356

Epoch 407/2000: 100%|██████████| 34/34 [00:00<00:00, 62.76it/s]

Epoch 406 Loss: 0.018600670620799065

Epoch 408/2000: 100%|██████████| 34/34 [00:00<00:00, 62.58it/s]

Epoch 407 Loss: 0.0196127500385046

Epoch 409/2000: 100%|██████████| 34/34 [00:00<00:00, 62.65it/s]

Epoch 408 Loss: 0.007685259450227022

Epoch 410/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 409 Loss: 0.00691890437155962

Epoch 411/2000: 100%|██████████| 34/34 [00:00<00:00, 62.70it/s]

Epoch 410 Loss: 0.02121649496257305

Epoch 412/2000: 100%|██████████| 34/34 [00:00<00:00, 62.75it/s]

Epoch 411 Loss: 0.004879469983279705

Epoch 413/2000: 100%|██████████| 34/34 [00:00<00:00, 62.58it/s]

Epoch 412 Loss: 0.034870751202106476

Epoch 414/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 413 Loss: 0.004096004646271467

Epoch 415/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 414 Loss: 0.0035902373492717743

Epoch 416/2000: 100%|██████████| 34/34 [00:00<00:00, 63.21it/s]

Epoch 415 Loss: 0.00941771361976862

Epoch 417/2000: 100%|██████████| 34/34 [00:00<00:00, 63.27it/s]

Epoch 416 Loss: 0.0036160973832011223

Epoch 418/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 417 Loss: 0.004233320709317923

Epoch 419/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 418 Loss: 0.00829843059182167

Epoch 420/2000: 100%|██████████| 34/34 [00:00<00:00, 63.16it/s]

Epoch 419 Loss: 0.008166182786226273

Epoch 421/2000: 100%|██████████| 34/34 [00:00<00:00, 63.15it/s]

Epoch 420 Loss: 0.010807326063513756

Epoch 422/2000: 100%|██████████| 34/34 [00:00<00:00, 63.22it/s]

Epoch 421 Loss: 0.03756760060787201

Epoch 423/2000: 100%|██████████| 34/34 [00:00<00:00, 63.27it/s]

Epoch 422 Loss: 0.02740386873483658

Epoch 424/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 423 Loss: 0.004027401562780142

Epoch 425/2000: 100%|██████████| 34/34 [00:00<00:00, 63.07it/s]

Epoch 424 Loss: 0.023625917732715607

Epoch 426/2000: 100%|██████████| 34/34 [00:00<00:00, 63.21it/s]

Epoch 425 Loss: 0.052170779556035995

Epoch 427/2000: 100%|██████████| 34/34 [00:00<00:00, 63.33it/s]

Epoch 426 Loss: 0.003205052111297846

Epoch 428/2000: 100%|██████████| 34/34 [00:00<00:00, 63.44it/s]

Epoch 427 Loss: 0.057936891913414

Epoch 429/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 428 Loss: 0.007072953507304192

Epoch 430/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 429 Loss: 0.006971284747123718

Epoch 431/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 430 Loss: 0.00431966595351696

Epoch 432/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 431 Loss: 0.004911454860121012

Epoch 433/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 432 Loss: 0.06006855517625809

Epoch 434/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 433 Loss: 0.0045136758126318455

Epoch 435/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 434 Loss: 0.005244989413768053

Epoch 436/2000: 100%|██████████| 34/34 [00:00<00:00, 62.51it/s]

Epoch 435 Loss: 0.005220206920057535

Epoch 437/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 436 Loss: 0.024701561778783798

Epoch 438/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 437 Loss: 0.01026887260377407

Epoch 439/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 438 Loss: 0.0325181744992733

Epoch 440/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 439 Loss: 0.010193291120231152

Epoch 441/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 440 Loss: 0.03378491476178169

Epoch 442/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 441 Loss: 0.008183586411178112

Epoch 443/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 442 Loss: 0.008445716463029385

Epoch 444/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 443 Loss: 0.01331021822988987

Epoch 445/2000: 100%|██████████| 34/34 [00:00<00:00, 64.34it/s]

Epoch 444 Loss: 0.006008792668581009

Epoch 446/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 445 Loss: 0.029524056240916252

Epoch 447/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 446 Loss: 0.004980372730642557

Epoch 448/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 447 Loss: 0.006041625048965216

Epoch 449/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 448 Loss: 0.045985881239175797

Epoch 450/2000: 100%|██████████| 34/34 [00:00<00:00, 64.39it/s]

Epoch 449 Loss: 0.003693912411108613

Epoch 451/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 450 Loss: 0.03076195903122425

Epoch 452/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 451 Loss: 0.004202243871986866

Epoch 453/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 452 Loss: 0.003517845645546913

Epoch 454/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 453 Loss: 0.012718106620013714

Epoch 455/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 454 Loss: 0.0052569108083844185

Epoch 456/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 455 Loss: 0.004426412750035524

Epoch 457/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 456 Loss: 0.008197839371860027

Epoch 458/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 457 Loss: 0.017827361822128296

Epoch 459/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 458 Loss: 0.021958379074931145

Epoch 460/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 459 Loss: 0.004718202166259289

Epoch 461/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 460 Loss: 0.005124869756400585

Epoch 462/2000: 100%|██████████| 34/34 [00:00<00:00, 64.85it/s]

Epoch 461 Loss: 0.005707778036594391

Epoch 463/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 462 Loss: 0.007467722054570913

Epoch 464/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 463 Loss: 0.016538478434085846

Epoch 465/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 464 Loss: 0.012288568541407585

Epoch 466/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 465 Loss: 0.021180711686611176

Epoch 467/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 466 Loss: 0.004764494486153126

Epoch 468/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 467 Loss: 0.01657773181796074

Epoch 469/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 468 Loss: 0.005296352785080671

Epoch 470/2000: 100%|██████████| 34/34 [00:00<00:00, 64.92it/s]

Epoch 469 Loss: 0.012269571423530579

Epoch 471/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 470 Loss: 0.036975763738155365

Epoch 472/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 471 Loss: 0.016008010134100914

Epoch 473/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 472 Loss: 0.04310858994722366

Epoch 474/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 473 Loss: 0.005137505475431681

Epoch 475/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 474 Loss: 0.003507850458845496

Epoch 476/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 475 Loss: 0.011921269819140434

Epoch 477/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 476 Loss: 0.026189226657152176

Epoch 478/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 477 Loss: 0.06517144292593002

Epoch 479/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 478 Loss: 0.03949284180998802

Epoch 480/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 479 Loss: 0.004972293507307768

Epoch 481/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 480 Loss: 0.007837969809770584

Epoch 482/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 481 Loss: 0.0044550118036568165

Epoch 483/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 482 Loss: 0.0065545798279345036

Epoch 484/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 483 Loss: 0.009952095337212086

Epoch 485/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 484 Loss: 0.004632973577827215

Epoch 486/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 485 Loss: 0.007224401459097862

Epoch 487/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 486 Loss: 0.01053432747721672

Epoch 488/2000: 100%|██████████| 34/34 [00:00<00:00, 64.39it/s]

Epoch 487 Loss: 0.004724545869976282

Epoch 489/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 488 Loss: 0.029101794585585594

Epoch 490/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 489 Loss: 0.0423274002969265

Epoch 491/2000: 100%|██████████| 34/34 [00:00<00:00, 64.41it/s]

Epoch 490 Loss: 0.005447572097182274

Epoch 492/2000: 100%|██████████| 34/34 [00:00<00:00, 63.21it/s]

Epoch 491 Loss: 0.012159159407019615

Epoch 493/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 492 Loss: 0.007913446053862572

Epoch 494/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 493 Loss: 0.0037925143260508776

Epoch 495/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 494 Loss: 0.008015638217329979

Epoch 496/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 495 Loss: 0.010512059554457664

Epoch 497/2000: 100%|██████████| 34/34 [00:00<00:00, 65.21it/s]

Epoch 496 Loss: 0.02434677630662918

Epoch 498/2000: 100%|██████████| 34/34 [00:00<00:00, 65.36it/s]

Epoch 497 Loss: 0.004530817735940218

Epoch 499/2000: 100%|██████████| 34/34 [00:00<00:00, 65.30it/s]

Epoch 498 Loss: 0.007634398061782122

Epoch 500/2000: 100%|██████████| 34/34 [00:00<00:00, 65.24it/s]

Epoch 499 Loss: 0.02126261219382286

Epoch 501/2000: 100%|██████████| 34/34 [00:00<00:00, 65.26it/s]

Epoch 500 Loss: 0.021366558969020844

Epoch 502/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 501 Loss: 0.004738175310194492

Epoch 503/2000: 100%|██████████| 34/34 [00:00<00:00, 65.34it/s]

Epoch 502 Loss: 0.023408707231283188

Epoch 504/2000: 100%|██████████| 34/34 [00:00<00:00, 65.35it/s]

Epoch 503 Loss: 0.004432906396687031

Epoch 505/2000: 100%|██████████| 34/34 [00:00<00:00, 65.20it/s]

Epoch 504 Loss: 0.014822539873421192

Epoch 506/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 505 Loss: 0.004048965405672789

Epoch 507/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 506 Loss: 0.03954831138253212

Epoch 508/2000: 100%|██████████| 34/34 [00:00<00:00, 65.44it/s]

Epoch 507 Loss: 0.012682243250310421

Epoch 509/2000: 100%|██████████| 34/34 [00:00<00:00, 65.49it/s]

Epoch 508 Loss: 0.0057249972596764565

Epoch 510/2000: 100%|██████████| 34/34 [00:00<00:00, 65.54it/s]

Epoch 509 Loss: 0.005094276275485754

Epoch 511/2000: 100%|██████████| 34/34 [00:00<00:00, 64.99it/s]

Epoch 510 Loss: 0.015452025458216667

Epoch 512/2000: 100%|██████████| 34/34 [00:00<00:00, 65.41it/s]

Epoch 511 Loss: 0.03428465127944946

Epoch 513/2000: 100%|██████████| 34/34 [00:00<00:00, 65.43it/s]

Epoch 512 Loss: 0.010066800750792027

Epoch 514/2000: 100%|██████████| 34/34 [00:00<00:00, 65.44it/s]

Epoch 513 Loss: 0.024533294141292572

Epoch 515/2000: 100%|██████████| 34/34 [00:00<00:00, 65.19it/s]

Epoch 514 Loss: 0.04139036312699318

Epoch 516/2000: 100%|██████████| 34/34 [00:00<00:00, 65.34it/s]

Epoch 515 Loss: 0.014139199629426003

Epoch 517/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 516 Loss: 0.044618528336286545

Epoch 518/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 517 Loss: 0.04547129571437836

Epoch 519/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 518 Loss: 0.004502453841269016

Epoch 520/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 519 Loss: 0.004375440999865532

Epoch 521/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 520 Loss: 0.05786081403493881

Epoch 522/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 521 Loss: 0.022987691685557365

Epoch 523/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 522 Loss: 0.002933929907158017

Epoch 524/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 523 Loss: 0.03411666303873062

Epoch 525/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 524 Loss: 0.006810859777033329

Epoch 526/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 525 Loss: 0.026949726045131683

Epoch 527/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 526 Loss: 0.004394135437905788

Epoch 528/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 527 Loss: 0.005085159558802843

Epoch 529/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 528 Loss: 0.005926027894020081

Epoch 530/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 529 Loss: 0.0040763565339148045

Epoch 531/2000: 100%|██████████| 34/34 [00:00<00:00, 65.26it/s]

Epoch 530 Loss: 0.01063468772917986

Epoch 532/2000: 100%|██████████| 34/34 [00:00<00:00, 65.46it/s]

Epoch 531 Loss: 0.011200983077287674

Epoch 533/2000: 100%|██████████| 34/34 [00:00<00:00, 65.54it/s]

Epoch 532 Loss: 0.006932456977665424

Epoch 534/2000: 100%|██████████| 34/34 [00:00<00:00, 65.50it/s]

Epoch 533 Loss: 0.0030914826784282923

Epoch 535/2000: 100%|██████████| 34/34 [00:00<00:00, 65.50it/s]

Epoch 534 Loss: 0.0035652494989335537

Epoch 536/2000: 100%|██████████| 34/34 [00:00<00:00, 65.58it/s]

Epoch 535 Loss: 0.006734120659530163

Epoch 537/2000: 100%|██████████| 34/34 [00:00<00:00, 65.53it/s]

Epoch 536 Loss: 0.017220513895154

Epoch 538/2000: 100%|██████████| 34/34 [00:00<00:00, 65.35it/s]

Epoch 537 Loss: 0.01214509829878807

Epoch 539/2000: 100%|██████████| 34/34 [00:00<00:00, 65.47it/s]

Epoch 538 Loss: 0.0039135790430009365

Epoch 540/2000: 100%|██████████| 34/34 [00:00<00:00, 65.21it/s]

Epoch 539 Loss: 0.05297530069947243

Epoch 541/2000: 100%|██████████| 34/34 [00:00<00:00, 65.52it/s]

Epoch 540 Loss: 0.002932468196377158

Epoch 542/2000: 100%|██████████| 34/34 [00:00<00:00, 65.36it/s]

Epoch 541 Loss: 0.0023212628439068794

Epoch 543/2000: 100%|██████████| 34/34 [00:00<00:00, 65.49it/s]

Epoch 542 Loss: 0.016396665945649147

Epoch 544/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 543 Loss: 0.011593053117394447

Epoch 545/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 544 Loss: 0.0038947684224694967

Epoch 546/2000: 100%|██████████| 34/34 [00:00<00:00, 64.85it/s]

Epoch 545 Loss: 0.004190736450254917

Epoch 547/2000: 100%|██████████| 34/34 [00:00<00:00, 64.81it/s]

Epoch 546 Loss: 0.021913789212703705

Epoch 548/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 547 Loss: 0.004736301023513079

Epoch 549/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 548 Loss: 0.04209107160568237

Epoch 550/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 549 Loss: 0.02398977056145668

Epoch 551/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 550 Loss: 0.025430157780647278

Epoch 552/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 551 Loss: 0.012115396559238434

Epoch 553/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 552 Loss: 0.004951986484229565

Epoch 554/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 553 Loss: 0.0026687518693506718

Epoch 555/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 554 Loss: 0.014864888973534107

Epoch 556/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 555 Loss: 0.007154879625886679

Epoch 557/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 556 Loss: 0.0032567044254392385

Epoch 558/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 557 Loss: 0.004169326275587082

Epoch 559/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 558 Loss: 0.011179561726748943

Epoch 560/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 559 Loss: 0.04021593928337097

Epoch 561/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 560 Loss: 0.025912251323461533

Epoch 562/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 561 Loss: 0.004743165336549282

Epoch 563/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 562 Loss: 0.002371653914451599

Epoch 564/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 563 Loss: 0.007019572891294956

Epoch 565/2000: 100%|██████████| 34/34 [00:00<00:00, 63.33it/s]

Epoch 564 Loss: 0.01379240583628416

Epoch 566/2000: 100%|██████████| 34/34 [00:00<00:00, 62.97it/s]

Epoch 565 Loss: 0.0055459532886743546

Epoch 567/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 566 Loss: 0.010539432056248188

Epoch 568/2000: 100%|██████████| 34/34 [00:00<00:00, 62.99it/s]

Epoch 567 Loss: 0.031128382310271263

Epoch 569/2000: 100%|██████████| 34/34 [00:00<00:00, 63.06it/s]

Epoch 568 Loss: 0.01244247704744339

Epoch 570/2000: 100%|██████████| 34/34 [00:00<00:00, 63.01it/s]

Epoch 569 Loss: 0.030952850356698036

Epoch 571/2000: 100%|██████████| 34/34 [00:00<00:00, 62.92it/s]

Epoch 570 Loss: 0.0032931321766227484

Epoch 572/2000: 100%|██████████| 34/34 [00:00<00:00, 63.01it/s]

Epoch 571 Loss: 0.0059457882307469845

Epoch 573/2000: 100%|██████████| 34/34 [00:00<00:00, 62.97it/s]

Epoch 572 Loss: 0.04145200550556183

Epoch 574/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 573 Loss: 0.004425863269716501

Epoch 575/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 574 Loss: 0.0047235856764018536

Epoch 576/2000: 100%|██████████| 34/34 [00:00<00:00, 65.49it/s]

Epoch 575 Loss: 0.008008924312889576

Epoch 577/2000: 100%|██████████| 34/34 [00:00<00:00, 65.20it/s]

Epoch 576 Loss: 0.004643751308321953

Epoch 578/2000: 100%|██████████| 34/34 [00:00<00:00, 65.48it/s]

Epoch 577 Loss: 0.004798874258995056

Epoch 579/2000: 100%|██████████| 34/34 [00:00<00:00, 65.35it/s]

Epoch 578 Loss: 0.022399185225367546

Epoch 580/2000: 100%|██████████| 34/34 [00:00<00:00, 65.42it/s]

Epoch 579 Loss: 0.009365200065076351

Epoch 581/2000: 100%|██████████| 34/34 [00:00<00:00, 65.40it/s]

Epoch 580 Loss: 0.03436734899878502

Epoch 582/2000: 100%|██████████| 34/34 [00:00<00:00, 65.40it/s]

Epoch 581 Loss: 0.0035364089999347925

Epoch 583/2000: 100%|██████████| 34/34 [00:00<00:00, 65.46it/s]

Epoch 582 Loss: 0.03627418354153633

Epoch 584/2000: 100%|██████████| 34/34 [00:00<00:00, 65.48it/s]

Epoch 583 Loss: 0.009495561942458153

Epoch 585/2000: 100%|██████████| 34/34 [00:00<00:00, 65.41it/s]

Epoch 584 Loss: 0.009157059714198112

Epoch 586/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 585 Loss: 0.006786302663385868

Epoch 587/2000: 100%|██████████| 34/34 [00:00<00:00, 65.36it/s]

Epoch 586 Loss: 0.024504149332642555

Epoch 588/2000: 100%|██████████| 34/34 [00:00<00:00, 65.56it/s]

Epoch 587 Loss: 0.018500594422221184

Epoch 589/2000: 100%|██████████| 34/34 [00:00<00:00, 65.49it/s]

Epoch 588 Loss: 0.009966285899281502

Epoch 590/2000: 100%|██████████| 34/34 [00:00<00:00, 65.43it/s]

Epoch 589 Loss: 0.016039742156863213

Epoch 591/2000: 100%|██████████| 34/34 [00:00<00:00, 65.52it/s]

Epoch 590 Loss: 0.0354398712515831

Epoch 592/2000: 100%|██████████| 34/34 [00:00<00:00, 65.57it/s]

Epoch 591 Loss: 0.002008724259212613

Epoch 593/2000: 100%|██████████| 34/34 [00:00<00:00, 65.53it/s]

Epoch 592 Loss: 0.03734543174505234

Epoch 594/2000: 100%|██████████| 34/34 [00:00<00:00, 65.43it/s]

Epoch 593 Loss: 0.001952802762389183

Epoch 595/2000: 100%|██████████| 34/34 [00:00<00:00, 65.48it/s]

Epoch 594 Loss: 0.003336576744914055

Epoch 596/2000: 100%|██████████| 34/34 [00:00<00:00, 65.40it/s]

Epoch 595 Loss: 0.005166899878531694

Epoch 597/2000: 100%|██████████| 34/34 [00:00<00:00, 65.46it/s]

Epoch 596 Loss: 0.007077832706272602

Epoch 598/2000: 100%|██████████| 34/34 [00:00<00:00, 65.53it/s]

Epoch 597 Loss: 0.0029320877511054277

Epoch 599/2000: 100%|██████████| 34/34 [00:00<00:00, 65.41it/s]

Epoch 598 Loss: 0.003338125068694353

Epoch 600/2000: 100%|██████████| 34/34 [00:00<00:00, 65.49it/s]

Epoch 599 Loss: 0.046816594898700714

Epoch 601/2000: 100%|██████████| 34/34 [00:00<00:00, 65.59it/s]

Epoch 600 Loss: 0.011301063932478428

Epoch 602/2000: 100%|██████████| 34/34 [00:00<00:00, 65.52it/s]

Epoch 601 Loss: 0.002463509561493993

Epoch 603/2000: 100%|██████████| 34/34 [00:00<00:00, 65.54it/s]

Epoch 602 Loss: 0.010570541955530643

Epoch 604/2000: 100%|██████████| 34/34 [00:00<00:00, 65.48it/s]

Epoch 603 Loss: 0.0023644098546355963

Epoch 605/2000: 100%|██████████| 34/34 [00:00<00:00, 65.47it/s]

Epoch 604 Loss: 0.0021212745923548937

Epoch 606/2000: 100%|██████████| 34/34 [00:00<00:00, 65.36it/s]

Epoch 605 Loss: 0.0027267553377896547

Epoch 607/2000: 100%|██████████| 34/34 [00:00<00:00, 65.62it/s]

Epoch 606 Loss: 0.00501790177077055

Epoch 608/2000: 100%|██████████| 34/34 [00:00<00:00, 65.60it/s]

Epoch 607 Loss: 0.02684840001165867

Epoch 609/2000: 100%|██████████| 34/34 [00:00<00:00, 65.55it/s]

Epoch 608 Loss: 0.005674928892403841

Epoch 610/2000: 100%|██████████| 34/34 [00:00<00:00, 65.55it/s]

Epoch 609 Loss: 0.022280476987361908

Epoch 611/2000: 100%|██████████| 34/34 [00:00<00:00, 65.51it/s]

Epoch 610 Loss: 0.006883462890982628

Epoch 612/2000: 100%|██████████| 34/34 [00:00<00:00, 65.34it/s]

Epoch 611 Loss: 0.015976963564753532

Epoch 613/2000: 100%|██████████| 34/34 [00:00<00:00, 65.46it/s]

Epoch 612 Loss: 0.030658697709441185

Epoch 614/2000: 100%|██████████| 34/34 [00:00<00:00, 65.43it/s]

Epoch 613 Loss: 0.007920785807073116

Epoch 615/2000: 100%|██████████| 34/34 [00:00<00:00, 65.11it/s]

Epoch 614 Loss: 0.012697621248662472

Epoch 616/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 615 Loss: 0.007230136077851057

Epoch 617/2000: 100%|██████████| 34/34 [00:00<00:00, 65.33it/s]

Epoch 616 Loss: 0.007198497653007507

Epoch 618/2000: 100%|██████████| 34/34 [00:00<00:00, 65.32it/s]

Epoch 617 Loss: 0.023355336859822273

Epoch 619/2000: 100%|██████████| 34/34 [00:00<00:00, 65.32it/s]

Epoch 618 Loss: 0.0042812032625079155

Epoch 620/2000: 100%|██████████| 34/34 [00:00<00:00, 65.16it/s]

Epoch 619 Loss: 0.005544605199247599

Epoch 621/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 620 Loss: 0.03026842139661312

Epoch 622/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 621 Loss: 0.007652138359844685

Epoch 623/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 622 Loss: 0.029185879975557327

Epoch 624/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 623 Loss: 0.03281551972031593

Epoch 625/2000: 100%|██████████| 34/34 [00:00<00:00, 64.86it/s]

Epoch 624 Loss: 0.008459893986582756

Epoch 626/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 625 Loss: 0.004832095932215452

Epoch 627/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 626 Loss: 0.003781365230679512

Epoch 628/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 627 Loss: 0.03788527101278305

Epoch 629/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 628 Loss: 0.04516662284731865

Epoch 630/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 629 Loss: 0.018427936360239983

Epoch 631/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 630 Loss: 0.023992232978343964

Epoch 632/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 631 Loss: 0.006623626220971346

Epoch 633/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 632 Loss: 0.016123652458190918

Epoch 634/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 633 Loss: 0.04585517942905426

Epoch 635/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 634 Loss: 0.013392663560807705

Epoch 636/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 635 Loss: 0.01636524125933647

Epoch 637/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 636 Loss: 0.00769989425316453

Epoch 638/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 637 Loss: 0.00445515988394618

Epoch 639/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 638 Loss: 0.015154379419982433

Epoch 640/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 639 Loss: 0.0029261831659823656

Epoch 641/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 640 Loss: 0.016925672069191933

Epoch 642/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 641 Loss: 0.002461828291416168

Epoch 643/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 642 Loss: 0.04685734212398529

Epoch 644/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 643 Loss: 0.006602512206882238

Epoch 645/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 644 Loss: 0.04636920243501663

Epoch 646/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 645 Loss: 0.0024811485782265663

Epoch 647/2000: 100%|██████████| 34/34 [00:00<00:00, 64.30it/s]

Epoch 646 Loss: 0.0031862184405326843

Epoch 648/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 647 Loss: 0.0043110051192343235

Epoch 649/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 648 Loss: 0.002449651947245002

Epoch 650/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 649 Loss: 0.03208310157060623

Epoch 651/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 650 Loss: 0.027123624458909035

Epoch 652/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 651 Loss: 0.007885213010013103

Epoch 653/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 652 Loss: 0.006542664021253586

Epoch 654/2000: 100%|██████████| 34/34 [00:00<00:00, 64.34it/s]

Epoch 653 Loss: 0.007043950725346804

Epoch 655/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 654 Loss: 0.024933455511927605

Epoch 656/2000: 100%|██████████| 34/34 [00:00<00:00, 64.33it/s]

Epoch 655 Loss: 0.009701771661639214

Epoch 657/2000: 100%|██████████| 34/34 [00:00<00:00, 64.33it/s]

Epoch 656 Loss: 0.014624601230025291

Epoch 658/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 657 Loss: 0.012621601112186909

Epoch 659/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 658 Loss: 0.01864364929497242

Epoch 660/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 659 Loss: 0.006548716686666012

Epoch 661/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 660 Loss: 0.008515754714608192

Epoch 662/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 661 Loss: 0.016662994399666786

Epoch 663/2000: 100%|██████████| 34/34 [00:00<00:00, 62.57it/s]

Epoch 662 Loss: 0.0333440825343132

Epoch 664/2000: 100%|██████████| 34/34 [00:00<00:00, 62.46it/s]

Epoch 663 Loss: 0.003695111256092787

Epoch 665/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 664 Loss: 0.035901106894016266

Epoch 666/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 665 Loss: 0.0034785366151481867

Epoch 667/2000: 100%|██████████| 34/34 [00:00<00:00, 62.54it/s]

Epoch 666 Loss: 0.03421758860349655

Epoch 668/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 667 Loss: 0.023094531148672104

Epoch 669/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 668 Loss: 0.035093531012535095

Epoch 670/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 669 Loss: 0.016034575179219246

Epoch 671/2000: 100%|██████████| 34/34 [00:00<00:00, 62.52it/s]

Epoch 670 Loss: 0.011893919669091702

Epoch 672/2000: 100%|██████████| 34/34 [00:00<00:00, 62.44it/s]

Epoch 671 Loss: 0.006386981811374426

Epoch 673/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 672 Loss: 0.003224326530471444

Epoch 674/2000: 100%|██████████| 34/34 [00:00<00:00, 62.44it/s]

Epoch 673 Loss: 0.007639368064701557

Epoch 675/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 674 Loss: 0.018156040459871292

Epoch 676/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 675 Loss: 0.006060766987502575

Epoch 677/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 676 Loss: 0.007245477754622698

Epoch 678/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 677 Loss: 0.0033364722039550543

Epoch 679/2000: 100%|██████████| 34/34 [00:00<00:00, 61.99it/s]

Epoch 678 Loss: 0.0064973775297403336

Epoch 680/2000: 100%|██████████| 34/34 [00:00<00:00, 62.02it/s]

Epoch 679 Loss: 0.047297339886426926

Epoch 681/2000: 100%|██████████| 34/34 [00:00<00:00, 62.09it/s]

Epoch 680 Loss: 0.02322668395936489

Epoch 682/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 681 Loss: 0.009628752246499062

Epoch 683/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 682 Loss: 0.003329984378069639

Epoch 684/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 683 Loss: 0.022691864520311356

Epoch 685/2000: 100%|██████████| 34/34 [00:00<00:00, 62.31it/s]

Epoch 684 Loss: 0.0025217104703187943

Epoch 686/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 685 Loss: 0.03332611173391342

Epoch 687/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 686 Loss: 0.0021492168307304382

Epoch 688/2000: 100%|██████████| 34/34 [00:00<00:00, 62.22it/s]

Epoch 687 Loss: 0.0068557001650333405

Epoch 689/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 688 Loss: 0.022369591519236565

Epoch 690/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 689 Loss: 0.028084781020879745

Epoch 691/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 690 Loss: 0.015486722812056541

Epoch 692/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 691 Loss: 0.006758140865713358

Epoch 693/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 692 Loss: 0.0024481851141899824

Epoch 694/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 693 Loss: 0.016964422538876534

Epoch 695/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 694 Loss: 0.0023373907897621393

Epoch 696/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 695 Loss: 0.014156932942569256

Epoch 697/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 696 Loss: 0.005949373822659254

Epoch 698/2000: 100%|██████████| 34/34 [00:00<00:00, 62.67it/s]

Epoch 697 Loss: 0.009771834127604961

Epoch 699/2000: 100%|██████████| 34/34 [00:00<00:00, 62.96it/s]

Epoch 698 Loss: 0.012427159585058689

Epoch 700/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 699 Loss: 0.002516338834539056

Epoch 701/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 700 Loss: 0.003329769242554903

Epoch 702/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 701 Loss: 0.019794821739196777

Epoch 703/2000: 100%|██████████| 34/34 [00:00<00:00, 62.96it/s]

Epoch 702 Loss: 0.020813442766666412

Epoch 704/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 703 Loss: 0.0062486096285283566

Epoch 705/2000: 100%|██████████| 34/34 [00:00<00:00, 61.20it/s]

Epoch 704 Loss: 0.008183920755982399

Epoch 706/2000: 100%|██████████| 34/34 [00:00<00:00, 61.63it/s]

Epoch 705 Loss: 0.010640548542141914

Epoch 707/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 706 Loss: 0.011613207869231701

Epoch 708/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 707 Loss: 0.005832045339047909

Epoch 709/2000: 100%|██████████| 34/34 [00:00<00:00, 62.92it/s]

Epoch 708 Loss: 0.0435677170753479

Epoch 710/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 709 Loss: 0.0037920870818197727

Epoch 711/2000: 100%|██████████| 34/34 [00:00<00:00, 62.77it/s]

Epoch 710 Loss: 0.015001409687101841

Epoch 712/2000: 100%|██████████| 34/34 [00:00<00:00, 62.91it/s]

Epoch 711 Loss: 0.006007665768265724

Epoch 713/2000: 100%|██████████| 34/34 [00:00<00:00, 62.97it/s]

Epoch 712 Loss: 0.03050490841269493

Epoch 714/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 713 Loss: 0.006482787895947695

Epoch 715/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 714 Loss: 0.0037136010359972715

Epoch 716/2000: 100%|██████████| 34/34 [00:00<00:00, 62.10it/s]

Epoch 715 Loss: 0.0041312226094305515

Epoch 717/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 716 Loss: 0.02650892175734043

Epoch 718/2000: 100%|██████████| 34/34 [00:00<00:00, 62.91it/s]

Epoch 717 Loss: 0.056705355644226074

Epoch 719/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 718 Loss: 0.007093867287039757

Epoch 720/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 719 Loss: 0.005431148689240217

Epoch 721/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 720 Loss: 0.005194161087274551

Epoch 722/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 721 Loss: 0.041674379259347916

Epoch 723/2000: 100%|██████████| 34/34 [00:00<00:00, 62.93it/s]

Epoch 722 Loss: 0.007587493397295475

Epoch 724/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 723 Loss: 0.0023133629001677036

Epoch 725/2000: 100%|██████████| 34/34 [00:00<00:00, 62.91it/s]

Epoch 724 Loss: 0.0048848954029381275

Epoch 726/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 725 Loss: 0.012551484629511833

Epoch 727/2000: 100%|██████████| 34/34 [00:00<00:00, 62.98it/s]

Epoch 726 Loss: 0.06751906871795654

Epoch 728/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 727 Loss: 0.012129154987633228

Epoch 729/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 728 Loss: 0.004330620169639587

Epoch 730/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 729 Loss: 0.005220050923526287

Epoch 731/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 730 Loss: 0.008699140511453152

Epoch 732/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 731 Loss: 0.008014971390366554

Epoch 733/2000: 100%|██████████| 34/34 [00:00<00:00, 61.73it/s]

Epoch 732 Loss: 0.002354040741920471

Epoch 734/2000: 100%|██████████| 34/34 [00:00<00:00, 61.97it/s]

Epoch 733 Loss: 0.0036019531544297934

Epoch 735/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 734 Loss: 0.010589663870632648

Epoch 736/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 735 Loss: 0.002535733859986067

Epoch 737/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 736 Loss: 0.007833835668861866

Epoch 738/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 737 Loss: 0.012696498073637486

Epoch 739/2000: 100%|██████████| 34/34 [00:00<00:00, 62.31it/s]

Epoch 738 Loss: 0.0136184087023139

Epoch 740/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 739 Loss: 0.0055909184738993645

Epoch 741/2000: 100%|██████████| 34/34 [00:00<00:00, 62.13it/s]

Epoch 740 Loss: 0.014553737826645374

Epoch 742/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 741 Loss: 0.00778578594326973

Epoch 743/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 742 Loss: 0.00283093866892159

Epoch 744/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 743 Loss: 0.01856190897524357

Epoch 745/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 744 Loss: 0.0017976228846237063

Epoch 746/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 745 Loss: 0.023201994597911835

Epoch 747/2000: 100%|██████████| 34/34 [00:00<00:00, 61.98it/s]

Epoch 746 Loss: 0.004036202095448971

Epoch 748/2000: 100%|██████████| 34/34 [00:00<00:00, 62.23it/s]

Epoch 747 Loss: 0.04321109876036644

Epoch 749/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 748 Loss: 0.024141399189829826

Epoch 750/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 749 Loss: 0.0018097636057063937

Epoch 751/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 750 Loss: 0.006209853105247021

Epoch 752/2000: 100%|██████████| 34/34 [00:00<00:00, 61.59it/s]

Epoch 751 Loss: 0.0032373128924518824

Epoch 753/2000: 100%|██████████| 34/34 [00:00<00:00, 62.53it/s]

Epoch 752 Loss: 0.0036577244754880667

Epoch 754/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 753 Loss: 0.015447617508471012

Epoch 755/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 754 Loss: 0.0029055713675916195

Epoch 756/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 755 Loss: 0.010091876611113548

Epoch 757/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 756 Loss: 0.004342271946370602

Epoch 758/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 757 Loss: 0.004386318847537041

Epoch 759/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 758 Loss: 0.0053230407647788525

Epoch 760/2000: 100%|██████████| 34/34 [00:00<00:00, 62.52it/s]

Epoch 759 Loss: 0.003909196704626083

Epoch 761/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 760 Loss: 0.004173056222498417

Epoch 762/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 761 Loss: 0.02044781856238842

Epoch 763/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 762 Loss: 0.010546254925429821

Epoch 764/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 763 Loss: 0.00519646005704999

Epoch 765/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 764 Loss: 0.00776805030182004

Epoch 766/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 765 Loss: 0.00592045160010457

Epoch 767/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 766 Loss: 0.001422350062057376

Epoch 768/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 767 Loss: 0.00674727838486433

Epoch 769/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 768 Loss: 0.007201846688985825

Epoch 770/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 769 Loss: 0.03392066806554794

Epoch 771/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 770 Loss: 0.024709166958928108

Epoch 772/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 771 Loss: 0.00354021810926497

Epoch 773/2000: 100%|██████████| 34/34 [00:00<00:00, 62.57it/s]

Epoch 772 Loss: 0.017653271555900574

Epoch 774/2000: 100%|██████████| 34/34 [00:00<00:00, 62.46it/s]

Epoch 773 Loss: 0.002449337625876069

Epoch 775/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 774 Loss: 0.004442273639142513

Epoch 776/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 775 Loss: 0.00363111961632967

Epoch 777/2000: 100%|██████████| 34/34 [00:00<00:00, 62.54it/s]

Epoch 776 Loss: 0.003021086333319545

Epoch 778/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 777 Loss: 0.007698357570916414

Epoch 779/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 778 Loss: 0.0073948875069618225

Epoch 780/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 779 Loss: 0.0038081796374171972

Epoch 781/2000: 100%|██████████| 34/34 [00:00<00:00, 62.56it/s]

Epoch 780 Loss: 0.042076997458934784

Epoch 782/2000: 100%|██████████| 34/34 [00:00<00:00, 62.29it/s]

Epoch 781 Loss: 0.0025262164417654276

Epoch 783/2000: 100%|██████████| 34/34 [00:00<00:00, 62.21it/s]

Epoch 782 Loss: 0.006580698303878307

Epoch 784/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 783 Loss: 0.0014913766644895077

Epoch 785/2000: 100%|██████████| 34/34 [00:00<00:00, 62.05it/s]

Epoch 784 Loss: 0.002381911501288414

Epoch 786/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 785 Loss: 0.016372650861740112

Epoch 787/2000: 100%|██████████| 34/34 [00:00<00:00, 61.98it/s]

Epoch 786 Loss: 0.0076767695136368275

Epoch 788/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 787 Loss: 0.005124135874211788

Epoch 789/2000: 100%|██████████| 34/34 [00:00<00:00, 62.29it/s]

Epoch 788 Loss: 0.030472896993160248

Epoch 790/2000: 100%|██████████| 34/34 [00:00<00:00, 62.48it/s]

Epoch 789 Loss: 0.01726451702415943

Epoch 791/2000: 100%|██████████| 34/34 [00:00<00:00, 62.53it/s]

Epoch 790 Loss: 0.005777121987193823

Epoch 792/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 791 Loss: 0.009484140202403069

Epoch 793/2000: 100%|██████████| 34/34 [00:00<00:00, 65.03it/s]

Epoch 792 Loss: 0.004681101534515619

Epoch 794/2000: 100%|██████████| 34/34 [00:00<00:00, 64.96it/s]

Epoch 793 Loss: 0.003133574267849326

Epoch 795/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 794 Loss: 0.003088119439780712

Epoch 796/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 795 Loss: 0.014344710856676102

Epoch 797/2000: 100%|██████████| 34/34 [00:00<00:00, 62.77it/s]

Epoch 796 Loss: 0.0022517675533890724

Epoch 798/2000: 100%|██████████| 34/34 [00:00<00:00, 62.53it/s]

Epoch 797 Loss: 0.0026518211234360933

Epoch 799/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 798 Loss: 0.005392115563154221

Epoch 800/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 799 Loss: 0.010712954215705395

Epoch 801/2000: 100%|██████████| 34/34 [00:00<00:00, 62.75it/s]

Epoch 800 Loss: 0.002081165323033929

Epoch 802/2000: 100%|██████████| 34/34 [00:00<00:00, 62.62it/s]

Epoch 801 Loss: 0.0021296695340424776

Epoch 803/2000: 100%|██████████| 34/34 [00:00<00:00, 62.82it/s]

Epoch 802 Loss: 0.0027729584835469723

Epoch 804/2000: 100%|██████████| 34/34 [00:00<00:00, 62.79it/s]

Epoch 803 Loss: 0.004539574962109327

Epoch 805/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 804 Loss: 0.008336874656379223

Epoch 806/2000: 100%|██████████| 34/34 [00:00<00:00, 62.74it/s]

Epoch 805 Loss: 0.012096350081264973

Epoch 807/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 806 Loss: 0.011241395957767963

Epoch 808/2000: 100%|██████████| 34/34 [00:00<00:00, 62.66it/s]

Epoch 807 Loss: 0.00448038661852479

Epoch 809/2000: 100%|██████████| 34/34 [00:00<00:00, 62.68it/s]

Epoch 808 Loss: 0.006800665985792875

Epoch 810/2000: 100%|██████████| 34/34 [00:00<00:00, 62.80it/s]

Epoch 809 Loss: 0.020260736346244812

Epoch 811/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 810 Loss: 0.017720729112625122

Epoch 812/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 811 Loss: 0.0022638430818915367

Epoch 813/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 812 Loss: 0.0034459801390767097

Epoch 814/2000: 100%|██████████| 34/34 [00:00<00:00, 64.91it/s]

Epoch 813 Loss: 0.0018526747589930892

Epoch 815/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 814 Loss: 0.004127458669245243

Epoch 816/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 815 Loss: 0.016782395541667938

Epoch 817/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 816 Loss: 0.020307457074522972

Epoch 818/2000: 100%|██████████| 34/34 [00:00<00:00, 65.01it/s]

Epoch 817 Loss: 0.009118507616221905

Epoch 819/2000: 100%|██████████| 34/34 [00:00<00:00, 65.03it/s]

Epoch 818 Loss: 0.00262394268065691

Epoch 820/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 819 Loss: 0.006446230690926313

Epoch 821/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 820 Loss: 0.004757914692163467

Epoch 822/2000: 100%|██████████| 34/34 [00:00<00:00, 65.10it/s]

Epoch 821 Loss: 0.010046030394732952

Epoch 823/2000: 100%|██████████| 34/34 [00:00<00:00, 65.03it/s]

Epoch 822 Loss: 0.005132333375513554

Epoch 824/2000: 100%|██████████| 34/34 [00:00<00:00, 64.91it/s]

Epoch 823 Loss: 0.011554941534996033

Epoch 825/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 824 Loss: 0.004522417671978474

Epoch 826/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 825 Loss: 0.013584233820438385

Epoch 827/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 826 Loss: 0.0023747393861413

Epoch 828/2000: 100%|██████████| 34/34 [00:00<00:00, 64.97it/s]

Epoch 827 Loss: 0.010458378121256828

Epoch 829/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 828 Loss: 0.015481510199606419

Epoch 830/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 829 Loss: 0.00873901229351759

Epoch 831/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 830 Loss: 0.0017714299028739333

Epoch 832/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 831 Loss: 0.014060580171644688

Epoch 833/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 832 Loss: 0.03992834314703941

Epoch 834/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 833 Loss: 0.007596998009830713

Epoch 835/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 834 Loss: 0.002594457706436515

Epoch 836/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 835 Loss: 0.002604040317237377

Epoch 837/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 836 Loss: 0.008007959462702274

Epoch 838/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 837 Loss: 0.0059895506128668785

Epoch 839/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 838 Loss: 0.022000808268785477

Epoch 840/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 839 Loss: 0.022635582834482193

Epoch 841/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 840 Loss: 0.017873695120215416

Epoch 842/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 841 Loss: 0.0028890357352793217

Epoch 843/2000: 100%|██████████| 34/34 [00:00<00:00, 62.13it/s]

Epoch 842 Loss: 0.013800220564007759

Epoch 844/2000: 100%|██████████| 34/34 [00:00<00:00, 63.26it/s]

Epoch 843 Loss: 0.005489411763846874

Epoch 845/2000: 100%|██████████| 34/34 [00:00<00:00, 64.34it/s]

Epoch 844 Loss: 0.0023984601721167564

Epoch 846/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 845 Loss: 0.004083485342562199

Epoch 847/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 846 Loss: 0.0021579801104962826

Epoch 848/2000: 100%|██████████| 34/34 [00:00<00:00, 63.90it/s]

Epoch 847 Loss: 0.01740935631096363

Epoch 849/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 848 Loss: 0.002760526491329074

Epoch 850/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 849 Loss: 0.0018953544786199927

Epoch 851/2000: 100%|██████████| 34/34 [00:00<00:00, 63.65it/s]

Epoch 850 Loss: 0.0047517321072518826

Epoch 852/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 851 Loss: 0.017362793907523155

Epoch 853/2000: 100%|██████████| 34/34 [00:00<00:00, 62.60it/s]

Epoch 852 Loss: 0.007593450602144003

Epoch 854/2000: 100%|██████████| 34/34 [00:00<00:00, 63.03it/s]

Epoch 853 Loss: 0.040844496339559555

Epoch 855/2000: 100%|██████████| 34/34 [00:00<00:00, 63.67it/s]

Epoch 854 Loss: 0.00605729827657342

Epoch 856/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 855 Loss: 0.0037260050885379314

Epoch 857/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 856 Loss: 0.00740816630423069

Epoch 858/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 857 Loss: 0.00490699103102088

Epoch 859/2000: 100%|██████████| 34/34 [00:00<00:00, 64.28it/s]

Epoch 858 Loss: 0.014600630849599838

Epoch 860/2000: 100%|██████████| 34/34 [00:00<00:00, 64.30it/s]

Epoch 859 Loss: 0.020822927355766296

Epoch 861/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 860 Loss: 0.011172990314662457

Epoch 862/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 861 Loss: 0.0022243144921958447

Epoch 863/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 862 Loss: 0.002000687876716256

Epoch 864/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 863 Loss: 0.016886981204152107

Epoch 865/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 864 Loss: 0.0023895972408354282

Epoch 866/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 865 Loss: 0.0032774063292890787

Epoch 867/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 866 Loss: 0.013234719634056091

Epoch 868/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 867 Loss: 0.009307288564741611

Epoch 869/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 868 Loss: 0.009098291397094727

Epoch 870/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 869 Loss: 0.03277258202433586

Epoch 871/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 870 Loss: 0.0028568957932293415

Epoch 872/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 871 Loss: 0.03314819186925888

Epoch 873/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 872 Loss: 0.02940886840224266

Epoch 874/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 873 Loss: 0.0027664946392178535

Epoch 875/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 874 Loss: 0.0037448753137141466

Epoch 876/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 875 Loss: 0.024835558608174324

Epoch 877/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 876 Loss: 0.013089703395962715

Epoch 878/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 877 Loss: 0.002326955320313573

Epoch 879/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 878 Loss: 0.006250111851841211

Epoch 880/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 879 Loss: 0.008332748897373676

Epoch 881/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 880 Loss: 0.007379904855042696

Epoch 882/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 881 Loss: 0.03649219870567322

Epoch 883/2000: 100%|██████████| 34/34 [00:00<00:00, 63.60it/s]

Epoch 882 Loss: 0.019327722489833832

Epoch 884/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 883 Loss: 0.004874744918197393

Epoch 885/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 884 Loss: 0.021901268512010574

Epoch 886/2000: 100%|██████████| 34/34 [00:00<00:00, 63.22it/s]

Epoch 885 Loss: 0.021332887932658195

Epoch 887/2000: 100%|██████████| 34/34 [00:00<00:00, 63.23it/s]

Epoch 886 Loss: 0.004235299304127693

Epoch 888/2000: 100%|██████████| 34/34 [00:00<00:00, 63.22it/s]

Epoch 887 Loss: 0.020109152421355247

Epoch 889/2000: 100%|██████████| 34/34 [00:00<00:00, 63.24it/s]

Epoch 888 Loss: 0.005921474192291498

Epoch 890/2000: 100%|██████████| 34/34 [00:00<00:00, 63.23it/s]

Epoch 889 Loss: 0.002559741260483861

Epoch 891/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 890 Loss: 0.014216328971087933

Epoch 892/2000: 100%|██████████| 34/34 [00:00<00:00, 63.28it/s]

Epoch 891 Loss: 0.0018774106865748763

Epoch 893/2000: 100%|██████████| 34/34 [00:00<00:00, 63.24it/s]

Epoch 892 Loss: 0.007542988285422325

Epoch 894/2000: 100%|██████████| 34/34 [00:00<00:00, 63.03it/s]

Epoch 893 Loss: 0.0048964908346533775

Epoch 895/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 894 Loss: 0.007471694145351648

Epoch 896/2000: 100%|██████████| 34/34 [00:00<00:00, 63.29it/s]

Epoch 895 Loss: 0.0073753478936851025

Epoch 897/2000: 100%|██████████| 34/34 [00:00<00:00, 63.13it/s]

Epoch 896 Loss: 0.017669053748250008

Epoch 898/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 897 Loss: 0.0041819182224571705

Epoch 899/2000: 100%|██████████| 34/34 [00:00<00:00, 62.67it/s]

Epoch 898 Loss: 0.007600743323564529

Epoch 900/2000: 100%|██████████| 34/34 [00:00<00:00, 63.20it/s]

Epoch 899 Loss: 0.006423520855605602

Epoch 901/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 900 Loss: 0.004183123353868723

Epoch 902/2000: 100%|██████████| 34/34 [00:00<00:00, 63.11it/s]

Epoch 901 Loss: 0.006267880089581013

Epoch 903/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 902 Loss: 0.005769950337707996

Epoch 904/2000: 100%|██████████| 34/34 [00:00<00:00, 63.20it/s]

Epoch 903 Loss: 0.003218764904886484

Epoch 905/2000: 100%|██████████| 34/34 [00:00<00:00, 63.24it/s]

Epoch 904 Loss: 0.0073646423406898975

Epoch 906/2000: 100%|██████████| 34/34 [00:00<00:00, 63.23it/s]

Epoch 905 Loss: 0.0027114960830658674

Epoch 907/2000: 100%|██████████| 34/34 [00:00<00:00, 63.26it/s]

Epoch 906 Loss: 0.0019486532546579838

Epoch 908/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 907 Loss: 0.0015836248639971018

Epoch 909/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 908 Loss: 0.0032882748637348413

Epoch 910/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 909 Loss: 0.001303979428485036

Epoch 911/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 910 Loss: 0.002001196378841996

Epoch 912/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 911 Loss: 0.04234408959746361

Epoch 913/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 912 Loss: 0.003328974125906825

Epoch 914/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 913 Loss: 0.015229204669594765

Epoch 915/2000: 100%|██████████| 34/34 [00:00<00:00, 64.01it/s]

Epoch 914 Loss: 0.001841431949287653

Epoch 916/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 915 Loss: 0.004209103062748909

Epoch 917/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 916 Loss: 0.025987565517425537

Epoch 918/2000: 100%|██████████| 34/34 [00:00<00:00, 63.64it/s]

Epoch 917 Loss: 0.0032777683809399605

Epoch 919/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 918 Loss: 0.024976558983325958

Epoch 920/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 919 Loss: 0.007597609888762236

Epoch 921/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 920 Loss: 0.0021811015903949738

Epoch 922/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 921 Loss: 0.00377593282610178

Epoch 923/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 922 Loss: 0.0015545384958386421

Epoch 924/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 923 Loss: 0.00999689195305109

Epoch 925/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 924 Loss: 0.0060206991620361805

Epoch 926/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 925 Loss: 0.0038113477639853954

Epoch 927/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 926 Loss: 0.002857843181118369

Epoch 928/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 927 Loss: 0.002361084334552288

Epoch 929/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 928 Loss: 0.00173777318559587

Epoch 930/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 929 Loss: 0.00652448832988739

Epoch 931/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 930 Loss: 0.004680732265114784

Epoch 932/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 931 Loss: 0.006618340965360403

Epoch 933/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 932 Loss: 0.013630031608045101

Epoch 934/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 933 Loss: 0.002314432989805937

Epoch 935/2000: 100%|██████████| 34/34 [00:00<00:00, 63.04it/s]

Epoch 934 Loss: 0.004775616340339184

Epoch 936/2000: 100%|██████████| 34/34 [00:00<00:00, 63.55it/s]

Epoch 935 Loss: 0.014831116423010826

Epoch 937/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 936 Loss: 0.011163967661559582

Epoch 938/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 937 Loss: 0.024655630812048912

Epoch 939/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 938 Loss: 0.002242758171632886

Epoch 940/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 939 Loss: 0.027264662086963654

Epoch 941/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 940 Loss: 0.0027020671404898167

Epoch 942/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 941 Loss: 0.0028631591703742743

Epoch 943/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 942 Loss: 0.0060347882099449635

Epoch 944/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 943 Loss: 0.0021934835240244865

Epoch 945/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 944 Loss: 0.008943915367126465

Epoch 946/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 945 Loss: 0.002424022415652871

Epoch 947/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 946 Loss: 0.008230733685195446

Epoch 948/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 947 Loss: 0.014904283918440342

Epoch 949/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 948 Loss: 0.0023347530514001846

Epoch 950/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 949 Loss: 0.0038346066139638424

Epoch 951/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 950 Loss: 0.006636267993599176

Epoch 952/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 951 Loss: 0.022588806226849556

Epoch 953/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 952 Loss: 0.03840998560190201

Epoch 954/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 953 Loss: 0.024098433554172516

Epoch 955/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 954 Loss: 0.003125863615423441

Epoch 956/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 955 Loss: 0.007712448015809059

Epoch 957/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 956 Loss: 0.007406067103147507

Epoch 958/2000: 100%|██████████| 34/34 [00:00<00:00, 64.81it/s]

Epoch 957 Loss: 0.005210580304265022

Epoch 959/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 958 Loss: 0.002103686798363924

Epoch 960/2000: 100%|██████████| 34/34 [00:00<00:00, 64.85it/s]

Epoch 959 Loss: 0.0032263831235468388

Epoch 961/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 960 Loss: 0.030600547790527344

Epoch 962/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 961 Loss: 0.014907428063452244

Epoch 963/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 962 Loss: 0.01589765027165413

Epoch 964/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 963 Loss: 0.003154854755848646

Epoch 965/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 964 Loss: 0.004606262315064669

Epoch 966/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 965 Loss: 0.0033590642269700766

Epoch 967/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 966 Loss: 0.005686173215508461

Epoch 968/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 967 Loss: 0.008243990130722523

Epoch 969/2000: 100%|██████████| 34/34 [00:00<00:00, 64.33it/s]

Epoch 968 Loss: 0.0076143876649439335

Epoch 970/2000: 100%|██████████| 34/34 [00:00<00:00, 64.63it/s]

Epoch 969 Loss: 0.00402213167399168

Epoch 971/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 970 Loss: 0.03196820989251137

Epoch 972/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 971 Loss: 0.002774630207568407

Epoch 973/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 972 Loss: 0.0038945756386965513

Epoch 974/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 973 Loss: 0.004048132337629795

Epoch 975/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 974 Loss: 0.009841825813055038

Epoch 976/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 975 Loss: 0.00896258745342493

Epoch 977/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 976 Loss: 0.0030527054332196712

Epoch 978/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 977 Loss: 0.003135398030281067

Epoch 979/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 978 Loss: 0.011958705261349678

Epoch 980/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 979 Loss: 0.005552425514906645

Epoch 981/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 980 Loss: 0.009809930808842182

Epoch 982/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 981 Loss: 0.0014762573409825563

Epoch 983/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 982 Loss: 0.0031974934972822666

Epoch 984/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 983 Loss: 0.0032707080245018005

Epoch 985/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 984 Loss: 0.02345222793519497

Epoch 986/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 985 Loss: 0.006245368625968695

Epoch 987/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 986 Loss: 0.006081595551222563

Epoch 988/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 987 Loss: 0.011417210102081299

Epoch 989/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 988 Loss: 0.005282299127429724

Epoch 990/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 989 Loss: 0.0028239767998456955

Epoch 991/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 990 Loss: 0.002421919722110033

Epoch 992/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 991 Loss: 0.012763005681335926

Epoch 993/2000: 100%|██████████| 34/34 [00:00<00:00, 63.95it/s]

Epoch 992 Loss: 0.03431392461061478

Epoch 994/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 993 Loss: 0.007766664959490299

Epoch 995/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 994 Loss: 0.0017880713567137718

Epoch 996/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 995 Loss: 0.0016376266721636057

Epoch 997/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 996 Loss: 0.010104791261255741

Epoch 998/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 997 Loss: 0.0017901420360431075

Epoch 999/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 998 Loss: 0.006604334805160761

Epoch 1000/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 999 Loss: 0.004938100930303335

Epoch 1001/2000: 100%|██████████| 34/34 [00:00<00:00, 63.15it/s]

Epoch 1000 Loss: 0.009308750741183758

Epoch 1002/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 1001 Loss: 0.0046086679212749004

Epoch 1003/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1002 Loss: 0.008050082251429558

Epoch 1004/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 1003 Loss: 0.002627816516906023

Epoch 1005/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1004 Loss: 0.012925204820930958

Epoch 1006/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1005 Loss: 0.001718179788440466

Epoch 1007/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1006 Loss: 0.030288124457001686

Epoch 1008/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 1007 Loss: 0.005669940263032913

Epoch 1009/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1008 Loss: 0.011713522486388683

Epoch 1010/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1009 Loss: 0.0029520660173147917

Epoch 1011/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 1010 Loss: 0.006267084274441004

Epoch 1012/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 1011 Loss: 0.001952921855263412

Epoch 1013/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1012 Loss: 0.005154166836291552

Epoch 1014/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 1013 Loss: 0.001567329280078411

Epoch 1015/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 1014 Loss: 0.005290686618536711

Epoch 1016/2000: 100%|██████████| 34/34 [00:00<00:00, 64.81it/s]

Epoch 1015 Loss: 0.0029773765709251165

Epoch 1017/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 1016 Loss: 0.0018700935179367661

Epoch 1018/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 1017 Loss: 0.004496444016695023

Epoch 1019/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1018 Loss: 0.003670593025162816

Epoch 1020/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 1019 Loss: 0.0052296994253993034

Epoch 1021/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1020 Loss: 0.0064110890962183475

Epoch 1022/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 1021 Loss: 0.0014660536544397473

Epoch 1023/2000: 100%|██████████| 34/34 [00:00<00:00, 64.90it/s]

Epoch 1022 Loss: 0.0027865725569427013

Epoch 1024/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 1023 Loss: 0.0025951899588108063

Epoch 1025/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 1024 Loss: 0.002866617636755109

Epoch 1026/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 1025 Loss: 0.03394227847456932

Epoch 1027/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 1026 Loss: 0.009148335084319115

Epoch 1028/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 1027 Loss: 0.0014535144437104464

Epoch 1029/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1028 Loss: 0.002255581319332123

Epoch 1030/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1029 Loss: 0.006598176900297403

Epoch 1031/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1030 Loss: 0.010012553073465824

Epoch 1032/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1031 Loss: 0.009444770403206348

Epoch 1033/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1032 Loss: 0.004652573727071285

Epoch 1034/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1033 Loss: 0.006107598543167114

Epoch 1035/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1034 Loss: 0.00569545105099678

Epoch 1036/2000: 100%|██████████| 34/34 [00:00<00:00, 63.60it/s]

Epoch 1035 Loss: 0.005223684478551149

Epoch 1037/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1036 Loss: 0.006258390378206968

Epoch 1038/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1037 Loss: 0.00902325939387083

Epoch 1039/2000: 100%|██████████| 34/34 [00:00<00:00, 63.10it/s]

Epoch 1038 Loss: 0.016906583681702614

Epoch 1040/2000: 100%|██████████| 34/34 [00:00<00:00, 63.79it/s]

Epoch 1039 Loss: 0.016918892040848732

Epoch 1041/2000: 100%|██████████| 34/34 [00:00<00:00, 63.86it/s]

Epoch 1040 Loss: 0.0014874044572934508

Epoch 1042/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1041 Loss: 0.0022715239319950342

Epoch 1043/2000: 100%|██████████| 34/34 [00:00<00:00, 63.82it/s]

Epoch 1042 Loss: 0.0013063442893326283

Epoch 1044/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1043 Loss: 0.007079394068568945

Epoch 1045/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1044 Loss: 0.0017247730866074562

Epoch 1046/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1045 Loss: 0.011281456798315048

Epoch 1047/2000: 100%|██████████| 34/34 [00:00<00:00, 63.69it/s]

Epoch 1046 Loss: 0.030348947271704674

Epoch 1048/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1047 Loss: 0.03219720348715782

Epoch 1049/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 1048 Loss: 0.014563195407390594

Epoch 1050/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1049 Loss: 0.04155506566166878

Epoch 1051/2000: 100%|██████████| 34/34 [00:00<00:00, 63.58it/s]

Epoch 1050 Loss: 0.008077413775026798

Epoch 1052/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1051 Loss: 0.008653338067233562

Epoch 1053/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1052 Loss: 0.0022747546900063753

Epoch 1054/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1053 Loss: 0.005665040109306574

Epoch 1055/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1054 Loss: 0.005181372631341219

Epoch 1056/2000: 100%|██████████| 34/34 [00:00<00:00, 63.61it/s]

Epoch 1055 Loss: 0.009460408240556717

Epoch 1057/2000: 100%|██████████| 34/34 [00:00<00:00, 63.42it/s]

Epoch 1056 Loss: 0.004026585258543491

Epoch 1058/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1057 Loss: 0.015444766730070114

Epoch 1059/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1058 Loss: 0.004403733182698488

Epoch 1060/2000: 100%|██████████| 34/34 [00:00<00:00, 63.60it/s]

Epoch 1059 Loss: 0.011032910086214542

Epoch 1061/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1060 Loss: 0.002783551113680005

Epoch 1062/2000: 100%|██████████| 34/34 [00:00<00:00, 63.52it/s]

Epoch 1061 Loss: 0.004451159853488207

Epoch 1063/2000: 100%|██████████| 34/34 [00:00<00:00, 63.48it/s]

Epoch 1062 Loss: 0.003240761114284396

Epoch 1064/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1063 Loss: 0.0028294643852859735

Epoch 1065/2000: 100%|██████████| 34/34 [00:00<00:00, 63.10it/s]

Epoch 1064 Loss: 0.020222334191203117

Epoch 1066/2000: 100%|██████████| 34/34 [00:00<00:00, 63.17it/s]

Epoch 1065 Loss: 0.0013318719575181603

Epoch 1067/2000: 100%|██████████| 34/34 [00:00<00:00, 63.36it/s]

Epoch 1066 Loss: 0.0054995352402329445

Epoch 1068/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 1067 Loss: 0.004760500509291887

Epoch 1069/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 1068 Loss: 0.0021983240731060505

Epoch 1070/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 1069 Loss: 0.004922831896692514

Epoch 1071/2000: 100%|██████████| 34/34 [00:00<00:00, 63.55it/s]

Epoch 1070 Loss: 0.007477532606571913

Epoch 1072/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1071 Loss: 0.018868817016482353

Epoch 1073/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1072 Loss: 0.0030762171372771263

Epoch 1074/2000: 100%|██████████| 34/34 [00:00<00:00, 63.89it/s]

Epoch 1073 Loss: 0.009919287636876106

Epoch 1075/2000: 100%|██████████| 34/34 [00:00<00:00, 63.55it/s]

Epoch 1074 Loss: 0.012676204554736614

Epoch 1076/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1075 Loss: 0.018376806750893593

Epoch 1077/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1076 Loss: 0.006474748253822327

Epoch 1078/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1077 Loss: 0.0012758508091792464

Epoch 1079/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1078 Loss: 0.002093015005812049

Epoch 1080/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1079 Loss: 0.004202628042548895

Epoch 1081/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1080 Loss: 0.0033292912412434816

Epoch 1082/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1081 Loss: 0.0072445133700966835

Epoch 1083/2000: 100%|██████████| 34/34 [00:00<00:00, 63.45it/s]

Epoch 1082 Loss: 0.021489180624485016

Epoch 1084/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1083 Loss: 0.0017030044691637158

Epoch 1085/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1084 Loss: 0.0037380014546215534

Epoch 1086/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1085 Loss: 0.02448992058634758

Epoch 1087/2000: 100%|██████████| 34/34 [00:00<00:00, 63.42it/s]

Epoch 1086 Loss: 0.0052518462762236595

Epoch 1088/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1087 Loss: 0.006198216695338488

Epoch 1089/2000: 100%|██████████| 34/34 [00:00<00:00, 63.46it/s]

Epoch 1088 Loss: 0.007899543270468712

Epoch 1090/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1089 Loss: 0.020062996074557304

Epoch 1091/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 1090 Loss: 0.004766527097672224

Epoch 1092/2000: 100%|██████████| 34/34 [00:00<00:00, 63.35it/s]

Epoch 1091 Loss: 0.026562387123703957

Epoch 1093/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1092 Loss: 0.004142932128161192

Epoch 1094/2000: 100%|██████████| 34/34 [00:00<00:00, 63.47it/s]

Epoch 1093 Loss: 0.0035240384750068188

Epoch 1095/2000: 100%|██████████| 34/34 [00:00<00:00, 63.59it/s]

Epoch 1094 Loss: 0.006807275582104921

Epoch 1096/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1095 Loss: 0.013621301390230656

Epoch 1097/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1096 Loss: 0.02278127148747444

Epoch 1098/2000: 100%|██████████| 34/34 [00:00<00:00, 63.86it/s]

Epoch 1097 Loss: 0.005585862323641777

Epoch 1099/2000: 100%|██████████| 34/34 [00:00<00:00, 63.80it/s]

Epoch 1098 Loss: 0.0021419888362288475

Epoch 1100/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1099 Loss: 0.0032938492950052023

Epoch 1101/2000: 100%|██████████| 34/34 [00:00<00:00, 63.47it/s]

Epoch 1100 Loss: 0.02604222111403942

Epoch 1102/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1101 Loss: 0.004078481812030077

Epoch 1103/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 1102 Loss: 0.012361071072518826

Epoch 1104/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1103 Loss: 0.013268014416098595

Epoch 1105/2000: 100%|██████████| 34/34 [00:00<00:00, 63.89it/s]

Epoch 1104 Loss: 0.006691353395581245

Epoch 1106/2000: 100%|██████████| 34/34 [00:00<00:00, 63.80it/s]

Epoch 1105 Loss: 0.004997849930077791

Epoch 1107/2000: 100%|██████████| 34/34 [00:00<00:00, 63.62it/s]

Epoch 1106 Loss: 0.0026897441130131483

Epoch 1108/2000: 100%|██████████| 34/34 [00:00<00:00, 63.46it/s]

Epoch 1107 Loss: 0.004274503327906132

Epoch 1109/2000: 100%|██████████| 34/34 [00:00<00:00, 63.56it/s]

Epoch 1108 Loss: 0.0017879155930131674

Epoch 1110/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1109 Loss: 0.0016149134607985616

Epoch 1111/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1110 Loss: 0.007437329739332199

Epoch 1112/2000: 100%|██████████| 34/34 [00:00<00:00, 63.57it/s]

Epoch 1111 Loss: 0.0019273747457191348

Epoch 1113/2000: 100%|██████████| 34/34 [00:00<00:00, 63.95it/s]

Epoch 1112 Loss: 0.00161675363779068

Epoch 1114/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1113 Loss: 0.036383479833602905

Epoch 1115/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1114 Loss: 0.004676942713558674

Epoch 1116/2000: 100%|██████████| 34/34 [00:00<00:00, 63.54it/s]

Epoch 1115 Loss: 0.0037505310028791428

Epoch 1117/2000: 100%|██████████| 34/34 [00:00<00:00, 63.43it/s]

Epoch 1116 Loss: 0.00797085091471672

Epoch 1118/2000: 100%|██████████| 34/34 [00:00<00:00, 63.35it/s]

Epoch 1117 Loss: 0.0065332138910889626

Epoch 1119/2000: 100%|██████████| 34/34 [00:00<00:00, 63.90it/s]

Epoch 1118 Loss: 0.03588075190782547

Epoch 1120/2000: 100%|██████████| 34/34 [00:00<00:00, 63.80it/s]

Epoch 1119 Loss: 0.00640206690877676

Epoch 1121/2000: 100%|██████████| 34/34 [00:00<00:00, 63.82it/s]

Epoch 1120 Loss: 0.002951079048216343

Epoch 1122/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1121 Loss: 0.0020852775778621435

Epoch 1123/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1122 Loss: 0.0015271221054717898

Epoch 1124/2000: 100%|██████████| 34/34 [00:00<00:00, 63.57it/s]

Epoch 1123 Loss: 0.010841216892004013

Epoch 1125/2000: 100%|██████████| 34/34 [00:00<00:00, 61.76it/s]

Epoch 1124 Loss: 0.0027452304493635893

Epoch 1126/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 1125 Loss: 0.014500356279313564

Epoch 1127/2000: 100%|██████████| 34/34 [00:00<00:00, 61.90it/s]

Epoch 1126 Loss: 0.027505317702889442

Epoch 1128/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 1127 Loss: 0.002478643087670207

Epoch 1129/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 1128 Loss: 0.01938673108816147

Epoch 1130/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 1129 Loss: 0.0087507925927639

Epoch 1131/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 1130 Loss: 0.015065999701619148

Epoch 1132/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 1131 Loss: 0.0017770811682567

Epoch 1133/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 1132 Loss: 0.004608660936355591

Epoch 1134/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 1133 Loss: 0.008671017363667488

Epoch 1135/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 1134 Loss: 0.024465685710310936

Epoch 1136/2000: 100%|██████████| 34/34 [00:00<00:00, 61.59it/s]

Epoch 1135 Loss: 0.0018320499220862985

Epoch 1137/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 1136 Loss: 0.0027266591787338257

Epoch 1138/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 1137 Loss: 0.0190862026065588

Epoch 1139/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 1138 Loss: 0.00960511900484562

Epoch 1140/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1139 Loss: 0.0017717378214001656

Epoch 1141/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 1140 Loss: 0.012018045410513878

Epoch 1142/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 1141 Loss: 0.0020651936065405607

Epoch 1143/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 1142 Loss: 0.006342415232211351

Epoch 1144/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 1143 Loss: 0.001181336585432291

Epoch 1145/2000: 100%|██████████| 34/34 [00:00<00:00, 61.82it/s]

Epoch 1144 Loss: 0.0011669264640659094

Epoch 1146/2000: 100%|██████████| 34/34 [00:00<00:00, 59.97it/s]

Epoch 1145 Loss: 0.00650097755715251

Epoch 1147/2000: 100%|██████████| 34/34 [00:00<00:00, 62.13it/s]

Epoch 1146 Loss: 0.03694430738687515

Epoch 1148/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1147 Loss: 0.0034462183248251677

Epoch 1149/2000: 100%|██████████| 34/34 [00:00<00:00, 62.11it/s]

Epoch 1148 Loss: 0.004473793786019087

Epoch 1150/2000: 100%|██████████| 34/34 [00:00<00:00, 62.43it/s]

Epoch 1149 Loss: 0.012369809672236443

Epoch 1151/2000: 100%|██████████| 34/34 [00:00<00:00, 62.59it/s]

Epoch 1150 Loss: 0.01773407869040966

Epoch 1152/2000: 100%|██████████| 34/34 [00:00<00:00, 61.92it/s]

Epoch 1151 Loss: 0.0028034134302288294

Epoch 1153/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 1152 Loss: 0.016776068136096

Epoch 1154/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 1153 Loss: 0.004220247734338045

Epoch 1155/2000: 100%|██████████| 34/34 [00:00<00:00, 62.49it/s]

Epoch 1154 Loss: 0.0033191244583576918

Epoch 1156/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 1155 Loss: 0.022853868082165718

Epoch 1157/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1156 Loss: 0.0018451448995620012

Epoch 1158/2000: 100%|██████████| 34/34 [00:00<00:00, 62.54it/s]

Epoch 1157 Loss: 0.002213971223682165

Epoch 1159/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 1158 Loss: 0.005916329100728035

Epoch 1160/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 1159 Loss: 0.004322899505496025

Epoch 1161/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 1160 Loss: 0.019267253577709198

Epoch 1162/2000: 100%|██████████| 34/34 [00:00<00:00, 62.39it/s]

Epoch 1161 Loss: 0.005997484549880028

Epoch 1163/2000: 100%|██████████| 34/34 [00:00<00:00, 62.24it/s]

Epoch 1162 Loss: 0.0032058849465101957

Epoch 1164/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 1163 Loss: 0.009477476589381695

Epoch 1165/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 1164 Loss: 0.0226203091442585

Epoch 1166/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 1165 Loss: 0.012601454742252827

Epoch 1167/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 1166 Loss: 0.025352180004119873

Epoch 1168/2000: 100%|██████████| 34/34 [00:00<00:00, 62.15it/s]

Epoch 1167 Loss: 0.031570352613925934

Epoch 1169/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 1168 Loss: 0.012594969943165779

Epoch 1170/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 1169 Loss: 0.010593065060675144

Epoch 1171/2000: 100%|██████████| 34/34 [00:00<00:00, 62.26it/s]

Epoch 1170 Loss: 0.004812641069293022

Epoch 1172/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 1171 Loss: 0.0018139489693567157

Epoch 1173/2000: 100%|██████████| 34/34 [00:00<00:00, 62.41it/s]

Epoch 1172 Loss: 0.007153936196118593

Epoch 1174/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 1173 Loss: 0.0061266422271728516

Epoch 1175/2000: 100%|██████████| 34/34 [00:00<00:00, 62.50it/s]

Epoch 1174 Loss: 0.011898091994225979

Epoch 1176/2000: 100%|██████████| 34/34 [00:00<00:00, 62.45it/s]

Epoch 1175 Loss: 0.001561091630719602

Epoch 1177/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 1176 Loss: 0.001415993319824338

Epoch 1178/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 1177 Loss: 0.007320199627429247

Epoch 1179/2000: 100%|██████████| 34/34 [00:00<00:00, 62.25it/s]

Epoch 1178 Loss: 0.01713598519563675

Epoch 1180/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 1179 Loss: 0.00680907629430294

Epoch 1181/2000: 100%|██████████| 34/34 [00:00<00:00, 62.59it/s]

Epoch 1180 Loss: 0.006900213658809662

Epoch 1182/2000: 100%|██████████| 34/34 [00:00<00:00, 62.42it/s]

Epoch 1181 Loss: 0.0070836786180734634

Epoch 1183/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 1182 Loss: 0.004907917231321335

Epoch 1184/2000: 100%|██████████| 34/34 [00:00<00:00, 62.29it/s]

Epoch 1183 Loss: 0.0021687557455152273

Epoch 1185/2000: 100%|██████████| 34/34 [00:00<00:00, 63.51it/s]

Epoch 1184 Loss: 0.03852713108062744

Epoch 1186/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 1185 Loss: 0.011751941405236721

Epoch 1187/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1186 Loss: 0.00852152518928051

Epoch 1188/2000: 100%|██████████| 34/34 [00:00<00:00, 63.38it/s]

Epoch 1187 Loss: 0.001331806997768581

Epoch 1189/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1188 Loss: 0.00705418735742569

Epoch 1190/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 1189 Loss: 0.004114475101232529

Epoch 1191/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1190 Loss: 0.0013240128755569458

Epoch 1192/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 1191 Loss: 0.028940537944436073

Epoch 1193/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1192 Loss: 0.007130993530154228

Epoch 1194/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1193 Loss: 0.004571526311337948

Epoch 1195/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1194 Loss: 0.004612566903233528

Epoch 1196/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1195 Loss: 0.009053440764546394

Epoch 1197/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 1196 Loss: 0.0018976933788508177

Epoch 1198/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1197 Loss: 0.003401414956897497

Epoch 1199/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1198 Loss: 0.003130581695586443

Epoch 1200/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1199 Loss: 0.0014375594910234213

Epoch 1201/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1200 Loss: 0.006214730441570282

Epoch 1202/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1201 Loss: 0.005020428914576769

Epoch 1203/2000: 100%|██████████| 34/34 [00:00<00:00, 64.63it/s]

Epoch 1202 Loss: 0.007989877834916115

Epoch 1204/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1203 Loss: 0.0030132306274026632

Epoch 1205/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1204 Loss: 0.001465363777242601

Epoch 1206/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1205 Loss: 0.003473208285868168

Epoch 1207/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1206 Loss: 0.0030304822139441967

Epoch 1208/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1207 Loss: 0.002316535683348775

Epoch 1209/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1208 Loss: 0.0037187582347542048

Epoch 1210/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 1209 Loss: 0.0014563746517524123

Epoch 1211/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1210 Loss: 0.044152963906526566

Epoch 1212/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 1211 Loss: 0.001953358994796872

Epoch 1213/2000: 100%|██████████| 34/34 [00:00<00:00, 64.28it/s]

Epoch 1212 Loss: 0.005891241133213043

Epoch 1214/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1213 Loss: 0.0020991642959415913

Epoch 1215/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1214 Loss: 0.0012614080915227532

Epoch 1216/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1215 Loss: 0.0016807450447231531

Epoch 1217/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1216 Loss: 0.020778413861989975

Epoch 1218/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1217 Loss: 0.006453842390328646

Epoch 1219/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1218 Loss: 0.00243932893499732

Epoch 1220/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1219 Loss: 0.0011152977822348475

Epoch 1221/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1220 Loss: 0.0017229150980710983

Epoch 1222/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1221 Loss: 0.0019706697203218937

Epoch 1223/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1222 Loss: 0.004724218510091305

Epoch 1224/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1223 Loss: 0.032502517104148865

Epoch 1225/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1224 Loss: 0.0033677469473332167

Epoch 1226/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1225 Loss: 0.002509595127776265

Epoch 1227/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 1226 Loss: 0.0018503076862543821

Epoch 1228/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1227 Loss: 0.0014498720411211252

Epoch 1229/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1228 Loss: 0.049899399280548096

Epoch 1230/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1229 Loss: 0.0029274453409016132

Epoch 1231/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1230 Loss: 0.0027502160519361496

Epoch 1232/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1231 Loss: 0.0022843051701784134

Epoch 1233/2000: 100%|██████████| 34/34 [00:00<00:00, 64.30it/s]

Epoch 1232 Loss: 0.01335755456238985

Epoch 1234/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1233 Loss: 0.00159812334459275

Epoch 1235/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1234 Loss: 0.01834198459982872

Epoch 1236/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1235 Loss: 0.017062848433852196

Epoch 1237/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1236 Loss: 0.0018239885102957487

Epoch 1238/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 1237 Loss: 0.016966944560408592

Epoch 1239/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1238 Loss: 0.02154412306845188

Epoch 1240/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1239 Loss: 0.0012969793751835823

Epoch 1241/2000: 100%|██████████| 34/34 [00:00<00:00, 64.63it/s]

Epoch 1240 Loss: 0.031134305521845818

Epoch 1242/2000: 100%|██████████| 34/34 [00:00<00:00, 64.41it/s]

Epoch 1241 Loss: 0.002206973033025861

Epoch 1243/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1242 Loss: 0.0067547960206866264

Epoch 1244/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1243 Loss: 0.012595400214195251

Epoch 1245/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1244 Loss: 0.0026355686131864786

Epoch 1246/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1245 Loss: 0.004157135728746653

Epoch 1247/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 1246 Loss: 0.011209258809685707

Epoch 1248/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1247 Loss: 0.0021664972882717848

Epoch 1249/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 1248 Loss: 0.003142543602734804

Epoch 1250/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1249 Loss: 0.0019007560331374407

Epoch 1251/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 1250 Loss: 0.017427142709493637

Epoch 1252/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1251 Loss: 0.0072761643677949905

Epoch 1253/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1252 Loss: 0.001965726027265191

Epoch 1254/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1253 Loss: 0.007133416831493378

Epoch 1255/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1254 Loss: 0.009547125548124313

Epoch 1256/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1255 Loss: 0.02679780125617981

Epoch 1257/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1256 Loss: 0.013009262271225452

Epoch 1258/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1257 Loss: 0.00769655779004097

Epoch 1259/2000: 100%|██████████| 34/34 [00:00<00:00, 63.54it/s]

Epoch 1258 Loss: 0.001595142064616084

Epoch 1260/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1259 Loss: 0.011790728196501732

Epoch 1261/2000: 100%|██████████| 34/34 [00:00<00:00, 63.40it/s]

Epoch 1260 Loss: 0.0009135445579886436

Epoch 1262/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1261 Loss: 0.004669419955462217

Epoch 1263/2000: 100%|██████████| 34/34 [00:00<00:00, 63.80it/s]

Epoch 1262 Loss: 0.004164509940892458

Epoch 1264/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1263 Loss: 0.0017966621089726686

Epoch 1265/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1264 Loss: 0.0027730618603527546

Epoch 1266/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1265 Loss: 0.01808803528547287

Epoch 1267/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1266 Loss: 0.005230178590863943

Epoch 1268/2000: 100%|██████████| 34/34 [00:00<00:00, 63.56it/s]

Epoch 1267 Loss: 0.003247980261221528

Epoch 1269/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1268 Loss: 0.010305280797183514

Epoch 1270/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1269 Loss: 0.0018209355184808373

Epoch 1271/2000: 100%|██████████| 34/34 [00:00<00:00, 63.90it/s]

Epoch 1270 Loss: 0.0014791378052905202

Epoch 1272/2000: 100%|██████████| 34/34 [00:00<00:00, 63.82it/s]

Epoch 1271 Loss: 0.0029077257495373487

Epoch 1273/2000: 100%|██████████| 34/34 [00:00<00:00, 63.26it/s]

Epoch 1272 Loss: 0.002399905351921916

Epoch 1274/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1273 Loss: 0.00213512871414423

Epoch 1275/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1274 Loss: 0.004201661795377731

Epoch 1276/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1275 Loss: 0.0423165000975132

Epoch 1277/2000: 100%|██████████| 34/34 [00:00<00:00, 64.63it/s]

Epoch 1276 Loss: 0.00302279950119555

Epoch 1278/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 1277 Loss: 0.0034190767910331488

Epoch 1279/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 1278 Loss: 0.0033741681836545467

Epoch 1280/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1279 Loss: 0.009324464946985245

Epoch 1281/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1280 Loss: 0.009336023591458797

Epoch 1282/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1281 Loss: 0.00931322667747736

Epoch 1283/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1282 Loss: 0.02294335700571537

Epoch 1284/2000: 100%|██████████| 34/34 [00:00<00:00, 63.60it/s]

Epoch 1283 Loss: 0.002431699074804783

Epoch 1285/2000: 100%|██████████| 34/34 [00:00<00:00, 62.99it/s]

Epoch 1284 Loss: 0.002168419072404504

Epoch 1286/2000: 100%|██████████| 34/34 [00:00<00:00, 62.93it/s]

Epoch 1285 Loss: 0.0019003413617610931

Epoch 1287/2000: 100%|██████████| 34/34 [00:00<00:00, 63.06it/s]

Epoch 1286 Loss: 0.0019355188123881817

Epoch 1288/2000: 100%|██████████| 34/34 [00:00<00:00, 62.93it/s]

Epoch 1287 Loss: 0.0016998740611597896

Epoch 1289/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1288 Loss: 0.006743539124727249

Epoch 1290/2000: 100%|██████████| 34/34 [00:00<00:00, 62.94it/s]

Epoch 1289 Loss: 0.004627768415957689

Epoch 1291/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 1290 Loss: 0.0011900487588718534

Epoch 1292/2000: 100%|██████████| 34/34 [00:00<00:00, 63.05it/s]

Epoch 1291 Loss: 0.002890177071094513

Epoch 1293/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 1292 Loss: 0.008003427647054195

Epoch 1294/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 1293 Loss: 0.022466428577899933

Epoch 1295/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 1294 Loss: 0.0012467559427022934

Epoch 1296/2000: 100%|██████████| 34/34 [00:00<00:00, 62.61it/s]

Epoch 1295 Loss: 0.014062969945371151

Epoch 1297/2000: 100%|██████████| 34/34 [00:00<00:00, 62.70it/s]

Epoch 1296 Loss: 0.04019416868686676

Epoch 1298/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 1297 Loss: 0.0019974028691649437

Epoch 1299/2000: 100%|██████████| 34/34 [00:00<00:00, 63.31it/s]

Epoch 1298 Loss: 0.004074320662766695

Epoch 1300/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1299 Loss: 0.0014382313238456845

Epoch 1301/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1300 Loss: 0.0061896308325231075

Epoch 1302/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1301 Loss: 0.01599971391260624

Epoch 1303/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 1302 Loss: 0.00526667945086956

Epoch 1304/2000: 100%|██████████| 34/34 [00:00<00:00, 64.33it/s]

Epoch 1303 Loss: 0.014542564749717712

Epoch 1305/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 1304 Loss: 0.012515051290392876

Epoch 1306/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1305 Loss: 0.003915104083716869

Epoch 1307/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1306 Loss: 0.005227142479270697

Epoch 1308/2000: 100%|██████████| 34/34 [00:00<00:00, 64.28it/s]

Epoch 1307 Loss: 0.02108870819211006

Epoch 1309/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1308 Loss: 0.02676232159137726

Epoch 1310/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 1309 Loss: 0.018026938661932945

Epoch 1311/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1310 Loss: 0.0012615429004654288

Epoch 1312/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1311 Loss: 0.0017167094629257917

Epoch 1313/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1312 Loss: 0.017700156196951866

Epoch 1314/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1313 Loss: 0.0012738360092043877

Epoch 1315/2000: 100%|██████████| 34/34 [00:00<00:00, 63.76it/s]

Epoch 1314 Loss: 0.024549206718802452

Epoch 1316/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 1315 Loss: 0.001726061454974115

Epoch 1317/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 1316 Loss: 0.003482244908809662

Epoch 1318/2000: 100%|██████████| 34/34 [00:00<00:00, 64.62it/s]

Epoch 1317 Loss: 0.022000817582011223

Epoch 1319/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1318 Loss: 0.004186231642961502

Epoch 1320/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 1319 Loss: 0.0010192287154495716

Epoch 1321/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 1320 Loss: 0.02711004577577114

Epoch 1322/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 1321 Loss: 0.00201977975666523

Epoch 1323/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1322 Loss: 0.022981153801083565

Epoch 1324/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1323 Loss: 0.0015453688101843

Epoch 1325/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 1324 Loss: 0.0028785739559680223

Epoch 1326/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 1325 Loss: 0.0019112421432510018

Epoch 1327/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1326 Loss: 0.0016149204457178712

Epoch 1328/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1327 Loss: 0.043206583708524704

Epoch 1329/2000: 100%|██████████| 34/34 [00:00<00:00, 62.56it/s]

Epoch 1328 Loss: 0.004064057022333145

Epoch 1330/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 1329 Loss: 0.08000137656927109

Epoch 1331/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 1330 Loss: 0.004324018023908138

Epoch 1332/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 1331 Loss: 0.004402292892336845

Epoch 1333/2000: 100%|██████████| 34/34 [00:00<00:00, 62.71it/s]

Epoch 1332 Loss: 0.006428093649446964

Epoch 1334/2000: 100%|██████████| 34/34 [00:00<00:00, 62.55it/s]

Epoch 1333 Loss: 0.001393834943883121

Epoch 1335/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1334 Loss: 0.0023675975389778614

Epoch 1336/2000: 100%|██████████| 34/34 [00:00<00:00, 62.81it/s]

Epoch 1335 Loss: 0.0019127995474264026

Epoch 1337/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 1336 Loss: 0.00865749642252922

Epoch 1338/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 1337 Loss: 0.014544173143804073

Epoch 1339/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 1338 Loss: 0.010965327732264996

Epoch 1340/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 1339 Loss: 0.018120000138878822

Epoch 1341/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 1340 Loss: 0.0020595004316419363

Epoch 1342/2000: 100%|██████████| 34/34 [00:00<00:00, 62.70it/s]

Epoch 1341 Loss: 0.012023519724607468

Epoch 1343/2000: 100%|██████████| 34/34 [00:00<00:00, 62.62it/s]

Epoch 1342 Loss: 0.0011073620989918709

Epoch 1344/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 1343 Loss: 0.004781658761203289

Epoch 1345/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1344 Loss: 0.006019845139235258

Epoch 1346/2000: 100%|██████████| 34/34 [00:00<00:00, 62.95it/s]

Epoch 1345 Loss: 0.0013110917061567307

Epoch 1347/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 1346 Loss: 0.00223326962441206

Epoch 1348/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 1347 Loss: 0.0018661750946193933

Epoch 1349/2000: 100%|██████████| 34/34 [00:00<00:00, 62.78it/s]

Epoch 1348 Loss: 0.008520307019352913

Epoch 1350/2000: 100%|██████████| 34/34 [00:00<00:00, 62.98it/s]

Epoch 1349 Loss: 0.0041699642315506935

Epoch 1351/2000: 100%|██████████| 34/34 [00:00<00:00, 62.75it/s]

Epoch 1350 Loss: 0.003924084827303886

Epoch 1352/2000: 100%|██████████| 34/34 [00:00<00:00, 62.90it/s]

Epoch 1351 Loss: 0.002741000382229686

Epoch 1353/2000: 100%|██████████| 34/34 [00:00<00:00, 63.67it/s]

Epoch 1352 Loss: 0.0016564452089369297

Epoch 1354/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1353 Loss: 0.003217906691133976

Epoch 1355/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1354 Loss: 0.0019711540080606937

Epoch 1356/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1355 Loss: 0.009562482126057148

Epoch 1357/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1356 Loss: 0.005481682252138853

Epoch 1358/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1357 Loss: 0.005340336821973324

Epoch 1359/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1358 Loss: 0.0025276741944253445

Epoch 1360/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1359 Loss: 0.002728831022977829

Epoch 1361/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1360 Loss: 0.0031157999765127897

Epoch 1362/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1361 Loss: 0.004601509775966406

Epoch 1363/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1362 Loss: 0.01792510785162449

Epoch 1364/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1363 Loss: 0.0035171133931726217

Epoch 1365/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 1364 Loss: 0.003090077545493841

Epoch 1366/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1365 Loss: 0.008277474902570248

Epoch 1367/2000: 100%|██████████| 34/34 [00:00<00:00, 64.71it/s]

Epoch 1366 Loss: 0.002529584104195237

Epoch 1368/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 1367 Loss: 0.005289917811751366

Epoch 1369/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1368 Loss: 0.0019041522173210979

Epoch 1370/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 1369 Loss: 0.0034197333734482527

Epoch 1371/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1370 Loss: 0.0035459415521472692

Epoch 1372/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 1371 Loss: 0.03986267372965813

Epoch 1373/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 1372 Loss: 0.006884142756462097

Epoch 1374/2000: 100%|██████████| 34/34 [00:00<00:00, 64.69it/s]

Epoch 1373 Loss: 0.002485714852809906

Epoch 1375/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1374 Loss: 0.006242068018764257

Epoch 1376/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1375 Loss: 0.0006786031881347299

Epoch 1377/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 1376 Loss: 0.0009422155562788248

Epoch 1378/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 1377 Loss: 0.009895969182252884

Epoch 1379/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1378 Loss: 0.005173008888959885

Epoch 1380/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 1379 Loss: 0.0017210929654538631

Epoch 1381/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 1380 Loss: 0.0017923046834766865

Epoch 1382/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 1381 Loss: 0.0024758644867688417

Epoch 1383/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1382 Loss: 0.02574508637189865

Epoch 1384/2000: 100%|██████████| 34/34 [00:00<00:00, 64.70it/s]

Epoch 1383 Loss: 0.00988586526364088

Epoch 1385/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 1384 Loss: 0.002274514874443412

Epoch 1386/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 1385 Loss: 0.0060271816328167915

Epoch 1387/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 1386 Loss: 0.0069363354705274105

Epoch 1388/2000: 100%|██████████| 34/34 [00:00<00:00, 64.72it/s]

Epoch 1387 Loss: 0.0022686824668198824

Epoch 1389/2000: 100%|██████████| 34/34 [00:00<00:00, 64.66it/s]

Epoch 1388 Loss: 0.0018218321492895484

Epoch 1390/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1389 Loss: 0.006752748508006334

Epoch 1391/2000: 100%|██████████| 34/34 [00:00<00:00, 64.78it/s]

Epoch 1390 Loss: 0.012646905146539211

Epoch 1392/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1391 Loss: 0.008516546338796616

Epoch 1393/2000: 100%|██████████| 34/34 [00:00<00:00, 63.12it/s]

Epoch 1392 Loss: 0.0027151750400662422

Epoch 1394/2000: 100%|██████████| 34/34 [00:00<00:00, 63.05it/s]

Epoch 1393 Loss: 0.0008307143580168486

Epoch 1395/2000: 100%|██████████| 34/34 [00:00<00:00, 63.06it/s]

Epoch 1394 Loss: 0.004910566378384829

Epoch 1396/2000: 100%|██████████| 34/34 [00:00<00:00, 63.07it/s]

Epoch 1395 Loss: 0.004199265502393246

Epoch 1397/2000: 100%|██████████| 34/34 [00:00<00:00, 62.86it/s]

Epoch 1396 Loss: 0.004336646292358637

Epoch 1398/2000: 100%|██████████| 34/34 [00:00<00:00, 63.09it/s]

Epoch 1397 Loss: 0.00112056452780962

Epoch 1399/2000: 100%|██████████| 34/34 [00:00<00:00, 62.92it/s]

Epoch 1398 Loss: 0.0043655214831233025

Epoch 1400/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1399 Loss: 0.016138341277837753

Epoch 1401/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 1400 Loss: 0.016628043726086617

Epoch 1402/2000: 100%|██████████| 34/34 [00:00<00:00, 63.06it/s]

Epoch 1401 Loss: 0.0076872920617461205

Epoch 1403/2000: 100%|██████████| 34/34 [00:00<00:00, 63.01it/s]

Epoch 1402 Loss: 0.0013949916465207934

Epoch 1404/2000: 100%|██████████| 34/34 [00:00<00:00, 63.20it/s]

Epoch 1403 Loss: 0.007046698126941919

Epoch 1405/2000: 100%|██████████| 34/34 [00:00<00:00, 62.97it/s]

Epoch 1404 Loss: 0.0014635659754276276

Epoch 1406/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 1405 Loss: 0.033338792622089386

Epoch 1407/2000: 100%|██████████| 34/34 [00:00<00:00, 63.19it/s]

Epoch 1406 Loss: 0.00508539006114006

Epoch 1408/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 1407 Loss: 0.005003361497074366

Epoch 1409/2000: 100%|██████████| 34/34 [00:00<00:00, 63.08it/s]

Epoch 1408 Loss: 0.007898816838860512

Epoch 1410/2000: 100%|██████████| 34/34 [00:00<00:00, 63.09it/s]

Epoch 1409 Loss: 0.016570767387747765

Epoch 1411/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 1410 Loss: 0.012280499562621117

Epoch 1412/2000: 100%|██████████| 34/34 [00:00<00:00, 62.83it/s]

Epoch 1411 Loss: 0.0018333670450374484

Epoch 1413/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 1412 Loss: 0.027913104742765427

Epoch 1414/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1413 Loss: 0.018142305314540863

Epoch 1415/2000: 100%|██████████| 34/34 [00:00<00:00, 62.78it/s]

Epoch 1414 Loss: 0.004331138450652361

Epoch 1416/2000: 100%|██████████| 34/34 [00:00<00:00, 62.89it/s]

Epoch 1415 Loss: 0.005133132915943861

Epoch 1417/2000: 100%|██████████| 34/34 [00:00<00:00, 62.84it/s]

Epoch 1416 Loss: 0.009694812819361687

Epoch 1418/2000: 100%|██████████| 34/34 [00:00<00:00, 62.85it/s]

Epoch 1417 Loss: 0.017099080607295036

Epoch 1419/2000: 100%|██████████| 34/34 [00:00<00:00, 62.38it/s]

Epoch 1418 Loss: 0.005948903039097786

Epoch 1420/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 1419 Loss: 0.002675257856026292

Epoch 1421/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 1420 Loss: 0.013731795363128185

Epoch 1422/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 1421 Loss: 0.005913131404668093

Epoch 1423/2000: 100%|██████████| 34/34 [00:00<00:00, 61.73it/s]

Epoch 1422 Loss: 0.0019032859709113836

Epoch 1424/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 1423 Loss: 0.002694526454433799

Epoch 1425/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 1424 Loss: 0.00240284763276577

Epoch 1426/2000: 100%|██████████| 34/34 [00:00<00:00, 62.28it/s]

Epoch 1425 Loss: 0.002765676937997341

Epoch 1427/2000: 100%|██████████| 34/34 [00:00<00:00, 62.32it/s]

Epoch 1426 Loss: 0.0022711085621267557

Epoch 1428/2000: 100%|██████████| 34/34 [00:00<00:00, 62.22it/s]

Epoch 1427 Loss: 0.013377169147133827

Epoch 1429/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 1428 Loss: 0.0013829279923811555

Epoch 1430/2000: 100%|██████████| 34/34 [00:00<00:00, 62.37it/s]

Epoch 1429 Loss: 0.018744928762316704

Epoch 1431/2000: 100%|██████████| 34/34 [00:00<00:00, 62.31it/s]

Epoch 1430 Loss: 0.006475215777754784

Epoch 1432/2000: 100%|██████████| 34/34 [00:00<00:00, 62.14it/s]

Epoch 1431 Loss: 0.0023376643657684326

Epoch 1433/2000: 100%|██████████| 34/34 [00:00<00:00, 60.66it/s]

Epoch 1432 Loss: 0.010754820890724659

Epoch 1434/2000: 100%|██████████| 34/34 [00:00<00:00, 53.49it/s]

Epoch 1433 Loss: 0.0018564540660008788

Epoch 1435/2000: 100%|██████████| 34/34 [00:00<00:00, 53.75it/s]

Epoch 1434 Loss: 0.002109127352014184

Epoch 1436/2000: 100%|██████████| 34/34 [00:00<00:00, 52.85it/s]

Epoch 1435 Loss: 0.006912063341587782

Epoch 1437/2000: 100%|██████████| 34/34 [00:00<00:00, 53.63it/s]

Epoch 1436 Loss: 0.0030030447524040937

Epoch 1438/2000: 100%|██████████| 34/34 [00:00<00:00, 53.62it/s]

Epoch 1437 Loss: 0.002833141479641199

Epoch 1439/2000: 100%|██████████| 34/34 [00:00<00:00, 53.31it/s]

Epoch 1438 Loss: 0.036235082894563675

Epoch 1440/2000: 100%|██████████| 34/34 [00:00<00:00, 60.24it/s]

Epoch 1439 Loss: 0.013881616294384003

Epoch 1441/2000: 100%|██████████| 34/34 [00:00<00:00, 61.88it/s]

Epoch 1440 Loss: 0.0034450236707925797

Epoch 1442/2000: 100%|██████████| 34/34 [00:00<00:00, 61.95it/s]

Epoch 1441 Loss: 0.014024930074810982

Epoch 1443/2000: 100%|██████████| 34/34 [00:00<00:00, 62.18it/s]

Epoch 1442 Loss: 0.00496692257001996

Epoch 1444/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 1443 Loss: 0.0068321009166538715

Epoch 1445/2000: 100%|██████████| 34/34 [00:00<00:00, 62.36it/s]

Epoch 1444 Loss: 0.0049621304497122765

Epoch 1446/2000: 100%|██████████| 34/34 [00:00<00:00, 62.01it/s]

Epoch 1445 Loss: 0.003951369319111109

Epoch 1447/2000: 100%|██████████| 34/34 [00:00<00:00, 61.92it/s]

Epoch 1446 Loss: 0.0009998343884944916

Epoch 1448/2000: 100%|██████████| 34/34 [00:00<00:00, 62.30it/s]

Epoch 1447 Loss: 0.009587256237864494

Epoch 1449/2000: 100%|██████████| 34/34 [00:00<00:00, 62.16it/s]

Epoch 1448 Loss: 0.007145535666495562

Epoch 1450/2000: 100%|██████████| 34/34 [00:00<00:00, 62.16it/s]

Epoch 1449 Loss: 0.0026867010165005922

Epoch 1451/2000: 100%|██████████| 34/34 [00:00<00:00, 62.22it/s]

Epoch 1450 Loss: 0.0220379289239645

Epoch 1452/2000: 100%|██████████| 34/34 [00:00<00:00, 62.33it/s]

Epoch 1451 Loss: 0.002321318956092

Epoch 1453/2000: 100%|██████████| 34/34 [00:00<00:00, 62.20it/s]

Epoch 1452 Loss: 0.006221057381480932

Epoch 1454/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1453 Loss: 0.0018517066491767764

Epoch 1455/2000: 100%|██████████| 34/34 [00:00<00:00, 62.17it/s]

Epoch 1454 Loss: 0.001695927232503891

Epoch 1456/2000: 100%|██████████| 34/34 [00:00<00:00, 62.23it/s]

Epoch 1455 Loss: 0.0074226269498467445

Epoch 1457/2000: 100%|██████████| 34/34 [00:00<00:00, 62.07it/s]

Epoch 1456 Loss: 0.009849521331489086

Epoch 1458/2000: 100%|██████████| 34/34 [00:00<00:00, 61.73it/s]

Epoch 1457 Loss: 0.0064846365712583065

Epoch 1459/2000: 100%|██████████| 34/34 [00:00<00:00, 62.51it/s]

Epoch 1458 Loss: 0.00217067776247859

Epoch 1460/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1459 Loss: 0.047336164861917496

Epoch 1461/2000: 100%|██████████| 34/34 [00:00<00:00, 62.88it/s]

Epoch 1460 Loss: 0.004853595048189163

Epoch 1462/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1461 Loss: 0.0018797274678945541

Epoch 1463/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1462 Loss: 0.0035923514515161514

Epoch 1464/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1463 Loss: 0.016482127830386162

Epoch 1465/2000: 100%|██████████| 34/34 [00:00<00:00, 63.82it/s]

Epoch 1464 Loss: 0.03598723188042641

Epoch 1466/2000: 100%|██████████| 34/34 [00:00<00:00, 63.59it/s]

Epoch 1465 Loss: 0.005901941563934088

Epoch 1467/2000: 100%|██████████| 34/34 [00:00<00:00, 63.76it/s]

Epoch 1466 Loss: 0.00257487827911973

Epoch 1468/2000: 100%|██████████| 34/34 [00:00<00:00, 63.64it/s]

Epoch 1467 Loss: 0.0010618368396535516

Epoch 1469/2000: 100%|██████████| 34/34 [00:00<00:00, 63.79it/s]

Epoch 1468 Loss: 0.01724172756075859

Epoch 1470/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1469 Loss: 0.014062792994081974

Epoch 1471/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1470 Loss: 0.021238969638943672

Epoch 1472/2000: 100%|██████████| 34/34 [00:00<00:00, 63.94it/s]

Epoch 1471 Loss: 0.0019503923831507564

Epoch 1473/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 1472 Loss: 0.004964913707226515

Epoch 1474/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1473 Loss: 0.021730201318860054

Epoch 1475/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 1474 Loss: 0.006006036419421434

Epoch 1476/2000: 100%|██████████| 34/34 [00:00<00:00, 63.50it/s]

Epoch 1475 Loss: 0.010635417886078358

Epoch 1477/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1476 Loss: 0.0008633105899207294

Epoch 1478/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1477 Loss: 0.0261711273342371

Epoch 1479/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1478 Loss: 0.0014552215579897165

Epoch 1480/2000: 100%|██████████| 34/34 [00:00<00:00, 63.74it/s]

Epoch 1479 Loss: 0.005203675478696823

Epoch 1481/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1480 Loss: 0.014040506444871426

Epoch 1482/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1481 Loss: 0.010879271663725376

Epoch 1483/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1482 Loss: 0.0010071663418784738

Epoch 1484/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1483 Loss: 0.009030276909470558

Epoch 1485/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1484 Loss: 0.0027297046035528183

Epoch 1486/2000: 100%|██████████| 34/34 [00:00<00:00, 64.76it/s]

Epoch 1485 Loss: 0.0023899658117443323

Epoch 1487/2000: 100%|██████████| 34/34 [00:00<00:00, 64.59it/s]

Epoch 1486 Loss: 0.0015628106193616986

Epoch 1488/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 1487 Loss: 0.003446443472057581

Epoch 1489/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1488 Loss: 0.00372708891518414

Epoch 1490/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1489 Loss: 0.004978854209184647

Epoch 1491/2000: 100%|██████████| 34/34 [00:00<00:00, 64.85it/s]

Epoch 1490 Loss: 0.0033182413317263126

Epoch 1492/2000: 100%|██████████| 34/34 [00:00<00:00, 64.74it/s]

Epoch 1491 Loss: 0.026482239365577698

Epoch 1493/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1492 Loss: 0.004671085625886917

Epoch 1494/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 1493 Loss: 0.0009901293087750673

Epoch 1495/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1494 Loss: 0.0031864410266280174

Epoch 1496/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1495 Loss: 0.009247423149645329

Epoch 1497/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1496 Loss: 0.003820189740508795

Epoch 1498/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 1497 Loss: 0.007685688324272633

Epoch 1499/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 1498 Loss: 0.005834757350385189

Epoch 1500/2000: 100%|██████████| 34/34 [00:00<00:00, 62.34it/s]

Epoch 1499 Loss: 0.008829794824123383

Epoch 1501/2000: 100%|██████████| 34/34 [00:00<00:00, 63.56it/s]

Epoch 1500 Loss: 0.003375203348696232

Epoch 1502/2000: 100%|██████████| 34/34 [00:00<00:00, 63.58it/s]

Epoch 1501 Loss: 0.007495747413486242

Epoch 1503/2000: 100%|██████████| 34/34 [00:00<00:00, 63.59it/s]

Epoch 1502 Loss: 0.004152480512857437

Epoch 1504/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1503 Loss: 0.0068125235848128796

Epoch 1505/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 1504 Loss: 0.0019865850917994976

Epoch 1506/2000: 100%|██████████| 34/34 [00:00<00:00, 63.79it/s]

Epoch 1505 Loss: 0.006461099721491337

Epoch 1507/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1506 Loss: 0.0015010175993666053

Epoch 1508/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1507 Loss: 0.003261625301092863

Epoch 1509/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1508 Loss: 0.00290862750262022

Epoch 1510/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 1509 Loss: 0.016612984240055084

Epoch 1511/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1510 Loss: 0.001053257961757481

Epoch 1512/2000: 100%|██████████| 34/34 [00:00<00:00, 63.50it/s]

Epoch 1511 Loss: 0.028702979907393456

Epoch 1513/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1512 Loss: 0.004123279824852943

Epoch 1514/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 1513 Loss: 0.025950895622372627

Epoch 1515/2000: 100%|██████████| 34/34 [00:00<00:00, 63.66it/s]

Epoch 1514 Loss: 0.012347321026027203

Epoch 1516/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1515 Loss: 0.03164107725024223

Epoch 1517/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1516 Loss: 0.009235170669853687

Epoch 1518/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 1517 Loss: 0.0023688010405749083

Epoch 1519/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1518 Loss: 0.0023492607288062572

Epoch 1520/2000: 100%|██████████| 34/34 [00:00<00:00, 63.59it/s]

Epoch 1519 Loss: 0.006569830235093832

Epoch 1521/2000: 100%|██████████| 34/34 [00:00<00:00, 63.44it/s]

Epoch 1520 Loss: 0.002256033243611455

Epoch 1522/2000: 100%|██████████| 34/34 [00:00<00:00, 63.53it/s]

Epoch 1521 Loss: 0.0069719599559903145

Epoch 1523/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1522 Loss: 0.0018557197181507945

Epoch 1524/2000: 100%|██████████| 34/34 [00:00<00:00, 63.48it/s]

Epoch 1523 Loss: 0.03326434642076492

Epoch 1525/2000: 100%|██████████| 34/34 [00:00<00:00, 63.38it/s]

Epoch 1524 Loss: 0.0020387880504131317

Epoch 1526/2000: 100%|██████████| 34/34 [00:00<00:00, 63.69it/s]

Epoch 1525 Loss: 0.025697000324726105

Epoch 1527/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1526 Loss: 0.002644334686920047

Epoch 1528/2000: 100%|██████████| 34/34 [00:00<00:00, 63.94it/s]

Epoch 1527 Loss: 0.01609225384891033

Epoch 1529/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1528 Loss: 0.0035316068679094315

Epoch 1530/2000: 100%|██████████| 34/34 [00:00<00:00, 63.95it/s]

Epoch 1529 Loss: 0.0026413400191813707

Epoch 1531/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1530 Loss: 0.002433227375149727

Epoch 1532/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1531 Loss: 0.007817418314516544

Epoch 1533/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1532 Loss: 0.0024437957908958197

Epoch 1534/2000: 100%|██████████| 34/34 [00:00<00:00, 63.94it/s]

Epoch 1533 Loss: 0.021973703056573868

Epoch 1535/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1534 Loss: 0.001568361185491085

Epoch 1536/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1535 Loss: 0.002213983563706279

Epoch 1537/2000: 100%|██████████| 34/34 [00:00<00:00, 64.01it/s]

Epoch 1536 Loss: 0.007874560542404652

Epoch 1538/2000: 100%|██████████| 34/34 [00:00<00:00, 63.80it/s]

Epoch 1537 Loss: 0.004760107956826687

Epoch 1539/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1538 Loss: 0.0013864291831851006

Epoch 1540/2000: 100%|██████████| 34/34 [00:00<00:00, 63.43it/s]

Epoch 1539 Loss: 0.004296301398426294

Epoch 1541/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 1540 Loss: 0.002970847301185131

Epoch 1542/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1541 Loss: 0.002207743003964424

Epoch 1543/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1542 Loss: 0.0124083636328578

Epoch 1544/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1543 Loss: 0.0027416134253144264

Epoch 1545/2000: 100%|██████████| 34/34 [00:00<00:00, 63.53it/s]

Epoch 1544 Loss: 0.0022011769469827414

Epoch 1546/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1545 Loss: 0.003943318035453558

Epoch 1547/2000: 100%|██████████| 34/34 [00:00<00:00, 63.53it/s]

Epoch 1546 Loss: 0.0008675152785144746

Epoch 1548/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1547 Loss: 0.0010776715353131294

Epoch 1549/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1548 Loss: 0.02152477763593197

Epoch 1550/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1549 Loss: 0.010122870095074177

Epoch 1551/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1550 Loss: 0.004607691429555416

Epoch 1552/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 1551 Loss: 0.0010583762777969241

Epoch 1553/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1552 Loss: 0.03999555483460426

Epoch 1554/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 1553 Loss: 0.023629384115338326

Epoch 1555/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1554 Loss: 0.011723451316356659

Epoch 1556/2000: 100%|██████████| 34/34 [00:00<00:00, 63.65it/s]

Epoch 1555 Loss: 0.001715035759843886

Epoch 1557/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1556 Loss: 0.003991751465946436

Epoch 1558/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1557 Loss: 0.0019288725452497602

Epoch 1559/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1558 Loss: 0.0013123168610036373

Epoch 1560/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1559 Loss: 0.0025947086978703737

Epoch 1561/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1560 Loss: 0.0022712117061018944

Epoch 1562/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1561 Loss: 0.0015433976659551263

Epoch 1563/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1562 Loss: 0.002859266707673669

Epoch 1564/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1563 Loss: 0.0021074945107102394

Epoch 1565/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1564 Loss: 0.0011079444084316492

Epoch 1566/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1565 Loss: 0.0020315132569521666

Epoch 1567/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1566 Loss: 0.006199290510267019

Epoch 1568/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 1567 Loss: 0.03460332751274109

Epoch 1569/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1568 Loss: 0.002624617191031575

Epoch 1570/2000: 100%|██████████| 34/34 [00:00<00:00, 64.01it/s]

Epoch 1569 Loss: 0.015959126874804497

Epoch 1571/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1570 Loss: 0.002048142021521926

Epoch 1572/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1571 Loss: 0.0008283170755021274

Epoch 1573/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1572 Loss: 0.0015487134223803878

Epoch 1574/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1573 Loss: 0.001330028404481709

Epoch 1575/2000: 100%|██████████| 34/34 [00:00<00:00, 63.41it/s]

Epoch 1574 Loss: 0.005178214982151985

Epoch 1576/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1575 Loss: 0.005949095357209444

Epoch 1577/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1576 Loss: 0.001770518603734672

Epoch 1578/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1577 Loss: 0.0009994050487875938

Epoch 1579/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1578 Loss: 0.0019015070283785462

Epoch 1580/2000: 100%|██████████| 34/34 [00:00<00:00, 63.23it/s]

Epoch 1579 Loss: 0.0016945950919762254

Epoch 1581/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1580 Loss: 0.0016221969854086637

Epoch 1582/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1581 Loss: 0.012065903283655643

Epoch 1583/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1582 Loss: 0.0011828674469143152

Epoch 1584/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1583 Loss: 0.010610746219754219

Epoch 1585/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1584 Loss: 0.0068041239865124226

Epoch 1586/2000: 100%|██████████| 34/34 [00:00<00:00, 64.01it/s]

Epoch 1585 Loss: 0.001481792889535427

Epoch 1587/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1586 Loss: 0.0013113103341311216

Epoch 1588/2000: 100%|██████████| 34/34 [00:00<00:00, 63.73it/s]

Epoch 1587 Loss: 0.0017820196226239204

Epoch 1589/2000: 100%|██████████| 34/34 [00:00<00:00, 63.95it/s]

Epoch 1588 Loss: 0.005122946109622717

Epoch 1590/2000: 100%|██████████| 34/34 [00:00<00:00, 63.77it/s]

Epoch 1589 Loss: 0.004010528326034546

Epoch 1591/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1590 Loss: 0.0024267418775707483

Epoch 1592/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1591 Loss: 0.0019133402965962887

Epoch 1593/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1592 Loss: 0.009611624293029308

Epoch 1594/2000: 100%|██████████| 34/34 [00:00<00:00, 63.70it/s]

Epoch 1593 Loss: 0.004765598569065332

Epoch 1595/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1594 Loss: 0.0030420729890465736

Epoch 1596/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1595 Loss: 0.0020500493701547384

Epoch 1597/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1596 Loss: 0.011613400653004646

Epoch 1598/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1597 Loss: 0.006817286368459463

Epoch 1599/2000: 100%|██████████| 34/34 [00:00<00:00, 63.60it/s]

Epoch 1598 Loss: 0.004489688202738762

Epoch 1600/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1599 Loss: 0.028734926134347916

Epoch 1601/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1600 Loss: 0.017576659098267555

Epoch 1602/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 1601 Loss: 0.007294815499335527

Epoch 1603/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1602 Loss: 0.013046721927821636

Epoch 1604/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 1603 Loss: 0.004987812601029873

Epoch 1605/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1604 Loss: 0.0013613576302304864

Epoch 1606/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1605 Loss: 0.005863771308213472

Epoch 1607/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 1606 Loss: 0.0020244454499334097

Epoch 1608/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1607 Loss: 0.001817846903577447

Epoch 1609/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1608 Loss: 0.005689876154065132

Epoch 1610/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1609 Loss: 0.0014972658827900887

Epoch 1611/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1610 Loss: 0.0012728344881907105

Epoch 1612/2000: 100%|██████████| 34/34 [00:00<00:00, 63.66it/s]

Epoch 1611 Loss: 0.003285779617726803

Epoch 1613/2000: 100%|██████████| 34/34 [00:00<00:00, 63.00it/s]

Epoch 1612 Loss: 0.0007163314148783684

Epoch 1614/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1613 Loss: 0.0012890895595774055

Epoch 1615/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1614 Loss: 0.004833670798689127

Epoch 1616/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1615 Loss: 0.0015382777201011777

Epoch 1617/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 1616 Loss: 0.0066148326732218266

Epoch 1618/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1617 Loss: 0.01122190710157156

Epoch 1619/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1618 Loss: 0.004527300596237183

Epoch 1620/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1619 Loss: 0.005641935858875513

Epoch 1621/2000: 100%|██████████| 34/34 [00:00<00:00, 63.92it/s]

Epoch 1620 Loss: 0.003108812728896737

Epoch 1622/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1621 Loss: 0.01615590788424015

Epoch 1623/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 1622 Loss: 0.0015942417085170746

Epoch 1624/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1623 Loss: 0.006707234773784876

Epoch 1625/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1624 Loss: 0.00913033727556467

Epoch 1626/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1625 Loss: 0.00340227666310966

Epoch 1627/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1626 Loss: 0.0026523852720856667

Epoch 1628/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1627 Loss: 0.009139977395534515

Epoch 1629/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1628 Loss: 0.005035347305238247

Epoch 1630/2000: 100%|██████████| 34/34 [00:00<00:00, 63.63it/s]

Epoch 1629 Loss: 0.0021966653876006603

Epoch 1631/2000: 100%|██████████| 34/34 [00:00<00:00, 63.77it/s]

Epoch 1630 Loss: 0.004395442083477974

Epoch 1632/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1631 Loss: 0.01017469260841608

Epoch 1633/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1632 Loss: 0.003949319943785667

Epoch 1634/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1633 Loss: 0.008765689097344875

Epoch 1635/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1634 Loss: 0.0027046625036746264

Epoch 1636/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1635 Loss: 0.001908587757498026

Epoch 1637/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1636 Loss: 0.0021143413614481688

Epoch 1638/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1637 Loss: 0.0013368945801630616

Epoch 1639/2000: 100%|██████████| 34/34 [00:00<00:00, 63.93it/s]

Epoch 1638 Loss: 0.02117921970784664

Epoch 1640/2000: 100%|██████████| 34/34 [00:00<00:00, 63.89it/s]

Epoch 1639 Loss: 0.004937991965562105

Epoch 1641/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1640 Loss: 0.011292582377791405

Epoch 1642/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1641 Loss: 0.003211303846910596

Epoch 1643/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1642 Loss: 0.0035741084720939398

Epoch 1644/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1643 Loss: 0.002079579047858715

Epoch 1645/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1644 Loss: 0.002281312830746174

Epoch 1646/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 1645 Loss: 0.0016266589518636465

Epoch 1647/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1646 Loss: 0.004820786416530609

Epoch 1648/2000: 100%|██████████| 34/34 [00:00<00:00, 63.96it/s]

Epoch 1647 Loss: 0.00864067766815424

Epoch 1649/2000: 100%|██████████| 34/34 [00:00<00:00, 63.75it/s]

Epoch 1648 Loss: 0.010440109297633171

Epoch 1650/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1649 Loss: 0.0029475095216184855

Epoch 1651/2000: 100%|██████████| 34/34 [00:00<00:00, 63.85it/s]

Epoch 1650 Loss: 0.0014467349974438548

Epoch 1652/2000: 100%|██████████| 34/34 [00:00<00:00, 63.48it/s]

Epoch 1651 Loss: 0.025426439940929413

Epoch 1653/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 1652 Loss: 0.011450988240540028

Epoch 1654/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1653 Loss: 0.0020383941009640694

Epoch 1655/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1654 Loss: 0.0009924735641106963

Epoch 1656/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1655 Loss: 0.001999368192628026

Epoch 1657/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1656 Loss: 0.013878010213375092

Epoch 1658/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1657 Loss: 0.0010914774611592293

Epoch 1659/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 1658 Loss: 0.0035792640410363674

Epoch 1660/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1659 Loss: 0.0010843119816854596

Epoch 1661/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1660 Loss: 0.0021222522482275963

Epoch 1662/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1661 Loss: 0.011077324859797955

Epoch 1663/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1662 Loss: 0.008645860478281975

Epoch 1664/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1663 Loss: 0.021574433892965317

Epoch 1665/2000: 100%|██████████| 34/34 [00:00<00:00, 63.78it/s]

Epoch 1664 Loss: 0.00793871097266674

Epoch 1666/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 1665 Loss: 0.0045369332656264305

Epoch 1667/2000: 100%|██████████| 34/34 [00:00<00:00, 63.83it/s]

Epoch 1666 Loss: 0.002008337527513504

Epoch 1668/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1667 Loss: 0.006708015687763691

Epoch 1669/2000: 100%|██████████| 34/34 [00:00<00:00, 63.91it/s]

Epoch 1668 Loss: 0.0045109582133591175

Epoch 1670/2000: 100%|██████████| 34/34 [00:00<00:00, 63.97it/s]

Epoch 1669 Loss: 0.004278542939573526

Epoch 1671/2000: 100%|██████████| 34/34 [00:00<00:00, 63.87it/s]

Epoch 1670 Loss: 0.00749934883788228

Epoch 1672/2000: 100%|██████████| 34/34 [00:00<00:00, 64.05it/s]

Epoch 1671 Loss: 0.01729448325932026

Epoch 1673/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1672 Loss: 0.002769619459286332

Epoch 1674/2000: 100%|██████████| 34/34 [00:00<00:00, 63.71it/s]

Epoch 1673 Loss: 0.005609998945146799

Epoch 1675/2000: 100%|██████████| 34/34 [00:00<00:00, 63.89it/s]

Epoch 1674 Loss: 0.0011582712177187204

Epoch 1676/2000: 100%|██████████| 34/34 [00:00<00:00, 64.02it/s]

Epoch 1675 Loss: 0.0023686380591243505

Epoch 1677/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1676 Loss: 0.0017090735491365194

Epoch 1678/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1677 Loss: 0.01625114493072033

Epoch 1679/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 1678 Loss: 0.001945820520631969

Epoch 1680/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1679 Loss: 0.034240398555994034

Epoch 1681/2000: 100%|██████████| 34/34 [00:00<00:00, 63.81it/s]

Epoch 1680 Loss: 0.014598151668906212

Epoch 1682/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1681 Loss: 0.00119895173702389

Epoch 1683/2000: 100%|██████████| 34/34 [00:00<00:00, 63.72it/s]

Epoch 1682 Loss: 0.038780998438596725

Epoch 1684/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1683 Loss: 0.001301847049035132

Epoch 1685/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1684 Loss: 0.004406689200550318

Epoch 1686/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1685 Loss: 0.03138519451022148

Epoch 1687/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1686 Loss: 0.0007971934392116964

Epoch 1688/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1687 Loss: 0.004658471327275038

Epoch 1689/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1688 Loss: 0.005127042531967163

Epoch 1690/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1689 Loss: 0.03004918247461319

Epoch 1691/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1690 Loss: 0.003239689627662301

Epoch 1692/2000: 100%|██████████| 34/34 [00:00<00:00, 63.84it/s]

Epoch 1691 Loss: 0.0012555174762383103

Epoch 1693/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 1692 Loss: 0.006822618190199137

Epoch 1694/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1693 Loss: 0.020044958218932152

Epoch 1695/2000: 100%|██████████| 34/34 [00:00<00:00, 64.30it/s]

Epoch 1694 Loss: 0.005613415502011776

Epoch 1696/2000: 100%|██████████| 34/34 [00:00<00:00, 62.47it/s]

Epoch 1695 Loss: 0.019209042191505432

Epoch 1697/2000: 100%|██████████| 34/34 [00:00<00:00, 62.40it/s]

Epoch 1696 Loss: 0.015406421385705471

Epoch 1698/2000: 100%|██████████| 34/34 [00:00<00:00, 62.35it/s]

Epoch 1697 Loss: 0.00583117688074708

Epoch 1699/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1698 Loss: 0.002477884292602539

Epoch 1700/2000: 100%|██████████| 34/34 [00:00<00:00, 65.12it/s]

Epoch 1699 Loss: 0.0017089048633351922

Epoch 1701/2000: 100%|██████████| 34/34 [00:00<00:00, 65.20it/s]

Epoch 1700 Loss: 0.0015637536998838186

Epoch 1702/2000: 100%|██████████| 34/34 [00:00<00:00, 65.07it/s]

Epoch 1701 Loss: 0.004645009525120258

Epoch 1703/2000: 100%|██████████| 34/34 [00:00<00:00, 65.08it/s]

Epoch 1702 Loss: 0.029048314318060875

Epoch 1704/2000: 100%|██████████| 34/34 [00:00<00:00, 64.73it/s]

Epoch 1703 Loss: 0.006004232447594404

Epoch 1705/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1704 Loss: 0.001192461233586073

Epoch 1706/2000: 100%|██████████| 34/34 [00:00<00:00, 65.24it/s]

Epoch 1705 Loss: 0.0014628471108153462

Epoch 1707/2000: 100%|██████████| 34/34 [00:00<00:00, 65.13it/s]

Epoch 1706 Loss: 0.003173824632540345

Epoch 1708/2000: 100%|██████████| 34/34 [00:00<00:00, 65.24it/s]

Epoch 1707 Loss: 0.021081658080220222

Epoch 1709/2000: 100%|██████████| 34/34 [00:00<00:00, 65.29it/s]

Epoch 1708 Loss: 0.0032402120996266603

Epoch 1710/2000: 100%|██████████| 34/34 [00:00<00:00, 65.16it/s]

Epoch 1709 Loss: 0.0026749647222459316

Epoch 1711/2000: 100%|██████████| 34/34 [00:00<00:00, 65.29it/s]

Epoch 1710 Loss: 0.0018364388961344957

Epoch 1712/2000: 100%|██████████| 34/34 [00:00<00:00, 64.97it/s]

Epoch 1711 Loss: 0.0031850060913711786

Epoch 1713/2000: 100%|██████████| 34/34 [00:00<00:00, 65.56it/s]

Epoch 1712 Loss: 0.0038920496590435505

Epoch 1714/2000: 100%|██████████| 34/34 [00:00<00:00, 65.29it/s]

Epoch 1713 Loss: 0.007632710505276918

Epoch 1715/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 1714 Loss: 0.0017913763877004385

Epoch 1716/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 1715 Loss: 0.019978394731879234

Epoch 1717/2000: 100%|██████████| 34/34 [00:00<00:00, 65.36it/s]

Epoch 1716 Loss: 0.002701991703361273

Epoch 1718/2000: 100%|██████████| 34/34 [00:00<00:00, 65.28it/s]

Epoch 1717 Loss: 0.001776302233338356

Epoch 1719/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 1718 Loss: 0.03958459943532944

Epoch 1720/2000: 100%|██████████| 34/34 [00:00<00:00, 65.12it/s]

Epoch 1719 Loss: 0.0016412745462730527

Epoch 1721/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1720 Loss: 0.009166707284748554

Epoch 1722/2000: 100%|██████████| 34/34 [00:00<00:00, 64.85it/s]

Epoch 1721 Loss: 0.007268658839166164

Epoch 1723/2000: 100%|██████████| 34/34 [00:00<00:00, 65.01it/s]

Epoch 1722 Loss: 0.004786206874996424

Epoch 1724/2000: 100%|██████████| 34/34 [00:00<00:00, 64.96it/s]

Epoch 1723 Loss: 0.001498478464782238

Epoch 1725/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 1724 Loss: 0.0013142965035513043

Epoch 1726/2000: 100%|██████████| 34/34 [00:00<00:00, 65.29it/s]

Epoch 1725 Loss: 0.0019848672673106194

Epoch 1727/2000: 100%|██████████| 34/34 [00:00<00:00, 65.37it/s]

Epoch 1726 Loss: 0.0019475244916975498

Epoch 1728/2000: 100%|██████████| 34/34 [00:00<00:00, 65.38it/s]

Epoch 1727 Loss: 0.009256049990653992

Epoch 1729/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 1728 Loss: 0.001983199268579483

Epoch 1730/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1729 Loss: 0.029088657349348068

Epoch 1731/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 1730 Loss: 0.001381967682391405

Epoch 1732/2000: 100%|██████████| 34/34 [00:00<00:00, 64.99it/s]

Epoch 1731 Loss: 0.0020926189608871937

Epoch 1733/2000: 100%|██████████| 34/34 [00:00<00:00, 65.01it/s]

Epoch 1732 Loss: 0.035758405923843384

Epoch 1734/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1733 Loss: 0.03750575706362724

Epoch 1735/2000: 100%|██████████| 34/34 [00:00<00:00, 65.14it/s]

Epoch 1734 Loss: 0.003919645212590694

Epoch 1736/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1735 Loss: 0.007168572396039963

Epoch 1737/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1736 Loss: 0.0016515670577064157

Epoch 1738/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1737 Loss: 0.0019908377435058355

Epoch 1739/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1738 Loss: 0.002458094386383891

Epoch 1740/2000: 100%|██████████| 34/34 [00:00<00:00, 65.06it/s]

Epoch 1739 Loss: 0.02638508379459381

Epoch 1741/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 1740 Loss: 0.0018501172307878733

Epoch 1742/2000: 100%|██████████| 34/34 [00:00<00:00, 64.97it/s]

Epoch 1741 Loss: 0.005746455863118172

Epoch 1743/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 1742 Loss: 0.004951590672135353

Epoch 1744/2000: 100%|██████████| 34/34 [00:00<00:00, 64.97it/s]

Epoch 1743 Loss: 0.0016303994925692677

Epoch 1745/2000: 100%|██████████| 34/34 [00:00<00:00, 64.87it/s]

Epoch 1744 Loss: 0.003034659195691347

Epoch 1746/2000: 100%|██████████| 34/34 [00:00<00:00, 64.99it/s]

Epoch 1745 Loss: 0.03194776177406311

Epoch 1747/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 1746 Loss: 0.016291512176394463

Epoch 1748/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 1747 Loss: 0.008187999948859215

Epoch 1749/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 1748 Loss: 0.0065948572009801865

Epoch 1750/2000: 100%|██████████| 34/34 [00:00<00:00, 64.77it/s]

Epoch 1749 Loss: 0.0051144505850970745

Epoch 1751/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 1750 Loss: 0.0036333396565169096

Epoch 1752/2000: 100%|██████████| 34/34 [00:00<00:00, 64.68it/s]

Epoch 1751 Loss: 0.010544748976826668

Epoch 1753/2000: 100%|██████████| 34/34 [00:00<00:00, 64.79it/s]

Epoch 1752 Loss: 0.008205694146454334

Epoch 1754/2000: 100%|██████████| 34/34 [00:00<00:00, 64.75it/s]

Epoch 1753 Loss: 0.0010217569069936872

Epoch 1755/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1754 Loss: 0.006516001652926207

Epoch 1756/2000: 100%|██████████| 34/34 [00:00<00:00, 64.80it/s]

Epoch 1755 Loss: 0.002352719893679023

Epoch 1757/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1756 Loss: 0.002760313218459487

Epoch 1758/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1757 Loss: 0.01038290187716484

Epoch 1759/2000: 100%|██████████| 34/34 [00:00<00:00, 65.03it/s]

Epoch 1758 Loss: 0.014597083441913128

Epoch 1760/2000: 100%|██████████| 34/34 [00:00<00:00, 65.27it/s]

Epoch 1759 Loss: 0.0015566422371193767

Epoch 1761/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 1760 Loss: 0.0032732472755014896

Epoch 1762/2000: 100%|██████████| 34/34 [00:00<00:00, 65.32it/s]

Epoch 1761 Loss: 0.0017896409844979644

Epoch 1763/2000: 100%|██████████| 34/34 [00:00<00:00, 65.24it/s]

Epoch 1762 Loss: 0.0022089513950049877

Epoch 1764/2000: 100%|██████████| 34/34 [00:00<00:00, 65.30it/s]

Epoch 1763 Loss: 0.0025119101628661156

Epoch 1765/2000: 100%|██████████| 34/34 [00:00<00:00, 65.28it/s]

Epoch 1764 Loss: 0.00980269256979227

Epoch 1766/2000: 100%|██████████| 34/34 [00:00<00:00, 65.11it/s]

Epoch 1765 Loss: 0.0022123674862086773

Epoch 1767/2000: 100%|██████████| 34/34 [00:00<00:00, 65.31it/s]

Epoch 1766 Loss: 0.0020646899938583374

Epoch 1768/2000: 100%|██████████| 34/34 [00:00<00:00, 64.65it/s]

Epoch 1767 Loss: 0.006905887275934219

Epoch 1769/2000: 100%|██████████| 34/34 [00:00<00:00, 65.54it/s]

Epoch 1768 Loss: 0.0019105924293398857

Epoch 1770/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1769 Loss: 0.0026626596227288246

Epoch 1771/2000: 100%|██████████| 34/34 [00:00<00:00, 65.02it/s]

Epoch 1770 Loss: 0.012187310494482517

Epoch 1772/2000: 100%|██████████| 34/34 [00:00<00:00, 65.07it/s]

Epoch 1771 Loss: 0.0033555806148797274

Epoch 1773/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1772 Loss: 0.017924878746271133

Epoch 1774/2000: 100%|██████████| 34/34 [00:00<00:00, 65.06it/s]

Epoch 1773 Loss: 0.0028317165561020374

Epoch 1775/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1774 Loss: 0.03361358866095543

Epoch 1776/2000: 100%|██████████| 34/34 [00:00<00:00, 65.08it/s]

Epoch 1775 Loss: 0.0013580229133367538

Epoch 1777/2000: 100%|██████████| 34/34 [00:00<00:00, 65.08it/s]

Epoch 1776 Loss: 0.0015355675714090466

Epoch 1778/2000: 100%|██████████| 34/34 [00:00<00:00, 65.06it/s]

Epoch 1777 Loss: 0.002162350108847022

Epoch 1779/2000: 100%|██████████| 34/34 [00:00<00:00, 65.13it/s]

Epoch 1778 Loss: 0.0053049298003315926

Epoch 1780/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1779 Loss: 0.006115797441452742

Epoch 1781/2000: 100%|██████████| 34/34 [00:00<00:00, 64.67it/s]

Epoch 1780 Loss: 0.002511411439627409

Epoch 1782/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1781 Loss: 0.003388290060684085

Epoch 1783/2000: 100%|██████████| 34/34 [00:00<00:00, 64.92it/s]

Epoch 1782 Loss: 0.0033410543110221624

Epoch 1784/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1783 Loss: 0.00811094231903553

Epoch 1785/2000: 100%|██████████| 34/34 [00:00<00:00, 64.84it/s]

Epoch 1784 Loss: 0.012114224955439568

Epoch 1786/2000: 100%|██████████| 34/34 [00:00<00:00, 64.91it/s]

Epoch 1785 Loss: 0.00926303956657648

Epoch 1787/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1786 Loss: 0.0012022724840790033

Epoch 1788/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1787 Loss: 0.0013681628042832017

Epoch 1789/2000: 100%|██████████| 34/34 [00:00<00:00, 65.06it/s]

Epoch 1788 Loss: 0.002624912653118372

Epoch 1790/2000: 100%|██████████| 34/34 [00:00<00:00, 65.01it/s]

Epoch 1789 Loss: 0.030990393832325935

Epoch 1791/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1790 Loss: 0.002447565784677863

Epoch 1792/2000: 100%|██████████| 34/34 [00:00<00:00, 65.18it/s]

Epoch 1791 Loss: 0.0017129469197243452

Epoch 1793/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 1792 Loss: 0.0017475608037784696

Epoch 1794/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1793 Loss: 0.009017360396683216

Epoch 1795/2000: 100%|██████████| 34/34 [00:00<00:00, 65.10it/s]

Epoch 1794 Loss: 0.003121281275525689

Epoch 1796/2000: 100%|██████████| 34/34 [00:00<00:00, 65.13it/s]

Epoch 1795 Loss: 0.002630827948451042

Epoch 1797/2000: 100%|██████████| 34/34 [00:00<00:00, 65.09it/s]

Epoch 1796 Loss: 0.0040127248503267765

Epoch 1798/2000: 100%|██████████| 34/34 [00:00<00:00, 65.20it/s]

Epoch 1797 Loss: 0.005216645542532206

Epoch 1799/2000: 100%|██████████| 34/34 [00:00<00:00, 64.94it/s]

Epoch 1798 Loss: 0.0017041262472048402

Epoch 1800/2000: 100%|██████████| 34/34 [00:00<00:00, 64.88it/s]

Epoch 1799 Loss: 0.007089172024279833

Epoch 1801/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 1800 Loss: 0.00337157491594553

Epoch 1802/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 1801 Loss: 0.007583738770335913

Epoch 1803/2000: 100%|██████████| 34/34 [00:00<00:00, 64.83it/s]

Epoch 1802 Loss: 0.0049912831746041775

Epoch 1804/2000: 100%|██████████| 34/34 [00:00<00:00, 64.82it/s]

Epoch 1803 Loss: 0.016525903716683388

Epoch 1805/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 1804 Loss: 0.0021022013388574123

Epoch 1806/2000: 100%|██████████| 34/34 [00:00<00:00, 64.91it/s]

Epoch 1805 Loss: 0.0008697934681549668

Epoch 1807/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 1806 Loss: 0.002554515143856406

Epoch 1808/2000: 100%|██████████| 34/34 [00:00<00:00, 65.04it/s]

Epoch 1807 Loss: 0.0015194420702755451

Epoch 1809/2000: 100%|██████████| 34/34 [00:00<00:00, 65.00it/s]

Epoch 1808 Loss: 0.002210823120549321

Epoch 1810/2000: 100%|██████████| 34/34 [00:00<00:00, 64.90it/s]

Epoch 1809 Loss: 0.003256490221247077

Epoch 1811/2000: 100%|██████████| 34/34 [00:00<00:00, 65.07it/s]

Epoch 1810 Loss: 0.002859409898519516

Epoch 1812/2000: 100%|██████████| 34/34 [00:00<00:00, 64.89it/s]

Epoch 1811 Loss: 0.0022848397493362427

Epoch 1813/2000: 100%|██████████| 34/34 [00:00<00:00, 64.93it/s]

Epoch 1812 Loss: 0.009019020944833755

Epoch 1814/2000: 100%|██████████| 34/34 [00:00<00:00, 65.09it/s]

Epoch 1813 Loss: 0.004244029987603426

Epoch 1815/2000: 100%|██████████| 34/34 [00:00<00:00, 65.09it/s]

Epoch 1814 Loss: 0.02478591538965702

Epoch 1816/2000: 100%|██████████| 34/34 [00:00<00:00, 64.98it/s]

Epoch 1815 Loss: 0.00460075493901968

Epoch 1817/2000: 100%|██████████| 34/34 [00:00<00:00, 65.09it/s]

Epoch 1816 Loss: 0.00435482757166028

Epoch 1818/2000: 100%|██████████| 34/34 [00:00<00:00, 65.12it/s]

Epoch 1817 Loss: 0.009548649191856384

Epoch 1819/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 1818 Loss: 0.003123470116406679

Epoch 1820/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 1819 Loss: 0.006224410142749548

Epoch 1821/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 1820 Loss: 0.004006683826446533

Epoch 1822/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1821 Loss: 0.0041258870624005795

Epoch 1823/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1822 Loss: 0.008409027941524982

Epoch 1824/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1823 Loss: 0.0028994858730584383

Epoch 1825/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1824 Loss: 0.0014575995737686753

Epoch 1826/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 1825 Loss: 0.0016909500118345022

Epoch 1827/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1826 Loss: 0.03305693343281746

Epoch 1828/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1827 Loss: 0.008505763486027718

Epoch 1829/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1828 Loss: 0.0019238715758547187

Epoch 1830/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1829 Loss: 0.0018390659242868423

Epoch 1831/2000: 100%|██████████| 34/34 [00:00<00:00, 64.29it/s]

Epoch 1830 Loss: 0.004995510447770357

Epoch 1832/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1831 Loss: 0.0008121655555441976

Epoch 1833/2000: 100%|██████████| 34/34 [00:00<00:00, 64.64it/s]

Epoch 1832 Loss: 0.005179244559258223

Epoch 1834/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1833 Loss: 0.008579079993069172

Epoch 1835/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1834 Loss: 0.002787176985293627

Epoch 1836/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1835 Loss: 0.0012457239208742976

Epoch 1837/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1836 Loss: 0.00432542571797967

Epoch 1838/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1837 Loss: 0.024590227752923965

Epoch 1839/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1838 Loss: 0.0024515693075954914

Epoch 1840/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1839 Loss: 0.004513250198215246

Epoch 1841/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 1840 Loss: 0.0008877025102265179

Epoch 1842/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1841 Loss: 0.0016373617108911276

Epoch 1843/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1842 Loss: 0.010471421293914318

Epoch 1844/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1843 Loss: 0.009079140610992908

Epoch 1845/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1844 Loss: 0.01499111671000719

Epoch 1846/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 1845 Loss: 0.001255230512470007

Epoch 1847/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1846 Loss: 0.005900587420910597

Epoch 1848/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1847 Loss: 0.0016647543525323272

Epoch 1849/2000: 100%|██████████| 34/34 [00:00<00:00, 64.28it/s]

Epoch 1848 Loss: 0.0010269699851050973

Epoch 1850/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1849 Loss: 0.001991679659113288

Epoch 1851/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1850 Loss: 0.002595748985186219

Epoch 1852/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1851 Loss: 0.01712719537317753

Epoch 1853/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1852 Loss: 0.02818792499601841

Epoch 1854/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1853 Loss: 0.006737173069268465

Epoch 1855/2000: 100%|██████████| 34/34 [00:00<00:00, 64.14it/s]

Epoch 1854 Loss: 0.0015292104799300432

Epoch 1856/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1855 Loss: 0.01439409889280796

Epoch 1857/2000: 100%|██████████| 34/34 [00:00<00:00, 64.23it/s]

Epoch 1856 Loss: 0.006723713595420122

Epoch 1858/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1857 Loss: 0.0012844218872487545

Epoch 1859/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1858 Loss: 0.003497116267681122

Epoch 1860/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1859 Loss: 0.005524863954633474

Epoch 1861/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1860 Loss: 0.005373246502131224

Epoch 1862/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1861 Loss: 0.0080138323828578

Epoch 1863/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1862 Loss: 0.005740715190768242

Epoch 1864/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1863 Loss: 0.001975679537281394

Epoch 1865/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 1864 Loss: 0.0046968162059783936

Epoch 1866/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1865 Loss: 0.0014972554054111242

Epoch 1867/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1866 Loss: 0.03896836191415787

Epoch 1868/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1867 Loss: 0.0007348959916271269

Epoch 1869/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 1868 Loss: 0.0012394632212817669

Epoch 1870/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1869 Loss: 0.0009642468066886067

Epoch 1871/2000: 100%|██████████| 34/34 [00:00<00:00, 63.90it/s]

Epoch 1870 Loss: 0.01419234648346901

Epoch 1872/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1871 Loss: 0.0015654939925298095

Epoch 1873/2000: 100%|██████████| 34/34 [00:00<00:00, 64.11it/s]

Epoch 1872 Loss: 0.007026581093668938

Epoch 1874/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1873 Loss: 0.005149363074451685

Epoch 1875/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1874 Loss: 0.0021784587297588587

Epoch 1876/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1875 Loss: 0.007531341630965471

Epoch 1877/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 1876 Loss: 0.00092691695317626

Epoch 1878/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1877 Loss: 0.014792365953326225

Epoch 1879/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1878 Loss: 0.002800628077238798

Epoch 1880/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1879 Loss: 0.0018226058455184102

Epoch 1881/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1880 Loss: 0.0012874597450718284

Epoch 1882/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1881 Loss: 0.011791158467531204

Epoch 1883/2000: 100%|██████████| 34/34 [00:00<00:00, 63.88it/s]

Epoch 1882 Loss: 0.0035441548097878695

Epoch 1884/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1883 Loss: 0.0018666958203539252

Epoch 1885/2000: 100%|██████████| 34/34 [00:00<00:00, 64.16it/s]

Epoch 1884 Loss: 0.007823674939572811

Epoch 1886/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1885 Loss: 0.023503346368670464

Epoch 1887/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1886 Loss: 0.001440561143681407

Epoch 1888/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1887 Loss: 0.00220339628867805

Epoch 1889/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1888 Loss: 0.002580959815531969

Epoch 1890/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1889 Loss: 0.00976934190839529

Epoch 1891/2000: 100%|██████████| 34/34 [00:00<00:00, 64.13it/s]

Epoch 1890 Loss: 0.008023520931601524

Epoch 1892/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 1891 Loss: 0.03527969866991043

Epoch 1893/2000: 100%|██████████| 34/34 [00:00<00:00, 64.20it/s]

Epoch 1892 Loss: 0.0009560338221490383

Epoch 1894/2000: 100%|██████████| 34/34 [00:00<00:00, 64.17it/s]

Epoch 1893 Loss: 0.0011307225795462728

Epoch 1895/2000: 100%|██████████| 34/34 [00:00<00:00, 64.15it/s]

Epoch 1894 Loss: 0.001804996863938868

Epoch 1896/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1895 Loss: 0.011505436152219772

Epoch 1897/2000: 100%|██████████| 34/34 [00:00<00:00, 64.31it/s]

Epoch 1896 Loss: 0.0010499923955649137

Epoch 1898/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1897 Loss: 0.0011525554582476616

Epoch 1899/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1898 Loss: 0.0019388188375160098

Epoch 1900/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1899 Loss: 0.0014243567129597068

Epoch 1901/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1900 Loss: 0.002590066520497203

Epoch 1902/2000: 100%|██████████| 34/34 [00:00<00:00, 64.24it/s]

Epoch 1901 Loss: 0.002069310750812292

Epoch 1903/2000: 100%|██████████| 34/34 [00:00<00:00, 64.22it/s]

Epoch 1902 Loss: 0.005562305450439453

Epoch 1904/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1903 Loss: 0.001825168845243752

Epoch 1905/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1904 Loss: 0.0019815301056951284

Epoch 1906/2000: 100%|██████████| 34/34 [00:00<00:00, 64.41it/s]

Epoch 1905 Loss: 0.003756261430680752

Epoch 1907/2000: 100%|██████████| 34/34 [00:00<00:00, 64.34it/s]

Epoch 1906 Loss: 0.0016560282092541456

Epoch 1908/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1907 Loss: 0.004942482337355614

Epoch 1909/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1908 Loss: 0.0021844455040991306

Epoch 1910/2000: 100%|██████████| 34/34 [00:00<00:00, 64.09it/s]

Epoch 1909 Loss: 0.0032169674523174763

Epoch 1911/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1910 Loss: 0.0071576787158846855

Epoch 1912/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1911 Loss: 0.010504537262022495

Epoch 1913/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1912 Loss: 0.0015843815635889769

Epoch 1914/2000: 100%|██████████| 34/34 [00:00<00:00, 64.55it/s]

Epoch 1913 Loss: 0.0019887564703822136

Epoch 1915/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1914 Loss: 0.03165081888437271

Epoch 1916/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1915 Loss: 0.002597009064629674

Epoch 1917/2000: 100%|██████████| 34/34 [00:00<00:00, 64.41it/s]

Epoch 1916 Loss: 0.005942494608461857

Epoch 1918/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1917 Loss: 0.0050081489607691765

Epoch 1919/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 1918 Loss: 0.018991608172655106

Epoch 1920/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1919 Loss: 0.0018298772629350424

Epoch 1921/2000: 100%|██████████| 34/34 [00:00<00:00, 64.26it/s]

Epoch 1920 Loss: 0.021552428603172302

Epoch 1922/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 1921 Loss: 0.005144999362528324

Epoch 1923/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1922 Loss: 0.0027509666979312897

Epoch 1924/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1923 Loss: 0.003076964756473899

Epoch 1925/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1924 Loss: 0.008649641647934914

Epoch 1926/2000: 100%|██████████| 34/34 [00:00<00:00, 64.54it/s]

Epoch 1925 Loss: 0.0015097230207175016

Epoch 1927/2000: 100%|██████████| 34/34 [00:00<00:00, 64.41it/s]

Epoch 1926 Loss: 0.02747599221765995

Epoch 1928/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1927 Loss: 0.002514004008844495

Epoch 1929/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1928 Loss: 0.003097828011959791

Epoch 1930/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1929 Loss: 0.0007915890892036259

Epoch 1931/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1930 Loss: 0.006078744772821665

Epoch 1932/2000: 100%|██████████| 34/34 [00:00<00:00, 63.41it/s]

Epoch 1931 Loss: 0.00670786714181304

Epoch 1933/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1932 Loss: 0.0027226253878325224

Epoch 1934/2000: 100%|██████████| 34/34 [00:00<00:00, 64.60it/s]

Epoch 1933 Loss: 0.0011145418975502253

Epoch 1935/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1934 Loss: 0.002063910709694028

Epoch 1936/2000: 100%|██████████| 34/34 [00:00<00:00, 63.98it/s]

Epoch 1935 Loss: 0.0013942243531346321

Epoch 1937/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1936 Loss: 0.0011981100542470813

Epoch 1938/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1937 Loss: 0.002908296650275588

Epoch 1939/2000: 100%|██████████| 34/34 [00:00<00:00, 64.18it/s]

Epoch 1938 Loss: 0.0013522885274142027

Epoch 1940/2000: 100%|██████████| 34/34 [00:00<00:00, 64.00it/s]

Epoch 1939 Loss: 0.002481064759194851

Epoch 1941/2000: 100%|██████████| 34/34 [00:00<00:00, 64.39it/s]

Epoch 1940 Loss: 0.0012050720397382975

Epoch 1942/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1941 Loss: 0.0015983069315552711

Epoch 1943/2000: 100%|██████████| 34/34 [00:00<00:00, 64.38it/s]

Epoch 1942 Loss: 0.006270578131079674

Epoch 1944/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1943 Loss: 0.010326310992240906

Epoch 1945/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 1944 Loss: 0.004695219453424215

Epoch 1946/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1945 Loss: 0.021388603374361992

Epoch 1947/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1946 Loss: 0.0011615721741691232

Epoch 1948/2000: 100%|██████████| 34/34 [00:00<00:00, 64.04it/s]

Epoch 1947 Loss: 0.002733952598646283

Epoch 1949/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1948 Loss: 0.0016330929938703775

Epoch 1950/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1949 Loss: 0.009902264922857285

Epoch 1951/2000: 100%|██████████| 34/34 [00:00<00:00, 64.47it/s]

Epoch 1950 Loss: 0.0028928255196660757

Epoch 1952/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1951 Loss: 0.004586915951222181

Epoch 1953/2000: 100%|██████████| 34/34 [00:00<00:00, 64.61it/s]

Epoch 1952 Loss: 0.0015922553138807416

Epoch 1954/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1953 Loss: 0.002773253945633769

Epoch 1955/2000: 100%|██████████| 34/34 [00:00<00:00, 64.49it/s]

Epoch 1954 Loss: 0.005807646084576845

Epoch 1956/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1955 Loss: 0.0017506867880001664

Epoch 1957/2000: 100%|██████████| 34/34 [00:00<00:00, 64.19it/s]

Epoch 1956 Loss: 0.003562720725312829

Epoch 1958/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1957 Loss: 0.003175441874191165

Epoch 1959/2000: 100%|██████████| 34/34 [00:00<00:00, 64.51it/s]

Epoch 1958 Loss: 0.007726704701781273

Epoch 1960/2000: 100%|██████████| 34/34 [00:00<00:00, 64.58it/s]

Epoch 1959 Loss: 0.00200775358825922

Epoch 1961/2000: 100%|██████████| 34/34 [00:00<00:00, 64.44it/s]

Epoch 1960 Loss: 0.027068844065070152

Epoch 1962/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1961 Loss: 0.0037903785705566406

Epoch 1963/2000: 100%|██████████| 34/34 [00:00<00:00, 64.39it/s]

Epoch 1962 Loss: 0.0006090460228733718

Epoch 1964/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1963 Loss: 0.0021530245430767536

Epoch 1965/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1964 Loss: 0.00996310729533434

Epoch 1966/2000: 100%|██████████| 34/34 [00:00<00:00, 64.08it/s]

Epoch 1965 Loss: 0.0049767219461500645

Epoch 1967/2000: 100%|██████████| 34/34 [00:00<00:00, 64.53it/s]

Epoch 1966 Loss: 0.003227067645639181

Epoch 1968/2000: 100%|██████████| 34/34 [00:00<00:00, 64.52it/s]

Epoch 1967 Loss: 0.003263878170400858

Epoch 1969/2000: 100%|██████████| 34/34 [00:00<00:00, 64.48it/s]

Epoch 1968 Loss: 0.0028735711239278316

Epoch 1970/2000: 100%|██████████| 34/34 [00:00<00:00, 64.57it/s]

Epoch 1969 Loss: 0.002396536059677601

Epoch 1971/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1970 Loss: 0.014207733795046806

Epoch 1972/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1971 Loss: 0.025350090116262436

Epoch 1973/2000: 100%|██████████| 34/34 [00:00<00:00, 64.37it/s]

Epoch 1972 Loss: 0.0014531172346323729

Epoch 1974/2000: 100%|██████████| 34/34 [00:00<00:00, 64.50it/s]

Epoch 1973 Loss: 0.022109845653176308

Epoch 1975/2000: 100%|██████████| 34/34 [00:00<00:00, 64.21it/s]

Epoch 1974 Loss: 0.022604839876294136

Epoch 1976/2000: 100%|██████████| 34/34 [00:00<00:00, 64.45it/s]

Epoch 1975 Loss: 0.008535487577319145

Epoch 1977/2000: 100%|██████████| 34/34 [00:00<00:00, 64.56it/s]

Epoch 1976 Loss: 0.003255010349676013

Epoch 1978/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1977 Loss: 0.01456957496702671

Epoch 1979/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 1978 Loss: 0.003256379161030054

Epoch 1980/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1979 Loss: 0.0017724258359521627

Epoch 1981/2000: 100%|██████████| 34/34 [00:00<00:00, 64.42it/s]

Epoch 1980 Loss: 0.003007102059200406

Epoch 1982/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1981 Loss: 0.0013921541394665837

Epoch 1983/2000: 100%|██████████| 34/34 [00:00<00:00, 64.12it/s]

Epoch 1982 Loss: 0.0064737675711512566

Epoch 1984/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1983 Loss: 0.0011659779120236635

Epoch 1985/2000: 100%|██████████| 34/34 [00:00<00:00, 64.46it/s]

Epoch 1984 Loss: 0.001049325685016811

Epoch 1986/2000: 100%|██████████| 34/34 [00:00<00:00, 64.34it/s]

Epoch 1985 Loss: 0.008164972998201847

Epoch 1987/2000: 100%|██████████| 34/34 [00:00<00:00, 64.40it/s]

Epoch 1986 Loss: 0.014761699363589287

Epoch 1988/2000: 100%|██████████| 34/34 [00:00<00:00, 64.36it/s]

Epoch 1987 Loss: 0.0015028729103505611

Epoch 1989/2000: 100%|██████████| 34/34 [00:00<00:00, 64.43it/s]

Epoch 1988 Loss: 0.01205522008240223

Epoch 1990/2000: 100%|██████████| 34/34 [00:00<00:00, 64.27it/s]

Epoch 1989 Loss: 0.002044528257101774

Epoch 1991/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1990 Loss: 0.004086884204298258

Epoch 1992/2000: 100%|██████████| 34/34 [00:00<00:00, 64.35it/s]

Epoch 1991 Loss: 0.0019954522140324116

Epoch 1993/2000: 100%|██████████| 34/34 [00:00<00:00, 64.07it/s]

Epoch 1992 Loss: 0.010884937830269337

Epoch 1994/2000: 100%|██████████| 34/34 [00:00<00:00, 64.25it/s]

Epoch 1993 Loss: 0.021269947290420532

Epoch 1995/2000: 100%|██████████| 34/34 [00:00<00:00, 64.10it/s]

Epoch 1994 Loss: 0.015431786887347698

Epoch 1996/2000: 100%|██████████| 34/34 [00:00<00:00, 64.32it/s]

Epoch 1995 Loss: 0.0009899361757561564

Epoch 1997/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 1996 Loss: 0.0025961820501834154

Epoch 1998/2000: 100%|██████████| 34/34 [00:00<00:00, 63.99it/s]

Epoch 1997 Loss: 0.004435619805008173

Epoch 1999/2000: 100%|██████████| 34/34 [00:00<00:00, 64.03it/s]

Epoch 1998 Loss: 0.0008509450126439333

Epoch 2000/2000: 100%|██████████| 34/34 [00:00<00:00, 64.06it/s]

Epoch 1999 Loss: 0.0009411214850842953

In [25]:
batch = next(iter(test_loader))
x_real_raw = batch["x"].to(device).float()      # [32, 64, 14, 1]
cond_raw = batch["x_cond"].to(device).float()   # [32, 64, 14, 6]
B, W, A, F = x_real_raw.shape

# Mask (Logic: 1=known, 0=predict)
mask = torch.ones_like(x_real_raw)
mask[:, -10:, :, :] = 0  # latest 10 Assets 

# Reshape Flat
# x_real: [32, 64, 14, 1] -> [32, 64, 14]
x_start_flat = x_real_raw.view(B, W, -1)

# cond: [32, 64, 14, 6] -> [32, 64, 84]
cond_flat = cond_raw.view(B, W, -1)

# mask: [32, 64, 14, 1] -> [32, 64, 14]
mask_flat = mask.view(B, W, -1)

print(f"x_start_flat: {x_start_flat.shape}\ncond_flat: {cond_flat.shape}\nmask_flat: {mask_flat.shape}")

# Inpaint
diffusion.eval()
with torch.no_grad():
    inpainted_flat = diffusion.sample_inpaint(
        x_cond=cond_flat,
        x_start=x_start_flat,
        mask=mask_flat
    )

# Reshape
# [32, 64, 14] -> [32, 64, 14, 1]
inpainted_final = inpainted_flat.view(B, W, A, F)

print("Inpaint Finished!")

x_start_flat: torch.Size([32, 64, 14])
cond_flat: torch.Size([32, 64, 84])
mask_flat: torch.Size([32, 64, 14])
Inpaint Finished!

In [26]:
inpainted_final.shape

torch.Size([32, 64, 14, 1])