# Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import logging
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
import talib as ta

from torch import optim
from torch.utils.data import DataLoader, Dataset, TensorDataset, random_split
from tqdm import tqdm

from numpy.lib.stride_tricks import sliding_window_view
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from torch.optim import AdamW
from utils import scale, inverse_scale, inspect
from utils.paths import CHECKPOINTS_DIR
from pypfopt import risk_models, expected_returns, plotting, EfficientFrontier

In [2]:
from config import *
from entities import *
from strategies import *
from datasets import *
from engine import Engine
from models import DiffusionTransformer, Diffusion

# Setup

In [3]:
logging.basicConfig(level=logging.DEBUG)
logging.getLogger('matplotlib').setLevel(logging.WARNING)

In [4]:
cfg = TrainConfig(epochs=1000, window_size=64)
window_size = cfg.window_size
device = cfg.device
batch_size = cfg.batch_size
epochs = cfg.epochs
sim_steps = cfg.steps_to_sim
num_sims = cfg.num_sims

# Optimizer
weight_decay = cfg.optimizer.weight_decay
lr = cfg.optimizer.lr

time_range = {
    'start_date': '2021-01-01',
    'end_date': '2024-12-31'
}

ddpm = {
    'timesteps': int(1000),
    'beta_start': 0.0001,
    'beta_end': 0.02
}

ddpm_transformer = {
    'n_features': 1,
    'n_cond': 10,
    'window_size': window_size,
    'd_model': 64,
    'nhead': 4,
    'num_layers': 16,
    'dim_feedforward': 512,
    'dropout': 0.1
}

# Data [N, W, A, F]
**[N, T, A, F]** means: 
* **N**: Num of Window or Num of Batch
* **W**: Window
* **A**: Assets
* **F**: Features or Channels

In [5]:
def time_range_info(df):
    info = (df.index.min(), df.index.max())
    print(f"Data range: {info[0]} to {info[1]}")
    
    duration = df.index.max() - df.index.min()
    print(f"Total duration: {duration}")

def time_range_mask(df, start_date, end_date):
    mask = (df.index >= start_date) & (df.index <= end_date)
    return mask

In [6]:
symbols = ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO']
freq = "1d"

# Basket
basket = Basket(symbols=symbols)
basket.load_all_assets(freq=freq)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

DEBUG:entities.basket:Initialized Asset Basket: ['AAPL', 'TSLA', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'GOOG', 'META', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD', 'CSCO'] with 0 assets which loaded.
INFO:entities.basket:Starting batch load for 14 symbols...
DEBUG:entities.basket:Attempting to load AAPL...
DEBUG:entities.asset:Initialized Asset: AAPL with 2724 rows.
INFO:entities.basket:Successfully loaded AAPL (2724 rows).
DEBUG:entities.basket:Attempting to load TSLA...
DEBUG:entities.asset:Initialized Asset: TSLA with 2760 rows.
INFO:entities.basket:Successfully loaded TSLA (2760 rows).
DEBUG:entities.basket:Attempting to load MSFT...
DEBUG:entities.asset:Initialized Asset: MSFT with 2724 rows.
INFO:entities.basket:Successfully loaded MSFT (2724 rows).
DEBUG:entities.basket:Attempting to load NVDA...
DEBUG:entities.asset:Initialized Asset: NVDA with 2724 rows.
INFO:entities.basket:Successfully loaded NVDA (2724 rows).
DEBUG:entities.basket:Attempting to load GOOGL...
DEBUG:entities.asset:Initialized Asset: GOOGL with 2760 rows.
INFO:entities.basket:Successfully loaded GOOGL (2760 rows).
DEBUG:entities.basket:Attempting to load AMZN...
DEBUG:entities.asset:Initialized Asset: AMZN with 2760 rows.
INFO:entities.basket:Successfully loaded AMZN (2760 rows).
DEBUG:entities.basket:Attempting to load GOOG...
DEBUG:entities.asset:Initialized Asset: GOOG with 1464 rows.
INFO:entities.basket:Successfully loaded GOOG (1464 rows).
DEBUG:entities.basket:Attempting to load META...
DEBUG:entities.asset:Initialized Asset: META with 2760 rows.
INFO:entities.basket:Successfully loaded META (2760 rows).
DEBUG:entities.basket:Attempting to load AVGO...
DEBUG:entities.asset:Initialized Asset: AVGO with 2724 rows.
INFO:entities.basket:Successfully loaded AVGO (2724 rows).
DEBUG:entities.basket:Attempting to load ORCL...
DEBUG:entities.asset:Initialized Asset: ORCL with 2724 rows.
INFO:entities.basket:Successfully loaded ORCL (2724 rows).
DEBUG:entities.basket:Attempting to load CRM...
DEBUG:entities.asset:Initialized Asset: CRM with 2724 rows.
INFO:entities.basket:Successfully loaded CRM (2724 rows).
DEBUG:entities.basket:Attempting to load ADBE...
DEBUG:entities.asset:Initialized Asset: ADBE with 2724 rows.
INFO:entities.basket:Successfully loaded ADBE (2724 rows).
DEBUG:entities.basket:Attempting to load AMD...
DEBUG:entities.asset:Initialized Asset: AMD with 2724 rows.
INFO:entities.basket:Successfully loaded AMD (2724 rows).
DEBUG:entities.basket:Attempting to load CSCO...
DEBUG:entities.asset:Initialized Asset: CSCO with 2724 rows.
INFO:entities.basket:Successfully loaded CSCO (2724 rows).
INFO:entities.basket:Batch load complete. Success: 14/14. Total assets in basket: 14

Basket data shape: (2760, 70)

                 AAPL                                                \
                Close       High        Low       Open       Volume
Date
2015-01-02  24.261047  24.729270  23.821672  24.718174  212818400.0
2015-01-05  23.577574  24.110150  23.391173  24.030263  257142000.0
2015-01-06  23.579794  23.839424  23.218085  23.641928  263188400.0
2015-01-07  23.910433  24.010290  23.677430  23.788384  160423600.0
2015-01-08  24.829119  24.886815  24.121236  24.238848  237458000.0

                 TSLA                                             ...   AMD  \
                Close       High        Low       Open    Volume  ... Close
Date                                                              ...
2015-01-02  14.620667  14.883333  14.217333  14.858000  71466000  ...  2.67
2015-01-05  14.006000  14.433333  13.810667  14.303333  80527500  ...  2.66
2015-01-06  14.085333  14.280000  13.614000  14.004000  93928500  ...  2.63
2015-01-07  14.063333  14.318667  13.985333  14.223333  44526000  ...  2.58
2015-01-08  14.041333  14.253333  14.000667  14.187333  51637500  ...  2.61

                                               CSCO                        \
            High   Low  Open      Volume      Close       High        Low
Date
2015-01-02  2.67  2.67  2.67         0.0  19.815605  20.181631  19.650534
2015-01-05  2.70  2.64  2.67   8878200.0  19.420874  19.700776  19.377812
2015-01-06  2.66  2.55  2.65  13912500.0  19.413698  19.865848  19.406522
2015-01-07  2.65  2.54  2.63  12377600.0  19.593126  19.664896  19.363463
2015-01-08  2.65  2.56  2.59  11136600.0  19.743843  20.160107  19.715135


                 Open      Volume
Date
2015-01-02  19.995029  22926500.0
2015-01-05  19.607475  29460600.0
2015-01-06  19.478291  47297600.0
2015-01-07  19.478295  27570800.0
2015-01-08  19.765374  40907000.0

[5 rows x 70 columns]

### Time Range Custom

In [7]:
time_range_info(basket.data)

for symbol, asset in basket.assets.items():
    mask = time_range_mask(asset.data, time_range['start_date'], time_range['end_date'])
    asset.data = asset.data[mask]

time_range_info(basket.data)

Data range: 2015-01-02 00:00:00 to 2025-12-22 00:00:00
Total duration: 4007 days 00:00:00
Data range: 2021-01-04 00:00:00 to 2024-12-31 00:00:00
Total duration: 1457 days 00:00:00

## Features/Channels ($F$)
1. Find Joint Distribution $F_{\text{date\ A}} \cap F_{\text{date\ B}}$ with intersection
2. Select $F$ to norm as Return values

In [8]:
targets = ["Close"]
features = basket.get_unique_features()
print(f"Features:\t{features}\nTargets:\t{targets}")

Features:	['Close', 'High', 'Low', 'Open', 'Volume']
Targets:	['Close']

In [9]:
print(f"Basket data shape before Joint: {basket.data.shape}")

joint_strategy = IntersectionStrategy()
basket.align(joint_strategy)

print(f"Basket data shape after Joint: {basket.data.shape}")

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 1005 rows
DEBUG:entities.basket:Aligned data shape: (1005, 70)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 1005)

Basket data shape before Joint: (1005, 70)
Basket data shape after Joint: (1005, 70)

In [10]:
basket.to_returns(features=targets, log=True, keep=False)
targets = basket.get_keyword_features("Returns")
features = basket.get_unique_features()

print(f"Features:\t{features}\nTargets:\t{targets}")
basket.data.head(5)

DEBUG:entities.asset:AAPL converted to Returns (log=True)
DEBUG:entities.asset:TSLA converted to Returns (log=True)
DEBUG:entities.asset:MSFT converted to Returns (log=True)
DEBUG:entities.asset:NVDA converted to Returns (log=True)
DEBUG:entities.asset:GOOGL converted to Returns (log=True)
DEBUG:entities.asset:AMZN converted to Returns (log=True)
DEBUG:entities.asset:GOOG converted to Returns (log=True)
DEBUG:entities.asset:META converted to Returns (log=True)
DEBUG:entities.asset:AVGO converted to Returns (log=True)
DEBUG:entities.asset:ORCL converted to Returns (log=True)
DEBUG:entities.asset:CRM converted to Returns (log=True)
DEBUG:entities.asset:ADBE converted to Returns (log=True)
DEBUG:entities.asset:AMD converted to Returns (log=True)
DEBUG:entities.asset:CSCO converted to Returns (log=True)

Features:	['Close_Log_Returns', 'High', 'Low', 'Open', 'Volume']
Targets:	{'Close_Log_Returns'}

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                  TSLA                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  246.946671  239.733337  241.220001   96735600          0.007291
2021-01-06  258.000000  249.699997  252.830002  134100000          0.027995
2021-01-07  272.329987  258.399994  259.209991  154496700          0.076448
2021-01-08  294.829987  279.463318  285.333344  225166500          0.075481
2021-01-11  284.809998  267.873322  283.133331  177904800         -0.081442

            ...        AMD                                                    \
            ...       High        Low       Open    Volume Close_Log_Returns
Date        ...
2021-01-05  ...  93.209999  91.410004  92.099998  34208000          0.005079
2021-01-06  ...  92.279999  89.459999  91.620003  51911700         -0.026654
2021-01-07  ...  95.510002  91.199997  91.330002  42897200          0.052090
2021-01-08  ...  96.400002  93.269997  95.980003  39816400         -0.006114
2021-01-11  ...  99.230003  93.760002  94.029999  48600200          0.027839

                 CSCO
                 High        Low       Open    Volume Close_Log_Returns
Date
2021-01-05  38.335017  37.734811  37.995770  17763700          0.000455
2021-01-06  39.030909  38.178440  38.387210  21823100          0.009505
2021-01-07  39.239677  38.422000  38.448099  18218800          0.012534
2021-01-08  39.500638  38.491593  38.691662  20936300          0.002222
2021-01-11  39.970367  39.161391  39.274475  25058200          0.006636

[5 rows x 70 columns]

### Add Indicators as Features ($F$)

In [11]:
# Indicator
time_prd = 20
fast_prd, slow_prd, signal_prd = 12, 26, 9

for symbol, asset in basket.assets.items():
    df = asset.data 
    
    for target in targets:
        s = df[target]
        
        df[f"SMA_{time_prd} {target}"] = ta.SMA(s, timeperiod=time_prd)
        df[f"EMA_{time_prd} {target}"] = ta.EMA(s, timeperiod=time_prd)
        df[f"RSI_{time_prd} {target}"] = ta.RSI(s, timeperiod=time_prd)
        
        macd, signal, hist = ta.MACD(s, fastperiod=fast_prd, slowperiod=slow_prd, signalperiod=signal_prd)
        df[f"MACD {target}"] = macd
        df[f"MACD_Sig {target}"] = signal
        df[f"MACD_Hist {target}"] = hist

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

Basket data shape: (1004, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-01-05  128.366929  125.141666  125.589894   97664900          0.012288
2021-01-06  127.694587  123.144152  124.449847  155088000         -0.034241
2021-01-07  128.259768  124.586290  125.073488  109578200          0.033554
2021-01-08  129.234127  126.895568  129.039236  105158200          0.008594
2021-01-11  126.837115  125.209876  125.882211  100384500         -0.023523

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-01-05                      NaN                    NaN
2021-01-06                      NaN                    NaN
2021-01-07                      NaN                    NaN
2021-01-08                      NaN                    NaN
2021-01-11                      NaN                    NaN

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-01-05                        NaN  ...  37.734811  37.995770  17763700
2021-01-06                        NaN  ...  38.178440  38.387210  21823100
2021-01-07                        NaN  ...  38.422000  38.448099  18218800
2021-01-08                        NaN  ...  38.491593  38.691662  20936300
2021-01-11                        NaN  ...  39.161391  39.274475  25058200

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-01-05          0.000455                      NaN
2021-01-06          0.009505                      NaN
2021-01-07          0.012534                      NaN
2021-01-08          0.002222                      NaN
2021-01-11          0.006636                      NaN

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-01-05                      NaN                      NaN
2021-01-06                      NaN                      NaN
2021-01-07                      NaN                      NaN
2021-01-08                      NaN                      NaN
2021-01-11                      NaN                      NaN

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-01-05                    NaN                        NaN
2021-01-06                    NaN                        NaN
2021-01-07                    NaN                        NaN
2021-01-08                    NaN                        NaN
2021-01-11                    NaN                        NaN


           MACD_Hist Close_Log_Returns
Date
2021-01-05                         NaN
2021-01-06                         NaN
2021-01-07                         NaN
2021-01-08                         NaN
2021-01-11                         NaN

[5 rows x 154 columns]

In [12]:
basket.align(joint_strategy)

print(f"Basket data shape: {basket.data.shape}")
basket.data.head(5)

INFO:strategies.concrete:Aligned: 14 orig -> 14 clean assets -> 971 rows
DEBUG:entities.basket:Aligned data shape: (971, 154)
INFO:entities.basket:Assets updated in-place to aligned index (Length: 971)

Basket data shape: (971, 154)

                  AAPL                                                       \
                  High         Low        Open     Volume Close_Log_Returns
Date
2021-02-23  123.650197  115.531109  120.771437  158273000         -0.001112
2021-02-24  122.527972  119.278390  121.922948  111039900         -0.004060
2021-02-25  123.406232  117.629191  121.669217  148199500         -0.035402
2021-02-26  121.835107  118.273246  119.629680  164560400          0.002229
2021-03-01  124.840766  119.824887  120.761704  116307900          0.052452

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-23                -0.006281                -0.004764
2021-02-24                -0.006568                -0.004697
2021-02-25                -0.007952                -0.007621
2021-02-26                -0.006060                -0.006683
2021-03-01                -0.001531                -0.001051

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-23                49.443327              -0.005006
2021-02-24                49.042061              -0.004288
2021-02-25                44.959599              -0.006177
2021-02-26                50.199121              -0.004584
2021-03-01                56.073523               0.000722

                                       ...       CSCO                       \
           MACD_Sig Close_Log_Returns  ...        Low       Open    Volume
Date                                   ...
2021-02-23                  -0.005451  ...  39.230971  39.370149  19714900
2021-02-24                  -0.005218  ...  39.178786  39.352760  17823600
2021-02-25                  -0.005410  ...  39.352752  39.657204  21916700
2021-02-26                  -0.005245  ...  38.935217  39.648511  22144900
2021-03-01                  -0.004051  ...  39.335356  39.335356  17394100

                                                       \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-23          0.001759                 0.000530
2021-02-24          0.005041                 0.000527
2021-02-25         -0.004822                -0.000197
2021-02-26         -0.014382                -0.000521
2021-03-01          0.023131                 0.001481

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-23                -0.001497                50.527952
2021-02-24                -0.000874                51.224838
2021-02-25                -0.001250                49.039717
2021-02-26                -0.002501                46.994221
2021-03-01                -0.000060                54.783902

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-23              -0.001681                  -0.000759
2021-02-24              -0.000967                  -0.000801
2021-02-25              -0.001184                  -0.000877
2021-02-26              -0.002102                  -0.001122
2021-03-01               0.000194                  -0.000859


           MACD_Hist Close_Log_Returns
Date
2021-02-23                   -0.000923
2021-02-24                   -0.000167
2021-02-25                   -0.000307
2021-02-26                   -0.000980
2021-03-01                    0.001053

[5 rows x 154 columns]

### Filter only Target Features ($F_{target} $)

In [13]:
targets = basket.get_keyword_features("Returns")
print(f"Targets: {targets}")


for symbol, asset in basket.assets.items():
    mask = asset.data.columns.isin(targets)
    asset.data = asset.data.loc[:, mask]

print(f"Basket shape: {basket.data.shape}")
basket.data.head(5)

Targets: {'RSI_20 Close_Log_Returns', 'MACD_Hist Close_Log_Returns', 'MACD_Sig Close_Log_Returns', 'SMA_20 Close_Log_Returns', 'EMA_20 Close_Log_Returns', 'MACD Close_Log_Returns', 'Close_Log_Returns'}
Basket shape: (971, 98)

                        AAPL                           \
           Close_Log_Returns SMA_20 Close_Log_Returns
Date
2021-02-23         -0.001112                -0.006281
2021-02-24         -0.004060                -0.006568
2021-02-25         -0.035402                -0.007952
2021-02-26          0.002229                -0.006060
2021-03-01          0.052452                -0.001531

                                                              \
           EMA_20 Close_Log_Returns RSI_20 Close_Log_Returns
Date
2021-02-23                -0.004764                49.443327
2021-02-24                -0.004697                49.042061
2021-02-25                -0.007621                44.959599
2021-02-26                -0.006683                50.199121
2021-03-01                -0.001051                56.073523

                                                              \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-23              -0.005006                  -0.005451
2021-02-24              -0.004288                  -0.005218
2021-02-25              -0.006177                  -0.005410
2021-02-26              -0.004584                  -0.005245
2021-03-01               0.000722                  -0.004051

                                                    TSLA  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-23                    0.000445         -0.022161
2021-02-24                    0.000930          0.059954
2021-02-25                   -0.000767         -0.084024
2021-02-26                    0.000661         -0.009899
2021-03-01                    0.004773          0.061615

                                                              ...  \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns  ...
Date                                                          ...
2021-02-23                -0.011570                -0.012856  ...
2021-02-24                -0.008703                -0.005921  ...
2021-02-25                -0.011820                -0.013360  ...
2021-02-26                -0.010625                -0.013030  ...
2021-03-01                -0.004971                -0.005921  ...

                              AMD                             \
           MACD Close_Log_Returns MACD_Sig Close_Log_Returns
Date
2021-02-23              -0.004678                  -0.002595
2021-02-24              -0.001476                  -0.002371
2021-02-25              -0.005253                  -0.002947
2021-02-26              -0.001896                  -0.002737
2021-03-01               0.000513                  -0.002087

                                                    CSCO  \
           MACD_Hist Close_Log_Returns Close_Log_Returns
Date
2021-02-23                   -0.002084          0.001759
2021-02-24                    0.000895          0.005041
2021-02-25                   -0.002306         -0.004822
2021-02-26                    0.000841         -0.014382
2021-03-01                    0.002600          0.023131

                                                              \
           SMA_20 Close_Log_Returns EMA_20 Close_Log_Returns
Date
2021-02-23                 0.000530                -0.001497
2021-02-24                 0.000527                -0.000874
2021-02-25                -0.000197                -0.001250
2021-02-26                -0.000521                -0.002501
2021-03-01                 0.001481                -0.000060

                                                            \
           RSI_20 Close_Log_Returns MACD Close_Log_Returns
Date
2021-02-23                50.527952              -0.001681
2021-02-24                51.224838              -0.000967
2021-02-25                49.039717              -0.001184
2021-02-26                46.994221              -0.002102
2021-03-01                54.783902               0.000194


           MACD_Sig Close_Log_Returns MACD_Hist Close_Log_Returns
Date
2021-02-23                  -0.000759                   -0.000923
2021-02-24                  -0.000801                   -0.000167
2021-02-25                  -0.000877                   -0.000307
2021-02-26                  -0.001122                   -0.000980
2021-03-01                  -0.000859                    0.001053

[5 rows x 98 columns]

## Dataset & Dataloader

In [14]:
n_obs = len(basket.data)
n_assets = basket.data.columns.levels[0].size
n_features = basket.data.columns.levels[1].size

print(n_obs, n_assets, n_features)

basket_np = basket.data.values.reshape(n_obs, n_assets, n_features)
basket_np.shape

971 14 7

(971, 14, 7)

### Ratio Dataset

In [15]:
ratios = [0.8, 0.1, 0.1]
total_count = len(basket_np)
train_count = int(total_count * ratios[0])
val_count = int(total_count * ratios[1])
test_count = total_count - train_count - val_count

print(f"Ratios DS\nTrain:\t{train_count}\nVal:\t{val_count}\nTest:\t{test_count}\nTotal:\t{total_count}")

Ratios DS
Train:	776
Val:	97
Test:	98
Total:	971

In [16]:
end_val = train_count + val_count

# Ratios
train_part = basket_np[:train_count]
val_part = basket_np[train_count:end_val]
test_part = basket_np[end_val:]

print(f"Train: {train_part.shape}\nVal: {val_part.shape}\nTest:{test_part.shape}")

Train: (776, 14, 7)
Val: (97, 14, 7)
Test:(98, 14, 7)

### Scale Dataset

In [17]:
def scale(part: np.ndarray, scaler) -> np.ndarray:
    T, A, F = part.shape
    part_2d = part.reshape(-1, F)

    # print(f"2D Part: {part_2d.shape}")

    scaled_part = scaler.transform(part_2d).reshape(T, A, F)
    return scaled_part.astype(np.float32)

def inverse_scale(scaled_part: np.ndarray, scaler) -> np.ndarray:
    original_shape = scaled_part.shape
    F = original_shape[-1]

    part_2d = scaled_part.reshape(-1, F)
    
    unscaled_2d = scaler.inverse_transform(part_2d)
    return unscaled_2d.reshape(original_shape).astype(np.float32)

def inverse_scale_with_cond(x, x_cond, scaler):
    if torch.is_tensor(x):
        x = x.cpu().numpy()
    if torch.is_tensor(x_cond):
        x_cond = x_cond.cpu().numpy()
        
    assert x.shape[:-1] == x_cond.shape[:-1], f"Shape Mismatch: x {x.shape} vs cond {x_cond.shape}"
    
    # [..., 1] + [..., 6] -> [..., 7]
    full_features = np.concatenate([x, x_cond], axis=-1)

    original_shape = full_features.shape
    total_features = original_shape[-1]

    flat_data = full_features.reshape(-1, total_features)

    unscaled_flat = scaler.inverse_transform(flat_data)

    unscaled_full = unscaled_flat.reshape(original_shape)
    unscaled_price = unscaled_full[..., 0:1]
    return unscaled_price.astype(np.float32)

In [18]:
def inspect_data(data, name):
    if isinstance(data, torch.Tensor):
        data = data.detach().cpu().numpy()

    _min = np.min(data)
    _max = np.max(data)
    _mean = np.mean(data)
    _std = np.std(data)
    
    print(f"--- Inspecting: {name} ---")
    print("-" * 36)
    print(f"Shape: {data.shape}")
    print(f"Min:   {_min:.4f}")
    print(f"Max:   {_max:.4f}")
    print(f"Mean:  {_mean:.4f}")
    print(f"Std:   {_std:.4f}")
    print("-" * 36)
    return _min, _max, _mean, _std

In [19]:
# scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = StandardScaler()

# Require 2D Numpy Array
T, A, F = train_part.shape
scaler.fit(train_part.reshape(-1, F))

scaled_train_part = scale(train_part, scaler)
scaled_val_part = scale(val_part, scaler)
scaled_test_part = scale(test_part, scaler)

inspect_data(scaled_train_part, "Scaled Train Part")
inspect_data(scaled_val_part, "Scaled Val Part")
inspect_data(scaled_test_part, "Scaled Test Part")
print(f"Train:\t{scaled_train_part.shape}\nVal:\t{scaled_val_part.shape}\nTest:\t{scaled_test_part.shape}")

--- Inspecting: Scaled Train Part ---
------------------------------------
Shape: (776, 14, 7)
Min:   -12.4914
Max:   8.8454
Mean:  -0.0000
Std:   1.0000
------------------------------------
--- Inspecting: Scaled Val Part ---
------------------------------------
Shape: (97, 14, 7)
Min:   -8.9713
Max:   6.1577
Mean:  -0.0453
Std:   0.9932
------------------------------------
--- Inspecting: Scaled Test Part ---
------------------------------------
Shape: (98, 14, 7)
Min:   -6.1881
Max:   8.8660
Mean:  0.1184
Std:   0.9507
------------------------------------
Train:	(776, 14, 7)
Val:	(97, 14, 7)
Test:	(98, 14, 7)

### Dataloader

In [20]:
train_ds = MarketDataset(scaled_train_part, window_size=window_size)
val_ds = MarketDataset(scaled_val_part, window_size=window_size)
test_ds = MarketDataset(scaled_test_part, window_size=window_size)

print(f"Num of Windows\nTrain DS: {len(train_ds)}, Val Ds: {len(val_ds)}, Test DS: {len(test_ds)}\n")
print(f"A sample shape from Train DS\n\tx: {train_ds[0]['x'].shape},\n\tx_cond: {train_ds[0]['x_cond'].shape}")

Num of Windows
Train DS: 713, Val Ds: 34, Test DS: 35

A sample shape from Train DS
	x: (64, 14, 1),
	x_cond: (64, 14, 6)

In [21]:
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_ds, batch_size=1, shuffle=False)

batch = next(iter(train_loader))
print(len(train_loader))
print(batch["x"].shape)
print(batch["x_cond"].shape)

90
torch.Size([8, 64, 14, 1])
torch.Size([8, 64, 14, 6])

# Model, Engine
Use *Condition DDPM*

In [22]:
# n_window mean batch size
n_window, window, n_assets, n_features = batch["x"].shape
n_window, window, n_assets, n_conds = batch["x_cond"].shape
ddpm_transformer['n_cond'] = n_conds

print(n_assets, n_features, n_conds)

input_channels = n_assets * n_features
cond_channels = n_assets * n_conds
print(input_channels, cond_channels)

14 1 6
14 84

In [23]:
model = DiffusionTransformer(
    n_features=input_channels,
    n_cond=cond_channels,        
    window_size=window_size,             
    d_model=ddpm_transformer['d_model'],                
    nhead=ddpm_transformer['nhead'],
    num_layers=ddpm_transformer['num_layers'],
    dim_feedforward=ddpm_transformer['dim_feedforward'],
    dropout=ddpm_transformer['dropout']
).to(device)

/home/narodom.y@FUSION.LAB/.conda/envs/tsgenai/lib/python3.11/site-packages/torch/cuda/__init__.py:716: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

In [24]:
diffusion = Diffusion(model, timesteps=ddpm['timesteps'], beta_start=ddpm['beta_start'], beta_end=ddpm['beta_end']).to(device)

In [25]:
optimizer = AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

In [26]:
engine = Engine(
    train_dataloader=train_loader,
    val_dataloader=val_loader,
    model=diffusion,
    scaler=scaler,
    optimizer=optimizer,
    device=device,
    file_name=f"ddpm_transformer_d{ddpm_transformer['d_model']}_l{ddpm_transformer['num_layers']}",
)

In [ ]:
engine.fit(epochs)

INFO:engine.trainer:Engine started Training for 1000 epochs on cuda...
Epoch 1/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.86it/s, loss=0.989]
Epoch 1/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 84.92it/s]

End of Epoch 1 | Train Loss: 1.021581 | Val Loss: 1.001317
New Best Model Saved (Val Loss: 1.001317)

Epoch 2/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.84it/s, loss=0.988]
Epoch 2/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.70it/s]

End of Epoch 2 | Train Loss: 1.007693 | Val Loss: 0.984924
New Best Model Saved (Val Loss: 0.984924)

Epoch 3/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.80it/s, loss=0.936]
Epoch 3/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.42it/s]

End of Epoch 3 | Train Loss: 0.950984 | Val Loss: 0.865568
New Best Model Saved (Val Loss: 0.865568)

Epoch 4/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.645]
Epoch 4/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.24it/s]

End of Epoch 4 | Train Loss: 0.791421 | Val Loss: 0.685206
New Best Model Saved (Val Loss: 0.685206)

Epoch 5/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.487]
Epoch 5/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.47it/s]

End of Epoch 5 | Train Loss: 0.653499 | Val Loss: 0.601201
New Best Model Saved (Val Loss: 0.601201)

Epoch 6/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.829]
Epoch 6/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.70it/s]

End of Epoch 6 | Train Loss: 0.566285 | Val Loss: 0.438337
New Best Model Saved (Val Loss: 0.438337)

Epoch 7/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.299]
Epoch 7/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.92it/s]

End of Epoch 7 | Train Loss: 0.480316 | Val Loss: 0.435027
New Best Model Saved (Val Loss: 0.435027)

Epoch 8/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=1.05]
Epoch 8/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.05it/s]

End of Epoch 8 | Train Loss: 0.428749 | Val Loss: 0.343555
New Best Model Saved (Val Loss: 0.343555)

Epoch 9/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.977]
Epoch 9/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.28it/s]

End of Epoch 9 | Train Loss: 0.384512 | Val Loss: 0.411399

Epoch 10/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.677]
Epoch 10/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.32it/s]

End of Epoch 10 | Train Loss: 0.349921 | Val Loss: 0.235767
New Best Model Saved (Val Loss: 0.235767)

Epoch 11/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.81it/s, loss=0.23]
Epoch 11/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.88it/s]

End of Epoch 11 | Train Loss: 0.302905 | Val Loss: 0.310560

Epoch 12/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.82it/s, loss=0.177]
Epoch 12/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.47it/s]

End of Epoch 12 | Train Loss: 0.302363 | Val Loss: 0.185062
New Best Model Saved (Val Loss: 0.185062)

Epoch 13/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.87it/s, loss=0.145]
Epoch 13/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.34it/s]

End of Epoch 13 | Train Loss: 0.280300 | Val Loss: 0.244466

Epoch 14/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.126]
Epoch 14/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.54it/s]

End of Epoch 14 | Train Loss: 0.280635 | Val Loss: 0.494884

Epoch 15/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.83it/s, loss=0.166]
Epoch 15/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.03it/s]

End of Epoch 15 | Train Loss: 0.265756 | Val Loss: 0.232714

Epoch 16/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.146]
Epoch 16/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.78it/s]

End of Epoch 16 | Train Loss: 0.264432 | Val Loss: 0.262917

Epoch 17/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0989]
Epoch 17/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.72it/s]

End of Epoch 17 | Train Loss: 0.253217 | Val Loss: 0.217541

Epoch 18/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.524]
Epoch 18/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.13it/s]

End of Epoch 18 | Train Loss: 0.256662 | Val Loss: 0.236728

Epoch 19/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.154]
Epoch 19/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.34it/s]

End of Epoch 19 | Train Loss: 0.255023 | Val Loss: 0.258707

Epoch 20/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.49]
Epoch 20/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.43it/s]

End of Epoch 20 | Train Loss: 0.235827 | Val Loss: 0.253700

Epoch 21/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.109]
Epoch 21/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.51it/s]

End of Epoch 21 | Train Loss: 0.237916 | Val Loss: 0.247621

Epoch 22/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.79it/s, loss=0.0701]
Epoch 22/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.07it/s]

End of Epoch 22 | Train Loss: 0.249064 | Val Loss: 0.240528

Epoch 23/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.114]
Epoch 23/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.22it/s]

End of Epoch 23 | Train Loss: 0.233338 | Val Loss: 0.250076

Epoch 24/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.114]
Epoch 24/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.04it/s]

End of Epoch 24 | Train Loss: 0.239457 | Val Loss: 0.199708

Epoch 25/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.82it/s, loss=0.105]
Epoch 25/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.74it/s]

End of Epoch 25 | Train Loss: 0.228260 | Val Loss: 0.349779

Epoch 26/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.87it/s, loss=0.15]
Epoch 26/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.56it/s]

End of Epoch 26 | Train Loss: 0.224009 | Val Loss: 0.206247

Epoch 27/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.0882]
Epoch 27/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.40it/s]

End of Epoch 27 | Train Loss: 0.219873 | Val Loss: 0.185254

Epoch 28/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.319]
Epoch 28/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.50it/s]

End of Epoch 28 | Train Loss: 0.207710 | Val Loss: 0.224491

Epoch 29/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.223]
Epoch 29/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.19it/s]

End of Epoch 29 | Train Loss: 0.214096 | Val Loss: 0.229031

Epoch 30/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.136]
Epoch 30/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.31it/s]

End of Epoch 30 | Train Loss: 0.203533 | Val Loss: 0.229780

Epoch 31/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.67it/s, loss=0.532]
Epoch 31/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.71it/s]

End of Epoch 31 | Train Loss: 0.214287 | Val Loss: 0.247867

Epoch 32/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.15it/s, loss=0.13]
Epoch 32/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.88it/s]

End of Epoch 32 | Train Loss: 0.211155 | Val Loss: 0.160647
New Best Model Saved (Val Loss: 0.160647)

Epoch 33/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0872]
Epoch 33/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.27it/s]

End of Epoch 33 | Train Loss: 0.193075 | Val Loss: 0.199264

Epoch 34/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.0716]
Epoch 34/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.53it/s]

End of Epoch 34 | Train Loss: 0.208034 | Val Loss: 0.246736

Epoch 35/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.93it/s, loss=0.0835]
Epoch 35/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.25it/s]

End of Epoch 35 | Train Loss: 0.201597 | Val Loss: 0.169717

Epoch 36/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.0696]
Epoch 36/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.63it/s]

End of Epoch 36 | Train Loss: 0.189822 | Val Loss: 0.284422

Epoch 37/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.94it/s, loss=0.102]
Epoch 37/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.65it/s]

End of Epoch 37 | Train Loss: 0.200870 | Val Loss: 0.181973

Epoch 38/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.0899]
Epoch 38/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.60it/s]

End of Epoch 38 | Train Loss: 0.208836 | Val Loss: 0.232514

Epoch 39/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.147]
Epoch 39/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.58it/s]

End of Epoch 39 | Train Loss: 0.203271 | Val Loss: 0.187531

Epoch 40/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.88it/s, loss=0.0859]
Epoch 40/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.09it/s]

End of Epoch 40 | Train Loss: 0.199647 | Val Loss: 0.161177

Epoch 41/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0734]
Epoch 41/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.85it/s]

End of Epoch 41 | Train Loss: 0.191729 | Val Loss: 0.181856

Epoch 42/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0886]
Epoch 42/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.39it/s]

End of Epoch 42 | Train Loss: 0.184327 | Val Loss: 0.165779

Epoch 43/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.175]
Epoch 43/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.12it/s]

End of Epoch 43 | Train Loss: 0.177578 | Val Loss: 0.178730

Epoch 44/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0651]
Epoch 44/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.57it/s]

End of Epoch 44 | Train Loss: 0.171880 | Val Loss: 0.212920

Epoch 45/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0757]
Epoch 45/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.13it/s]

End of Epoch 45 | Train Loss: 0.168305 | Val Loss: 0.209745

Epoch 46/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.0438]
Epoch 46/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.71it/s]

End of Epoch 46 | Train Loss: 0.178938 | Val Loss: 0.247474

Epoch 47/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.37it/s, loss=0.828]
Epoch 47/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.32it/s]

End of Epoch 47 | Train Loss: 0.190582 | Val Loss: 0.154609
New Best Model Saved (Val Loss: 0.154609)

Epoch 48/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.19]
Epoch 48/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.88it/s]

End of Epoch 48 | Train Loss: 0.183433 | Val Loss: 0.135217
New Best Model Saved (Val Loss: 0.135217)

Epoch 49/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0674]
Epoch 49/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.36it/s]

End of Epoch 49 | Train Loss: 0.174156 | Val Loss: 0.219922

Epoch 50/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0473]
Epoch 50/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.05it/s]

End of Epoch 50 | Train Loss: 0.171143 | Val Loss: 0.137875

Epoch 51/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.41it/s, loss=0.0865]
Epoch 51/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.81it/s]

End of Epoch 51 | Train Loss: 0.171780 | Val Loss: 0.136829

Epoch 52/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.968]
Epoch 52/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.18it/s]

End of Epoch 52 | Train Loss: 0.172552 | Val Loss: 0.235050

Epoch 53/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.44it/s, loss=0.0767]
Epoch 53/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.06it/s]

End of Epoch 53 | Train Loss: 0.176832 | Val Loss: 0.142127

Epoch 54/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.44it/s, loss=0.0635]
Epoch 54/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.76it/s]

End of Epoch 54 | Train Loss: 0.189004 | Val Loss: 0.173258

Epoch 55/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0878]
Epoch 55/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.02it/s]

End of Epoch 55 | Train Loss: 0.165208 | Val Loss: 0.094632
New Best Model Saved (Val Loss: 0.094632)

Epoch 56/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.369]
Epoch 56/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.25it/s]

End of Epoch 56 | Train Loss: 0.168646 | Val Loss: 0.212168

Epoch 57/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.46it/s, loss=0.0791]
Epoch 57/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.85it/s]

End of Epoch 57 | Train Loss: 0.176154 | Val Loss: 0.183061

Epoch 58/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0567]
Epoch 58/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.01it/s]

End of Epoch 58 | Train Loss: 0.150562 | Val Loss: 0.166564

Epoch 59/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0549]
Epoch 59/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.12it/s]

End of Epoch 59 | Train Loss: 0.154895 | Val Loss: 0.171623

Epoch 60/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0361]
Epoch 60/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.00it/s]

End of Epoch 60 | Train Loss: 0.164231 | Val Loss: 0.202314

Epoch 61/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.699]
Epoch 61/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.93it/s]

End of Epoch 61 | Train Loss: 0.168867 | Val Loss: 0.098754

Epoch 62/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=1.03]
Epoch 62/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.72it/s]

End of Epoch 62 | Train Loss: 0.159081 | Val Loss: 0.178143

Epoch 63/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.056]
Epoch 63/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 88.98it/s]

End of Epoch 63 | Train Loss: 0.155004 | Val Loss: 0.143378

Epoch 64/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0737]
Epoch 64/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.73it/s]

End of Epoch 64 | Train Loss: 0.146346 | Val Loss: 0.113689

Epoch 65/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.18]
Epoch 65/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.58it/s]

End of Epoch 65 | Train Loss: 0.152669 | Val Loss: 0.146917

Epoch 66/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.79it/s, loss=0.0956]
Epoch 66/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.71it/s]

End of Epoch 66 | Train Loss: 0.151592 | Val Loss: 0.097405

Epoch 67/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.81it/s, loss=0.218]
Epoch 67/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.51it/s]

End of Epoch 67 | Train Loss: 0.135437 | Val Loss: 0.206636

Epoch 68/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.0479]
Epoch 68/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.71it/s]

End of Epoch 68 | Train Loss: 0.147301 | Val Loss: 0.065475
New Best Model Saved (Val Loss: 0.065475)

Epoch 69/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.191]
Epoch 69/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.83it/s]

End of Epoch 69 | Train Loss: 0.129023 | Val Loss: 0.150017

Epoch 70/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.0342]
Epoch 70/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.41it/s]

End of Epoch 70 | Train Loss: 0.145521 | Val Loss: 0.273427

Epoch 71/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0488]
Epoch 71/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.23it/s]

End of Epoch 71 | Train Loss: 0.132654 | Val Loss: 0.077362

Epoch 72/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.55it/s, loss=0.0596]
Epoch 72/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.72it/s]

End of Epoch 72 | Train Loss: 0.139607 | Val Loss: 0.118417

Epoch 73/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.0414]
Epoch 73/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.04it/s]

End of Epoch 73 | Train Loss: 0.133010 | Val Loss: 0.210779

Epoch 74/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.66]
Epoch 74/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.54it/s]

End of Epoch 74 | Train Loss: 0.139612 | Val Loss: 0.155711

Epoch 75/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0587]
Epoch 75/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.81it/s]

End of Epoch 75 | Train Loss: 0.141381 | Val Loss: 0.107107

Epoch 76/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0415]
Epoch 76/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.60it/s]

End of Epoch 76 | Train Loss: 0.141942 | Val Loss: 0.162062

Epoch 77/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.039]
Epoch 77/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.80it/s]

End of Epoch 77 | Train Loss: 0.135829 | Val Loss: 0.161627

Epoch 78/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.36it/s, loss=0.072]
Epoch 78/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.49it/s]

End of Epoch 78 | Train Loss: 0.128412 | Val Loss: 0.115927

Epoch 79/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0292]
Epoch 79/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.47it/s]

End of Epoch 79 | Train Loss: 0.143245 | Val Loss: 0.127028

Epoch 80/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.523]
Epoch 80/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.98it/s]

End of Epoch 80 | Train Loss: 0.142886 | Val Loss: 0.202541

Epoch 81/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0427]
Epoch 81/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.38it/s]

End of Epoch 81 | Train Loss: 0.124292 | Val Loss: 0.178085

Epoch 82/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0579]
Epoch 82/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.18it/s]

End of Epoch 82 | Train Loss: 0.127214 | Val Loss: 0.142996

Epoch 83/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.344]
Epoch 83/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.15it/s]

End of Epoch 83 | Train Loss: 0.137410 | Val Loss: 0.133257

Epoch 84/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.55it/s, loss=0.208]
Epoch 84/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.04it/s]

End of Epoch 84 | Train Loss: 0.134269 | Val Loss: 0.125604

Epoch 85/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.46it/s, loss=0.0284]
Epoch 85/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.95it/s]

End of Epoch 85 | Train Loss: 0.124596 | Val Loss: 0.155942

Epoch 86/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.0554]
Epoch 86/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.76it/s]

End of Epoch 86 | Train Loss: 0.108443 | Val Loss: 0.097427

Epoch 87/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.0413]
Epoch 87/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.31it/s]

End of Epoch 87 | Train Loss: 0.117740 | Val Loss: 0.119986

Epoch 88/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.657]
Epoch 88/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.40it/s]

End of Epoch 88 | Train Loss: 0.125052 | Val Loss: 0.088693

Epoch 89/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.68it/s, loss=0.0526]
Epoch 89/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.04it/s]

End of Epoch 89 | Train Loss: 0.117259 | Val Loss: 0.134720

Epoch 90/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.0524]
Epoch 90/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.33it/s]

End of Epoch 90 | Train Loss: 0.116150 | Val Loss: 0.171893

Epoch 91/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.043]
Epoch 91/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.49it/s]

End of Epoch 91 | Train Loss: 0.115903 | Val Loss: 0.102642

Epoch 92/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0798]
Epoch 92/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.16it/s]

End of Epoch 92 | Train Loss: 0.123947 | Val Loss: 0.128702

Epoch 93/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.028]
Epoch 93/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.94it/s]

End of Epoch 93 | Train Loss: 0.109237 | Val Loss: 0.292722

Epoch 94/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.44it/s, loss=0.0276]
Epoch 94/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.20it/s]

End of Epoch 94 | Train Loss: 0.108562 | Val Loss: 0.165889

Epoch 95/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.93it/s, loss=0.0603]
Epoch 95/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.63it/s]

End of Epoch 95 | Train Loss: 0.106543 | Val Loss: 0.067192

Epoch 96/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.74it/s, loss=0.0391]
Epoch 96/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.26it/s]

End of Epoch 96 | Train Loss: 0.115874 | Val Loss: 0.131118

Epoch 97/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.0713]
Epoch 97/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.45it/s]

End of Epoch 97 | Train Loss: 0.110909 | Val Loss: 0.217855

Epoch 98/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.41it/s, loss=0.0448]
Epoch 98/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 80.89it/s]

End of Epoch 98 | Train Loss: 0.091444 | Val Loss: 0.066130

Epoch 99/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.34it/s, loss=0.0489]
Epoch 99/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.44it/s]

End of Epoch 99 | Train Loss: 0.108003 | Val Loss: 0.084492

Epoch 100/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.48it/s, loss=0.135]
Epoch 100/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.97it/s]

End of Epoch 100 | Train Loss: 0.106391 | Val Loss: 0.173950

Epoch 101/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.83it/s, loss=0.035]
Epoch 101/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.81it/s]

End of Epoch 101 | Train Loss: 0.112430 | Val Loss: 0.150567

Epoch 102/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.82it/s, loss=0.0347]
Epoch 102/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.69it/s]

End of Epoch 102 | Train Loss: 0.099857 | Val Loss: 0.124045

Epoch 103/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.418]
Epoch 103/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.44it/s]

End of Epoch 103 | Train Loss: 0.102786 | Val Loss: 0.139805

Epoch 104/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.0328]
Epoch 104/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.02it/s]

End of Epoch 104 | Train Loss: 0.100101 | Val Loss: 0.085904

Epoch 105/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0616]
Epoch 105/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.26it/s]

End of Epoch 105 | Train Loss: 0.119691 | Val Loss: 0.148464

Epoch 106/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.03it/s, loss=0.146]
Epoch 106/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.90it/s]

End of Epoch 106 | Train Loss: 0.099805 | Val Loss: 0.077416

Epoch 107/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.897]
Epoch 107/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.80it/s]

End of Epoch 107 | Train Loss: 0.097199 | Val Loss: 0.206250

Epoch 108/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.0656]
Epoch 108/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.29it/s]

End of Epoch 108 | Train Loss: 0.093624 | Val Loss: 0.279340

Epoch 109/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.20it/s, loss=0.0305]
Epoch 109/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.04it/s]

End of Epoch 109 | Train Loss: 0.091646 | Val Loss: 0.081146

Epoch 110/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.041]
Epoch 110/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.45it/s]

End of Epoch 110 | Train Loss: 0.108096 | Val Loss: 0.134012

Epoch 111/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.0247]
Epoch 111/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.26it/s]

End of Epoch 111 | Train Loss: 0.107140 | Val Loss: 0.170835

Epoch 112/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.70it/s, loss=0.0259]
Epoch 112/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.93it/s]

End of Epoch 112 | Train Loss: 0.100847 | Val Loss: 0.193090

Epoch 113/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.0354]
Epoch 113/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.34it/s]

End of Epoch 113 | Train Loss: 0.096976 | Val Loss: 0.076355

Epoch 114/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0279]
Epoch 114/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.30it/s]

End of Epoch 114 | Train Loss: 0.101200 | Val Loss: 0.299202

Epoch 115/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0221]
Epoch 115/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.12it/s]

End of Epoch 115 | Train Loss: 0.083915 | Val Loss: 0.080208

Epoch 116/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.0308]
Epoch 116/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.38it/s]

End of Epoch 116 | Train Loss: 0.092167 | Val Loss: 0.065607

Epoch 117/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0273]
Epoch 117/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.42it/s]

End of Epoch 117 | Train Loss: 0.078292 | Val Loss: 0.163380

Epoch 118/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.68it/s, loss=0.0249]
Epoch 118/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.99it/s]

End of Epoch 118 | Train Loss: 0.096667 | Val Loss: 0.093584

Epoch 119/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.0221]
Epoch 119/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.50it/s]

End of Epoch 119 | Train Loss: 0.090121 | Val Loss: 0.113554

Epoch 120/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.72it/s, loss=0.0278]
Epoch 120/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.30it/s]

End of Epoch 120 | Train Loss: 0.080677 | Val Loss: 0.132613

Epoch 121/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.0288]
Epoch 121/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.34it/s]

End of Epoch 121 | Train Loss: 0.090916 | Val Loss: 0.069063

Epoch 122/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.46it/s, loss=0.0621]
Epoch 122/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.66it/s]

End of Epoch 122 | Train Loss: 0.093524 | Val Loss: 0.193763

Epoch 123/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.0548]
Epoch 123/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.86it/s]

End of Epoch 123 | Train Loss: 0.091295 | Val Loss: 0.194316

Epoch 124/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0226]
Epoch 124/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.44it/s]

End of Epoch 124 | Train Loss: 0.088873 | Val Loss: 0.196473

Epoch 125/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0965]
Epoch 125/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.15it/s]

End of Epoch 125 | Train Loss: 0.090619 | Val Loss: 0.122590

Epoch 126/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.0311]
Epoch 126/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.49it/s]

End of Epoch 126 | Train Loss: 0.099233 | Val Loss: 0.123367

Epoch 127/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0271]
Epoch 127/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.38it/s]

End of Epoch 127 | Train Loss: 0.096450 | Val Loss: 0.106937

Epoch 128/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.82it/s, loss=0.0261]
Epoch 128/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.24it/s]

End of Epoch 128 | Train Loss: 0.093423 | Val Loss: 0.106766

Epoch 129/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.41it/s, loss=0.335]
Epoch 129/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.03it/s]

End of Epoch 129 | Train Loss: 0.097971 | Val Loss: 0.106507

Epoch 130/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.0255]
Epoch 130/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.32it/s]

End of Epoch 130 | Train Loss: 0.092274 | Val Loss: 0.095196

Epoch 131/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.38it/s, loss=0.436]
Epoch 131/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.46it/s]

End of Epoch 131 | Train Loss: 0.102071 | Val Loss: 0.117046

Epoch 132/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.38it/s, loss=0.0181]
Epoch 132/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.69it/s]

End of Epoch 132 | Train Loss: 0.087800 | Val Loss: 0.143855

Epoch 133/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.0236]
Epoch 133/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.61it/s]

End of Epoch 133 | Train Loss: 0.092119 | Val Loss: 0.069006

Epoch 134/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.182]
Epoch 134/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.74it/s]

End of Epoch 134 | Train Loss: 0.076139 | Val Loss: 0.098826

Epoch 135/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0812]
Epoch 135/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.13it/s]

End of Epoch 135 | Train Loss: 0.095482 | Val Loss: 0.085143

Epoch 136/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0623]
Epoch 136/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.94it/s]

End of Epoch 136 | Train Loss: 0.073224 | Val Loss: 0.087102

Epoch 137/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.135]
Epoch 137/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.49it/s]

End of Epoch 137 | Train Loss: 0.088351 | Val Loss: 0.113689

Epoch 138/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0277]
Epoch 138/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.67it/s]

End of Epoch 138 | Train Loss: 0.069798 | Val Loss: 0.078516

Epoch 139/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.027]
Epoch 139/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.85it/s]

End of Epoch 139 | Train Loss: 0.090739 | Val Loss: 0.111148

Epoch 140/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0274]
Epoch 140/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.70it/s]

End of Epoch 140 | Train Loss: 0.090143 | Val Loss: 0.158840

Epoch 141/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.0259]
Epoch 141/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.89it/s]

End of Epoch 141 | Train Loss: 0.080139 | Val Loss: 0.114058

Epoch 142/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0158]
Epoch 142/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.20it/s]

End of Epoch 142 | Train Loss: 0.074117 | Val Loss: 0.072546

Epoch 143/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.36it/s, loss=0.0605]
Epoch 143/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.31it/s]

End of Epoch 143 | Train Loss: 0.080854 | Val Loss: 0.072632

Epoch 144/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.38it/s, loss=0.0226]
Epoch 144/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.14it/s]

End of Epoch 144 | Train Loss: 0.081236 | Val Loss: 0.144537

Epoch 145/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.56]
Epoch 145/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.56it/s]

End of Epoch 145 | Train Loss: 0.081350 | Val Loss: 0.176211

Epoch 146/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.40it/s, loss=0.0226]
Epoch 146/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.14it/s]

End of Epoch 146 | Train Loss: 0.080764 | Val Loss: 0.132284

Epoch 147/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.44it/s, loss=0.0198]
Epoch 147/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.07it/s]

End of Epoch 147 | Train Loss: 0.076821 | Val Loss: 0.090483

Epoch 148/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.712]
Epoch 148/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.18it/s]

End of Epoch 148 | Train Loss: 0.087737 | Val Loss: 0.095524

Epoch 149/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.55it/s, loss=0.11]
Epoch 149/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.42it/s]

End of Epoch 149 | Train Loss: 0.071005 | Val Loss: 0.065230
New Best Model Saved (Val Loss: 0.065230)

Epoch 150/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.49it/s, loss=0.122]
Epoch 150/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.72it/s]

End of Epoch 150 | Train Loss: 0.085605 | Val Loss: 0.071961

Epoch 151/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.0177]
Epoch 151/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.78it/s]

End of Epoch 151 | Train Loss: 0.083148 | Val Loss: 0.070425

Epoch 152/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0236]
Epoch 152/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.26it/s]

End of Epoch 152 | Train Loss: 0.079658 | Val Loss: 0.094340

Epoch 153/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0226]
Epoch 153/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.82it/s]

End of Epoch 153 | Train Loss: 0.079423 | Val Loss: 0.061191
New Best Model Saved (Val Loss: 0.061191)

Epoch 154/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.80it/s, loss=0.178]
Epoch 154/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.88it/s]

End of Epoch 154 | Train Loss: 0.092337 | Val Loss: 0.037554
New Best Model Saved (Val Loss: 0.037554)

Epoch 155/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0172]
Epoch 155/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.16it/s]

End of Epoch 155 | Train Loss: 0.080421 | Val Loss: 0.076207

Epoch 156/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0187]
Epoch 156/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.83it/s]

End of Epoch 156 | Train Loss: 0.083803 | Val Loss: 0.100298

Epoch 157/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.0235]
Epoch 157/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.18it/s]

End of Epoch 157 | Train Loss: 0.068399 | Val Loss: 0.100450

Epoch 158/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.0261]
Epoch 158/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.69it/s]

End of Epoch 158 | Train Loss: 0.077865 | Val Loss: 0.053530

Epoch 159/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0203]
Epoch 159/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.05it/s]

End of Epoch 159 | Train Loss: 0.076857 | Val Loss: 0.189652

Epoch 160/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0426]
Epoch 160/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.85it/s]

End of Epoch 160 | Train Loss: 0.077698 | Val Loss: 0.110676

Epoch 161/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0184]
Epoch 161/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.05it/s]

End of Epoch 161 | Train Loss: 0.073294 | Val Loss: 0.063198

Epoch 162/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0168]
Epoch 162/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.43it/s]

End of Epoch 162 | Train Loss: 0.065607 | Val Loss: 0.105538

Epoch 163/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.664]
Epoch 163/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.93it/s]

End of Epoch 163 | Train Loss: 0.084035 | Val Loss: 0.044779

Epoch 164/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0161]
Epoch 164/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.25it/s]

End of Epoch 164 | Train Loss: 0.083182 | Val Loss: 0.103710

Epoch 165/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0178]
Epoch 165/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.28it/s]

End of Epoch 165 | Train Loss: 0.067408 | Val Loss: 0.171346

Epoch 166/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.024]
Epoch 166/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.73it/s]

End of Epoch 166 | Train Loss: 0.077505 | Val Loss: 0.146176

Epoch 167/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0207]
Epoch 167/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.09it/s]

End of Epoch 167 | Train Loss: 0.074623 | Val Loss: 0.064459

Epoch 168/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.137]
Epoch 168/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.87it/s]

End of Epoch 168 | Train Loss: 0.081738 | Val Loss: 0.053616

Epoch 169/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0183]
Epoch 169/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.43it/s]

End of Epoch 169 | Train Loss: 0.077276 | Val Loss: 0.079506

Epoch 170/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.79it/s, loss=0.0172]
Epoch 170/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.01it/s]

End of Epoch 170 | Train Loss: 0.070360 | Val Loss: 0.120304

Epoch 171/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.04it/s, loss=0.0462]
Epoch 171/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.11it/s]

End of Epoch 171 | Train Loss: 0.074802 | Val Loss: 0.058118

Epoch 172/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.70it/s, loss=0.0193]
Epoch 172/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.92it/s]

End of Epoch 172 | Train Loss: 0.074762 | Val Loss: 0.108381

Epoch 173/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0162]
Epoch 173/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.47it/s]

End of Epoch 173 | Train Loss: 0.063828 | Val Loss: 0.059438

Epoch 174/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0308]
Epoch 174/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.92it/s]

End of Epoch 174 | Train Loss: 0.058660 | Val Loss: 0.167172

Epoch 175/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0703]
Epoch 175/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.07it/s]

End of Epoch 175 | Train Loss: 0.070467 | Val Loss: 0.067351

Epoch 176/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.75it/s, loss=0.0167]
Epoch 176/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.28it/s]

End of Epoch 176 | Train Loss: 0.071618 | Val Loss: 0.144767

Epoch 177/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.68it/s, loss=0.18]
Epoch 177/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.28it/s]

End of Epoch 177 | Train Loss: 0.071522 | Val Loss: 0.198141

Epoch 178/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.76it/s, loss=0.206]
Epoch 178/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.85it/s]

End of Epoch 178 | Train Loss: 0.077386 | Val Loss: 0.129066

Epoch 179/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.74it/s, loss=0.0232]
Epoch 179/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.38it/s]

End of Epoch 179 | Train Loss: 0.070297 | Val Loss: 0.106420

Epoch 180/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.87it/s, loss=0.0183]
Epoch 180/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.14it/s]

End of Epoch 180 | Train Loss: 0.067638 | Val Loss: 0.124930

Epoch 181/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.52it/s, loss=0.0604]
Epoch 181/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.20it/s]

End of Epoch 181 | Train Loss: 0.073213 | Val Loss: 0.119335

Epoch 182/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.52it/s, loss=0.168]
Epoch 182/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.11it/s]

End of Epoch 182 | Train Loss: 0.081737 | Val Loss: 0.190291

Epoch 183/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.278]
Epoch 183/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.97it/s]

End of Epoch 183 | Train Loss: 0.074896 | Val Loss: 0.083608

Epoch 184/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0149]
Epoch 184/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.98it/s]

End of Epoch 184 | Train Loss: 0.074669 | Val Loss: 0.101718

Epoch 185/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0163]
Epoch 185/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.24it/s]

End of Epoch 185 | Train Loss: 0.070801 | Val Loss: 0.192932

Epoch 186/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0185]
Epoch 186/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.66it/s]

End of Epoch 186 | Train Loss: 0.056886 | Val Loss: 0.063603

Epoch 187/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.0174]
Epoch 187/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.08it/s]

End of Epoch 187 | Train Loss: 0.070636 | Val Loss: 0.080374

Epoch 188/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.034]
Epoch 188/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.34it/s]

End of Epoch 188 | Train Loss: 0.067985 | Val Loss: 0.113052

Epoch 189/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0299]
Epoch 189/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.78it/s]

End of Epoch 189 | Train Loss: 0.053529 | Val Loss: 0.114276

Epoch 190/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0162]
Epoch 190/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.90it/s]

End of Epoch 190 | Train Loss: 0.067921 | Val Loss: 0.188903

Epoch 191/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.55it/s, loss=0.0236]
Epoch 191/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.01it/s]

End of Epoch 191 | Train Loss: 0.073089 | Val Loss: 0.069201

Epoch 192/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.017]
Epoch 192/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.44it/s]

End of Epoch 192 | Train Loss: 0.056556 | Val Loss: 0.091966

Epoch 193/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0199]
Epoch 193/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.32it/s]

End of Epoch 193 | Train Loss: 0.074880 | Val Loss: 0.107314

Epoch 194/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.0131]
Epoch 194/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.72it/s]

End of Epoch 194 | Train Loss: 0.071788 | Val Loss: 0.174219

Epoch 195/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.52it/s, loss=0.0205]
Epoch 195/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.02it/s]

End of Epoch 195 | Train Loss: 0.068554 | Val Loss: 0.112428

Epoch 196/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0143]
Epoch 196/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.82it/s]

End of Epoch 196 | Train Loss: 0.063310 | Val Loss: 0.055430

Epoch 197/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0752]
Epoch 197/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.87it/s]

End of Epoch 197 | Train Loss: 0.062973 | Val Loss: 0.109658

Epoch 198/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0144]
Epoch 198/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.61it/s]

End of Epoch 198 | Train Loss: 0.067850 | Val Loss: 0.081886

Epoch 199/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.014]
Epoch 199/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.06it/s]

End of Epoch 199 | Train Loss: 0.065186 | Val Loss: 0.123881

Epoch 200/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.0153]
Epoch 200/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.48it/s]

End of Epoch 200 | Train Loss: 0.063205 | Val Loss: 0.073139

Epoch 201/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.70it/s, loss=0.0163]
Epoch 201/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.26it/s]

End of Epoch 201 | Train Loss: 0.058341 | Val Loss: 0.095656

Epoch 202/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0151]
Epoch 202/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.07it/s]

End of Epoch 202 | Train Loss: 0.063550 | Val Loss: 0.311510

Epoch 203/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.98it/s, loss=0.0145]
Epoch 203/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.58it/s]

End of Epoch 203 | Train Loss: 0.073665 | Val Loss: 0.103125

Epoch 204/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.20it/s, loss=0.0584]
Epoch 204/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.03it/s]

End of Epoch 204 | Train Loss: 0.065037 | Val Loss: 0.117315

Epoch 205/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.19it/s, loss=0.0136]
Epoch 205/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.63it/s]

End of Epoch 205 | Train Loss: 0.065889 | Val Loss: 0.022867
New Best Model Saved (Val Loss: 0.022867)

Epoch 206/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.21it/s, loss=0.862]
Epoch 206/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.13it/s]

End of Epoch 206 | Train Loss: 0.071725 | Val Loss: 0.132236

Epoch 207/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.0228]
Epoch 207/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.51it/s]

End of Epoch 207 | Train Loss: 0.075070 | Val Loss: 0.073290

Epoch 208/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0178]
Epoch 208/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.49it/s]

End of Epoch 208 | Train Loss: 0.074466 | Val Loss: 0.099668

Epoch 209/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0124]
Epoch 209/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.92it/s]

End of Epoch 209 | Train Loss: 0.062150 | Val Loss: 0.034898

Epoch 210/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.123]
Epoch 210/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.41it/s]

End of Epoch 210 | Train Loss: 0.067772 | Val Loss: 0.080463

Epoch 211/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.71it/s, loss=0.0455]
Epoch 211/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.63it/s]

End of Epoch 211 | Train Loss: 0.074003 | Val Loss: 0.104745

Epoch 212/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.0132]
Epoch 212/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.72it/s]

End of Epoch 212 | Train Loss: 0.059998 | Val Loss: 0.170034

Epoch 213/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.71it/s, loss=0.0141]
Epoch 213/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.63it/s]

End of Epoch 213 | Train Loss: 0.052072 | Val Loss: 0.084697

Epoch 214/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.0126]
Epoch 214/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.58it/s]

End of Epoch 214 | Train Loss: 0.070284 | Val Loss: 0.028855

Epoch 215/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.0176]
Epoch 215/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.66it/s]

End of Epoch 215 | Train Loss: 0.059147 | Val Loss: 0.134246

Epoch 216/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.013]
Epoch 216/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.65it/s]

End of Epoch 216 | Train Loss: 0.061509 | Val Loss: 0.050368

Epoch 217/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0156]
Epoch 217/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.91it/s]

End of Epoch 217 | Train Loss: 0.071374 | Val Loss: 0.088610

Epoch 218/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.601]
Epoch 218/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.49it/s]

End of Epoch 218 | Train Loss: 0.077961 | Val Loss: 0.135682

Epoch 219/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0139]
Epoch 219/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.13it/s]

End of Epoch 219 | Train Loss: 0.065387 | Val Loss: 0.097882

Epoch 220/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.0134]
Epoch 220/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.30it/s]

End of Epoch 220 | Train Loss: 0.069037 | Val Loss: 0.123913

Epoch 221/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0128]
Epoch 221/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.65it/s]

End of Epoch 221 | Train Loss: 0.063916 | Val Loss: 0.094286

Epoch 222/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.0139]
Epoch 222/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.22it/s]

End of Epoch 222 | Train Loss: 0.067602 | Val Loss: 0.107968

Epoch 223/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.0143]
Epoch 223/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.47it/s]

End of Epoch 223 | Train Loss: 0.057284 | Val Loss: 0.141182

Epoch 224/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0137]
Epoch 224/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.80it/s]

End of Epoch 224 | Train Loss: 0.069086 | Val Loss: 0.118444

Epoch 225/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.204]
Epoch 225/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.91it/s]

End of Epoch 225 | Train Loss: 0.058426 | Val Loss: 0.097057

Epoch 226/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.26it/s, loss=0.221]
Epoch 226/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.47it/s]

End of Epoch 226 | Train Loss: 0.063477 | Val Loss: 0.071415

Epoch 227/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.22it/s, loss=0.0226]
Epoch 227/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.00it/s]

End of Epoch 227 | Train Loss: 0.057732 | Val Loss: 0.103396

Epoch 228/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.23it/s, loss=0.0137]
Epoch 228/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.77it/s]

End of Epoch 228 | Train Loss: 0.068422 | Val Loss: 0.166871

Epoch 229/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.0558]
Epoch 229/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.12it/s]

End of Epoch 229 | Train Loss: 0.053391 | Val Loss: 0.098259

Epoch 230/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.0116]
Epoch 230/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.91it/s]

End of Epoch 230 | Train Loss: 0.063213 | Val Loss: 0.065675

Epoch 231/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.98it/s, loss=0.013]
Epoch 231/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.80it/s]

End of Epoch 231 | Train Loss: 0.052235 | Val Loss: 0.073990

Epoch 232/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.01it/s, loss=0.0193]
Epoch 232/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.69it/s]

End of Epoch 232 | Train Loss: 0.058996 | Val Loss: 0.115643

Epoch 233/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.0146]
Epoch 233/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.32it/s]

End of Epoch 233 | Train Loss: 0.052897 | Val Loss: 0.230043

Epoch 234/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0256]
Epoch 234/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.58it/s]

End of Epoch 234 | Train Loss: 0.057612 | Val Loss: 0.131116

Epoch 235/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0129]
Epoch 235/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.62it/s]

End of Epoch 235 | Train Loss: 0.058132 | Val Loss: 0.075507

Epoch 236/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.12it/s, loss=0.0155]
Epoch 236/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.98it/s]

End of Epoch 236 | Train Loss: 0.062864 | Val Loss: 0.162411

Epoch 237/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.53it/s, loss=0.466]
Epoch 237/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.58it/s]

End of Epoch 237 | Train Loss: 0.060801 | Val Loss: 0.070955

Epoch 238/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0129]
Epoch 238/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.65it/s]

End of Epoch 238 | Train Loss: 0.057223 | Val Loss: 0.095738

Epoch 239/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.601]
Epoch 239/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.70it/s]

End of Epoch 239 | Train Loss: 0.067019 | Val Loss: 0.173014

Epoch 240/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0129]
Epoch 240/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.84it/s]

End of Epoch 240 | Train Loss: 0.061356 | Val Loss: 0.082542

Epoch 241/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.0298]
Epoch 241/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.55it/s]

End of Epoch 241 | Train Loss: 0.050874 | Val Loss: 0.152701

Epoch 242/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.012]
Epoch 242/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.03it/s]

End of Epoch 242 | Train Loss: 0.061731 | Val Loss: 0.137964

Epoch 243/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.0114]
Epoch 243/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.18it/s]

End of Epoch 243 | Train Loss: 0.062885 | Val Loss: 0.162901

Epoch 244/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0132]
Epoch 244/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.78it/s]

End of Epoch 244 | Train Loss: 0.061236 | Val Loss: 0.055033

Epoch 245/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0352]
Epoch 245/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.55it/s]

End of Epoch 245 | Train Loss: 0.060427 | Val Loss: 0.069977

Epoch 246/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0825]
Epoch 246/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.89it/s]

End of Epoch 246 | Train Loss: 0.063940 | Val Loss: 0.091292

Epoch 247/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0154]
Epoch 247/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.90it/s]

End of Epoch 247 | Train Loss: 0.064035 | Val Loss: 0.138492

Epoch 248/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0139]
Epoch 248/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.01it/s]

End of Epoch 248 | Train Loss: 0.057673 | Val Loss: 0.130048

Epoch 249/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0239]
Epoch 249/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.93it/s]

End of Epoch 249 | Train Loss: 0.068576 | Val Loss: 0.112240

Epoch 250/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.0499]
Epoch 250/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.86it/s]

End of Epoch 250 | Train Loss: 0.051630 | Val Loss: 0.063944

Epoch 251/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.012]
Epoch 251/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.54it/s]

End of Epoch 251 | Train Loss: 0.061813 | Val Loss: 0.046419

Epoch 252/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0127]
Epoch 252/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.13it/s]

End of Epoch 252 | Train Loss: 0.065379 | Val Loss: 0.090738

Epoch 253/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.0127]
Epoch 253/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.88it/s]

End of Epoch 253 | Train Loss: 0.057439 | Val Loss: 0.111002

Epoch 254/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.03it/s, loss=0.0467]
Epoch 254/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.42it/s]

End of Epoch 254 | Train Loss: 0.066763 | Val Loss: 0.129308

Epoch 255/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.0114]
Epoch 255/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.87it/s]

End of Epoch 255 | Train Loss: 0.054791 | Val Loss: 0.085174

Epoch 256/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.015]
Epoch 256/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.78it/s]

End of Epoch 256 | Train Loss: 0.055872 | Val Loss: 0.080225

Epoch 257/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.025]
Epoch 257/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.81it/s]

End of Epoch 257 | Train Loss: 0.053109 | Val Loss: 0.048207

Epoch 258/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0114]
Epoch 258/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.48it/s]

End of Epoch 258 | Train Loss: 0.053321 | Val Loss: 0.079956

Epoch 259/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.239]
Epoch 259/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.54it/s]

End of Epoch 259 | Train Loss: 0.060094 | Val Loss: 0.122078

Epoch 260/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.0126]
Epoch 260/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.20it/s]

End of Epoch 260 | Train Loss: 0.054482 | Val Loss: 0.250541

Epoch 261/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.0127]
Epoch 261/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.18it/s]

End of Epoch 261 | Train Loss: 0.066755 | Val Loss: 0.223836

Epoch 262/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.23it/s, loss=0.0308]
Epoch 262/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.91it/s]

End of Epoch 262 | Train Loss: 0.066574 | Val Loss: 0.152834

Epoch 263/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.0164]
Epoch 263/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.51it/s]

End of Epoch 263 | Train Loss: 0.048422 | Val Loss: 0.110183

Epoch 264/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.0122]
Epoch 264/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.29it/s]

End of Epoch 264 | Train Loss: 0.054552 | Val Loss: 0.106410

Epoch 265/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.0192]
Epoch 265/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.11it/s]

End of Epoch 265 | Train Loss: 0.055382 | Val Loss: 0.098525

Epoch 266/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.0158]
Epoch 266/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.66it/s]

End of Epoch 266 | Train Loss: 0.057002 | Val Loss: 0.191635

Epoch 267/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.74it/s, loss=0.0121]
Epoch 267/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.31it/s]

End of Epoch 267 | Train Loss: 0.048712 | Val Loss: 0.066905

Epoch 268/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.77it/s, loss=0.0189]
Epoch 268/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.48it/s]

End of Epoch 268 | Train Loss: 0.056225 | Val Loss: 0.105844

Epoch 269/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.0689]
Epoch 269/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.15it/s]

End of Epoch 269 | Train Loss: 0.060284 | Val Loss: 0.194271

Epoch 270/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.79it/s, loss=0.01]
Epoch 270/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.11it/s]

End of Epoch 270 | Train Loss: 0.055443 | Val Loss: 0.077655

Epoch 271/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.74it/s, loss=0.012]
Epoch 271/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.19it/s]

End of Epoch 271 | Train Loss: 0.057401 | Val Loss: 0.160067

Epoch 272/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.0118]
Epoch 272/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.22it/s]

End of Epoch 272 | Train Loss: 0.054287 | Val Loss: 0.239934

Epoch 273/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.81it/s, loss=0.0143]
Epoch 273/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.28it/s]

End of Epoch 273 | Train Loss: 0.050606 | Val Loss: 0.097669

Epoch 274/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.75it/s, loss=0.247]
Epoch 274/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.23it/s]

End of Epoch 274 | Train Loss: 0.059363 | Val Loss: 0.261439

Epoch 275/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0688]
Epoch 275/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.09it/s]

End of Epoch 275 | Train Loss: 0.058615 | Val Loss: 0.068889

Epoch 276/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.0336]
Epoch 276/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.49it/s]

End of Epoch 276 | Train Loss: 0.061831 | Val Loss: 0.053713

Epoch 277/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.0423]
Epoch 277/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.58it/s]

End of Epoch 277 | Train Loss: 0.051801 | Val Loss: 0.093239

Epoch 278/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.025]
Epoch 278/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.03it/s]

End of Epoch 278 | Train Loss: 0.046239 | Val Loss: 0.134843

Epoch 279/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.805]
Epoch 279/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.86it/s]

End of Epoch 279 | Train Loss: 0.057026 | Val Loss: 0.066469

Epoch 280/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.0135]
Epoch 280/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.08it/s]

End of Epoch 280 | Train Loss: 0.046742 | Val Loss: 0.122431

Epoch 281/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.0103]
Epoch 281/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.14it/s]

End of Epoch 281 | Train Loss: 0.054398 | Val Loss: 0.127663

Epoch 282/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0301]
Epoch 282/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.46it/s]

End of Epoch 282 | Train Loss: 0.054233 | Val Loss: 0.086891

Epoch 283/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0122]
Epoch 283/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.59it/s]

End of Epoch 283 | Train Loss: 0.054936 | Val Loss: 0.036562

Epoch 284/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.012]
Epoch 284/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.63it/s]

End of Epoch 284 | Train Loss: 0.045732 | Val Loss: 0.225754

Epoch 285/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.57it/s, loss=0.0126]
Epoch 285/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.14it/s]

End of Epoch 285 | Train Loss: 0.052424 | Val Loss: 0.137733

Epoch 286/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.41it/s, loss=0.52]
Epoch 286/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.42it/s]

End of Epoch 286 | Train Loss: 0.058260 | Val Loss: 0.049839

Epoch 287/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.45it/s, loss=0.0131]
Epoch 287/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.35it/s]

End of Epoch 287 | Train Loss: 0.063800 | Val Loss: 0.092451

Epoch 288/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.31it/s, loss=0.0132]
Epoch 288/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.95it/s]

End of Epoch 288 | Train Loss: 0.060985 | Val Loss: 0.092232

Epoch 289/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.0169]
Epoch 289/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.04it/s]

End of Epoch 289 | Train Loss: 0.053613 | Val Loss: 0.045890

Epoch 290/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0131]
Epoch 290/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.29it/s]

End of Epoch 290 | Train Loss: 0.052125 | Val Loss: 0.086423

Epoch 291/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.61it/s, loss=0.0125]
Epoch 291/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.31it/s]

End of Epoch 291 | Train Loss: 0.052900 | Val Loss: 0.064824

Epoch 292/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.49it/s, loss=0.0139]
Epoch 292/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.06it/s]

End of Epoch 292 | Train Loss: 0.062099 | Val Loss: 0.060011

Epoch 293/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.48it/s, loss=0.01]
Epoch 293/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.65it/s]

End of Epoch 293 | Train Loss: 0.054008 | Val Loss: 0.115398

Epoch 294/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.49it/s, loss=0.0209]
Epoch 294/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.29it/s]

End of Epoch 294 | Train Loss: 0.053706 | Val Loss: 0.181698

Epoch 295/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.0115]
Epoch 295/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.51it/s]

End of Epoch 295 | Train Loss: 0.055444 | Val Loss: 0.174784

Epoch 296/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.49it/s, loss=0.0115]
Epoch 296/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.21it/s]

End of Epoch 296 | Train Loss: 0.042687 | Val Loss: 0.101445

Epoch 297/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.48it/s, loss=0.227]
Epoch 297/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.16it/s]

End of Epoch 297 | Train Loss: 0.051659 | Val Loss: 0.113716

Epoch 298/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0127]
Epoch 298/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.87it/s]

End of Epoch 298 | Train Loss: 0.062216 | Val Loss: 0.181491

Epoch 299/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.0125]
Epoch 299/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.05it/s]

End of Epoch 299 | Train Loss: 0.045283 | Val Loss: 0.070338

Epoch 300/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.0162]
Epoch 300/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.40it/s]

End of Epoch 300 | Train Loss: 0.058222 | Val Loss: 0.228115

Epoch 301/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.0116]
Epoch 301/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.26it/s]

End of Epoch 301 | Train Loss: 0.050035 | Val Loss: 0.159571

Epoch 302/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0144]
Epoch 302/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.15it/s]

End of Epoch 302 | Train Loss: 0.061384 | Val Loss: 0.129100

Epoch 303/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.0103]
Epoch 303/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.23it/s]

End of Epoch 303 | Train Loss: 0.054436 | Val Loss: 0.158619

Epoch 304/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.93it/s, loss=0.0109]
Epoch 304/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.77it/s]

End of Epoch 304 | Train Loss: 0.060762 | Val Loss: 0.159797

Epoch 305/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.02it/s, loss=0.0134]
Epoch 305/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.59it/s]

End of Epoch 305 | Train Loss: 0.047843 | Val Loss: 0.121983

Epoch 306/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.406]
Epoch 306/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.27it/s]

End of Epoch 306 | Train Loss: 0.054111 | Val Loss: 0.044920

Epoch 307/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.77it/s, loss=0.0947]
Epoch 307/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.95it/s]

End of Epoch 307 | Train Loss: 0.053183 | Val Loss: 0.101475

Epoch 308/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.0093]
Epoch 308/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.57it/s]

End of Epoch 308 | Train Loss: 0.047179 | Val Loss: 0.132503

Epoch 309/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.0323]
Epoch 309/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.05it/s]

End of Epoch 309 | Train Loss: 0.042794 | Val Loss: 0.104494

Epoch 310/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.054]
Epoch 310/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.12it/s]

End of Epoch 310 | Train Loss: 0.050497 | Val Loss: 0.033522

Epoch 311/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.334]
Epoch 311/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.64it/s]

End of Epoch 311 | Train Loss: 0.051028 | Val Loss: 0.038402

Epoch 312/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.00947]
Epoch 312/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.03it/s]

End of Epoch 312 | Train Loss: 0.053518 | Val Loss: 0.081467

Epoch 313/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.00it/s, loss=0.0108]
Epoch 313/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.67it/s]

End of Epoch 313 | Train Loss: 0.043401 | Val Loss: 0.093110

Epoch 314/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.078]
Epoch 314/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.98it/s]

End of Epoch 314 | Train Loss: 0.061917 | Val Loss: 0.117199

Epoch 315/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.162]
Epoch 315/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.49it/s]

End of Epoch 315 | Train Loss: 0.042971 | Val Loss: 0.096498

Epoch 316/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.44it/s, loss=0.285]
Epoch 316/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.07it/s]

End of Epoch 316 | Train Loss: 0.057401 | Val Loss: 0.089534

Epoch 317/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.93it/s, loss=0.266]
Epoch 317/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.05it/s]

End of Epoch 317 | Train Loss: 0.054066 | Val Loss: 0.210470

Epoch 318/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.00935]
Epoch 318/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.50it/s]

End of Epoch 318 | Train Loss: 0.053011 | Val Loss: 0.123436

Epoch 319/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.00898]
Epoch 319/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.84it/s]

End of Epoch 319 | Train Loss: 0.043829 | Val Loss: 0.140822

Epoch 320/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0528]
Epoch 320/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.91it/s]

End of Epoch 320 | Train Loss: 0.052851 | Val Loss: 0.130364

Epoch 321/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.106]
Epoch 321/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.43it/s]

End of Epoch 321 | Train Loss: 0.051884 | Val Loss: 0.077212

Epoch 322/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.0119]
Epoch 322/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.13it/s]

End of Epoch 322 | Train Loss: 0.047251 | Val Loss: 0.120188

Epoch 323/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.0112]
Epoch 323/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.21it/s]

End of Epoch 323 | Train Loss: 0.048728 | Val Loss: 0.061299

Epoch 324/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.0236]
Epoch 324/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.74it/s]

End of Epoch 324 | Train Loss: 0.048817 | Val Loss: 0.077227

Epoch 325/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0109]
Epoch 325/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.37it/s]

End of Epoch 325 | Train Loss: 0.041856 | Val Loss: 0.127409

Epoch 326/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.0106]
Epoch 326/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.24it/s]

End of Epoch 326 | Train Loss: 0.051559 | Val Loss: 0.156257

Epoch 327/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.826]
Epoch 327/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.78it/s]

End of Epoch 327 | Train Loss: 0.059988 | Val Loss: 0.049837

Epoch 328/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.02it/s, loss=0.0113]
Epoch 328/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.69it/s]

End of Epoch 328 | Train Loss: 0.054251 | Val Loss: 0.143377

Epoch 329/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.00875]
Epoch 329/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.40it/s]

End of Epoch 329 | Train Loss: 0.051220 | Val Loss: 0.147460

Epoch 330/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.0194]
Epoch 330/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.43it/s]

End of Epoch 330 | Train Loss: 0.047299 | Val Loss: 0.077852

Epoch 331/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.01it/s, loss=0.0117]
Epoch 331/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.15it/s]

End of Epoch 331 | Train Loss: 0.042870 | Val Loss: 0.086506

Epoch 332/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.351]
Epoch 332/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.54it/s]

End of Epoch 332 | Train Loss: 0.047849 | Val Loss: 0.198090

Epoch 333/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.0444]
Epoch 333/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.18it/s]

End of Epoch 333 | Train Loss: 0.052571 | Val Loss: 0.048284

Epoch 334/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.016]
Epoch 334/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.82it/s]

End of Epoch 334 | Train Loss: 0.044783 | Val Loss: 0.180186

Epoch 335/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0721]
Epoch 335/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.26it/s]

End of Epoch 335 | Train Loss: 0.045449 | Val Loss: 0.088830

Epoch 336/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.0117]
Epoch 336/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.89it/s]

End of Epoch 336 | Train Loss: 0.046980 | Val Loss: 0.055348

Epoch 337/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.177]
Epoch 337/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.04it/s]

End of Epoch 337 | Train Loss: 0.048332 | Val Loss: 0.067163

Epoch 338/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.023]
Epoch 338/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.94it/s]

End of Epoch 338 | Train Loss: 0.050253 | Val Loss: 0.089078

Epoch 339/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.00988]
Epoch 339/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.10it/s]

End of Epoch 339 | Train Loss: 0.051055 | Val Loss: 0.062910

Epoch 340/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.00944]
Epoch 340/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.47it/s]

End of Epoch 340 | Train Loss: 0.045247 | Val Loss: 0.159875

Epoch 341/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.05it/s, loss=0.087]
Epoch 341/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.78it/s]

End of Epoch 341 | Train Loss: 0.052469 | Val Loss: 0.123260

Epoch 342/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.88it/s, loss=0.251]
Epoch 342/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.10it/s]

End of Epoch 342 | Train Loss: 0.050688 | Val Loss: 0.106901

Epoch 343/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00897]
Epoch 343/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.09it/s]

End of Epoch 343 | Train Loss: 0.045728 | Val Loss: 0.217824

Epoch 344/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.88it/s, loss=0.0107]
Epoch 344/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.72it/s]

End of Epoch 344 | Train Loss: 0.052547 | Val Loss: 0.093285

Epoch 345/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.0309]
Epoch 345/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.28it/s]

End of Epoch 345 | Train Loss: 0.047708 | Val Loss: 0.050683

Epoch 346/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00787]
Epoch 346/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.22it/s]

End of Epoch 346 | Train Loss: 0.044383 | Val Loss: 0.087261

Epoch 347/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0127]
Epoch 347/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.19it/s]

End of Epoch 347 | Train Loss: 0.048324 | Val Loss: 0.096686

Epoch 348/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.0149]
Epoch 348/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.00it/s]

End of Epoch 348 | Train Loss: 0.042093 | Val Loss: 0.096618

Epoch 349/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.93it/s, loss=0.0123]
Epoch 349/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.75it/s]

End of Epoch 349 | Train Loss: 0.049059 | Val Loss: 0.133762

Epoch 350/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0162]
Epoch 350/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.47it/s]

End of Epoch 350 | Train Loss: 0.048955 | Val Loss: 0.103957

Epoch 351/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.00967]
Epoch 351/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.38it/s]

End of Epoch 351 | Train Loss: 0.042416 | Val Loss: 0.114342

Epoch 352/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.011]
Epoch 352/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.87it/s]

End of Epoch 352 | Train Loss: 0.040375 | Val Loss: 0.060357

Epoch 353/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.108]
Epoch 353/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.75it/s]

End of Epoch 353 | Train Loss: 0.036633 | Val Loss: 0.055523

Epoch 354/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0106]
Epoch 354/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.97it/s]

End of Epoch 354 | Train Loss: 0.045627 | Val Loss: 0.124840

Epoch 355/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.488]
Epoch 355/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.07it/s]

End of Epoch 355 | Train Loss: 0.046945 | Val Loss: 0.073293

Epoch 356/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.76it/s, loss=0.0121]
Epoch 356/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.04it/s]

End of Epoch 356 | Train Loss: 0.055746 | Val Loss: 0.122549

Epoch 357/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0101]
Epoch 357/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.64it/s]

End of Epoch 357 | Train Loss: 0.040996 | Val Loss: 0.084438

Epoch 358/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0113]
Epoch 358/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.84it/s]

End of Epoch 358 | Train Loss: 0.048509 | Val Loss: 0.084179

Epoch 359/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.00989]
Epoch 359/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.58it/s]

End of Epoch 359 | Train Loss: 0.054752 | Val Loss: 0.105449

Epoch 360/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.83it/s, loss=0.00906]
Epoch 360/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.55it/s]

End of Epoch 360 | Train Loss: 0.042437 | Val Loss: 0.084620

Epoch 361/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.0124]
Epoch 361/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.08it/s]

End of Epoch 361 | Train Loss: 0.040066 | Val Loss: 0.088737

Epoch 362/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.105]
Epoch 362/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.86it/s]

End of Epoch 362 | Train Loss: 0.041419 | Val Loss: 0.038284

Epoch 363/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00916]
Epoch 363/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.22it/s]

End of Epoch 363 | Train Loss: 0.048937 | Val Loss: 0.079839

Epoch 364/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00971]
Epoch 364/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.60it/s]

End of Epoch 364 | Train Loss: 0.047427 | Val Loss: 0.070110

Epoch 365/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00851]
Epoch 365/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.44it/s]

End of Epoch 365 | Train Loss: 0.043354 | Val Loss: 0.122245

Epoch 366/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.00971]
Epoch 366/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.70it/s]

End of Epoch 366 | Train Loss: 0.052290 | Val Loss: 0.223077

Epoch 367/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0387]
Epoch 367/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.44it/s]

End of Epoch 367 | Train Loss: 0.042207 | Val Loss: 0.123036

Epoch 368/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.0125]
Epoch 368/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.60it/s]

End of Epoch 368 | Train Loss: 0.044233 | Val Loss: 0.235127

Epoch 369/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.06]
Epoch 369/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.51it/s]

End of Epoch 369 | Train Loss: 0.044379 | Val Loss: 0.079570

Epoch 370/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.94it/s, loss=0.013]
Epoch 370/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.63it/s]

End of Epoch 370 | Train Loss: 0.051996 | Val Loss: 0.147748

Epoch 371/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0399]
Epoch 371/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.47it/s]

End of Epoch 371 | Train Loss: 0.049134 | Val Loss: 0.169144

Epoch 372/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.05it/s, loss=0.139]
Epoch 372/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.73it/s]

End of Epoch 372 | Train Loss: 0.047822 | Val Loss: 0.102761

Epoch 373/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.0261]
Epoch 373/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.20it/s]

End of Epoch 373 | Train Loss: 0.040062 | Val Loss: 0.077595

Epoch 374/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.0117]
Epoch 374/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.20it/s]

End of Epoch 374 | Train Loss: 0.040697 | Val Loss: 0.154259

Epoch 375/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.31it/s, loss=0.012]
Epoch 375/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.36it/s]

End of Epoch 375 | Train Loss: 0.051911 | Val Loss: 0.062779

Epoch 376/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.22it/s, loss=0.00811]
Epoch 376/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.96it/s]

End of Epoch 376 | Train Loss: 0.047398 | Val Loss: 0.130496

Epoch 377/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.00886]
Epoch 377/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.37it/s]

End of Epoch 377 | Train Loss: 0.044999 | Val Loss: 0.118842

Epoch 378/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.26it/s, loss=0.0079]
Epoch 378/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.65it/s]

End of Epoch 378 | Train Loss: 0.040171 | Val Loss: 0.199885

Epoch 379/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.77it/s, loss=0.00935]
Epoch 379/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.09it/s]

End of Epoch 379 | Train Loss: 0.048486 | Val Loss: 0.066548

Epoch 380/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.00769]
Epoch 380/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.43it/s]

End of Epoch 380 | Train Loss: 0.042046 | Val Loss: 0.123130

Epoch 381/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.00it/s, loss=0.00825]
Epoch 381/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.73it/s]

End of Epoch 381 | Train Loss: 0.041399 | Val Loss: 0.199633

Epoch 382/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.01it/s, loss=0.00761]
Epoch 382/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.36it/s]

End of Epoch 382 | Train Loss: 0.040846 | Val Loss: 0.130256

Epoch 383/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.98it/s, loss=0.0258]
Epoch 383/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.52it/s]

End of Epoch 383 | Train Loss: 0.044326 | Val Loss: 0.131154

Epoch 384/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.0106]
Epoch 384/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.06it/s]

End of Epoch 384 | Train Loss: 0.048674 | Val Loss: 0.064861

Epoch 385/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.00907]
Epoch 385/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.42it/s]

End of Epoch 385 | Train Loss: 0.049615 | Val Loss: 0.078755

Epoch 386/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0112]
Epoch 386/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.31it/s]

End of Epoch 386 | Train Loss: 0.041677 | Val Loss: 0.101073

Epoch 387/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.00792]
Epoch 387/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.83it/s]

End of Epoch 387 | Train Loss: 0.043096 | Val Loss: 0.096566

Epoch 388/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.00957]
Epoch 388/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.61it/s]

End of Epoch 388 | Train Loss: 0.040676 | Val Loss: 0.080998

Epoch 389/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.00931]
Epoch 389/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.21it/s]

End of Epoch 389 | Train Loss: 0.048866 | Val Loss: 0.234215

Epoch 390/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.0111]
Epoch 390/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.49it/s]

End of Epoch 390 | Train Loss: 0.045531 | Val Loss: 0.057418

Epoch 391/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.29it/s, loss=0.00825]
Epoch 391/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.25it/s]

End of Epoch 391 | Train Loss: 0.048225 | Val Loss: 0.099623

Epoch 392/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.30it/s, loss=0.0279]
Epoch 392/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.00it/s]

End of Epoch 392 | Train Loss: 0.040977 | Val Loss: 0.195627

Epoch 393/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.28it/s, loss=0.485]
Epoch 393/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.65it/s]

End of Epoch 393 | Train Loss: 0.054884 | Val Loss: 0.092873

Epoch 394/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.30it/s, loss=0.0104]
Epoch 394/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.36it/s]

End of Epoch 394 | Train Loss: 0.043444 | Val Loss: 0.055184

Epoch 395/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.28it/s, loss=0.0328]
Epoch 395/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.25it/s]

End of Epoch 395 | Train Loss: 0.040636 | Val Loss: 0.124473

Epoch 396/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.29it/s, loss=0.00901]
Epoch 396/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.16it/s]

End of Epoch 396 | Train Loss: 0.040735 | Val Loss: 0.203988

Epoch 397/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.30it/s, loss=0.0713]
Epoch 397/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.75it/s]

End of Epoch 397 | Train Loss: 0.046492 | Val Loss: 0.133330

Epoch 398/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.00782]
Epoch 398/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.99it/s]

End of Epoch 398 | Train Loss: 0.035807 | Val Loss: 0.113649

Epoch 399/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.0102]
Epoch 399/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.18it/s]

End of Epoch 399 | Train Loss: 0.046070 | Val Loss: 0.122419

Epoch 400/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.011]
Epoch 400/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.06it/s]

End of Epoch 400 | Train Loss: 0.049709 | Val Loss: 0.133497

Epoch 401/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.0101]
Epoch 401/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.90it/s]

End of Epoch 401 | Train Loss: 0.038223 | Val Loss: 0.058254

Epoch 402/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00954]
Epoch 402/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.35it/s]

End of Epoch 402 | Train Loss: 0.046499 | Val Loss: 0.145014

Epoch 403/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.0309]
Epoch 403/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.05it/s]

End of Epoch 403 | Train Loss: 0.044122 | Val Loss: 0.081833

Epoch 404/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00848]
Epoch 404/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.03it/s]

End of Epoch 404 | Train Loss: 0.037286 | Val Loss: 0.091164

Epoch 405/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.05it/s, loss=0.00892]
Epoch 405/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.93it/s]

End of Epoch 405 | Train Loss: 0.050338 | Val Loss: 0.193481

Epoch 406/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.00766]
Epoch 406/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.43it/s]

End of Epoch 406 | Train Loss: 0.033735 | Val Loss: 0.118395

Epoch 407/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.017]
Epoch 407/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.62it/s]

End of Epoch 407 | Train Loss: 0.038952 | Val Loss: 0.096956

Epoch 408/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.20it/s, loss=0.00794]
Epoch 408/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.63it/s]

End of Epoch 408 | Train Loss: 0.042959 | Val Loss: 0.126185

Epoch 409/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.011]
Epoch 409/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.06it/s]

End of Epoch 409 | Train Loss: 0.049784 | Val Loss: 0.144268

Epoch 410/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.30it/s, loss=0.0114]
Epoch 410/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.27it/s]

End of Epoch 410 | Train Loss: 0.038742 | Val Loss: 0.210941

Epoch 411/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0172]
Epoch 411/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.68it/s]

End of Epoch 411 | Train Loss: 0.042904 | Val Loss: 0.093802

Epoch 412/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0191]
Epoch 412/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.17it/s]

End of Epoch 412 | Train Loss: 0.042141 | Val Loss: 0.127439

Epoch 413/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0136]
Epoch 413/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.18it/s]

End of Epoch 413 | Train Loss: 0.043339 | Val Loss: 0.117766

Epoch 414/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.0082]
Epoch 414/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.53it/s]

End of Epoch 414 | Train Loss: 0.047470 | Val Loss: 0.133787

Epoch 415/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.00959]
Epoch 415/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.44it/s]

End of Epoch 415 | Train Loss: 0.044234 | Val Loss: 0.091497

Epoch 416/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.94it/s, loss=0.00802]
Epoch 416/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.23it/s]

End of Epoch 416 | Train Loss: 0.045827 | Val Loss: 0.106123

Epoch 417/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0495]
Epoch 417/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.17it/s]

End of Epoch 417 | Train Loss: 0.041826 | Val Loss: 0.179314

Epoch 418/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.00968]
Epoch 418/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.03it/s]

End of Epoch 418 | Train Loss: 0.037136 | Val Loss: 0.108908

Epoch 419/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0203]
Epoch 419/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.51it/s]

End of Epoch 419 | Train Loss: 0.036646 | Val Loss: 0.197233

Epoch 420/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.39it/s, loss=0.00893]
Epoch 420/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.71it/s]

End of Epoch 420 | Train Loss: 0.040728 | Val Loss: 0.050973

Epoch 421/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.153]
Epoch 421/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.60it/s]

End of Epoch 421 | Train Loss: 0.042922 | Val Loss: 0.090950

Epoch 422/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00996]
Epoch 422/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.64it/s]

End of Epoch 422 | Train Loss: 0.049964 | Val Loss: 0.147412

Epoch 423/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.00705]
Epoch 423/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.49it/s]

End of Epoch 423 | Train Loss: 0.037780 | Val Loss: 0.068035

Epoch 424/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.00899]
Epoch 424/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.90it/s]

End of Epoch 424 | Train Loss: 0.030878 | Val Loss: 0.066264

Epoch 425/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.85it/s, loss=0.0102]
Epoch 425/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.63it/s]

End of Epoch 425 | Train Loss: 0.035596 | Val Loss: 0.202445

Epoch 426/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.00926]
Epoch 426/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.94it/s]

End of Epoch 426 | Train Loss: 0.044659 | Val Loss: 0.118802

Epoch 427/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.76it/s, loss=0.0167]
Epoch 427/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.24it/s]

End of Epoch 427 | Train Loss: 0.045120 | Val Loss: 0.033963

Epoch 428/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0216]
Epoch 428/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.55it/s]

End of Epoch 428 | Train Loss: 0.036377 | Val Loss: 0.065202

Epoch 429/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.00817]
Epoch 429/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.03it/s]

End of Epoch 429 | Train Loss: 0.047682 | Val Loss: 0.157975

Epoch 430/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.78it/s, loss=0.262]
Epoch 430/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.47it/s]

End of Epoch 430 | Train Loss: 0.040729 | Val Loss: 0.053417

Epoch 431/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.357]
Epoch 431/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.05it/s]

End of Epoch 431 | Train Loss: 0.041143 | Val Loss: 0.086559

Epoch 432/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0279]
Epoch 432/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.89it/s]

End of Epoch 432 | Train Loss: 0.046215 | Val Loss: 0.061661

Epoch 433/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.94it/s, loss=0.0114]
Epoch 433/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.35it/s]

End of Epoch 433 | Train Loss: 0.046773 | Val Loss: 0.163620

Epoch 434/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.00867]
Epoch 434/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.19it/s]

End of Epoch 434 | Train Loss: 0.043826 | Val Loss: 0.068270

Epoch 435/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.0137]
Epoch 435/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.35it/s]

End of Epoch 435 | Train Loss: 0.050050 | Val Loss: 0.068694

Epoch 436/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.00791]
Epoch 436/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.22it/s]

End of Epoch 436 | Train Loss: 0.051382 | Val Loss: 0.154494

Epoch 437/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.19it/s, loss=0.00732]
Epoch 437/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.69it/s]

End of Epoch 437 | Train Loss: 0.034483 | Val Loss: 0.097110

Epoch 438/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.0129]
Epoch 438/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.09it/s]

End of Epoch 438 | Train Loss: 0.039195 | Val Loss: 0.255326

Epoch 439/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.01]
Epoch 439/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.82it/s]

End of Epoch 439 | Train Loss: 0.039606 | Val Loss: 0.151876

Epoch 440/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.21it/s, loss=0.00978]
Epoch 440/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.95it/s]

End of Epoch 440 | Train Loss: 0.037772 | Val Loss: 0.068400

Epoch 441/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.22it/s, loss=0.00804]
Epoch 441/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.73it/s]

End of Epoch 441 | Train Loss: 0.038396 | Val Loss: 0.117439

Epoch 442/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.21it/s, loss=0.0079]
Epoch 442/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.14it/s]

End of Epoch 442 | Train Loss: 0.040797 | Val Loss: 0.104143

Epoch 443/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.19it/s, loss=0.0088]
Epoch 443/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.79it/s]

End of Epoch 443 | Train Loss: 0.041012 | Val Loss: 0.094801

Epoch 444/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.21it/s, loss=0.00709]
Epoch 444/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.00it/s]

End of Epoch 444 | Train Loss: 0.042687 | Val Loss: 0.116889

Epoch 445/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.35it/s, loss=0.0148]
Epoch 445/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.46it/s]

End of Epoch 445 | Train Loss: 0.037830 | Val Loss: 0.097961

Epoch 446/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.33it/s, loss=0.00899]
Epoch 446/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.98it/s]

End of Epoch 446 | Train Loss: 0.040766 | Val Loss: 0.084750

Epoch 447/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.34it/s, loss=0.0127]
Epoch 447/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.38it/s]

End of Epoch 447 | Train Loss: 0.044168 | Val Loss: 0.139618

Epoch 448/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.35it/s, loss=0.00961]
Epoch 448/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.83it/s]

End of Epoch 448 | Train Loss: 0.031958 | Val Loss: 0.155294

Epoch 449/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.22it/s, loss=0.051]
Epoch 449/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.04it/s]

End of Epoch 449 | Train Loss: 0.040718 | Val Loss: 0.181421

Epoch 450/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.21it/s, loss=0.0246]
Epoch 450/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.31it/s]

End of Epoch 450 | Train Loss: 0.036399 | Val Loss: 0.039698

Epoch 451/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.0092]
Epoch 451/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.81it/s]

End of Epoch 451 | Train Loss: 0.039611 | Val Loss: 0.051587

Epoch 452/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.00823]
Epoch 452/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.94it/s]

End of Epoch 452 | Train Loss: 0.036051 | Val Loss: 0.097678

Epoch 453/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.04it/s, loss=0.0111]
Epoch 453/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.03it/s]

End of Epoch 453 | Train Loss: 0.035491 | Val Loss: 0.125962

Epoch 454/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.00865]
Epoch 454/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.94it/s]

End of Epoch 454 | Train Loss: 0.045840 | Val Loss: 0.090855

Epoch 455/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.0116]
Epoch 455/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.40it/s]

End of Epoch 455 | Train Loss: 0.037462 | Val Loss: 0.125384

Epoch 456/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.00968]
Epoch 456/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.62it/s]

End of Epoch 456 | Train Loss: 0.037052 | Val Loss: 0.064417

Epoch 457/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.30it/s, loss=0.0127]
Epoch 457/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.48it/s]

End of Epoch 457 | Train Loss: 0.041138 | Val Loss: 0.037456

Epoch 458/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.31it/s, loss=0.00914]
Epoch 458/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.71it/s]

End of Epoch 458 | Train Loss: 0.036107 | Val Loss: 0.070038

Epoch 459/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.233]
Epoch 459/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.94it/s]

End of Epoch 459 | Train Loss: 0.034012 | Val Loss: 0.072594

Epoch 460/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00801]
Epoch 460/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.39it/s]

End of Epoch 460 | Train Loss: 0.042271 | Val Loss: 0.187668

Epoch 461/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.00923]
Epoch 461/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.08it/s]

End of Epoch 461 | Train Loss: 0.032399 | Val Loss: 0.168136

Epoch 462/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.0098]
Epoch 462/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.54it/s]

End of Epoch 462 | Train Loss: 0.038533 | Val Loss: 0.088864

Epoch 463/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00994]
Epoch 463/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.66it/s]

End of Epoch 463 | Train Loss: 0.041438 | Val Loss: 0.102261

Epoch 464/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.00716]
Epoch 464/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.40it/s]

End of Epoch 464 | Train Loss: 0.037470 | Val Loss: 0.248982

Epoch 465/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.88it/s, loss=0.0151]
Epoch 465/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.12it/s]

End of Epoch 465 | Train Loss: 0.031694 | Val Loss: 0.140267

Epoch 466/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.0724]
Epoch 466/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.31it/s]

End of Epoch 466 | Train Loss: 0.043190 | Val Loss: 0.130312

Epoch 467/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.18it/s, loss=0.0112]
Epoch 467/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.04it/s]

End of Epoch 467 | Train Loss: 0.036647 | Val Loss: 0.177719

Epoch 468/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.26it/s, loss=0.0104]
Epoch 468/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.33it/s]

End of Epoch 468 | Train Loss: 0.043697 | Val Loss: 0.184481

Epoch 469/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.22it/s, loss=0.0245]
Epoch 469/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.33it/s]

End of Epoch 469 | Train Loss: 0.031753 | Val Loss: 0.043491

Epoch 470/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0865]
Epoch 470/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.50it/s]

End of Epoch 470 | Train Loss: 0.045392 | Val Loss: 0.136199

Epoch 471/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.00653]
Epoch 471/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.12it/s]

End of Epoch 471 | Train Loss: 0.040744 | Val Loss: 0.193142

Epoch 472/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.45]
Epoch 472/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.69it/s]

End of Epoch 472 | Train Loss: 0.036542 | Val Loss: 0.154931

Epoch 473/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.205]
Epoch 473/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.86it/s]

End of Epoch 473 | Train Loss: 0.042502 | Val Loss: 0.056781

Epoch 474/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.00874]
Epoch 474/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.46it/s]

End of Epoch 474 | Train Loss: 0.041840 | Val Loss: 0.096960

Epoch 475/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.0115]
Epoch 475/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.81it/s]

End of Epoch 475 | Train Loss: 0.030313 | Val Loss: 0.057532

Epoch 476/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0158]
Epoch 476/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.16it/s]

End of Epoch 476 | Train Loss: 0.035648 | Val Loss: 0.067531

Epoch 477/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.04it/s, loss=0.0104]
Epoch 477/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.96it/s]

End of Epoch 477 | Train Loss: 0.036376 | Val Loss: 0.053359

Epoch 478/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.05it/s, loss=0.0134]
Epoch 478/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.26it/s]

End of Epoch 478 | Train Loss: 0.038543 | Val Loss: 0.130379

Epoch 479/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.80it/s, loss=0.00751]
Epoch 479/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.16it/s]

End of Epoch 479 | Train Loss: 0.042838 | Val Loss: 0.122876

Epoch 480/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.00945]
Epoch 480/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.20it/s]

End of Epoch 480 | Train Loss: 0.038562 | Val Loss: 0.222575

Epoch 481/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.00928]
Epoch 481/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.66it/s]

End of Epoch 481 | Train Loss: 0.036974 | Val Loss: 0.095810

Epoch 482/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0203]
Epoch 482/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.81it/s]

End of Epoch 482 | Train Loss: 0.037952 | Val Loss: 0.066171

Epoch 483/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.00it/s, loss=0.00891]
Epoch 483/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.29it/s]

End of Epoch 483 | Train Loss: 0.035229 | Val Loss: 0.131589

Epoch 484/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0509]
Epoch 484/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.79it/s]

End of Epoch 484 | Train Loss: 0.046353 | Val Loss: 0.151809

Epoch 485/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.00954]
Epoch 485/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.16it/s]

End of Epoch 485 | Train Loss: 0.033838 | Val Loss: 0.020872
New Best Model Saved (Val Loss: 0.020872)

Epoch 486/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.87it/s, loss=0.0074]
Epoch 486/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.64it/s]

End of Epoch 486 | Train Loss: 0.031865 | Val Loss: 0.121586

Epoch 487/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.05it/s, loss=0.00776]
Epoch 487/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.05it/s]

End of Epoch 487 | Train Loss: 0.043741 | Val Loss: 0.080584

Epoch 488/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.23it/s, loss=0.00988]
Epoch 488/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.86it/s]

End of Epoch 488 | Train Loss: 0.036136 | Val Loss: 0.313996

Epoch 489/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.20it/s, loss=0.0175]
Epoch 489/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.54it/s]

End of Epoch 489 | Train Loss: 0.037995 | Val Loss: 0.196106

Epoch 490/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.00733]
Epoch 490/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.32it/s]

End of Epoch 490 | Train Loss: 0.038477 | Val Loss: 0.129326

Epoch 491/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.0148]
Epoch 491/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.94it/s]

End of Epoch 491 | Train Loss: 0.029736 | Val Loss: 0.063562

Epoch 492/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.17it/s, loss=0.00856]
Epoch 492/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 81.64it/s]

End of Epoch 492 | Train Loss: 0.033969 | Val Loss: 0.135829

Epoch 493/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.00it/s, loss=0.00985]
Epoch 493/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 81.44it/s]

End of Epoch 493 | Train Loss: 0.038542 | Val Loss: 0.215746

Epoch 494/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.27it/s, loss=0.0148]
Epoch 494/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.62it/s]

End of Epoch 494 | Train Loss: 0.040997 | Val Loss: 0.040962

Epoch 495/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.0098]
Epoch 495/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.02it/s]

End of Epoch 495 | Train Loss: 0.038617 | Val Loss: 0.056542

Epoch 496/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.52it/s, loss=0.00936]
Epoch 496/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 80.99it/s]

End of Epoch 496 | Train Loss: 0.039910 | Val Loss: 0.151115

Epoch 497/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.18it/s, loss=0.0173]
Epoch 497/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 80.99it/s]

End of Epoch 497 | Train Loss: 0.044931 | Val Loss: 0.062822

Epoch 498/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.08it/s, loss=0.026]
Epoch 498/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 79.64it/s]

End of Epoch 498 | Train Loss: 0.033197 | Val Loss: 0.129558

Epoch 499/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00659]
Epoch 499/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.50it/s]

End of Epoch 499 | Train Loss: 0.038407 | Val Loss: 0.123292

Epoch 500/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.76it/s, loss=0.0089]
Epoch 500/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 77.68it/s]

End of Epoch 500 | Train Loss: 0.049695 | Val Loss: 0.025334

Epoch 501/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.29it/s, loss=0.0274]
Epoch 501/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.09it/s]

End of Epoch 501 | Train Loss: 0.034037 | Val Loss: 0.097249

Epoch 502/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0965]
Epoch 502/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.76it/s]

End of Epoch 502 | Train Loss: 0.041522 | Val Loss: 0.036900

Epoch 503/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.59it/s, loss=0.00834]
Epoch 503/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.40it/s]

End of Epoch 503 | Train Loss: 0.045236 | Val Loss: 0.059274

Epoch 504/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.037]
Epoch 504/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.21it/s]

End of Epoch 504 | Train Loss: 0.030234 | Val Loss: 0.169422

Epoch 505/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0177]
Epoch 505/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.54it/s]

End of Epoch 505 | Train Loss: 0.031915 | Val Loss: 0.146327

Epoch 506/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.00807]
Epoch 506/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.67it/s]

End of Epoch 506 | Train Loss: 0.030661 | Val Loss: 0.122292

Epoch 507/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.00689]
Epoch 507/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.48it/s]

End of Epoch 507 | Train Loss: 0.035341 | Val Loss: 0.111437

Epoch 508/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.56it/s, loss=0.0384]
Epoch 508/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.60it/s]

End of Epoch 508 | Train Loss: 0.038741 | Val Loss: 0.164785

Epoch 509/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.45it/s, loss=0.0295]
Epoch 509/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.54it/s]

End of Epoch 509 | Train Loss: 0.030191 | Val Loss: 0.174273

Epoch 510/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.45it/s, loss=0.0264]
Epoch 510/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.23it/s]

End of Epoch 510 | Train Loss: 0.033088 | Val Loss: 0.060230

Epoch 511/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0369]
Epoch 511/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.81it/s]

End of Epoch 511 | Train Loss: 0.036994 | Val Loss: 0.152012

Epoch 512/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.00822]
Epoch 512/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.46it/s]

End of Epoch 512 | Train Loss: 0.031764 | Val Loss: 0.027052

Epoch 513/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00951]
Epoch 513/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.00it/s]

End of Epoch 513 | Train Loss: 0.033253 | Val Loss: 0.339325

Epoch 514/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.00728]
Epoch 514/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.60it/s]

End of Epoch 514 | Train Loss: 0.029798 | Val Loss: 0.070409

Epoch 515/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.123]
Epoch 515/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.64it/s]

End of Epoch 515 | Train Loss: 0.040618 | Val Loss: 0.070989

Epoch 516/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.0073]
Epoch 516/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.04it/s]

End of Epoch 516 | Train Loss: 0.031821 | Val Loss: 0.188861

Epoch 517/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.0269]
Epoch 517/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.33it/s]

End of Epoch 517 | Train Loss: 0.040774 | Val Loss: 0.124574

Epoch 518/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.0127]
Epoch 518/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.42it/s]

End of Epoch 518 | Train Loss: 0.033820 | Val Loss: 0.135074

Epoch 519/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.00625]
Epoch 519/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.28it/s]

End of Epoch 519 | Train Loss: 0.033686 | Val Loss: 0.098608

Epoch 520/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.02it/s, loss=0.00782]
Epoch 520/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.62it/s]

End of Epoch 520 | Train Loss: 0.035127 | Val Loss: 0.042829

Epoch 521/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.19it/s, loss=0.00809]
Epoch 521/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.35it/s]

End of Epoch 521 | Train Loss: 0.035562 | Val Loss: 0.163885

Epoch 522/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.00726]
Epoch 522/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.88it/s]

End of Epoch 522 | Train Loss: 0.038347 | Val Loss: 0.157830

Epoch 523/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.115]
Epoch 523/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.71it/s]

End of Epoch 523 | Train Loss: 0.034735 | Val Loss: 0.188554

Epoch 524/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.00743]
Epoch 524/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.36it/s]

End of Epoch 524 | Train Loss: 0.037649 | Val Loss: 0.184929

Epoch 525/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.70it/s, loss=0.00959]
Epoch 525/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.11it/s]

End of Epoch 525 | Train Loss: 0.040330 | Val Loss: 0.056579

Epoch 526/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00709]
Epoch 526/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.71it/s]

End of Epoch 526 | Train Loss: 0.030771 | Val Loss: 0.100391

Epoch 527/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.0125]
Epoch 527/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.90it/s]

End of Epoch 527 | Train Loss: 0.035300 | Val Loss: 0.158852

Epoch 528/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.46it/s, loss=0.00701]
Epoch 528/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.34it/s]

End of Epoch 528 | Train Loss: 0.043230 | Val Loss: 0.080682

Epoch 529/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.36it/s, loss=0.00731]
Epoch 529/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 81.07it/s]

End of Epoch 529 | Train Loss: 0.032043 | Val Loss: 0.080668

Epoch 530/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 13.35it/s, loss=0.00797]
Epoch 530/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.30it/s]

End of Epoch 530 | Train Loss: 0.035560 | Val Loss: 0.221219

Epoch 531/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 13.47it/s, loss=0.00663]
Epoch 531/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 95.88it/s]

End of Epoch 531 | Train Loss: 0.030549 | Val Loss: 0.209960

Epoch 532/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.47it/s, loss=0.00689]
Epoch 532/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.84it/s]

End of Epoch 532 | Train Loss: 0.037329 | Val Loss: 0.069245

Epoch 533/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.45it/s, loss=0.0404]
Epoch 533/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.12it/s]

End of Epoch 533 | Train Loss: 0.038051 | Val Loss: 0.249615

Epoch 534/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.41it/s, loss=0.00814]
Epoch 534/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.25it/s]

End of Epoch 534 | Train Loss: 0.039176 | Val Loss: 0.101914

Epoch 535/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.0101]
Epoch 535/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.01it/s]

End of Epoch 535 | Train Loss: 0.036003 | Val Loss: 0.220632

Epoch 536/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.42it/s, loss=0.00762]
Epoch 536/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.74it/s]

End of Epoch 536 | Train Loss: 0.033982 | Val Loss: 0.043593

Epoch 537/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.46it/s, loss=0.00692]
Epoch 537/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.08it/s]

End of Epoch 537 | Train Loss: 0.035980 | Val Loss: 0.110424

Epoch 538/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.53it/s, loss=0.0534]
Epoch 538/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.64it/s]

End of Epoch 538 | Train Loss: 0.041810 | Val Loss: 0.215686

Epoch 539/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.00604]
Epoch 539/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.69it/s]

End of Epoch 539 | Train Loss: 0.034437 | Val Loss: 0.078923

Epoch 540/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.034]
Epoch 540/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.61it/s]

End of Epoch 540 | Train Loss: 0.036109 | Val Loss: 0.166260

Epoch 541/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.77it/s, loss=0.00758]
Epoch 541/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.71it/s]

End of Epoch 541 | Train Loss: 0.040189 | Val Loss: 0.111233

Epoch 542/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.00797]
Epoch 542/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.92it/s]

End of Epoch 542 | Train Loss: 0.030304 | Val Loss: 0.140437

Epoch 543/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.65it/s, loss=0.00989]
Epoch 543/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.39it/s]

End of Epoch 543 | Train Loss: 0.036675 | Val Loss: 0.224833

Epoch 544/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0157]
Epoch 544/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.59it/s]

End of Epoch 544 | Train Loss: 0.028632 | Val Loss: 0.110691

Epoch 545/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.0067]
Epoch 545/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.06it/s]

End of Epoch 545 | Train Loss: 0.036875 | Val Loss: 0.119670

Epoch 546/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.53it/s, loss=0.365]
Epoch 546/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.32it/s]

End of Epoch 546 | Train Loss: 0.036887 | Val Loss: 0.086018

Epoch 547/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.55it/s, loss=0.00759]
Epoch 547/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.37it/s]

End of Epoch 547 | Train Loss: 0.037987 | Val Loss: 0.061476

Epoch 548/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.54it/s, loss=0.00842]
Epoch 548/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.21it/s]

End of Epoch 548 | Train Loss: 0.026509 | Val Loss: 0.074451

Epoch 549/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.53it/s, loss=0.0186]
Epoch 549/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.42it/s]

End of Epoch 549 | Train Loss: 0.032631 | Val Loss: 0.154228

Epoch 550/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.51it/s, loss=0.00828]
Epoch 550/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.82it/s]

End of Epoch 550 | Train Loss: 0.040094 | Val Loss: 0.097235

Epoch 551/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.00579]
Epoch 551/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.90it/s]

End of Epoch 551 | Train Loss: 0.024622 | Val Loss: 0.073296

Epoch 552/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.00756]
Epoch 552/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.93it/s]

End of Epoch 552 | Train Loss: 0.034585 | Val Loss: 0.240989

Epoch 553/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.48it/s, loss=0.00779]
Epoch 553/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.24it/s]

End of Epoch 553 | Train Loss: 0.035149 | Val Loss: 0.235967

Epoch 554/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.43it/s, loss=0.011]
Epoch 554/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.10it/s]

End of Epoch 554 | Train Loss: 0.031614 | Val Loss: 0.043144

Epoch 555/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.00629]
Epoch 555/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.11it/s]

End of Epoch 555 | Train Loss: 0.045906 | Val Loss: 0.036085

Epoch 556/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.58it/s, loss=0.00665]
Epoch 556/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.47it/s]

End of Epoch 556 | Train Loss: 0.028525 | Val Loss: 0.072109

Epoch 557/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.48it/s, loss=0.0103]
Epoch 557/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.49it/s]

End of Epoch 557 | Train Loss: 0.032111 | Val Loss: 0.145653

Epoch 558/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.35it/s, loss=0.0194]
Epoch 558/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.93it/s]

End of Epoch 558 | Train Loss: 0.032090 | Val Loss: 0.181825

Epoch 559/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.60it/s, loss=0.0413]
Epoch 559/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.88it/s]

End of Epoch 559 | Train Loss: 0.034295 | Val Loss: 0.114605

Epoch 560/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.67it/s, loss=0.00844]
Epoch 560/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.64it/s]

End of Epoch 560 | Train Loss: 0.038891 | Val Loss: 0.088685

Epoch 561/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.0844]
Epoch 561/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 96.45it/s]

End of Epoch 561 | Train Loss: 0.034053 | Val Loss: 0.074071

Epoch 562/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.68it/s, loss=0.00636]
Epoch 562/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.20it/s]

End of Epoch 562 | Train Loss: 0.040014 | Val Loss: 0.065954

Epoch 563/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.69it/s, loss=0.00787]
Epoch 563/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 94.03it/s]

End of Epoch 563 | Train Loss: 0.042992 | Val Loss: 0.071679

Epoch 564/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.00766]
Epoch 564/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.62it/s]

End of Epoch 564 | Train Loss: 0.031889 | Val Loss: 0.060253

Epoch 565/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.62it/s, loss=0.00738]
Epoch 565/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.56it/s]

End of Epoch 565 | Train Loss: 0.028724 | Val Loss: 0.119496

Epoch 566/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.00815]
Epoch 566/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.73it/s]

End of Epoch 566 | Train Loss: 0.029806 | Val Loss: 0.115185

Epoch 567/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.64it/s, loss=0.00765]
Epoch 567/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.98it/s]

End of Epoch 567 | Train Loss: 0.035276 | Val Loss: 0.069842

Epoch 568/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.906]
Epoch 568/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.32it/s]

End of Epoch 568 | Train Loss: 0.043983 | Val Loss: 0.173857

Epoch 569/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.63it/s, loss=0.0162]
Epoch 569/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.92it/s]

End of Epoch 569 | Train Loss: 0.037441 | Val Loss: 0.091372

Epoch 570/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.66it/s, loss=0.0514]
Epoch 570/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.14it/s]

End of Epoch 570 | Train Loss: 0.034685 | Val Loss: 0.125097

Epoch 571/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.53it/s, loss=0.0133]
Epoch 571/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.33it/s]

End of Epoch 571 | Train Loss: 0.041649 | Val Loss: 0.090563

Epoch 572/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.52it/s, loss=0.0068]
Epoch 572/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.21it/s]

End of Epoch 572 | Train Loss: 0.034115 | Val Loss: 0.167392

Epoch 573/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.52it/s, loss=0.00806]
Epoch 573/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.28it/s]

End of Epoch 573 | Train Loss: 0.034022 | Val Loss: 0.157518

Epoch 574/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.50it/s, loss=0.00731]
Epoch 574/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.09it/s]

End of Epoch 574 | Train Loss: 0.037248 | Val Loss: 0.109316

Epoch 575/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.0511]
Epoch 575/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.37it/s]

End of Epoch 575 | Train Loss: 0.040022 | Val Loss: 0.179880

Epoch 576/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.00705]
Epoch 576/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.97it/s]

End of Epoch 576 | Train Loss: 0.033061 | Val Loss: 0.231163

Epoch 577/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.97it/s, loss=0.017]
Epoch 577/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.87it/s]

End of Epoch 577 | Train Loss: 0.032254 | Val Loss: 0.185462

Epoch 578/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.0171]
Epoch 578/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.13it/s]

End of Epoch 578 | Train Loss: 0.030243 | Val Loss: 0.029056

Epoch 579/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.00707]
Epoch 579/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.84it/s]

End of Epoch 579 | Train Loss: 0.035327 | Val Loss: 0.140358

Epoch 580/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.00672]
Epoch 580/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.91it/s]

End of Epoch 580 | Train Loss: 0.034131 | Val Loss: 0.232498

Epoch 581/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.00808]
Epoch 581/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.80it/s]

End of Epoch 581 | Train Loss: 0.027367 | Val Loss: 0.132947

Epoch 582/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.00682]
Epoch 582/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.44it/s]

End of Epoch 582 | Train Loss: 0.031847 | Val Loss: 0.138784

Epoch 583/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.27it/s, loss=0.00655]
Epoch 583/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.64it/s]

End of Epoch 583 | Train Loss: 0.034777 | Val Loss: 0.176851

Epoch 584/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.25it/s, loss=0.0165]
Epoch 584/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.76it/s]

End of Epoch 584 | Train Loss: 0.034856 | Val Loss: 0.170405

Epoch 585/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.28it/s, loss=0.00749]
Epoch 585/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.81it/s]

End of Epoch 585 | Train Loss: 0.029754 | Val Loss: 0.149201

Epoch 586/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.0366]
Epoch 586/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.83it/s]

End of Epoch 586 | Train Loss: 0.027418 | Val Loss: 0.165011

Epoch 587/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00864]
Epoch 587/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.33it/s]

End of Epoch 587 | Train Loss: 0.032697 | Val Loss: 0.123002

Epoch 588/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.108]
Epoch 588/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.83it/s]

End of Epoch 588 | Train Loss: 0.029543 | Val Loss: 0.130144

Epoch 589/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.0489]
Epoch 589/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.82it/s]

End of Epoch 589 | Train Loss: 0.036079 | Val Loss: 0.056198

Epoch 590/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.26it/s, loss=0.00882]
Epoch 590/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.92it/s]

End of Epoch 590 | Train Loss: 0.031511 | Val Loss: 0.077725

Epoch 591/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.18it/s, loss=0.00681]
Epoch 591/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.58it/s]

End of Epoch 591 | Train Loss: 0.028838 | Val Loss: 0.086177

Epoch 592/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0153]
Epoch 592/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.92it/s]

End of Epoch 592 | Train Loss: 0.030476 | Val Loss: 0.260197

Epoch 593/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.0107]
Epoch 593/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.52it/s]

End of Epoch 593 | Train Loss: 0.030681 | Val Loss: 0.268442

Epoch 594/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.00769]
Epoch 594/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.49it/s]

End of Epoch 594 | Train Loss: 0.032430 | Val Loss: 0.195078

Epoch 595/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.00785]
Epoch 595/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.84it/s]

End of Epoch 595 | Train Loss: 0.031819 | Val Loss: 0.055837

Epoch 596/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.0176]
Epoch 596/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.15it/s]

End of Epoch 596 | Train Loss: 0.033042 | Val Loss: 0.199019

Epoch 597/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.0293]
Epoch 597/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.60it/s]

End of Epoch 597 | Train Loss: 0.034484 | Val Loss: 0.376958

Epoch 598/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.00it/s, loss=0.0115]
Epoch 598/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.79it/s]

End of Epoch 598 | Train Loss: 0.035102 | Val Loss: 0.113783

Epoch 599/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.93it/s, loss=0.0187]
Epoch 599/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.90it/s]

End of Epoch 599 | Train Loss: 0.028168 | Val Loss: 0.135109

Epoch 600/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.00601]
Epoch 600/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.48it/s]

End of Epoch 600 | Train Loss: 0.035143 | Val Loss: 0.164723

Epoch 601/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00624]
Epoch 601/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.55it/s]

End of Epoch 601 | Train Loss: 0.035446 | Val Loss: 0.139784

Epoch 602/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.00739]
Epoch 602/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.01it/s]

End of Epoch 602 | Train Loss: 0.027691 | Val Loss: 0.221622

Epoch 603/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.006]
Epoch 603/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.57it/s]

End of Epoch 603 | Train Loss: 0.033596 | Val Loss: 0.232379

Epoch 604/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00522]
Epoch 604/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.13it/s]

End of Epoch 604 | Train Loss: 0.046428 | Val Loss: 0.105090

Epoch 605/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.0224]
Epoch 605/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.97it/s]

End of Epoch 605 | Train Loss: 0.036462 | Val Loss: 0.112350

Epoch 606/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00859]
Epoch 606/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.14it/s]

End of Epoch 606 | Train Loss: 0.037545 | Val Loss: 0.128782

Epoch 607/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.86it/s, loss=0.0519]
Epoch 607/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.84it/s]

End of Epoch 607 | Train Loss: 0.035822 | Val Loss: 0.206513

Epoch 608/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.90it/s, loss=0.00889]
Epoch 608/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.60it/s]

End of Epoch 608 | Train Loss: 0.029163 | Val Loss: 0.090764

Epoch 609/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00845]
Epoch 609/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.69it/s]

End of Epoch 609 | Train Loss: 0.031300 | Val Loss: 0.106960

Epoch 610/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.91it/s, loss=0.00832]
Epoch 610/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.26it/s]

End of Epoch 610 | Train Loss: 0.028049 | Val Loss: 0.076719

Epoch 611/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.24it/s, loss=0.0116]
Epoch 611/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 81.50it/s]

End of Epoch 611 | Train Loss: 0.032215 | Val Loss: 0.142265

Epoch 612/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.04it/s, loss=0.00615]
Epoch 612/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 78.96it/s]

End of Epoch 612 | Train Loss: 0.035573 | Val Loss: 0.276589

Epoch 613/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.36it/s, loss=0.00707]
Epoch 613/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.53it/s]

End of Epoch 613 | Train Loss: 0.029253 | Val Loss: 0.240884

Epoch 614/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.0319]
Epoch 614/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.99it/s]

End of Epoch 614 | Train Loss: 0.032736 | Val Loss: 0.186145

Epoch 615/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.0126]
Epoch 615/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.65it/s]

End of Epoch 615 | Train Loss: 0.038902 | Val Loss: 0.090318

Epoch 616/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.09it/s, loss=0.0104]
Epoch 616/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.79it/s]

End of Epoch 616 | Train Loss: 0.031640 | Val Loss: 0.262603

Epoch 617/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.99it/s, loss=0.00622]
Epoch 617/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.92it/s]

End of Epoch 617 | Train Loss: 0.031720 | Val Loss: 0.119778

Epoch 618/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.07it/s, loss=0.00651]
Epoch 618/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.47it/s]

End of Epoch 618 | Train Loss: 0.033679 | Val Loss: 0.134723

Epoch 619/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.12it/s, loss=0.0121]
Epoch 619/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.02it/s]

End of Epoch 619 | Train Loss: 0.031884 | Val Loss: 0.086286

Epoch 620/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0511]
Epoch 620/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.90it/s]

End of Epoch 620 | Train Loss: 0.033020 | Val Loss: 0.173470

Epoch 621/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.94it/s, loss=0.00674]
Epoch 621/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.47it/s]

End of Epoch 621 | Train Loss: 0.032775 | Val Loss: 0.073766

Epoch 622/1000 [Train]: 100%|██████████| 90/90 [00:06<00:00, 14.83it/s, loss=0.00686]
Epoch 622/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 82.10it/s]

End of Epoch 622 | Train Loss: 0.034453 | Val Loss: 0.131674

Epoch 623/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.06it/s, loss=0.2]
Epoch 623/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.54it/s]

End of Epoch 623 | Train Loss: 0.037782 | Val Loss: 0.077488

Epoch 624/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.41it/s, loss=0.33]
Epoch 624/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 81.76it/s]

End of Epoch 624 | Train Loss: 0.040920 | Val Loss: 0.280922

Epoch 625/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.14it/s, loss=0.0072]
Epoch 625/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.71it/s]

End of Epoch 625 | Train Loss: 0.037368 | Val Loss: 0.250327

Epoch 626/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.19it/s, loss=0.011]
Epoch 626/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.79it/s]

End of Epoch 626 | Train Loss: 0.031311 | Val Loss: 0.082777

Epoch 627/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.0123]
Epoch 627/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.53it/s]

End of Epoch 627 | Train Loss: 0.028592 | Val Loss: 0.155580

Epoch 628/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.18it/s, loss=0.00797]
Epoch 628/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 101.07it/s]

End of Epoch 628 | Train Loss: 0.031977 | Val Loss: 0.126434

Epoch 629/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.73it/s, loss=0.044]
Epoch 629/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.30it/s]

End of Epoch 629 | Train Loss: 0.034807 | Val Loss: 0.079752

Epoch 630/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.89it/s, loss=0.00691]
Epoch 630/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.83it/s]

End of Epoch 630 | Train Loss: 0.024850 | Val Loss: 0.119690

Epoch 631/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.24it/s, loss=0.0868]
Epoch 631/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.70it/s]

End of Epoch 631 | Train Loss: 0.033339 | Val Loss: 0.080562

Epoch 632/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.15it/s, loss=0.581]
Epoch 632/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.36it/s]

End of Epoch 632 | Train Loss: 0.036900 | Val Loss: 0.181495

Epoch 633/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.13it/s, loss=0.0173]
Epoch 633/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.47it/s]

End of Epoch 633 | Train Loss: 0.032743 | Val Loss: 0.032997

Epoch 634/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.00833]
Epoch 634/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.90it/s]

End of Epoch 634 | Train Loss: 0.033032 | Val Loss: 0.125621

Epoch 635/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.00715]
Epoch 635/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.95it/s]

End of Epoch 635 | Train Loss: 0.036180 | Val Loss: 0.107553

Epoch 636/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.0195]
Epoch 636/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.92it/s]

End of Epoch 636 | Train Loss: 0.033836 | Val Loss: 0.181524

Epoch 637/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.10it/s, loss=0.0218]
Epoch 637/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.49it/s]

End of Epoch 637 | Train Loss: 0.026780 | Val Loss: 0.350571

Epoch 638/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.17it/s, loss=0.0104]
Epoch 638/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.80it/s]

End of Epoch 638 | Train Loss: 0.027268 | Val Loss: 0.195480

Epoch 639/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.08it/s, loss=0.00781]
Epoch 639/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.11it/s]

End of Epoch 639 | Train Loss: 0.034604 | Val Loss: 0.198534

Epoch 640/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.11it/s, loss=0.00631]
Epoch 640/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.78it/s]

End of Epoch 640 | Train Loss: 0.022870 | Val Loss: 0.235759

Epoch 641/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.16it/s, loss=0.00712]
Epoch 641/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.58it/s]

End of Epoch 641 | Train Loss: 0.029999 | Val Loss: 0.082400

Epoch 642/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.27it/s, loss=0.0108]
Epoch 642/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.31it/s]

End of Epoch 642 | Train Loss: 0.030520 | Val Loss: 0.145388

Epoch 643/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.33it/s, loss=0.00642]
Epoch 643/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.70it/s]

End of Epoch 643 | Train Loss: 0.025677 | Val Loss: 0.069719

Epoch 644/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.31it/s, loss=0.00683]
Epoch 644/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.85it/s]

End of Epoch 644 | Train Loss: 0.033932 | Val Loss: 0.155128

Epoch 645/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.14it/s, loss=0.0125]
Epoch 645/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.04it/s]

End of Epoch 645 | Train Loss: 0.036572 | Val Loss: 0.140449

Epoch 646/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.92it/s, loss=0.00613]
Epoch 646/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.01it/s]

End of Epoch 646 | Train Loss: 0.027830 | Val Loss: 0.216273

Epoch 647/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.06it/s, loss=0.00764]
Epoch 647/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 98.47it/s]

End of Epoch 647 | Train Loss: 0.031303 | Val Loss: 0.104664

Epoch 648/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.95it/s, loss=0.0126]
Epoch 648/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 100.01it/s]

End of Epoch 648 | Train Loss: 0.027129 | Val Loss: 0.129652

Epoch 649/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 16.04it/s, loss=0.00594]
Epoch 649/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 99.97it/s]

End of Epoch 649 | Train Loss: 0.032447 | Val Loss: 0.188012

Epoch 650/1000 [Train]: 100%|██████████| 90/90 [00:05<00:00, 15.96it/s, loss=0.00688]
Epoch 650/1000 [Val]: 100%|██████████| 5/5 [00:00<00:00, 97.61it/s]

End of Epoch 650 | Train Loss: 0.026390 | Val Loss: 0.099161

Epoch 651/1000 [Train]:  91%|█████████ | 82/90 [00:05<00:00, 16.10it/s, loss=0.0177]

In [ ]:
batch = next(iter(test_loader))
x_real_raw = batch["x"].to(device).float()      # [32, 64, 14, 1]
cond_raw = batch["x_cond"].to(device).float()   # [32, 64, 14, 6]
B, W, A, F = x_real_raw.shape

# Mask (Logic: 1=known, 0=predict)
mask = torch.ones_like(x_real_raw)
mask[:, -10:, :, :] = 0  # latest 10 Assets 

# Reshape Flat
# x_real: [32, 64, 14, 1] -> [32, 64, 14]
x_start_flat = x_real_raw.view(B, W, -1)

# cond: [32, 64, 14, 6] -> [32, 64, 84]
cond_flat = cond_raw.view(B, W, -1)

# mask: [32, 64, 14, 1] -> [32, 64, 14]
mask_flat = mask.view(B, W, -1)

print(f"x_start_flat: {x_start_flat.shape}\ncond_flat: {cond_flat.shape}\nmask_flat: {mask_flat.shape}")

# Inpaint
diffusion.eval()
with torch.no_grad():
    inpainted_flat = diffusion.sample_inpaint(
        x_cond=cond_flat,
        x_start=x_start_flat,
        mask=mask_flat
    )

# Reshape
# [32, 64, 14] -> [32, 64, 14, 1]
inpainted_final = inpainted_flat.view(B, W, A, F)

print("Inpaint Finished!")

In [ ]:
inpainted_final.shape

In [ ]:
def forward_simulate(steps: int, batch, diffusion: Diffusion):
    device = next(diffusion.parameters()).device
    
    x_real_raw = batch["x"].to(device).float()       # [B, W, A, F]
    cond_raw = batch["x_cond"].to(device).float()    # [B, W, A, Cond_F]

    B, W, A, F = x_real_raw.shape

    # Mask (Logic: 1=known, 0=predict)
    mask = torch.ones_like(x_real_raw)
    if steps > 0:
        mask[:, -steps:, :, :] = 0

    # Flatten
    # [B, W, A, F] -> [B, W, A*F]
    x_start_flat = x_real_raw.view(B, W, -1)
    cond_flat = cond_raw.view(B, W, -1)
    mask_flat = mask.view(B, W, -1)

    # Inpaint Execution
    diffusion.eval()
    with torch.no_grad():
        inpainted_flat = diffusion.sample_inpaint(
            x_cond=cond_flat,
            x_start=x_start_flat,
            mask=mask_flat
        )

    # Unflatten
    # [B, W, A*F] -> [B, W, A, F]
    inpainted_final = inpainted_flat.view(B, W, A, F)

    # Extract Only Predicted Part
    if steps > 0:
        # [B, steps, A, F] (32, steps, 14, 1)
        simulated_part = inpainted_final[:, -steps:, :, :]
    else:
        simulated_part = torch.empty((B, 0, A, F), device=device)

    # inpaint_simulation, ground_truth, simulated_part 
    return inpainted_final, x_real_raw, simulated_part, cond_raw

In [ ]:
inpaint_simulation, ground_truth, simulated_part, x_cond = forward_simulate(steps=sim_steps, batch=batch, diffusion=diffusion)

In [ ]:
simulated_part.shape

In [ ]:
ground_truth.shape

In [ ]:
x_cond.shape

In [ ]:
inspect_data(inpaint_simulation,name='inpaint simulation')
inspect_data(ground_truth,name='ground truth')
inspect_data(ground_truth[:, -sim_steps:, :, :],name='ground truth latest n steps part')
inspect_data(simulated_part,name='simulated part')

In [ ]:
unscaled_inpaint_simulation = inverse_scale_with_cond(inpaint_simulation.cpu().numpy(), x_cond.cpu().numpy() , scaler)
unscaled_ground_truth = inverse_scale_with_cond(ground_truth.cpu().numpy(), x_cond.cpu().numpy() , scaler)
unscaled_simulated_part = inverse_scale_with_cond(simulated_part, x_cond[:, -sim_steps:, :, :].cpu().numpy() , scaler)

inspect_data(unscaled_inpaint_simulation,name='inpaint simulation')
inspect_data(unscaled_ground_truth,name='ground truth')
inspect_data(unscaled_ground_truth[:,-sim_steps:, :, :],name='ground truth at simulate part')
inspect_data(unscaled_simulated_part,name='simulated part')

In [ ]:
def gbm_monte_carlo_simulate(past_log_returns, n_steps, n_samples=100):
    """
    Simulate future prices using Geometric Brownian Motion (GBM)
    Args:
        past_log_returns: [Time, Assets] (numpy array)
        n_steps: steps to sim
        n_samples: n paths to simulate
    """
    # 1. คำนวณ Stats จากข้อมูลในอดีต (batch นี้)
    # mu = drift (แนวโน้ม), sigma = volatility (ความผันผวน)
    mu = np.mean(past_log_returns, axis=0)
    sigma = np.std(past_log_returns, axis=0)
    
    n_assets = past_log_returns.shape[1]
    
    # 2. จำลองอนาคต (Simulate Future Log Returns)
    # ภายใต้สมมติฐาน GBM: Log Return จะเป็น Normal Distribution
    # ret ~ N(mu, sigma)
    
    # สร้าง array เปล่า [Samples, Steps, Assets]
    sim_log_returns = np.random.normal(
        loc=mu, 
        scale=sigma, 
        size=(n_samples, n_steps, n_assets)
    )
            
    return sim_log_returns

In [ ]:
mc_simulations = gbm_monte_carlo_simulate(unscaled_ground_truth[:, :-sim_steps, :, :].squeeze(-1).squeeze(0), sim_steps, num_sims)
# n_sample, n_steps, n_assets
mc_simulations.shape

In [ ]:
type(unscaled_simulated_part)

In [ ]:
# sim_part_df = pd.DataFrame(unscaled_simulated_part[0].squeeze(-1))
# Case Batch size = 1
sim_part_df = pd.DataFrame(unscaled_simulated_part.squeeze(-1).squeeze(0))
sim_part_df

In [ ]:
mc_simulations_df = pd.DataFrame(mc_simulations[0]) 
mc_simulations_df

In [ ]:
# gt_sim_part_df = pd.DataFrame(unscaled_ground_truth[0, -10:, :, :].squeeze(-1))

# Case Batch size = 1
gt_sim_part_df = pd.DataFrame(unscaled_ground_truth[:, -sim_steps:, :, :].squeeze(-1).squeeze(0))
gt_sim_part_df

In [ ]:
plotting.plot_covariance(risk_models.sample_cov(gt_sim_part_df), plot_correlation=True)
plotting.plot_covariance(risk_models.sample_cov(sim_part_df), plot_correlation=True)
plotting.plot_covariance(risk_models.sample_cov(mc_simulations_df), plot_correlation=True)

In [ ]:
batch_expanded = {
    "x": batch["x"].repeat(num_sims, 1, 1, 1),           # [num_sims, 64, 14, 1]
    "x_cond": batch["x_cond"].repeat(num_sims, 1, 1, 1)  # [num_sims, 64, 14, 6]
}


# inpaint_simulation, ground_truth, simulated_part, x_cond
inpaint_final, _, simulated_part, x_cond = forward_simulate(
    steps=sim_steps,
    batch=batch_expanded,
    diffusion=diffusion
)
genai_simulations = simulated_part
genai_simulations.shape

In [ ]:
genai_simulations.shape

In [ ]:
unscaled_genai_simulated = inverse_scale_with_cond(genai_simulations[:, :, : ,:], batch["x_cond"].repeat(num_sims, 1, 1, 1)[:, -sim_steps:, :, :].cpu().numpy() , scaler)
inspect_data(unscaled_genai_simulated,name='GenAI simulations')

In [ ]:
unscaled_genai_simulated[0,:, :, :].squeeze(-1).cumsum(0).shape

In [ ]:
genai_simulations = unscaled_genai_simulated[0].squeeze(-1)
n_steps, n_assets = genai_simulations.shape

for i in range(n_assets):
    plt.plot(genai_simulations[:, i].cumsum(0), label=f"{i}")
plt.legend()
plt.show()

In [ ]:
mc_simulations.shape

In [ ]:
n_sims, n_steps, n_assets = mc_simulations.shape

for i in range(n_assets):
    plt.plot(mc_simulations[0, :, i].cumsum(0), label=f"{i}")
plt.legend()
plt.show()

In [ ]:
inspect_data(unscaled_ground_truth[:,:-10, :, :], name="Ground Truth")

In [ ]:
ground_truth = unscaled_ground_truth[:, -steps_sim:, :, :].squeeze(-1).squeeze(0)
n_obs, n_assets = ground_truth.shape

for i in range(n_assets):
    plt.plot(ground_truth[:, i].cumsum(0), label=f"{i}")
plt.legend()
plt.show()